local addonVersion="1.0.0"
local L=LibStub("AceLocale-3.0"):NewLocale("Holy_Storm_POI","deDE")
if not L then return end
L["TITLE"]="Orte von Interesse";L["DESCRIPTION"]="Kartenmarkierungen erstellen, verwalten, filtern und teilen.";L["CREATE"]="POI erstellen";L["BACK"]="Zurück";L["CANCEL"]="Abbrechen";L["SAVE"]="Speichern";L["EDIT"]="Bearbeiten";L["DETAILS"]="Details";L["SETTINGS"]="Einstellungen";L["DIAGNOSTICS"]="Diagnose";L["SHOW_MAP"]="Auf Karte anzeigen";L["SHARE"]="Chatlink einfügen";L["GUIDE_COORDINATE"]="Guide-Koordinate";L["HIDE_LOCAL"]="Lokal ausblenden";L["UNHIDE"]="Wieder einblenden";L["DELETE_LOCAL"]="Persönlichen POI löschen";L["DELETE_GLOBAL"]="Global löschen"
L["MODE_ALL"]="Aktiv";L["MODE_OWN"]="Meine POIs";L["MODE_SYNCED"]="Synchronisiert";L["MODE_HIDDEN"]="Ausgeblendet";L["EMPTY"]="Keine passenden POIs.";L["MODULE_DISABLED"]="Geteilte POIs sind durch die Gildenrichtlinie deaktiviert. Persönliche POIs bleiben verfügbar.";L["SEARCH"]="POIs suchen"
L["COLUMN_NAME"]="Name";L["COLUMN_CATEGORY"]="Kategorie";L["COLUMN_TARGET"]="Ziel";L["COLUMN_MAP"]="Karte";L["COLUMN_CREATOR"]="Ersteller";L["COLUMN_CREATED"]="Erstellt";L["COLUMN_LIFETIME"]="Laufzeit";L["COLUMN_STATUS"]="Status";L["STATUS_ACTIVE"]="Aktiv";L["STATUS_DELETED"]="Gelöscht";L["PERMANENT"]="Permanent";L["SECONDS"]="%d Sek.";L["MINUTES"]="%d Min.";L["HOURS"]="%d Std."
L["FIELD_NAME"]="Name";L["FIELD_DESCRIPTION"]="Beschreibung";L["FIELD_MAP"]="Karten-ID";L["FIELD_X"]="X (0–1)";L["FIELD_Y"]="Y (0–1)";L["FIELD_TARGET"]="Ziel";L["FIELD_CATEGORY"]="Kategorie";L["FIELD_CUSTOM_CATEGORY"]="Eigene Kategorie";L["FIELD_LIFETIME"]="Laufzeit";L["FIELD_COLOR"]="Farbe";L["FIELD_ICON"]="Symbol";L["CURRENT_POSITION"]="Aktuelle Position verwenden"
L["TARGET_PERSONAL"]="Persönlich";L["TARGET_GUILD"]="Gilde";L["TARGET_GROUP"]="Aktuelle Gruppe";L["TARGET_RAID"]="Aktueller Raid";L["CATEGORY_QUEST"]="Quest";L["CATEGORY_ACHIEVEMENT"]="Erfolg";L["CATEGORY_RAID_ENTRANCE"]="Raid-/Instanzeingang";L["CATEGORY_NOTE"]="Notiz / Hinweis";L["CATEGORY_CUSTOM"]="Eigene Kategorie";L["LIFETIME_PERMANENT"]="Permanent";L["LIFETIME_5_MIN"]="5 Minuten";L["LIFETIME_30_MIN"]="30 Minuten";L["LIFETIME_1_HOUR"]="1 Stunde";L["LIFETIME_SESSION"]="Bis zum Gruppenende"
L["WORLD_ENABLED"]="Auf Weltkarte anzeigen";L["MINIMAP_ENABLED"]="Auf Minimap anzeigen";L["WORLD_SIZE"]="Markergröße Weltkarte: %d";L["MINIMAP_SIZE"]="Markergröße Minimap: %d";L["MAX_SYNCED"]="Maximal synchronisierte POIs: %d";L["CATEGORY_FILTERS"]="Sichtbarkeit nach Kategorie";L["TARGET_FILTERS"]="Sichtbarkeit nach Ziel";L["DECREASE"]="−";L["INCREASE"]="+"
L["ERROR_SAVE"]="Der POI konnte nicht gespeichert werden: %s";L["ERROR_CONFLICT"]="Es existiert eine neuere POI-Revision. Bitte vor dem Speichern neu laden.";L["ERROR_POSITION"]="Die aktuelle Position ist nicht verfügbar.";L["SAVED"]="POI gespeichert.";L["SHARE_UNAVAILABLE"]="Persönliche POIs können nicht über ihre ID geteilt werden.";L["COPY_FALLBACK"]="Diesen Wert manuell kopieren oder einfügen:";L["CONFIRM_DELETE"]="%s löschen?";L["DETAIL_FORMAT"]="%s · %s · Karte %d · %.2f, %.2f · %s";L["CREATED_FORMAT"]="Erstellt von %s am %s"
L["DEBUG_HEADER"]="ID | Ziel | Karte | Koordinaten | Ersteller | Revision | Quelle | empfangen von | Ablauf | Session | sichtbar | Welt | Minimap | lokal verborgen | betrachtete Karte | Transformation | transformierte Koordinaten | Abruf ausstehend";L["DEBUG_ROW"]="%s | %s | %s | %.4f,%.4f | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %s | %.4f,%.4f | %s";L["DEBUG_CONTEXT"]="Kontext: %s · aktive temporäre POIs: %d · letzte Synchronisierung: %s · ausstehend: %d · Tasks: %d · Suppression-Anfragen: %d"
