local addonVersion="1.0.0"
local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm")
local L=LibStub("AceLocale-3.0"):GetLocale("Holy_Storm")
local Positions={version=addonVersion,remote={},ownState=nil,pendingSnapshot=nil,currentGuildId=nil,sequence=0,staleTimeout=90,movement={active=false,bucket="stationary",speed=nil,nextEligible=0,lastSent=0,lastCapture=nil},metrics={published=0,received=0,coalesced=0,droppedStale=0,rejected=0}}
local function now()return HolyStorm.Utils.Now()end
local function clock()return GetTime and GetTime()or 0 end
local function finite(value)value=tonumber(value);return value and value==value and value~=math.huge and value~=-math.huge end
local function copy(value)return HolyStorm.Utils.DeepCopy(value)end
local function log(level,message,context)HolyStorm.Logger:Write(level,"Positions","live",message,context)end

function Positions:GetSettings()HolyStorm.db.profile.positions=HolyStorm.Utils.ApplyDefaults(HolyStorm.db.profile.positions,{share=false,display=true,worldMapEnabled=true,minimapEnabled=false,currentMapOnly=false,worldMapSize=24,minimapSize=18,markerStyle="CLASS"});return HolyStorm.db.profile.positions end
function Positions:IsEnabled()return not HolyStorm.Policy or HolyStorm.Policy:IsGuildModuleEnabled("positions")end
function Positions:GetGuild()return HolyStorm.Data.GuildStore:GetCurrent()end
function Positions:CanShare()
 local guild=self:GetGuild();local guid=UnitGUID("player");local engine=HolyStorm.PermissionEngine or HolyStorm.Policy;return self:GetSettings().share==true and self:IsEnabled()and guild and guild.id and(IsInGuild==nil or IsInGuild())and engine:Can("position-share",HolyStorm.Data.PlayerStore:GetCharacterOwner(guid),guid)
end
function Positions:CanDisplay()local engine=HolyStorm.PermissionEngine or HolyStorm.Policy;return self:GetSettings().display==true and self:IsEnabled()and engine:Can("position-view")end
function Positions:SetSetting(key,value)
 local settings=self:GetSettings();if key=="worldMapSize"then value=math.max(14,math.min(48,tonumber(value)or 24))elseif key=="minimapSize"then value=math.max(12,math.min(36,tonumber(value)or 18))elseif key=="markerStyle"then value=value=="GUILD"and"GUILD"or"CLASS"elseif key=="share"or key=="display"or key=="worldMapEnabled"or key=="minimapEnabled"or key=="currentMapOnly"then value=value==true else return false end;local changed=settings[key]~=value;settings[key]=value;if not changed then return true end;if key=="share"then self.ownState,self.pendingSnapshot=nil,nil;log("INFO",value and"Guild position sharing enabled"or"Guild position sharing disabled",{enabled=value});if value then self:QueueCapture("PRIVACY_ENABLED",true,.2)end end;if key=="display"and not value then HolyStorm.Events:Emit("HS_GUILD_POSITIONS_CLEARED","DISPLAY_DISABLED")end;HolyStorm.Events:Emit("HS_POSITION_SETTINGS_CHANGED",key,value);self:RefreshMap();return true
end
function Positions:IsValidMap(mapID)return HolyStorm.POI and HolyStorm.POI:IsMapValid(mapID)or tonumber(mapID)and tonumber(mapID)>0 and tonumber(mapID)%1==0 end
function Positions:Capture()
 if not self:CanShare()then return nil,"PRIVACY_OR_POLICY"end;local guild=self:GetGuild();local mapID,x,y=HolyStorm.MapLinks:GetPlayerPosition();if not mapID or not self:IsValidMap(mapID)or not HolyStorm.MapLinks:IsValidCoordinate(mapID,x,y)then log("DEBUG","No valid local position available",{mapID=mapID,x=x,y=y});return nil,"POSITION_UNAVAILABLE"end;return{characterUUID=UnitGUID("player"),guildId=guild.id,mapID=mapID,x=x,y=y,timestamp=now(),sequence=self.sequence+1}
end
function Positions:GetMovementPolicy()
 if not self.movement.active then return"stationary",nil,nil end;if not GetUnitSpeed then return"normal",nil,5 end;local ok,bucket,speed,interval=pcall(function()local value=tonumber(GetUnitSpeed("player"));if not value or value<=.05 then return"stationary",value,nil elseif value<4 then return"slow",value,8 elseif value<10 then return"normal",value,5 else return"fast",value,3 end end);if not ok then return"normal",nil,5 end;return bucket,speed,interval
end
function Positions:HasMeaningfulChange(snapshot,previous)
 if not previous or snapshot.mapID~=previous.mapID then return true end;local dx,dy=snapshot.x-previous.x,snapshot.y-previous.y;return dx*dx+dy*dy>=0.0000001225
end
function Positions:SampleMovement(reason,force)
 if not self:CanShare()then return false,"PRIVACY_OR_POLICY"end;local bucket,speed,interval=self:GetMovementPolicy();self.movement.bucket,self.movement.speed=bucket,speed;if not force and(not interval or clock()<self.movement.nextEligible)then return false,"NOT_DUE"end;local snapshot,err=self:Capture();if not snapshot then return false,err end;local previous=self.pendingSnapshot or self.ownState;if not self:HasMeaningfulChange(snapshot,previous)then return false,"UNCHANGED"end;self.sequence=snapshot.sequence;self.pendingSnapshot=snapshot;self.movement.lastCapture=copy(snapshot);self.movement.nextEligible=clock()+(interval or 3);local _,status=HolyStorm.Tasks:Queue("Position.Publish",{mergeKey=snapshot.characterUUID,startupPhase=4,delay=.15,priority=110,triggerSource=reason or"MOVEMENT"});if status=="MERGED"then self.metrics.coalesced=self.metrics.coalesced+1 end;return true,status
end
function Positions:QueueCapture(reason,force,delay)
 self.captureForce=self.captureForce or force==true;self.captureReason=reason or self.captureReason;return HolyStorm.Tasks:Queue("Position.Capture",{mergeKey=UnitGUID("player")or"player",startupPhase=4,delay=delay or 0,priority=108,triggerSource=reason or"CAPTURE"})
end
function Positions:RunCapture()local force,reason=self.captureForce,self.captureReason;self.captureForce,self.captureReason=false,nil;return self:SampleMovement(reason,force)end
function Positions:RunPublish()
 if not self:CanShare()then self.pendingSnapshot=nil;return false,"PRIVACY_OR_POLICY"end;local snapshot=self.pendingSnapshot;if not snapshot then return false,"NO_POSITION"end;self.pendingSnapshot=nil;self.ownState=snapshot;self.movement.lastSent=clock();self.metrics.published=self.metrics.published+1;local ok,reason=HolyStorm.Sync:Publish("guild-position",snapshot.characterUUID,"POSITION_LIVE_UPDATE");if not ok then log("WARN","Position publish could not be queued",{reason=reason})end;HolyStorm.Events:Emit("HS_OWN_POSITION_UPDATED",copy(snapshot));return ok,reason
end
function Positions:StartMovement()
 self.movement.active=true;if not self.movementTicker and C_Timer and C_Timer.NewTicker then self.movementTicker=C_Timer.NewTicker(.5,function()Positions:SampleMovement("MOVEMENT_TICK",false)end)end;self:QueueCapture("MOVEMENT_STARTED",false,.4)
end
function Positions:StopMovement()
 self.movement.active=false;if self.movementTicker then self.movementTicker:Cancel();self.movementTicker=nil end;self:QueueCapture("MOVEMENT_STOPPED",true,0)
end
function Positions:IsStale(entry)return not entry or not finite(entry.timestamp)or now()-entry.timestamp>self.staleTimeout end
function Positions:IsRosterOnline(characterUUID)local guild=self:GetGuild();local member=guild and guild.roster and guild.roster[characterUUID];return member and member.online==true or false end
function Positions:IsRenderable(entry)
 return self:CanDisplay()and entry and entry.guildId==(self:GetGuild()and self:GetGuild().id)and not self:IsStale(entry)and self:IsRosterOnline(entry.characterUUID)
end
function Positions:Get(characterUUID)local entry=self.remote[characterUUID];return self:IsRenderable(entry)and entry or nil end
function Positions:GetVisible()local out={};if not self:CanDisplay()then return out end;for _,entry in pairs(self.remote)do if self:IsRenderable(entry)then out[#out+1]=entry end end;table.sort(out,function(a,b)return a.characterUUID<b.characterUUID end);return out end
function Positions:Clear(reason)
 local changed=next(self.remote)~=nil;self.remote={};if changed then HolyStorm.Events:Emit("HS_GUILD_POSITIONS_CLEARED",reason or"CLEAR");self:RefreshMap()end
end
function Positions:ReconcileRoster()
 local guild=self:GetGuild();local guildId=guild and guild.id;if guildId~=self.currentGuildId then self:Clear("GUILD_CHANGED");self.ownState,self.pendingSnapshot=nil,nil;log("INFO","Guild position cache changed guild context",{oldGuildId=self.currentGuildId,newGuildId=guildId});self.currentGuildId=guildId end;if not guildId or not self:IsEnabled()then self:Clear(not guildId and"NO_GUILD"or"MODULE_DISABLED");return true end;local removed=0;for guid,entry in pairs(self.remote)do if entry.guildId~=guildId or not self:IsRosterOnline(guid)or self:IsStale(entry)then self.remote[guid]=nil;removed=removed+1;self.metrics.droppedStale=self.metrics.droppedStale+(self:IsStale(entry)and 1 or 0)end end;if removed>0 then HolyStorm.Events:Emit("HS_GUILD_POSITIONS_RECONCILED",removed);self:RefreshMap()end;return true
end
function Positions:ValidatePayload(payload,meta,id)
 local allowed={characterUUID=true,guildId=true,mapID=true,x=true,y=true,timestamp=true,sequence=true};if type(payload)~="table"then return false,"INVALID_PAYLOAD"end;for key in pairs(payload)do if not allowed[key]then return false,"NON_COMPACT_PAYLOAD"end end;local guild=self:GetGuild();if type(payload.characterUUID)~="string"or payload.characterUUID~=id or#payload.characterUUID>160 or not guild or payload.guildId~=guild.id or meta.owner~=id or not self:IsValidMap(payload.mapID)or not HolyStorm.MapLinks:IsValidCoordinate(payload.mapID,payload.x,payload.y)or not finite(payload.timestamp)or payload.timestamp<now()-self.staleTimeout or payload.timestamp>now()+300 or not finite(payload.sequence)or payload.sequence<1 or payload.sequence%1~=0 then return false,"INVALID_POSITION"end;local member=guild.roster and guild.roster[id];if not member or member.online~=true then return false,"NOT_ONLINE_GUILD_MEMBER"end;return true
end
function Positions:Import(id,payload,meta,senderId,sender)
 local current=self.remote[id];if current and(current.sequence>payload.sequence or current.sequence==payload.sequence and current.timestamp>=payload.timestamp)then return false,"STALE"end;local entry=copy(payload);entry.source=senderId==id and"owner"or"relay";entry.receivedFrom=sender;entry.receivedAt=now();self.remote[id]=entry;self.metrics.received=self.metrics.received+1;HolyStorm.Events:Emit("HS_GUILD_POSITION_UPDATED",id,copy(entry));self:RefreshMap(id);return true
end
function Positions:RefreshMap(characterUUID)HolyStorm.Tasks:Queue("Position.MapRefresh",{mergeKey=characterUUID or"all",startupPhase=4,priority=112,triggerSource="POSITION_CHANGED",metadata={characterUUID=characterUUID}})end
function Positions:Discover()
 if not self:CanDisplay()or not self:GetGuild()then return false end;log("DEBUG","Discovering current guild positions",{guildId=self:GetGuild().id});return HolyStorm.Sync:Discover("guild-position",nil,{channel="GUILD",scope=self:GetGuild().id,reason="POSITION_INITIAL_DISCOVERY",priority=110,delay=.5,startupPhase=4})
end
function Positions:GetCharacterSummary(characterUUID)
 local context=HolyStorm.CharacterUI:ResolveContext(characterUUID);if not context then return{characterUUID=characterUUID,name=characterUUID}end;local record,member=context.record or{},context.member or{};local main=HolyStorm.TwinkCore and HolyStorm.TwinkCore:GetRosterIdentity(characterUUID,context.guild);local mainGuid=main and(main.accountMain or main.guildMain);local mainContext=mainGuid and HolyStorm.CharacterUI:ResolveContext(mainGuid);local raid=HolyStorm.CharacterUI:GetSnapshot(characterUUID,"raid");local progress=HolyStorm.CharacterUI:GetBestProgress(raid);local mythic=HolyStorm.CharacterUI:GetSnapshot(characterUUID,"mythicPlus");local role=record.profile and record.profile.preferredRole or record.stats and record.stats.spec and record.stats.spec.role;return{characterUUID=characterUUID,name=context.fullName or context.name,class=context.className,classFile=context.classFile,race=record.race,role=role,rank=member.rank,status=member.status,online=member.online==true,itemLevel=tonumber(record.itemLevel),mythicScore=mythic and tonumber(mythic.overallScore),raidProgress=progress,mainGuid=mainGuid,mainName=mainContext and(mainContext.fullName or mainContext.name),isShadowMain=main and main.isShadowMain}
end
function Positions:GetDiagnostics()
 local remote={};for guid,entry in pairs(self.remote)do local render=HolyStorm.GuildPositionMap and HolyStorm.GuildPositionMap:GetRenderState(guid)or{};remote[#remote+1]={characterUUID=guid,mapID=entry.mapID,x=entry.x,y=entry.y,timestamp=entry.timestamp,sequence=entry.sequence,source=entry.source,receivedFrom=entry.receivedFrom,stale=self:IsStale(entry),online=self:IsRosterOnline(guid),worldPin=render.worldPin==true,minimapPin=render.minimapPin==true,viewedMapID=render.viewedMapID,transform=render.transform,transformedX=render.transformedX,transformedY=render.transformedY,reason=render.reason}end;table.sort(remote,function(a,b)return a.characterUUID<b.characterUUID end);return{sharing=self:GetSettings().share,enabled=self:IsEnabled(),guildId=self.currentGuildId,own=copy(self.ownState or self.movement.lastCapture),movement=copy(self.movement),metrics=copy(self.metrics),remote=remote,staleTimeout=self.staleTimeout}
end
function Positions:Initialize()
 HolyStorm.Tasks:RegisterTaskType("Position.Capture",{name=L["TASK_POSITION_CAPTURE"],localizedNameKey="TASK_POSITION_CAPTURE",module="Positions",priority=108,executionMode="MERGE_BY_KEY",execute=function()return Positions:RunCapture()end});HolyStorm.Tasks:RegisterTaskType("Position.Publish",{name=L["TASK_POSITION_PUBLISH"],localizedNameKey="TASK_POSITION_PUBLISH",module="Positions",priority=110,executionMode="MERGE_BY_KEY",conditions={"PLAYER_READY","NOT_LOADING","NOT_ZONING","GUILD_AVAILABLE"},execute=function()return Positions:RunPublish()end});HolyStorm.Tasks:RegisterTaskType("Position.Reconcile",{name=L["TASK_POSITION_RECONCILE"],localizedNameKey="TASK_POSITION_RECONCILE",module="Positions",priority=105,executionMode="UNIQUE",execute=function()return Positions:ReconcileRoster()end});HolyStorm.Tasks:RegisterTaskType("Position.MapRefresh",{name=L["TASK_POSITION_MAP_REFRESH"],localizedNameKey="TASK_POSITION_MAP_REFRESH",module="Positions",priority=112,executionMode="MERGE_BY_KEY",execute=function(task)if HolyStorm.GuildPositionMap then HolyStorm.GuildPositionMap:Refresh(task.metadata and task.metadata.characterUUID)end;return true end})
 HolyStorm.Sync:RegisterDomain("guild-position",{live=true,catchUp=false,priority=110,getChannel=function()return"GUILD"end,getMetadata=function(id)local entry=id==UnitGUID("player")and Positions.ownState or Positions.remote[id];if not entry or Positions:IsStale(entry)then return nil end;return{objectId=id,owner=id,version=entry.sequence,updatedAt=entry.timestamp,source="live-position"}end,listMetadata=function()local own=Positions.ownState;if Positions:CanShare()and own and not Positions:IsStale(own)then return{{objectId=own.characterUUID,owner=own.characterUUID,version=own.sequence,updatedAt=own.timestamp,source="live-position"}}end;return{}end,export=function(id)return id==UnitGUID("player")and Positions:CanShare()and copy(Positions.ownState)or nil end,validate=function(payload,meta,id)local ok,reason=Positions:ValidatePayload(payload,meta,id);if not ok then Positions.metrics.rejected=Positions.metrics.rejected+1;log("WARN","Rejected guild position payload",{characterUUID=id,reason=reason})end;return ok,reason end,authorize=function(_,meta,senderId,_,id)local engine=HolyStorm.PermissionEngine or HolyStorm.Policy;return meta.owner==id and senderId==id and engine:Can("position-share",HolyStorm.Data.PlayerStore:GetCharacterOwner(id),id)end,import=function(id,payload,meta,senderId,sender)return Positions:Import(id,payload,meta,senderId,sender)end,updateEvent="HS_GUILD_POSITION_SYNCED"})
 HolyStorm.Events:Register("PLAYER_STARTED_MOVING","positions-movement",function()Positions:StartMovement()end);HolyStorm.Events:Register("PLAYER_STOPPED_MOVING","positions-movement",function()Positions:StopMovement()end);for _,event in ipairs({"ZONE_CHANGED_NEW_AREA","ZONE_CHANGED","ZONE_CHANGED_INDOORS"})do local eventName=event;HolyStorm.Events:Register(eventName,"positions-zone",function()Positions:QueueCapture(eventName,true,.2)end)end;HolyStorm.Events:Register("PLAYER_ENTERING_WORLD","positions-login",function()HolyStorm.Tasks:Queue("Position.Reconcile",{startupPhase=4,delay=2,priority=105,triggerSource="POSITION_LOGIN"});Positions:QueueCapture("POSITION_LOGIN",true,3);HolyStorm.Tasks:Queue("Position.InitialDiscovery",{startupPhase=4,delay=4,priority=110,triggerSource="POSITION_LOGIN"});if GetUnitSpeed then local ok,moving=pcall(function()return tonumber(GetUnitSpeed("player"))>.05 end);if ok and moving then Positions:StartMovement()end end end);HolyStorm.Tasks:RegisterTaskType("Position.InitialDiscovery",{name=L["TASK_POSITION_DISCOVERY"],localizedNameKey="TASK_POSITION_DISCOVERY",module="Positions",priority=110,executionMode="UNIQUE",conditions={"PLAYER_READY","NOT_LOADING","NOT_ZONING","GUILD_AVAILABLE"},execute=function()return Positions:Discover()end});for _,event in ipairs({"HS_ROSTER_UPDATED","PLAYER_GUILD_UPDATE","HS_PERMISSIONS_STATE_UPDATED"})do local eventName=event;HolyStorm.Events:Register(eventName,"positions-roster",function()HolyStorm.Tasks:Queue("Position.Reconcile",{startupPhase=4,delay=.2,priority=105,triggerSource=eventName})end)end;HolyStorm.Tasks:ScheduleRecurring("Position.Cleanup",10,function()return Positions:ReconcileRoster()end,{priority=115,cooldown=10,module="Positions"});self.currentGuildId=self:GetGuild()and self:GetGuild().id;self:ReconcileRoster()
end
HolyStorm.GuildPositions=Positions
