local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm")
local L=LibStub("AceLocale-3.0"):GetLocale("Holy_Storm_Policy")
local Registry,Engine,Groups,Filters,State=HolyStorm.PermissionRegistry,HolyStorm.PermissionEngine,HolyStorm.GroupManager,HolyStorm.FilterManager,HolyStorm.PolicyState
local Page=HolyStorm:RegisterRequiredModule("PermissionsUI")
HolyStorm:ApplyModuleMetadata(Page,{displayName=L["PERMISSIONS_TITLE"],internalName="permissionsUI",version="2.1.0",category="required",description=L["PERMISSIONS_DESC"],permissions={"permissions-manage"},dependencies={"core","ui"},enabledByDefault=true})
local tabs={"GENERAL","MEMBERS","PERMISSIONS","PERMISSION_MATRIX","RULES_FILTERS","MANAGERS","EFFECTIVE_MEMBERS","MODULE_SETTINGS","ANALYSIS","STATUS"}
local function csv(value)local out={};for item in tostring(value or""):gmatch("[^,]+")do out[#out+1]=item:match("^%s*(.-)%s*$")end;return out end
local function keys(value)local out={};for key in pairs(value or{})do out[#out+1]=key end;table.sort(out,function(a,b)return tostring(a)<tostring(b)end);return out end
function Page:GetGroups()local out={};local search=string.lower(self.search:GetText()or"");for _,group in pairs(Groups:GetGroups())do local name=HolyStorm.PolicyUI:DisplayGroupName(group);if search==""or string.lower(name.." "..group.id):find(search,1,true)then out[#out+1]=group end end;table.sort(out,function(a,b)if a.system~=b.system then return a.system end;return HolyStorm.PolicyUI:DisplayGroupName(a)<HolyStorm.PolicyUI:DisplayGroupName(b)end);return out end
function Page:CanMutate(permission)local s=State:GetPermissionStateStatus();return s.status==State.status.VALID and Engine:HasPermission(nil,nil,permission)end
function Page:Select(group)self.selectedId=group and group.id;self.isNew=group and Groups:GetGroup(group.id)==nil or false;self.draft=group and HolyStorm.Utils.DeepCopy(group)or nil;self.baseRevision=State:GetPermissionStateStatus().revisionID;if self.deleteButton then self.deleteButton:SetEnabled(group and not self.isNew and not group.system and self:CanMutate("groups-delete")or false)end;self:RefreshDetails()end
function Page:RefreshList()local summaries=Engine:GetGroupSummaries();self.list:SetItems(self:GetGroups(),function(group)local summary=summaries[group.id]or{};return string.format("%s%s  (%d / %d / %d / %d)",group.system and("|TInterface\\Buttons\\LockButton-Locked-Up:12|t ")or"",HolyStorm.PolicyUI:DisplayGroupName(group),summary.effectiveMembers or 0,summary.explicitMembers or 0,summary.filters or 0,summary.permissions or 0)end)end
function Page:EnsurePermissionChecks()if not self.permissionsFrame then return end;local defs=Registry:GetPermissions();local query=string.lower(self.permissionSearch and self.permissionSearch:GetText()or"");local visible=0;for _,key in ipairs(keys(defs))do local permissionKey=key;local definition=defs[key];local check=self.permissionChecks[key];if not check then check=CreateFrame("CheckButton",nil,self.permissionsFrame,"UICheckButtonTemplate");self.permissionChecks[key]=check;check:SetScript("OnClick",function(c)if Page.draft then Page.draft.permissions[permissionKey]=c:GetChecked()and true or nil end end);check:SetScript("OnEnter",function(c)GameTooltip:SetOwner(c,"ANCHOR_RIGHT");GameTooltip:AddLine(L[definition.labelKey]or permissionKey);GameTooltip:AddLine(L[definition.descriptionKey]or permissionKey,nil,nil,nil,true);GameTooltip:AddLine(permissionKey,.6,.6,.6);GameTooltip:AddLine(definition.module or"Core",.6,.6,.6);GameTooltip:Show()end);check:SetScript("OnLeave",function()GameTooltip:Hide()end)end;local categoryKey="CATEGORY_"..definition.category:gsub("[^%w]","_"):upper();local label=(L[definition.labelKey]or permissionKey).."  ["..(L[categoryKey]or definition.category).."]";check.text:SetText(label);local matches=query==""or string.lower(label.." "..permissionKey.." "..(definition.module or"")):find(query,1,true);check:SetShown(matches and true or false);if matches then check:ClearAllPoints();check:SetPoint("TOPLEFT",(visible%3)*220,-30-math.floor(visible/3)*27);visible=visible+1 end end end
function Page:ShowTab(id)self.activeTab=id;for key,frame in pairs(self.tabFrames)do frame:SetShown(key==id)end;for key,button in pairs(self.tabButtons)do button:SetEnabled(key~=id)end;self:RefreshDetails()end
function Page:RefreshDetails()
 local draft=self.draft;if not draft then for _,frame in pairs(self.tabFrames)do frame:Hide()end;self.empty:Show();return end;self.empty:Hide();local active=self.activeTab or"GENERAL";for key,frame in pairs(self.tabFrames)do frame:SetShown(key==active)end
 if active=="GENERAL"then self.nameEdit:SetText(draft.nameKey and(L[draft.nameKey]or draft.name)or draft.name or"");self.descEdit:SetText(draft.description or"");self.nameEdit:SetEnabled(not draft.system);self.descEdit:SetEnabled(not draft.system);self.generalInfo:SetText(string.format("%s: %s\n%s: %s\n%s: %s\n%s: %s\n%s: %s",L["INTERNAL_ID"],draft.id,L["TYPE"],draft.system and L["SYSTEM_GROUP"]or L["CUSTOM_GROUP"],L["CREATOR"],draft.creator or"-",L["CREATED_AT"],draft.createdAt and date("%Y-%m-%d %H:%M",draft.createdAt)or"-",L["MODIFIED_AT"],draft.modifiedAt and date("%Y-%m-%d %H:%M",draft.modifiedAt)or"-"))
 elseif active=="MEMBERS"then self.memberText:SetText(string.format("%s:\n%s\n\n%s:\n%s\n\n%s:\n%s\n\n%s",L["CHARACTER_MEMBERS"],table.concat(keys(draft.characterMembers),"\n"),L["ACCOUNT_MEMBERS"],table.concat(keys(draft.accountMembers),"\n"),L["GUILD_RANK"],table.concat(keys(draft.guildRanks),", "),L["ACCOUNT_MEMBERSHIP_HELP"]));local leaderOnly=draft.id==Groups.systemIds.LEADERSHIP and not Engine:IsActualGuildLeader();local actor=Engine:Actor();local canMembers=(Engine:CanManageGroup(actor.accountUUID,actor.characterUUID,draft.id)or self:CanMutate("groups-manage-members"))and not leaderOnly;self.addCharacterButton:SetEnabled(canMembers);self.addAccountButton:SetEnabled(canMembers);self.addRankButton:SetEnabled(canMembers);self.removeMembershipButton:SetEnabled(canMembers)
 elseif active=="PERMISSIONS"then self:EnsurePermissionChecks();local leadership=draft.id==Groups.systemIds.LEADERSHIP;self.fullAccess:SetShown(leadership);for key,check in pairs(self.permissionChecks)do check:SetChecked(leadership or draft.permissions[key]==true);check:SetEnabled(not leadership and self:CanMutate("permissions-manage"))end;local unknown={};for key in pairs(draft.permissions or {})do if not Registry:GetPermission(key)then unknown[#unknown+1]=key end end;table.sort(unknown);if #unknown>0 then self.fullAccess:SetText(L["FULL_ACCESS"].." — "..L["UNKNOWN_PERMISSIONS"]..": "..table.concat(unknown,", "))else self.fullAccess:SetText(L["FULL_ACCESS"].." — "..L["FULL_ACCESS_HELP"])end
 elseif active=="PERMISSION_MATRIX"then self:RefreshMatrix()
 elseif active=="RULES_FILTERS"then self.ruleList:Refresh();self.filterList:Refresh();self.filterMode:SetValue(draft.filterOperator,L["LOGIC_"..draft.filterOperator])
 elseif active=="MANAGERS"then self.managerList:Refresh()
 elseif active=="EFFECTIVE_MEMBERS"then local lines={L["NAME"].." | "..L["GUILD_RANK"].." | "..L["MAIN_TWINK"].." | "..L["SOURCES"]};local query=string.lower(self.memberSearch:GetText()or"");for _,entry in ipairs(Engine:GetEffectiveMembers(draft.id))do if query==""or string.lower((entry.name or"").." "..(entry.rank or"").." "..(entry.accountUUID or"")):find(query,1,true)then local labels={};for _,reason in ipairs(entry.reasons)do labels[#labels+1]=(L["MEMBERSHIP_"..reason.type]or reason.type)..(reason.name and(": "..reason.name)or"")end;lines[#lines+1]=string.format("%s | %s | %s | %s",entry.name,entry.rank or"-",entry.isMain and L["MAIN"]or L["ALT"],table.concat(labels,", "))end end;self.effectiveText:SetText(table.concat(lines,"\n"))
 elseif active=="MODULE_SETTINGS"then self:RefreshModules()
 elseif active=="ANALYSIS"then self:Analyze()
 elseif active=="STATUS"then local s=State:GetPermissionStateStatus();local statusLabel=L["STATE_"..tostring(s.status)]or s.status or"-";local text=string.format(L["STATE_DETAILS_FORMAT"],tostring(s.guildId or"-"),statusLabel,s.version or 0,s.revisionID or"-",s.previousRevisionID or"-",tostring(s.lastSync or 0),tostring(s.changedBy and(s.changedBy.characterUUID or s.changedBy.accountUUID)or"-"),tostring(s.changedAt or"-"),s.historyLength or 0,s.rejectedLength or 0,tostring(s.missingRevisions and(s.missingRevisions.target or s.missingRevisions.after)or"-"),tostring(s.fork and(s.fork.remoteRevision or s.fork.reason)or"-"));if s.catchup then text=text.."\n"..string.format(L["CATCHUP_FORMAT"],tostring(s.catchup.requestedAfter or"-"),s.catchup.receivedCount or 0,s.catchup.validatedCount or 0,tostring(s.catchup.respondingPeer or"-"))end;self.statusText:SetText(text)end
end
function Page:CommitEdits()if not self.draft then return end;if not self.draft.system then self.draft.name=self.nameEdit:GetText();self.draft.nameKey=nil;self.draft.description=self.descEdit:GetText()end end
function Page:Save()if not self.draft then return end;if self.baseRevision~=State:GetPermissionStateStatus().revisionID then HolyStorm.Events:Emit("HS_UI_STATUS_REQUESTED",L["STALE_EDITOR"]);return end;self:CommitEdits();local ok,result=Groups:SaveGroup(self.draft);if ok then self:Select(result);self:RefreshList();HolyStorm.Events:Emit("HS_UI_STATUS_REQUESTED",L["SAVED"])else HolyStorm.Events:Emit("HS_UI_STATUS_REQUESTED",string.format(L["INVALID"],tostring(result)))end end
function Page:RefreshMatrix()local matrix=Engine:GetPermissionMatrix();local lines={L["PERMISSION_MATRIX"]};for _,id in ipairs(matrix.groupIds)do lines[1]=lines[1].." | "..HolyStorm.PolicyUI:DisplayGroupName(matrix.groups[id])end;for _,row in ipairs(matrix.rows)do local line=L[row.definition.labelKey]or row.permissionId;for _,id in ipairs(matrix.groupIds)do line=line.." | "..(row.grants[id]and "✓"or "—")end;lines[#lines+1]=line end;self.matrixText:SetText(table.concat(lines,"\n"))end
function Page:RefreshModules()self.moduleList:Refresh()end
function Page:Analyze()if not self.analysisText or not self.draft then return end;local guid=self.analysisGuid:GetText();if guid==""then guid=UnitGUID("player")end;local playerId=HolyStorm.Data.PlayerStore:GetCharacterOwner(guid)or guid;local reasons=Engine:GetMembershipReasons(self.draft,playerId,guid);local lines={self.draft.name,"GUID: "..tostring(guid)};for _,reason in ipairs(reasons)do lines[#lines+1]=string.format("✓ %s: %s",reason.type,tostring(reason.name or reason.id))end;if#reasons==0 then lines[#lines+1]="✗ "..L["NONE"]end;local permissions=Engine:GetEffectivePermissions(playerId,guid);lines[#lines+1]="\n"..L["PERMISSIONS"]..": "..table.concat(keys(permissions),", ");self.analysisText:SetText(table.concat(lines,"\n"))end
function Page:Render()if not self.page:IsShown()then return end;self:RefreshList();local current=self.selectedId and Groups:GetGroup(self.selectedId);if self.selectedId and not current and not self.isNew then self:Select(nil)elseif current and not self.draft then self:Select(current)else self:RefreshDetails()end;local valid=State:GetPermissionStateStatus().status==State.status.VALID;self.newButton:SetEnabled(valid and self:CanMutate("groups-create"));self.saveButton:SetEnabled(valid and self.draft~=nil);self.resetButton:SetEnabled(valid and self:CanMutate("permissions-reset"));self.readOnly:SetText(valid and""or L["STATE_READ_ONLY"]);if self.draft and self.baseRevision~=State:GetPermissionStateStatus().revisionID then self.readOnly:SetText(L["STALE_EDITOR"]);self.saveButton:SetEnabled(false)end end
function Page:OnInitialize()
 local UI=HolyStorm:GetModule("UI",true);local p=CreateFrame("Frame",nil,UI.content);self.page=p;local title=HolyStorm.PolicyUI:Label(p,L["PERMISSIONS_TITLE"],"GameFontHighlightLarge");title:SetPoint("TOPLEFT",14,-12)
 self.search=HolyStorm.PolicyUI:Edit(p,190,function()Page:RefreshList()end);self.search:SetPoint("TOPLEFT",14,-42);local columns=HolyStorm.PolicyUI:Label(p,L["GROUP_COUNT_COLUMNS"]);columns:SetPoint("TOPLEFT",14,-67);self.list=HolyStorm.PolicyUI:CreateList(p,function(group)Page:Select(group)end);self.list:SetPoint("TOPLEFT",14,-86);self.list:SetSize(200,416)
 local new=HolyStorm.PolicyUI:Button(p,L["NEW"],62,function()Page:Select({id=HolyStorm.PolicyUI:NewId("group"),name=L["CUSTOM_GROUP"],description="",permissions={},characterMembers={},accountMembers={},guildRanks={},ruleIds={},filterIds={},managerGroupIds={},filterOperator="AND"})end);new:SetPoint("BOTTOMLEFT",14,50);self.newButton=new
 local duplicate=HolyStorm.PolicyUI:Button(p,L["DUPLICATE"],90,function()if Page.draft then local group=HolyStorm.Utils.DeepCopy(Page.draft);group.id=HolyStorm.PolicyUI:NewId("group");group.name=(group.name or"").." "..L["COPY_SUFFIX"];group.system=false;group.systemRule=nil;group.version=0;Page:Select(group)end end);duplicate:SetPoint("LEFT",new,"RIGHT",4,0)
 local del=HolyStorm.PolicyUI:Button(p,L["DELETE"],70,function()if Page.draft then StaticPopup_Show("HOLYSTORM_GROUP_DELETE",HolyStorm.PolicyUI:DisplayGroupName(Page.draft),nil,Page.draft.id)end end);del:SetPoint("TOPLEFT",14,-530);del:SetEnabled(false);self.deleteButton=del
 self.empty=HolyStorm.PolicyUI:Label(p,L["NO_SELECTION"],"GameFontHighlight");self.empty:SetPoint("TOPLEFT",235,-100);self.tabFrames={};self.tabButtons={};for i,id in ipairs(tabs)do local tabId=id;local button=HolyStorm.PolicyUI:Button(p,L[tabId],122,function()Page:ShowTab(tabId)end);local column=(i-1)%5;local row=math.floor((i-1)/5);button:SetPoint("TOPLEFT",220+column*124,-42-row*27);self.tabButtons[tabId]=button;local frame=CreateFrame("Frame",nil,p);frame:SetPoint("TOPLEFT",225,-102);frame:SetPoint("BOTTOMRIGHT",-14,82);frame:Hide();self.tabFrames[tabId]=frame end
 local general=self.tabFrames.GENERAL;local nl=HolyStorm.PolicyUI:Label(general,L["NAME"]);nl:SetPoint("TOPLEFT");self.nameEdit=HolyStorm.PolicyUI:Edit(general,300);self.nameEdit:SetPoint("TOPLEFT",0,-20);local dl=HolyStorm.PolicyUI:Label(general,L["DESCRIPTION"]);dl:SetPoint("TOPLEFT",0,-55);self.descEdit=HolyStorm.PolicyUI:Edit(general,500);self.descEdit:SetPoint("TOPLEFT",0,-75);self.generalInfo=HolyStorm.PolicyUI:Label(general,"");self.generalInfo:SetPoint("TOPLEFT",0,-115)
 local members=self.tabFrames.MEMBERS;self.memberText=HolyStorm.PolicyUI:Label(members,"");self.memberText:SetPoint("TOPLEFT");self.memberText:SetPoint("RIGHT");self.characterSelector=HolyStorm.PolicyUI:CreateSelector(members,210,function()return HolyStorm.PolicyUI:CharacterItems()end);self.characterSelector:SetPoint("BOTTOMLEFT",-15,8);local addCharacter=HolyStorm.PolicyUI:Button(members,L["ADD_CHARACTER"],125,function()local id=Page.characterSelector:GetValue();if Page.draft and id then Page.draft.characterMembers[id]=true;Page:RefreshDetails()end end);addCharacter:SetPoint("LEFT",self.characterSelector,"RIGHT",-12,0);self.addCharacterButton=addCharacter;self.accountSelector=HolyStorm.PolicyUI:CreateSelector(members,210,function()return HolyStorm.PolicyUI:AccountItems()end);self.accountSelector:SetPoint("LEFT",addCharacter,"RIGHT",-12,0);local addAccount=HolyStorm.PolicyUI:Button(members,L["ADD_ACCOUNT"],115,function()local id=Page.accountSelector:GetValue();if Page.draft and id then Page.draft.accountMembers[id]=true;Page:RefreshDetails()end end);addAccount:SetPoint("LEFT",self.accountSelector,"RIGHT",-12,0);self.addAccountButton=addAccount;self.removeSource=HolyStorm.PolicyUI:CreateSelector(members,210,function()local out={};if Page.draft then for id in pairs(Page.draft.characterMembers)do out[#out+1]={value="character\031"..id,label=L["CHARACTER"]..": "..id}end;for id in pairs(Page.draft.accountMembers)do out[#out+1]={value="account\031"..id,label=L["ACCOUNT_MEMBERS"]..": "..id}end;for id in pairs(Page.draft.guildRanks)do out[#out+1]={value="guild-rank\031"..id,label=L["GUILD_RANK"]..": "..id}end end;return out end);self.removeSource:SetPoint("BOTTOMLEFT",-15,-22);local removeMembership=HolyStorm.PolicyUI:Button(members,L["REMOVE_SOURCE"],145,function()local source,id=tostring(Page.removeSource:GetValue()or""):match("^(.-)\031(.+)$");if Page.draft and source then local map=source=="character"and Page.draft.characterMembers or source=="account"and Page.draft.accountMembers or Page.draft.guildRanks;map[tonumber(id)or id]=nil;Page:RefreshDetails()end end);removeMembership:SetPoint("LEFT",self.removeSource,"RIGHT",-12,0);self.removeMembershipButton=removeMembership;self.rankSelector=HolyStorm.PolicyUI:CreateSelector(members,180,function()local out={};local guild=HolyStorm.Data.GuildStore:GetCurrent();for index,name in pairs(guild and guild.ranks or{})do out[#out+1]={value=index-1,label=name}end;return out end);self.rankSelector:SetPoint("LEFT",removeMembership,"RIGHT",-12,0);self.addRankButton=HolyStorm.PolicyUI:Button(members,L["ADD_GUILD_RANK"],120,function()local rank=Page.rankSelector:GetValue();if Page.draft and rank~=nil then Page.draft.guildRanks[rank]=true;Page:RefreshDetails()end end);self.addRankButton:SetPoint("LEFT",self.rankSelector,"RIGHT",-12,0)
 local permissions=self.tabFrames.PERMISSIONS;self.permissionSearch=HolyStorm.PolicyUI:Edit(permissions,240,function()Page:EnsurePermissionChecks();Page:RefreshDetails()end);self.permissionSearch:SetPoint("TOPLEFT");local permissionScroll=CreateFrame("ScrollFrame",nil,permissions,"UIPanelScrollFrameTemplate");permissionScroll:SetPoint("TOPLEFT",0,-28);permissionScroll:SetPoint("BOTTOMRIGHT",-28,26);local permissionContent=CreateFrame("Frame",nil,permissionScroll);permissionContent:SetSize(680,1000);permissionScroll:SetScrollChild(permissionContent);self.permissionsFrame=permissionContent;self.permissionChecks={};self.fullAccess=HolyStorm.PolicyUI:Label(permissions,L["FULL_ACCESS"].." — "..L["FULL_ACCESS_HELP"]);self.fullAccess:SetPoint("BOTTOMLEFT");self:EnsurePermissionChecks()
 local rf=self.tabFrames.RULES_FILTERS;local rl=HolyStorm.PolicyUI:Label(rf,L["RULES_TITLE"]);rl:SetPoint("TOPLEFT");self.ruleList=HolyStorm.PolicyUI:CreateCheckList(rf,function()local out={};for id,rule in pairs(Filters:GetRules("global"))do out[#out+1]={value=id,label=rule.name,checked=Page.draft and tContains(Page.draft.ruleIds,id)}end;table.sort(out,function(a,b)return a.label<b.label end);return out end,function(id,checked)if Page.draft then local set={};for _,v in ipairs(Page.draft.ruleIds)do set[v]=true end;set[id]=checked or nil;Page.draft.ruleIds=keys(set)end end);self.ruleList:SetPoint("TOPLEFT",0,-25);self.ruleList:SetSize(300,400);local fl=HolyStorm.PolicyUI:Label(rf,L["FILTERS_TITLE"]);fl:SetPoint("TOPLEFT",330,0);self.filterMode=HolyStorm.PolicyUI:CreateSelector(rf,130,function()return{{value="AND",label=L["LOGIC_AND"]},{value="OR",label=L["LOGIC_OR"]}}end,function(v)if Page.draft then Page.draft.filterOperator=v end end);self.filterMode:SetPoint("TOPLEFT",315,-18);self.filterList=HolyStorm.PolicyUI:CreateCheckList(rf,function()local out={};for id,filter in pairs(Filters:GetFilters("global"))do out[#out+1]={value=id,label=filter.name,checked=Page.draft and tContains(Page.draft.filterIds,id)}end;table.sort(out,function(a,b)return a.label<b.label end);return out end,function(id,checked)if Page.draft then local set={};for _,v in ipairs(Page.draft.filterIds)do set[v]=true end;set[id]=checked or nil;Page.draft.filterIds=keys(set)end end);self.filterList:SetPoint("TOPLEFT",330,-62);self.filterList:SetSize(300,365)
 local managers=self.tabFrames.MANAGERS;local ml=HolyStorm.PolicyUI:Label(managers,L["MANAGER_GROUPS"]);ml:SetPoint("TOPLEFT");local mh=HolyStorm.PolicyUI:Label(managers,L["MANAGEMENT_HELP"]);mh:SetPoint("TOPLEFT",0,-24);mh:SetPoint("RIGHT");self.managerList=HolyStorm.PolicyUI:CreateCheckList(managers,function()local out={};for _,item in ipairs(HolyStorm.PolicyUI:GroupItems(Page.draft and Page.draft.id))do item.checked=Page.draft and tContains(Page.draft.managerGroupIds,item.value);out[#out+1]=item end;return out end,function(id,checked)if Page.draft then local set={};for _,v in ipairs(Page.draft.managerGroupIds)do set[v]=true end;set[id]=checked or nil;Page.draft.managerGroupIds=keys(set)end end);self.managerList:SetPoint("TOPLEFT",0,-55)
 self.memberSearch=HolyStorm.PolicyUI:Edit(self.tabFrames.EFFECTIVE_MEMBERS,240,function()Page:RefreshDetails()end);self.memberSearch:SetPoint("TOPLEFT");local effectiveScroll,effectiveText=HolyStorm.PolicyUI:CreateTextPanel(self.tabFrames.EFFECTIVE_MEMBERS);effectiveScroll:SetPoint("TOPLEFT",0,-30);effectiveScroll:SetPoint("BOTTOMRIGHT");self.effectiveText=effectiveText
 local matrixScroll,matrixText=HolyStorm.PolicyUI:CreateTextPanel(self.tabFrames.PERMISSION_MATRIX);matrixScroll:SetAllPoints();self.matrixText=matrixText
 local moduleHelp=HolyStorm.PolicyUI:Label(self.tabFrames.MODULE_SETTINGS,L["MODULE_MODEL_HELP"]);moduleHelp:SetPoint("TOPLEFT");moduleHelp:SetPoint("RIGHT");self.moduleList=HolyStorm.PolicyUI:CreateCheckList(self.tabFrames.MODULE_SETTINGS,function()local out={};for _,meta in ipairs(HolyStorm:GetModuleEntries())do local id=meta and meta.internalName;if id and meta.category=="optional"then out[#out+1]={value=id,label=meta.displayName or id,checked=State:IsGuildModuleEnabled(id),disabled=not Page:CanMutate("modules-manage")}end end;return out end,function(id,checked)local ok,err=State:SetGuildModuleEnabled(id,checked);if not ok then HolyStorm.Events:Emit("HS_UI_STATUS_REQUESTED",tostring(err))end end);self.moduleList:SetPoint("TOPLEFT",0,-38)
 local analysis=self.tabFrames.ANALYSIS;self.analysisGuid=HolyStorm.PolicyUI:Edit(analysis,300);self.analysisGuid:SetPoint("TOPLEFT");local analyze=HolyStorm.PolicyUI:Button(analysis,L["ANALYSIS"],90,function()Page:Analyze()end);analyze:SetPoint("LEFT",self.analysisGuid,"RIGHT",5,0);self.analysisText=HolyStorm.PolicyUI:Label(analysis,"");self.analysisText:SetPoint("TOPLEFT",0,-38);self.analysisText:SetPoint("RIGHT");self.statusText=HolyStorm.PolicyUI:Label(self.tabFrames.STATUS,"");self.statusText:SetPoint("TOPLEFT");self.statusText:SetPoint("RIGHT")
 local save=HolyStorm.PolicyUI:Button(p,L["SAVE"],100,function()Page:Save()end);save:SetPoint("BOTTOMRIGHT",-120,18);self.saveButton=save;local discard=HolyStorm.PolicyUI:Button(p,L["DISCARD"],100,function()local group=Page.selectedId and Groups:GetGroup(Page.selectedId);Page:Select(group);HolyStorm.Events:Emit("HS_UI_STATUS_REQUESTED",L["DISCARDED"])end);discard:SetPoint("LEFT",save,"RIGHT",6,0);local reset=HolyStorm.PolicyUI:Button(p,L["RESTORE_DEFAULTS"],150,function()StaticPopup_Show("HOLYSTORM_PERMISSION_RESET")end);reset:SetPoint("BOTTOMLEFT",225,18);self.resetButton=reset;self.readOnly=HolyStorm.PolicyUI:Label(p,"");self.readOnly:SetPoint("BOTTOMLEFT",225,48);self.readOnly:SetPoint("RIGHT",-14,0)
 StaticPopupDialogs["HOLYSTORM_PERMISSION_RESET"]={text=L["CONFIRM_PERMISSION_RESET"],button1=L["YES"],button2=L["NO"],OnAccept=function()local ok,err=State:RestoreDefaults();HolyStorm.Events:Emit("HS_UI_STATUS_REQUESTED",ok and L["RESET_COMPLETE"]or tostring(err));Page:Render()end,timeout=0,whileDead=true,hideOnEscape=true,preferredIndex=3}
 StaticPopupDialogs["HOLYSTORM_GROUP_DELETE"]={text=L["CONFIRM_GROUP_DELETE"],button1=L["DELETE"],button2=L["NO"],OnAccept=function(_,id)local ok,err=Groups:DeleteGroup(id);if ok then Page:Select(nil);Page:RefreshList()else HolyStorm.Events:Emit("HS_UI_STATUS_REQUESTED",err=="SYSTEM_GROUP"and L["CANNOT_DELETE_SYSTEM"]or err=="GROUP_IN_USE"and L["GROUP_IN_USE"]or tostring(err))end end,timeout=0,whileDead=true,hideOnEscape=true,preferredIndex=3}
 self.activeTab="GENERAL";HolyStorm.Administration:RegisterSection({id="permissions",displayName=L["PERMISSIONS_TITLE"],displayNameKey="PERMISSIONS_TITLE",description=L["PERMISSIONS_DESC"],descriptionKey="PERMISSIONS_DESC",order=14,requiredPermission={"groups-create","groups-edit","groups-delete","groups-manage-members","permissions-manage","permissions-reset","modules-manage","policy-inspect"},owner="Core",page=p,icon="Interface\\Icons\\Achievement_GuildPerk_EverybodysFriend",render=function()Page:Render()end,events={"HS_GROUP_UPDATED","HS_GROUP_DELETED","HS_EFFECTIVE_MEMBERSHIP_CHANGED","HS_EFFECTIVE_PERMISSIONS_CHANGED","HS_FILTER_UPDATED","HS_PERMISSION_REGISTERED","HS_PERMISSIONS_STATE_UPDATED","HS_PERMISSIONS_CATCHUP_STARTED","HS_PERMISSIONS_CATCHUP_COMPLETED","HS_PERMISSIONS_RECOVERY_REQUIRED","HS_PERMISSIONS_CONFLICT_DETECTED"}})
end
