local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm")
local L=LibStub("AceLocale-3.0"):GetLocale("Holy_Storm_Policy")
local Page=HolyStorm:RegisterRequiredModule("PolicyInspectorUI")
local Engine,Filters,State,Registry=HolyStorm.PermissionEngine,HolyStorm.FilterManager,HolyStorm.PolicyState,HolyStorm.PermissionRegistry
local DEFAULT_SCOPE="global"
HolyStorm:ApplyModuleMetadata(Page,{displayName=L["INSPECTOR_TITLE"],internalName="policyInspectorUI",version="2.2.0",category="required",description=L["INSPECTOR_DESC"],permissions={"policy-inspect"},dependencies={"core","ui"},enabledByDefault=true})
local function displayReason(reason)return HolyStorm.PolicyUI:DisplayMembershipReason(reason)end
local function defaultPermission()local ids={};for id in pairs(Registry:GetPermissions())do ids[#ids+1]=id end;table.sort(ids);return ids[1]or""end
local function displayTime(value)value=tonumber(value);return value and value>0 and date("%Y-%m-%d %H:%M:%S",value)or"—"end
function Page:Inspect()
 local guid=self.character:GetValue()or UnitGUID("player");local accountUUID=guid and(HolyStorm.TwinkCore:GetAccountUUIDForCharacter(guid)or HolyStorm.Data.PlayerStore:GetCharacterOwner(guid));local permission=self.permission:GetText();local explanation=Engine:Explain(permission,accountUUID,guid,self.target:GetText());local state=State:GetPermissionStateStatus();local actor=state.changedBy and table.concat({state.changedBy.accountUUID or"-",state.changedBy.characterUUID or"-"}," / ")or"-";local missing=state.missingRevisions and tostring(state.missingRevisions.after or"-").." -> "..tostring(state.missingRevisions.target or"-")or"-";local fork=state.fork and tostring(state.fork.localRevision or"-").." <> "..tostring(state.fork.remoteRevision or"-")or"-";local lines={L["IDENTITY"],L["CHARACTER"]..": "..tostring(guid),L["ACCOUNT_MEMBERS"]..": "..tostring(accountUUID),"",string.format(L["STATE_DETAILS_FORMAT"],tostring(state.guildId or"-"),L["STATE_"..tostring(state.status)]or tostring(state.status),state.version or 0,tostring(state.revisionID or"-"),tostring(state.previousRevisionID or"-"),displayTime(state.lastSync),actor,displayTime(state.changedAt),state.historyLength or 0,state.rejectedLength or 0,missing,fork),L["RESULT"]..": "..(explanation.allowed and L["ALLOWED"]or L["DENIED"]),"",L["EFFECTIVE_MEMBERS"]}
 for id,group in pairs(explanation.groups)do local sources={};for _,reason in ipairs(group.reasons or{})do sources[#sources+1]=displayReason(reason)end;lines[#lines+1]=string.format("• %s (%s) — %s",HolyStorm.PolicyUI:DisplayGroupName(group),id,table.concat(sources,", "))end
 lines[#lines+1]="";lines[#lines+1]=L["SOURCES"];for _,grant in ipairs(explanation.grants)do lines[#lines+1]="✓ "..HolyStorm.PolicyUI:DisplayGroupName(grant) end;if#explanation.grants==0 then lines[#lines+1]="— "..L["NONE"]end
 local filterId=self.filter:GetText();if filterId~=""then local result,trace,status=Filters:ApplyFilter(filterId,{guid=guid},self.filterScope:GetText()=="local"and"local"or"global");local label=status==HolyStorm.Rules.Result.UNKNOWN and L["UNKNOWN"]or result and L["PASSED"]or L["FAILED"];lines[#lines+1]="";lines[#lines+1]=L["FILTER_REASON"].." "..filterId..": "..label;lines[#lines+1]=HolyStorm.PolicyUI:FlattenTrace(trace)end
 lines[#lines+1]="";lines[#lines+1]=L["REVISION_HISTORY"];for _,revision in ipairs(State:GetRevisionHistory())do lines[#lines+1]=string.format("v%d | %s | %s | %s | %s",revision.version or 0,tostring(revision.revisionID),tostring(revision.previousRevisionID),tostring(revision.action or(revision.change and revision.change.action)),displayTime(revision.changedAt))end
 lines[#lines+1]="";lines[#lines+1]=L["REJECTED_REVISIONS"];for _,rejected in ipairs(State:GetRejectedRevisions())do lines[#lines+1]=string.format("%s | %s | %s | %s",tostring(rejected.revisionID),tostring(rejected.sender),tostring(rejected.reason),displayTime(rejected.timestamp))end
 if state.missingRevisions or state.recovery or state.fork then lines[#lines+1]="";lines[#lines+1]=L["STATUS"]..": "..tostring(state.catchupReason or(state.recovery and state.recovery.reason)or(state.fork and state.fork.reason)or state.status)end;self.output:SetText(table.concat(lines,"\n"))
end
function Page:OnInitialize()
 local UI=HolyStorm:GetModule("UI",true);local p=CreateFrame("Frame",nil,UI.content);self.page=p;local title=HolyStorm.PolicyUI:Label(p,L["INSPECTOR_TITLE"],"GameFontHighlightLarge");title:SetPoint("TOPLEFT",14,-12)
 self.character=HolyStorm.PolicyUI:CreateSelector(p,260,function()return HolyStorm.PolicyUI:CharacterItems()end);self.character:SetPoint("TOPLEFT",-2,-48);self.permission=HolyStorm.PolicyUI:Edit(p,220);self.permission:SetPoint("TOPLEFT",295,-64);self.permission:SetText(defaultPermission());self.target=HolyStorm.PolicyUI:Edit(p,180);self.target:SetPoint("TOPLEFT",526,-64);self.filter=HolyStorm.PolicyUI:Edit(p,180);self.filter:SetPoint("TOPLEFT",717,-64);self.filterScope=HolyStorm.PolicyUI:Edit(p,75);self.filterScope:SetPoint("TOPLEFT",908,-64);self.filterScope:SetText(DEFAULT_SCOPE)
 local inspect=HolyStorm.PolicyUI:Button(p,L["ANALYSIS"],100,function()Page:Inspect()end);inspect:SetPoint("TOPLEFT",14,-100);local scroll,text=HolyStorm.PolicyUI:CreateTextPanel(p);scroll:SetPoint("TOPLEFT",14,-132);scroll:SetPoint("BOTTOMRIGHT",-28,18);self.output=text;HolyStorm.Administration:RegisterSection({id="policyInspector",category="system",displayName=L["INSPECTOR_TITLE"],displayNameKey="INSPECTOR_TITLE",description=L["INSPECTOR_DESC"],descriptionKey="INSPECTOR_DESC",order=10,requiredPermission="policy-inspect",owner="Core",page=p,refresh=function()Page:Inspect()end,events={"HS_POLICY_UPDATED","HS_PERMISSIONS_REVISION_REJECTED","HS_PERMISSIONS_CONFLICT_DETECTED","HS_PERMISSIONS_RECOVERY_REQUIRED"},icon="Interface\\Icons\\INV_Misc_Eye_01"})
end
