local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm");local L=LibStub("AceLocale-3.0"):GetLocale("Holy_Storm_Policy");local Page=HolyStorm:RegisterRequiredModule("RulesUI")
local Filters,State,Engine=HolyStorm.FilterManager,HolyStorm.PolicyState,HolyStorm.PermissionEngine
HolyStorm:ApplyModuleMetadata(Page,{displayName=L["RULES_TITLE"],internalName="rulesUI",version="1.1.0",category="required",description=L["RULES_DESC"],permissions={"rules-manage"},dependencies={"core","ui"},enabledByDefault=true})
function Page:Items()local out={};local query=string.lower(self.search and self.search:GetText()or"");for _,rule in pairs(Filters:GetRules(self.scope))do if query==""or string.lower((rule.name or"").." "..rule.id):find(query,1,true)then out[#out+1]=rule end end;table.sort(out,function(a,b)return a.name<b.name end);return out end
function Page:Select(rule)self.selectedId=rule and rule.id;self.isNew=rule and Filters:GetRules(self.scope)[rule.id]==nil or false;self.draft=rule and HolyStorm.Utils.DeepCopy(rule)or nil;self.baseRevision=State:GetPermissionStateStatus().revisionID;if self.draft then self.name:SetText(self.draft.name);self.description:SetText(self.draft.description or"");self.builder:SetRule(self.draft.root or self.draft.rules);self:ShowUsage()end end
function Page:Render()if not self.page:IsShown()then return end;local root=Filters:GetRules(self.scope);if self.selectedId and not root[self.selectedId]and not self.isNew then self:Select(nil)end;self.list:SetItems(self:Items(),function(rule)return rule.name.."  v"..(rule.version or 0)end);if self.selectedId and not self.draft then self:Select(root[self.selectedId])end;local valid=self.scope~="global"or State:GetPermissionStateStatus().status==State.status.VALID;local allowed=self.scope~="global"or Engine:HasPermission(nil,nil,"rules-manage");self.newButton:SetEnabled(valid and allowed);self.saveButton:SetEnabled(valid and allowed and self.draft~=nil);self.deleteButton:SetEnabled(valid and allowed and self.draft~=nil and not self.isNew)end
function Page:ShowUsage()local lines={L["USAGE"]..":"};for _,usage in ipairs(Filters:GetUsage("rules",self.draft and self.draft.id))do lines[#lines+1]=usage.kind..": "..usage.id end;self.usage:SetText(table.concat(lines,"\n"))end
function Page:Save()if not self.draft then return end;local valid,err=self.builder:Validate();if not valid then HolyStorm.Events:Emit("HS_UI_STATUS_REQUESTED",string.format(L["INVALID_EXPRESSION"],tostring(err)));return end;if self.scope=="global"and self.baseRevision~=State:GetPermissionStateStatus().revisionID then HolyStorm.Events:Emit("HS_UI_STATUS_REQUESTED",L["STALE_EDITOR"]);return end;self.draft.name=self.name:GetText();self.draft.description=self.description:GetText();self.draft.root=self.builder:GetRule();local ok,result=Filters:SaveRule(self.draft,self.scope);if ok then self:Select(result);self:Render()else HolyStorm.Events:Emit("HS_UI_STATUS_REQUESTED",string.format(L["INVALID"],tostring(result)))end end
function Page:Test()if not self.draft then return end;local rule=HolyStorm.Utils.DeepCopy(self.draft);rule.root=self.builder:GetRule();local result,trace,status=Filters:EvaluateRule(rule,Engine:BuildContext(nil,UnitGUID("player")));local label=status==HolyStorm.Rules.Result.UNKNOWN and L["UNKNOWN"]or result and L["PASSED"]or L["FAILED"];self.testText:SetText(label.."\n"..HolyStorm.PolicyUI:FlattenTrace(trace))end
function Page:SetScope(scope)self.scope=scope;self.selectedId=nil;self.draft=nil;self.localButton:SetEnabled(scope~="local");self.globalButton:SetEnabled(scope~="global");self:Render()end
function Page:OnInitialize()local UI=HolyStorm:GetModule("UI",true);local p=CreateFrame("Frame",nil,UI.content);self.page=p;local title=HolyStorm.PolicyUI:Label(p,L["RULES_TITLE"],"GameFontHighlightLarge");title:SetPoint("TOPLEFT",14,-12);self.localButton=HolyStorm.PolicyUI:Button(p,L["LOCAL_RULES"],120,function()Page:SetScope("local")end);self.localButton:SetPoint("TOPLEFT",14,-40);self.globalButton=HolyStorm.PolicyUI:Button(p,L["GLOBAL_RULES"],120,function()Page:SetScope("global")end);self.globalButton:SetPoint("LEFT",self.localButton,"RIGHT",4,0)
 self.search=HolyStorm.PolicyUI:Edit(p,190,function()Page:Render()end);self.search:SetPoint("TOPLEFT",14,-72);self.list=HolyStorm.PolicyUI:CreateList(p,function(rule)Page:Select(rule)end);self.list:SetPoint("TOPLEFT",14,-100);self.list:SetSize(200,420);local new=HolyStorm.PolicyUI:Button(p,L["NEW"],62,function()Page:Select({id=HolyStorm.PolicyUI:NewId("rule"),name=L["NEW"],description="",root={logic="AND",children={{field="character.level",operator=">=",value=1}}}})end);new:SetPoint("BOTTOMLEFT",14,18);self.newButton=new;local duplicate=HolyStorm.PolicyUI:Button(p,L["DUPLICATE"],90,function()if Page.draft then local d=HolyStorm.Utils.DeepCopy(Page.draft);d.id=HolyStorm.PolicyUI:NewId("rule");d.name=d.name.." "..L["COPY_SUFFIX"];d.version=0;Page:Select(d)end end);duplicate:SetPoint("LEFT",new,"RIGHT",4,0);local del=HolyStorm.PolicyUI:Button(p,L["DELETE"],70,function()if Page.draft then local ok,err=Filters:DeleteRule(Page.draft.id,Page.scope);if ok then Page:Select(nil);Page:Render()else HolyStorm.Events:Emit("HS_UI_STATUS_REQUESTED",err=="RULE_IN_USE"and L["RULE_IN_USE"]or tostring(err))end end end);del:SetPoint("LEFT",duplicate,"RIGHT",4,0);self.deleteButton=del
 local nameLabel=HolyStorm.PolicyUI:Label(p,L["NAME"]);nameLabel:SetPoint("TOPLEFT",225,-46);self.name=HolyStorm.PolicyUI:Edit(p,260);self.name:SetPoint("TOPLEFT",225,-64);local descLabel=HolyStorm.PolicyUI:Label(p,L["DESCRIPTION"]);descLabel:SetPoint("LEFT",self.name,"RIGHT",12,18);self.description=HolyStorm.PolicyUI:Edit(p,330);self.description:SetPoint("LEFT",self.name,"RIGHT",12,0);self.builder=HolyStorm.PolicyUI:CreateRuleBuilder(p);self.builder:SetPoint("TOPLEFT",225,-100);self.builder:SetPoint("BOTTOMRIGHT",-14,150);self.usage=HolyStorm.PolicyUI:Label(p,"");self.usage:SetPoint("BOTTOMLEFT",225,74);self.testText=HolyStorm.PolicyUI:Label(p,"");self.testText:SetPoint("BOTTOMLEFT",500,44);self.testText:SetPoint("RIGHT",-14,0)
 local save=HolyStorm.PolicyUI:Button(p,L["SAVE"],90,function()Page:Save()end);save:SetPoint("BOTTOMLEFT",225,18);self.saveButton=save;local discard=HolyStorm.PolicyUI:Button(p,L["DISCARD"],90,function()Page.draft=nil;Page:Select(Page.selectedId and Filters:GetRules(Page.scope)[Page.selectedId])end);discard:SetPoint("LEFT",save,"RIGHT",5,0);local test=HolyStorm.PolicyUI:Button(p,L["TEST"],90,function()Page:Test()end);test:SetPoint("LEFT",discard,"RIGHT",5,0)
 self.scope="local";HolyStorm.Administration:RegisterSection({id="rules",displayName=L["RULES_TITLE"],displayNameKey="RULES_TITLE",description=L["RULES_DESC"],descriptionKey="RULES_DESC",order=15,requiredPermission="rules-manage",owner="Core",page=p,render=function()Page:Render()end,events={"HS_RULE_UPDATED","HS_RULE_DELETED","HS_PERMISSIONS_STATE_UPDATED"},icon="Interface\\Icons\\INV_Inscription_Tradeskill01"})end
