local addonVersion="2.2.0"
local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm");local L=LibStub("AceLocale-3.0"):GetLocale("Holy_Storm_Dungeons")
if HolyStorm.PermissionRegistry then HolyStorm.PermissionRegistry:RegisterLegacyAlias("mythicplus.read","mythicplus-read")end
local function validateMythicPlus(data)
 if type(data)~="table"then return false,"INVALID_MYTHICPLUS_DATA"end
 if data.dungeons~=nil and type(data.dungeons)~="table"then return false,"INVALID_MYTHICPLUS_DUNGEONS"end
 local dungeonCount=0;for _,dungeon in pairs(type(data.dungeons)=="table"and data.dungeons or{})do if type(dungeon)~="table"then return false,"INVALID_MYTHICPLUS_DUNGEON"end;dungeonCount=dungeonCount+1 end
 if data.seasonId==nil and data.overallScore==nil and data.ownedKey==nil and dungeonCount==0 then return false,"EMPTY_MYTHICPLUS_DATA"end
 if data.ownedKey~=nil and type(data.ownedKey)~="table"then return false,"INVALID_MYTHICPLUS_KEY"end
 if(tonumber(data.snapshotVersion)or 0)>=3 then if not tonumber(data.seasonId)or tonumber(data.seasonId)<=0 or dungeonCount==0 then return false,"INCOMPLETE_MYTHICPLUS_DATA"end;for _,dungeon in pairs(data.dungeons)do if not dungeon.name or not dungeon.challengeMapId or not dungeon.timeLimit then return false,"INCOMPLETE_MYTHICPLUS_DUNGEON"end end;if(tonumber(data.overallScore)or 0)>0 and data.scoreDataReady~=true then return false,"INCOMPLETE_MYTHICPLUS_SCORES"end end
 return true
end
if HolyStorm.PlayerData then HolyStorm.PlayerData:RegisterBlock("mythicPlus",{fields={"mythicPlus"},event="HS_MYTHICPLUS_UPDATED",staleAfter=21600,validate=validateMythicPlus})end
local metadata={id="mythicPlus",name="MythicPlus",displayName=L["DISPLAY_NAME"],description=L["DESCRIPTION"],version=addonVersion,moduleType="feature",category="feature",permissions={{id="mythicplus-read",category="Mythic+",defaults={member=true}},"sync-send","sync-receive"},dependencies={"core"},capabilities={"character.scan.mythicplus"},ui={},options={},administration={},data={block="mythicPlus",snapshotType="mythicplus",schemaVersion=3,capability="character.scan.mythicplus"},sync={domains={"character"}},enabledByDefault=true,ruleFields={{id="mythicplus.rating",aliases={"mythicScore"},type="number",name=L["RULE_FIELD_RATING"],nameKey="RULE_FIELD_RATING",description=L["RULE_FIELD_RATING_DESC"],descriptionKey="RULE_FIELD_RATING_DESC",category=L["DISPLAY_NAME"],dependencies={"mythicPlus"},unit="rating",resolver=function(context)local block=context.character and context.character.mythicPlus or HolyStorm.Data.CharacterStore:GetBlock(context.characterUUID,"mythicPlus");return block and tonumber(block.overallScore)or nil end}}}
local function plain(v,depth) if type(v)~="table"then return (type(v)=="string"or type(v)=="number"or type(v)=="boolean")and v or nil end;if depth>5 then return nil end;local r={};for k,x in pairs(v)do if type(k)=="string"or type(k)=="number"then r[k]=plain(x,depth+1)end end;return r end
local function affixNameKey(value)return type(value)=="string"and value:lower():gsub("|c%x%x%x%x%x%x%x%x",""):gsub("|r",""):gsub("[%s%p%c]+","")or nil end
local function snapshotAffixScores(scores)local result=plain(scores,0);if type(result)~="table"then return result end;local categories={[affixNameKey(L["TYRANNICAL"]) ]="TYRANNICAL",[affixNameKey(L["FORTIFIED"]) ]="FORTIFIED"};for _,entry in pairs(result)do if type(entry)=="table"then entry.category=categories[affixNameKey(entry.name)]end end;return result end
local function bestRun(intime,overtime,affixScores)
 local best;local function consider(entry,overTime)local score=entry and tonumber(entry.dungeonScore or entry.score or entry.seasonScore);local level=entry and tonumber(entry.level or entry.bestLevel);if level and level>0 and(not best or(score or 0)>(best.score or 0)or((score or 0)==(best.score or 0)and level>(best.level or 0)))then best={level=level,score=score or 0,durationSec=tonumber(entry.durationSec),overTime=overTime==true or entry.overTime==true}end end
 consider(intime,false);consider(overtime,true);for _,entry in pairs(type(affixScores)=="table"and affixScores or{})do consider(entry,entry.overTime)end;return best
end
HolyStorm:RegisterModule(metadata,function(Module)
 HolyStorm:ApplyModuleMetadata(Module,metadata)
 function Module:GetCharacterSnapshot(guid)return HolyStorm.Data.CharacterStore:GetBlock(guid,"mythicPlus")end
 function Module:RequestData(force)
  if self.initialDataRequested and not force then return false end;self.initialDataRequested=true;local mp=C_MythicPlus;if not mp then return false end;local requested=false;if mp.RequestCurrentAffixes then mp.RequestCurrentAffixes();requested=true end;if mp.RequestMapInfo then mp.RequestMapInfo();requested=true end;if mp.RequestRewards then mp.RequestRewards();requested=true end;return requested
 end
 function Module:Collect()
  local mp,cm=C_MythicPlus,C_ChallengeMode;if not mp or not cm then return nil end
  local s={seasonId=mp.GetCurrentSeason and mp.GetCurrentSeason(),displaySeasonId=mp.GetCurrentUIDisplaySeason and mp.GetCurrentUIDisplaySeason(),overallScore=cm.GetOverallDungeonScore and cm.GetOverallDungeonScore()or 0,dungeons={},affixes={},updatedAt=HolyStorm.Utils.Now(),snapshotVersion=3}
  s.ownedKey={level=mp.GetOwnedKeystoneLevel and mp.GetOwnedKeystoneLevel()or 0,challengeMapId=mp.GetOwnedKeystoneChallengeMapID and mp.GetOwnedKeystoneChallengeMapID()or 0,mapId=mp.GetOwnedKeystoneMapID and mp.GetOwnedKeystoneMapID()or 0}
  for _,a in ipairs(mp.GetCurrentAffixes and mp.GetCurrentAffixes()or{})do local id=type(a)=="table"and a.id or a;local n,d,icon=cm.GetAffixInfo(id);s.affixes[#s.affixes+1]={id=id,name=n,description=d,icon=icon}end
  local hasDungeonScore=false;for _,id in ipairs(cm.GetMapTable and cm.GetMapTable()or{})do local name,instanceId,timeLimit,texture,background,mapId=cm.GetMapUIInfo(id);local intime,overtime;if mp.GetSeasonBestForMap then intime,overtime=mp.GetSeasonBestForMap(id)end;local scores,overall;if mp.GetSeasonBestAffixScoreInfoForMap then scores,overall=mp.GetSeasonBestAffixScoreInfoForMap(id)end;local best=bestRun(intime,overtime,scores);local score=tonumber(overall)or(best and best.score)or 0;if score>0 or(best and best.level and best.level>0)then hasDungeonScore=true end;s.dungeons[#s.dungeons+1]={challengeMapId=id,name=name,instanceId=instanceId,mapId=mapId,timeLimit=timeLimit,texture=texture,background=background,bestInTime=plain(intime,0),bestOverTime=plain(overtime,0),affixScores=snapshotAffixScores(scores),bestRun=plain(best,0),score=score}end
  s.scoreDataReady=(tonumber(s.overallScore)or 0)<=0 or hasDungeonScore
  table.sort(s.dungeons,function(a,b)return(a.name or"")<(b.name or"")end);return s
 end
 function Module:Validate(s)if type(s)~="table"then return false,"API unavailable"end;if not tonumber(s.seasonId)or tonumber(s.seasonId)<=0 then return false,"season unavailable"end;if type(s.dungeons)~="table"or next(s.dungeons)==nil then return false,"dungeon pool unavailable"end;for _,d in pairs(s.dungeons)do if type(d)~="table"or not d.name or not d.challengeMapId or not d.timeLimit then return false,"map data incomplete"end end;if(tonumber(s.overallScore)or 0)>0 and s.scoreDataReady~=true then return false,"dungeon scores pending"end;return true end
 function Module:Commit(s)local guid=UnitGUID("player");return HolyStorm.PlayerData:WriteOwnedBlock(guid,"mythicPlus",s,"blizzard")end
 function Module:Queue(sync,delay)return HolyStorm.Snapshots:Queue("mythicplus",function()return Module:Collect()end,function(s)return Module:Validate(s)end,function(s,f)return Module:Commit(s,f,sync)end,{source="MythicPlus",delay=delay or 1.5,retryDelay=2.5,priority=4})end
 function Module:RefreshPage()if not self.page or not self.page:IsShown()then return end;local r=HolyStorm.Data.CharacterStore:Get(UnitGUID("player"));local d=r and r.mythicPlus;if not d then self.text:SetText(L["NO_MYTHIC_DATA"]);return end;local lines={string.format("Season %s  |  Score %.1f",d.seasonId or"-",d.overallScore or 0)};for _,x in ipairs(d.dungeons or{})do lines[#lines+1]=string.format("%s  +%s  %.1f",x.name or"-",x.bestInTime and x.bestInTime.level or"-",x.score or 0)end;self.text:SetText(table.concat(lines,"\n"))end
 function Module:OnInitialize()
  HolyStorm.CharacterScans:RegisterProvider("MythicPlus",{block="mythicPlus",capability="character.scan.mythicplus",addonId="mythicPlus",order=20,request=function(sync,reason)if reason=="INITIAL_MISSING_BLOCK"then Module:RequestData(false)elseif reason=="CAPABILITY"then Module:RequestData(true)end;local shortDelay=reason=="CHALLENGE_MODE_COMPLETED"or reason=="CHALLENGE_MODE_MAPS_UPDATE";local _,workflowId=Module:Queue(sync,shortDelay and.5 or 1.5);return workflowId end})
  HolyStorm:RegisterCapability("MythicPlus","character.scan.mythicplus",function(_,sync,reason)return HolyStorm.CharacterScans:Request("mythicPlus",reason or"CAPABILITY",sync,{order=20})end)
 end
 function Module:OnEnable()if not C_MythicPlus or not C_ChallengeMode then self:Disable();return end;self.initialDataRequested=false;for _,ev in ipairs({"CHALLENGE_MODE_COMPLETED","CHALLENGE_MODE_MAPS_UPDATE","MYTHIC_PLUS_CURRENT_AFFIX_UPDATE","MYTHIC_PLUS_NEW_WEEKLY_RECORD"})do local event=ev;HolyStorm.Events:Register(event,"mythicplus",function()HolyStorm.CharacterScans:Request("mythicPlus",event,true,{order=20})end)end;local context=self.loadContext;if context and context.reason=="event"then HolyStorm.CharacterScans:Request("mythicPlus",context.trigger,true,{order=20})end end
 function Module:OnDisable()self.initialDataRequested=false;HolyStorm.Events:UnregisterOwner("mythicplus");HolyStorm.Snapshots:Cancel("mythicplus")end
end)
