local addonVersion="1.0.0"
local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm")
local L=LibStub("AceLocale-3.0"):GetLocale("Holy_Storm")
local TwinkCore={version=addonVersion,visibility={ALL="all",GUILD_ONLY="guild-only"},sources={OWNER="owner-confirmed",ADMIN="administrative"},guildMainCache={}}
local function copy(v)return HolyStorm.Utils.DeepCopy(v)end
local function now()return HolyStorm.Utils.Now()end
local function validId(v)return type(v)=="string"and#v>0 and#v<=128 end
local function log(level,message,context)HolyStorm.Logger:Write(level,"TwinkCore","identity",message,context)end
local function syncObjectId(accountUUID,characterUUID)return accountUUID.."\031"..characterUUID end
local function splitObjectId(value)if type(value)~="string"then return nil end;return value:match("^(.-)\031([^\031]+)$")end

function TwinkCore:CreateAccountUUID()
 local value=string.format("account-%08x-%08x-%08x",now()%0xFFFFFFFF,math.random(0,0x7FFFFFFF),math.random(0,0x7FFFFFFF));log("INFO","Account UUID generated",{accountUUID=value});return value
end
function TwinkCore:GetLocalAccountUUID()return self.localAccountUUID end
function TwinkCore:_GetAccount(accountUUID)return validId(accountUUID)and self.accounts and self.accounts[accountUUID]or nil end
function TwinkCore:GetAccount(accountUUID)local account=self:_GetAccount(accountUUID);return account and copy(account)end
function TwinkCore:GetAccountUUIDForCharacter(characterUUID)return validId(characterUUID)and self.relationships and self.relationships[characterUUID]or nil end
function TwinkCore:GetCharactersForAccount(accountUUID)local account=self:_GetAccount(accountUUID);return account and copy(account.characters)or{}end
function TwinkCore:GetRelationshipSource(characterUUID)local account=self:_GetAccount(self:GetAccountUUIDForCharacter(characterUUID));local entry=account and account.characters[characterUUID];return entry and entry.relationship and entry.relationship.source or nil end
function TwinkCore:IsOwnerConfirmed(characterUUID)return self:GetRelationshipSource(characterUUID)==self.sources.OWNER end
function TwinkCore:NormalizeCharacterName(name,realm)
 if type(name)~="string"or name==""then return nil end;local base,embedded=name:match("^([^%-]+)%-(.+)$");base=base or name;realm=embedded or realm;local full=realm and realm~=""and(base.."-"..realm)or base;return{ name=base,realm=realm,fullName=full,normalizedFullName=string.lower(full:gsub("%s+","")) }
end
function TwinkCore:CompactIdentity(characterUUID,source,guildContext)
 local character=HolyStorm.Data.CharacterStore:Get(characterUUID)or{};local normalized=self:NormalizeCharacterName(character.name or character.fullName,character.realm)or{}
 local guild=guildContext or HolyStorm.Data.GuildStore:GetCurrentRosterSummary();local member=guild and guild.roster and guild.roster[characterUUID]
 return{characterUUID=characterUUID,name=normalized.name or character.name,realm=normalized.realm or character.realm,fullName=normalized.fullName or character.name,normalizedFullName=normalized.normalizedFullName,classFile=character.classFile or(member and member.classFile),level=character.level or(member and member.level),guildId=member and guild.id or character.guild,guildRankIndex=member and member.rankIndex or character.guildRankIndex,relationship={source=source,confirmedAt=source==self.sources.OWNER and now()or nil}}
end
function TwinkCore:EnsureAccount(accountUUID)
 if not validId(accountUUID)then return nil end;local account=self.accounts[accountUUID];if not account then account={accountUUID=accountUUID,characters={},visibility=self.visibility.ALL,ownerVersion=0,version=0,updatedAt=0};self.accounts[accountUUID]=account end
 account.accountUUID=accountUUID;account.characters=type(account.characters)=="table"and account.characters or{};account.visibility=account.visibility==self.visibility.GUILD_ONLY and self.visibility.GUILD_ONLY or self.visibility.ALL;account.ownerVersion=tonumber(account.ownerVersion or account.version)or 0;account.version=account.ownerVersion;return account
end
function TwinkCore:TouchOwner(account,reason)
 if not account or account.accountUUID~=self.localAccountUUID then return false,"NOT_LOCAL_ACCOUNT"end;account.ownerVersion=(account.ownerVersion or 0)+1;account.version=account.ownerVersion;account.updatedAt=now();account.issuedBy=UnitGUID("player");account.relayable=true
 HolyStorm.Events:Emit("HS_ACCOUNT_UPDATED",account.accountUUID,reason);HolyStorm.Events:Emit("HS_TWINKS_UPDATED",account.accountUUID);if HolyStorm.Sync:GetDomain("twinks")then HolyStorm.Sync:Publish("twinks",account.accountUUID,reason or"ACCOUNT_UPDATED")end;return true
end
local identityKeys={"name","realm","fullName","normalizedFullName","classFile","level","guildId","guildRankIndex"}
local function identityChanged(left,right)for _,key in ipairs(identityKeys)do if left[key]~=right[key]then return true end end;return false end
function TwinkCore:ConfirmLocalCharacter(characterUUID)
 if not validId(characterUUID)or characterUUID~=UnitGUID("player")then return false,"NOT_CURRENT_CHARACTER"end;local account=self:EnsureAccount(self.localAccountUUID);local fresh=self:CompactIdentity(characterUUID,self.sources.OWNER);local oldAccountUUID=self.relationships[characterUUID];local oldAccount=oldAccountUUID and self.accounts[oldAccountUUID];local old=account.characters[characterUUID];local changed=not old or old.relationship.source~=self.sources.OWNER or identityChanged(old,fresh)
 if oldAccount and oldAccount~=account then local previous=oldAccount.characters[characterUUID];if previous then oldAccount.characters[characterUUID]=nil;oldAccount.relayable=false;log("INFO","Character relationship conflict resolved by owner proof",{characterUUID=characterUUID,fromAccount=oldAccountUUID,toAccount=account.accountUUID,previousSource=previous.relationship and previous.relationship.source})end end
 fresh.relationship.confirmedAt=now();account.characters[characterUUID]=fresh;self.relationships[characterUUID]=account.accountUUID;HolyStorm.PlayerData:GetOwners()[characterUUID]=account.accountUUID;HolyStorm.PlayerData:GetOrCreateCharacter(characterUUID).playerId=account.accountUUID
 if changed then self:TouchOwner(account,old and"OWNER_RELATIONSHIP_CONFIRMED"or"CHARACTER_DISCOVERED");HolyStorm.Events:Emit("HS_CHARACTER_RELATIONSHIP_UPDATED",characterUUID,account.accountUUID,self.sources.OWNER);log("INFO",old and"Owner-confirmed relationship received"or"Character discovered for account",{accountUUID=account.accountUUID,characterUUID=characterUUID})else log("DEBUG","Character already known for account",{accountUUID=account.accountUUID,characterUUID=characterUUID})end;return true,changed
end
local function candidateSort(left,right)
 local lr,rr=tonumber(left.rankIndex)or math.huge,tonumber(right.rankIndex)or math.huge;if lr~=rr then return lr<rr end;local ln,rn=left.normalizedFullName or"",right.normalizedFullName or"";if ln~=rn then return ln<rn end;return left.characterUUID<right.characterUUID
end
function TwinkCore:BuildCandidates(account,guild,onlyGuild)
 local out={};for guid,entry in pairs(account and account.characters or{})do local member=guild and guild.roster and guild.roster[guid];if not onlyGuild or member then out[#out+1]={characterUUID=guid,rankIndex=member and member.rankIndex or nil,normalizedFullName=entry.normalizedFullName or string.lower(entry.fullName or guid),entry=entry,member=member}end end;table.sort(out,candidateSort);return out
end
function TwinkCore:GetAccountMain(accountUUID,guildContext,candidates)
 local account=self:_GetAccount(accountUUID);if not account then return nil end;if account.mainIsManual and account.mainCharacterUUID and account.characters[account.mainCharacterUUID]then return account.mainCharacterUUID,"manual"end;if not candidates then candidates=self:BuildCandidates(account,guildContext or HolyStorm.Data.GuildStore:GetCurrentRosterSummary(),false)end;return candidates[1]and candidates[1].characterUUID or nil,"fallback"
end
function TwinkCore:SetAccountMain(characterUUID)
 local account=self:_GetAccount(self.localAccountUUID);local entry=account and account.characters[characterUUID];if not entry or entry.relationship.source~=self.sources.OWNER then return false,"CHARACTER_NOT_OWNER_CONFIRMED",L["TWINK_ERROR_NOT_OWNER_CONFIRMED"]end;if account.mainIsManual and account.mainCharacterUUID==characterUUID then return false,"UNCHANGED"end;account.mainCharacterUUID=characterUUID;account.mainIsManual=true;self:TouchOwner(account,"ACCOUNT_MAIN_CHANGED");HolyStorm.Events:Emit("HS_ACCOUNT_MAIN_CHANGED",account.accountUUID,characterUUID);self:QueueGuildMainRecalculation("ACCOUNT_MAIN_CHANGED");log("INFO","Account main changed",{accountUUID=account.accountUUID,characterUUID=characterUUID});return true
end
function TwinkCore:CalculateGuildMain(accountUUID,guildContext)
 local account=self:_GetAccount(accountUUID);local guild=guildContext or HolyStorm.Data.GuildStore:GetCurrentRosterSummary();if not account or not guild or type(guild.roster)~="table"then return nil,false end;local candidates=self:BuildCandidates(account,guild,false);local accountMain=self:GetAccountMain(accountUUID,guild,candidates);if accountMain and guild.roster[accountMain]then return accountMain,false end;for _,candidate in ipairs(candidates)do if candidate.member then return candidate.characterUUID,true end end;return nil,true
end
function TwinkCore:GetGuildMain(accountUUID,guildContext)local guid,shadow=self:CalculateGuildMain(accountUUID,guildContext);return guid,shadow end
function TwinkCore:GetGuildCharacters(accountUUID,guildContext)
 local account=self:_GetAccount(accountUUID);local guild=guildContext or HolyStorm.Data.GuildStore:GetCurrentRosterSummary();local candidates=self:BuildCandidates(account,guild,true);local main=self:GetGuildMain(accountUUID,guild);table.sort(candidates,function(a,b)if a.characterUUID==main then return true elseif b.characterUUID==main then return false end;return candidateSort(a,b)end);local out={};for _,candidate in ipairs(candidates)do out[#out+1]=candidate.characterUUID end;return out
end
function TwinkCore:GetRosterIdentity(characterUUID,guildContext)
 local accountUUID=self:GetAccountUUIDForCharacter(characterUUID);if not accountUUID then return nil end;local accountMain,mainSource=self:GetAccountMain(accountUUID,guildContext);local guildMain,shadow=self:GetGuildMain(accountUUID,guildContext);return{accountUUID=accountUUID,accountMain=accountMain,guildMain=guildMain,isAccountMain=characterUUID==accountMain,isGuildMain=characterUUID==guildMain,isShadowMain=shadow and characterUUID==guildMain,mainSource=mainSource,relationshipSource=self:GetRelationshipSource(characterUUID)}
end
function TwinkCore:RecalculateGuildMains()
 local guild=HolyStorm.Data.GuildStore:GetCurrentRosterSummary();for accountUUID in pairs(self.accounts)do local main,shadow=self:CalculateGuildMain(accountUUID,guild);local old=self.guildMainCache[accountUUID];local token=tostring(main)..":"..tostring(shadow);if old~=token then self.guildMainCache[accountUUID]=token;HolyStorm.Events:Emit("HS_GUILD_MAIN_CHANGED",accountUUID,main,shadow);log("DEBUG",shadow and"Shadow main determined"or"Guild main recalculated",{accountUUID=accountUUID,characterUUID=main,shadow=shadow})end end;return true
end
function TwinkCore:QueueGuildMainRecalculation(reason)return HolyStorm.Tasks:Queue("TwinkCore.RecalculateGuildMains",{debounce=.2,priority=30,triggerSource=reason or"ACCOUNT_UPDATED"})end
function TwinkCore:GetVisibility(accountUUID)local account=self:_GetAccount(accountUUID);return account and account.visibility or self.visibility.ALL end
function TwinkCore:SetVisibility(value)
 if value~=self.visibility.ALL and value~=self.visibility.GUILD_ONLY then return false,"INVALID_VISIBILITY",L["TWINK_ERROR_INVALID_VISIBILITY"]end;local account=self:_GetAccount(self.localAccountUUID);if account.visibility==value then return false,"UNCHANGED"end;account.visibility=value;self:TouchOwner(account,"TWINK_VISIBILITY_CHANGED");HolyStorm.Events:Emit("HS_TWINK_VISIBILITY_CHANGED",account.accountUUID,value);log("INFO","Twink visibility changed",{accountUUID=account.accountUUID,visibility=value});return true
end
function TwinkCore:SetAccountMetadata(metadata)
 local account=self:_GetAccount(self.localAccountUUID);if not account or type(metadata)~="table"then return false,"INVALID_METADATA"end;if HolyStorm.Serializer:Serialize(account.metadata or{})==HolyStorm.Serializer:Serialize(metadata)then return false,"UNCHANGED"end;account.metadata=copy(metadata);self:TouchOwner(account,"ACCOUNT_METADATA_CHANGED");return true
end
function TwinkCore:GetVisibleCharactersForViewer(accountUUID,guildContext)
 local account=self:_GetAccount(accountUUID);if not account then return{}end;local guild=guildContext or HolyStorm.Data.GuildStore:GetCurrentRosterSummary();local accountMain=self:GetAccountMain(accountUUID,guild);local out={};for guid,entry in pairs(account.characters)do if account.visibility==self.visibility.ALL or guid==accountMain or(guild and guild.roster and guild.roster[guid])then out[#out+1]=copy(entry)end end;table.sort(out,function(a,b)if a.characterUUID==accountMain then return true elseif b.characterUUID==accountMain then return false end;return candidateSort({characterUUID=a.characterUUID,rankIndex=a.guildRankIndex,normalizedFullName=a.normalizedFullName},{characterUUID=b.characterUUID,rankIndex=b.guildRankIndex,normalizedFullName=b.normalizedFullName})end);return out
end
function TwinkCore:CanAdmin(permission,actorGuid)local playerId=actorGuid and(HolyStorm.Data.PlayerStore:GetCharacterOwner(actorGuid)or actorGuid);local engine=HolyStorm.PermissionEngine or HolyStorm.Policy;return engine:Can(permission,playerId,actorGuid)end
function TwinkCore:AssignCharacterAdministrative(accountUUID,characterUUID,identity,note)
 if not self:CanAdmin("twinks-assign")then return false,"PERMISSION_DENIED",L["TWINK_ERROR_PERMISSION"]end;if not validId(accountUUID)or not validId(characterUUID)then return false,"INVALID_IDENTITY",L["TWINK_ERROR_INVALID_IDENTITY"]end;local existingAccountUUID=self.relationships[characterUUID];local existingAccount=existingAccountUUID and self.accounts[existingAccountUUID];local existing=existingAccount and existingAccount.characters[characterUUID];if existing and existing.relationship.source==self.sources.OWNER then log("WARN","Administrative assignment rejected for owner-confirmed character",{characterUUID=characterUUID,accountUUID=existingAccountUUID});return false,"OWNER_CONFIRMED",L["TWINK_ERROR_OWNER_CONFIRMED"]end
 if existingAccount and existingAccountUUID~=accountUUID then existingAccount.characters[characterUUID]=nil end;local account=self:EnsureAccount(accountUUID);local actor=UnitGUID("player");local previous=account.characters[characterUUID];local version=math.max(tonumber(previous and previous.relationship and previous.relationship.adminVersion)or 0,self:GetAdministrativeVersion(accountUUID,characterUUID))+1;local entry=self:CompactIdentity(characterUUID,self.sources.ADMIN);for key,value in pairs(type(identity)=="table"and identity or{})do if(key=="name"or key=="realm"or key=="fullName"or key=="classFile"or key=="level"or key=="guildId")and(type(value)=="string"or type(value)=="number")then entry[key]=value end end;entry.relationship={source=self.sources.ADMIN,assignedBy=actor,assignedAt=now(),adminVersion=version,note=type(note)=="string"and note or nil};account.characters[characterUUID]=entry;self.relationships[characterUUID]=accountUUID;HolyStorm.PlayerData:GetOwners()[characterUUID]=accountUUID;HolyStorm.PlayerData:GetOrCreateCharacter(characterUUID).playerId=accountUUID;self.adminTombstones[syncObjectId(accountUUID,characterUUID)]=nil;HolyStorm.Sync:Publish("twinkAdmin",syncObjectId(accountUUID,characterUUID),"ADMINISTRATIVE_ASSIGNMENT");HolyStorm.Events:Emit("HS_CHARACTER_RELATIONSHIP_UPDATED",characterUUID,accountUUID,self.sources.ADMIN);HolyStorm.Events:Emit("HS_TWINKS_UPDATED",accountUUID);self:QueueGuildMainRecalculation("ADMINISTRATIVE_ASSIGNMENT");log("INFO","Administrative relationship created",{accountUUID=accountUUID,characterUUID=characterUUID,assignedBy=actor,version=version});return true
end
function TwinkCore:GetAdministrativeVersion(accountUUID,characterUUID)local account=self:_GetAccount(accountUUID);local entry=account and account.characters[characterUUID];local relation=entry and entry.relationship;local tombstone=self.adminTombstones[syncObjectId(accountUUID,characterUUID)];return math.max(tonumber(relation and relation.adminVersion)or 0,tonumber(tombstone and tombstone.version)or 0)end
function TwinkCore:RemoveAdministrativeAssignment(accountUUID,characterUUID)
 if not self:CanAdmin("twinks-remove")then return false,"PERMISSION_DENIED",L["TWINK_ERROR_PERMISSION"]end;local account=self:_GetAccount(accountUUID);local entry=account and account.characters[characterUUID];if not entry then return false,"NOT_FOUND",L["TWINK_ERROR_NOT_FOUND"]end;if entry.relationship.source==self.sources.OWNER then log("WARN","Owner-confirmed relationship removal rejected",{accountUUID=accountUUID,characterUUID=characterUUID});return false,"OWNER_CONFIRMED",L["TWINK_ERROR_OWNER_CONFIRMED"]end;local actor=UnitGUID("player");local version=self:GetAdministrativeVersion(accountUUID,characterUUID)+1;account.characters[characterUUID]=nil;if self.relationships[characterUUID]==accountUUID then self.relationships[characterUUID]=nil;HolyStorm.PlayerData:GetOwners()[characterUUID]=nil end;self.adminTombstones[syncObjectId(accountUUID,characterUUID)]={accountUUID=accountUUID,characterUUID=characterUUID,operation="REMOVE",source=self.sources.ADMIN,assignedBy=actor,assignedAt=now(),version=version};HolyStorm.Sync:Publish("twinkAdmin",syncObjectId(accountUUID,characterUUID),"ADMINISTRATIVE_REMOVAL");HolyStorm.Events:Emit("HS_CHARACTER_RELATIONSHIP_UPDATED",characterUUID,nil,self.sources.ADMIN);HolyStorm.Events:Emit("HS_TWINKS_UPDATED",accountUUID);self:QueueGuildMainRecalculation("ADMINISTRATIVE_REMOVAL");log("INFO","Administrative relationship removed",{accountUUID=accountUUID,characterUUID=characterUUID,assignedBy=actor,version=version});return true
end
function TwinkCore:ValidateOwnerSnapshot(payload)
 if type(payload)~="table"or not validId(payload.accountUUID)or type(payload.characters)~="table"or(payload.visibility~=self.visibility.ALL and payload.visibility~=self.visibility.GUILD_ONLY)then return false end;if payload.mainCharacterUUID and(not validId(payload.mainCharacterUUID)or not payload.characters[payload.mainCharacterUUID])then return false end;local count=0;for guid,entry in pairs(payload.characters)do count=count+1;if count>200 or not validId(guid)or type(entry)~="table"or entry.characterUUID~=guid or type(entry.relationship)~="table"or(entry.relationship.source~=self.sources.OWNER and entry.relationship.source~=self.sources.ADMIN)then return false end;if entry.relationship.source==self.sources.ADMIN and(not validId(entry.relationship.assignedBy)or not tonumber(entry.relationship.assignedAt))then return false end end;return true
end
function TwinkCore:ExportOwnerSnapshot(accountUUID)local account=self:_GetAccount(accountUUID);if not account or account.relayable==false then return nil end;return{accountUUID=account.accountUUID,characters=copy(account.characters),mainCharacterUUID=account.mainCharacterUUID,mainIsManual=account.mainIsManual==true,visibility=account.visibility,metadata=copy(account.metadata or{}),ownerVersion=account.ownerVersion,updatedAt=account.updatedAt,issuedBy=account.issuedBy}end
function TwinkCore:GetOwnerMetadata(accountUUID)local account=self:_GetAccount(accountUUID);if not account or account.relayable==false or not validId(account.issuedBy)then return nil end;return{objectId=accountUUID,owner=account.issuedBy,version=tonumber(account.ownerVersion)or 0,updatedAt=tonumber(account.updatedAt)or 0,source="twinks-owner"}end
function TwinkCore:MergeOwnerSnapshot(accountUUID,payload,meta)
 if accountUUID==self.localAccountUUID then return false,"LOCAL_OWNER_PROTECTED"end;local account=self:EnsureAccount(accountUUID);for guid,incoming in pairs(payload.characters)do local oldAccountUUID=self.relationships[guid];local oldAccount=oldAccountUUID and self.accounts[oldAccountUUID];local old=oldAccount and oldAccount.characters[guid]
    if incoming.relationship.source==self.sources.OWNER then if oldAccountUUID~=self.localAccountUUID or oldAccountUUID==accountUUID then if oldAccount and oldAccount~=account then oldAccount.characters[guid]=nil;oldAccount.relayable=false;log("INFO","Character conflict resolved by synchronized owner proof",{characterUUID=guid,fromAccount=oldAccountUUID,toAccount=accountUUID,previousSource=old and old.relationship and old.relationship.source})end;account.characters[guid]=copy(incoming);self.relationships[guid]=accountUUID;HolyStorm.PlayerData:GetOwners()[guid]=accountUUID;local identity=HolyStorm.PlayerData:GetOrCreateCharacter(guid);identity.playerId=accountUUID end
  elseif not old or old.relationship.source~=self.sources.OWNER then account.characters[guid]=copy(incoming);self.relationships[guid]=accountUUID;HolyStorm.PlayerData:GetOwners()[guid]=accountUUID end
 end
 account.mainCharacterUUID=payload.mainCharacterUUID;account.mainIsManual=payload.mainIsManual==true;account.visibility=payload.visibility;account.metadata=type(payload.metadata)=="table"and copy(payload.metadata)or{};account.ownerVersion=meta.version;account.version=meta.version;account.updatedAt=meta.updatedAt;account.issuedBy=meta.owner;account.relayable=true;HolyStorm.Events:Emit("HS_ACCOUNT_UPDATED",accountUUID,"SYNC");HolyStorm.Events:Emit("HS_TWINKS_UPDATED",accountUUID);HolyStorm.Events:Emit("HS_ACCOUNT_MAIN_CHANGED",accountUUID,self:GetAccountMain(accountUUID));HolyStorm.Events:Emit("HS_TWINK_VISIBILITY_CHANGED",accountUUID,account.visibility);self:QueueGuildMainRecalculation("TWINK_SYNC");log("INFO","Twink account synchronized",{accountUUID=accountUUID,version=meta.version,receivedFrom=meta.receivedFrom});return true
end
function TwinkCore:GetAdminPayload(objectId)local accountUUID,guid=splitObjectId(objectId);local tombstone=self.adminTombstones[objectId];if tombstone then return copy(tombstone)end;local account=self:_GetAccount(accountUUID);local entry=account and account.characters[guid];if entry and entry.relationship.source==self.sources.ADMIN then return{accountUUID=accountUUID,characterUUID=guid,operation="ASSIGN",entry=copy(entry),source=self.sources.ADMIN,assignedBy=entry.relationship.assignedBy,assignedAt=entry.relationship.assignedAt,version=entry.relationship.adminVersion}end end
function TwinkCore:GetAdminMetadata(objectId)local payload=self:GetAdminPayload(objectId);return payload and{objectId=objectId,owner=payload.assignedBy,version=tonumber(payload.version)or 0,updatedAt=tonumber(payload.assignedAt)or 0,source="twinks-administrative"}end
function TwinkCore:ValidateAdminPayload(payload,meta,objectId)local accountUUID,guid=splitObjectId(objectId);if type(payload)~="table"or not validId(accountUUID)or not validId(guid)or not validId(payload.assignedBy)or payload.accountUUID~=accountUUID or payload.characterUUID~=guid or payload.source~=self.sources.ADMIN or(payload.operation~="ASSIGN"and payload.operation~="REMOVE")or payload.assignedBy~=meta.owner or not tonumber(payload.assignedAt)or tonumber(payload.version)~=tonumber(meta.version)then return false end;if payload.operation=="ASSIGN"then return type(payload.entry)=="table"and payload.entry.characterUUID==guid and payload.entry.relationship and payload.entry.relationship.source==self.sources.ADMIN end;return true end
function TwinkCore:ApplyAdministrativePayload(objectId,payload)
 local account=self:EnsureAccount(payload.accountUUID);local existingAccountUUID=self.relationships[payload.characterUUID];local existingAccount=existingAccountUUID and self.accounts[existingAccountUUID];local existing=existingAccount and existingAccount.characters[payload.characterUUID];if existing and existing.relationship.source==self.sources.OWNER then return false end
 if payload.operation=="REMOVE"then if existingAccountUUID==payload.accountUUID and existing then account.characters[payload.characterUUID]=nil;self.relationships[payload.characterUUID]=nil;HolyStorm.PlayerData:GetOwners()[payload.characterUUID]=nil end;self.adminTombstones[objectId]=copy(payload)else if existingAccount and existingAccount~=account then existingAccount.characters[payload.characterUUID]=nil end;account.characters[payload.characterUUID]=copy(payload.entry);self.relationships[payload.characterUUID]=payload.accountUUID;HolyStorm.PlayerData:GetOwners()[payload.characterUUID]=payload.accountUUID;HolyStorm.PlayerData:GetOrCreateCharacter(payload.characterUUID).playerId=payload.accountUUID;self.adminTombstones[objectId]=nil end
 HolyStorm.Events:Emit("HS_CHARACTER_RELATIONSHIP_UPDATED",payload.characterUUID,payload.operation=="ASSIGN"and payload.accountUUID or nil,self.sources.ADMIN);HolyStorm.Events:Emit("HS_TWINKS_UPDATED",payload.accountUUID);self:QueueGuildMainRecalculation("ADMINISTRATIVE_SYNC");return true
end
function TwinkCore:RegisterSyncDomains()
 HolyStorm.Sync:RegisterDomain("twinks",{
  getMetadata=function(id)return TwinkCore:GetOwnerMetadata(id)end,
  listMetadata=function(since)local out={};for id in pairs(TwinkCore.accounts)do local meta=TwinkCore:GetOwnerMetadata(id);if meta and(meta.updatedAt or 0)>since then out[#out+1]=meta end end;return out end,
  export=function(id)return TwinkCore:ExportOwnerSnapshot(id)end,
  validate=function(payload,meta,id)return payload.accountUUID==id and tonumber(payload.ownerVersion)==tonumber(meta.version)and payload.issuedBy==meta.owner and TwinkCore:ValidateOwnerSnapshot(payload)end,
  authorize=function(payload,meta)local issuer=payload.characters[meta.owner];return issuer~=nil and issuer.relationship.source==TwinkCore.sources.OWNER end,
  import=function(id,payload,meta)return TwinkCore:MergeOwnerSnapshot(id,payload,meta)end,
  updateEvent="HS_TWINK_SYNC_UPDATED",
 })
 HolyStorm.Sync:RegisterDomain("twinkAdmin",{
  getMetadata=function(id)return TwinkCore:GetAdminMetadata(id)end,
  listMetadata=function(since)
   local out,seen={},{}
   for accountUUID,account in pairs(TwinkCore.accounts)do for guid,entry in pairs(account.characters)do if entry.relationship and entry.relationship.source==TwinkCore.sources.ADMIN then local id=syncObjectId(accountUUID,guid);local meta=TwinkCore:GetAdminMetadata(id);if meta and(meta.updatedAt or 0)>since then out[#out+1]=meta;seen[id]=true end end end end
   for id in pairs(TwinkCore.adminTombstones)do if not seen[id]then local meta=TwinkCore:GetAdminMetadata(id);if meta and(meta.updatedAt or 0)>since then out[#out+1]=meta end end end
   return out
  end,
  export=function(id)return TwinkCore:GetAdminPayload(id)end,
  validate=function(payload,meta,id)return TwinkCore:ValidateAdminPayload(payload,meta,id)end,
  authorize=function(payload,meta)local permission=payload.operation=="REMOVE"and"twinks-remove"or"twinks-assign";return TwinkCore:CanAdmin(permission,meta.owner)end,
  import=function(id,payload)return TwinkCore:ApplyAdministrativePayload(id,payload)end,
  updateEvent="HS_TWINK_ADMIN_SYNC_UPDATED",
 })
end
function TwinkCore:MigrateAccounts()
 for accountUUID,account in pairs(self.accounts)do if type(accountUUID)~="string"or type(account)~="table"then self.accounts[accountUUID]=nil else account=self:EnsureAccount(accountUUID);local migrated={};for guid,value in pairs(account.characters)do if validId(guid)then if type(value)=="table"and value.characterUUID==guid and value.relationship then migrated[guid]=value else local source=accountUUID==self.localAccountUUID and self.sources.OWNER or account.ownerGuid and self.sources.OWNER or self.sources.ADMIN;local entry=self:CompactIdentity(guid,source);if source==self.sources.ADMIN then entry.relationship={source=source,assignedBy="legacy-migration",assignedAt=tonumber(account.updatedAt)or now(),adminVersion=1}end;migrated[guid]=entry end;self.relationships[guid]=accountUUID;HolyStorm.PlayerData:GetOwners()[guid]=accountUUID end end;account.characters=migrated;account.mainCharacterUUID=account.mainCharacterUUID or account.mainCharacter;account.mainCharacter=nil;account.mainIsManual=account.mainIsManual==true or account.mainCharacterUUID~=nil;account.visibility=account.visibility==self.visibility.GUILD_ONLY and self.visibility.GUILD_ONLY or self.visibility.ALL;account.ownerVersion=tonumber(account.ownerVersion or account.version)or 0;account.version=account.ownerVersion;account.issuedBy=account.issuedBy or account.ownerGuid or account.mainCharacterUUID or next(account.characters);account.relayable=account.relayable~=false end end
end
function TwinkCore:Initialize()
 local root=HolyStorm.PlayerData:GetRoot();root.accounts=type(root.accounts)=="table"and root.accounts or root.players or{};root.players=root.accounts;root.characterAccounts=type(root.characterAccounts)=="table"and root.characterAccounts or root.characterOwners or{};root.characterOwners=root.characterAccounts;root.adminTwinkTombstones=type(root.adminTwinkTombstones)=="table"and root.adminTwinkTombstones or{};self.accounts,self.relationships,self.adminTombstones=root.accounts,root.characterAccounts,root.adminTwinkTombstones
 local accountUUID=root.localAccountUUID or HolyStorm.db.global.localAccountUUID or HolyStorm.db.global.localPlayerId;if not validId(accountUUID)then accountUUID=self:CreateAccountUUID()end;root.localAccountUUID=accountUUID;HolyStorm.db.global.localAccountUUID=accountUUID;HolyStorm.db.global.localPlayerId=accountUUID;self.localAccountUUID=accountUUID;self:EnsureAccount(accountUUID);self:MigrateAccounts()
 if HolyStorm.Rules then
  HolyStorm.Rules:RegisterField("twink-core","account.uuid",{type="string",name=L["RULE_FIELD_ACCOUNT_UUID"],nameKey="RULE_FIELD_ACCOUNT_UUID",description=L["RULE_FIELD_ACCOUNT_UUID_DESC"],descriptionKey="RULE_FIELD_ACCOUNT_UUID_DESC",category=L["ACCOUNT_MAIN"],dependencies={"twinks"},resolver=function(context)return context.accountUUID end})
  HolyStorm.Rules:RegisterField("twink-core","account.isMain",{type="boolean",name=L["RULE_FIELD_ACCOUNT_MAIN"],nameKey="RULE_FIELD_ACCOUNT_MAIN",description=L["RULE_FIELD_ACCOUNT_MAIN_DESC"],descriptionKey="RULE_FIELD_ACCOUNT_MAIN_DESC",category=L["ACCOUNT_MAIN"],dependencies={"twinks"},resolver=function(context)local account=context.accountUUID;if not account or not context.characterUUID then return nil,"MISSING_IDENTITY"end;return context.characterUUID==TwinkCore:GetAccountMain(account)end})
  HolyStorm.Rules:RegisterField("twink-core","character.mainTwinkStatus",{type="enum",name=L["RULE_FIELD_MAIN_STATUS"],nameKey="RULE_FIELD_MAIN_STATUS",description=L["RULE_FIELD_MAIN_STATUS_DESC"],descriptionKey="RULE_FIELD_MAIN_STATUS_DESC",category=L["ACCOUNT_MAIN"],dependencies={"twinks"},values={"MAIN","TWINK"},resolver=function(context)local guid=context.characterUUID or context.character and context.character.guid;local account=guid and TwinkCore:GetAccountUUIDForCharacter(guid);local main=account and TwinkCore:GetAccountMain(account);return guid and main and(main==guid and"MAIN"or"TWINK")or nil end})
  HolyStorm.Rules:RegisterAlias("twink-core","mainTwinkStatus","character.mainTwinkStatus")
 end
 HolyStorm.Tasks:RegisterTaskType("TwinkCore.RecalculateGuildMains",{name=L["TASK_TWINK_RECALCULATE_GUILD_MAINS"],localizedNameKey="TASK_TWINK_RECALCULATE_GUILD_MAINS",module="TwinkCore",priority=30,executionMode="UNIQUE",execute=function()return TwinkCore:RecalculateGuildMains()end})
 HolyStorm.Events:Register("HS_ROSTER_UPDATED","twink-core",function()TwinkCore:QueueGuildMainRecalculation("HS_ROSTER_UPDATED")end);HolyStorm.Events:Register("HS_CHARACTER_UPDATED","twink-core-identity",function(_,guid)if guid==UnitGUID("player")then TwinkCore:ConfirmLocalCharacter(guid)end end)
 self:RegisterSyncDomains();local guid=UnitGUID("player");if guid then self:ConfirmLocalCharacter(guid)end;return true
end
HolyStorm.TwinkCore=TwinkCore
