local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm")
local CharacterL=LibStub("AceLocale-3.0"):GetLocale("Holy_Storm_CharacterUI")
local function locale(prefix)return setmetatable({},{__index=function(_,key)return CharacterL[prefix..key]end})end

-- These adapters belong to the Character Storage consumer. The optional
-- feature addons only produce and update the snapshots consumed here.
do
 local L=locale("EQUIPMENT_")
 local slots={
  {INVSLOT_HEAD,"SLOT_HEAD","Interface\\PaperDoll\\UI-PaperDoll-Slot-Head"},{INVSLOT_NECK,"SLOT_NECK","Interface\\PaperDoll\\UI-PaperDoll-Slot-Neck"},{INVSLOT_SHOULDER,"SLOT_SHOULDER","Interface\\PaperDoll\\UI-PaperDoll-Slot-Shoulder"},{INVSLOT_BACK,"SLOT_BACK","Interface\\PaperDoll\\UI-PaperDoll-Slot-Chest"},
  {INVSLOT_CHEST,"SLOT_CHEST","Interface\\PaperDoll\\UI-PaperDoll-Slot-Chest"},{INVSLOT_WRIST,"SLOT_WRIST","Interface\\PaperDoll\\UI-PaperDoll-Slot-Wrists"},{INVSLOT_HAND,"SLOT_HANDS","Interface\\PaperDoll\\UI-PaperDoll-Slot-Hands"},{INVSLOT_WAIST,"SLOT_WAIST","Interface\\PaperDoll\\UI-PaperDoll-Slot-Waist"},
  {INVSLOT_LEGS,"SLOT_LEGS","Interface\\PaperDoll\\UI-PaperDoll-Slot-Legs"},{INVSLOT_FEET,"SLOT_FEET","Interface\\PaperDoll\\UI-PaperDoll-Slot-Feet"},{INVSLOT_FINGER1,"SLOT_FINGER1","Interface\\PaperDoll\\UI-PaperDoll-Slot-Finger"},{INVSLOT_FINGER2,"SLOT_FINGER2","Interface\\PaperDoll\\UI-PaperDoll-Slot-Finger"},
  {INVSLOT_TRINKET1,"SLOT_TRINKET1","Interface\\PaperDoll\\UI-PaperDoll-Slot-Trinket"},{INVSLOT_TRINKET2,"SLOT_TRINKET2","Interface\\PaperDoll\\UI-PaperDoll-Slot-Trinket"},{INVSLOT_MAINHAND,"SLOT_MAINHAND","Interface\\PaperDoll\\UI-PaperDoll-Slot-MainHand"},{INVSLOT_OFFHAND,"SLOT_OFFHAND","Interface\\PaperDoll\\UI-PaperDoll-Slot-SecondaryHand"},
 }
 local function itemName(item)if not item then return nil end;local label=type(item.link)=="string"and item.link:match("|h%[?(.-)%]?|h");return label or item.name or(item.itemId and tostring(item.itemId))end
 local function openItem(row)local link=row.item and row.item.link;if not link then return end;if HandleModifiedItemClick then HandleModifiedItemClick(link)elseif SetItemRef then local payload=link:match("|H([^|]+)|h");if payload then SetItemRef(payload,link,"LeftButton")end end end
 local function itemTooltip(row,_,_,tooltip)local link=row.item and row.item.link;if not link then return end;tooltip:SetHyperlink(link);return true end
 local function iconCell(cell,_,row)if not cell.icon then cell.icon=cell.frame:CreateTexture(nil,"ARTWORK");cell.icon:SetSize(20,20);cell.icon:SetPoint("LEFT",4,0);cell.text:ClearAllPoints();cell.text:SetPoint("LEFT",28,0);cell.text:SetPoint("RIGHT",-4,0)end;cell.icon:SetTexture(row.item and row.item.icon or row.state=="EMPTY"and row.emptyTexture or"Interface\\Icons\\INV_Misc_QuestionMark");cell.icon:Show();cell:SetDisplay(row.slotLabel)end
 local function itemCell(cell,_,row)if row.state=="UNKNOWN"then cell:SetDisplay(HolyStorm.CharacterUI:FormatState(nil));return end;if row.state=="EMPTY"then cell:SetDisplay(L["EMPTY_SLOT"]);return end;local name=itemName(row.item);local link=row.item.link;if link then cell:SetDisplay(link,name,function(short)return HolyStorm.UI.Components:ReplaceHyperlinkLabel(link,short)end)else cell:SetDisplay(name or HolyStorm.CharacterUI:FormatState(nil),name)end end
 local function statusCell(cell,_,row,column)if not cell.statusIcon then cell.statusIcon=cell.frame:CreateTexture(nil,"ARTWORK");cell.statusIcon:SetSize(18,18);cell.statusIcon:SetPoint("CENTER");cell.statusIcon:SetTexture("Interface\\Buttons\\UI-CheckBox-Check")end;local state=row[column.id.."State"];if state==true then cell.statusIcon:SetVertexColor(.2,1,.2,1);cell.statusIcon:Show();cell:SetDisplay("")else cell.statusIcon:Hide();cell:SetDisplay(state==nil and HolyStorm.CharacterUI:FormatState(nil)or"")end end
 local function formatItemLevel(value)local number=tonumber(value);return number and string.format("%.1f",number)or HolyStorm.CharacterUI:FormatState(nil)end
 local function itemLevelSummary(value)return"|cffffd100"..L["ITEM_LEVEL"]..":|r |cff80dfff"..formatItemLevel(value).."|r"end
 local function gemsFor(item)
  if not item then return nil,nil,nil end;local sockets=tonumber(item.sockets);local gems=type(item.gems)=="table"and item.gems or nil;if sockets==nil and gems then sockets=#gems end;if sockets==0 then return"",{},{}end;if sockets==nil then return nil,nil,nil end
  local labels,details,installed={},{},{};for index=1,sockets do local gem=gems and gems[index];if type(gem)=="table"and gem.empty then labels[#labels+1]=L["EMPTY_SOCKET"];details[#details+1]=gem.name or L["EMPTY_SOCKET"]elseif gem~=nil then local id=type(gem)=="table"and gem.itemId or gem;local name=type(gem)=="table"and gem.name or nil;local icon=type(gem)=="table"and gem.icon or nil;labels[#labels+1]=icon and("|T"..icon..":16:16|t")or tostring(id or index);details[#details+1]=name or string.format(L["GEM_ID"],tostring(id or index));installed[#installed+1]=gem else labels[#labels+1]=HolyStorm.CharacterUI:FormatState(nil);details[#details+1]=HolyStorm.CharacterUI:FormatState(nil)end end;return table.concat(labels," "),details,installed
 end
 local function refresh(view,context)
  local C=HolyStorm.CharacterUI;local snapshot=C:GetSnapshot(context.characterUUID,"equipment");if not snapshot then C:SetTableView(view,{}, {emptyText=L["NO_EQUIPMENT"]});return end
  local rows={};for _,slot in ipairs(slots)do local raw=snapshot.slots and snapshot.slots[slot[1]];local state=raw==nil and"UNKNOWN"or raw==false and"EMPTY"or"VALUE";local item=state=="VALUE"and raw or nil;local gems,gemDetails,installedGems=gemsFor(item);local tierState,enchantState;if item then tierState=item.isTier;local enchantId=tonumber(item.enchantId);if enchantId~=nil then enchantState=enchantId>0 end elseif state=="EMPTY"then tierState,enchantState=false,false end;rows[#rows+1]={slotId=slot[1],slotLabel=L[slot[2]],emptyTexture=slot[3],state=state,item=item,itemText=itemName(item),tier="",tierState=tierState,enchant="",enchantState=enchantState,gems=gems or(state=="UNKNOWN"and C:FormatState(nil)or""),gemDetails=gemDetails,installedGems=installedGems,itemLevel=item and C:FormatState(item.itemLevel)or(state=="UNKNOWN"and C:FormatState(nil)or"")}end
  C:SetTableView(view,rows,{summary=itemLevelSummary(snapshot.itemLevel),emptyText=L["NO_EQUIPMENT"]})
 end
 local function build(parent)return HolyStorm.CharacterUI:CreateTableView(parent,{columns={{id="slotLabel",title=L["COLUMN_SLOT"],width=150,renderCell=iconCell,onClick=openItem,tooltip=itemTooltip},{id="itemText",title=L["COLUMN_ITEM"],weight=1,minWidth=180,truncate=true,renderCell=itemCell,onClick=openItem,tooltip=itemTooltip},{id="tier",title=L["COLUMN_TIER"],width=55,align="CENTER",renderCell=statusCell,tooltip=function(row)return row.tierState==true and L["TIER_ITEM"]or nil end},{id="enchant",title=L["COLUMN_ENCHANT"],width=100,align="CENTER",renderCell=statusCell,tooltip=function(row)if row.enchantState==nil then return end;if row.enchantState==false then return L["NOT_ENCHANTED"]end;return row.item and(row.item.enchantName or L["ENCHANTED"])or L["ENCHANTED"]end},{id="gems",title=L["COLUMN_GEMS"],width=130,align="CENTER",tooltip=function(row,_,_,tooltip)if row.installedGems and#row.installedGems==1 and type(row.installedGems[1])=="table"and row.installedGems[1].link then tooltip:SetHyperlink(row.installedGems[1].link);return true end;if not row.gemDetails or#row.gemDetails==0 then return end;tooltip:SetText(L["COLUMN_GEMS"]);for _,line in ipairs(row.gemDetails)do tooltip:AddLine(line,1,1,1)end;return true end},{id="itemLevel",title=L["COLUMN_ILVL"],width=80,align="RIGHT"}},rowHeight=26,headerHeight=26,columnGap=1,emptyText=L["NO_EQUIPMENT"]})end
 HolyStorm:RegisterCharacterTab("characters",{id="equipment",order=20,label=L["DISPLAY_NAME"],labelKey="EQUIPMENT_DISPLAY_NAME",icon="Interface\\Icons\\INV_Helmet_08",blocks={"equipment"},events={"HS_EQUIPMENT_UPDATED"},build=build,refresh=refresh})
 HolyStorm:RegisterCharacterSummarySection("characters",{id="equipment",order=20,render=function(context)local C=HolyStorm.CharacterUI;local snapshot=C:GetSnapshot(context.characterUUID,"equipment");return{label=L["DISPLAY_NAME"],tabId="equipment",value=snapshot and itemLevelSummary(snapshot.itemLevel)or L["NO_EQUIPMENT"]}end})
end

do
 local L=locale("MYTHICPLUS_")
 local function affixEntry(dungeon,category)
  -- The current MythicPlusAffixScoreInfo structure contains a localized name,
  -- score, level, durationSec and overTime; it does not contain an affix ID.
  for _,entry in pairs(type(dungeon.affixScores)=="table"and dungeon.affixScores or{})do if type(entry)=="table"and entry.category==category then return entry end end
 end
 local function affixDataState(dungeon)local scores=dungeon.affixScores;if type(scores)~="table"then return false,false end;if next(scores)==nil then return true,false end;for _,entry in pairs(scores)do if type(entry)=="table"and(entry.category=="TYRANNICAL"or entry.category=="FORTIFIED")then return true,false end end;return false,true end
 local function durationText(value)local seconds=tonumber(value);if not seconds or seconds<0 then return HolyStorm.CharacterUI:FormatState(nil)end;seconds=math.floor(seconds+.5);local hours=math.floor(seconds/3600);local minutes=math.floor((seconds%3600)/60);local remainder=seconds%60;if hours>0 then return string.format("%d:%02d:%02d",hours,minutes,remainder)end;return string.format("%d:%02d",minutes,remainder)end
 local function keyResult(entry,ready,timeLimit)
  if type(entry)~="table"then return ready and""or HolyStorm.CharacterUI:FormatState(nil)end
  local level=tonumber(entry.level or entry.bestLevel);if not level or level<=0 then return ready and""or HolyStorm.CharacterUI:FormatState(nil)end
  local overTime=entry.overTime;if overTime==nil and tonumber(entry.durationSec)and tonumber(timeLimit)then overTime=tonumber(entry.durationSec)>tonumber(timeLimit)end
  local text="+"..level.."  "..durationText(entry.durationSec);if overTime==nil then return"|cff888888"..text:gsub("|c%x%x%x%x%x%x%x%x",""):gsub("|r","").."|r"end
  return overTime and("|cffff4040"..text.."|r")or("|cff20ff20"..text.."|r")
 end
 local function scoreText(value)local score=tonumber(value);if score==nil then return HolyStorm.CharacterUI:FormatState(nil)end;local text=score%1==0 and tostring(score)or string.format("%.1f",score);local color=C_ChallengeMode and C_ChallengeMode.GetDungeonScoreRarityColor and C_ChallengeMode.GetDungeonScoreRarityColor(score);if color then if color.WrapTextInColorCode then return color:WrapTextInColorCode(text)end;if color.r then return string.format("|cff%02x%02x%02x%s|r",math.floor(color.r*255+.5),math.floor(color.g*255+.5),math.floor(color.b*255+.5),text)end end;return text end
 local function teleportState(dungeon)local spellId=tonumber(dungeon.teleportSpellId or dungeon.teleportSpellID);if not spellId then return{state="UNAVAILABLE"}end;local known=(C_SpellBook and C_SpellBook.IsSpellKnown and C_SpellBook.IsSpellKnown(spellId))or(C_Spell and C_Spell.IsSpellKnown and C_Spell.IsSpellKnown(spellId))or(IsSpellKnownOrOverridesKnown and IsSpellKnownOrOverridesKnown(spellId))or(IsSpellKnown and IsSpellKnown(spellId));if not known then return{state="UNAVAILABLE",spellId=spellId}end;local hasCooldownAPI=C_Spell and C_Spell.GetSpellCooldown or GetSpellCooldown;if not hasCooldownAPI then return{state="UNAVAILABLE",spellId=spellId}end;local cooldown=C_Spell and C_Spell.GetSpellCooldown and C_Spell.GetSpellCooldown(spellId);local start,duration;if type(cooldown)=="table"then start,duration=cooldown.startTime,cooldown.duration elseif GetSpellCooldown then start,duration=GetSpellCooldown(spellId)end;if start==nil or duration==nil then return{state="UNAVAILABLE",spellId=spellId}end;local remaining=math.max(0,start+duration-((GetTime and GetTime())or 0));return{state=remaining>0 and"COOLDOWN"or"READY",spellId=spellId,remaining=remaining}end
 local function teleportTooltip(row,tooltip)local state=row.teleport;if state.spellId and tooltip.SetSpellByID then tooltip:SetSpellByID(state.spellId)else tooltip:SetText(row.name)end;if state.state=="READY"then tooltip:AddLine(L["TELEPORT_READY"],.2,1,.2,true)elseif state.state=="COOLDOWN"then local value=SecondsToClock and SecondsToClock(state.remaining)or tostring(math.ceil(state.remaining));tooltip:AddLine(string.format(L["TELEPORT_COOLDOWN"],value),1,.3,.3,true)else tooltip:AddLine(L["TELEPORT_UNAVAILABLE"],.7,.7,.7,true)end end
 local function castTeleport(row)local state=row.teleport;if not state or state.state~="READY"or not state.spellId then return end;if CastSpellByID then CastSpellByID(state.spellId)elseif C_Spell and C_Spell.CastSpell then C_Spell.CastSpell(state.spellId)end end
 local function dungeonCell(cell,_,row)if not cell.teleportButton then local button=CreateFrame("Button",nil,cell.frame);button:SetSize(20,20);button:SetPoint("LEFT",4,0);local texture=button:CreateTexture(nil,"ARTWORK");texture:SetAllPoints();button.texture=texture;button:SetScript("OnClick",function()castTeleport(cell.teleportRow)end);button:SetScript("OnEnter",function(owner)if not GameTooltip then return end;GameTooltip:SetOwner(owner,"ANCHOR_RIGHT");teleportTooltip(cell.teleportRow,GameTooltip);GameTooltip:Show()end);button:SetScript("OnLeave",function()if GameTooltip then GameTooltip:Hide()end end);cell.teleportButton=button;cell.text:ClearAllPoints();cell.text:SetPoint("LEFT",30,0);cell.text:SetPoint("RIGHT",-4,0)end;cell.teleportRow=row;cell.teleportButton.texture:SetTexture(row.texture or"Interface\\Icons\\Spell_Arcane_TeleportStormWind");cell.teleportButton:SetEnabled(row.teleport.state=="READY");cell.teleportButton:SetAlpha(row.teleport.state=="READY"and 1 or row.teleport.state=="COOLDOWN"and.65 or.3);cell:SetDisplay(row.name)end
 local function openJournal(row)if row.instanceId and not(InCombatLockdown and InCombatLockdown())and EncounterJournal_OpenJournal then EncounterJournal_OpenJournal(nil,tonumber(row.instanceId))end end
 local function refresh(view,context)local C=HolyStorm.CharacterUI;local snapshot=C:GetSnapshot(context.characterUUID,"mythicPlus");if not snapshot or next(snapshot)==nil then C:SetTableView(view,{}, {emptyText=L["NO_MYTHICPLUS"]});return end;local rows,needsRefresh={},false;for _,dungeon in pairs(type(snapshot.dungeons)=="table"and snapshot.dungeons or{})do if type(dungeon)=="table"then local affixDataReady,unusable=affixDataState(dungeon);needsRefresh=needsRefresh or unusable;rows[#rows+1]={name=dungeon.name or C:FormatState(nil),instanceId=dungeon.instanceId,texture=dungeon.texture,teleport=teleportState(dungeon),tyrannical=keyResult(affixEntry(dungeon,"TYRANNICAL"),affixDataReady,dungeon.timeLimit),fortified=keyResult(affixEntry(dungeon,"FORTIFIED"),affixDataReady,dungeon.timeLimit),rating=snapshot.scoreDataReady==false and C:FormatState(nil)or scoreText(dungeon.score)}end end;if needsRefresh and context.characterUUID==UnitGUID("player")and not view.affixRefreshRequested then view.affixRefreshRequested=true;HolyStorm:CallCapability("character.scan.mythicplus",true,"AFFIX_CATEGORY_REFRESH")elseif not needsRefresh then view.affixRefreshRequested=false end;table.sort(rows,function(a,b)return tostring(a.name)<tostring(b.name)end);C:SetTableView(view,rows,{summary=string.format(L["SEASON_SUMMARY"],C:FormatState(snapshot.seasonId or snapshot.seasonNumber),scoreText(snapshot.overallScore)),emptyText=L["NO_MYTHICPLUS"]})end
 local function build(parent)return HolyStorm.CharacterUI:CreateTableView(parent,{columns={{id="name",title=L["COLUMN_DUNGEON"],weight=1,minWidth=220,truncate=true,renderCell=dungeonCell,onClick=openJournal,tooltip=function(row,_,_,tooltip)tooltip:SetText(row.name);tooltip:AddLine(L["OPEN_JOURNAL"],1,1,1,true);return true end},{id="tyrannical",title=L["TYRANNICAL"],width=120,align="RIGHT"},{id="fortified",title=L["FORTIFIED"],width=120,align="RIGHT"},{id="rating",title=L["DUNGEON_SCORE"],width=110,align="RIGHT"}},rowHeight=28,headerHeight=26,columnGap=1,emptyText=L["NO_MYTHICPLUS"]})end
 HolyStorm:RegisterCharacterTab("characters",{id="mythicPlus",order=30,label=L["DISPLAY_NAME"],labelKey="MYTHICPLUS_DISPLAY_NAME",icon="Interface\\Icons\\Achievement_ChallengeMode_Gold",blocks={"mythicPlus"},events={"HS_MYTHICPLUS_UPDATED"},build=build,refresh=refresh})
 HolyStorm:RegisterCharacterSummarySection("characters",{id="mythicPlus",order=30,render=function(context)local snapshot=HolyStorm.CharacterUI:GetSnapshot(context.characterUUID,"mythicPlus");return{label=L["DISPLAY_NAME"],tabId="mythicPlus",value=snapshot and(L["OVERALL_RATING"]..": "..scoreText(snapshot.overallScore))or L["NO_MYTHICPLUS"]}end})
end

do
 local L=locale("RAID_");local baseDifficultyKeys={"LFR","NORMAL","HEROIC","MYTHIC"}
 local function raidKey(name)return type(name)=="string"and name:lower():gsub("[%s%p%c]+","")or nil end
 local function openJournal(row)if row.instanceId and not(InCombatLockdown and InCombatLockdown())and EncounterJournal_OpenJournal then EncounterJournal_OpenJournal(nil,tonumber(row.instanceId))end end
 local function raidCell(cell,_,row)if not cell.icon then cell.icon=cell.frame:CreateTexture(nil,"ARTWORK");cell.icon:SetSize(20,20);cell.icon:SetPoint("LEFT",4,0);cell.text:ClearAllPoints();cell.text:SetPoint("LEFT",28,0);cell.text:SetPoint("RIGHT",-4,0)end;cell.icon:SetTexture(row.icon or"Interface\\Icons\\INV_Sword_27");cell:SetDisplay(row.nameDisplay or row.name,row.name)end
 local function progress(row,key)local lockout=row.weekly[key];if lockout then return string.format("%d/%d",tonumber(lockout.killed)or 0,tonumber(lockout.total)or row.total or 0)end;return HolyStorm.CharacterUI:FormatState(nil)end
 local function weeklyTooltip(row,key,tooltip)
  tooltip:SetText(string.format(L["WEEKLY_TOOLTIP"],L["DIFFICULTY_"..key]or key));local lockout=row.weekly[key];if not lockout then tooltip:AddLine(L["NO_CURRENT_LOCKOUT"],.55,.55,.55);return true end;local bosses=lockout.bosses
  for _,boss in ipairs(bosses or{})do local state=boss.killed;if state==true then tooltip:AddLine(string.format(L["BOSS_KILLED"],boss.name or L["UNKNOWN"]),1,.2,.2)elseif state==false then tooltip:AddLine(string.format(L["BOSS_OPEN"],boss.name or L["UNKNOWN"]),.2,1,.2)else tooltip:AddLine(string.format(L["BOSS_UNKNOWN"],boss.name or L["UNKNOWN"]),.55,.55,.55)end end
  if not bosses or#bosses==0 then tooltip:AddLine(L["NO_DATA"],.55,.55,.55)end;return true
 end
 local function shortDifficulty(key)return key=="MYTHIC"and"M"or key=="HEROIC"and"H"or key=="NORMAL"and"N"or key=="TIMEWALKING"and"TW"or key=="LFR"and"LFR"or"?"end
 local function bestText(snapshot,row)local C=HolyStorm.CharacterUI;local best=C:GetBestProgress(snapshot,row);if not best and row then for _,key in ipairs({"LFR","NORMAL","HEROIC","MYTHIC","TIMEWALKING"})do local lockout=row.weekly[key];if lockout and(tonumber(lockout.killed)or 0)>0 then best={difficulty=key,killed=tonumber(lockout.killed)or 0,total=tonumber(lockout.total)or row.total or 0}end end end;if best and(tonumber(best.killed)or 0)>0 then return C:ColorDifficulty(best.difficulty,string.format("%s %d/%d",shortDifficulty(best.difficulty),best.killed,best.total))end;return snapshot.catalogReady==true and""or C:FormatState(nil)end
 local function bestTooltip(row,tooltip)
  local C=HolyStorm.CharacterUI;tooltip:SetText(L["BEST_TOOLTIP"]);local trustedById,trustedByName,fallbackByName,shown,shownTrusted={},{},{},0,{};local bestRows=C:BuildRaidBestRows(row.snapshot)
  for _,boss in ipairs(bestRows)do if C:RaidIdentityMatches(boss,row)then local nameKey=raidKey(boss.bossName);if boss.bossIdStable then trustedById[tostring(boss.bossId)]=boss else fallbackByName[nameKey]=boss end;trustedByName[nameKey]=boss end end
  local function addBest(boss)local short=shortDifficulty(boss.difficulty);tooltip:AddLine(string.format(L["BEST_ROW"],C:ColorDifficulty(boss.difficulty,short),boss.bossName,boss.kills),1,1,1);shown=shown+1;shownTrusted[boss]=true end
  for _,catalogBoss in ipairs(row.catalogBosses or{})do local nameKey=raidKey(catalogBoss.name);local boss=catalogBoss.id~=nil and(trustedById[tostring(catalogBoss.id)]or fallbackByName[nameKey])or trustedByName[nameKey];if boss then addBest(boss)else tooltip:AddLine(string.format(L["LIFETIME_UNKNOWN"],catalogBoss.name or L["UNKNOWN"]),.55,.55,.55);shown=shown+1 end end
  for _,boss in ipairs(bestRows)do if C:RaidIdentityMatches(boss,row)and not shownTrusted[boss]then addBest(boss)end end
  if shown==0 then tooltip:AddLine(L["NO_DATA"],.55,.55,.55)end;return true
 end
 local function raidTooltip(row,tooltip)tooltip:SetText(row.name);local lockout=row.weekly.TIMEWALKING;if lockout then tooltip:AddLine((L["DIFFICULTY_TIMEWALKING"]or"Timewalking")..": "..progress(row,"TIMEWALKING"),.4,.8,1);for _,boss in ipairs(lockout.bosses or{})do if boss.killed==true then tooltip:AddLine(string.format(L["BOSS_KILLED"],boss.name or L["UNKNOWN"]),1,.2,.2)elseif boss.killed==false then tooltip:AddLine(string.format(L["BOSS_OPEN"],boss.name or L["UNKNOWN"]),.2,1,.2)else tooltip:AddLine(string.format(L["BOSS_UNKNOWN"],boss.name or L["UNKNOWN"]),.55,.55,.55)end end end;tooltip:AddLine(L["OPEN_JOURNAL"],1,1,1,true);return true end
 local function columns()local result={{id="name",title=L["COLUMN_RAID"],weight=1,minWidth=200,truncate=true,renderCell=raidCell,onClick=openJournal,tooltip=function(row,_,_,tooltip)return raidTooltip(row,tooltip)end}};for _,key in ipairs(baseDifficultyKeys)do local difficultyKey=key;result[#result+1]={id=difficultyKey:lower(),title=L["DIFFICULTY_"..difficultyKey],width=90,compactWidth=68,align="RIGHT",tooltip=function(row,_,_,tooltip)return weeklyTooltip(row,difficultyKey,tooltip)end}end;result[#result+1]={id="best",title=L["COLUMN_BEST"],width=180,compactWidth=100,align="RIGHT",tooltip=function(row,_,_,tooltip)return bestTooltip(row,tooltip)end};return result end
 local function refresh(view,context)local C=HolyStorm.CharacterUI;local snapshot=C:GetSnapshot(context.characterUUID,"raid");if not snapshot then C:SetTableView(view,{}, {emptyText=L["NO_RAID"]});return end;local rows,byName,byId={},{},{};for _,catalog in ipairs(type(snapshot.raids)=="table"and snapshot.raids or{})do local row={name=catalog.name or C:FormatState(nil),instanceId=catalog.id,icon=catalog.icon,order=catalog.order or#rows+1,weekly={},catalogBosses=catalog.bosses or{},total=#(catalog.bosses or{}),catalogReady=snapshot.catalogReady==true,snapshot=snapshot};rows[#rows+1]=row;byName[raidKey(row.name)]=row;byId[tostring(row.instanceId)]=row end;for _,lockout in ipairs(type(snapshot.lockouts)=="table"and snapshot.lockouts or{})do local row=lockout.journalInstanceId and byId[tostring(lockout.journalInstanceId)]or byName[raidKey(lockout.name)];if not row then row={name=lockout.name or C:FormatState(nil),instanceId=lockout.journalInstanceId,order=1000+#rows,weekly={},catalogBosses=lockout.bosses or{},total=tonumber(lockout.total),catalogReady=false,snapshot=snapshot};rows[#rows+1]=row;byName[raidKey(row.name)]=row;if row.instanceId then byId[tostring(row.instanceId)]=row end end;local difficulty=C:GetDifficultyById(lockout.difficultyId);if difficulty then row.weekly[difficulty.id]=lockout end end;table.sort(rows,function(a,b)if a.order==b.order then return tostring(a.name)<tostring(b.name)end;return a.order<b.order end);for _,row in ipairs(rows)do for _,key in ipairs(baseDifficultyKeys)do row[key:lower()]=C:ColorDifficulty(key,progress(row,key))end;local timewalking=row.weekly.TIMEWALKING;if timewalking then row.timewalkingText=C:ColorDifficulty("TIMEWALKING","TW "..progress(row,"TIMEWALKING"));row.nameDisplay=row.name.."  "..row.timewalkingText end;row.best=bestText(snapshot,row)end;C:SetTableView(view,rows,{emptyText=L["NO_RAID"]})end
 local function build(parent)return HolyStorm.CharacterUI:CreateTableView(parent,{columns=columns(),rowHeight=27,headerHeight=26,columnGap=1,emptyText=L["NO_RAID"]})end
 HolyStorm:RegisterCharacterTab("characters",{id="raid",order=40,label=L["DISPLAY_NAME"],labelKey="RAID_DISPLAY_NAME",icon="Interface\\Icons\\INV_Sword_27",blocks={"raid"},events={"HS_RAIDLOCKS_UPDATED"},build=build,refresh=refresh})
 HolyStorm:RegisterCharacterSummarySection("characters",{id="raid",order=40,render=function(context)local C=HolyStorm.CharacterUI;local snapshot=C:GetSnapshot(context.characterUUID,"raid");return{label=L["DISPLAY_NAME"],tabId="raid",formatted=snapshot and bestText(snapshot,nil)or L["NO_RAID"]}end})
end

do
 local L=locale("DELVES_")
 local function field(value)local C=HolyStorm.CharacterUI;if type(value)=="boolean"then return value and L["YES"]or L["NO"]end;if type(value)~="table"then return C:FormatState(value)end;if value.status=="unknown"then return C:FormatState(nil)end;for _,key in ipairs({"value","count","level","name"})do if value[key]~=nil then return C:FormatState(value[key])end end;return L["PRESENT"]end
 local function refresh(view,context)local C=HolyStorm.CharacterUI;local snapshot=C:GetSnapshot(context.characterUUID,"delves");if not snapshot then C:SetTableView(view,{}, {emptyText=L["NO_DELVES"]});return end;local rows={{group=L["GROUP_OVERVIEW"],metric=L["GREAT_VAULT"],value=field(snapshot.weeklyProgress),details=""},{group=L["GROUP_OVERVIEW"],metric=L["BOUNTIFUL"],value=field(snapshot.bountiful),details=""},{group=L["GROUP_RESOURCES"],metric=L["KEY_FRAGMENTS"],value=field(snapshot.keyFragments),details=""},{group=L["GROUP_RESOURCES"],metric=L["COMPLETED_KEYS"],value=field(snapshot.completedKeys),details=""},{group=L["GROUP_RESOURCES"],metric=L["TREASURE_MAP"],value=field(snapshot.treasureMap),details=""},{group=L["GROUP_RESOURCES"],metric=L["MAP_USED"],value=field(snapshot.treasureMapUsed),details=""},{group=L["GROUP_COMPANION"],metric=L["COMPANION"],value=field(snapshot.companion),details=""},{group=L["GROUP_COMPANION"],metric=L["FLUTE"],value=field(snapshot.flute),details=""},{group=L["GROUP_COMPANION"],metric=L["MINI_ROGUE"],value=field(snapshot.miniRogue),details=""}};for index,activity in ipairs(type(snapshot.activities)=="table"and snapshot.activities or{})do rows[#rows+1]={group=L["GROUP_ACTIVITIES"],metric=string.format(L["ACTIVITY"],activity.index or index),value=field(activity.progress),details=string.format(L["ACTIVITY_DETAILS"],field(activity.threshold),field(activity.level))}end;C:SetTableView(view,rows,{summary=string.format(L["SEASON"],field(snapshot.seasonNumber)),emptyText=L["NO_DELVES"]})end
 local function build(parent)return HolyStorm.CharacterUI:CreateTableView(parent,{columns={{id="group",title=L["COLUMN_GROUP"],width=135},{id="metric",title=L["COLUMN_METRIC"],weight=1,minWidth=190},{id="value",title=L["COLUMN_VALUE"],width=130,align="RIGHT"},{id="details",title=L["COLUMN_DETAILS"],weight=.8,minWidth=160}},rowHeight=26,headerHeight=26,columnGap=1,emptyText=L["NO_DELVES"]})end
 HolyStorm:RegisterCharacterTab("characters",{id="delves",order=50,label=L["DISPLAY_NAME"],labelKey="DELVES_DISPLAY_NAME",icon="Interface\\Icons\\INV_Misc_Map_01",blocks={"delves"},events={"HS_DELVES_UPDATED"},build=build,refresh=refresh})
 HolyStorm:RegisterCharacterSummarySection("characters",{id="delves",order=50,render=function(context)local snapshot=HolyStorm.CharacterUI:GetSnapshot(context.characterUUID,"delves");return{label=L["DISPLAY_NAME"],tabId="delves",value=snapshot and(L["GREAT_VAULT"]..": "..field(snapshot.weeklyProgress))or L["NO_DELVES"]}end})
end
