local L=LibStub("AceLocale-3.0"):NewLocale("Holy_Storm_Achievements","deDE")
if not L then return end
L["SOURCE_FILTER"]="Gildenfilter"
L["SOURCE_MANUAL"]="Manuelle Auswahl"
L["RULE_FIELD_GUILD_ACHIEVEMENT"]="Gildenerfolg"
L["RULE_FIELD_GUILD_ACHIEVEMENT_DESC"]="Ob der Charakter den ausgewählten Holy-Storm-Gildenerfolg verdient hat."
L["PASS"]="Berechtigt";L["FAIL"]="Nicht berechtigt"
L["TASK_PREVIEW"]="Erfolgsvergabe-Vorschau erstellen";L["TASK_AWARD"]="Erfolgsvergaben speichern";L["TASK_REVOKE"]="Erfolgsvergabe widerrufen"
L["DISPLAY_NAME"]="Gildenerfolge";L["DESCRIPTION"]="Gildeneigene Erfolge erstellen, vergeben und verfolgen.";L["ACHIEVEMENT"]="Erfolg";L["ACHIEVEMENTS"]="Erfolge";L["CATEGORY_GENERAL"]="Allgemein";L["EARNED"]="✓ Verdient";L["NOT_EARNED"]="○ Nicht verdient";L["UNKNOWN"]="? Unbekannt";L["AUTOMATIC"]="Automatisch";L["MANUAL"]="Manuell";L["FEAT_OF_STRENGTH"]="Heldentat";L["DRAFT"]="Entwurf";L["ACTIVE"]="Aktiv";L["ARCHIVED"]="Archiviert";L["SEARCH"]="Suchen";L["ALL"]="Alle";L["NEW"]="Neu";L["EDIT"]="Bearbeiten";L["SAVE_DRAFT"]="Entwurf speichern";L["ACTIVATE"]="Aktivieren";L["ARCHIVE"]="Archivieren";L["BACK"]="Zurück";L["NAME"]="Name";L["DESCRIPTION_FIELD"]="Beschreibung";L["CATEGORY"]="Kategorie";L["ICON"]="Symbol";L["TYPE"]="Typ";L["SCOPE"]="Bezug";L["CHARACTER"]="Charakter";L["ACCOUNT"]="Account";L["REPEATABLE"]="Wiederholbar";L["CONDITIONS"]="Bedingungen";L["AWARD"]="Erfolg vergeben";L["TEST"]="Testmodus";L["REVOKE"]="Vergabe widerrufen";L["RECIPIENTS"]="Ausgezeichnete Mitglieder";L["NO_ACHIEVEMENTS"]="Keine sichtbaren Erfolge.";L["NO_AWARDS"]="Keine aktiven Vergaben.";L["CREATED_BY"]="Erstellt von";L["REVISION"]="Revision";L["PREVIEW"]="Vergabevorschau";L["CAPTURED_AT"]="Kandidaten erfasst am %s";L["PREVIEW_COUNTS"]="%d Kandidaten · %d berechtigt · %d fehlgeschlagen · %d unbekannt";L["CONFIRM_AWARD"]="Diesen Erfolg an genau %d berechtigte Empfänger vergeben?";L["CONFIRM_REVOKE"]="%s für %s widerrufen?";L["CONFIRM"]="Bestätigen";L["CANCEL"]="Abbrechen";L["TEST_WARNING"]="TEST — ES WERDEN KEINE VERGABEN GESPEICHERT";L["PERMISSION_DENIED"]="Keine Berechtigung.";L["INVALID"]="Ungültig: %s";L["EARNED_NOTIFICATION"]="Erfolg verdient: %s";L["TASK_EVALUATE"]="Gildenerfolg auswerten";L["SOURCE_GUILD"]="Gildenroster";L["SOURCE_PARTY"]="Aktuelle Gruppe";L["SOURCE_RAID"]="Aktueller Schlachtzug";L["STATUS_RESULT"]="Ergebnis: %s";L["AWARDED_AT"]="Vergeben am";L["AWARDED_BY"]="Vergeben von";L["NOT_VISIBLE"]="Dieser Erfolg ist nicht sichtbar.";L["TAB_ACHIEVEMENTS"]="Erfolge";L["NO_RULE"]="Keine Bedingungen (berechtigt)";L["DEFINITION_SAVED"]="Erfolgsdefinition gespeichert.";L["AWARD_SAVED"]="Vergaben gespeichert.";L["REVOKED"]="Widerrufen";L["REASON"]="Grund";L["FILTER_EARNED"]="Verdient";L["FILTER_NOT_EARNED"]="Nicht verdient"
L["COLUMN_STATE"]="Status"
