local L=LibStub("AceLocale-3.0"):NewLocale("Holy_Storm_Achievements","enUS",true)
if not L then return end
L["SOURCE_FILTER"]="Guild filter"
L["SOURCE_MANUAL"]="Manual selection"
L["RULE_FIELD_GUILD_ACHIEVEMENT"]="Guild achievement"
L["RULE_FIELD_GUILD_ACHIEVEMENT_DESC"]="Whether the character has earned the selected Holy Storm guild achievement."
L["PASS"]="Eligible";L["FAIL"]="Failed"
L["TASK_PREVIEW"]="Build achievement award preview";L["TASK_AWARD"]="Persist achievement awards";L["TASK_REVOKE"]="Revoke achievement award"
L["DISPLAY_NAME"]="Guild Achievements";L["DESCRIPTION"]="Create, award and track guild-defined achievements.";L["ACHIEVEMENT"]="Achievement";L["ACHIEVEMENTS"]="Achievements";L["CATEGORY_GENERAL"]="General";L["EARNED"]="✓ Earned";L["NOT_EARNED"]="○ Not earned";L["UNKNOWN"]="? Unknown";L["AUTOMATIC"]="Automatic";L["MANUAL"]="Manual";L["FEAT_OF_STRENGTH"]="Feat of Strength";L["DRAFT"]="Draft";L["ACTIVE"]="Active";L["ARCHIVED"]="Archived";L["SEARCH"]="Search";L["ALL"]="All";L["NEW"]="New";L["EDIT"]="Edit";L["SAVE_DRAFT"]="Save draft";L["ACTIVATE"]="Activate";L["ARCHIVE"]="Archive";L["BACK"]="Back";L["NAME"]="Name";L["DESCRIPTION_FIELD"]="Description";L["CATEGORY"]="Category";L["ICON"]="Icon";L["TYPE"]="Type";L["SCOPE"]="Scope";L["CHARACTER"]="Character";L["ACCOUNT"]="Account";L["REPEATABLE"]="Repeatable";L["CONDITIONS"]="Conditions";L["AWARD"]="Award achievement";L["TEST"]="Test mode";L["REVOKE"]="Revoke award";L["RECIPIENTS"]="Earned members";L["NO_ACHIEVEMENTS"]="No visible achievements.";L["NO_AWARDS"]="No active awards.";L["CREATED_BY"]="Created by";L["REVISION"]="Revision";L["PREVIEW"]="Award preview";L["CAPTURED_AT"]="Candidates captured at %s";L["PREVIEW_COUNTS"]="%d candidates · %d eligible · %d failed · %d unknown";L["CONFIRM_AWARD"]="Award this achievement to exactly %d eligible recipients?";L["CONFIRM_REVOKE"]="Revoke %s for %s?";L["CONFIRM"]="Confirm";L["CANCEL"]="Cancel";L["TEST_WARNING"]="TEST — NO AWARDS WILL BE SAVED";L["PERMISSION_DENIED"]="Permission denied.";L["INVALID"]="Invalid: %s";L["EARNED_NOTIFICATION"]="Achievement earned: %s";L["TASK_EVALUATE"]="Evaluate guild achievement";L["SOURCE_GUILD"]="Guild roster";L["SOURCE_PARTY"]="Current party";L["SOURCE_RAID"]="Current raid";L["STATUS_RESULT"]="Result: %s";L["AWARDED_AT"]="Awarded at";L["AWARDED_BY"]="Awarded by";L["NOT_VISIBLE"]="This achievement is not visible.";L["TAB_ACHIEVEMENTS"]="Achievements";L["NO_RULE"]="No conditions (eligible)";L["DEFINITION_SAVED"]="Achievement definition saved.";L["AWARD_SAVED"]="Awards saved.";L["REVOKED"]="Revoked";L["REASON"]="Reason";L["FILTER_EARNED"]="Earned";L["FILTER_NOT_EARNED"]="Not earned"
