local L=LibStub("AceLocale-3.0"):NewLocale("Holy_Storm_Chat","enUS",true)
L["DISPLAY_NAME"]="Chat"
L["DESCRIPTION"]="Enriches chat messages with Holy Storm links, URLs and mention alerts."
L["CHAT_URL_COPY_HELP"]="Copy this URL manually (Ctrl+C). WoW addons cannot open your browser or access the operating-system clipboard."
L["CHAT_URL_TOOLTIP"]="External URL - click to copy"
L["CHAT_SETTINGS"]="Chat";L["CHAT_ENABLED"]="Enable chat enrichment";L["CHAT_PLAYER_ENRICHMENT"]="Enrich known player names";L["CHAT_CLASS_COLORS"]="Use class colors";L["CHAT_PLAYER_TOOLTIPS"]="Player tooltips";L["CHAT_SHOW_MAIN"]="Show main character";L["CHAT_SHOW_REAL_NAME"]="Show shared real name";L["CHAT_REAL_NAME_PRIVACY"]="Only voluntarily shared Holy Storm account metadata is shown.";L["CHAT_LINKS"]="Holy Storm links and tokens";L["CHAT_URLS"]="Detect web URLs"
L["CHAT_MENTIONS"]="Mentions";L["CHAT_MENTION_ENABLED"]="Enable mention alerts";L["CHAT_MENTION_CHARACTER"]="Detect character name";L["CHAT_MENTION_REAL_NAME"]="Detect shared real name";L["CHAT_MENTION_OWN"]="Alert for own messages";L["CHAT_MENTION_SOUND"]="Notification sound";L["CHAT_SOUND_TEST"]="Test sound";L["CHAT_SOUND_TELL"]="Whisper";L["CHAT_SOUND_READY_CHECK"]="Ready check";L["CHAT_SOUND_RAID_WARNING"]="Raid warning"
L["CHAT_CHANNELS"]="Channels";L["CHAT_CHANNEL_GUILD"]="Guild";L["CHAT_CHANNEL_OFFICER"]="Officer";L["CHAT_CHANNEL_PARTY"]="Party";L["CHAT_CHANNEL_PARTY_LEADER"]="Party leader";L["CHAT_CHANNEL_RAID"]="Raid";L["CHAT_CHANNEL_RAID_LEADER"]="Raid leader";L["CHAT_CHANNEL_INSTANCE_CHAT"]="Instance";L["CHAT_CHANNEL_INSTANCE_CHAT_LEADER"]="Instance leader";L["CHAT_CHANNEL_WHISPER"]="Whisper";L["CHAT_CHANNEL_WHISPER_INFORM"]="Outgoing whisper";L["CHAT_CHANNEL_SAY"]="Say";L["CHAT_CHANNEL_YELL"]="Yell"
L["CHAT_DIAGNOSTICS"]="Developer diagnostics";L["CHAT_DIAGNOSTICS_FORMAT"]="Enabled: %s | Player index: %d | Link types: %d | Tokens: %d\nActive channels: %s\nProcessed: %d | Errors: %d";L["CHAT_PARSER_TEST"]="Parser test input";L["CHAT_PARSER_EMPTY"]="Enter text to inspect the rendered result."
