local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm")
local L=LibStub("AceLocale-3.0"):GetLocale("Holy_Storm_Policy")
local UI={}
local DEFAULT_LOGIC="AND"
local function copy(v)return HolyStorm.Utils.DeepCopy(v)end
function UI:Label(parent,text,template)local label=parent:CreateFontString(nil,"OVERLAY",template or"GameFontHighlightSmall");label:SetText(text or"");label:SetJustifyH("LEFT");return label end
function UI:Button(parent,text,width,callback)local b=CreateFrame("Button",nil,parent,"UIPanelButtonTemplate");b:SetSize(width or 100,23);b:SetText(text);b:SetScript("OnClick",callback);return b end
function UI:Edit(parent,width,onChanged)local e=CreateFrame("EditBox",nil,parent,"InputBoxTemplate");e:SetSize(width or 180,22);e:SetAutoFocus(false);if onChanged then e:SetScript("OnTextChanged",onChanged)end;return e end
function UI:NewId(prefix)return string.format("%s-%08x-%04x",prefix,HolyStorm.Utils.Now()%0xffffffff,math.random(0,0xffff))end
function UI:DisplayGroupName(group)return group and group.nameKey and L[group.nameKey]or group and group.name or"-"end
function UI:Value(text)local n=tonumber(text);if n then return n end;if text=="true"then return true elseif text=="false"then return false elseif text:find(",",1,true)then local result={};for value in text:gmatch("[^,]+")do result[#result+1]=value:match("^%s*(.-)%s*$")end;return result end;return text end
function UI:FlattenTrace(trace)local function label(entry)return entry.status=="UNKNOWN"and L["UNKNOWN"]or entry.result and L["PASSED"]or L["FAILED"]end;local lines={};for _,entry in ipairs(trace or{})do if entry.kind=="condition"then lines[#lines+1]=string.format("%s %s %s [%s -> %s]",entry.field or"?",entry.operator or"?",tostring(entry.expected),tostring(entry.actual),label(entry))elseif entry.kind=="group"then lines[#lines+1]=string.format("%s -> %s",entry.logic,label(entry))else lines[#lines+1]=tostring(entry.error).." ("..label(entry)..")"end end;return table.concat(lines,"\n")end
function UI:CreateTextPanel(parent)local scroll=CreateFrame("ScrollFrame",nil,parent,"UIPanelScrollFrameTemplate");local content=CreateFrame("Frame",nil,scroll);content:SetSize(1,1);scroll:SetScrollChild(content);local text=self:Label(content,"","GameFontHighlightSmall");text:SetPoint("TOPLEFT",4,-4);text:SetPoint("RIGHT",-4,0);text:SetJustifyV("TOP");text:SetWordWrap(true);scroll:HookScript("OnSizeChanged",function(s)content:SetWidth(s:GetWidth());text:SetWidth(math.max(1,s:GetWidth()-8))end);return scroll,text,content end
function UI:CreateList(parent,onSelect)
 local frame=CreateFrame("Frame",nil,parent);frame.rows={};frame.selected=nil;frame.offset=0;frame:EnableMouseWheel(true)
 function frame:RefreshRows()for _,row in ipairs(self.rows)do row:Hide()end;for slot=1,math.min(24,#(self.items or{}))do local item=self.items[self.offset+slot];if not item then break end;local index=slot;local row=self.rows[index]or UI:Button(self,"",190,function()local r=self.rows[index];self.selected=r.item;onSelect(r.item)end);self.rows[index]=row;row.item=item;row:SetText(self.labeler and self.labeler(item)or tostring(item.name or item.id));row:ClearAllPoints();row:SetPoint("TOPLEFT",0,-((index-1)*25));row:Show()end end
 function frame:SetItems(items,labeler)self.items=items or{};self.labeler=labeler;self.offset=math.min(self.offset,math.max(0,#self.items-24));self:RefreshRows()end
 frame:SetScript("OnMouseWheel",function(self,delta)self.offset=math.max(0,math.min(math.max(0,#(self.items or{})-24),self.offset-delta*3));self:RefreshRows()end)
 return frame
end
function UI:CreateSelector(parent,width,getItems,onSelect)
 local menu=CreateFrame("Frame",nil,parent,"UIDropDownMenuTemplate");UIDropDownMenu_SetWidth(menu,width or 180);UIDropDownMenu_Initialize(menu,function(_,level)if level~=1 then return end;for _,item in ipairs(getItems()or{})do local selected=item;local info=UIDropDownMenu_CreateInfo();info.text=item.label or item.name or item.id;info.disabled=item.disabled;info.checked=item.value==menu.value;info.func=function()menu.value=selected.value;UIDropDownMenu_SetText(menu,selected.label or selected.name or selected.id);if onSelect then onSelect(selected.value,selected)end end;UIDropDownMenu_AddButton(info,level)end end);function menu:SetValue(value,label)self.value=value;UIDropDownMenu_SetText(self,label or tostring(value or""))end;function menu:GetValue()return self.value end;return menu
end
function UI:CreateCheckList(parent,getItems,onToggle)
 local frame=CreateFrame("Frame",nil,parent);frame:SetSize(620,500);frame.rows={};frame.offset=0;frame:EnableMouseWheel(true)
 function frame:Refresh()self.items=getItems()or{};self.offset=math.min(self.offset,math.max(0,#self.items-20));for _,row in ipairs(self.rows)do row:Hide()end;for slot=1,20 do local item=self.items[self.offset+slot];if not item then break end;local index=slot;local row=self.rows[index]or CreateFrame("CheckButton",nil,self,"UICheckButtonTemplate");self.rows[index]=row;row.item=item;row.text:SetText(item.label or item.name or item.id);row:SetChecked(item.checked==true);row:SetEnabled(item.disabled~=true);row:SetScript("OnClick",function(c)onToggle(c.item.value,c:GetChecked()and true or false,c.item);frame:Refresh()end);row:ClearAllPoints();row:SetPoint("TOPLEFT",0,-((index-1)*25));row:Show()end end
 frame:SetScript("OnMouseWheel",function(self,delta)self.offset=math.max(0,math.min(math.max(0,#(self.items or{})-20),self.offset-delta*3));self:Refresh()end)
 return frame
end
function UI:CharacterItems()local out={};local guild=HolyStorm.Data.GuildStore:GetCurrent();for guid,member in pairs(guild and guild.roster or{})do out[#out+1]={value=guid,label=member.name or guid,member=member}end;table.sort(out,function(a,b)return a.label<b.label end);return out end
function UI:AccountItems()local seen,out={},{};for _,character in ipairs(self:CharacterItems())do local id=HolyStorm.TwinkCore and HolyStorm.TwinkCore:GetAccountUUIDForCharacter(character.value);if id and not seen[id]then seen[id]=true;local chars=HolyStorm.TwinkCore:GetCharactersForAccount(id);local main=HolyStorm.TwinkCore:GetAccountMain(id);local record=main and HolyStorm.Data.CharacterStore:Get(main);local label=record and record.name or main or id;out[#out+1]={value=id,label=string.format(L["ACCOUNT_SELECTOR_FORMAT"],label,HolyStorm.Utils.TableCount(chars)),main=main}end end;table.sort(out,function(a,b)return a.label<b.label end);return out end
function UI:GroupItems(excludeId)local out={};for _,group in pairs(HolyStorm.Policy:GetGroups())do out[#out+1]={value=group.id,label=self:DisplayGroupName(group),disabled=group.id==excludeId}end;table.sort(out,function(a,b)return a.label<b.label end);return out end
function UI:CreateRuleBuilder(parent,onChanged)
 local builder=CreateFrame("Frame",nil,parent);builder.root={logic="AND",children={{field="character.level",operator=">=",value=1}}};builder.selectedPath={1};builder.rows={}
 local logic=self:CreateSelector(builder,75,function()return{{value="AND",label=L["LOGIC_AND"]},{value="OR",label=L["LOGIC_OR"]},{value="NOT",label=L["LOGIC_NOT"]}}end,function(v)local n=builder:GetSelected();if n and n.logic then n.logic=v;if v=="NOT"then while#n.children>1 do table.remove(n.children)end end;builder:Changed()end end);logic:SetPoint("TOPLEFT",-15,3)
 local field=self:CreateSelector(builder,180,function()local out={};for id,definition in pairs(HolyStorm.Rules:GetFields())do out[#out+1]={value=id,label=definition.nameKey and(L[definition.nameKey]or id)or id,definition=definition}end;table.sort(out,function(a,b)return a.label<b.label end);return out end,function(v)local n=builder:GetSelected();if n and not n.logic then n.field=v;n.operator="=";builder:Changed()end end);field:SetPoint("LEFT",logic,"RIGHT",-20,0)
 local op=self:CreateSelector(builder,92,function()local n=builder:GetSelected();local def=n and HolyStorm.Rules:GetFields()[n.field];local kind=def and def.type or"string";local allowed=kind=="boolean"and{"=","!=","true","false","exists","not_exists"}or kind=="number"and{"=","!=",">",">=","<","<=","between","not_between","exists","not_exists"}or{"=","!=","contains","not_contains","starts_with","ends_with","in","not_in","exists","not_exists"};local out={};for _,v in ipairs(allowed)do out[#out+1]={value=v,label=L["OP_"..v:upper()]or v}end;return out end,function(v)local n=builder:GetSelected();if n and not n.logic then n.operator=v;builder:Changed()end end);op:SetPoint("LEFT",field,"RIGHT",-20,0)
 local value=self:Edit(builder,150);value:SetPoint("LEFT",op,"RIGHT",-12,0);local typedValue=self:CreateSelector(builder,150,function()local n=builder:GetSelected();local def=n and HolyStorm.Rules:GetFields()[n.field]or{};if def.type=="boolean"then return{{value=true,label=L["YES"]},{value=false,label=L["NO"]}}elseif def.type=="character"then return UI:CharacterItems()elseif def.type=="account"then return UI:AccountItems()elseif def.type=="enum"then local out={};for _,v in ipairs(def.values or{})do out[#out+1]={value=v,label=def.valueLabels and L[def.valueLabels[v]]or tostring(v)}end;return out end;return{}end,function(v)local n=builder:GetSelected();if n and not n.logic then n.value=v;builder:Changed()end end);typedValue:SetPoint("LEFT",op,"RIGHT",-28,0);local apply=self:Button(builder,L["APPLY"],75,function()local node=builder:GetSelected();if node and not node.logic then node.value=UI:Value(value:GetText());builder:Changed()end end);apply:SetPoint("LEFT",value,"RIGHT",8,0)
 local add=self:Button(builder,L["ADD_CONDITION"],130,function()local container=builder:GetContainer();local path=builder:GetContainerPath();container.children[#container.children+1]={field="character.level",operator=">=",value=1};builder.selectedPath=path;builder.selectedPath[#builder.selectedPath+1]=#container.children;builder:Changed()end);add:SetPoint("TOPLEFT",0,-30)
 local group=self:Button(builder,L["ADD_GROUP"],120,function()local container=builder:GetContainer();container.children[#container.children+1]={logic="AND",children={{field="character.level",operator=">=",value=1}}};builder:Changed()end);group:SetPoint("LEFT",add,"RIGHT",6,0)
 local remove=self:Button(builder,L["REMOVE"],90,function()local parentNode,index=builder:GetParent();if parentNode and index and#parentNode.children>1 then table.remove(parentNode.children,index);builder.selectedPath={};builder:Changed()end end);remove:SetPoint("LEFT",group,"RIGHT",6,0)
 builder.validation=UI:Label(builder,"");builder.validation:SetPoint("LEFT",remove,"RIGHT",12,0);builder.tree=CreateFrame("Frame",nil,builder);builder.tree:SetPoint("TOPLEFT",0,-60);builder.tree:SetPoint("BOTTOMRIGHT");builder.tree:EnableMouseWheel(true);builder.offset=0
 function builder:GetNode(path)local node=self.root;for _,index in ipairs(path or self.selectedPath)do node=node and node.children and node.children[index]end;return node end
 function builder:GetSelected()return self:GetNode(self.selectedPath)end
 function builder:GetParent()if#self.selectedPath==0 then return nil end;local path=copy(self.selectedPath);local index=table.remove(path);return self:GetNode(path),index end
 function builder:GetContainer()local node=self:GetSelected();if node and node.logic then return node end;local parentNode=self:GetParent();return parentNode or self.root end
 function builder:GetContainerPath()local node=self:GetSelected();if node and node.logic then return copy(self.selectedPath)end;local path=copy(self.selectedPath);table.remove(path);return path end
 function builder:SetRule(root)self.root=copy(root or{logic="AND",children={{field="character.level",operator=">=",value=1}}});if not self.root.logic then self.root={logic="AND",children={self.root}}end;self.selectedPath={};self:Render()end
 function builder:GetRule()return copy(self.root)end
 function builder:Validate()return HolyStorm.Rules:Validate(self.root)end
 function builder:Changed()if onChanged then onChanged()end;self:Render()end
 function builder:Render()for _,row in ipairs(self.rows)do row:Hide()end;local flat={};local function walk(node,path,depth)flat[#flat+1]={node=node,path=path,depth=depth};for i,child in ipairs(node.children or{})do local p=copy(path);p[#p+1]=i;walk(child,p,depth+1)end end;walk(self.root,{},0);self.flat=flat;self.offset=math.min(self.offset,math.max(0,#flat-14));for slot=1,14 do local entry=flat[self.offset+slot];if not entry then break end;local index=slot;local row=self.rows[index]or UI:Button(self.tree,"",590,function()local e=builder.flat[builder.offset+index];if e then builder.selectedPath=copy(e.path);builder:Render()end end);self.rows[index]=row;local n=entry.node;local label=n.logic and("["..(L["LOGIC_"..n.logic]or n.logic).."]")or string.format("%s  %s  %s",n.field or"?",n.operator or"=",type(n.value)=="table"and table.concat(n.value,",")or tostring(n.value or""));row:SetText(string.rep("    ",entry.depth)..label);row:ClearAllPoints();row:SetPoint("TOPLEFT",0,-((index-1)*25));row:Show()end;local selected=self:GetSelected()or self.root;if selected.logic then logic:SetValue(selected.logic,L["LOGIC_"..selected.logic]or selected.logic);value:Show();typedValue:Hide()else field:SetValue(selected.field,selected.field);op:SetValue(selected.operator or"=",L["OP_"..tostring(selected.operator or"="):upper()]or selected.operator);local def=HolyStorm.Rules:GetFields()[selected.field]or{};local typed=def.type=="boolean"or def.type=="enum"or def.type=="character"or def.type=="account";value:SetShown(not typed);typedValue:SetShown(typed);typedValue:SetValue(selected.value,tostring(selected.value or""));value:SetText(type(selected.value)=="table"and table.concat(selected.value,",")or tostring(selected.value or""))end;local valid,err=self:Validate();self.validation:SetText(valid and L["VALID_EXPRESSION"]or string.format(L["INVALID_EXPRESSION"],tostring(err)))end
 builder.tree:SetScript("OnMouseWheel",function(_,delta)builder.offset=math.max(0,math.min(math.max(0,#(builder.flat or{})-14),builder.offset-delta*3));builder:Render()end)
 builder:Render();return builder
end
function UI:CreateFilterBar(parent,contextId,onChanged)
 local bar=CreateFrame("Frame",nil,parent);bar:SetHeight(52);bar.contextId=contextId;bar.active=HolyStorm.Policy:GetActiveFilters(contextId);bar.chips={}
 local menu=CreateFrame("Frame",nil,bar,"UIDropDownMenuTemplate");menu:SetPoint("TOPLEFT",-16,0);UIDropDownMenu_SetWidth(menu,125);UIDropDownMenu_SetText(menu,L["FILTER"])
 local function changed()HolyStorm.Policy:SetActiveFilters(contextId,bar.active);if onChanged then onChanged()end end
 local function refresh()for _,chip in ipairs(bar.chips)do chip:Hide()end;local x=145;for i,entry in ipairs(bar.active)do local index=i;local filter=HolyStorm.Rules:GetFilter(entry.id,entry.scope);local chip=bar.chips[index]or UI:Button(bar,"",115,function()table.remove(bar.active,index);refresh();changed()end);bar.chips[index]=chip;chip:SetText((filter and filter.name or entry.id).." ×");chip:ClearAllPoints();chip:SetPoint("TOPLEFT",x,2);chip:Show();x=x+120 end end
 UIDropDownMenu_Initialize(menu,function(_,level)if level~=1 then return end;for _,scope in ipairs({"local","global"})do local selectedScope=scope;local root=HolyStorm.Policy:GetFilters(selectedScope);for id,filter in pairs(root or{})do local selectedId=id;local info=UIDropDownMenu_CreateInfo();info.text=(selectedScope=="global"and L["GLOBAL_BADGE"]or L["LOCAL_BADGE"])..filter.name;info.keepShownOnClick=true;local found;for index,entry in ipairs(bar.active)do if entry.id==selectedId and entry.scope==selectedScope then found=index end end;local foundIndex=found;info.checked=foundIndex~=nil;info.func=function()if foundIndex then table.remove(bar.active,foundIndex)else bar.active[#bar.active+1]={id=selectedId,scope=selectedScope}end;refresh();changed()end;UIDropDownMenu_AddButton(info,level)end end end)
 local reset=self:Button(bar,L["RESET"],110,function()for i=#bar.active,1,-1 do table.remove(bar.active,i)end;refresh();changed()end);reset:SetPoint("TOPLEFT",0,-28)
 local manage=self:Button(bar,L["MANAGE_FILTERS"],135,function()HolyStorm.UI:ShowPage("filters")end);manage:SetPoint("LEFT",reset,"RIGHT",6,0)
 function bar:Matches(value)return HolyStorm.Policy:ApplyFilters(self.active,value,"AND")end;function bar:Apply(items)local out={};for _,item in ipairs(items or{})do if self:Matches(item)then out[#out+1]=item end end;return out end;refresh();return bar
end
HolyStorm.PolicyUI=UI
