local addonVersion="1.0.0"
local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm");local L=LibStub("AceLocale-3.0"):GetLocale("Holy_Storm_Twinks")
local Profiles=HolyStorm:RegisterRequiredModule("Profiles");HolyStorm:ApplyModuleMetadata(Profiles,{id="Profiles",displayName=L["PROFILE_NAV"],internalName="profiles",version=addonVersion,category="required",description=L["PROFILE_DESC"],permissions={"player-read"},dependencies={"core"},enabledByDefault=true,ruleFields={
 {id="profile.preferredRole",aliases={"preferredRole"},type="string",name=L["RULE_FIELD_PREFERRED_ROLE"],nameKey="RULE_FIELD_PREFERRED_ROLE",description=L["RULE_FIELD_PREFERRED_ROLE_DESC"],descriptionKey="RULE_FIELD_PREFERRED_ROLE_DESC",category=L["PROFILE_NAV"],dependencies={"profile"},resolver=function(context)return context.character and context.character.profile and context.character.profile.preferredRole end},
 {id="profile.raidInterest",type="string",name=L["RULE_FIELD_RAID_INTEREST"],nameKey="RULE_FIELD_RAID_INTEREST",description=L["RULE_FIELD_RAID_INTEREST_DESC"],descriptionKey="RULE_FIELD_RAID_INTEREST_DESC",category=L["PROFILE_NAV"],dependencies={"profile"},resolver=function(context)return context.character and context.character.profile and context.character.profile.raidInterest end},
}})
local fields={{"displayName","PROFILE_DISPLAY_NAME"},{"location","PROFILE_LOCATION"},{"birthdate","PROFILE_BIRTHDATE"},{"preferredRole","PROFILE_ROLE"},{"alternateRoles","PROFILE_ALT_ROLES"},{"raidInterest","PROFILE_RAID"},{"mythicInterest","PROFILE_MYTHIC"},{"delveInterest","PROFILE_DELVES"}}
function Profiles:GetAccount()local p=HolyStorm.Data.PlayerStore:Get(HolyStorm.Data.PlayerStore:GetLocalPlayerId());p.metadata=type(p.metadata)=="table"and p.metadata or {};return p end
function Profiles:Select(guid)self.selected=guid;local p=self:GetAccount();local c=HolyStorm.Data.CharacterStore:Get(guid);local cp=c and c.profile or {};for i,x in ipairs(fields)do self.edits[i]:SetText(i<=3 and(p.metadata[x[1]]or"")or(cp[x[1]]or""))end end
function Profiles:Save()local guid=self.selected or UnitGUID("player");local accountMetadata,cp={},{};for i,x in ipairs(fields)do local v=HolyStorm.Utils.Trim(self.edits[i]:GetText());if i<=3 then if v~=""then accountMetadata[x[1]]=v end elseif v~=""then cp[x[1]]=v end end;HolyStorm.Data.PlayerStore:SetLocalMetadata(accountMetadata);HolyStorm.PlayerData:WriteOwnedBlock(guid,"profile",cp,"local");HolyStorm.Events:Emit("HS_UI_STATUS_REQUESTED",L["PROFILE_SAVED"])
end
function Profiles:CycleCharacter()local list={};for guid in pairs(self:GetAccount().characters or{})do list[#list+1]=guid end;table.sort(list);for i,guid in ipairs(list)do if guid==self.selected then self:Select(list[i%#list+1]);return end end;if list[1]then self:Select(list[1])end end
function Profiles:InitializeUI()local UI=HolyStorm:GetModule("UI",true);local p=CreateFrame("Frame",nil,UI.content);local h=p:CreateFontString(nil,"OVERLAY","GameFontHighlightLarge");h:SetPoint("TOPLEFT",20,-20);h:SetText(L["PROFILE_TITLE"]);local d=p:CreateFontString(nil,"OVERLAY","GameFontHighlightSmall");d:SetPoint("TOPLEFT",h,"BOTTOMLEFT",0,-8);d:SetText(L["PROFILE_DESC"]);local choose=CreateFrame("Button",nil,p,"UIPanelButtonTemplate");choose:SetSize(180,24);choose:SetPoint("TOPRIGHT",-20,-18);choose:SetText(L["PROFILE_CHARACTER"]);choose:SetScript("OnClick",function()Profiles:CycleCharacter()end);self.edits={};for i,x in ipairs(fields)do local y=-80-(i-1)*42;local label=p:CreateFontString(nil,"OVERLAY","GameFontNormal");label:SetPoint("TOPLEFT",20,y);label:SetText(L[x[2]]);local e=CreateFrame("EditBox",nil,p,"InputBoxTemplate");e:SetSize(300,24);e:SetPoint("TOPLEFT",190,y+6);e:SetAutoFocus(false);self.edits[i]=e end;local b=CreateFrame("Button",nil,p,"UIPanelButtonTemplate");b:SetSize(180,26);b:SetPoint("TOPLEFT",190,-430);b:SetText(L["PROFILE_SAVE"]);b:SetScript("OnClick",function()Profiles:Save()end);self.page=p;HolyStorm.UI:RegisterPage("profiles",p,L["PROFILE_TITLE"],function()Profiles:Select(Profiles.selected or UnitGUID("player"))end,{"HS_PROFILE_UPDATED"});HolyStorm.UI:AddNavigation("profiles",4,"Interface\\Icons\\Achievement_Character_Human_Male",L["PROFILE_NAV"],L["PROFILE_DESC"],function()HolyStorm.UI:ShowPage("profiles")end)end
function Profiles:OnInitialize()HolyStorm:RegisterUIExtension("Profiles",{id="characters.profiles",order=6,initialize=function()Profiles:InitializeUI()end})end
function Profiles:OnEnable()end
