local addonVersion="1.0.0"
local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm")
local L=LibStub("AceLocale-3.0"):GetLocale("Holy_Storm_Positions")
local metadata={id="Positions",name="Positions",internalName="positions",displayName=L["TITLE"],description=L["DESCRIPTION"],version=addonVersion,moduleType="feature",category="feature",permissions={{id="position-view",category="Positions",defaults={officers=true,member=true}},{id="position-share",category="Positions",defaults={officers=true,member=true}}},dependencies={"core","synchronization"},ui={page="positions",navigation=true},sync={domains={"guild-position"}},enabledByDefault=true}
HolyStorm:RegisterModule(metadata,function(Module)
local function yes(value)return value and L["YES"]or L["NO"]end
local function stamp(value)return value and date("%H:%M:%S",value)or"-"end
local columns={{key="character",label="COLUMN_CHARACTER",weight=.25},{key="position",label="COLUMN_POSITION",weight=.18},{key="age",label="COLUMN_AGE_SOURCE",weight=.15},{key="state",label="COLUMN_STATE",weight=.14},{key="pins",label="COLUMN_PINS",weight=.13},{key="transform",label="COLUMN_TRANSFORM",weight=.15}}
local function layoutRow(row,width)
 local left=0;width=math.max(300,width or 300);for _,column in ipairs(columns)do local cell=row.cells[column.key];local cellWidth=math.floor(width*column.weight);cell:ClearAllPoints();cell:SetPoint("TOPLEFT",row,"TOPLEFT",left+6,-3);cell:SetWidth(math.max(20,cellWidth-10));left=left+cellWidth end;row:SetWidth(width)
end
local function acquireRow(module,index)
 local row=module.rows[index];if row then row:Show();return row end;row=CreateFrame("Frame",nil,module.content);row:SetHeight(38);row.cells={};local background=row:CreateTexture(nil,"BACKGROUND");background:SetAllPoints();background:SetColorTexture(1,1,1,index%2==0 and.035 or.015);for _,column in ipairs(columns)do local cell=row:CreateFontString(nil,"OVERLAY","GameFontHighlightSmall");cell:SetJustifyH("LEFT");cell:SetJustifyV("TOP");cell:SetWordWrap(true);row.cells[column.key]=cell end;module.rows[index]=row;return row
end
function Module:Refresh()
 if not self.page or not self.page:IsShown()then return end;local d=HolyStorm.GuildPositions:GetDiagnostics();self.disabled:SetShown(not d.enabled);self.privacy:SetText(d.sharing and L["SHARING_ON"]or L["SHARING_OFF"]);self.privacy:SetTextColor(d.sharing and.2 or 1,d.sharing and 1 or.55,.2);local own=d.own and string.format("%s · %.4f, %.4f · %s",d.own.mapID,d.own.x,d.own.y,stamp(d.own.timestamp))or"-";local bucket=L["BUCKET_"..string.upper(d.movement.bucket or"stationary")]or d.movement.bucket;self.summary:SetText(string.format(L["DIAGNOSTIC_SUMMARY"],d.guildId or"-",bucket,d.movement.speed and string.format("%.1f",d.movement.speed)or"-",d.movement.lastSent and d.movement.lastSent>0 and string.format("%.1f",d.movement.lastSent)or"-",own,d.metrics.published,d.metrics.received,d.metrics.coalesced,d.metrics.droppedStale,d.metrics.rejected));local width=math.max(300,self.scroll:GetWidth()-8);layoutRow(self.header,width);local top=-32;for index,entry in ipairs(d.remote)do local row=acquireRow(self,index);row:ClearAllPoints();row:SetPoint("TOPLEFT",self.content,"TOPLEFT",0,top);layoutRow(row,width);row.cells.character:SetText(entry.characterUUID);row.cells.position:SetText(string.format("%s\n%.4f, %.4f",entry.mapID,entry.x,entry.y));row.cells.age:SetText(string.format("%ss · %s\n%s",math.max(0,HolyStorm.Utils.Now()-entry.timestamp),entry.source or"-",entry.receivedFrom or"-"));row.cells.state:SetText(string.format("%s: %s\n%s: %s",L["ONLINE_SHORT"],yes(entry.online),L["STALE_SHORT"],yes(entry.stale)));row.cells.pins:SetText(string.format("%s: %s\n%s: %s",L["WORLD_SHORT"],yes(entry.worldPin),L["MINIMAP_SHORT"],yes(entry.minimapPin)));row.cells.transform:SetText(string.format("%s → %s\n%s",entry.mapID,entry.viewedMapID or"-",entry.transform or entry.reason or"-"));top=top-38 end;for index=#d.remote+1,#self.rows do self.rows[index]:Hide()end;self.empty:SetShown(#d.remote==0);self.content:SetHeight(math.max(self.scroll:GetHeight(),-top+8))
end
function Module:BuildOptions()
 local function get(key)return HolyStorm.GuildPositions:GetSettings()[key]end;local function set(key)return function(_,value)HolyStorm.GuildPositions:SetSetting(key,value)end end;return{type="group",name=L["TITLE"],order=3,args={disabled={type="description",name=function()return HolyStorm.GuildPositions:IsEnabled()and""or L["MODULE_DISABLED"]end,order=1},privacy={type="group",name=L["PRIVACY"],inline=true,order=10,args={share={type="toggle",name=L["SHARE"],desc=L["SHARE_DESC"],order=1,get=function()return get("share")end,set=set("share"),disabled=function()return not HolyStorm.GuildPositions:IsEnabled()end}}},display={type="group",name=L["DISPLAY"],inline=true,order=20,args={show={type="toggle",name=L["DISPLAY_MEMBERS"],order=1,get=function()return get("display")end,set=set("display")},world={type="toggle",name=L["WORLD_MAP"],order=2,get=function()return get("worldMapEnabled")end,set=set("worldMapEnabled")},mini={type="toggle",name=L["MINIMAP"],order=3,get=function()return get("minimapEnabled")end,set=set("minimapEnabled")},current={type="toggle",name=L["CURRENT_MAP_ONLY"],order=4,get=function()return get("currentMapOnly")end,set=set("currentMapOnly")}}},markers={type="group",name=L["MARKERS"],inline=true,order=30,args={worldSize={type="range",name=L["WORLD_SIZE"],min=14,max=48,step=1,order=1,get=function()return get("worldMapSize")end,set=set("worldMapSize")},miniSize={type="range",name=L["MINIMAP_SIZE"],min=12,max=36,step=1,order=2,get=function()return get("minimapSize")end,set=set("minimapSize")},style={type="select",name=L["MARKER_STYLE"],values={CLASS=L["STYLE_CLASS"],GUILD=L["STYLE_GUILD"]},order=3,get=function()return get("markerStyle")end,set=set("markerStyle")}}}}}
end
function Module:InitializeUI()
 local UI=HolyStorm:GetModule("UI",true);local page=CreateFrame("Frame",nil,UI.content);self.page=page;local title=page:CreateFontString(nil,"OVERLAY","GameFontHighlightLarge");title:SetPoint("TOPLEFT",18,-18);title:SetText(L["TITLE"]);local description=page:CreateFontString(nil,"OVERLAY","GameFontHighlightSmall");description:SetPoint("TOPLEFT",title,"BOTTOMLEFT",0,-7);description:SetText(L["DESCRIPTION"]);local privacy=page:CreateFontString(nil,"OVERLAY","GameFontNormal");privacy:SetPoint("TOPLEFT",description,"BOTTOMLEFT",0,-12);self.privacy=privacy;local disabled=page:CreateFontString(nil,"OVERLAY","GameFontNormal");disabled:SetPoint("TOPLEFT",privacy,"BOTTOMLEFT",0,-8);disabled:SetText(L["MODULE_DISABLED"]);disabled:SetTextColor(1,.35,.2);self.disabled=disabled;local refresh=CreateFrame("Button",nil,page,"UIPanelButtonTemplate");refresh:SetSize(110,24);refresh:SetPoint("TOPRIGHT",-18,-18);refresh:SetText(L["REFRESH"]);refresh:SetScript("OnClick",function()HolyStorm.Tasks:Queue("Position.Reconcile",{priority=105,triggerSource="MANUAL"});Module:Refresh()end);local summary=page:CreateFontString(nil,"OVERLAY","GameFontHighlightSmall");summary:SetPoint("TOPLEFT",18,-104);summary:SetPoint("RIGHT",-18,0);summary:SetJustifyH("LEFT");self.summary=summary;local scroll=CreateFrame("ScrollFrame",nil,page,"UIPanelScrollFrameTemplate");scroll:SetPoint("TOPLEFT",18,-142);scroll:SetPoint("BOTTOMRIGHT",-30,18);local content=CreateFrame("Frame",nil,scroll);content:SetSize(1,1);scroll:SetScrollChild(content);self.scroll,self.content,self.rows=scroll,content,{};local header=CreateFrame("Frame",nil,content);header:SetPoint("TOPLEFT",content,"TOPLEFT",0,0);header:SetHeight(28);header.cells={};for _,column in ipairs(columns)do local cell=header:CreateFontString(nil,"OVERLAY","GameFontNormal");cell:SetTextColor(1,.82,0);cell:SetJustifyH("LEFT");cell:SetText(L[column.label]);header.cells[column.key]=cell end;self.header=header;local empty=content:CreateFontString(nil,"OVERLAY","GameFontHighlightSmall");empty:SetPoint("TOPLEFT",6,-38);empty:SetText(L["NONE"]);self.empty=empty;scroll:SetScript("OnSizeChanged",function(s)local width=math.max(300,s:GetWidth()-8);content:SetWidth(width);layoutRow(header,width);Module:Refresh()end);HolyStorm.UI:RegisterPage("positions",page,L["TITLE"],function()Module:Refresh()end);HolyStorm.UI:AddNavigation("positions",3.5,"Interface\\Icons\\Achievement_GuildPerk_EverybodysFriend",L["TITLE"],L["DESCRIPTION"],function()HolyStorm.UI:ShowPage("positions")end);local options=HolyStorm:GetModule("Options",true);if options and options.RegisterOptionsTab then options:RegisterOptionsTab("positions",self:BuildOptions())end
end
function Module:OnInitialize()
 HolyStorm.GuildPositions:Initialize();HolyStorm.GuildPositionMap:Initialize()
 HolyStorm:RegisterUIExtension("Positions",{id="positions.page",order=3.5,initialize=function()Module:InitializeUI()end})
end
function Module:OnEnable()for _,event in ipairs({"HS_GUILD_POSITION_UPDATED","HS_GUILD_POSITIONS_CLEARED","HS_GUILD_POSITIONS_RECONCILED","HS_POSITION_SETTINGS_CHANGED","HS_GUILD_POSITION_MAP_REFRESHED"})do local eventName=event;HolyStorm.Events:Register(eventName,"positions-ui",function()Module:Refresh()end)end end
function Module:OnDisable()HolyStorm.Events:UnregisterOwner("positions-ui")end
end)
