local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm")
local L=LibStub("AceLocale-3.0"):GetLocale("Holy_Storm_Equipment")
local columns={{width=.18},{width=.35},{width=.08},{width=.12},{width=.18},{width=.09,align="RIGHT"}}
local slots={{INVSLOT_HEAD,"SLOT_HEAD"},{INVSLOT_NECK,"SLOT_NECK"},{INVSLOT_SHOULDER,"SLOT_SHOULDER"},{INVSLOT_BACK,"SLOT_BACK"},{INVSLOT_CHEST,"SLOT_CHEST"},{INVSLOT_WRIST,"SLOT_WRIST"},{INVSLOT_HAND,"SLOT_HANDS"},{INVSLOT_WAIST,"SLOT_WAIST"},{INVSLOT_LEGS,"SLOT_LEGS"},{INVSLOT_FEET,"SLOT_FEET"},{INVSLOT_FINGER1,"SLOT_FINGER1"},{INVSLOT_FINGER2,"SLOT_FINGER2"},{INVSLOT_TRINKET1,"SLOT_TRINKET1"},{INVSLOT_TRINKET2,"SLOT_TRINKET2"},{INVSLOT_MAINHAND,"SLOT_MAINHAND"},{INVSLOT_OFFHAND,"SLOT_OFFHAND"}}
local function value(v)return v==nil and L["UNKNOWN"]or tostring(v)end
local function number(v)return tonumber(v)and string.format("%.1f",tonumber(v))or L["UNKNOWN"]end
local function linkedIcon(link,texture)local payload=link and link:match("|H([^|]+)|h");return payload and texture and("|H"..payload.."|h|T"..texture..":18:18|t|h")or(texture and("|T"..texture..":18:18|t")or"")end
local function linkedText(link,label)local payload=link and link:match("|H([^|]+)|h");return payload and("|H"..payload.."|h"..tostring(label).."|h")or tostring(label or"")end
local function gemDisplay(gem,itemLink)local C=HolyStorm.CharacterUI;if type(gem)=="table"and gem.empty then return linkedText(itemLink,gem.name or L["EMPTY_SOCKET"])end;local itemId=type(gem)=="table"and gem.itemId or gem;local storedName=type(gem)=="table"and gem.name;local storedLink=type(gem)=="table"and gem.link;local storedIcon=type(gem)=="table"and gem.icon;local name,link,_,_,_,_,_,_,_,icon;if GetItemInfo then name,link,_,_,_,_,_,_,_,icon=GetItemInfo(storedLink or itemId)end;name=name or storedName;link=link or storedLink;icon=icon or storedIcon or(C_Item and C_Item.GetItemIconByID and C_Item.GetItemIconByID(itemId));if not name and itemId and C_Item and C_Item.RequestLoadItemDataByID then C_Item.RequestLoadItemDataByID(itemId)end;if not link and itemId then link="|Hitem:"..tostring(itemId).."|h|cff3fc7eb["..tostring(name or string.format(L["GEM_ID"],itemId)).."]|r|h"end;local iconText=linkedIcon(link,icon);return(iconText~=""and(iconText.." ")or"")..(link or name or"")end
local function refresh(view,context,definition)local C=HolyStorm.CharacterUI;local ok,reason=C:CanUseTab(definition);if not ok then C:SetView(view,L["DISPLAY_NAME"],{reason=="PERMISSION"and L["PERMISSION_DENIED"]or L["MODULE_DISABLED"]});return end;local snapshot,meta=C:GetSnapshot(context.characterUUID,"equipment");local status=C:GetDataStatus(context.characterUUID,"equipment");if not snapshot then C:SetView(view,L["DISPLAY_NAME"],{L["NO_EQUIPMENT"]},status);return end;local lines={string.format("%s: %s",L["ITEM_LEVEL"],number(snapshot.itemLevel)),{cells={L["COLUMN_SLOT"],L["COLUMN_ITEM"],L["COLUMN_TIER"],L["COLUMN_ENCHANT"],L["COLUMN_GEMS"],L["COLUMN_ILVL"]},columns=columns,style="header",maxWidth=1650}};for _,slot in ipairs(slots)do local item=snapshot.slots and snapshot.slots[slot[1]];if item then local gems={};for index=1,tonumber(item.sockets or(type(item.gems)=="table"and#item.gems)or 0)do local gem=item.gems and item.gems[index];if gem then gems[#gems+1]=gemDisplay(gem,item.link)end end;local tier=item.isTier==true and"✓"or"";local enchant="";if(tonumber(item.enchantId)or 0)>0 then enchant=linkedText(item.link,item.enchantName or"✓")end;lines[#lines+1]={cells={linkedIcon(item.link,item.icon).." "..L[slot[2]],item.link or tostring(item.itemId or L["UNKNOWN"]),tier,enchant,table.concat(gems,"  "),value(item.itemLevel)},columns=columns,maxWidth=1650}else lines[#lines+1]={cells={L[slot[2]],L["EMPTY_SLOT"],"","","",""},columns=columns,maxWidth=1650}end end;C:SetView(view,L["DISPLAY_NAME"],lines,status,meta,{[1]="accent"})end
HolyStorm:RegisterCharacterTab("equipment",{id="equipment",order=20,label=L["DISPLAY_NAME"],labelKey="DISPLAY_NAME",icon="Interface\\Icons\\INV_Helmet_08",permission="equipment-read",moduleId="equipment",blocks={"equipment"},events={"HS_EQUIPMENT_UPDATED"},build=function(parent)return HolyStorm.CharacterUI:CreateTextView(parent)end,refresh=refresh})
HolyStorm:RegisterCharacterSummarySection("equipment",{id="equipment",order=20,render=function(context)local snapshot=HolyStorm.CharacterUI:GetSnapshot(context.characterUUID,"equipment");return{label=L["DISPLAY_NAME"],tabId="equipment",text="  "..(snapshot and(L["ITEM_LEVEL"]..": "..number(snapshot.itemLevel))or L["NO_EQUIPMENT"])}end})
