local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm")
local L=LibStub("AceLocale-3.0"):GetLocale("Holy_Storm_Achievements")
local A={version="1.0.0",sequence=0,types={AUTOMATIC=true,MANUAL=true,FEAT_OF_STRENGTH=true},statuses={DRAFT=true,ACTIVE=true,ARCHIVED=true},scopes={CHARACTER=true,ACCOUNT=true},pending={},index={dependencies={},status={},category={},recipient={},achievement={}},diagnostics={evaluations={},lastSync=nil},maxDescription=4000,maxRuleBytes=16000,maxAwardRecipients=30,maxAwardBytes=60000}
local function copy(v)return HolyStorm.Utils.DeepCopy(v)end
local function now()return HolyStorm.Utils.Now()end
local function id(prefix)A.sequence=A.sequence+1;return string.format("%s-%08x-%04x-%04x",prefix,now()%0xffffffff,A.sequence%0xffff,math.random(0,0xffff))end
local function validId(v)return type(v)=="string"and#v>0 and#v<=160 and v:match("^[%w_%.%-:]+$")~=nil end
local function log(level,category,message,context)HolyStorm.Logger:Write(level,"Achievements",category,message,context)end
function A:GetGuildId()return HolyStorm.Data.AchievementStore:GetGuildId()end
function A:Can(permission,actorGuid)return HolyStorm.Policy:Can(permission,nil,actorGuid or UnitGUID("player"))end
function A:ValidateDefinition(value,activating,portable)
 if type(value)~="table"or not validId(value.achievementID)then return false,"INVALID_ID"end;if type(value.name)~="string"or#value.name<1 or#value.name>120 then return false,"INVALID_NAME"end;if type(value.description or"")~="string"or#(value.description or"")>self.maxDescription then return false,"INVALID_DESCRIPTION"end;if not self.types[value.type]or not self.statuses[value.status]or not self.scopes[value.scope or"CHARACTER"]then return false,"INVALID_ENUM"end;if type(value.category)~="string"or#value.category<1 or#value.category>64 then return false,"INVALID_CATEGORY"end;if value.icon~=nil and type(value.icon)~="number"and type(value.icon)~="string"then return false,"INVALID_ICON"end
 local rule=value.rule;if rule then local serialized=HolyStorm.Serializer:Serialize(rule);if not serialized or#serialized>self.maxRuleBytes then return false,"RULE_TOO_LARGE"end;local ok,reason=(portable and HolyStorm.Rules.ValidatePortable or HolyStorm.Rules.Validate)(HolyStorm.Rules,rule);if not ok then return false,reason end elseif activating and value.type=="AUTOMATIC"then return false,"RULE_REQUIRED"end;return true
end
function A:NormalizeDefinition(input,current)
 local actor=UnitGUID("player");local value=copy(input);value.achievementID=current and current.achievementID or value.achievementID or id("achievement");value.type=value.type or"AUTOMATIC";value.status=value.status or"DRAFT";value.scope=value.scope or"CHARACTER";value.category=value.category or L["CATEGORY_GENERAL"];value.description=value.description or"";value.icon=value.icon or 236681;value.repeatable=value.type=="FEAT_OF_STRENGTH"and false or value.repeatable==true;value.createdBy=current and current.createdBy or actor;value.createdAt=current and current.createdAt or now();value.updatedBy=actor;value.updatedAt=now();value.revision=(current and current.revision or 0)+1;value.visibility=type(value.visibility)=="table"and value.visibility or{};value.dependencies=value.rule and HolyStorm.Rules:GetDependencies(value.rule)or{};return value
end
function A:GetDefinition(idValue)return HolyStorm.Data.AchievementStore:GetDefinition(idValue)end
function A:GetDefinitions(includeHidden,characterGuid)local out={};for _,definition in pairs(HolyStorm.Data.AchievementStore:GetDefinitions())do if(includeHidden or definition.status=="ACTIVE")and self:IsVisible(definition,characterGuid)then out[#out+1]=definition end end;table.sort(out,function(a,b)if a.category==b.category then return a.name<b.name end;return a.category<b.category end);return out end
function A:IsVisible(definition,characterGuid)if not self:Can("achievement-view")then return false end;local filter=definition.visibility and definition.visibility.filterId;if not filter then return true end;local ok=HolyStorm.Policy:ApplyFilter(filter,{guid=characterGuid or UnitGUID("player")},definition.visibility.scope);return ok==true end
function A:SaveDefinition(input)
 local current=input and input.achievementID and self:GetDefinition(input.achievementID);local permission=current and"achievement-edit"or"achievement-create";if not self:Can(permission)or(input.status=="ACTIVE"and(not current or current.status~="ACTIVE")and not self:Can("achievement-publish"))or(input.status=="ARCHIVED"and current and current.status~="ARCHIVED"and not self:Can("achievement-delete"))then log("WARN","permission","Definition mutation rejected",{permission=permission});return false,"PERMISSION_DENIED"end;local value=self:NormalizeDefinition(input,current);local ok,reason=self:ValidateDefinition(value,value.status=="ACTIVE");if not ok then return false,reason end;local saved,meta=HolyStorm.Data.AchievementStore:Put("D",value.achievementID,value,UnitGUID("player"));if saved then self:RebuildIndex();HolyStorm.Sync:Publish("achievements",meta.objectId,"ACHIEVEMENT_DEFINITION");if value.status=="ACTIVE"and value.type=="AUTOMATIC"then HolyStorm.Tasks:Queue("Achievement.Evaluate",{mergeKey=value.achievementID.."\031"..tostring(UnitGUID("player")),debounce=.2,triggerSource="DEFINITION_ACTIVATED",metadata={achievementID=value.achievementID,characterGuid=UnitGUID("player")}})end;log("INFO","definition",current and"Definition updated"or"Definition created",{achievementID=value.achievementID,revision=value.revision})end;return saved,saved and value or meta
end
function A:SetStatus(achievementID,status)if not self.statuses[status]then return false,"INVALID_STATUS"end;local definition=self:GetDefinition(achievementID);if not definition then return false,"NOT_FOUND"end;local permission=status=="ACTIVE"and"achievement-publish"or status=="ARCHIVED"and"achievement-delete"or"achievement-edit";if not self:Can(permission)then return false,"PERMISSION_DENIED"end;local nextValue=copy(definition);nextValue.status=status;return self:SaveDefinition(nextValue)end
function A:Recipient(definition,characterGuid)local recipient=characterGuid;if definition.scope=="ACCOUNT"then recipient=HolyStorm.TwinkCore and HolyStorm.TwinkCore:GetAccountUUIDForCharacter(characterGuid)end;return recipient end
function A:IsEarned(achievementID,characterGuid)local definition=self:GetDefinition(achievementID);if not definition then return false end;local recipient=self:Recipient(definition,characterGuid);if not recipient then return false end;return HolyStorm.Data.AchievementStore:IsEarned(achievementID,recipient)end
function A:BuildContext(characterGuid)return HolyStorm.Policy:BuildContext(nil,characterGuid,{achievementService=self})end
function A:Evaluate(definition,characterGuid)
 if not definition or not definition.rule then return HolyStorm.Rules.Result.PASS,{}end;for _,dependency in ipairs(definition.dependencies or{})do if HolyStorm.PlayerData and HolyStorm.PlayerData.blocks and HolyStorm.PlayerData.blocks[dependency]and HolyStorm.PlayerData:IsStale(characterGuid,dependency)then local trace={{kind="error",error="STALE_DATA:"..dependency,status=HolyStorm.Rules.Result.UNKNOWN,result=false}};self.diagnostics.evaluations[definition.achievementID.."\031"..characterGuid]={at=now(),status=HolyStorm.Rules.Result.UNKNOWN,trace=copy(trace),dependencies=copy(definition.dependencies)};return HolyStorm.Rules.Result.UNKNOWN,trace end end;local status,trace=HolyStorm.Rules:EvaluateDetailed(definition.rule,self:BuildContext(characterGuid));self.diagnostics.evaluations[definition.achievementID.."\031"..characterGuid]={at=now(),status=status,trace=copy(trace),dependencies=copy(definition.dependencies)};return status,trace
end
function A:NewAwardEvent(definition,candidates,provenance,issuer,testMode)
 if#candidates>self.maxAwardRecipients then return false,"TOO_MANY_CANDIDATES"end;local eventID=id("award");local snapshot={};for _,candidate in ipairs(candidates)do snapshot[#snapshot+1]={characterUUID=candidate.characterUUID,result=candidate.result}end;local event={awardInstanceID=eventID,achievementID=definition.achievementID,definitionRevision=definition.revision,capturedAt=provenance.capturedAt or now(),awardedAt=now(),awardedBy=issuer,provenance=copy(provenance),candidateSnapshot=snapshot,status="ACTIVE",awards={}}
 for _,candidate in ipairs(candidates)do if candidate.result==HolyStorm.Rules.Result.PASS then local recipient=self:Recipient(definition,candidate.characterUUID);local already=recipient and HolyStorm.Data.AchievementStore:IsEarned(definition.achievementID,recipient);if recipient and(definition.repeatable or not already)then event.awards[#event.awards+1]={awardID=eventID..":"..recipient,achievementID=definition.achievementID,awardInstanceID=eventID,recipientID=recipient,recipientScope=definition.scope,characterUUID=candidate.characterUUID,awardedAt=event.awardedAt,awardedBy=issuer,definitionRevision=definition.revision,provenance=provenance.kind,status="AWARDED"}end end end
 local serialized=HolyStorm.Serializer:Serialize(event);if not serialized or#serialized>self.maxAwardBytes then return false,"AWARD_EVENT_TOO_LARGE"end;if testMode then return true,event end;if#event.awards==0 then return false,"NO_ELIGIBLE_RECIPIENTS"end;local ok,meta=HolyStorm.Data.AchievementStore:Put("E",eventID,event,issuer);if ok then self:RebuildIndex();HolyStorm.Sync:Publish("achievements",meta.objectId,"ACHIEVEMENT_AWARD");for _,award in ipairs(event.awards)do self:Notify(award,definition)end;log("INFO","award","Award event created",{achievementID=definition.achievementID,awardInstanceID=eventID,recipients=#event.awards})end;return ok,ok and event or meta
end
function A:EvaluateAutomatic(achievementID,characterGuid)
 local definition=self:GetDefinition(achievementID);if not definition or definition.status~="ACTIVE"or definition.type~="AUTOMATIC"then return false,"NOT_ACTIVE_AUTOMATIC"end;if characterGuid~=UnitGUID("player")then return false,"RECIPIENT_OWNER_REQUIRED"end;if not definition.repeatable and self:IsEarned(achievementID,characterGuid)then return false,"DUPLICATE"end;local status,trace=self:Evaluate(definition,characterGuid);if status~=HolyStorm.Rules.Result.PASS then return false,status,trace end;return self:NewAwardEvent(definition,{{characterUUID=characterGuid,result=status,trace=trace}},{kind="AUTOMATIC",capturedAt=now()},characterGuid,false)
end
function A:QueueEvaluation(characterGuid,dependency)characterGuid=characterGuid or UnitGUID("player");for achievementID in pairs(self.index.dependencies[dependency]or{})do HolyStorm.Tasks:Queue("Achievement.Evaluate",{mergeKey=achievementID.."\031"..characterGuid,debounce=.5,triggerSource=dependency,metadata={achievementID=achievementID,characterGuid=characterGuid}})end end
function A:CaptureCandidates(source,manual)
 local seen,out={},{};local filterId=type(source)=="string"and source:match("^FILTER:(.+)$");local function add(guid)if validId(guid)and not seen[guid]then if filterId then local matched=HolyStorm.Policy:ApplyFilter(filterId,{guid=guid});if matched~=true then return end end;seen[guid]=true;out[#out+1]={characterUUID=guid}end end
 if source=="MANUAL"then for _,guid in ipairs(manual or{})do add(guid)end
 elseif source=="GUILD"or source=="FILTER"or filterId then local guild=HolyStorm.Data.GuildStore:GetCurrent();for guid in pairs(guild and guild.roster or{})do add(guid)end
 else local raid=source=="RAID";local count=raid and(GetNumGroupMembers and GetNumGroupMembers()or 0)or(GetNumSubgroupMembers and GetNumSubgroupMembers()or 0);if count==0 then add(UnitGUID("player"))else for index=1,count do add(UnitGUID(raid and("raid"..index)or("party"..index)))end;if not raid then add(UnitGUID("player"))end end end
 return out
end
function A:PreviewManual(achievementID,source,manual,testMode)
 if not self:Can(testMode and"achievement-test"or"achievement-award")then return false,"PERMISSION_DENIED"end;local definition=self:GetDefinition(achievementID);if not definition or definition.status~="ACTIVE"or definition.type=="AUTOMATIC"then return false,"INVALID_MANUAL_ACHIEVEMENT"end;local capturedAt=now();local candidates=self:CaptureCandidates(source,manual);local preview={previewID=id("preview"),achievementID=achievementID,source=source,capturedAt=capturedAt,testMode=testMode==true,candidates={},counts={total=#candidates,PASS=0,FAIL=0,UNKNOWN=0}}
 for _,candidate in ipairs(candidates)do local status,trace=self:Evaluate(definition,candidate.characterUUID);candidate.result,candidate.trace=status,trace;preview.counts[status]=preview.counts[status]+1;preview.candidates[#preview.candidates+1]=candidate end;local pendingCount=0;for _ in pairs(self.pending)do pendingCount=pendingCount+1 end;if pendingCount>=20 then local oldestKey,oldestAt;for key,value in pairs(self.pending)do if not oldestAt or value.capturedAt<oldestAt then oldestKey,oldestAt=key,value.capturedAt end end;if oldestKey then self.pending[oldestKey]=nil end end;self.pending[preview.previewID]=copy(preview);log("INFO","preview","Manual candidate snapshot created",{achievementID=achievementID,candidates=#candidates,testMode=testMode==true});return true,preview
end
function A:ConfirmManual(previewID)
 if not self:Can("achievement-award")then return false,"PERMISSION_DENIED"end;local preview=self.pending[previewID];if not preview then return false,"PREVIEW_NOT_FOUND"end;self.pending[previewID]=nil;local definition=self:GetDefinition(preview.achievementID);if not definition or definition.status~="ACTIVE"then return false,"DEFINITION_NOT_ACTIVE"end;if#preview.candidates<=self.maxAwardRecipients then return self:NewAwardEvent(definition,preview.candidates,{kind=definition.type,capturedAt=preview.capturedAt,source=preview.source},UnitGUID("player"),preview.testMode)end;local group={awardGroupID=id("awardgroup"),achievementID=definition.achievementID,capturedAt=preview.capturedAt,candidateSnapshot={},events={},awards={}};for _,candidate in ipairs(preview.candidates)do group.candidateSnapshot[#group.candidateSnapshot+1]={characterUUID=candidate.characterUUID,result=candidate.result}end;for first=1,#preview.candidates,self.maxAwardRecipients do local batch={};for index=first,math.min(first+self.maxAwardRecipients-1,#preview.candidates)do batch[#batch+1]=preview.candidates[index]end;local ok,result=self:NewAwardEvent(definition,batch,{kind=definition.type,capturedAt=preview.capturedAt,source=preview.source,awardGroupID=group.awardGroupID,batch=math.floor((first-1)/self.maxAwardRecipients)+1},UnitGUID("player"),preview.testMode);if ok then group.events[#group.events+1]=result;for _,award in ipairs(result.awards)do group.awards[#group.awards+1]=award end elseif result~="NO_ELIGIBLE_RECIPIENTS"then return false,result end end;if#group.awards==0 then return false,"NO_ELIGIBLE_RECIPIENTS"end;return true,group
end
function A:Revoke(awardID,reason)
 if not self:Can("achievement-revoke")then return false,"PERMISSION_DENIED"end;for _,event in pairs(HolyStorm.Data.AchievementStore:GetEvents())do for _,award in ipairs(event.awards or{})do if award.awardID==awardID then local earned,current=HolyStorm.Data.AchievementStore:IsEarned(award.achievementID,award.recipientID);if not earned then return false,"ALREADY_REVOKED"end;local correctionID=id("revoke");local target=copy(current or award);target.originalAwardInstanceID=target.originalAwardInstanceID or target.awardInstanceID;target.awardInstanceID=correctionID;target.status="REVOKED";target.revokedBy=UnitGUID("player");target.revokedAt=now();target.revokeReason=tostring(reason or""):sub(1,300);local correction={awardInstanceID=correctionID,achievementID=target.achievementID,definitionRevision=target.definitionRevision,capturedAt=target.revokedAt,awardedAt=target.awardedAt,awardedBy=target.awardedBy,provenance={kind="REVOKE",originalAwardInstanceID=target.originalAwardInstanceID},candidateSnapshot={},status="CORRECTION",awards={target}};local ok,meta=HolyStorm.Data.AchievementStore:Put("E",correctionID,correction,UnitGUID("player"));if ok then self:RebuildIndex();HolyStorm.Sync:Publish("achievements",meta.objectId,"ACHIEVEMENT_REVOKE");log("INFO","revoke","Award revoked",{awardID=awardID,correctionID=correctionID})end;return ok,ok and target or meta end end end;return false,"NOT_FOUND"
end
function A:RebuildIndex()
 local index={dependencies={},status={},category={},recipient={},achievement={}};for idValue,definition in pairs(HolyStorm.Data.AchievementStore:GetDefinitions())do index.status[definition.status]=index.status[definition.status]or{};index.status[definition.status][idValue]=true;index.category[definition.category]=index.category[definition.category]or{};index.category[definition.category][idValue]=true;if definition.status=="ACTIVE"and definition.type=="AUTOMATIC"then for _,dependency in ipairs(definition.dependencies or HolyStorm.Rules:GetDependencies(definition.rule))do index.dependencies[dependency]=index.dependencies[dependency]or{};index.dependencies[dependency][idValue]=true end end;local awards=HolyStorm.Data.AchievementStore:GetAwardsFor(idValue);for _,award in ipairs(awards)do index.recipient[award.recipientID]=index.recipient[award.recipientID]or{};index.recipient[award.recipientID][award.awardID]=award;index.achievement[award.achievementID]=index.achievement[award.achievementID]or{};index.achievement[award.achievementID][award.awardID]=award end end;self.index=index;HolyStorm.Events:Emit("HS_ACHIEVEMENT_INDEX_UPDATED")
end
function A:ValidateSync(payload,meta,objectId)local guildId,kind,idValue=HolyStorm.Data.AchievementStore:SplitObjectId(objectId);if guildId~=self:GetGuildId()or type(payload)~="table"or payload.guildId~=guildId or payload.kind~=kind or payload.id~=idValue or type(payload.data)~="table"then return false,"INVALID_PAYLOAD"end;if kind=="D"then return self:ValidateDefinition(payload.data,payload.data.status=="ACTIVE",true)end;local event=payload.data;local serialized=HolyStorm.Serializer:Serialize(event);if not serialized or#serialized>self.maxAwardBytes or not validId(event.awardInstanceID)or event.awardInstanceID~=idValue or not validId(event.achievementID)or type(event.awards)~="table"or#event.awards>self.maxAwardRecipients or type(event.candidateSnapshot)~="table"or#event.candidateSnapshot>self.maxAwardRecipients then return false,"INVALID_AWARD_EVENT"end;for _,award in ipairs(event.awards)do if type(award)~="table"or not validId(award.awardID)or not validId(award.recipientID)or not validId(award.characterUUID)or award.achievementID~=event.achievementID or award.awardInstanceID~=event.awardInstanceID or(award.status~="AWARDED"and award.status~="REVOKED")then return false,"INVALID_AWARD"end end;return true
end
function A:AuthorizeSync(payload,meta,senderId)local permission;if not meta.owner then return false end;if payload.kind=="D"then local current=self:GetDefinition(payload.id);if payload.data.updatedBy~=meta.owner or(not current and payload.data.createdBy~=meta.owner)then return false end;permission=current and"achievement-edit"or"achievement-create";if payload.data.status=="ACTIVE"and(not current or current.status~="ACTIVE")and not self:Can("achievement-publish",meta.owner)then return false end;if payload.data.status=="ARCHIVED"and current and current.status~="ARCHIVED"and not self:Can("achievement-delete",meta.owner)then return false end else local event=payload.data;local automatic=event.provenance and event.provenance.kind=="AUTOMATIC";local correction=event.provenance and event.provenance.kind=="REVOKE";if automatic then if#event.awards~=1 or event.awardedBy~=meta.owner then return false end;local award=event.awards[1];return award.status=="AWARDED"and award.characterUUID==meta.owner and award.awardedBy==meta.owner end;if correction then if#event.awards~=1 or event.awards[1].status~="REVOKED"or event.awards[1].revokedBy~=meta.owner then return false end;permission="achievement-revoke"else if event.awardedBy~=meta.owner then return false end;permission="achievement-award"end end;return self:Can(permission,meta.owner)==true
end
function A:Import(objectId,payload,meta)local guildId,kind,idValue=HolyStorm.Data.AchievementStore:SplitObjectId(objectId);local ok,result=HolyStorm.Data.AchievementStore:Put(kind,idValue,payload.data,meta.owner,meta,guildId);if ok then self:RebuildIndex();self.diagnostics.lastSync=now();if kind=="E"then local definition=self:GetDefinition(payload.data.achievementID);for _,award in ipairs(payload.data.awards or{})do if award.status=="AWARDED"then self:Notify(award,definition)end end end end;return ok,result end
function A:Notify(award,definition)if not definition or award.characterUUID~=UnitGUID("player")then return end;HolyStorm.Events:Emit("HS_ACHIEVEMENT_EARNED",award,definition);if HolyStorm.Notifications then HolyStorm.Notifications:Push("achievement",{award=award,definition=definition})elseif UIErrorsFrame and UIErrorsFrame.AddMessage then UIErrorsFrame:AddMessage(string.format(L["EARNED_NOTIFICATION"],definition.name),1,.82,0,1)end end
function A:Open(achievementID)if not self:IsVisible(self:GetDefinition(achievementID)or{})then return false end;HolyStorm.Events:Emit("HS_ACHIEVEMENT_OPEN_REQUESTED",achievementID);return true end
function A:QueuePreview(achievementID,source,manual,testMode)local requestID=id("request");local taskID,reason=HolyStorm.Tasks:Queue("Achievement.Preview",{mergeKey=requestID,triggerSource="MANUAL_PREVIEW",metadata={requestID=requestID,achievementID=achievementID,source=source,manual=copy(manual),testMode=testMode==true}});return taskID and requestID or false,reason end
function A:QueueConfirm(previewID)return HolyStorm.Tasks:Queue("Achievement.Award",{mergeKey=previewID,triggerSource="MANUAL_CONFIRM",metadata={previewID=previewID}})end
function A:QueueRevoke(awardID,reason)return HolyStorm.Tasks:Queue("Achievement.Revoke",{mergeKey=awardID,triggerSource="MANUAL_REVOKE",metadata={awardID=awardID,reason=reason}})end
function A:GetDiagnostics()return copy({index=self.index,evaluations=self.diagnostics.evaluations,lastSync=self.diagnostics.lastSync,pendingPreviews=self.pending})end
function A:Initialize()
 HolyStorm.Database:RegisterArea("achievements","profile",{sound=true});self:RebuildIndex();HolyStorm.Rules:RegisterConditionProvider("holystorm.achievement",{type="string",dependencies={"achievements"},get=function(context,node)local idValue=node.argument or node.value;if not A:GetDefinition(tostring(idValue))then return nil,"ACHIEVEMENT_NOT_FOUND"end;local earned=A:IsEarned(tostring(idValue),context.characterUUID);return earned and tostring(idValue)or"__NOT_EARNED__"end});if HolyStorm.Notifications then HolyStorm.Notifications:RegisterType("achievement",{title=function(payload)return payload.definition.name end,text=function()return L["EARNED"]end,icon=function(payload)return payload.definition.icon end,onClick=function(payload)A:Open(payload.definition.achievementID)end,sound=function()if HolyStorm.Database:Get("achievements.sound","profile")~=false and PlaySound then PlaySound(SOUNDKIT and SOUNDKIT.UI_70_ARTIFACT_FORGE_APPEARANCE_LOCKED or 12891,"Master")end end})end
 HolyStorm.Tasks:RegisterTaskType("Achievement.Evaluate",{name=L["TASK_EVALUATE"],localizedNameKey="TASK_EVALUATE",module="Achievements",priority=45,executionMode="MERGE_BY_KEY",conditions={"PLAYER_READY","GUILD_AVAILABLE"},execute=function(task)return A:EvaluateAutomatic(task.metadata.achievementID,task.metadata.characterGuid)end})
 HolyStorm.Tasks:RegisterTaskType("Achievement.Preview",{name=L["TASK_PREVIEW"],localizedNameKey="TASK_PREVIEW",module="Achievements",priority=42,executionMode="MERGE_BY_KEY",conditions={"PLAYER_READY","GUILD_AVAILABLE"},execute=function(task)local m=task.metadata;local ok,result=A:PreviewManual(m.achievementID,m.source,m.manual,m.testMode);HolyStorm.Events:Emit("HS_ACHIEVEMENT_PREVIEW_READY",m.requestID,ok,result);return ok end})
 HolyStorm.Tasks:RegisterTaskType("Achievement.Award",{name=L["TASK_AWARD"],localizedNameKey="TASK_AWARD",module="Achievements",priority=40,executionMode="MERGE_BY_KEY",conditions={"PLAYER_READY","GUILD_AVAILABLE"},execute=function(task)local ok,result=A:ConfirmManual(task.metadata.previewID);HolyStorm.Events:Emit("HS_ACHIEVEMENT_AWARD_FINISHED",ok,result);return ok end})
 HolyStorm.Tasks:RegisterTaskType("Achievement.Revoke",{name=L["TASK_REVOKE"],localizedNameKey="TASK_REVOKE",module="Achievements",priority=40,executionMode="MERGE_BY_KEY",conditions={"PLAYER_READY","GUILD_AVAILABLE"},execute=function(task)local ok,result=A:Revoke(task.metadata.awardID,task.metadata.reason);HolyStorm.Events:Emit("HS_ACHIEVEMENT_REVOKE_FINISHED",ok,result);return ok end})
 HolyStorm.Sync:RegisterDomain("achievements",{getMetadata=function(objectId)return HolyStorm.Data.AchievementStore:GetMetadata(objectId)end,listMetadata=function(since)return HolyStorm.Data.AchievementStore:ListMetadata(since)end,export=function(objectId)return HolyStorm.Data.AchievementStore:Export(objectId)end,validate=function(...)return A:ValidateSync(...)end,authorize=function(...)return A:AuthorizeSync(...)end,import=function(...)return A:Import(...)end,updateEvent="HS_ACHIEVEMENT_SYNC_UPDATED",priority=72})
 HolyStorm.RichLinks:RegisterType({type="achievement",validate=function(target)return validId(target)end,render=function(target,label)local definition=A:GetDefinition(target);return label or(definition and definition.name)or target end,onClick=function(target)return A:Open(target)end,tooltip=function(target)local definition=A:GetDefinition(target);if not definition or not A:IsVisible(definition)then return L["ACHIEVEMENT"],L["NOT_VISIBLE"]end;return definition.name,definition.description end,chatText=function(target)local definition=A:GetDefinition(target);return definition and definition.name or target end})
 local events={HS_EQUIPMENT_UPDATED="equipment",HS_MYTHICPLUS_UPDATED="mythicPlus",HS_RAIDLOCKS_UPDATED="raid",HS_DELVES_UPDATED="delves",HS_STATS_UPDATED="stats",HS_CHARACTER_UPDATED="identity",HS_ROSTER_UPDATED="roster",HS_TWINKS_UPDATED="twinks",HS_ACHIEVEMENT_AWARDS_UPDATED="achievements"};for event,dependency in pairs(events)do HolyStorm.Events:Register(event,"achievements-evaluation",function(_,guid)if event=="HS_ROSTER_UPDATED"then guid=UnitGUID("player")end;if guid==UnitGUID("player")then A:QueueEvaluation(guid,dependency)end end)end
 HolyStorm.Events:Register("PLAYER_ENTERING_WORLD","achievements-sync",function()if IsInGuild()then HolyStorm.Sync:Discover("achievements",nil,{reason="ACHIEVEMENT_LOGIN",priority=96})end end)
 HolyStorm.Events:Register("HS_GUILD_UPDATED","achievements-guild",function()A:RebuildIndex();if IsInGuild()then HolyStorm.Sync:Discover("achievements",nil,{reason="ACHIEVEMENT_GUILD_CHANGED",priority=96})end end)
end
HolyStorm.Achievements=A
