local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm")
local Notifications={version="1.0.0",types={},history={},maxHistory=50,sequence=0}
function Notifications:RegisterType(id,definition)if type(id)~="string"or type(definition)~="table"or type(definition.title)~="function"then return false,"INVALID_NOTIFICATION_TYPE"end;self.types[id]=definition;return true end
function Notifications:EnsureFrame()
 if self.frame then return self.frame end;local frame=CreateFrame("Button",nil,UIParent,"BackdropTemplate");frame:SetSize(360,82);frame:SetPoint("TOP",0,-120);frame:SetFrameStrata("DIALOG");frame:SetBackdrop({bgFile="Interface\\Buttons\\WHITE8x8",edgeFile="Interface\\Tooltips\\UI-Tooltip-Border",edgeSize=14,insets={left=3,right=3,top=3,bottom=3}});frame:SetBackdropColor(.025,.035,.05,.97);frame:SetBackdropBorderColor(1,.72,.12,1);frame.icon=frame:CreateTexture(nil,"ARTWORK");frame.icon:SetSize(52,52);frame.icon:SetPoint("LEFT",14,0);frame.title=frame:CreateFontString(nil,"OVERLAY","GameFontNormalLarge");frame.title:SetPoint("TOPLEFT",frame.icon,"TOPRIGHT",12,-8);frame.title:SetPoint("RIGHT",-12,0);frame.title:SetJustifyH("LEFT");frame.text=frame:CreateFontString(nil,"OVERLAY","GameFontHighlight");frame.text:SetPoint("TOPLEFT",frame.title,"BOTTOMLEFT",0,-7);frame.text:SetPoint("RIGHT",-12,0);frame.text:SetJustifyH("LEFT");frame:SetScript("OnClick",function()local entry=Notifications.current;local definition=entry and Notifications.types[entry.type];if definition and definition.onClick then definition.onClick(entry.payload)end;frame:Hide()end);frame:SetScript("OnEnter",function()if Notifications.hideTimer then Notifications.hideTimer:Cancel();Notifications.hideTimer=nil end end);frame:SetScript("OnLeave",function()Notifications:ScheduleHide()end);frame:Hide();self.frame=frame;return frame
end
function Notifications:ScheduleHide()if not(self.frame and self.frame:IsShown())or not C_Timer then return end;if self.hideTimer then self.hideTimer:Cancel()end;self.hideTimer=C_Timer.NewTimer(8,function()Notifications.frame:Hide();Notifications.hideTimer=nil end)end
function Notifications:Push(typeId,payload)
 local definition=self.types[typeId];if not definition then return false,"UNKNOWN_NOTIFICATION_TYPE"end;self.sequence=self.sequence+1;local entry={id=string.format("notification-%08x-%04x",HolyStorm.Utils.Now()%0xffffffff,self.sequence%0xffff),type=typeId,payload=HolyStorm.Utils.DeepCopy(payload),createdAt=HolyStorm.Utils.Now()};self.history[#self.history+1]=entry;while#self.history>self.maxHistory do table.remove(self.history,1)end;self.current=entry;local frame=self:EnsureFrame();frame.icon:SetTexture(definition.icon and definition.icon(payload)or"Interface\\Icons\\INV_Misc_QuestionMark");frame.title:SetText(definition.title(payload));frame.text:SetText(definition.text and definition.text(payload)or"");frame:Show();self:ScheduleHide();if definition.sound then definition.sound(payload)end;HolyStorm.Events:Emit("HS_NOTIFICATION_SHOWN",typeId,entry);return true,entry
end
function Notifications:GetHistory()return HolyStorm.Utils.DeepCopy(self.history)end
function Notifications:Initialize()return true end
HolyStorm.Notifications=Notifications
