local addonVersion="1.0.3"
local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm")
local L=LibStub("AceLocale-3.0"):GetLocale("Holy_Storm")
local POI={version=addonVersion,categories={},icons={},targets={PERSONAL=true,GUILD=true,GROUP=true,RAID=true},statuses={ACTIVE=true,DELETED=true},sequence=0,maxEntries=1000,maxName=120,maxDescription=4000,maxCustomCategory=80,currentContext=nil,lastResync=nil}
local function copy(v)return HolyStorm.Utils.DeepCopy(v)end
local function now()return HolyStorm.Utils.Now()end
local function finite(v)v=tonumber(v);return v and v==v and v~=math.huge and v~=-math.huge end
local function validId(v)return type(v)=="string"and#v>0 and#v<=160 and v:match("^[%w%-_]+$")~=nil end
local function account(guid)return HolyStorm.TwinkCore and HolyStorm.TwinkCore:GetAccountUUIDForCharacter(guid)or HolyStorm.Data.PlayerStore:GetCharacterOwner(guid)end
local function permission(target,action,own)if action=="create"then return"poi-create-"..string.lower(target)end;return"poi-"..action.."-"..(own and"own"or"any")end
local function log(level,message,context)HolyStorm.Logger:Write(level,"POI","state",message,context)end

function POI:RegisterCategory(id,definition)if not validId(id)or type(definition)~="table"then return false end;self.categories[id]=copy(definition);self.categories[id].id=id;return true end
function POI:RegisterIcon(id,definition)if not validId(id)or type(definition)~="table"or(type(definition.texture)~="string"and type(definition.texture)~="number")then return false end;self.icons[id]=copy(definition);self.icons[id].id=id;return true end
function POI:GetCategories()local out={};for _,value in pairs(self.categories)do out[#out+1]=copy(value)end;table.sort(out,function(a,b)return tostring(a.nameKey or a.id)<tostring(b.nameKey or b.id)end);return out end
function POI:GetIcons()local out={};for _,value in pairs(self.icons)do out[#out+1]=copy(value)end;table.sort(out,function(a,b)return tostring(a.id)<tostring(b.id)end);return out end
function POI:GetSettings()HolyStorm.db.profile.poi=HolyStorm.Utils.ApplyDefaults(HolyStorm.db.profile.poi,{worldMapEnabled=true,minimapEnabled=true,worldMapSize=22,minimapSize=18,maxSynced=500,hidden={},categoryVisible={},targetVisible={}});return HolyStorm.db.profile.poi end
function POI:SetSetting(key,value)local settings=self:GetSettings();if key=="worldMapSize"then value=math.max(12,math.min(48,tonumber(value)or 22))elseif key=="minimapSize"then value=math.max(10,math.min(36,tonumber(value)or 18))elseif key=="maxSynced"then value=math.max(50,math.min(1000,math.floor(tonumber(value)or 500)))elseif key=="worldMapEnabled"or key=="minimapEnabled"then value=value==true else return false end;settings[key]=value;self:Refresh("SETTING");return true end
function POI:SetCategoryVisible(id,visible)self:GetSettings().categoryVisible[id]=visible~=false;HolyStorm.Events:Emit("HS_POI_FILTER_CHANGED","category",id,visible~=false);self:Refresh("CATEGORY_FILTER");return true end
function POI:SetTargetVisible(id,visible)if not self.targets[id]then return false end;self:GetSettings().targetVisible[id]=visible~=false;HolyStorm.Events:Emit("HS_POI_FILTER_CHANGED","target",id,visible~=false);self:Refresh("TARGET_FILTER");return true end
function POI:IsModuleEnabled(target)return target=="PERSONAL"or not HolyStorm.Policy or HolyStorm.Policy:IsGuildModuleEnabled("poi")end
function POI:IsMapValid(mapID)mapID=tonumber(mapID);if not mapID or mapID<1 or mapID%1~=0 then return false end;if C_Map and C_Map.GetMapInfo then local ok,info=pcall(C_Map.GetMapInfo,mapID);return ok and info~=nil end;return true end
function POI:GetCurrentContext()
 local inRaid=IsInRaid and IsInRaid();local inGroup=IsInGroup and IsInGroup();if not inRaid and not inGroup then return nil end;local target=inRaid and"RAID"or"GROUP";local leader=UnitGUID("player")or"unknown";local count=inRaid and(GetNumGroupMembers and GetNumGroupMembers()or 0)or(GetNumSubgroupMembers and GetNumSubgroupMembers()or 0);for index=1,count do local unit=inRaid and("raid"..index)or("party"..index);if UnitExists and UnitExists(unit)and UnitIsGroupLeader and UnitIsGroupLeader(unit)then leader=UnitGUID(unit)or leader break end end;if UnitIsGroupLeader and UnitIsGroupLeader("player")then leader=UnitGUID("player")or leader end;local instanceID=0;if GetInstanceInfo then local currentInstanceID=select(8,GetInstanceInfo());instanceID=tonumber(currentInstanceID)or 0 end;return{target=target,leaderGuid=leader,instanceID=instanceID,sessionId=string.format("%s-%s-%d",string.lower(target),tostring(leader):gsub("[^%w%-_]",""),instanceID)}
end
function POI:NewId()self.sequence=self.sequence+1;return string.format("poi-%08x-%04x-%04x-%s",now()%0xffffffff,self.sequence%0xffff,math.random(0,0xffff),tostring(HolyStorm.db.global.installId or"local"):gsub("[^%w]",""):sub(-12))end
function POI:Normalize(input,current)
 local result=copy(input or{});result.poiID=result.poiID or self:NewId();result.target=string.upper(tostring(result.target or(current and current.target)or"PERSONAL"));result.mapID=tonumber(result.mapID);result.x=tonumber(result.x);result.y=tonumber(result.y);result.name=HolyStorm.Utils.Trim(result.name or"");result.description=tostring(result.description or"");result.category=tostring(result.category or"note"):lower();result.customCategory=HolyStorm.Utils.Trim(result.customCategory or"");result.icon=self.icons[result.icon]and result.icon or"marker";result.color=type(result.color)=="table"and result.color or{r=1,g=.82,b=0,a=1};result.status=string.upper(tostring(result.status or"ACTIVE"));result.expiresAt=tonumber(result.expiresAt);result.lifetime=tonumber(result.lifetime);if result.lifetime and result.lifetime>0 and not result.expiresAt then result.expiresAt=now()+result.lifetime end;if result.target=="GUILD"then result.guildId=result.guildId or HolyStorm.Data.POIStore:GetGuildId();result.sessionId=nil elseif result.target=="GROUP"or result.target=="RAID"then local context=self:GetCurrentContext();result.sessionId=result.sessionId or(context and context.target==result.target and context.sessionId);result.guildId=nil else result.guildId,result.sessionId=nil,nil end;return result
end
function POI:Validate(entry)
 if type(entry)=="table"and(not self:IsMapValid(entry.mapID)or not finite(entry.x)or not finite(entry.y)or entry.x<0 or entry.x>1 or entry.y<0 or entry.y>1)then log("WARN","Invalid POI map position",{poiID=entry.poiID,mapID=entry.mapID,x=entry.x,y=entry.y});return false,"INVALID_POSITION"end
 if type(entry)~="table"or not validId(entry.poiID)or not self.targets[entry.target]or not self.statuses[entry.status]then return false,"INVALID_POI"end;if not self:IsMapValid(entry.mapID)or not finite(entry.x)or not finite(entry.y)or entry.x<0 or entry.x>1 or entry.y<0 or entry.y>1 then return false,"INVALID_POSITION"end;if type(entry.name)~="string"or#entry.name==0 or#entry.name>self.maxName or type(entry.description)~="string"or#entry.description>self.maxDescription or type(entry.customCategory)~="string"or#entry.customCategory>self.maxCustomCategory then return false,"INVALID_TEXT"end;if not self.categories[entry.category]and entry.category~="custom"then return false,"INVALID_CATEGORY"end;if entry.category=="custom"and entry.customCategory==""then return false,"INVALID_CATEGORY"end;if not self.icons[entry.icon]then return false,"INVALID_ICON"end;local c=entry.color;if type(c)~="table"or not finite(c.r)or not finite(c.g)or not finite(c.b)or not finite(c.a)or c.r<0 or c.r>1 or c.g<0 or c.g>1 or c.b<0 or c.b>1 or c.a<0 or c.a>1 then return false,"INVALID_COLOR"end;if entry.expiresAt and(not finite(entry.expiresAt)or entry.expiresAt<0)then return false,"INVALID_EXPIRATION"end;if entry.revision~=nil and(not finite(entry.revision)or entry.revision<1 or entry.revision%1~=0 or type(entry.creatorGuid)~="string"or entry.creatorGuid==""or not finite(entry.createdAt)or entry.createdAt<0 or not finite(entry.updatedAt)or entry.updatedAt<entry.createdAt)then return false,"INVALID_METADATA"end;if entry.target=="GUILD"and(type(entry.guildId)~="string"or entry.guildId=="")then return false,"INVALID_GUILD"end;if(entry.target=="GROUP"or entry.target=="RAID")and not validId(entry.sessionId)then return false,"INVALID_SESSION"end;return true
end
function POI:NormalizeIncoming(entry)
 if type(entry)~="table"then return entry end;if type(entry.icon)=="string"and not self.icons[entry.icon]then entry.icon="marker"end;if type(entry.category)=="string"and not self.categories[entry.category]then local fallback=HolyStorm.Utils.Trim(entry.customCategory~=""and entry.customCategory or entry.category);entry.category="custom";entry.customCategory=fallback:sub(1,self.maxCustomCategory);if entry.customCategory==""then entry.customCategory="Unknown"end end;return entry
end
function POI:IsExpired(entry)return entry.expiresAt and entry.expiresAt<=now()end
function POI:CanView(entry,ignoreLocal)
 if not entry or entry.status~="ACTIVE"or self:IsExpired(entry)or not self:IsModuleEnabled(entry.target)then return false end;if entry.target~="PERSONAL"and not HolyStorm.Policy:Can("poi-view",account(UnitGUID("player")),UnitGUID("player"),entry)then return false end;if entry.target=="GUILD"and entry.guildId~=HolyStorm.Data.POIStore:GetGuildId()then return false end;if entry.target=="GROUP"or entry.target=="RAID"then local context=self:GetCurrentContext();if not context or context.target~=entry.target or context.sessionId~=entry.sessionId then return false end end;if not ignoreLocal then local settings=self:GetSettings();if settings.hidden[entry.poiID]or settings.categoryVisible[entry.category]==false or settings.targetVisible[entry.target]==false then return false end end;return true
end
function POI:Get(id)return HolyStorm.Data.POIStore:Get(id)end
function POI:GetVisible(options)
 options=options or{};local out={};local q=string.lower(HolyStorm.Utils.Trim(options.search or""));for _,entry in ipairs(HolyStorm.Data.POIStore:GetAll())do local visible=options.includeHidden and self:CanView(entry,true)or self:CanView(entry);local hidden=self:GetSettings().hidden[entry.poiID]==true;local mode=not options.mode or options.mode=="ALL"or options.mode=="OWN"and entry.creatorGuid==UnitGUID("player")or options.mode=="SYNCED"and entry.target~="PERSONAL"or options.mode=="HIDDEN"and hidden;if visible and mode and(options.mode~="HIDDEN"or hidden)then local haystack=string.lower(table.concat({entry.name,entry.description,entry.creatorName or"",entry.customCategory or""}," "));if q==""or haystack:find(q,1,true)then out[#out+1]=entry end end end;local field=options.sort or"name";table.sort(out,function(a,b)local av,bv=a[field],b[field];if av==bv then return a.poiID<b.poiID end;if av==nil then return false elseif bv==nil then return true end;return options.desc and av>bv or av<bv end);return out
end
function POI:CountSynced()
 local count=0;for _,entry in ipairs(HolyStorm.Data.POIStore:GetAll())do if entry.target~="PERSONAL"and entry.status=="ACTIVE"then count=count+1 end end;return count
end
function POI:CanMutate(entry,action,actorGuid)
 actorGuid=actorGuid or UnitGUID("player");local own=not entry or entry.creatorGuid==actorGuid;return HolyStorm.Policy:Can(permission(entry and entry.target or"PERSONAL",action,own),account(actorGuid),actorGuid,entry)
end
function POI:Save(input,expectedRevision)
 local current=input.poiID and self:Get(input.poiID);local candidate=self:Normalize(input,current);if not self:IsModuleEnabled(candidate.target)then return false,"MODULE_DISABLED"end;if current and tonumber(expectedRevision)~=tonumber(current.revision)then return false,"CONFLICT",current.revision elseif not current and expectedRevision~=nil and tonumber(expectedRevision)~=0 then return false,"CONFLICT",0 end;if not self:CanMutate(current or candidate,current and"edit"or"create")then log("WARN","POI permission rejected",{poiID=candidate.poiID});return false,"PERMISSION_DENIED"end;if current and candidate.target~=current.target and not self:CanMutate(candidate,"create")then return false,"PERMISSION_DENIED"end;local valid,reason=self:Validate(candidate);if not valid then return false,reason end;if not current and#HolyStorm.Data.POIStore:GetAll()>=self.maxEntries then return false,"POI_LIMIT"end;local actor=UnitGUID("player");candidate.creatorGuid=current and current.creatorGuid or candidate.creatorGuid or actor;candidate.creatorAccountUUID=current and current.creatorAccountUUID or candidate.creatorAccountUUID or account(actor);candidate.creatorName=current and current.creatorName or candidate.creatorName or GetUnitName("player",true);candidate.createdAt=current and current.createdAt or candidate.createdAt or now();candidate.modifiedBy=actor;candidate.updatedAt=now();candidate.revision=(current and current.revision or 0)+1;candidate.source="local";if current and(current.target~=candidate.target or current.sessionId~=candidate.sessionId or current.guildId~=candidate.guildId)then HolyStorm.Data.POIStore:Remove(current)end;HolyStorm.Data.POIStore:Put(candidate);if candidate.target~="PERSONAL"then HolyStorm.Sync:Publish("poi",candidate.poiID,current and"POI_UPDATED"or"POI_CREATED")end;HolyStorm.Events:Emit(current and"HS_POI_UPDATED"or"HS_POI_CREATED",candidate.poiID,candidate.target);log("INFO",current and"POI updated"or"POI created",{poiID=candidate.poiID,target=candidate.target});self:ScheduleExpiration();self:Refresh("SAVE");return true,candidate
end
function POI:Delete(id,expectedRevision)
 local entry=self:Get(id);if not entry then return false,"NOT_FOUND"end;if tonumber(expectedRevision)~=tonumber(entry.revision)then return false,"CONFLICT",entry.revision end;if not self:CanMutate(entry,"delete")then return false,"PERMISSION_DENIED"end;if entry.target=="PERSONAL"then HolyStorm.Data.POIStore:Remove(entry);self:GetSettings().hidden[id]=nil else entry=copy(entry);entry.status="DELETED";entry.deletedAt=now();entry.deletedBy=UnitGUID("player");entry.updatedAt=now();entry.modifiedBy=entry.deletedBy;entry.revision=entry.revision+1;HolyStorm.Data.POIStore:Put(entry);HolyStorm.Sync:Publish("poi",id,"POI_DELETED")end;HolyStorm.Events:Emit("HS_POI_DELETED",id,entry.target);log("INFO","POI deleted",{poiID=id,target=entry.target});self:Refresh("DELETE");return true,entry
end
function POI:SetHidden(id,hidden)local entry=self:Get(id);if not entry then return false end;self:GetSettings().hidden[id]=hidden==true or nil;HolyStorm.Events:Emit("HS_POI_VISIBILITY_CHANGED",id,hidden==true);self:Refresh("LOCAL_HIDE");return true end
function POI:GetCategoryName(entry)local category=self.categories[entry.category];return entry.category=="custom"and entry.customCategory or category and(category.nameKey and L[category.nameKey]or category.name)or entry.customCategory~=""and entry.customCategory or entry.category end
function POI:GetIcon(entry)return self.icons[entry.icon]or self.icons.marker end
function POI:GetRemaining(entry)if not entry.expiresAt then return nil end;return math.max(0,entry.expiresAt-now())end
function POI:GetTooltip(entry)return entry.name,entry.description,{category=self:GetCategoryName(entry),creator=entry.creatorName,remaining=self:GetRemaining(entry),target=entry.target}end
function POI:Open(id)local entry=self:Get(id);if not entry then HolyStorm.Sync:RequestObject("poi",id,{reason="POI_LINK_OPEN"});return false,"LOADING"end;if not self:CanView(entry)then return false,"UNAVAILABLE"end;HolyStorm:CallCapability("poi.open",id);return HolyStorm.MapLinks:OpenCoordinate(entry.mapID,entry.x,entry.y,entry.name)end
function POI:Share(id)local entry=self:Get(id);if not self:CanView(entry)or entry.target=="PERSONAL"then return false,"UNAVAILABLE"end;return HolyStorm.RichLinks:InsertChatLink("poi",id,string.format(L["POI_LINK_LABEL"],entry.name))end
function POI:SetTemporaryMarker(mapID,x,y,options)local ok,marker=HolyStorm.MapLinks:SetTemporaryMarker(mapID,x,y,options);if ok then self:Refresh("TEMPORARY_MARKER")end;return ok,marker end
function POI:ClearTemporaryMarker()local removed=HolyStorm.MapLinks:ClearTemporaryMarker();if removed then self:Refresh("TEMPORARY_MARKER_CLEAR")end;return removed end
function POI:Refresh(reason)HolyStorm.Tasks:Queue("POI.MapRefresh",{mergeKey="all",debounce=.1,priority=88,triggerSource=reason or"POI_CHANGED"})end
function POI:ScheduleExpiration()local nextAt;for _,entry in ipairs(HolyStorm.Data.POIStore:GetAll())do if entry.status=="ACTIVE"and entry.expiresAt and entry.expiresAt>now()then nextAt=nextAt and math.min(nextAt,entry.expiresAt)or entry.expiresAt end end;if nextAt then HolyStorm.Tasks:Queue("POI.Expire",{mergeKey="expiration",delay=math.max(0,nextAt-now()),priority=90,triggerSource="EXPIRATION_SCHEDULE"})end end
function POI:CleanupExpired()
 local changed=0;for _,entry in ipairs(HolyStorm.Data.POIStore:GetAll())do if entry.status=="ACTIVE"and self:IsExpired(entry)then if entry.target=="PERSONAL"or entry.target=="GROUP"or entry.target=="RAID"then HolyStorm.Data.POIStore:Remove(entry)elseif entry.creatorGuid==UnitGUID("player")or self:CanMutate(entry,"delete")then self:Delete(entry.poiID,entry.revision)end;changed=changed+1;HolyStorm.Events:Emit("HS_POI_EXPIRED",entry.poiID,entry.target);log("INFO","POI expired",{poiID=entry.poiID})end end;if changed>0 then self:Refresh("EXPIRED")end;self:ScheduleExpiration();return true
end
function POI:HandleGroupContext()
 local previous=self.currentContext;local current=self:GetCurrentContext();local changed=not previous and current or previous and(not current or previous.sessionId~=current.sessionId or previous.target~=current.target);if previous and changed then local removed=HolyStorm.Data.POIStore:RemoveSession(previous.sessionId);if removed>0 then HolyStorm.Events:Emit("HS_POI_SESSION_CLEARED",previous.sessionId,removed);self:Refresh("SESSION_LEFT")end end;self.currentContext=current;if current then HolyStorm.Data.POIStore:RemoveOtherSessions(current.sessionId);if changed then self.lastResync=now();HolyStorm.Sync:Discover("poi",nil,{channel=current.target=="RAID"and"RAID"or"PARTY",scope=current.target,sessionId=current.sessionId,reason="POI_SESSION_RESYNC",priority=86,delay=.3+math.random()*1.5})end end
end
function POI:GetDiagnostics()
 local pending,queued={},0;for _,request in pairs(HolyStorm.Sync.requests or{})do if request.domain=="poi"and request.objectId then pending[request.objectId]=true end end;if HolyStorm.Tasks.GetLiveTasks then for _,task in ipairs(HolyStorm.Tasks:GetLiveTasks())do if task.module=="POI"or task.metadata and task.metadata.domain=="poi"then queued=queued+1 end end end;local rows={};for _,entry in ipairs(HolyStorm.Data.POIStore:GetAll())do local map=HolyStorm.POIMap and HolyStorm.POIMap:GetRenderState(entry.poiID)or{};rows[#rows+1]={poiID=entry.poiID,target=entry.target,mapID=entry.mapID,x=entry.x,y=entry.y,creator=entry.creatorGuid,revision=entry.revision,source=entry.source,receivedFrom=entry.receivedFrom,expiresAt=entry.expiresAt,sessionId=entry.sessionId,visible=self:CanView(entry),hidden=self:GetSettings().hidden[entry.poiID]==true,worldPin=map.worldPin==true,minimapPin=map.minimapPin==true,viewedMapID=map.viewedMapID,transform=map.transform,transformedX=map.transformedX,transformedY=map.transformedY,lastReceived=entry.syncedAt,pendingFetch=pending[entry.poiID]==true}end;return{entries=rows,context=copy(self.currentContext),lastResync=self.lastResync,pendingCount=HolyStorm.Utils.TableCount(pending),queuedTasks=queued,suppressionRequests=HolyStorm.Utils.TableCount(HolyStorm.Sync.heard or{})}
end
function POI:Initialize()
 HolyStorm.Data.POIStore:Initialize();self:RegisterCategory("quest",{nameKey="POI_CATEGORY_QUEST"});self:RegisterCategory("achievement",{nameKey="POI_CATEGORY_ACHIEVEMENT"});self:RegisterCategory("raid-entrance",{nameKey="POI_CATEGORY_RAID_ENTRANCE"});self:RegisterCategory("note",{nameKey="POI_CATEGORY_NOTE"});self:RegisterCategory("custom",{nameKey="POI_CATEGORY_CUSTOM"})
 local icons={marker="Interface\\Icons\\INV_Misc_Map_01",circle="Interface\\TargetingFrame\\UI-RaidTargetingIcon_2",dot="Interface\\TargetingFrame\\UI-RaidTargetingIcon_2",star="Interface\\TargetingFrame\\UI-RaidTargetingIcon_1",skull="Interface\\TargetingFrame\\UI-RaidTargetingIcon_8",diamond="Interface\\TargetingFrame\\UI-RaidTargetingIcon_3",triangle="Interface\\TargetingFrame\\UI-RaidTargetingIcon_4",moon="Interface\\TargetingFrame\\UI-RaidTargetingIcon_5",square="Interface\\TargetingFrame\\UI-RaidTargetingIcon_6",cross="Interface\\TargetingFrame\\UI-RaidTargetingIcon_7",exclamation="Interface\\GossipFrame\\AvailableQuestIcon",quest="Interface\\GossipFrame\\AvailableQuestIcon",question="Interface\\GossipFrame\\ActiveQuestIcon",treasure="Interface\\Icons\\INV_Misc_Coin_01",portal="Interface\\Icons\\Spell_Arcane_TeleportStormWind",flag="Interface\\Icons\\INV_BannerPVP_02",note="Interface\\Icons\\INV_Misc_Note_01"};for id,texture in pairs(icons)do self:RegisterIcon(id,{texture=texture,nameKey="POI_ICON_"..string.upper(id)})end
 HolyStorm.Tasks:RegisterTaskType("POI.Expire",{name=L["TASK_POI_EXPIRE"],localizedNameKey="TASK_POI_EXPIRE",module="POI",priority=90,executionMode="MERGE_BY_KEY",execute=function()return POI:CleanupExpired()end});HolyStorm.Tasks:RegisterTaskType("POI.MapRefresh",{name=L["TASK_POI_MAP_REFRESH"],localizedNameKey="TASK_POI_MAP_REFRESH",module="POI",priority=88,executionMode="MERGE_BY_KEY",execute=function()if HolyStorm.POIMap then HolyStorm.POIMap:Refresh()end;return true end})
 HolyStorm.Sync:RegisterDomain("poi",{getChannel=function(meta)return meta and(meta.target=="RAID"and"RAID"or meta.target=="GROUP"and"PARTY"or"GUILD")or"GUILD"end,getMetadata=function(id)local entry=POI:Get(id);if not entry or entry.target=="PERSONAL"or entry.status=="DELETED"and not entry.modifiedBy or entry.status=="ACTIVE"and POI:IsExpired(entry)then return nil end;return{objectId=id,owner=entry.modifiedBy or entry.creatorGuid,version=entry.revision,updatedAt=entry.updatedAt,target=entry.target,sessionId=entry.sessionId}end,listMetadata=function(since,request)local out={};for _,entry in ipairs(HolyStorm.Data.POIStore:GetAll())do if entry.target~="PERSONAL"and(entry.status=="DELETED"or not POI:IsExpired(entry))and(entry.updatedAt or 0)>since and(not request or not request.scope or entry.target==request.scope)and(not entry.sessionId or not request or not request.sessionId or entry.sessionId==request.sessionId)then out[#out+1]={objectId=entry.poiID,owner=entry.modifiedBy or entry.creatorGuid,version=entry.revision,updatedAt=entry.updatedAt,target=entry.target,sessionId=entry.sessionId}end end;return out end,export=function(id)return copy(POI:Get(id))end,validate=function(entry,meta,id)entry=POI:NormalizeIncoming(entry);local valid,reason=POI:Validate(entry);if not valid then log("WARN","Rejected incoming POI",{poiID=id,reason=reason})end;return valid and entry.poiID==id and entry.target~="PERSONAL"and meta.owner==(entry.modifiedBy or entry.creatorGuid)and(entry.target~="GUILD"or entry.guildId==HolyStorm.Data.POIStore:GetGuildId())and(entry.target=="GUILD"or POI:GetCurrentContext()and entry.sessionId==POI:GetCurrentContext().sessionId)end,authorize=function(entry,meta)local current=POI:Get(entry.poiID);local own=(current and current.creatorGuid or entry.creatorGuid)==meta.owner;local action=entry.status=="DELETED"and"delete"or current and"edit"or"create";return HolyStorm.Policy:Can(permission(entry.target,action,own),account(meta.owner),meta.owner,entry)end,import=function(id,entry,meta,_,sender)local current=POI:Get(id);if current and tonumber(current.revision)>=tonumber(entry.revision)then return false end;if not current and entry.status=="ACTIVE"and POI:CountSynced()>=POI:GetSettings().maxSynced then log("WARN","POI receive limit reached",{poiID=id});return false end;entry=copy(entry);entry.source="sync";entry.receivedFrom=sender;entry.syncedAt=now();HolyStorm.Data.POIStore:Put(entry);HolyStorm.Events:Emit(entry.status=="DELETED"and"HS_POI_DELETED"or current and"HS_POI_UPDATED"or"HS_POI_SYNCED",id,entry.target);POI:ScheduleExpiration();POI:Refresh("SYNC");return true end,updateEvent="HS_POI_SYNCED"})
 if HolyStorm.Rules then local fields={target=function(p)return p.target end,category=function(p)return p.category end,creator=function(p)return p.creatorGuid end,mapID=function(p)return p.mapID end,temporary=function(p)return p.temporary==true end};for id,getter in pairs(fields)do HolyStorm.Rules:RegisterField("poi."..id,{type=id=="mapID"and"number"or id=="temporary"and"boolean"or"string",get=function(context)local poi=context.target and context.target.poi;return poi and getter(poi)end})end end
 HolyStorm.MapLinks:RegisterPOIProvider("holy-storm-poi",{get=function(id)local entry=POI:Get(id);return POI:CanView(entry)and entry or nil end,list=function()return POI:GetVisible()end,open=function(id)return POI:Open(id)end})
 HolyStorm.Events:Register("GROUP_ROSTER_UPDATE","poi-context",function()HolyStorm.Tasks:Enqueue("poi.context",function()POI:HandleGroupContext();return true end,{priority=84,debounce=.5,cooldown=2})end);HolyStorm.Events:Register("PLAYER_ENTERING_WORLD","poi-world",function()POI:CleanupExpired();POI:HandleGroupContext();if POI:IsModuleEnabled("GUILD")then HolyStorm.Sync:Discover("poi",nil,{channel="GUILD",scope="GUILD",reason="POI_LOGIN",priority=94})end end);self.currentContext=nil;self:CleanupExpired()
end
HolyStorm.POI=POI
