local addonVersion="1.1.0"
local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm")
local L=LibStub("AceLocale-3.0"):GetLocale("Holy_Storm_Logs")
local Logs=HolyStorm:RegisterRequiredModule("Logs")
HolyStorm:ApplyModuleMetadata(Logs,{displayName=L["TITLE"],internalName="logs",version=addonVersion,category="required",description=L["DESCRIPTION"],permissions={"logs-view"},dependencies={"core","ui"},enabledByDefault=true})

local FILTER_KEYS={level=true,module=true,category=true,direction=true,event=true,search=true}
local SEARCH_CONTEXT={"from","to","domain","objectId","messageKind","transmissionId","event","eventName"}
local EXPORT_CONTEXT={"direction","from","to","channel","domain","objectId","transmissionId","packetPart","packetTotal","bytes","messageKind","version","reason","requestId","event","eventName","taskId","workflowId","triggerSource"}
local LEVEL_COLORS={DEBUG={.58,.68,.78},INFO={.82,.92,1},WARN={1,.72,.2},ERROR={1,.28,.28}}
local CATEGORY_COLORS={event={.45,.78,1},task={.66,.74,.86},workflow={.75,.58,1},sync={.35,.82,.86},payload={.35,.88,.64},send={.38,.82,1},receive={.5,.9,.72},comms={.45,.8,1},database={.82,.68,.4},permission={1,.72,.3},ui={.82,.65,1}}
local OMIT_CONTEXT={payload=true,data=true,database=true,equipment=true,serialized=true,message=true,packet=true,envelope=true}

local function lower(value)return string.lower(tostring(value or""))end
local function context(entry)return type(entry.context)=="table"and entry.context or{}end
local function field(entry,name)local c=context(entry);if name=="direction"then return entry.direction or c.direction elseif name=="event"then return entry.eventName or c.eventName or c.event end;return c[name]end
local function direction(entry)return string.upper(tostring(field(entry,"direction")or""))end
local function eventName(entry)return tostring(field(entry,"event")or"")end
local function transmission(entry)return tostring(entry.transmissionId or field(entry,"transmissionId")or"")end
local function correlation(entry)return tostring(entry.correlationId or field(entry,"correlationId")or"")end
local DESTINATION_KEYS={GUILD=true,RAID=true,PARTY=true,INSTANCE=true,BROADCAST=true}
local function destination(value)local key=string.upper(tostring(value or""));return DESTINATION_KEYS[key]and L[key]or value end
local function route(entry)local c=context(entry);local from=c.from;local to=destination(c.to);if from and to then return tostring(from).." → "..tostring(to)end;return tostring(from or to or"")end
local function progress(entry)local c=context(entry);local part,total=tonumber(c.packetPart),tonumber(c.packetTotal);return part and total and string.format("%d / %d",part,total)or""end
local function safeContext(source)local out={};source=type(source)=="table"and source or{};for _,key in ipairs(EXPORT_CONTEXT)do local value=source[key];if type(value)=="string"or type(value)=="number"or type(value)=="boolean"then out[key]=value end end;return out end
local function flattenContext(source,prefix,out,depth)out=out or{};depth=depth or 0;if type(source)~="table"or depth>3 or#out>=100 then return out end;local keys={};for key in pairs(source)do if type(key)=="string"and not OMIT_CONTEXT[key]then keys[#keys+1]=key end end;table.sort(keys);for _,key in ipairs(keys)do if#out>=100 then break end;local value=source[key];local path=prefix and(prefix.."."..key)or key;if type(value)=="string"or type(value)=="number"or type(value)=="boolean"then out[#out+1]={path,tostring(value)}elseif type(value)=="table"then flattenContext(value,path,out,depth+1)end end;return out end
local function exportEntry(entry)local c=safeContext(context(entry));return{timestamp=tonumber(entry.timestamp),level=tostring(entry.level or""),source=tostring(entry.source or""),category=tostring(entry.category or""),message=tostring(entry.message or""),direction=direction(entry),from=c.from,to=c.to,channel=c.channel,domain=c.domain,objectId=c.objectId,transmissionId=transmission(entry),packetPart=c.packetPart,packetTotal=c.packetTotal,bytes=c.bytes,messageKind=c.messageKind,version=c.version,eventName=eventName(entry),correlationId=correlation(entry),context=c}end
local function json(value)
 if value==nil then return"null"elseif type(value)=="boolean"or type(value)=="number"then return tostring(value)elseif type(value)=="string"then return'"'..value:gsub('\\','\\\\'):gsub('"','\\"'):gsub('\n','\\n'):gsub('\r','\\r')..'"'elseif type(value)~="table"then return"null"end
 local array,count=true,0;for key in pairs(value)do count=count+1;if type(key)~="number"then array=false end end;local out={};if array then for index=1,count do out[#out+1]=json(value[index])end;return"["..table.concat(out,",").."]"end;for key,child in pairs(value)do out[#out+1]=json(tostring(key))..":"..json(child)end;table.sort(out);return"{"..table.concat(out,",").."}"
end
local function csv(value)return'"'..tostring(value or""):gsub('"','""')..'"'end

function Logs:GetSettings()
 HolyStorm.db.profile.logs=type(HolyStorm.db.profile.logs)=="table"and HolyStorm.db.profile.logs or{};local settings=HolyStorm.db.profile.logs;settings.autoScroll=settings.autoScroll~=false;for key in pairs(FILTER_KEYS)do if key~="search"and type(settings[key])~="string"then settings[key]="ALL"end end;settings.search=type(settings.search)=="string"and settings.search or"";return settings
end
function Logs:LoadSettings()local settings=self:GetSettings();self.filters={level=settings.level or"ALL",module=settings.module or"ALL",category=settings.category or"ALL",direction=settings.direction or"ALL",event=settings.event or"ALL",search=settings.search or""};self.autoScroll=settings.autoScroll~=false;return self.filters end
function Logs:SetFilter(name,value,skipRender)if not FILTER_KEYS[name]then return false end;self.filters=self.filters or self:LoadSettings();value=name=="search"and tostring(value or"")or tostring(value or"ALL");self.filters[name]=value;self:GetSettings()[name]=value;if self.filterMenus and self.filterMenus[name]then self:UpdateMenuText(name)end;if not skipRender then self:Render()end;return true end
function Logs:ResetFilters(skipRender)self.filters=self.filters or{};for key in pairs(FILTER_KEYS)do self:SetFilter(key,key=="search"and""or"ALL",true)end;if self.searchBox then self.searchBox:SetText("")end;if not skipRender then self:Render()end end
function Logs:SetQuickFilter(kind)self:ResetFilters(true);if kind=="ERROR"or kind=="WARN"then self:SetFilter("level",kind,true)elseif kind=="EVENT"or kind=="TASK"or kind=="WORKFLOW"then self:SetFilter("category",string.lower(kind),true)elseif kind=="SYNC"or kind=="COMMS"then self:SetFilter("module",kind=="SYNC"and"Sync"or"Comms",true)end;self:Render()end
function Logs:GetOptions(kind)local seen,out={},{};for _,entry in ipairs(HolyStorm.Logger:GetHistory())do local value;if kind=="level"then value=entry.level elseif kind=="module"then value=entry.source elseif kind=="category"then value=entry.category elseif kind=="direction"then value=direction(entry)elseif kind=="event"then value=eventName(entry)end;if value and value~=""and not seen[value]then seen[value]=true;out[#out+1]=value end end;table.sort(out,function(a,b)return lower(a)<lower(b)end);return out end
function Logs:EnsureValidFilters()self.filters=self.filters or self:LoadSettings();for _,kind in ipairs({"level","module","category","direction","event"})do local selected=self.filters[kind];if selected and selected~="ALL"then local found=false;for _,value in ipairs(self:GetOptions(kind))do if lower(value)==lower(selected)then found=true;break end end;if not found then self:SetFilter(kind,"ALL",true)end end end end
function Logs:Matches(entry)
 local filters=self.filters or self:LoadSettings();if filters.level~="ALL"and lower(entry.level)~=lower(filters.level)then return false end;if filters.module~="ALL"and lower(entry.source)~=lower(filters.module)then return false end;if filters.category~="ALL"and lower(entry.category)~=lower(filters.category)then return false end;if filters.direction~="ALL"and lower(direction(entry))~=lower(filters.direction)then return false end;if filters.event~="ALL"and lower(eventName(entry))~=lower(filters.event)then return false end
 local query=lower(filters.search);if query~=""then local values={entry.message,entry.source,entry.category,entry.correlationId,entry.transmissionId};local c=context(entry);for _,name in ipairs(SEARCH_CONTEXT)do values[#values+1]=c[name]end;local found=false;for _,value in ipairs(values)do if lower(value):find(query,1,true)then found=true;break end end;if not found then return false end end;return true
end
function Logs:GetFiltered()local out={};for _,entry in ipairs(HolyStorm.Logger:GetHistory())do if self:Matches(entry)then out[#out+1]=entry end end;return out end

function Logs:Export(format,all)
 local entries=all and HolyStorm.Logger:GetHistory()or self:GetFiltered();local projected={};for _,entry in ipairs(entries)do projected[#projected+1]=exportEntry(entry)end;if format=="json"then return json(projected)end
 local lines={};if format=="csv"then lines[1]="timestamp,level,module,category,direction,from,to,channel,domain,objectId,transmissionId,packetPart,packetTotal,bytes,messageKind,version,eventName,correlationId,message";for _,entry in ipairs(projected)do lines[#lines+1]=table.concat({csv(entry.timestamp),csv(entry.level),csv(entry.source),csv(entry.category),csv(entry.direction),csv(entry.from),csv(entry.to),csv(entry.channel),csv(entry.domain),csv(entry.objectId),csv(entry.transmissionId),csv(entry.packetPart),csv(entry.packetTotal),csv(entry.bytes),csv(entry.messageKind),csv(entry.version),csv(entry.eventName),csv(entry.correlationId),csv(entry.message)},",")end else for _,entry in ipairs(projected)do local extra=route(entry);local packet=entry.packetPart and entry.packetTotal and string.format(" %s/%s",entry.packetPart,entry.packetTotal)or"";lines[#lines+1]=string.format("%s [%s] [%s/%s] %s%s%s%s",date("%Y-%m-%d %H:%M:%S",entry.timestamp),entry.level,entry.source,entry.category,entry.direction~=""and(entry.direction.." ")or"",extra,packet,entry.message~=""and(" | "..entry.message)or"")end end;return table.concat(lines,"\n")
end
function Logs:ExportDiscord(all)local entries=all and HolyStorm.Logger:GetHistory()or self:GetFiltered();local modules={};for _,entry in ipairs(entries)do modules[entry.source or"-"]=true end;local names={};for name in pairs(modules)do names[#names+1]=name end;table.sort(names);return string.format("**"..L["LOG_EXPORT_TITLE"].."**\n%s: %s\n%s: %s\n%s: %s / %s\n```text\n%s\n```",HolyStorm.version,L["LOG_EXPORT_TIME"],date("%Y-%m-%d %H:%M:%S"),L["LOG_EXPORT_MODULES"],table.concat(names,", "),L["LOG_EXPORT_FILTER"],all and L["ALL"]or self.filters.level,all and""or self.filters.search,self:Export("text",all))end

function Logs:ShowExport(all)
 local format=self.exportFormat or"text";local value=format=="discord"and self:ExportDiscord(all)or self:Export(format,all);if not self.exportDialog then local dialog=CreateFrame("Frame",nil,UIParent,"BackdropTemplate");dialog:SetSize(720,500);dialog:SetPoint("CENTER");dialog:SetFrameStrata("DIALOG");if dialog.SetBackdrop then dialog:SetBackdrop({bgFile="Interface\\DialogFrame\\UI-DialogBox-Background",edgeFile="Interface\\DialogFrame\\UI-DialogBox-Border",edgeSize=24,insets={left=6,right=6,top=6,bottom=6}})end;local title=dialog:CreateFontString(nil,"OVERLAY","GameFontNormalLarge");title:SetPoint("TOPLEFT",20,-18);title:SetText(L["EXPORT"]);local close=CreateFrame("Button",nil,dialog,"UIPanelButtonTemplate");close:SetSize(80,22);close:SetText(L["CLOSE"]);close:SetScript("OnClick",function()dialog:Hide()end);close:SetPoint("BOTTOMRIGHT",-18,16);local help=dialog:CreateFontString(nil,"OVERLAY","GameFontHighlightSmall");help:SetPoint("BOTTOMLEFT",20,24);help:SetText(L["EXPORT_COPY_HELP"]);local scroll=CreateFrame("ScrollFrame",nil,dialog,"UIPanelScrollFrameTemplate");scroll:SetPoint("TOPLEFT",20,-48);scroll:SetPoint("BOTTOMRIGHT",-38,52);local edit=CreateFrame("EditBox",nil,scroll);edit:SetMultiLine(true);edit:SetAutoFocus(false);edit:SetFontObject("ChatFontNormal");edit:SetWidth(650);edit:SetScript("OnEscapePressed",function()dialog:Hide()end);scroll:SetScrollChild(edit);dialog.edit,dialog.scroll=edit,scroll;self.exportDialog=dialog end;local lines=1;value:gsub("\n",function()lines=lines+1 end);self.exportDialog.edit:SetHeight(math.max(self.exportDialog.scroll:GetHeight(),lines*14+20));self.exportDialog.edit:SetText(value);self.exportDialog:Show();self.exportDialog.edit:HighlightText();self.exportDialog.edit:SetFocus()
end

function Logs:SetPaused(value)self.paused=value==true;if self.pauseButton then self.pauseButton:SetText(self.paused and L["RESUME"]or L["PAUSE"])end;if not self.paused then self:Render()end end
function Logs:SetAutoScroll(value)self.autoScroll=value==true;self:GetSettings().autoScroll=self.autoScroll;if self.autoScrollCheck then self.autoScrollCheck:SetChecked(self.autoScroll)end;if self.autoScroll then self:ScrollToEnd()end end
function Logs:SetLevel(level)return self:SetFilter("level",level or"ALL")end
function Logs:Refresh()self:Render()end
function Logs:FormatDetails(entry)
 if not entry then return L["NO_LOG_ENTRIES"]end;local c=context(entry);local lines={L["TIME"]..": "..date("%Y-%m-%d %H:%M:%S",tonumber(entry.timestamp)or 0),L["LEVEL"]..": "..tostring(entry.level or"-"),L["MODULE"]..": "..tostring(entry.source or"-"),L["CATEGORY"]..": "..tostring(entry.category or"-"),L["MESSAGE"]..": "..tostring(entry.message or"-")};local labels={direction=L["DIRECTION"],from=L["FROM"],to=L["TO"],channel=L["CHANNEL"],domain=L["DOMAIN"],objectId=L["OBJECT"],transmissionId=L["TRANSMISSION"],correlationId=L["CORRELATION_ID"]};for _,key in ipairs({"direction","from","to","channel","domain","objectId","transmissionId","correlationId"})do local value=key=="transmissionId"and transmission(entry)or key=="correlationId"and correlation(entry)or c[key];if value and value~=""then lines[#lines+1]=labels[key]..": "..tostring(destination(value))end end;if c.packetPart or c.packetTotal then lines[#lines+1]=L["PACKET"]..": "..tostring(c.packetPart or"-").." / "..tostring(c.packetTotal or"-")end
 local known={direction=true,from=true,to=true,channel=true,domain=true,objectId=true,transmissionId=true,correlationId=true,packetPart=true,packetTotal=true};for _,item in ipairs(flattenContext(c))do if not known[item[1]]then lines[#lines+1]=item[1]..": "..item[2]end end;return table.concat(lines,"\n")
end
function Logs:SelectEntry(entry)self.selected=entry;if self.detailsText then self.detailsText:SetText(self:FormatDetails(entry));if self.detailsContent and self.detailsScroll then self.detailsContent:SetHeight(math.max(self.detailsScroll:GetHeight(),(self.detailsText:GetStringHeight()or 1)+8));self.detailsScroll:SetVerticalScroll(0)end end end

local function makeButton(parent,text,width,callback)local button=CreateFrame("Button",nil,parent,"UIPanelButtonTemplate");button:SetSize(width,22);button:SetText(text);button:SetScript("OnClick",callback);return button end
function Logs:CreateFilterMenu(parent,kind,label,x,width)
 local caption=parent:CreateFontString(nil,"OVERLAY","GameFontNormalSmall");caption:SetPoint("TOPLEFT",x,-6);caption:SetText(label);local menu=CreateFrame("Frame",nil,parent,"UIDropDownMenuTemplate");menu:SetPoint("TOPLEFT",x-16,-17);UIDropDownMenu_SetWidth(menu,width);UIDropDownMenu_Initialize(menu,function(_,level)if level~=1 then return end;local values={"ALL"};for _,value in ipairs(Logs:GetOptions(kind))do values[#values+1]=value end;for _,value in ipairs(values)do local selected=value;local info=UIDropDownMenu_CreateInfo();info.text=value=="ALL"and L["ALL"]or(value=="SEND"and L["SEND"]or value=="RECEIVE"and L["RECEIVE"]or value);info.checked=lower(Logs.filters[kind])==lower(value);info.func=function()Logs:SetFilter(kind,selected)end;UIDropDownMenu_AddButton(info,level)end end);self.filterMenus=self.filterMenus or{};self.filterMenus[kind]=menu;return menu
end
function Logs:UpdateMenuText(kind)local menu=self.filterMenus and self.filterMenus[kind];if not menu then return end;local value=self.filters[kind];UIDropDownMenu_SetText(menu,value=="ALL"and L["ALL"]or(value=="SEND"and L["SEND"]or value=="RECEIVE"and L["RECEIVE"]or value))end

local columnDefinitions={{id="time",label="TIME",width=.075},{id="level",label="LEVEL",width=.07},{id="module",label="MODULE",width=.105},{id="category",label="CATEGORY",width=.10},{id="direction",label="DIRECTION",width=.075},{id="route",label="ROUTE",width=.18},{id="progress",label="PROGRESS",width=.075},{id="correlation",label="CORRELATION_ID",width=.12},{id="message",label="MESSAGE",width=.20}}
function Logs:LayoutRow(row,width)local x=4;for index,definition in ipairs(columnDefinitions)do local cellWidth=index==#columnDefinitions and math.max(80,width-x-4)or math.floor(width*definition.width);local cell=row.cells[definition.id];cell:ClearAllPoints();cell:SetPoint("LEFT",row,"LEFT",x,0);cell:SetWidth(math.max(20,cellWidth-6));x=x+cellWidth end;row:SetWidth(width)end
function Logs:AcquireRow(index)
 local row=self.rows[index];if row then return row end;row=CreateFrame("Button",nil,self.content);row:SetHeight(self.rowHeight);row:RegisterForClicks("LeftButtonUp");row.background=row:CreateTexture(nil,"BACKGROUND");row.background:SetAllPoints();row.background:SetColorTexture(1,1,1,.035);row.cells={};for _,definition in ipairs(columnDefinitions)do local cell=row:CreateFontString(nil,"OVERLAY","GameFontHighlightSmall");cell:SetJustifyH("LEFT");cell:SetWordWrap(false);row.cells[definition.id]=cell end;row:SetScript("OnClick",function(button)Logs:SelectEntry(button.entry)end);row:SetScript("OnEnter",function(button)button.background:SetColorTexture(.25,.55,.85,.18)end);row:SetScript("OnLeave",function(button)button.background:SetColorTexture(1,1,1,button.dataIndex and button.dataIndex%2==0 and.055 or.025)end);self.rows[index]=row;return row
end
function Logs:RenderRows()
 if not self.scroll or not self.filtered then return end;local width=math.max(1,self.scroll:GetWidth()-4);local height=math.max(1,self.scroll:GetHeight());local first=math.max(1,math.floor((self.scroll:GetVerticalScroll()or 0)/self.rowHeight)+1);local visible=math.min(60,math.ceil(height/self.rowHeight)+2);for poolIndex=1,visible do local dataIndex=first+poolIndex-1;local row=self:AcquireRow(poolIndex);local entry=self.filtered[dataIndex];if entry then row.entry,row.dataIndex=entry,dataIndex;row:ClearAllPoints();row:SetPoint("TOPLEFT",self.content,"TOPLEFT",0,-((dataIndex-1)*self.rowHeight));self:LayoutRow(row,width);row.cells.time:SetText(date("%H:%M:%S",tonumber(entry.timestamp)or 0));row.cells.level:SetText(entry.level or"-");row.cells.module:SetText(entry.source or"-");row.cells.category:SetText(string.upper(tostring(entry.category or"-")));row.cells.direction:SetText(direction(entry)=="SEND"and L["SEND"]or direction(entry)=="RECEIVE"and L["RECEIVE"]or"");row.cells.route:SetText(route(entry));row.cells.progress:SetText(progress(entry));row.cells.correlation:SetText(correlation(entry));row.cells.message:SetText(entry.message or"");local lc=LEVEL_COLORS[entry.level]or{.85,.85,.85};for _,cell in pairs(row.cells)do cell:SetTextColor(lc[1],lc[2],lc[3])end;local cc=CATEGORY_COLORS[lower(entry.category)];if cc then row.cells.category:SetTextColor(cc[1],cc[2],cc[3])end;row.background:SetColorTexture(1,1,1,dataIndex%2==0 and.055 or.025);row:Show()else row.entry,row.dataIndex=nil,nil;row:Hide()end end;for poolIndex=visible+1,#self.rows do self.rows[poolIndex]:Hide()end
end
function Logs:ScrollToEnd()if not self.scroll or not self.content then return end;self.scroll:SetVerticalScroll(math.max(0,self.content:GetHeight()-self.scroll:GetHeight()))end
function Logs:Render()
 if not self.page or not self.page:IsShown()or self.paused then return end;self:EnsureValidFilters();for kind in pairs(self.filterMenus or{})do self:UpdateMenuText(kind)end;self.filtered=self:GetFiltered();local height=math.max(self.scroll:GetHeight(),#self.filtered*self.rowHeight);self.content:SetHeight(math.max(1,height));self.content:SetWidth(math.max(1,self.scroll:GetWidth()-4));if self.emptyText then self.emptyText:SetShown(#self.filtered==0)end;if self.autoScroll then self:ScrollToEnd()else local maximum=math.max(0,height-self.scroll:GetHeight());if self.scroll:GetVerticalScroll()>maximum then self.scroll:SetVerticalScroll(maximum)end end;self:RenderRows()
end

function Logs:OnInitialize()
 self:LoadSettings();local UI=HolyStorm:GetModule("UI",true);local page=CreateFrame("Frame",nil,UI.content);self.page=page;self.rowHeight=21;self.rows={};self.filterMenus={}
 local searchLabel=page:CreateFontString(nil,"OVERLAY","GameFontNormalSmall");searchLabel:SetPoint("TOPLEFT",18,-6);searchLabel:SetText(L["SEARCH"]);local search=CreateFrame("EditBox",nil,page,"SearchBoxTemplate");search:SetSize(210,22);search:SetPoint("TOPLEFT",18,-20);search:SetText(self.filters.search);search:SetScript("OnTextChanged",function(box)Logs:SetFilter("search",box:GetText())end);self.searchBox=search
 self:CreateFilterMenu(page,"level",L["LEVEL"],240,92);self:CreateFilterMenu(page,"module",L["MODULE"],342,118);self:CreateFilterMenu(page,"category",L["CATEGORY"],470,110);self:CreateFilterMenu(page,"direction",L["DIRECTION"],590,100);self:CreateFilterMenu(page,"event",L["EVENT"],700,165)
 local quick={{"ERROR",L["ERRORS"]},{"WARN",L["WARNINGS"]},{"EVENT",L["EVENTS"]},{"TASK",L["TASKS"]},{"WORKFLOW",L["WORKFLOWS"]},{"SYNC",L["SYNC"]},{"COMMS",L["COMMS"]}};local x=18;for _,definition in ipairs(quick)do local kind=definition[1];local button=makeButton(page,definition[2],82,function()Logs:SetQuickFilter(kind)end);button:SetPoint("TOPLEFT",x,-51);x=x+86 end
 local reset=makeButton(page,L["RESET_FILTERS"],125,function()Logs:ResetFilters()end);reset:SetPoint("TOPLEFT",x,-51);local clear=makeButton(page,L["CLEAR"],70,function()if HolyStorm.Permissions:Has("logs-clear")then HolyStorm.Logger:Clear()end end);clear:SetPoint("LEFT",reset,"RIGHT",6,0);local pause=makeButton(page,L["PAUSE"],85,function()Logs:SetPaused(not Logs.paused)end);pause:SetPoint("LEFT",clear,"RIGHT",6,0);self.pauseButton=pause
 local auto=CreateFrame("CheckButton",nil,page,"UICheckButtonTemplate");auto:SetPoint("LEFT",pause,"RIGHT",8,0);auto:SetChecked(self.autoScroll);auto:SetScript("OnClick",function(button)Logs:SetAutoScroll(button:GetChecked())end);local autoLabel=page:CreateFontString(nil,"OVERLAY","GameFontNormalSmall");autoLabel:SetPoint("LEFT",auto,"RIGHT",1,0);autoLabel:SetText(L["AUTO_SCROLL"]);self.autoScrollCheck=auto
 local header=CreateFrame("Frame",nil,page);header:SetPoint("TOPLEFT",18,-80);header:SetPoint("TOPRIGHT",-28,-80);header:SetHeight(20);header.cells={};for _,definition in ipairs(columnDefinitions)do local cell=header:CreateFontString(nil,"OVERLAY","GameFontNormalSmall");cell:SetText(L[definition.label]);cell:SetJustifyH("LEFT");header.cells[definition.id]=cell end;self:LayoutRow(header,900);self.header=header
 local details=CreateFrame("Frame",nil,page,"BackdropTemplate");details:SetPoint("BOTTOMLEFT",18,12);details:SetPoint("BOTTOMRIGHT",-28,12);details:SetHeight(132);if details.SetBackdrop then details:SetBackdrop({bgFile="Interface\\Buttons\\WHITE8x8",edgeFile="Interface\\Buttons\\WHITE8x8",edgeSize=1});details:SetBackdropColor(.02,.03,.045,.96);details:SetBackdropBorderColor(.3,.24,.08,.9)end;local detailsTitle=details:CreateFontString(nil,"OVERLAY","GameFontNormal");detailsTitle:SetPoint("TOPLEFT",8,-7);detailsTitle:SetText(L["DETAILS"]);local detailsScroll=CreateFrame("ScrollFrame",nil,details,"UIPanelScrollFrameTemplate");detailsScroll:SetPoint("TOPLEFT",6,-24);detailsScroll:SetPoint("BOTTOMRIGHT",-26,6);local detailsContent=CreateFrame("Frame",nil,detailsScroll);detailsContent:SetSize(1,1);detailsScroll:SetScrollChild(detailsContent);local detailsText=detailsContent:CreateFontString(nil,"OVERLAY","GameFontHighlightSmall");detailsText:SetPoint("TOPLEFT",2,-2);detailsText:SetPoint("RIGHT",-2,0);detailsText:SetJustifyH("LEFT");detailsText:SetJustifyV("TOP");detailsText:SetText(L["NO_LOG_ENTRIES"]);detailsScroll:SetScript("OnSizeChanged",function(scrollFrame)detailsContent:SetWidth(math.max(1,scrollFrame:GetWidth()-4));detailsContent:SetHeight(math.max(scrollFrame:GetHeight(),(detailsText:GetStringHeight()or 1)+8))end);self.detailsText,self.detailsScroll,self.detailsContent=detailsText,detailsScroll,detailsContent
 local formats={{"text",L["FORMAT_TEXT"]},{"csv",L["FORMAT_CSV"]},{"json",L["FORMAT_JSON"]},{"discord",L["FORMAT_DISCORD"]}};self.exportFormat="text";local formatMenu=CreateFrame("Frame",nil,details,"UIDropDownMenuTemplate");formatMenu:SetPoint("TOPRIGHT",-198,5);UIDropDownMenu_SetWidth(formatMenu,92);UIDropDownMenu_SetText(formatMenu,L["FORMAT_TEXT"]);UIDropDownMenu_Initialize(formatMenu,function(_,level)if level~=1 then return end;for _,definition in ipairs(formats)do local selected,label=definition[1],definition[2];local info=UIDropDownMenu_CreateInfo();info.text=label;info.checked=Logs.exportFormat==selected;info.func=function()Logs.exportFormat=selected;UIDropDownMenu_SetText(formatMenu,label)end;UIDropDownMenu_AddButton(info,level)end end);local exportFiltered=makeButton(details,L["EXPORT_FILTERED"],92,function()Logs:ShowExport(false)end);exportFiltered:SetPoint("TOPRIGHT",-102,-3);local exportAll=makeButton(details,L["EXPORT_ALL"],92,function()Logs:ShowExport(true)end);exportAll:SetPoint("TOPRIGHT",-6,-3)
 local scroll=CreateFrame("ScrollFrame",nil,page,"UIPanelScrollFrameTemplate");scroll:SetPoint("TOPLEFT",18,-102);scroll:SetPoint("BOTTOMRIGHT",-28,152);local content=CreateFrame("Frame",nil,scroll);content:SetSize(1,1);scroll:SetScrollChild(content);self.scroll,self.content=scroll,content;local empty=content:CreateFontString(nil,"OVERLAY","GameFontDisable");empty:SetPoint("TOPLEFT",8,-8);empty:SetText(L["NO_LOG_ENTRIES"]);self.emptyText=empty;scroll:SetScript("OnVerticalScroll",function(_,offset)scroll:SetVerticalScroll(offset);Logs:RenderRows()end);scroll:SetScript("OnSizeChanged",function()Logs:LayoutRow(header,math.max(1,scroll:GetWidth()-4));Logs:Render()end)
 HolyStorm.UI:RegisterPage("logs",page,L["TITLE"],function()Logs:Render()end,{"HS_LOG_ADDED","HS_LOG_CLEARED"});HolyStorm.UI:AddNavigation("logs",12,"Interface\\Icons\\INV_Misc_Note_01",L["TITLE"],L["DESCRIPTION"],function()HolyStorm.UI:ShowPage("logs")end)
end
