local addonVersion="1.0.0"
local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm")
local Logs=HolyStorm:RegisterRequiredModule("Logs");HolyStorm:ApplyModuleMetadata(Logs,{displayName="Logs",internalName="logs",version=addonVersion,category="required",description="Technical log table and export",permissions={"logs-view"},dependencies={"core","ui"},enabledByDefault=true})
local function json(v)if v==nil then return"null"elseif type(v)=="boolean"or type(v)=="number"then return tostring(v)elseif type(v)=="string"then return'"'..v:gsub('\\','\\\\'):gsub('"','\\"'):gsub('\n','\\n')..'"'elseif type(v)=="table"then local array=true;local count=0;for k in pairs(v)do count=count+1;if type(k)~="number"then array=false end end;local out={};if array then for i=1,count do out[#out+1]=json(v[i])end;return"["..table.concat(out,",").."]"end;for k,x in pairs(v)do out[#out+1]=json(tostring(k))..":"..json(x)end;table.sort(out);return"{"..table.concat(out,",").."}"end;return"null"end
function Logs:GetFiltered()local out={};local q=string.lower(self.search or"");for _,e in ipairs(HolyStorm.Logger:GetHistory())do if(not self.level or e.level==self.level)and(q==""or string.lower((e.source or"").." "..(e.category or"").." "..(e.message or"")):find(q,1,true))then out[#out+1]=e end end;return out end
function Logs:Export(format,all)local entries=all and HolyStorm.Logger:GetHistory()or self:GetFiltered();if format=="json"then return json(entries)end;local lines={};if format=="csv"then lines[1]='timestamp,level,module,category,message';for _,e in ipairs(entries)do local function q(v)return'"'..tostring(v or""):gsub('"','""')..'"'end;lines[#lines+1]=table.concat({q(e.timestamp),q(e.level),q(e.source),q(e.category),q(e.message)},",")end else for _,e in ipairs(entries)do lines[#lines+1]=string.format("%s [%s] [%s/%s] %s",date("%Y-%m-%d %H:%M:%S",e.timestamp),e.level,e.source,e.category,e.message)end end;return table.concat(lines,"\n")end
function Logs:SetPaused(value)self.paused=value==true;if not self.paused then self:Render()end end;function Logs:SetAutoScroll(value)self.autoScroll=value==true end;function Logs:SetLevel(level)self.level=level;self:Render()end;function Logs:Refresh()self:Render()end
function Logs:ExportDiscord()local entries=self:GetFiltered();local modules={};for _,e in ipairs(entries)do modules[e.source]=true end;local names={};for n in pairs(modules)do names[#names+1]=n end;table.sort(names);return string.format("**Holy Storm %s — Log Export**\nTime: %s\nModules: %s\nFilter: %s / %s\n```text\n%s\n```",HolyStorm.version,date("%Y-%m-%d %H:%M:%S"),table.concat(names,", "),self.level or"ALL",self.search or"",self:Export("text",false))end
function Logs:Render()if not self.page:IsShown()or self.paused then return end;local lines={"TIME      | LEVEL | MODULE       | CATEGORY     | MESSAGE"};for _,e in ipairs(self:GetFiltered())do lines[#lines+1]=string.format("%s | %-5s | %-12s | %-12s | %s",date("%H:%M:%S",e.timestamp),e.level,e.source,e.category,e.message)end;self.text:SetText(table.concat(lines,"\n"));self.content:SetHeight(math.max(self.scroll:GetHeight(),self.text:GetStringHeight()+12));if self.autoScroll then self.scroll:SetVerticalScroll(math.max(0,self.content:GetHeight()-self.scroll:GetHeight()))end end
function Logs:OnInitialize()local UI=HolyStorm:GetModule("UI",true);local p=CreateFrame("Frame",nil,UI.content);local search=CreateFrame("EditBox",nil,p,"SearchBoxTemplate");search:SetSize(240,24);search:SetPoint("TOPLEFT",18,-18);search:SetScript("OnTextChanged",function(x)Logs.search=x:GetText();Logs:Render()end);local clear=CreateFrame("Button",nil,p,"UIPanelButtonTemplate");clear:SetSize(80,24);clear:SetPoint("LEFT",search,"RIGHT",8,0);clear:SetText(CLEAR);clear:SetScript("OnClick",function()if HolyStorm.Permissions:Has("logs-clear")then HolyStorm.Logger:Clear()end end);local scroll=CreateFrame("ScrollFrame",nil,p,"UIPanelScrollFrameTemplate");scroll:SetPoint("TOPLEFT",18,-54);scroll:SetPoint("BOTTOMRIGHT",-28,18);local content=CreateFrame("Frame",nil,scroll);content:SetSize(1,1);scroll:SetScrollChild(content);local text=content:CreateFontString(nil,"OVERLAY","GameFontHighlightSmall");text:SetPoint("TOPLEFT",4,-4);text:SetJustifyH("LEFT");self.page,self.scroll,self.content,self.text,self.autoScroll=p,scroll,content,text,true;scroll:SetScript("OnSizeChanged",function(x)content:SetWidth(x:GetWidth());Logs:Render()end);HolyStorm.UI:RegisterPage("logs",p,"Holy Storm — Logs",function()Logs:Render()end,{"HS_LOG_ADDED","HS_LOG_CLEARED"});HolyStorm.UI:AddNavigation("logs",12,"Interface\\Icons\\INV_Misc_Note_01","Logs","Technical logs",function()HolyStorm.UI:ShowPage("logs")end)end
