local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm")
local L=LibStub("AceLocale-3.0"):GetLocale("Holy_Storm_Policy")
local Page=HolyStorm:RegisterRequiredModule("PolicyInspectorUI")
local DEFAULT_PERMISSION,DEFAULT_SCOPE="news-edit","global"
HolyStorm:ApplyModuleMetadata(Page,{displayName=L["INSPECTOR_TITLE"],internalName="policyInspectorUI",version="2.0.0",category="required",description=L["INSPECTOR_DESC"],permissions={"policy-inspect"},dependencies={"core","ui"},enabledByDefault=true})
local function displayReason(reason)return string.format("%s: %s",L["MEMBERSHIP_"..reason.type]or reason.type,tostring(reason.name or reason.id))end
local function displayTime(value)return value and date("%Y-%m-%d %H:%M:%S",value)or"—"end
function Page:Inspect()
 local guid=self.character:GetValue()or UnitGUID("player");local accountUUID=guid and(HolyStorm.TwinkCore:GetAccountUUIDForCharacter(guid)or HolyStorm.Data.PlayerStore:GetCharacterOwner(guid));local permission=self.permission:GetText();local explanation=HolyStorm.Policy:Explain(permission,accountUUID,guid,self.target:GetText());local state=HolyStorm.Policy:GetPermissionStateStatus();local lines={L["IDENTITY"],L["CHARACTER"]..": "..tostring(guid),L["ACCOUNT_MEMBERS"]..": "..tostring(accountUUID),"",L["STATUS"]..": "..(L["STATE_"..tostring(state.status)]or tostring(state.status)),L["VERSION"]..": "..tostring(state.version),L["RESULT"]..": "..(explanation.allowed and L["ALLOWED"]or L["DENIED"]),"",L["EFFECTIVE_MEMBERS"]}
 for id,group in pairs(explanation.groups)do local sources={};for _,reason in ipairs(group.reasons or{})do sources[#sources+1]=displayReason(reason)end;lines[#lines+1]=string.format("• %s (%s) — %s",HolyStorm.PolicyUI:DisplayGroupName(group),id,table.concat(sources,", "))end
 lines[#lines+1]="";lines[#lines+1]=L["SOURCES"];for _,grant in ipairs(explanation.grants)do lines[#lines+1]="✓ "..HolyStorm.PolicyUI:DisplayGroupName(grant) end;if#explanation.grants==0 then lines[#lines+1]="— "..L["NONE"]end
 local filterId=self.filter:GetText();if filterId~=""then local result,trace=HolyStorm.Policy:ApplyFilter(filterId,{guid=guid},self.filterScope:GetText()=="local"and"local"or"global");lines[#lines+1]="";lines[#lines+1]=L["FILTER_REASON"].." "..filterId..": "..(result and L["PASSED"]or L["FAILED"]);lines[#lines+1]=HolyStorm.PolicyUI:FlattenTrace(trace)end
 lines[#lines+1]="";lines[#lines+1]=L["REVISION_HISTORY"];for _,revision in ipairs(HolyStorm.Policy:GetRevisionHistory())do lines[#lines+1]=string.format("v%d | %s | %s | %s | %s",revision.version or 0,tostring(revision.revisionID),tostring(revision.previousRevisionID),tostring(revision.action or(revision.change and revision.change.action)),displayTime(revision.changedAt))end
 lines[#lines+1]="";lines[#lines+1]=L["REJECTED_REVISIONS"];for _,rejected in ipairs(HolyStorm.Policy:GetRejectedRevisions())do lines[#lines+1]=string.format("%s | %s | %s | %s",tostring(rejected.revisionID),tostring(rejected.sender),tostring(rejected.reason),displayTime(rejected.timestamp))end
 if state.missingRevisions or state.recovery or state.fork then lines[#lines+1]="";lines[#lines+1]=L["STATUS"]..": "..tostring(state.catchupReason or(state.recovery and state.recovery.reason)or(state.fork and state.fork.reason)or state.status)end;self.output:SetText(table.concat(lines,"\n"))
end
function Page:OnInitialize()
 local UI=HolyStorm:GetModule("UI",true);local p=CreateFrame("Frame",nil,UI.content);self.page=p;local title=HolyStorm.PolicyUI:Label(p,L["INSPECTOR_TITLE"],"GameFontHighlightLarge");title:SetPoint("TOPLEFT",14,-12)
 self.character=HolyStorm.PolicyUI:CreateSelector(p,260,function()return HolyStorm.PolicyUI:CharacterItems()end);self.character:SetPoint("TOPLEFT",-2,-48);self.permission=HolyStorm.PolicyUI:Edit(p,220);self.permission:SetPoint("TOPLEFT",295,-64);self.permission:SetText(DEFAULT_PERMISSION);self.target=HolyStorm.PolicyUI:Edit(p,180);self.target:SetPoint("TOPLEFT",526,-64);self.filter=HolyStorm.PolicyUI:Edit(p,180);self.filter:SetPoint("TOPLEFT",717,-64);self.filterScope=HolyStorm.PolicyUI:Edit(p,75);self.filterScope:SetPoint("TOPLEFT",908,-64);self.filterScope:SetText(DEFAULT_SCOPE)
 local inspect=HolyStorm.PolicyUI:Button(p,L["ANALYSIS"],100,function()Page:Inspect()end);inspect:SetPoint("TOPLEFT",14,-100);local scroll,text=HolyStorm.PolicyUI:CreateTextPanel(p);scroll:SetPoint("TOPLEFT",14,-132);scroll:SetPoint("BOTTOMRIGHT",-28,18);self.output=text;HolyStorm.UI:RegisterPage("policyInspector",p,L["INSPECTOR_TITLE"],function()Page:Inspect()end,{"HS_POLICY_UPDATED","HS_PERMISSIONS_REVISION_REJECTED","HS_PERMISSIONS_CONFLICT_DETECTED","HS_PERMISSIONS_RECOVERY_REQUIRED"});HolyStorm.UI:AddNavigation("policyInspector",17,"Interface\\Icons\\INV_Misc_Eye_01",L["INSPECTOR_TITLE"],L["INSPECTOR_DESC"],function()HolyStorm.UI:ShowPage("policyInspector")end)
end
