local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm")
local L=LibStub("AceLocale-3.0"):GetLocale("Holy_Storm_Achievements")
local metadata={id="AchievementsUI",name="Achievements",internalName="achievements",displayName=L["DISPLAY_NAME"],description=L["DESCRIPTION"],version="1.0.0",moduleType="feature",category="feature",permissions={{id="achievement-view",category="Achievements",defaults={officers=true,member=true}},{id="achievement-create",category="Achievements",defaults={officers=true}},{id="achievement-edit",category="Achievements",defaults={officers=true}},{id="achievement-delete",category="Achievements",defaults={officers=true}},{id="achievement-publish",category="Achievements",defaults={officers=true}},{id="achievement-award",category="Achievements",defaults={officers=true}},{id="achievement-revoke",category="Achievements",defaults={officers=true}},{id="achievement-admin",category="Achievements",defaults={officers=true}},{id="achievement-test",category="Achievements",defaults={officers=true}}},dependencies={"core","synchronization"},ui={page="achievements",characterTab="achievements",navigation=true},data={store="AchievementStore"},sync={domains={"achievements"}},enabledByDefault=true}
HolyStorm:RegisterModule(metadata,function(Page)
local function setStatus(text)HolyStorm.Events:Emit("HS_UI_STATUS_REQUESTED",text)end
local function when(value)return value and(date and date("%d.%m.%Y %H:%M",value)or tostring(value))or"-"end
local function characterName(guid)local record=HolyStorm.Data.CharacterStore:Get(guid);return record and(record.name or record.fullName)or guid end
local function traceText(trace)local text=HolyStorm.PolicyUI:FlattenTrace(trace);return text~=""and text:gsub("\n","; ")or L["NO_RULE"]end
local function typeItems()return{{value="AUTOMATIC",label=L["AUTOMATIC"]},{value="MANUAL",label=L["MANUAL"]},{value="FEAT_OF_STRENGTH",label=L["FEAT_OF_STRENGTH"]}}end
local function scopeItems()return{{value="CHARACTER",label=L["CHARACTER"]},{value="ACCOUNT",label=L["ACCOUNT"]}}end
local function sourceItems()local out={{value="GUILD",label=L["SOURCE_GUILD"]},{value="MANUAL",label=L["SOURCE_MANUAL"]}};if IsInRaid and IsInRaid()then out[#out+1]={value="RAID",label=L["SOURCE_RAID"]}elseif IsInGroup and IsInGroup()then out[#out+1]={value="PARTY",label=L["SOURCE_PARTY"]}end;for filterId,filter in pairs(HolyStorm.Policy:GetFilters()or{})do out[#out+1]={value="FILTER:"..filterId,label=L["SOURCE_FILTER"]..": "..(filter.name or filterId)}end;table.sort(out,function(a,b)return a.label<b.label end);return out end
function Page:VisibleItems()
 local query=(self.search:GetText()or""):lower();local state=self.stateFilter:GetValue()or"ALL";local wantedType=self.typeFilter:GetValue()or"ALL";local category=self.categoryFilter and self.categoryFilter:GetValue()or"ALL";local definitionStatus=self.statusFilter and self.statusFilter:GetValue()or"ALL";local includeHidden=HolyStorm.Achievements:Can("achievement-admin");local out={};for _,definition in ipairs(HolyStorm.Achievements:GetDefinitions(includeHidden,self.characterGuid or UnitGUID("player")))do local earned=HolyStorm.Achievements:IsEarned(definition.achievementID,self.characterGuid or UnitGUID("player"));local haystack=((definition.name or"").." "..(definition.description or"").." "..(definition.category or"")):lower();if(query==""or haystack:find(query,1,true))and(state=="ALL"or state=="EARNED"and earned or state=="NOT_EARNED"and not earned)and(wantedType=="ALL"or definition.type==wantedType)and(category=="ALL"or definition.category==category)and(definitionStatus=="ALL"or definition.status==definitionStatus)then out[#out+1]=definition end end;return out
end
function Page:Render()
 if not self.page:IsShown()or self.mode~="browser"then return end;local items=self:VisibleItems();self.list:SetItems(items,function(definition)local earned,award=HolyStorm.Achievements:IsEarned(definition.achievementID,self.characterGuid or UnitGUID("player"));return(earned and L["EARNED"]or L["NOT_EARNED"]).."  "..definition.name.."  |cff888888"..definition.category.."|r"end);self.empty:SetShown(#items==0);self.newButton:SetEnabled(HolyStorm.Achievements:Can("achievement-create"));if self.selected then local current=HolyStorm.Achievements:GetDefinition(self.selected.achievementID);if current then self:Select(current)else self:Select(nil)end end
end
function Page:ShowMode(mode)self.mode=mode;if self.browser then self.browser:SetShown(mode=="browser")end;if self.editor then self.editor:SetShown(mode=="editor")end;if self.preview then self.preview:SetShown(mode=="preview")end;for _,widget in ipairs({self.search,self.stateFilter,self.typeFilter,self.categoryFilter,self.statusFilter,self.newButton})do if widget then widget:SetShown(mode=="browser"and(widget~=self.statusFilter or HolyStorm.Achievements:Can("achievement-admin")))end end end
function Page:Select(definition)
 self.selected=definition;self:ShowMode("browser");self.detail:SetShown(definition~=nil);if not definition then return end;self.detailIcon:SetTexture(definition.icon);self.detailTitle:SetText(definition.name);local earned,award=HolyStorm.Achievements:IsEarned(definition.achievementID,self.characterGuid or UnitGUID("player"));self.detailState:SetText(earned and L["EARNED"]or L["NOT_EARNED"]);self.detailMeta:SetText(table.concat({definition.category,L[definition.type],L[definition.status],L["REVISION"].." "..definition.revision},"  ·  "));HolyStorm.RichContent:Render(self.rich,definition.description,{achievementID=definition.achievementID})
 local recipients={};for _,entry in ipairs(HolyStorm.Data.AchievementStore:GetAwardsFor(definition.achievementID))do if entry.status=="AWARDED"then recipients[#recipients+1]=entry end end;self.recipientList:SetItems(recipients,function(entry)return characterName(entry.characterUUID).."  ·  "..when(entry.awardedAt)end);self.recipientList:SetShown(#recipients>0);self.noAwards:SetShown(#recipients==0);self.editButton:SetEnabled(HolyStorm.Achievements:Can("achievement-edit"));self.activateButton:SetEnabled(definition.status~="ACTIVE"and HolyStorm.Achievements:Can("achievement-publish"));self.archiveButton:SetEnabled(definition.status~="ARCHIVED"and HolyStorm.Achievements:Can("achievement-delete"));self.awardButton:SetEnabled(definition.status=="ACTIVE"and definition.type~="AUTOMATIC"and HolyStorm.Achievements:Can("achievement-award"));self.testButton:SetEnabled(definition.status=="ACTIVE"and definition.type~="AUTOMATIC"and HolyStorm.Achievements:Can("achievement-test"));self.revokeButton:SetEnabled(self.selectedAward~=nil and HolyStorm.Achievements:Can("achievement-revoke"))
end
function Page:Edit(definition)
 self.draft=HolyStorm.Utils.DeepCopy(definition or{name="",description="",category=L["CATEGORY_GENERAL"],type="AUTOMATIC",scope="CHARACTER",status="DRAFT",repeatable=false,icon=236681,rule={logic="AND",children={{field="character.level",operator=">=",value=1}}}});self.name:SetText(self.draft.name);self.description:SetText(self.draft.description);self.category:SetText(self.draft.category);self.icon:SetText(tostring(self.draft.icon));self.typeSelect:SetValue(self.draft.type,L[self.draft.type]);self.scopeSelect:SetValue(self.draft.scope,L[self.draft.scope]);self.repeatable:SetChecked(self.draft.repeatable);self.builder:SetRule(self.draft.rule);self:ShowMode("editor")
end
function Page:Save(status)
 local draft=HolyStorm.Utils.DeepCopy(self.draft);draft.name=self.name:GetText();draft.description=self.description:GetText();draft.category=self.category:GetText();draft.icon=tonumber(self.icon:GetText())or self.icon:GetText();draft.type=self.typeSelect:GetValue()or"AUTOMATIC";draft.scope=self.scopeSelect:GetValue()or"CHARACTER";draft.repeatable=self.repeatable:GetChecked()==true;draft.rule=self.builder:GetRule();draft.status=status or draft.status or"DRAFT";local ok,result=HolyStorm.Achievements:SaveDefinition(draft);if not ok then setStatus(string.format(L["INVALID"],tostring(result)));return end;setStatus(L["DEFINITION_SAVED"]);self:Select(result);self:Render()
end
function Page:BuildPreview(testMode)
 if not self.selected then return end;local source=self.sourceSelect:GetValue()or((IsInRaid and IsInRaid())and"RAID"or(IsInGroup and IsInGroup())and"PARTY"or"GUILD");local manual;if source=="MANUAL"then manual={};for token in tostring(self.manualInput:GetText()or""):gmatch("[^,;\n]+")do token=token:match("^%s*(.-)%s*$");local guid=HolyStorm.Chat and HolyStorm.Chat:ResolveCharacter(token)or(HolyStorm.Data.CharacterStore:Get(token)and token);if guid then manual[#manual+1]=guid end end end;local request,reason=HolyStorm.Achievements:QueuePreview(self.selected.achievementID,source,manual,testMode);if not request then setStatus(tostring(reason));return end;self.previewRequest=request;self.previewTitle:SetText(L["PREVIEW"]);self.previewText:SetText(L["UNKNOWN"]);self.confirmButton:SetEnabled(false);self:ShowMode("preview")
end
function Page:ShowPreviewResult(requestID,ok,result)if requestID~=self.previewRequest then return end;if not ok then setStatus(tostring(result));self:Select(self.selected);return end;self.currentPreview=result;local lines={result.testMode and L["TEST_WARNING"]or"",string.format(L["CAPTURED_AT"],when(result.capturedAt)),string.format(L["PREVIEW_COUNTS"],result.counts.total,result.counts.PASS,result.counts.FAIL,result.counts.UNKNOWN),""};for _,candidate in ipairs(result.candidates)do local color=candidate.result=="PASS"and"|cff20ff20"or candidate.result=="FAIL"and"|cffff4040"or"|cff888888";lines[#lines+1]=color..L[candidate.result].."|r: "..characterName(candidate.characterUUID).." — "..traceText(candidate.trace)end;self.previewText:SetText(table.concat(lines,"\n"));self.confirmButton:SetEnabled(not result.testMode and result.counts.PASS>0)end
function Page:ConfirmPreview()local preview=self.currentPreview;if not preview then return end;StaticPopupDialogs.HOLYSTORM_ACHIEVEMENT_AWARD={text=string.format(L["CONFIRM_AWARD"],preview.counts.PASS),button1=L["CONFIRM"],button2=L["CANCEL"],OnAccept=function()HolyStorm.Achievements:QueueConfirm(preview.previewID)end,timeout=0,whileDead=true,hideOnEscape=true};StaticPopup_Show("HOLYSTORM_ACHIEVEMENT_AWARD")end
function Page:RevokeSelected()local award=self.selectedAward;if not award then return end;StaticPopupDialogs.HOLYSTORM_ACHIEVEMENT_REVOKE={text=string.format(L["CONFIRM_REVOKE"],self.selected.name,characterName(award.characterUUID)),button1=L["REVOKE"],button2=L["CANCEL"],OnAccept=function()HolyStorm.Achievements:QueueRevoke(award.awardID)end,timeout=0,whileDead=true,hideOnEscape=true};StaticPopup_Show("HOLYSTORM_ACHIEVEMENT_REVOKE")end
local function refreshCharacter(view,context,definition)
 local rows={};for _,achievement in ipairs(HolyStorm.Achievements:GetDefinitions(false,context.characterUUID))do local earned,award=HolyStorm.Achievements:IsEarned(achievement.achievementID,context.characterUUID);rows[#rows+1]={achievementID=achievement.achievementID,state=earned and L["EARNED"]or L["NOT_EARNED"],name=achievement.name,category=achievement.category,awardedAt=award and when(award.awardedAt)or"",description=achievement.description}end;HolyStorm.CharacterUI:SetTableView(view,rows,{emptyText=L["NO_ACHIEVEMENTS"]})
end
local function buildCharacter(parent)return HolyStorm.CharacterUI:CreateTableView(parent,{columns={{id="state",title=L["COLUMN_STATE"],width=130},{id="name",title=L["NAME"],weight=1,minWidth=220,truncate=true,tooltip=function(row)return row.description end},{id="category",title=L["CATEGORY"],width=170},{id="awardedAt",title=L["AWARDED_AT"],width=150}},rowHeight=26,headerHeight=26,columnGap=1,emptyText=L["NO_ACHIEVEMENTS"],onRowClick=function(row)HolyStorm.Achievements:Open(row.achievementID)end})end
function Page:InitializeUI()
 local UI=HolyStorm:GetModule("UI",true);local p=CreateFrame("Frame",nil,UI.content);self.page=p;self.mode="browser";local title=HolyStorm.PolicyUI:Label(p,L["ACHIEVEMENTS"],"GameFontHighlightLarge");title:SetPoint("TOPLEFT",14,-12);self.search=HolyStorm.PolicyUI:Edit(p,210,function()Page:Render()end);self.search:SetPoint("TOPLEFT",14,-42);self.search:SetText("");self.stateFilter=HolyStorm.PolicyUI:CreateSelector(p,115,function()return{{value="ALL",label=L["ALL"]},{value="EARNED",label=L["FILTER_EARNED"]},{value="NOT_EARNED",label=L["FILTER_NOT_EARNED"]}}end,function()Page:Render()end);self.stateFilter:SetPoint("LEFT",self.search,"RIGHT",4,0);self.stateFilter:SetValue("ALL",L["ALL"]);self.typeFilter=HolyStorm.PolicyUI:CreateSelector(p,130,function()local out={{value="ALL",label=L["ALL"]}};for _,entry in ipairs(typeItems())do out[#out+1]=entry end;return out end,function()Page:Render()end);self.typeFilter:SetPoint("LEFT",self.stateFilter,"RIGHT",-12,0);self.typeFilter:SetValue("ALL",L["ALL"]);self.newButton=HolyStorm.PolicyUI:Button(p,L["NEW"],80,function()Page:Edit(nil)end);self.newButton:SetPoint("TOPRIGHT",-14,-42)
 self.categoryFilter=HolyStorm.PolicyUI:CreateSelector(p,145,function()local seen,out={},{{value="ALL",label=L["ALL"]}};for _,definition in pairs(HolyStorm.Data.AchievementStore:GetDefinitions())do if not seen[definition.category]then seen[definition.category]=true;out[#out+1]={value=definition.category,label=definition.category}end end;return out end,function()Page:Render()end);self.categoryFilter:SetPoint("TOPLEFT",-15,-70);self.categoryFilter:SetValue("ALL",L["ALL"]);self.statusFilter=HolyStorm.PolicyUI:CreateSelector(p,125,function()return{{value="ALL",label=L["ALL"]},{value="DRAFT",label=L["DRAFT"]},{value="ACTIVE",label=L["ACTIVE"]},{value="ARCHIVED",label=L["ARCHIVED"]}}end,function()Page:Render()end);self.statusFilter:SetPoint("LEFT",self.categoryFilter,"RIGHT",-12,0);self.statusFilter:SetValue("ALL",L["ALL"]);self.statusFilter:SetShown(HolyStorm.Achievements:Can("achievement-admin"))
 self.browser=CreateFrame("Frame",nil,p);self.browser:SetPoint("TOPLEFT",14,-104);self.browser:SetPoint("BOTTOMRIGHT",-14,14);self.list=HolyStorm.PolicyUI:CreateList(self.browser,function(definition)Page.selectedAward=nil;Page:Select(definition)end);self.list:SetPoint("TOPLEFT");self.list:SetSize(285,500);self.empty=HolyStorm.PolicyUI:Label(self.browser,L["NO_ACHIEVEMENTS"]);self.empty:SetPoint("TOPLEFT",0,-8);self.detail=CreateFrame("Frame",nil,self.browser);self.detail:SetPoint("TOPLEFT",300,0);self.detail:SetPoint("BOTTOMRIGHT");self.detailIcon=self.detail:CreateTexture(nil,"ARTWORK");self.detailIcon:SetSize(54,54);self.detailIcon:SetPoint("TOPLEFT");self.detailTitle=HolyStorm.PolicyUI:Label(self.detail,"","GameFontNormalLarge");self.detailTitle:SetPoint("TOPLEFT",self.detailIcon,"TOPRIGHT",12,-2);self.detailState=HolyStorm.PolicyUI:Label(self.detail,"");self.detailState:SetPoint("TOPLEFT",self.detailTitle,"BOTTOMLEFT",0,-6);self.detailMeta=HolyStorm.PolicyUI:Label(self.detail,"");self.detailMeta:SetPoint("TOPLEFT",0,-68);self.rich=HolyStorm.RichContent:CreateRenderer(self.detail);self.rich.frame:ClearAllPoints();self.rich.frame:SetPoint("TOPLEFT",0,-92);self.rich.frame:SetPoint("BOTTOMRIGHT",-310,115);local earnedTitle=HolyStorm.PolicyUI:Label(self.detail,L["RECIPIENTS"],"GameFontNormal");earnedTitle:SetPoint("TOPRIGHT",-190,-96);self.recipientList=HolyStorm.PolicyUI:CreateList(self.detail,function(award)Page.selectedAward=award;Page.revokeButton:SetEnabled(HolyStorm.Achievements:Can("achievement-revoke"))end);self.recipientList:SetPoint("TOPRIGHT",0,-118);self.recipientList:SetSize(285,270);self.noAwards=HolyStorm.PolicyUI:Label(self.detail,L["NO_AWARDS"]);self.noAwards:SetPoint("TOPRIGHT",-160,-125)
 local buttons={{"editButton",L["EDIT"],function()Page:Edit(Page.selected)end},{"activateButton",L["ACTIVATE"],function()local ok,result=HolyStorm.Achievements:SetStatus(Page.selected.achievementID,"ACTIVE");if ok then Page:Select(result);Page:Render()else setStatus(tostring(result))end end},{"archiveButton",L["ARCHIVE"],function()local ok,result=HolyStorm.Achievements:SetStatus(Page.selected.achievementID,"ARCHIVED");if ok then Page:Select(result);Page:Render()else setStatus(tostring(result))end end},{"awardButton",L["AWARD"],function()Page:BuildPreview(false)end},{"testButton",L["TEST"],function()Page:BuildPreview(true)end},{"revokeButton",L["REVOKE"],function()Page:RevokeSelected()end}};for index,item in ipairs(buttons)do local b=HolyStorm.PolicyUI:Button(self.detail,item[2],index==4 and 145 or 105,item[3]);b:SetPoint("BOTTOMLEFT",(index-1)*112,5);self[item[1]]=b end;self.sourceSelect=HolyStorm.PolicyUI:CreateSelector(self.detail,140,sourceItems);self.sourceSelect:SetPoint("BOTTOMLEFT",335,38);self.sourceSelect:SetValue("GUILD",L["SOURCE_GUILD"]);self.manualInput=HolyStorm.PolicyUI:Edit(self.detail,240);self.manualInput:SetPoint("LEFT",self.sourceSelect,"RIGHT",-12,0);self.manualInput:SetText("")
 self.editor=CreateFrame("Frame",nil,p);self.editor:SetPoint("TOPLEFT",14,-72);self.editor:SetPoint("BOTTOMRIGHT",-14,14);local function field(label,x,y,width)local l=HolyStorm.PolicyUI:Label(self.editor,label);l:SetPoint("TOPLEFT",x,y);local e=HolyStorm.PolicyUI:Edit(self.editor,width);e:SetPoint("TOPLEFT",x,y-18);return e end;self.name=field(L["NAME"],0,0,260);self.category=field(L["CATEGORY"],275,0,180);self.icon=field(L["ICON"],470,0,140);self.description=field(L["DESCRIPTION_FIELD"],0,-52,610);self.typeSelect=HolyStorm.PolicyUI:CreateSelector(self.editor,170,typeItems);self.typeSelect:SetPoint("TOPLEFT",-15,-110);self.scopeSelect=HolyStorm.PolicyUI:CreateSelector(self.editor,140,scopeItems);self.scopeSelect:SetPoint("TOPLEFT",165,-110);self.repeatable=CreateFrame("CheckButton",nil,self.editor,"UICheckButtonTemplate");self.repeatable:SetPoint("TOPLEFT",325,-106);self.repeatable.text:SetText(L["REPEATABLE"]);self.builder=HolyStorm.PolicyUI:CreateRuleBuilder(self.editor);self.builder:SetPoint("TOPLEFT",0,-150);self.builder:SetPoint("BOTTOMRIGHT",0,45);local save=HolyStorm.PolicyUI:Button(self.editor,L["SAVE_DRAFT"],120,function()Page:Save("DRAFT")end);save:SetPoint("BOTTOMLEFT",0,0);local activate=HolyStorm.PolicyUI:Button(self.editor,L["ACTIVATE"],110,function()Page:Save("ACTIVE")end);activate:SetPoint("LEFT",save,"RIGHT",6,0);local cancel=HolyStorm.PolicyUI:Button(self.editor,L["BACK"],90,function()Page:Select(Page.selected);Page:Render()end);cancel:SetPoint("LEFT",activate,"RIGHT",6,0)
 self.preview=CreateFrame("Frame",nil,p);self.preview:SetPoint("TOPLEFT",14,-74);self.preview:SetPoint("BOTTOMRIGHT",-14,14);self.previewTitle=HolyStorm.PolicyUI:Label(self.preview,L["PREVIEW"],"GameFontHighlightLarge");self.previewTitle:SetPoint("TOPLEFT");local scroll;scroll,self.previewText=HolyStorm.PolicyUI:CreateTextPanel(self.preview);scroll:SetPoint("TOPLEFT",0,-35);scroll:SetPoint("BOTTOMRIGHT",0,42);self.confirmButton=HolyStorm.PolicyUI:Button(self.preview,L["CONFIRM"],120,function()Page:ConfirmPreview()end);self.confirmButton:SetPoint("BOTTOMLEFT");local previewBack=HolyStorm.PolicyUI:Button(self.preview,L["BACK"],100,function()Page:Select(Page.selected);Page:Render()end);previewBack:SetPoint("LEFT",self.confirmButton,"RIGHT",6,0)
 self:ShowMode("browser");self.detail:Hide();HolyStorm.UI:RegisterPage("achievements",p,L["ACHIEVEMENTS"],function()Page:Render()end);HolyStorm.UI:AddNavigation("achievements",8,"Interface\\Icons\\Achievement_GuildPerk_EverybodysFriend",L["ACHIEVEMENTS"],L["DESCRIPTION"],function()HolyStorm.UI:ShowPage("achievements")end)
 HolyStorm:RegisterCharacterTab("AchievementsUI",{id="achievements",order=6.5,label=L["TAB_ACHIEVEMENTS"],labelKey="TAB_ACHIEVEMENTS",permission="achievement-view",icon="Interface\\Icons\\Achievement_GuildPerk_EverybodysFriend",blocks={},events={"HS_ACHIEVEMENT_DEFINITION_UPDATED","HS_ACHIEVEMENT_AWARDS_UPDATED","HS_ACHIEVEMENT_SYNC_UPDATED"},build=buildCharacter,refresh=refreshCharacter})
 for _,event in ipairs({"HS_ACHIEVEMENT_DEFINITION_UPDATED","HS_ACHIEVEMENT_AWARDS_UPDATED","HS_ACHIEVEMENT_SYNC_UPDATED"})do HolyStorm.Events:Register(event,"achievements-ui",function()Page:Render();if HolyStorm.CharacterUI and HolyStorm.CharacterUI.context then local overview=HolyStorm:GetModule("CharacterOverview",true);if overview then overview:ScheduleRefresh("achievements")end end end)end;HolyStorm.Events:Register("HS_ACHIEVEMENT_OPEN_REQUESTED","achievements-ui-open",function(_,achievementID)local definition=HolyStorm.Achievements:GetDefinition(achievementID);if definition and HolyStorm.Achievements:IsVisible(definition)then HolyStorm.UI:ShowPage("achievements");Page:Select(definition);Page:Render()end end)
 HolyStorm.Events:Register("HS_ACHIEVEMENT_PREVIEW_READY","achievements-ui-preview",function(_,requestID,ok,result)Page:ShowPreviewResult(requestID,ok,result)end);HolyStorm.Events:Register("HS_ACHIEVEMENT_AWARD_FINISHED","achievements-ui-award",function(_,ok,result)setStatus(ok and L["AWARD_SAVED"]or tostring(result));Page:Select(Page.selected);Page:Render()end);HolyStorm.Events:Register("HS_ACHIEVEMENT_REVOKE_FINISHED","achievements-ui-revoke",function(_,ok,result)setStatus(ok and L["REVOKED"]or tostring(result));Page.selectedAward=nil;Page:Select(Page.selected);Page:Render()end)
end
function Page:OnInitialize()
 HolyStorm.Achievements:Initialize()
 HolyStorm:RegisterUIExtension("AchievementsUI",{id="achievements.page",order=8,initialize=function()Page:InitializeUI()end})
end
function Page:OnDisable()for _,owner in ipairs({"achievements-ui","achievements-ui-open","achievements-ui-preview","achievements-ui-award","achievements-ui-revoke"})do HolyStorm.Events:UnregisterOwner(owner)end end
end)
