local L=LibStub("AceLocale-3.0"):NewLocale("Holy_Storm_GuildRoster","deDE")
if not L then return end
L["GUILD_ACTIVITY"]="Aktivität";L["GUILD_ACTION_VIEW_ACTIVITY"]="Aktivität anzeigen";L["GUILD_UNKNOWN"]="Unbekannt"
L["GUILD_ACTIVITY_DAYS"]="%d Tage";L["GUILD_ACTIVITY_ACCOUNT"]="Account / Referenzcharakter";L["GUILD_ACTIVITY_LAST_ACTIVITY"]="Letzte Aktivität";L["GUILD_ACTIVITY_LAST_SEEN"]="Zuletzt gesehen";L["GUILD_ACTIVITY_ONLINE"]="Online";L["GUILD_ACTIVITY_CHAT"]="Gildenchat";L["GUILD_ACTIVITY_RAIDS"]="Raids";L["GUILD_ACTIVITY_MYTHICPLUS"]="Mythisch+";L["GUILD_ACTIVITY_TIME"]="Zeit";L["GUILD_ACTIVITY_TYPE"]="Aktivitätstyp";L["GUILD_ACTIVITY_CHARACTER"]="Charakter";L["GUILD_ACTIVITY_PROVIDER"]="Anbieter";L["GUILD_ACTIVITY_DETAILS"]="Details"
L["GUILD_ACTIVITY_EMPTY"]="Kein berechtigter Aktivitätsverlauf verfügbar.";L["GUILD_ACTIVITY_HISTORY_EMPTY"]="Keine Aktivität entspricht diesen sachlichen Filtern.";L["GUILD_ACTIVITY_SELECT_ACCOUNT"]="Wähle einen Account, um dessen sachlichen Aktivitätsverlauf anzuzeigen.";L["GUILD_ACTIVITY_UNAVAILABLE"]="Aktivitätsdaten nicht verfügbar";L["GUILD_ACTIVITY_ALL_PROVIDERS"]="Alle Anbieter";L["GUILD_ACTIVITY_ALL_CHARACTERS"]="Alle Charaktere";L["GUILD_ACTIVITY_APPROXIMATE"]="Enthält verdichtete Zeiträume";L["GUILD_ACTIVITY_RECOVERED"]="wiederhergestellt; Endzeit unsicher";L["GUILD_ACTIVITY_DURATION"]="%d Std. %02d Min.";L["GUILD_ACTIVITY_CHAT_MESSAGES"]="%d Gildenchat-Nachrichten";L["GUILD_ACTIVITY_DETAIL_SUMMARY"]="%s · %d Charaktere · %s online · %d Chat · %d Raids · %d Mythisch+"
L["GUILD_ACTIVITY_RAID_DETAIL"]="%s · %s · %s%s";L["GUILD_ACTIVITY_MYTHICPLUS_DETAIL"]="%s +%s · %s%s";L["GUILD_ACTIVITY_SUCCESS"]="Erfolg";L["GUILD_ACTIVITY_FAILED"]="nicht besiegt";L["GUILD_ACTIVITY_TIMED"]="innerhalb der Zeit";L["GUILD_ACTIVITY_NOT_TIMED"]="nicht innerhalb der Zeit";L["GUILD_ACTIVITY_GROUP_FORMAT"]=" · %s (%d/%d Gilde)";L["GUILD_ACTIVITY_GROUP_FULL_GUILD"]="vollständige Gildengruppe";L["GUILD_ACTIVITY_GROUP_MAJORITY_GUILD"]="mehrheitliche Gildengruppe";L["GUILD_ACTIVITY_GROUP_PARTIAL_GUILD"]="teilweise Gildengruppe";L["GUILD_ACTIVITY_GROUP_NOT_GUILD_RELEVANT"]="nicht gildenrelevant";L["GUILD_ACTIVITY_GROUP_UNKNOWN"]="unbekannte Gruppe"
L["GUILD_ACTIVITY_TYPE_ONLINE_SESSION"]="Online-Sitzung";L["GUILD_ACTIVITY_TYPE_GUILD_CHAT"]="Gildenchat";L["GUILD_ACTIVITY_TYPE_RAID_ENCOUNTER"]="Raidbegegnung";L["GUILD_ACTIVITY_TYPE_MYTHICPLUS_RUN"]="Mythisch+-Abschluss";L["GUILD_ACTIVITY_TYPE_EVENT_ATTENDANCE"]="Ereignisteilnahme"
L["GUILD_ACTIVITY_PROVIDER_ONLINE"]="Online";L["GUILD_ACTIVITY_PROVIDER_GUILD_CHAT"]="Gildenchat";L["GUILD_ACTIVITY_PROVIDER_RAID"]="Raid";L["GUILD_ACTIVITY_PROVIDER_MYTHIC_PLUS"]="Mythisch+"
L["GUILD_ACTIVITY_TASK_CAPTURE"]="Gildenaktivität erfassen";L["GUILD_ACTIVITY_TASK_CHAT"]="Gildenchat-Aktivität zusammenfassen";L["GUILD_ACTIVITY_TASK_SESSION"]="Gildenaktivitätssitzung öffnen"
L["PERMISSION_GUILD_ACTIVITY_VIEW"]="Gildenaktivität anzeigen";L["PERMISSION_DESC_GUILD_ACTIVITY_VIEW"]="Gewöhnliche sachliche Gildenaktivität und synchronisierten Verlauf anzeigen."
L["GUILD_RULE_ACTIVITY_LAST_SEEN"]="Aktivität: zuletzt gesehen";L["GUILD_RULE_ACTIVITY_LAST_SEEN_DESC"]="Zuletzt beobachteter Online-Zeitstempel des Accounts.";L["GUILD_RULE_ACTIVITY_DAYS_SINCE"]="Tage seit letzter Aktivität";L["GUILD_RULE_ACTIVITY_DAYS_SINCE_DESC"]="Volle UTC-Tage seit der zuletzt erfassten Aktivität des Accounts.";L["GUILD_RULE_ACTIVITY_ONLINE_7D"]="Online-Dauer (7 Tage)";L["GUILD_RULE_ACTIVITY_ONLINE_7D_DESC"]="Erfasste Online-Sekunden in den letzten 7 Tagen.";L["GUILD_RULE_ACTIVITY_CHAT_7D"]="Gildenchat-Anzahl (7 Tage)";L["GUILD_RULE_ACTIVITY_CHAT_7D_DESC"]="Gildenchat-Beteiligung in den letzten 7 Tagen; Nachrichteninhalte werden nie gespeichert.";L["GUILD_RULE_ACTIVITY_RAID_30D"]="Raidteilnahme (30 Tage)";L["GUILD_RULE_ACTIVITY_RAID_30D_DESC"]="Gildenrelevante Teilnahme an Raidbegegnungen in den letzten 30 Tagen.";L["GUILD_RULE_ACTIVITY_MYTHICPLUS_30D"]="Mythisch+-Teilnahme (30 Tage)";L["GUILD_RULE_ACTIVITY_MYTHICPLUS_30D_DESC"]="Gildenrelevante abgeschlossene Mythisch+-Läufe in den letzten 30 Tagen.";L["GUILD_RULE_ACTIVITY_EVENT_30D"]="Ereignisteilnahme (30 Tage)";L["GUILD_RULE_ACTIVITY_EVENT_30D_DESC"]="Zuverlässig beobachtete Ereignisteilnahme in den letzten 30 Tagen; derzeit ohne Anbieter UNBEKANNT."
