local L=LibStub("AceLocale-3.0"):NewLocale("Holy_Storm_GuildRoster","deDE")
L["ACTIVITY_POINTS"]="AktivitÃ¤tspunkte";L["ACTIVITY_POINTS_ADMIN_TITLE"]="AktivitÃ¤tspunkte";L["ACTIVITY_POINTS_ADMIN_DESC"]="Prospektive Punkteregeln und deterministischen Wertungsverfall konfigurieren.";L["ACTIVITY_POINTS_RULES"]="Punkteregeln";L["ACTIVITY_POINTS_POINTS"]="Punkte";L["ACTIVITY_POINTS_ENABLED"]="Aktiv";L["ACTIVITY_POINTS_REVISION"]="Revision";L["ACTIVITY_POINTS_YES"]="Ja";L["ACTIVITY_POINTS_NO"]="Nein";L["ACTIVITY_POINTS_NO_RULES"]="Keine Punkteregeln konfiguriert.";L["ACTIVITY_POINTS_DECAY_NONE"]="Kein Verfall";L["ACTIVITY_POINTS_DECAY_FIXED"]="Fester Verfall";L["ACTIVITY_POINTS_DECAY_PERCENT"]="Prozentualer Verfall";L["ACTIVITY_POINTS_SAVE_DECAY"]="Verfall speichern";L["ACTIVITY_POINTS_RAW_SCORE"]="Rohe AktivitÃ¤tswertung";L["ACTIVITY_POINTS_EFFECTIVE_SCORE"]="Effektive AktivitÃ¤tswertung";L["ACTIVITY_POINTS_SCORE_DESC"]="Accountwertung aus dem nachvollziehbaren AktivitÃ¤tspunkte-Ledger.";L["PERMISSION_GUILD_ACTIVITY_POINTS_VIEW"]="AktivitÃ¤tspunkte anzeigen";L["PERMISSION_DESC_GUILD_ACTIVITY_POINTS_VIEW"]="Accountwertungen und Punkteverlauf anzeigen.";L["PERMISSION_GUILD_ACTIVITY_POINTS_CONFIGURE"]="AktivitÃ¤tspunkte konfigurieren";L["PERMISSION_DESC_GUILD_ACTIVITY_POINTS_CONFIGURE"]="Punkteregeln und Wertungsverfall erstellen und verwalten.";L["PERMISSION_GUILD_ACTIVITY_POINTS_ADJUST"]="AktivitÃ¤tspunkte anpassen";L["PERMISSION_DESC_GUILD_ACTIVITY_POINTS_ADJUST"]="Separat protokollierte positive oder negative Punkteanpassungen erstellen."
L["ACTIVITY_POINTS_ENABLE_DISABLE"]="Aktivieren / deaktivieren";L["ACTIVITY_POINTS_MANUAL_ADJUSTMENT"]="Manuelle Anpassung";L["ACTIVITY_POINTS_MANUAL_ADJUSTMENT_REASON"]="Begründung erforderlich"
L["ACTIVITY_POINTS_RULE_NAME"]="Regelname";L["ACTIVITY_POINTS_DECAY_SECTION"]="Verfall";L["ACTIVITY_POINTS_DECAY_MODE"]="Verfallsart";L["ACTIVITY_POINTS_DECAY_INTERVAL"]="Intervall (Tage)";L["ACTIVITY_POINTS_DECAY_AMOUNT"]="Verfallswert";L["ACTIVITY_POINTS_TARGET"]="Zielcharakter";L["ACTIVITY_POINTS_ADJUSTMENT_AMOUNT"]="Anpassung (+ / -)";L["ACTIVITY_POINTS_APPLY_ADJUSTMENT"]="Anpassung anwenden"
if not L then return end
L["GUILD_ACTIVITY"]="Aktivität";L["GUILD_ACTION_VIEW_ACTIVITY"]="Aktivität anzeigen";L["GUILD_UNKNOWN"]="Unbekannt"
L["GUILD_ACTIVITY_DAYS"]="%d Tage";L["GUILD_ACTIVITY_ACCOUNT"]="Account / Referenzcharakter";L["GUILD_ACTIVITY_LAST_ACTIVITY"]="Letzte Aktivität";L["GUILD_ACTIVITY_LAST_SEEN"]="Zuletzt gesehen";L["GUILD_ACTIVITY_ONLINE"]="Online";L["GUILD_ACTIVITY_CHAT"]="Gildenchat";L["GUILD_ACTIVITY_RAIDS"]="Raids";L["GUILD_ACTIVITY_MYTHICPLUS"]="Mythisch+";L["GUILD_ACTIVITY_TIME"]="Zeit";L["GUILD_ACTIVITY_TYPE"]="Aktivitätstyp";L["GUILD_ACTIVITY_CHARACTER"]="Charakter";L["GUILD_ACTIVITY_PROVIDER"]="Anbieter";L["GUILD_ACTIVITY_DETAILS"]="Details"
L["GUILD_ACTIVITY_EMPTY"]="Kein berechtigter Aktivitätsverlauf verfügbar.";L["GUILD_ACTIVITY_HISTORY_EMPTY"]="Keine Aktivität entspricht diesen sachlichen Filtern.";L["GUILD_ACTIVITY_SELECT_ACCOUNT"]="Wähle einen Account, um dessen sachlichen Aktivitätsverlauf anzuzeigen.";L["GUILD_ACTIVITY_UNAVAILABLE"]="Aktivitätsdaten nicht verfügbar";L["GUILD_ACTIVITY_ALL_PROVIDERS"]="Alle Anbieter";L["GUILD_ACTIVITY_ALL_CHARACTERS"]="Alle Charaktere";L["GUILD_ACTIVITY_APPROXIMATE"]="Enthält verdichtete Zeiträume";L["GUILD_ACTIVITY_RECOVERED"]="wiederhergestellt; Endzeit unsicher";L["GUILD_ACTIVITY_DURATION"]="%d Std. %02d Min.";L["GUILD_ACTIVITY_CHAT_MESSAGES"]="%d Gildenchat-Nachrichten";L["GUILD_ACTIVITY_DETAIL_SUMMARY"]="%s · %d Charaktere · %s online · %d Chat · %d Raids · %d Mythisch+"
L["GUILD_ACTIVITY_RAID_DETAIL"]="%s · %s · %s%s";L["GUILD_ACTIVITY_MYTHICPLUS_DETAIL"]="%s +%s · %s%s";L["GUILD_ACTIVITY_SUCCESS"]="Erfolg";L["GUILD_ACTIVITY_FAILED"]="nicht besiegt";L["GUILD_ACTIVITY_TIMED"]="innerhalb der Zeit";L["GUILD_ACTIVITY_NOT_TIMED"]="nicht innerhalb der Zeit";L["GUILD_ACTIVITY_GROUP_FORMAT"]=" · %s (%d/%d Gilde)";L["GUILD_ACTIVITY_GROUP_FULL_GUILD"]="vollständige Gildengruppe";L["GUILD_ACTIVITY_GROUP_MAJORITY_GUILD"]="mehrheitliche Gildengruppe";L["GUILD_ACTIVITY_GROUP_PARTIAL_GUILD"]="teilweise Gildengruppe";L["GUILD_ACTIVITY_GROUP_NOT_GUILD_RELEVANT"]="nicht gildenrelevant";L["GUILD_ACTIVITY_GROUP_UNKNOWN"]="unbekannte Gruppe"
L["GUILD_ACTIVITY_TYPE_ONLINE_SESSION"]="Online-Sitzung";L["GUILD_ACTIVITY_TYPE_GUILD_CHAT"]="Gildenchat";L["GUILD_ACTIVITY_TYPE_RAID_ENCOUNTER"]="Raidbegegnung";L["GUILD_ACTIVITY_TYPE_MYTHICPLUS_RUN"]="Mythisch+-Abschluss";L["GUILD_ACTIVITY_TYPE_EVENT_ATTENDANCE"]="Ereignisteilnahme"
L["GUILD_ACTIVITY_PROVIDER_ONLINE"]="Online";L["GUILD_ACTIVITY_PROVIDER_GUILD_CHAT"]="Gildenchat";L["GUILD_ACTIVITY_PROVIDER_RAID"]="Raid";L["GUILD_ACTIVITY_PROVIDER_MYTHIC_PLUS"]="Mythisch+"
L["GUILD_ACTIVITY_TASK_CAPTURE"]="Gildenaktivität erfassen";L["GUILD_ACTIVITY_TASK_CHAT"]="Gildenchat-Aktivität zusammenfassen";L["GUILD_ACTIVITY_TASK_SESSION"]="Gildenaktivitätssitzung öffnen"
L["PERMISSION_GUILD_ACTIVITY_VIEW"]="Gildenaktivität anzeigen";L["PERMISSION_DESC_GUILD_ACTIVITY_VIEW"]="Gewöhnliche sachliche Gildenaktivität und synchronisierten Verlauf anzeigen."
L["GUILD_RULE_ACTIVITY_LAST_SEEN"]="Aktivität: zuletzt gesehen";L["GUILD_RULE_ACTIVITY_LAST_SEEN_DESC"]="Zuletzt beobachteter Online-Zeitstempel des Accounts.";L["GUILD_RULE_ACTIVITY_DAYS_SINCE"]="Tage seit letzter Aktivität";L["GUILD_RULE_ACTIVITY_DAYS_SINCE_DESC"]="Volle UTC-Tage seit der zuletzt erfassten Aktivität des Accounts.";L["GUILD_RULE_ACTIVITY_ONLINE_7D"]="Online-Dauer (7 Tage)";L["GUILD_RULE_ACTIVITY_ONLINE_7D_DESC"]="Erfasste Online-Sekunden in den letzten 7 Tagen.";L["GUILD_RULE_ACTIVITY_CHAT_7D"]="Gildenchat-Anzahl (7 Tage)";L["GUILD_RULE_ACTIVITY_CHAT_7D_DESC"]="Gildenchat-Beteiligung in den letzten 7 Tagen; Nachrichteninhalte werden nie gespeichert.";L["GUILD_RULE_ACTIVITY_RAID_30D"]="Raidteilnahme (30 Tage)";L["GUILD_RULE_ACTIVITY_RAID_30D_DESC"]="Gildenrelevante Teilnahme an Raidbegegnungen in den letzten 30 Tagen.";L["GUILD_RULE_ACTIVITY_MYTHICPLUS_30D"]="Mythisch+-Teilnahme (30 Tage)";L["GUILD_RULE_ACTIVITY_MYTHICPLUS_30D_DESC"]="Gildenrelevante abgeschlossene Mythisch+-Läufe in den letzten 30 Tagen.";L["GUILD_RULE_ACTIVITY_EVENT_30D"]="Ereignisteilnahme (30 Tage)";L["GUILD_RULE_ACTIVITY_EVENT_30D_DESC"]="Zuverlässig beobachtete Ereignisteilnahme in den letzten 30 Tagen; derzeit ohne Anbieter UNBEKANNT."
