local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm")
local L=LibStub("AceLocale-3.0"):GetLocale("Holy_Storm_GuildRoster")
local GM=HolyStorm.GuildManagement
local Points={version="1.0.0",schemaVersion=1,initialized=false,events={ONLINE_SESSION=true,GUILD_CHAT=true,RAID_ENCOUNTER=true,MYTHICPLUS_RUN=true,EVENT_ATTENDANCE=true},scoreCache={}}
local function now()return HolyStorm.Utils.Now()end
local function copy(value)return HolyStorm.Utils.DeepCopy(value)end
local function trim(value)return tostring(value or""):gsub("^%s+",""):gsub("%s+$","")end
local function store()return HolyStorm.Data.GuildActivityPointsStore end
local function log(level,category,message,context)if HolyStorm.Logger then HolyStorm.Logger:Write(level,"GuildActivityPoints",category,message,context)end end
local function initial()return{schemaVersion=1,guildId=GM:GetGuildId(),revision=0,revisionHistory={},updatedAt=0,updatedByCharacterUUID=nil,authorityCharacterUUID=nil,rules={},ruleHistory={},ledger={},ledgerByAccount={},decay={mode="NONE",intervalDays=30,amount=0},cache={}}end
local function guildData(guildId,create)
 guildId=guildId or GM:GetGuildId();if not guildId then return nil end
 local data=store():GetGuild(guildId);if not data and create then data=initial();data.guildId=guildId;store():PutGuild(guildId,data)end;return data
end
local function authorized(permission,accountUUID,characterUUID,target)return GM:Can(permission,accountUUID,characterUUID,target)end
local function advanceRevision(data,characterUUID,at)
 data.previousRevisionID=data.revisionID;if data.revisionID then data.revisionHistory=data.revisionHistory or{};data.revisionHistory[#data.revisionHistory+1]=data.revisionID end;data.revision=(tonumber(data.revision)or 0)+1;data.revisionID=GM:NewId("activity-points-revision");data.updatedAt=at or now();data.updatedByCharacterUUID=characterUUID;data.authorityCharacterUUID=data.authorityCharacterUUID or characterUUID
end
function Points:InvalidateScore(guildId,accountUUID)
 if not guildId then self.scoreCache={};return end;local cache=self.scoreCache[guildId];if cache then if accountUUID then cache[accountUUID]=nil else self.scoreCache[guildId]=nil end end
end
local function stableId(...)
 local text=table.concat({...},"\031");local a,b=5381,52711;for i=1,#text do local c=text:byte(i);a=(a*33+c)%4294967291;b=(b*65599+c)%4294967279 end;return string.format("gap-%08x%08x",a,b)
end
local function validAmount(v)return type(v)=="number"and v==v and v%1==0 and math.abs(v)<=1000000 end
function Points:CanView(accountUUID,characterUUID,target)return authorized("guild-activity-points-view",accountUUID,characterUUID,target)end
function Points:CanConfigure(accountUUID,characterUUID,target)return authorized("guild-activity-points-configure",accountUUID,characterUUID,target)end
function Points:ValidateRule(rule)
 if type(rule)~="table"or type(rule.id)~="string"or#rule.id>96 or not rule.id:match("^[%w_%.%-:]+$")or type(rule.enabled)~="boolean"or type(rule.name)~="string"or#trim(rule.name)==0 or#rule.name>120 or type(rule.description)~="string"or#rule.description>500 or not self.events[rule.eventType]or not validAmount(rule.points)or type(rule.revision)~="number"or rule.revision<1 or type(rule.createdAt)~="number"or type(rule.updatedAt)~="number"or type(rule.effectiveFrom)~="number"or type(rule.createdByCharacterUUID)~="string"or type(rule.updatedByCharacterUUID)~="string"then return false,"INVALID_RULE"end;return true
end
function Points:ListRules(guildId)
 local out={};for _,rule in pairs(store():GetRules(guildId)or{})do out[#out+1]=rule end;table.sort(out,function(a,b)return a.id<b.id end);return out
end
function Points:SaveRule(input,expectedRevision)
 input=type(input)=="table"and input or{};local who=GM:Actor();if not self:CanConfigure(who.accountUUID,who.characterUUID,input)then return false,"PERMISSION_DENIED"end
 local data=guildData(nil,true);if not data then return false,"NO_GUILD"end;local current=input.id and data.rules[input.id];if current and tonumber(expectedRevision)~=current.revision or not current and expectedRevision~=nil and tonumber(expectedRevision)~=0 then return false,"CONFLICT"end
 local stamp=now();local id=current and current.id or GM:NewId("activity-rule");local enabled;if input.enabled~=nil then enabled=input.enabled==true else enabled=current and current.enabled or false end;local rule={id=id,enabled=enabled,name=trim(input.name~=nil and input.name or current and current.name),description=trim(input.description~=nil and input.description or current and current.description),eventType=input.eventType or current and current.eventType,points=tonumber(input.points~=nil and input.points or current and current.points),revision=(current and current.revision or 0)+1,createdAt=current and current.createdAt or stamp,updatedAt=stamp,effectiveFrom=stamp,createdByCharacterUUID=current and current.createdByCharacterUUID or who.characterUUID,updatedByCharacterUUID=who.characterUUID}
 local ok,reason=self:ValidateRule(rule);if not ok then log("WARN","validation","Invalid Activity Points rule rejected",{reason=reason});return false,reason end
 if current then data.ruleHistory[current.id]=data.ruleHistory[current.id]or{};data.ruleHistory[current.id][current.revision]=copy(current)end;data.rules[id]=rule;advanceRevision(data,who.characterUUID,stamp);data.cache={};local saved,result=store():PutGuild(data.guildId,data);if not saved then return false,result end
 if HolyStorm.Sync then HolyStorm.Sync:Publish("guildActivityPoints",data.guildId,"ACTIVITY_POINTS_RULE_UPDATED")end;log("INFO","rules",current and"Activity Points rule changed"or"Activity Points rule created",{ruleId=id,revision=rule.revision,actor=who.characterUUID});HolyStorm.Events:Emit("HS_GUILD_ACTIVITY_POINTS_UPDATED",data.guildId);self:ReconcileGuild(data.guildId);return true,copy(rule)
end
function Points:SetEnabled(id,enabled,expectedRevision)local data=guildData();local current=data and data.rules[id];if not current then return false,"NOT_FOUND"end;local draft=copy(current);draft.enabled=enabled==true;return self:SaveRule(draft,expectedRevision or current.revision)end
function Points:SetDecay(mode,intervalDays,amount)
 local who=GM:Actor();if not self:CanConfigure(who.accountUUID,who.characterUUID)then return false,"PERMISSION_DENIED"end
 if mode~="NONE"and mode~="FIXED"and mode~="PERCENT"then return false,"INVALID_DECAY_MODE"end;intervalDays=tonumber(intervalDays);amount=tonumber(amount);if not intervalDays or intervalDays%1~=0 or intervalDays<1 or intervalDays>3650 or not validAmount(amount)or mode=="PERCENT"and(amount<0 or amount>100)or mode=="FIXED"and amount<0 then return false,"INVALID_DECAY"end
 local data=guildData(nil,true);local stamp=now();data.decay={mode=mode,intervalDays=intervalDays,amount=amount,updatedAt=stamp,updatedByCharacterUUID=who.characterUUID};advanceRevision(data,who.characterUUID,stamp);data.cache={};local ok,result=store():PutGuild(data.guildId,data);if ok then self:InvalidateScore(data.guildId);HolyStorm.Sync:Publish("guildActivityPoints",data.guildId,"ACTIVITY_POINTS_DECAY_UPDATED");HolyStorm.Events:Emit("HS_GUILD_ACTIVITY_POINTS_UPDATED",data.guildId)end;return ok,ok and copy(data.decay)or result
end
function Points:AddEntry(entry)
 if entry.kind=="AUTOMATIC"then if store():HasEntry(entry.guildId,entry.entryId)then log("DEBUG","suppression","Duplicate Activity Points ledger entry suppressed",{entryId=entry.entryId});return true,"DUPLICATE"end;local ok,result=store():AppendEntry(entry.guildId,entry);if ok then self:InvalidateScore(entry.guildId,entry.accountUUID);log("INFO","ledger","Activity Points ledger entry generated",{entryId=entry.entryId,accountUUID=entry.accountUUID,characterUUID=entry.characterUUID,ruleId=entry.ruleId,amount=entry.amount})end;return ok,result end
 local data=guildData(entry.guildId,true);if not data then return false,"NO_GUILD"end;if data.ledger[entry.entryId]then log("DEBUG","suppression","Duplicate Activity Points ledger entry suppressed",{entryId=entry.entryId});return true,"DUPLICATE"end
 data.ledger[entry.entryId]=copy(entry);data.ledgerByAccount=data.ledgerByAccount or{};data.ledgerByAccount[entry.accountUUID]=data.ledgerByAccount[entry.accountUUID]or{};local ids=data.ledgerByAccount[entry.accountUUID];ids[#ids+1]=entry.entryId;table.sort(ids);if entry.kind=="MANUAL"then advanceRevision(data,entry.actorCharacterUUID,entry.generatedAt)end;data.cache[entry.accountUUID]=nil;local ok,result=store():PutGuild(data.guildId,data);if ok then self:InvalidateScore(data.guildId,entry.accountUUID);log("INFO","ledger","Activity Points ledger entry generated",{entryId=entry.entryId,accountUUID=entry.accountUUID,characterUUID=entry.characterUUID,ruleId=entry.ruleId,amount=entry.amount})end;return ok,result
end
function Points:ProcessActivityEvent(event,guildId,rules)
 if type(event)~="table"or not self.events[event.type]or type(event.eventId)~="string"or type(event.accountUUID)~="string"then return 0 end
 guildId=guildId or GM:GetGuildId();if not guildId then return 0 end;rules=rules or self:ListRules(guildId);local made=0;local occurredAt=tonumber(event.occurredAt or event.endedAt or event.startedAt);if not occurredAt then return 0 end
 for _,rule in ipairs(rules)do if rule.enabled and rule.eventType==event.type and occurredAt>rule.effectiveFrom then local entryId=stableId(guildId,event.eventId,rule.id,tostring(rule.revision));local entry={entryId=entryId,guildId=guildId,accountUUID=event.accountUUID,characterUUID=event.characterUUID,activityOccurrenceId=event.eventId,activityType=event.type,occurredAt=occurredAt,generatedAt=now(),ruleId=rule.id,ruleRevision=rule.revision,ruleName=rule.name,amount=rule.points,source="ACTIVITY",kind="AUTOMATIC",status="ACTIVE"};local ok=self:AddEntry(entry);if ok then made=made+1 end end end;return made
end
function Points:ReconcileAccount(accountUUID,guildId,rules)
 rules=rules or self:ListRules(guildId);local active=false;for _,rule in ipairs(rules)do if rule.enabled then active=true;break end end;if not active then return 0 end;local shard=HolyStorm.Data.GuildActivityStore:GetShard(accountUUID,guildId);local count=0;for _,event in pairs(shard and shard.details or{})do count=count+self:ProcessActivityEvent(event,guildId,rules)end
 -- Chat facts are persisted as private daily aggregates, so score each account/character/day summary once.
  for day,bucket in pairs(shard and shard.days or{})do for characterUUID,values in pairs(bucket.characters or{})do if(tonumber(values.guildChatCount)or 0)>0 then local occurredAt=tonumber(values.lastActivity)or tonumber(bucket.endAt)or 0;count=count+self:ProcessActivityEvent({eventId="chat:"..accountUUID..":"..day..":"..characterUUID,type="GUILD_CHAT",accountUUID=accountUUID,characterUUID=characterUUID,providerId="guild-chat",source="daily-aggregate",occurredAt=occurredAt,metadata={count=values.guildChatCount,aggregate=true}},guildId,rules)end end end
 return count
end
function Points:ReconcileGuild(guildId)local rules=self:ListRules(guildId);local active=false;for _,rule in ipairs(rules)do if rule.enabled then active=true;break end end;if not active then return 0 end;local n=0;for _,accountUUID in ipairs(HolyStorm.Data.GuildActivityStore:GetAccountIds(guildId))do n=n+self:ReconcileAccount(accountUUID,guildId,rules)end;return n end
function Points:ManualAdjustment(accountUUID,characterUUID,amount,reason)
 local who=GM:Actor();if not self:CanAdjust(who.accountUUID,who.characterUUID,{accountUUID=accountUUID,characterUUID=characterUUID})then return false,"PERMISSION_DENIED"end;amount=tonumber(amount);reason=trim(reason);if not accountUUID or not validAmount(amount)or amount==0 then return false,"INVALID_ADJUSTMENT"end;if characterUUID and GM:GetAccountUUID(characterUUID)~=accountUUID then return false,"CHARACTER_ACCOUNT_MISMATCH"end;if reason==""or#reason>500 then return false,"REASON_REQUIRED"end
 local at=now();local id=stableId(GM:GetGuildId(),"manual",GM:NewId("adjust"));local entry={entryId=id,guildId=GM:GetGuildId(),accountUUID=accountUUID,characterUUID=characterUUID,occurredAt=at,generatedAt=at,amount=amount,kind="MANUAL",source="MANUAL_ADJUSTMENT",reason=reason,actorAccountUUID=who.accountUUID,actorCharacterUUID=who.characterUUID,status="ACTIVE"};local ok,result=self:AddEntry(entry);if ok then HolyStorm.Sync:Publish("guildActivityPoints",entry.guildId,"ACTIVITY_POINTS_MANUAL_ADJUSTMENT");HolyStorm.Events:Emit("HS_GUILD_ACTIVITY_POINTS_UPDATED",entry.guildId);log("INFO","manual","Manual Activity Points adjustment",{accountUUID=accountUUID,amount=amount,actor=who.characterUUID})end;return ok,ok and entry or result
end
function Points:CanAdjust(accountUUID,characterUUID,target)return authorized("guild-activity-points-adjust",accountUUID,characterUUID,target)end
function Points:GetLedger(accountUUID,options)
 options=options or{};if not self:CanView(options.viewerAccount,options.viewerCharacter,{accountUUID=accountUUID})then return{}end;local state=store():GetScoreData(options.guildId or GM:GetGuildId(),accountUUID);local out=state and state.entries or{};table.sort(out,function(a,b)return a.occurredAt>b.occurredAt or a.occurredAt==b.occurredAt and a.entryId<b.entryId end);local limit=math.max(1,math.min(500,tonumber(options.limit)or 100));while#out>limit do table.remove(out)end;return out
end
local function entryValue(entry,decay,at)
 local periods=math.max(0,math.floor((at-(tonumber(entry.occurredAt)or at))/(math.max(1,tonumber(decay.intervalDays)or 30)*86400)));local value=tonumber(entry.amount)or 0;if decay.mode=="FIXED"then local reduction=math.abs(tonumber(decay.amount)or 0)*periods;if value>0 then return math.max(0,value-reduction)elseif value<0 then return math.min(0,value+reduction)end elseif decay.mode=="PERCENT"then local factor=math.max(0,1-(tonumber(decay.amount)or 0)/100)^periods;return value*factor end;return value
end
function Points:GetScore(accountUUID,evaluationTime,guildId)
 if not self:CanView(nil,nil,{accountUUID=accountUUID})then return nil,"PERMISSION_DENIED"end;local at=tonumber(evaluationTime)or now();local state=store():GetScoreData(guildId or GM:GetGuildId(),accountUUID);if not state then return{raw=0,effective=0,at=at}end;local byGuild=self.scoreCache[guildId or GM:GetGuildId()]or{};self.scoreCache[guildId or GM:GetGuildId()]=byGuild;local byAccount=byGuild[accountUUID]or{};byGuild[accountUUID]=byAccount;local cacheKey=state.decay.mode=="NONE"and"NONE"or tostring(at);local cached=byAccount[cacheKey];if cached then local result=copy(cached);result.at=at;return result end;local raw,effective=0,0;for _,entry in ipairs(state.entries)do if entry.status~="REVERSED"then raw=raw+(tonumber(entry.amount)or 0);effective=effective+entryValue(entry,state.decay,at)end end;local result={raw=raw,effective=effective,at=at};byAccount[cacheKey]=copy(result);return result
end
function Points:Rebuild(accountUUID,guildId)
 local data=guildData(guildId);if not data then return false,"NO_GUILD"end;local score,reason=self:GetScore(accountUUID,now(),guildId);if not score then log("ERROR","rebuild","Activity Points score rebuild failed",{accountUUID=accountUUID,reason=reason});return false,reason end;data.cache[accountUUID]={raw=score.raw,effective=score.effective,evaluatedAt=score.at,ledgerRevision=data.revision};local ok,result=store():PutGuild(data.guildId,data);return ok,ok and copy(data.cache[accountUUID])or result
end
function Points:ValidateGuild(data,meta,id)
 if type(data)~="table"or data.schemaVersion~=1 or data.guildId~=id or id~=GM:GetGuildId()or type(data.rules)~="table"or type(data.ruleHistory)~="table"or type(data.revisionHistory)~="table"or type(data.ledger)~="table"or type(data.ledgerByAccount)~="table"or type(data.decay)~="table"or type(data.revision)~="number"or tonumber(data.revision)~=tonumber(meta.version)or data.updatedByCharacterUUID~=meta.owner or data.authorityCharacterUUID~=meta.origin or data.revisionID~=meta.revisionID or data.previousRevisionID~=meta.previousRevisionID or #data.revisionHistory~=data.revision-1 or(data.revision>1 and data.revisionHistory[#data.revisionHistory]~=data.previousRevisionID)then return false end
 local seenRevisions={};for _,revisionID in ipairs(data.revisionHistory)do if type(revisionID)~="string"or revisionID==""or seenRevisions[revisionID]then return false end;seenRevisions[revisionID]=true end;if type(data.revisionID)~="string"or data.revisionID==""or seenRevisions[data.revisionID]then return false end
 for key,rule in pairs(data.rules)do if key~=rule.id or not self:ValidateRule(rule)then return false end end;local indexed={};for accountUUID,ids in pairs(data.ledgerByAccount)do if type(accountUUID)~="string"or type(ids)~="table"then return false end;for _,entryId in ipairs(ids)do local entry=data.ledger[entryId];if not entry or entry.accountUUID~=accountUUID or indexed[entryId]then return false end;indexed[entryId]=true end end;for idValue,entry in pairs(data.ledger)do if idValue~=entry.entryId or type(entry.accountUUID)~="string"or not validAmount(entry.amount)or type(entry.occurredAt)~="number"or(entry.kind~="MANUAL"and entry.kind~="AUTOMATIC")or not indexed[idValue]then return false end end;return true
end
function Points:GetMetadata(guildId)local data=guildData(guildId);return data and data.revision>0 and{objectId=data.guildId,owner=data.updatedByCharacterUUID or data.authorityCharacterUUID,origin=data.authorityCharacterUUID or data.updatedByCharacterUUID,version=data.revision,updatedAt=data.updatedAt,guildId=data.guildId,schemaVersion=1,revisionID=data.revisionID,previousRevisionID=data.previousRevisionID}or nil end
function Points:ListMetadata(since)local meta=self:GetMetadata();return meta and meta.updatedAt>(tonumber(since)or 0)and{meta}or{}end
function Points:CanShare(meta,recipientGuid)return meta and meta.guildId==GM:GetGuildId()and recipientGuid and self:CanView(GM:GetAccountUUID(recipientGuid),recipientGuid)or false end
function Points:GetRecipients(meta)local out={};local guild=HolyStorm.Data.GuildStore:GetCurrent();for guid,member in pairs(guild and guild.roster or{})do if guid~=UnitGUID("player")and member.online and self:CanShare(meta,guid)then out[#out+1]={guid=guid,name=member.name}end end;return out end
function Points:AuthorizeSync(_,meta,senderId)
 local actorAccount=GM:GetAccountUUID(meta.owner);return actorAccount~=nil and senderId==meta.owner and meta.guildId==GM:GetGuildId()and(self:CanConfigure(actorAccount,meta.owner)or self:CanAdjust(actorAccount,meta.owner))
end
function Points:Import(id,incoming,meta)
 local current=guildData(id);if current then if incoming.revisionID==current.revisionID then return false,"DUPLICATE"end;if tonumber(incoming.revision)<tonumber(current.revision)then return false,"STALE"end;if tonumber(incoming.revision)==tonumber(current.revision)then log("ERROR","sync","Activity Points revision fork rejected",{guildId=id,localRevision=current.revisionID,remoteRevision=incoming.revisionID});return false,"FORK"end;if incoming.revisionHistory[tonumber(current.revision)]~=current.revisionID then return false,"MISSING_PREDECESSOR"end elseif tonumber(incoming.revision)<1 then return false,"MISSING_BASELINE"end;local ok,result=store():PutGuild(id,copy(incoming));if ok then self:InvalidateScore(id);log("INFO","sync","Activity Points revision synchronized",{guildId=id,revision=incoming.revision,revisionID=incoming.revisionID});HolyStorm.Events:Emit("HS_GUILD_ACTIVITY_POINTS_SYNCED",id);self:ReconcileGuild(id)end;return ok,result
end
function Points:Initialize()
 if self.initialized then return true end;self.initialized=true
 HolyStorm.Sync:RegisterDomain("guildActivityPoints",{freshness="revision-chain",getMetadata=function(id)return Points:GetMetadata(id)end,listMetadata=function(since)return Points:ListMetadata(since)end,export=function(id)return guildData(id)end,validate=function(payload,meta,id)return Points:ValidateGuild(payload,meta,id)end,authorize=function(...)return Points:AuthorizeSync(...)end,import=function(...)return Points:Import(...)end,canShare=function(...)return Points:CanShare(...)end,getRecipients=function(...)return Points:GetRecipients(...)end,updateEvent="HS_GUILD_ACTIVITY_POINTS_SYNCED",priority=77})
 HolyStorm.Events:Register("HS_GUILD_ACTIVITY_UPDATED","activity-points-facts",function(_,accountUUID,change)
  if type(change)~="table"then Points:ReconcileAccount(accountUUID);return end
  if change.kind=="DETAIL"and type(change.event)=="table"then Points:ProcessActivityEvent(change.event)
  elseif change.kind=="CHAT_AGGREGATES"then for _,event in ipairs(change.events or{})do Points:ProcessActivityEvent(event)end
  elseif change.kind~="STATE"then Points:ReconcileAccount(accountUUID)end
 end)
 HolyStorm.Events:Register("HS_GUILD_ACTIVITY_SYNCED","activity-points-facts",function(_,accountUUID)Points:ReconcileAccount(accountUUID)end)
 HolyStorm.Events:Register("HS_GUILD_ACTIVITY_POINTS_SYNCED","activity-points-sync",function(_,guildId)Points:ReconcileGuild(guildId)end)
 self:ReconcileGuild();return true
end
function Points:BuildAdmin(parent)
 local C=HolyStorm.UIComponents;local L=LibStub("AceLocale-3.0"):GetLocale("Holy_Storm_GuildRoster")
 local scroll=C:CreateScrollContainer(parent);local frame=scroll.frame;local column=C:CreateColumn(scroll.content,{frame=scroll.content,gap=8,padding=8,autoHeight=true})
 local function labeled(host,text,control)
  local field=C:CreateLabeledField(host,text,control);return field
 end
 local rules=C:CreateSection(scroll.content,{title=L["ACTIVITY_POINTS_RULES"],gap=6,padding=4});rules.frame:SetHeight(225)
 local ruleName=C:CreateEditBox(rules.content,{height=26});local points=C:CreateEditBox(rules.content,{height=26});local event=HolyStorm.PolicyUI:CreateSelector(rules.content,220,function()local items={};for _,id in ipairs({"ONLINE_SESSION","GUILD_CHAT","RAID_ENCOUNTER","MYTHICPLUS_RUN","EVENT_ATTENDANCE"})do items[#items+1]={value=id,label=L["GUILD_ACTIVITY_TYPE_"..id]}end;return items end,function(value)self.adminEventType=value end)
 self.adminEventType=self.adminEventType or"MYTHICPLUS_RUN";event:SetValue(self.adminEventType,L["GUILD_ACTIVITY_TYPE_"..self.adminEventType])
 local ruleFields=C:CreateRow(rules.content,{gap=8,padding=2});ruleFields:Add(labeled(ruleFields.frame,L["ACTIVITY_POINTS_RULE_NAME"],ruleName),{weight=2,minWidth=180});ruleFields:Add(labeled(ruleFields.frame,L["ACTIVITY_POINTS_POINTS"],points),{weight=1,minWidth=120});ruleFields:Add(labeled(ruleFields.frame,L["GUILD_ACTIVITY_TYPE"],event),{weight=2,minWidth=220});rules:Add(ruleFields,{height=66})
 local ruleActions=C:CreateRow(rules.content,{gap=8,padding=2});local save=C:CreateButton(ruleActions.frame,{text=L["GUILD_SAVE"],width=100,onClick=function()local selected=self.adminSelectedRule;local input={name=ruleName.edit:GetText(),description=selected and selected.description or"",eventType=self.adminEventType,points=tonumber(points.edit:GetText()),enabled=true};if selected then input.id=selected.id;input.enabled=selected.enabled;self:SaveRule(input,selected.revision)else self:SaveRule(input)end;self:RefreshAdmin()end});ruleActions:Add(save,{width=110});local enable=C:CreateButton(ruleActions.frame,{text=L["ACTIVITY_POINTS_ENABLE_DISABLE"],width=155,onClick=function()local selected=self.adminSelectedRule;if selected then self:SetEnabled(selected.id,not selected.enabled,selected.revision);self.adminSelectedRule=nil;self:RefreshAdmin()end end});ruleActions:Add(enable,{width=165});self.adminEnableButton=enable;rules:Add(ruleActions,{height=32})
 local listing=C:CreateTable(rules.content,{emptyText=L["ACTIVITY_POINTS_NO_RULES"],columns={{id="name",weight=1,minWidth=140,title=L["ACTIVITY_POINTS_RULES"],value=function(rule)return rule.name end},{id="eventType",width=150,title=L["GUILD_ACTIVITY_TYPE"],value=function(rule)return L["GUILD_ACTIVITY_TYPE_"..rule.eventType]end},{id="points",width=70,title=L["ACTIVITY_POINTS_POINTS"],align="RIGHT"},{id="revision",width=85,title=L["ACTIVITY_POINTS_REVISION"],align="RIGHT"},{id="enabled",width=75,title=L["ACTIVITY_POINTS_ENABLED"],value=function(rule)return rule.enabled and L["ACTIVITY_POINTS_YES"]or L["ACTIVITY_POINTS_NO"]end}},onRowClick=function(rule)self.adminSelectedRule=rule;ruleName:SetText(rule.name);points:SetText(tostring(rule.points));self.adminEventType=rule.eventType;event:SetValue(rule.eventType,L["GUILD_ACTIVITY_TYPE_"..rule.eventType]);self:RefreshAdmin()end});rules:Add(listing,{weight=1,min=110});self.adminTable=listing;column:Add(rules,{height=225})
 local decay=C:CreateSection(scroll.content,{title=L["ACTIVITY_POINTS_DECAY_SECTION"],gap=6,padding=4});decay.frame:SetHeight(125)
 local mode=HolyStorm.PolicyUI:CreateSelector(decay.content,200,function()return{{value="NONE",label=L["ACTIVITY_POINTS_DECAY_NONE"]},{value="FIXED",label=L["ACTIVITY_POINTS_DECAY_FIXED"]},{value="PERCENT",label=L["ACTIVITY_POINTS_DECAY_PERCENT"]}}end,function(value)self.adminDecayValue=value end);local interval=C:CreateEditBox(decay.content,{height=26});local amount=C:CreateEditBox(decay.content,{height=26})
 local decayFields=C:CreateRow(decay.content,{gap=8,padding=2});decayFields:Add(labeled(decayFields.frame,L["ACTIVITY_POINTS_DECAY_MODE"],mode),{weight=1,minWidth=150});decayFields:Add(labeled(decayFields.frame,L["ACTIVITY_POINTS_DECAY_INTERVAL"],interval),{weight=1,minWidth=140});decayFields:Add(labeled(decayFields.frame,L["ACTIVITY_POINTS_DECAY_AMOUNT"],amount),{weight=1,minWidth=140});decay:Add(decayFields,{height=66});local saveDecay=C:CreateButton(decay.content,{text=L["ACTIVITY_POINTS_SAVE_DECAY"],width=150,onClick=function()local data=guildData();self:SetDecay(self.adminDecayValue or(data and data.decay.mode)or"NONE",tonumber(interval.edit:GetText()),tonumber(amount.edit:GetText()));self:RefreshAdmin()end});decay:Add(saveDecay,{height=30});column:Add(decay,{height=125})
 local adjustment=C:CreateSection(scroll.content,{title=L["ACTIVITY_POINTS_MANUAL_ADJUSTMENT"],gap=6,padding=4});adjustment.frame:SetHeight(170)
 local target=HolyStorm.PolicyUI:CreateSelector(adjustment.content,240,function()return HolyStorm.PolicyUI:CharacterItems()or{}end,function(value,item)self.adminTargetAccount=GM:GetAccountUUID(value);self.adminTargetCharacter=value end);local manualAmount=C:CreateEditBox(adjustment.content,{height=26});local reason=C:CreateEditBox(adjustment.content,{height=26})
 local adjustFields=C:CreateRow(adjustment.content,{gap=8,padding=2});adjustFields:Add(labeled(adjustFields.frame,L["ACTIVITY_POINTS_TARGET"],target),{weight=2,minWidth=220});adjustFields:Add(labeled(adjustFields.frame,L["ACTIVITY_POINTS_ADJUSTMENT_AMOUNT"],manualAmount),{weight=1,minWidth=140});adjustFields:Add(labeled(adjustFields.frame,L["ACTIVITY_POINTS_MANUAL_ADJUSTMENT_REASON"],reason),{weight=2,minWidth=180});adjustment:Add(adjustFields,{height=66})
 local apply=C:CreateButton(adjustment.content,{text=L["ACTIVITY_POINTS_APPLY_ADJUSTMENT"],width=190,onClick=function()local ok=self:ManualAdjustment(self.adminTargetAccount,self.adminTargetCharacter,tonumber(manualAmount.edit:GetText()),reason.edit:GetText());if ok then manualAmount:SetText("");reason:SetText("")end end});adjustment:Add(apply,{height=30});column:Add(adjustment,{height=170})
 frame:HookScript("OnSizeChanged",function()scroll:Relayout();column:Relayout()end)
 scroll:SetContentHeight(225+125+170+24+16);scroll:Relayout();column:Relayout();self.adminDecayMode=mode;self.adminDecayInterval=interval;self.adminDecayAmount=amount;self.adminEventSelector=event
 self:RefreshAdmin();return frame
end
function Points:RefreshAdmin()
 if not self.adminTable then return end;self.adminTable:SetData(self:ListRules());if self.adminEnableButton then self.adminEnableButton:SetEnabled(self.adminSelectedRule~=nil)end;local data=guildData();if data then local mode=data.decay.mode or"NONE";self.adminDecayMode:SetValue(mode,L["ACTIVITY_POINTS_DECAY_"..mode]or mode);self.adminDecayInterval.edit:SetText(tostring(data.decay.intervalDays or 30));self.adminDecayAmount.edit:SetText(tostring(data.decay.amount or 0));self.adminDecayValue=mode end
end
GM.ActivityPoints=Points
