local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm")
local L=LibStub("AceLocale-3.0"):GetLocale("Holy_Storm_GuildRoster")
local GM=HolyStorm.GuildManagement
local Activity={version="1.0.0",schemaVersion=1,providers={},providerOrder={},initialized=false,enabled=false,pendingChat={},chatSeen={},cache={},detailLimit=2500,dayRetention=180*86400,weekRetention=520*7*86400,retention={ONLINE_SESSION=90*86400,RAID_ENCOUNTER=730*86400,MYTHICPLUS_RUN=730*86400,EVENT_ATTENDANCE=730*86400},groupPolicy={minimumGuildMembers=1,majorityRatio=.5}}
Activity.types={ONLINE_SESSION=true,GUILD_CHAT=true,RAID_ENCOUNTER=true,MYTHICPLUS_RUN=true,EVENT_ATTENDANCE=true}
local metrics={onlineDuration=true,guildChatCount=true,raidParticipation=true,encounterParticipation=true,mythicPlusParticipation=true,eventAttendance=true}
local function now()return HolyStorm.Utils.Now()end
local function copy(value)return HolyStorm.Utils.DeepCopy(value)end
local function store()return HolyStorm.Data.GuildActivityStore end
local function validId(value,limit)return type(value)=="string"and value~=""and#value<=(limit or 160)end
local function dayStart(timestamp)return math.floor((tonumber(timestamp)or 0)/86400)*86400 end
local function dayKey(timestamp)return date("!%Y-%m-%d",dayStart(timestamp))end
local function weekStart(timestamp)local mondayOffset=4*86400;return math.floor(((tonumber(timestamp)or 0)-mondayOffset)/(7*86400))*(7*86400)+mondayOffset end
local function add(target,source)for key in pairs(metrics)do target[key]=(tonumber(target[key])or 0)+(tonumber(source and source[key])or 0)end;target.lastActivity=math.max(tonumber(target.lastActivity)or 0,tonumber(source and source.lastActivity)or 0);target.lastSeen=math.max(tonumber(target.lastSeen)or 0,tonumber(source and source.lastSeen)or 0)end
local function blankAggregate(startAt,endAt)return{startAt=startAt,endAt=endAt,onlineDuration=0,guildChatCount=0,raidParticipation=0,encounterParticipation=0,mythicPlusParticipation=0,eventAttendance=0,lastActivity=0,lastSeen=0,characters={}}end
local function validAggregate(bucket,withCharacters)
 if type(bucket)~="table"or type(bucket.startAt)~="number"or type(bucket.endAt)~="number"or bucket.endAt<bucket.startAt or type(bucket.lastActivity)~="number"or bucket.lastActivity<0 or type(bucket.lastSeen)~="number"or bucket.lastSeen<0 then return false end;for metric in pairs(metrics)do local value=bucket[metric];if type(value)~="number"or value<0 or value>1e12 then return false end end
 if withCharacters then if type(bucket.characters)~="table"then return false end;local count=0;for guid,values in pairs(bucket.characters)do count=count+1;if count>256 or not validId(guid)or not validAggregate(values,false)then return false end end end;return true
end
local function logger(level,category,message,context)if HolyStorm.Logger then HolyStorm.Logger:Write(level,"GuildActivity",category,message,context)end end
local function hash(text,reverse)local value=5381;if reverse then for index=#text,1,-1 do value=(value*33+text:byte(index))%4294967291 end else for index=1,#text do value=(value*33+text:byte(index))%4294967291 end end;return value end
local function boundedMetadata(value,depth,count)
 depth=depth or 0;count=count or{value=0};if depth>3 then return nil,"METADATA_DEPTH"end;local kind=type(value);if kind=="nil"or kind=="boolean"then return value elseif kind=="number"then if value==value and math.abs(value)<1e15 then return value end;return nil,"METADATA_NUMBER"elseif kind=="string"then if#value<=200 then return value end;return nil,"METADATA_STRING"elseif kind~="table"then return nil,"METADATA_TYPE"end
 local out={};for key,child in pairs(value)do count.value=count.value+1;if count.value>48 then return nil,"METADATA_SIZE"end;if(type(key)~="string"and type(key)~="number")or type(key)=="string"and#key>48 then return nil,"METADATA_KEY"end;local normalized,reason=boundedMetadata(child,depth+1,count);if reason then return nil,reason end;out[key]=normalized end;return out
end
local function typeSet(values)local out={};for _,value in ipairs(type(values)=="table"and values or{})do if Activity.types[value]then out[value]=true end end;return out end

function Activity:DeterministicId(kind,... )local values={...};for index,value in ipairs(values)do values[index]=tostring(value or"")end;local seed=kind.."\031"..table.concat(values,"\031");return string.format("act-%s-%08x%08x",kind:lower():gsub("_","-"),hash(seed),hash(seed,true))end
function Activity:NewShard(accountUUID,characterUUID,guildId)
 return{schemaVersion=1,guildId=guildId,accountUUID=accountUUID,originCharacterUUID=characterUUID,ownerCharacterUUID=characterUUID,lastWriterCharacterUUID=characterUUID,revision=0,updatedAt=0,lastActivity=0,lastSeen=0,characters={},details={},days={},weeks={},lifetime=blankAggregate(0,0),openSession=nil,lastCompactedAt=0}
end
function Activity:ValidateEvent(entry)
 if type(entry)~="table"or entry.schemaVersion~=1 or not validId(entry.eventId)or not self.types[entry.type]or not validId(entry.accountUUID)or not validId(entry.characterUUID)or not validId(entry.providerId,64)or not validId(entry.source,64)then return false,"INVALID_EVENT_IDENTITY"end
 local timestamp=entry.occurredAt or entry.endedAt or entry.startedAt;if type(timestamp)~="number"or timestamp<=0 then return false,"INVALID_EVENT_TIME"end
 if entry.startedAt~=nil and(type(entry.startedAt)~="number"or entry.startedAt<=0)or entry.endedAt~=nil and(type(entry.endedAt)~="number"or entry.endedAt<(entry.startedAt or entry.endedAt))then return false,"INVALID_EVENT_RANGE"end
 if entry.type=="ONLINE_SESSION"and(type(entry.startedAt)~="number"or type(entry.endedAt)~="number"or type(entry.duration)~="number"or entry.duration<0 or entry.duration>31*86400 or(entry.status~="CLOSED"and entry.status~="RECOVERED"))then return false,"INVALID_ONLINE_SESSION"end
 if entry.type=="RAID_ENCOUNTER"and(not validId(entry.occurrenceId)or type(entry.metadata and entry.metadata.encounterId)~="number"or type(entry.metadata.success)~="boolean")then return false,"INVALID_RAID_EVENT"end
 if entry.type=="MYTHICPLUS_RUN"and(not validId(entry.occurrenceId)or type(entry.metadata and entry.metadata.challengeMapId)~="number"or type(entry.metadata.keystoneLevel)~="number")then return false,"INVALID_MYTHICPLUS_EVENT"end
 if entry.type=="EVENT_ATTENDANCE"and(not validId(entry.occurrenceId)or not validId(entry.metadata and entry.metadata.attendanceState,48))then return false,"INVALID_ATTENDANCE_EVENT"end
 local normalized,reason=boundedMetadata(entry.metadata or{});if reason then return false,reason end;entry.metadata=normalized;return true
end
function Activity:ValidateShard(shard)
 if type(shard)~="table"or shard.schemaVersion~=1 or not validId(shard.guildId)or not validId(shard.accountUUID)or not validId(shard.originCharacterUUID)or not validId(shard.ownerCharacterUUID)or not validId(shard.lastWriterCharacterUUID)or type(shard.revision)~="number"or shard.revision<1 or type(shard.updatedAt)~="number"or shard.updatedAt<=0 or type(shard.lastActivity)~="number"or shard.lastActivity<0 or type(shard.lastSeen)~="number"or shard.lastSeen<0 or type(shard.lastCompactedAt)~="number"or shard.lastCompactedAt<0 or type(shard.details)~="table"or type(shard.days)~="table"or type(shard.weeks)~="table"or type(shard.lifetime)~="table"or type(shard.characters)~="table"then return false,"INVALID_ACTIVITY_SHARD"end
 local characterCount=0;for guid,value in pairs(shard.characters)do characterCount=characterCount+1;if characterCount>256 or not validId(guid)or type(value)~="number"or value<0 then return false,"INVALID_ACTIVITY_CHARACTERS"end end
 local count=0;for id,event in pairs(shard.details)do count=count+1;if count>self.detailLimit or id~=event.eventId then return false,"INVALID_ACTIVITY_DETAILS"end;local ok,reason=self:ValidateEvent(event);if not ok then return false,reason end;if event.accountUUID~=shard.accountUUID then return false,"ACTIVITY_ACCOUNT_MISMATCH"end end
 for index,collection in ipairs({shard.days,shard.weeks})do local bucketCount=0;for key,bucket in pairs(collection)do bucketCount=bucketCount+1;if bucketCount>(index==1 and 400 or 540)or not validId(key,64)or not validAggregate(bucket,true)then return false,"INVALID_ACTIVITY_BUCKET"end end end;if not validAggregate(shard.lifetime,true)then return false,"INVALID_ACTIVITY_LIFETIME"end
 if shard.openSession then local open=shard.openSession;if not validId(open.sessionId)or not validId(open.characterUUID)or type(open.startedAt)~="number"or open.startedAt<=0 or type(open.lastObservedAt)~="number"or open.lastObservedAt<open.startedAt or open.status~="OPEN"then return false,"INVALID_OPEN_SESSION"end end
 return true
end
function Activity:BuildSummary(shard)local lifetime=copy(shard.lifetime);lifetime.characters=nil;return{schemaVersion=1,guildId=shard.guildId,accountUUID=shard.accountUUID,referenceCharacterUUID=(HolyStorm.TwinkCore and HolyStorm.TwinkCore:GetAccountMain(shard.accountUUID))or shard.ownerCharacterUUID,originCharacterUUID=shard.originCharacterUUID,ownerCharacterUUID=shard.ownerCharacterUUID,revision=shard.revision,updatedAt=shard.updatedAt,lastActivity=shard.lastActivity,lastSeen=shard.lastSeen,characters=copy(shard.characters),lifetime=lifetime,openSession=shard.openSession and{characterUUID=shard.openSession.characterUUID,startedAt=shard.openSession.startedAt,lastObservedAt=shard.openSession.lastObservedAt,status="OPEN"}or nil}end
function Activity:Invalidate(accountUUID)for key in pairs(self.cache)do if key:find("\031"..tostring(accountUUID).."\031",1,true)then self.cache[key]=nil end end;HolyStorm.Events:Emit("HS_GUILD_ACTIVITY_UPDATED",accountUUID)end
function Activity:CommitShard(shard,reason,publish,writerCharacterUUID)
 local compacted=self:CompactShard(shard,now());shard.revision=(tonumber(shard.revision)or 0)+1;shard.updatedAt=now();shard.lastWriterCharacterUUID=writerCharacterUUID or UnitGUID("player")or shard.lastWriterCharacterUUID;shard.ownerCharacterUUID=shard.lastWriterCharacterUUID
 local valid,validationReason=self:ValidateShard(shard);if not valid then logger("WARN","validation","Activity shard rejected",{accountUUID=shard.accountUUID,reason=validationReason,activityReason=reason});return false,validationReason end
 local ok,result=store():PutShard(shard,self:BuildSummary(shard));if not ok then return false,result end;if compacted then logger("INFO","compaction","Activity history compacted",{accountUUID=shard.accountUUID,revision=shard.revision})end;self:Invalidate(shard.accountUUID);if publish~=false and HolyStorm.Sync then HolyStorm.Sync:Publish("guildActivity",shard.accountUUID,reason or(compacted and"ACTIVITY_COMPACTED"or"ACTIVITY_UPDATED"))end;return true,shard
end
function Activity:GetOrCreateLocalShard(characterUUID)
 local accountUUID=GM:GetAccountUUID(characterUUID)or GM:GetLocalAccountUUID();local guildId=GM:GetGuildId();if not accountUUID or not guildId then return nil,"MISSING_IDENTITY"end;local shard=store():GetShard(accountUUID,guildId)or self:NewShard(accountUUID,characterUUID,guildId);return shard
end
function Activity:GetDay(shard,timestamp)
 local key=dayKey(timestamp);local bucket=shard.days[key];if not bucket then local startAt=dayStart(timestamp);bucket=blankAggregate(startAt,startAt+86400-1);shard.days[key]=bucket end;return bucket
end
function Activity:AddMetric(shard,timestamp,characterUUID,values)
 local bucket=self:GetDay(shard,timestamp);add(bucket,values);bucket.characters=type(bucket.characters)=="table"and bucket.characters or{};local character=bucket.characters[characterUUID]or blankAggregate(bucket.startAt,bucket.endAt);add(character,values);bucket.characters[characterUUID]=character;add(shard.lifetime,values);shard.lifetime.characters=type(shard.lifetime.characters)=="table"and shard.lifetime.characters or{};local lifetimeCharacter=shard.lifetime.characters[characterUUID]or blankAggregate(0,0);add(lifetimeCharacter,values);shard.lifetime.characters[characterUUID]=lifetimeCharacter;shard.characters[characterUUID]=math.max(tonumber(shard.characters[characterUUID])or 0,tonumber(values.lastActivity)or timestamp);shard.lastActivity=math.max(tonumber(shard.lastActivity)or 0,tonumber(values.lastActivity)or timestamp);shard.lastSeen=math.max(tonumber(shard.lastSeen)or 0,tonumber(values.lastSeen)or 0)
end
function Activity:AddOnlineDuration(shard,characterUUID,startAt,endAt)
 local cursor=startAt;while cursor<endAt do local boundary=dayStart(cursor)+86400;local finish=math.min(endAt,boundary);self:AddMetric(shard,cursor,characterUUID,{onlineDuration=math.max(0,finish-cursor),lastActivity=finish,lastSeen=finish});cursor=finish end
end
function Activity:AddEventToShard(shard,event)
 if shard.details[event.eventId]then return false,"DUPLICATE"end;shard.details[event.eventId]=copy(event);local at=event.occurredAt or event.endedAt or event.startedAt;local values={lastActivity=at,lastSeen=at}
 if event.type=="ONLINE_SESSION"then self:AddOnlineDuration(shard,event.characterUUID,event.startedAt,event.endedAt);return true
 elseif event.type=="RAID_ENCOUNTER"then values.raidParticipation=1;values.encounterParticipation=1
 elseif event.type=="MYTHICPLUS_RUN"then values.mythicPlusParticipation=1
 elseif event.type=="EVENT_ATTENDANCE"then values.eventAttendance=1 end
 self:AddMetric(shard,at,event.characterUUID,values);return true
end
function Activity:CompactShard(shard,at)
 at=at or now();if at-(tonumber(shard.lastCompactedAt)or 0)<86400 then return false end;local changed=false
 for id,event in pairs(shard.details)do local age=at-tonumber(event.occurredAt or event.endedAt or event.startedAt or at);local keep=self.retention[event.type]or 180*86400;if age>keep then shard.details[id]=nil;changed=true end end
 local detailCount=0;local ordered={};for id,event in pairs(shard.details)do detailCount=detailCount+1;ordered[#ordered+1]={id=id,at=tonumber(event.occurredAt or event.endedAt or event.startedAt)or 0}end;if detailCount>self.detailLimit then table.sort(ordered,function(a,b)return a.at<b.at or a.at==b.at and a.id<b.id end);for index=1,detailCount-self.detailLimit do shard.details[ordered[index].id]=nil;changed=true end end
 for key,bucket in pairs(shard.days)do if at-bucket.startAt>self.dayRetention then local startAt=weekStart(bucket.startAt);local weekKey="W:"..tostring(startAt);local week=shard.weeks[weekKey]or blankAggregate(startAt,startAt+7*86400-1);add(week,bucket);for guid,values in pairs(bucket.characters or{})do week.characters[guid]=week.characters[guid]or blankAggregate(week.startAt,week.endAt);add(week.characters[guid],values)end;shard.weeks[weekKey]=week;shard.days[key]=nil;changed=true end end
 for key,bucket in pairs(shard.weeks)do if at-bucket.startAt>self.weekRetention then shard.weeks[key]=nil;changed=true end end;shard.lastCompactedAt=at;return changed
end

function Activity:RegisterProvider(id,definition)
 if not validId(id,64)or type(definition)~="table"then return false,"INVALID_PROVIDER"end;for _,field in ipairs({"enable","disable","normalize","validate"})do if definition[field]~=nil and type(definition[field])~="function"then return false,"INVALID_PROVIDER_CALLBACK"end end;if self.providers[id]then return false,"PROVIDER_EXISTS"end;local types=typeSet(definition.types);if not next(types)then return false,"INVALID_PROVIDER_TYPES"end
 self.providers[id]={id=id,types=types,enable=definition.enable,disable=definition.disable,normalize=definition.normalize,validate=definition.validate,available=false};self.providerOrder[#self.providerOrder+1]=id;table.sort(self.providerOrder);if self.enabled then self:EnableProvider(id)end;HolyStorm.Events:Emit("HS_GUILD_ACTIVITY_PROVIDER_REGISTERED",id);return true
end
function Activity:EnableProvider(id)
 local provider=self.providers[id];if not provider then return false,"PROVIDER_NOT_FOUND"end;if provider.available then return true end;local available=true;if provider.enable then local ok,result=HolyStorm.Utils.SafeCall("guild-activity.provider.enable:"..id,provider.enable,self,id);available=ok and result~=false end;provider.available=available;HolyStorm.Events:Emit("HS_GUILD_ACTIVITY_PROVIDER_AVAILABILITY",id,available);return available
end
function Activity:DisableProvider(id)
 local provider=self.providers[id];if not provider then return false end;if provider.disable then HolyStorm.Utils.SafeCall("guild-activity.provider.disable:"..id,provider.disable,self,id)end;provider.available=false;HolyStorm.Events:Emit("HS_GUILD_ACTIVITY_PROVIDER_AVAILABILITY",id,false);return true
end
function Activity:UnregisterProvider(id)if not self.providers[id]then return false end;self:DisableProvider(id);self.providers[id]=nil;for index,value in ipairs(self.providerOrder)do if value==id then table.remove(self.providerOrder,index);break end end;HolyStorm.Events:Emit("HS_GUILD_ACTIVITY_PROVIDER_UNREGISTERED",id);return true end
function Activity:GetProviders()local out={};for _,id in ipairs(self.providerOrder)do local provider=self.providers[id];out[#out+1]={id=id,types=copy(provider.types),available=provider.available}end;return out end
function Activity:IsTypeAvailable(activityType)for _,provider in pairs(self.providers)do if provider.types[activityType]and provider.available then return true end end;return false end
function Activity:CaptureNow(providerId,activityType,payload)
 if not self.enabled then return false,"ACTIVITY_DISABLED"end;local provider=self.providers[providerId];if not provider or not provider.available or not provider.types[activityType]then return false,"PROVIDER_UNAVAILABLE"end;if activityType=="GUILD_CHAT"then return false,"AGGREGATE_ONLY"end;local event=payload;if provider.normalize then local ok,result,reason=HolyStorm.Utils.SafeCall("guild-activity.provider.normalize:"..providerId,provider.normalize,self,activityType,payload);if not ok or not result then logger("WARN","validation","Activity provider normalization rejected",{provider=providerId,activityType=activityType,reason=reason or result});return false,reason or"NORMALIZE_FAILED"end;event=result end
 event=copy(event);event.schemaVersion=1;event.providerId=providerId;event.source=event.source or providerId;local valid,reason;if type(payload)=="table"and((payload.capturedAccountUUID and event.accountUUID~=payload.capturedAccountUUID)or(payload.capturedCharacterUUID and event.characterUUID~=payload.capturedCharacterUUID))then valid,reason=false,"CAPTURE_IDENTITY_MISMATCH"elseif event.type~=activityType then valid,reason=false,"ACTIVITY_TYPE_MISMATCH"else valid,reason=self:ValidateEvent(event)end;if valid and provider.validate then local called,result,providerReason=HolyStorm.Utils.SafeCall("guild-activity.provider.validate:"..providerId,provider.validate,event);valid=called and result==true;reason=valid and nil or providerReason or result or"PROVIDER_VALIDATION_FAILED"end;if not valid then logger("WARN","validation","Activity event rejected",{provider=providerId,activityType=activityType,reason=reason,accountUUID=event.accountUUID,characterUUID=event.characterUUID});return false,reason end
 local shard,shardReason=self:GetOrCreateLocalShard(event.characterUUID);if not shard then return false,shardReason end;if shard.accountUUID~=event.accountUUID then return false,"ACCOUNT_MISMATCH"end;local added,addReason=self:AddEventToShard(shard,event);if not added then logger("DEBUG","deduplication","Duplicate Activity event suppressed",{provider=providerId,activityType=activityType,eventId=event.eventId,accountUUID=event.accountUUID});return false,addReason end;return self:CommitShard(shard,"ACTIVITY_"..activityType,nil,event.characterUUID)
end
function Activity:Submit(providerId,activityType,payload)
 if not self.enabled then return false,"ACTIVITY_DISABLED"end;local provider=self.providers[providerId];if not provider or not provider.available or not provider.types[activityType]then return false,"PROVIDER_UNAVAILABLE"end;if type(payload)~="table"then return false,"INVALID_PAYLOAD"end;local actor=GM:Actor();if not actor.accountUUID or not actor.characterUUID then return false,"MISSING_IDENTITY"end;payload=copy(payload);payload.capturedAccountUUID=actor.accountUUID;payload.capturedCharacterUUID=actor.characterUUID;local taskId=HolyStorm.Tasks:Queue("GuildActivity.Capture",{executionMode="MULTI",priority=65,triggerSource="ACTIVITY_"..activityType,metadata={providerId=providerId,activityType=activityType,payload=payload}});return taskId~=nil,taskId
end

function Activity:RecordGuildChat(characterUUID,timestamp,lineId)
 if not self.enabled or not self:IsTypeAvailable("GUILD_CHAT")then return false end;local accountUUID=GM:GetAccountUUID(characterUUID)or GM:GetLocalAccountUUID();if not accountUUID or not GM:GetGuildId()then return false end;if lineId~=nil then local key=tostring(lineId);if self.chatSeen[key]then return false end;self.chatSeen[key]=timestamp;local count=0;for seen,at in pairs(self.chatSeen)do count=count+1;if count>250 or timestamp-at>600 then self.chatSeen[seen]=nil end end end
 local key=dayKey(timestamp);self.pendingChat[accountUUID]=self.pendingChat[accountUUID]or{};local pending=self.pendingChat[accountUUID][key]or{count=0,timestamp=timestamp,characterUUID=characterUUID};pending.count=pending.count+1;pending.timestamp=math.max(pending.timestamp,timestamp);pending.characterUUID=characterUUID;self.pendingChat[accountUUID][key]=pending;HolyStorm.Tasks:Queue("GuildActivity.FlushChat",{debounce=20,cooldown=10,priority=70,triggerSource="CHAT_MSG_GUILD"});return true
end
function Activity:FlushChat()
 for accountUUID,days in pairs(self.pendingChat)do local shard=store():GetShard(accountUUID)or self:NewShard(accountUUID,GM:Actor().characterUUID,GM:GetGuildId());for _,pending in pairs(days)do self:AddMetric(shard,pending.timestamp,pending.characterUUID,{guildChatCount=pending.count,lastActivity=pending.timestamp,lastSeen=pending.timestamp});if shard.openSession and shard.openSession.characterUUID==pending.characterUUID then shard.openSession.lastObservedAt=math.max(shard.openSession.lastObservedAt or 0,pending.timestamp)end end;local ok=self:CommitShard(shard,"ACTIVITY_GUILD_CHAT");if not ok then return false end;self.pendingChat[accountUUID]=nil end;return true
end
function Activity:OpenSession(reason)
 if not self.enabled then return false,"ACTIVITY_DISABLED"end;local characterUUID=UnitGUID("player");if not characterUUID or not IsInGuild()then return false,"MISSING_IDENTITY"end;local shard,why=self:GetOrCreateLocalShard(characterUUID);if not shard then return false,why end;local stamp=now()
 if shard.openSession and self.currentSessionId==shard.openSession.sessionId and shard.openSession.characterUUID==characterUUID then shard.openSession.lastObservedAt=stamp;shard.lastSeen=math.max(shard.lastSeen or 0,stamp);return self:CommitShard(shard,"ACTIVITY_SESSION_CHECKPOINT",false)end
 if shard.openSession then local open=shard.openSession;local endAt=math.max(open.startedAt,tonumber(open.lastObservedAt)or open.startedAt);local event={schemaVersion=1,type="ONLINE_SESSION",eventId=self:DeterministicId("online",shard.accountUUID,open.sessionId),occurrenceId=open.sessionId,accountUUID=shard.accountUUID,characterUUID=open.characterUUID,providerId="online",source="wow-session",startedAt=open.startedAt,endedAt=endAt,occurredAt=endAt,duration=endAt-open.startedAt,status="RECOVERED",metadata={uncertain=true,recoveryReason=reason or"STALE_OPEN_SESSION"}};self:AddEventToShard(shard,event);logger("INFO","recovery","Recovered stale open Activity session",{accountUUID=shard.accountUUID,characterUUID=open.characterUUID,startedAt=open.startedAt,lastObservedAt=endAt})end
 shard.openSession={sessionId=GM:NewId("activity-session"),characterUUID=characterUUID,startedAt=stamp,lastObservedAt=stamp,status="OPEN"};self.currentSessionId=shard.openSession.sessionId;shard.lastSeen=math.max(shard.lastSeen or 0,stamp);shard.lastActivity=math.max(shard.lastActivity or 0,stamp);shard.characters[characterUUID]=stamp;return self:CommitShard(shard,"ACTIVITY_SESSION_OPEN")
end
function Activity:CloseSession(status,reason)
 local characterUUID=UnitGUID("player");local accountUUID=GM:GetAccountUUID(characterUUID)or GM:GetLocalAccountUUID();local shard=accountUUID and store():GetShard(accountUUID);local open=shard and shard.openSession;if not open then return false,"NO_OPEN_SESSION"end;local stamp=now();local recovered=status=="RECOVERED";local endAt=recovered and math.max(open.startedAt,tonumber(open.lastObservedAt)or open.startedAt)or math.max(open.startedAt,stamp);local event={schemaVersion=1,type="ONLINE_SESSION",eventId=self:DeterministicId("online",shard.accountUUID,open.sessionId),occurrenceId=open.sessionId,accountUUID=shard.accountUUID,characterUUID=open.characterUUID,providerId="online",source="wow-session",startedAt=open.startedAt,endedAt=endAt,occurredAt=endAt,duration=endAt-open.startedAt,status=recovered and"RECOVERED"or"CLOSED",metadata={uncertain=recovered,closeReason=reason or status or"PLAYER_LOGOUT"}};local added=self:AddEventToShard(shard,event);shard.openSession=nil;self.currentSessionId=nil;if not added then return false,"DUPLICATE"end;return self:CommitShard(shard,"ACTIVITY_SESSION_CLOSE")
end
function Activity:Shutdown(reason)self:FlushChat();self:CloseSession("CLOSED",reason);return true end

function Activity:SnapshotGuildGroup()
 local guild=HolyStorm.Data.GuildStore:GetCurrent();if not guild or type(guild.roster)~="table"then return{classification="UNKNOWN",groupSize=0,guildMembers=0}end;local units={};if IsInRaid and IsInRaid()then for index=1,(GetNumGroupMembers and GetNumGroupMembers()or 0)do units[#units+1]="raid"..index end elseif IsInGroup and IsInGroup()then units[1]="player";for index=1,math.max(0,(GetNumGroupMembers and GetNumGroupMembers()or 1)-1)do units[#units+1]="party"..index end else units[1]="player"end
 local size,guildMembers=0,0;for _,unit in ipairs(units)do local guid=UnitGUID(unit);if guid then size=size+1;if guild.roster[guid]then guildMembers=guildMembers+1 end end end;if size==0 then return{classification="UNKNOWN",groupSize=0,guildMembers=0}end;local classification;if guildMembers==size then classification="FULL_GUILD"elseif guildMembers>=self.groupPolicy.minimumGuildMembers and guildMembers/size>=self.groupPolicy.majorityRatio then classification="MAJORITY_GUILD"elseif guildMembers>=self.groupPolicy.minimumGuildMembers then classification="PARTIAL_GUILD"else classification="NOT_GUILD_RELEVANT"end;return{classification=classification,groupSize=size,guildMembers=guildMembers}
end
function Activity:IsGuildRelevant(group)return type(group)=="table"and group.guildMembers>=self.groupPolicy.minimumGuildMembers and group.classification~="UNKNOWN"and group.classification~="NOT_GUILD_RELEVANT"end

local function aggregateBucket(result,bucket,characterUUID)
 local source=characterUUID and bucket.characters and bucket.characters[characterUUID]or bucket;if not source then return end;add(result,source)
end
function Activity:GetAggregate(accountUUID,startAt,endAt,options)
 options=options or{};if not GM:Can("guild-activity-view",options.viewerAccount,options.viewerCharacter)then return nil,"PERMISSION_DENIED"end;local shard=store():GetShard(accountUUID,options.guildId);if not shard then return nil,"MISSING_ACTIVITY_DATA"end;startAt=tonumber(startAt)or 0;endAt=tonumber(endAt)or now();local cacheKey=table.concat({"aggregate",accountUUID,tostring(shard.revision),tostring(startAt),tostring(endAt),tostring(options.characterUUID or"")},"\031");if self.cache[cacheKey]then return copy(self.cache[cacheKey])end
 local result=blankAggregate(startAt,endAt);result.accountUUID=accountUUID;result.revision=shard.revision;result.approximate=false;if startAt<=0 and endAt>=now()then aggregateBucket(result,shard.lifetime,options.characterUUID)else for _,collection in ipairs({shard.days,shard.weeks})do for _,bucket in pairs(collection)do if bucket.endAt>=startAt and bucket.startAt<=endAt then aggregateBucket(result,bucket,options.characterUUID);if bucket.startAt<startAt or bucket.endAt>endAt or collection==shard.weeks then result.approximate=true end end end end end
 if shard.openSession and(not options.characterUUID or options.characterUUID==shard.openSession.characterUUID)then local from=math.max(startAt,shard.openSession.startedAt);local finish=math.min(endAt,now());if finish>from then result.onlineDuration=result.onlineDuration+(finish-from);result.lastSeen=math.max(result.lastSeen,finish);result.lastActivity=math.max(result.lastActivity,shard.openSession.startedAt)end end;self.cache[cacheKey]=copy(result);return result
end
function Activity:GetHistory(accountUUID,startAt,endAt,options)
 options=options or{};if not GM:Can("guild-activity-view",options.viewerAccount,options.viewerCharacter)then return nil,"PERMISSION_DENIED"end;local shard=store():GetShard(accountUUID,options.guildId);if not shard then return nil,"MISSING_ACTIVITY_DATA"end;startAt=tonumber(startAt)or 0;endAt=tonumber(endAt)or now();local out={};for _,event in pairs(shard.details)do local at=event.occurredAt or event.endedAt or event.startedAt;if at>=startAt and at<=endAt and(not options.activityType or event.type==options.activityType)and(not options.characterUUID or event.characterUUID==options.characterUUID)and(not options.providerId or event.providerId==options.providerId)then out[#out+1]=copy(event)end end
 if(not options.activityType or options.activityType=="GUILD_CHAT")and(not options.providerId or options.providerId=="guild-chat")then for key,bucket in pairs(shard.days)do if bucket.endAt>=startAt and bucket.startAt<=endAt then local characters=options.characterUUID and{[options.characterUUID]=bucket.characters and bucket.characters[options.characterUUID]}or bucket.characters or{};for guid,source in pairs(characters)do if source and(source.guildChatCount or 0)>0 then out[#out+1]={schemaVersion=1,eventId="chat:"..accountUUID..":"..key..":"..guid,type="GUILD_CHAT",accountUUID=accountUUID,characterUUID=guid,providerId="guild-chat",source="daily-aggregate",occurredAt=bucket.startAt,metadata={count=source.guildChatCount,aggregate=true}}end end end end end
 table.sort(out,function(a,b)return(a.occurredAt or a.endedAt or 0)>(b.occurredAt or b.endedAt or 0)end);local limit=math.max(1,math.min(500,tonumber(options.limit)or 200));while#out>limit do table.remove(out)end;return out
end
function Activity:GetOverview(days)
 if not GM:Can("guild-activity-view")then return{}end;days=tonumber(days)or 30;local endAt=now();local startAt=endAt-days*86400;local out={};for accountUUID,summary in pairs(store():GetSummaries())do local aggregate=self:GetAggregate(accountUUID,startAt,endAt);if aggregate then local main=(HolyStorm.TwinkCore and HolyStorm.TwinkCore:GetAccountMain(accountUUID))or summary.referenceCharacterUUID or summary.ownerCharacterUUID;out[#out+1]={accountUUID=accountUUID,characterUUID=main,lastActivity=summary.lastActivity,lastSeen=summary.lastSeen,onlineDuration=aggregate.onlineDuration,guildChatCount=aggregate.guildChatCount,raidParticipation=aggregate.raidParticipation,mythicPlusParticipation=aggregate.mythicPlusParticipation,characters=copy(summary.characters),openSession=summary.openSession,approximate=aggregate.approximate}end end;table.sort(out,function(a,b)return(a.lastActivity or 0)>(b.lastActivity or 0)end);return out
end

function Activity:GetMetadata(accountUUID)local summary=store():GetSummary(accountUUID);return summary and{objectId=accountUUID,owner=summary.ownerCharacterUUID,origin=summary.originCharacterUUID,version=summary.revision,updatedAt=summary.updatedAt,guildId=summary.guildId,accountUUID=summary.accountUUID,schemaVersion=1}end
function Activity:ListMetadata(since)local out={};for accountUUID,summary in pairs(store():GetSummaries())do if(summary.updatedAt or 0)>(tonumber(since)or 0)then out[#out+1]={objectId=accountUUID,owner=summary.ownerCharacterUUID,origin=summary.originCharacterUUID,version=summary.revision,updatedAt=summary.updatedAt,guildId=summary.guildId,accountUUID=summary.accountUUID,schemaVersion=1}end end;return out end
function Activity:CanShare(meta,recipientGuid)local permission="guild-activity-view";return recipientGuid~=nil and meta and meta.guildId==GM:GetGuildId()and GM:Can(permission,GM:GetAccountUUID(recipientGuid),recipientGuid,meta)or false end
function Activity:GetRecipients(meta)local out={};local guild=HolyStorm.Data.GuildStore:GetCurrent();for guid,member in pairs(guild and guild.roster or{})do if guid~=UnitGUID("player")and member.online and self:CanShare(meta,guid)then out[#out+1]={guid=guid,name=member.name}end end;return out end
function Activity:ValidateSync(shard,meta,id)local valid=self:ValidateShard(shard);return valid and meta.objectId==id and shard.accountUUID==id and shard.accountUUID==meta.accountUUID and shard.guildId==GM:GetGuildId()and shard.ownerCharacterUUID==meta.owner and shard.originCharacterUUID==meta.origin and tonumber(shard.revision)==tonumber(meta.version)end
function Activity:AuthorizeSync(shard,meta)local ownerAccount=GM:GetAccountUUID(meta.owner);return self:CanShare(meta,UnitGUID("player"))and ownerAccount~=nil and ownerAccount==shard.accountUUID end
function Activity:Import(id,shard,meta)local current=store():GetShard(id,shard.guildId);if current and tonumber(current.revision)>=tonumber(meta.version)then logger("DEBUG","sync","Stale Activity shard rejected",{accountUUID=id,localRevision=current.revision,remoteRevision=meta.version});return false,"STALE"end;shard=copy(shard);shard.receivedFrom=meta.receivedFrom;local ok,result=store():PutShard(shard,self:BuildSummary(shard));if ok then self:Invalidate(id);HolyStorm.Events:Emit("HS_GUILD_ACTIVITY_SYNCED",id,shard.revision)end;return ok,result end

function Activity:Initialize()
 if self.initialized then return true end;self.initialized=true
 HolyStorm.Tasks:RegisterTaskType("GuildActivity.Capture",{name=L["GUILD_ACTIVITY_TASK_CAPTURE"],localizedNameKey="GUILD_ACTIVITY_TASK_CAPTURE",module="GuildManagement",priority=65,executionMode="MULTI",execute=function(task)local data=task.metadata or{};return Activity:CaptureNow(data.providerId,data.activityType,data.payload)end})
 HolyStorm.Tasks:RegisterTaskType("GuildActivity.FlushChat",{name=L["GUILD_ACTIVITY_TASK_CHAT"],localizedNameKey="GUILD_ACTIVITY_TASK_CHAT",module="GuildManagement",priority=70,executionMode="UNIQUE",execute=function()return Activity:FlushChat()end})
 HolyStorm.Tasks:RegisterTaskType("GuildActivity.OpenSession",{name=L["GUILD_ACTIVITY_TASK_SESSION"],localizedNameKey="GUILD_ACTIVITY_TASK_SESSION",module="GuildManagement",priority=60,executionMode="UNIQUE",conditions={"PLAYER_LOGGED_IN","GUILD_AVAILABLE"},execute=function(task)return Activity:OpenSession(task.metadata and task.metadata.reason)end})
 HolyStorm.Sync:RegisterDomain("guildActivity",{getMetadata=function(id)return Activity:GetMetadata(id)end,listMetadata=function(since)return Activity:ListMetadata(since)end,export=function(id)return store():GetShard(id)end,validate=function(...)return Activity:ValidateSync(...)end,authorize=function(...)return Activity:AuthorizeSync(...)end,import=function(...)return Activity:Import(...)end,canShare=function(...)return Activity:CanShare(...)end,getRecipients=function(...)return Activity:GetRecipients(...)end,updateEvent="HS_GUILD_ACTIVITY_SYNCED",priority=78})
 return true
end
function Activity:Enable()
 self:Initialize();if self.enabled then return true end;self.enabled=true;for _,id in ipairs(self.providerOrder)do self:EnableProvider(id)end;return true
end
function Activity:Disable(reason)
 if not self.enabled then return true end;self:Shutdown(reason or"MODULE_DISABLED");for _,id in ipairs(self.providerOrder)do self:DisableProvider(id)end;self.enabled=false;return true
end
GM.Activity=Activity
