local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm")
local Store={schemaVersion=1}
local function copy(value)return HolyStorm.Utils.DeepCopy(value)end
local function validId(value)return type(value)=="string"and#value>0 and#value<=160 and value:match("^[%w_%.%-:]+$")~=nil end
function Store:GetGuildId()local guild=HolyStorm.Data.GuildStore:GetCurrent();return guild and guild.id end
function Store:GetRoot()local root=HolyStorm.db.global.achievements;if type(root)~="table"then root={guilds={},schemaVersion=self.schemaVersion};HolyStorm.db.global.achievements=root end;root.guilds=type(root.guilds)=="table"and root.guilds or{};return root end
function Store:GetGuild(guildId,create)guildId=guildId or self:GetGuildId();if not guildId then return nil end;local root=self:GetRoot();local state=root.guilds[guildId];if not state and create then state={guildId=guildId,schemaVersion=self.schemaVersion,definitions={},events={},meta={},updatedAt=0};root.guilds[guildId]=state end;if state then state.definitions=type(state.definitions)=="table"and state.definitions or{};state.events=type(state.events)=="table"and state.events or{};state.meta=type(state.meta)=="table"and state.meta or{}end;return state end
function Store:ObjectId(kind,id,guildId)return table.concat({guildId or self:GetGuildId()or"",kind,id},"\031")end
function Store:SplitObjectId(objectId)local guildId,kind,id=tostring(objectId or""):match("^(.-)\031([DE])\031(.+)$");return guildId,kind,id end
function Store:GetObject(objectId)local guildId,kind,id=self:SplitObjectId(objectId);local state=self:GetGuild(guildId);return state and(kind=="D"and state.definitions[id]or state.events[id]),state and state.meta[objectId] end
function Store:GetDefinition(id,guildId)local state=self:GetGuild(guildId);return state and state.definitions[id] end
function Store:GetDefinitions(guildId)local state=self:GetGuild(guildId);return state and state.definitions or{}end
function Store:GetEvents(guildId)local state=self:GetGuild(guildId);return state and state.events or{}end
function Store:GetMetadata(objectId)local _,meta=self:GetObject(objectId);return meta and copy(meta)end
function Store:ListMetadata(since,guildId)local state=self:GetGuild(guildId);local out={};for _,meta in pairs(state and state.meta or{})do if(tonumber(meta.updatedAt)or 0)>(tonumber(since)or 0)then out[#out+1]=copy(meta)end end;return out end
function Store:Put(kind,id,value,actor,remoteMeta,guildId)
 guildId=guildId or self:GetGuildId();if not guildId or(kind~="D"and kind~="E")or not validId(id)or type(value)~="table"then return false,"INVALID_OBJECT"end;local state=self:GetGuild(guildId,true);local objectId=self:ObjectId(kind,id,guildId);local current=state.meta[objectId];local version=remoteMeta and tonumber(remoteMeta.version)or((tonumber(current and current.version)or 0)+1);if remoteMeta and current and version<=(tonumber(current.version)or 0)then return false,"STALE_VERSION"end
 local clean=copy(value);if kind=="D"then state.definitions[id]=clean else state.events[id]=clean end;local updatedAt=remoteMeta and tonumber(remoteMeta.updatedAt)or HolyStorm.Utils.Now();state.meta[objectId]={objectId=objectId,owner=remoteMeta and remoteMeta.owner or actor,version=version,updatedAt=updatedAt,source=remoteMeta and"sync"or"achievement",direct=remoteMeta==nil or remoteMeta.direct==true};state.updatedAt=math.max(state.updatedAt or 0,updatedAt);HolyStorm.Events:Emit(kind=="D"and"HS_ACHIEVEMENT_DEFINITION_UPDATED"or"HS_ACHIEVEMENT_AWARDS_UPDATED",id,copy(clean),remoteMeta~=nil);return true,copy(state.meta[objectId])
end
function Store:Export(objectId)local object=self:GetObject(objectId);local guildId,kind,id=self:SplitObjectId(objectId);return object and{guildId=guildId,kind=kind,id=id,data=copy(object)}or nil end
function Store:GetAwardsFor(achievementId,recipientId,guildId)local latest={};for _,event in pairs(self:GetEvents(guildId))do if event.achievementID==achievementId then for _,award in ipairs(event.awards or{})do if not recipientId or award.recipientID==recipientId then local current=latest[award.awardID];local stamp=tonumber(award.revokedAt or award.awardedAt)or 0;local currentStamp=current and(tonumber(current.revokedAt or current.awardedAt)or 0)or-1;if not current or stamp>currentStamp or(stamp==currentStamp and award.status=="REVOKED"and current.status~="REVOKED")then latest[award.awardID]=award end end end end end;local out={};for _,award in pairs(latest)do out[#out+1]=award end;table.sort(out,function(a,b)return(a.revokedAt or a.awardedAt or 0)>(b.revokedAt or b.awardedAt or 0)end);return out end
function Store:IsEarned(achievementId,recipientId,guildId)for _,award in ipairs(self:GetAwardsFor(achievementId,recipientId,guildId))do if award.status=="AWARDED"then return true,award end end;return false end
HolyStorm.Data.AchievementStore=Store
