local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm")
local L=LibStub("AceLocale-3.0"):GetLocale("Holy_Storm_Dungeons")
local columns={{width=.43},{width=.16,align="RIGHT"},{width=.18,align="RIGHT"},{width=.23,align="RIGHT"}}
local summaryColumns={{width=.25},{width=.25},{width=.25},{width=.25}}
local function value(v)return v==nil and L["UNKNOWN"]or tostring(v)end
local function number(v)return tonumber(v)and string.format("%.1f",tonumber(v))or L["UNKNOWN"]end
local function hyperlink(kind,id,label)local text="|cff3fc7eb"..tostring(label).."|r";return id and("|Hhscharacter:"..kind..":"..tostring(id).."|h"..text.."|h")or text end
local function bestRun(dungeon)if type(dungeon)~="table"then return nil end;if type(dungeon.bestRun)=="table"then return dungeon.bestRun end;local best;local function consider(entry,overTime)if type(entry)~="table"then return end;local score=tonumber(entry.dungeonScore or entry.score or entry.seasonScore);local level=tonumber(entry.level or entry.bestLevel);if level and level>0 and(not best or(score or 0)>(best.score or 0)or((score or 0)==(best.score or 0)and level>(best.level or 0)))then best={level=level,score=score or 0,durationSec=tonumber(entry.durationSec),overTime=overTime==true or entry.overTime==true}end end;consider(dungeon.bestInTime,false);consider(dungeon.bestOverTime,true);for _,entry in pairs(type(dungeon.affixScores)=="table"and dungeon.affixScores or{})do consider(entry,type(entry)=="table"and entry.overTime)end;return best end
local function runResult(run)if type(run)~="table"then return L["UNKNOWN"]end;local duration=tonumber(run.durationSec);local result=L[run.overTime==true and"MYTHIC_OVERTIME"or"MYTHIC_IN_TIME"];if duration and SecondsToClock then result=result.." · "..SecondsToClock(duration,duration>=3600)end;return result end
local function refresh(view,context,definition)local C=HolyStorm.CharacterUI;local ok,reason=C:CanUseTab(definition);if not ok then C:SetView(view,L["DISPLAY_NAME"],{reason=="PERMISSION"and L["PERMISSION_DENIED"]or L["MODULE_DISABLED"]});return end;local snapshot,meta=C:GetSnapshot(context.characterUUID,"mythicPlus");local status=C:GetDataStatus(context.characterUUID,"mythicPlus");if not snapshot or next(snapshot)==nil then C:SetView(view,L["DISPLAY_NAME"],{L["NO_MYTHICPLUS"]},status);return end;local dungeons=type(snapshot.dungeons)=="table"and snapshot.dungeons or{};local lines={string.format(L["SEASON"],value(snapshot.seasonId or snapshot.seasonNumber)),{cells={L["COLUMN_DUNGEON"],L["BEST_KEY"],L["DUNGEON_SCORE"],L["BEST_RUN"]},columns=columns,style="header",maxWidth=1320}};local completed,bestLevel,bestScore=0;for _,d in pairs(dungeons)do if type(d)=="table"then local best=bestRun(d);local level=best and tonumber(best.level);if best and(level or tonumber(best.score)or tonumber(best.durationSec))then completed=completed+1;if level and(not bestLevel or level>bestLevel)then bestLevel=level end else best=nil end;local dungeonScore=tonumber(d.score);if dungeonScore and(not bestScore or dungeonScore>bestScore)then bestScore=dungeonScore end;local texture=(type(d.texture)=="string"or type(d.texture)=="number")and d.texture;local icon=texture and hyperlink("teleport",d.challengeMapId or 0,"|T"..texture..":18:18|t")or"";local dungeonName=(type(d.name)=="string"or type(d.name)=="number")and tostring(d.name)or L["UNKNOWN"];local name=(type(d.instanceId)=="string"or type(d.instanceId)=="number")and hyperlink("journal",d.instanceId,dungeonName)or dungeonName;lines[#lines+1]={cells={(icon~=""and(icon.." ")or"")..name,value(level),number(dungeonScore),runResult(best)},columns=columns,maxWidth=1320}end end;lines[#lines+1]="";lines[#lines+1]={cells={L["DUNGEONS_TOTAL"].."\n|cffffffff"..completed.." / "..#dungeons.."|r",L["BEST_RATING"].."\n|cffffffff"..number(bestScore).."|r",L["BEST_KEY"].."\n|cffffffff"..value(bestLevel).."|r",L["OVERALL_RATING"].."\n|cffffd100"..number(snapshot.overallScore).."|r"},columns=summaryColumns,style="summary",maxWidth=1320};C:SetView(view,L["DISPLAY_NAME"],lines,status,meta,{[1]="accent"})end
HolyStorm:RegisterCharacterTab("mythicPlus",{id="mythicPlus",order=30,label=L["DISPLAY_NAME"],labelKey="DISPLAY_NAME",icon="Interface\\Icons\\Achievement_ChallengeMode_Gold",permission="mythicplus-read",moduleId="mythicPlus",blocks={"mythicPlus"},events={"HS_MYTHICPLUS_UPDATED"},build=function(parent)return HolyStorm.CharacterUI:CreateTextView(parent)end,refresh=refresh})
HolyStorm:RegisterCharacterSummarySection("mythicPlus",{id="mythicPlus",order=30,render=function(context)local snapshot=HolyStorm.CharacterUI:GetSnapshot(context.characterUUID,"mythicPlus");return{label=L["DISPLAY_NAME"],tabId="mythicPlus",text="  "..(snapshot and(L["OVERALL_RATING"]..": "..number(snapshot.overallScore))or L["NO_MYTHICPLUS"])}end})
HolyStorm.pendingCharacterLinkHandlers=HolyStorm.pendingCharacterLinkHandlers or{};HolyStorm.pendingCharacterLinkHandlers.journal={onClick=function(id)if not(InCombatLockdown and InCombatLockdown())and EncounterJournal_OpenJournal then EncounterJournal_OpenJournal(nil,tonumber(id))end end,tooltip=function()GameTooltip:SetText(L["COLUMN_DUNGEON"]);GameTooltip:AddLine(L["OPEN_JOURNAL"],1,1,1,true)end};HolyStorm.pendingCharacterLinkHandlers.teleport={tooltip=function()GameTooltip:SetText(L["COLUMN_DUNGEON"]);GameTooltip:AddLine(L["TELEPORT_UNAVAILABLE"],1,1,1,true)end}
if HolyStorm.CharacterUI then for kind,definition in pairs(HolyStorm.pendingCharacterLinkHandlers)do HolyStorm.CharacterUI:RegisterLinkHandler(kind,definition)end end
