local addonVersion="3.5.0"
local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm")
local L=LibStub("AceLocale-3.0"):GetLocale("Holy_Storm")
local Sync={version=addonVersion,protocol=3,domains={},requests={},activeRequests={},heard={},heardAt={},sequence=0,maxOffers=100,knownOnline={},knownVersions={},fetchTailByPeer={},publishedVersions={},requestTimeout=60,presenceTimeout=300,cleanupTimer=nil,cleanupDue=nil,cleanupTaskId=nil,loginSessionId=nil,presencePublished=false,peerVersionReceived=false,outdatedNotified=false}
local function copy(v)return HolyStorm.Utils.DeepCopy(v)end
local function now()return HolyStorm.Utils.Now()end
local function validId(v)return type(v)=="string"and#v>0 and#v<=160 end
local function validDomain(v)return type(v)=="string"and#v>0 and#v<=64 and v:match("^[%w_%-]+$")~=nil end
local function key(domain,objectId)return domain.."\030"..tostring(objectId or"*")end
local function log(level,category,message,context,correlationId)HolyStorm.Logger:Write(level,"Sync",category,message,context,correlationId)end
local function playerName()return GetUnitName and GetUnitName("player",true)or UnitName and UnitName("player")or"Player"end
local function audience(channel,target)if target and target~=""then return target end;local labels={GUILD="Guild",RAID="Raid",PARTY="Party",INSTANCE_CHAT="Instance"};return labels[channel]or"Broadcast"end
local function receiver(channel)return channel=="WHISPER"and playerName()or audience(channel)end
local messageClasses={PRESENCE="discovery",DISCOVER="discovery",ANNOUNCE="metadata",OFFER="metadata",FETCH="request",PAYLOAD="payload",LIVE="payload"}
local function envelopeDiagnostics(envelope,channel,target,correlationId)local data=type(envelope.data)=="table"and envelope.data or{};local meta=type(data.metadata)=="table"and data.metadata or type(data.offers)=="table"and type(data.offers[1])=="table"and data.offers[1]or{};local objectId=data.objectId or meta.objectId;local characterUUID,blockType;if type(objectId)=="string"then characterUUID,blockType=objectId:match("^(.-)\031([^\031]+)$")end;local destination=audience(channel,target);return{direction="SEND",sender=playerName(),receiver=destination,target=target or destination,from=playerName(),to=destination,channel=channel,domain=envelope.domain,logicalObject=blockType or objectId,blockType=blockType,block=blockType,characterUUID=characterUUID,objectId=objectId,messageKind=envelope.kind,messageClass=messageClasses[envelope.kind]or"control",version=meta.version or data.version,revision=meta.revisionID or data.revisionID,reason=data.reason,requestId=data.requestId,correlationId=correlationId,originalOwner=meta.owner,relay=meta.owner and meta.owner~=UnitGUID("player")or false,retry=false}end
local function senderGuid(sender)return HolyStorm.Data.GuildStore:ResolveSenderGuid(sender)end
local function samePlayerName(a,b)if not a or not b then return false end;if Ambiguate then return Ambiguate(a,"none")==Ambiguate(b,"none")end;return a==b end
local function splitCharacterId(objectId)if type(objectId)~="string"then return nil end;return objectId:match("^(.-)\031([^\031]+)$")end
local function startupActive()return HolyStorm.Tasks and type(HolyStorm.Tasks.IsStartupActive)=="function" and HolyStorm.Tasks:IsStartupActive()or false end
local function startupPhase(domainId)
 if domainId=="permissions"or domainId=="character"or domainId=="twinks"then return 3 end
 return 4
end

function Sync:RegisterDomain(id,definition)
 if not validDomain(id)or type(definition)~="table"or type(definition.getMetadata)~="function"or type(definition.listMetadata)~="function"or type(definition.export)~="function"or type(definition.import)~="function"then return false,"INVALID_DOMAIN"end
 self.domains[id]={id=id,getMetadata=definition.getMetadata,listMetadata=definition.listMetadata,export=definition.export,import=definition.import,validate=definition.validate,authorize=definition.authorize,getChannel=definition.getChannel,updateEvent=definition.updateEvent,freshness=definition.freshness or"metadata",live=definition.live==true,catchUp=definition.catchUp~=false,priority=tonumber(definition.priority)or nil};return true
end
function Sync:GetDomain(id)return self.domains[id]end
function Sync:UnregisterDomain(id)if not self.domains[id]then return false end;self.domains[id]=nil;return true end
function Sync:NewRequestId()self.sequence=self.sequence+1;return string.format("%08X-%04X",now()%0xFFFFFFFF,self.sequence%0xFFFF)end
function Sync:GetNextCleanupAt()
 local due;local function include(value)if value and(not due or value<due)then due=value end end
 for _,request in pairs(self.requests)do include((tonumber(request.createdAt)or 0)+self.requestTimeout)end
 for _,at in pairs(self.heardAt)do include((tonumber(at)or 0)+self.requestTimeout)end
 for _,at in pairs(self.knownOnline)do include((tonumber(at)or 0)+self.presenceTimeout)end
 return due
end
function Sync:CancelCleanupTimer()if self.cleanupTimer then self.cleanupTimer:Cancel()end;self.cleanupTimer,self.cleanupDue=nil,nil end
function Sync:ScheduleCleanup()
 local due=self:GetNextCleanupAt();if not due then self:CancelCleanupTimer();if self.cleanupTaskId then HolyStorm.Tasks:Cancel(self.cleanupTaskId,"SYNC_STATE_CLEARED");self.cleanupTaskId=nil end;return false end
 if self.cleanupTaskId then return true end
 if self.cleanupTimer and self.cleanupDue==due then return true end
 self:CancelCleanupTimer();self.cleanupDue=due;self.cleanupTimer=C_Timer.NewTimer(math.max(0,due-now()),function()
  Sync.cleanupTimer,Sync.cleanupDue=nil,nil;local nextDue=Sync:GetNextCleanupAt()
  if nextDue and nextDue<=now()then Sync.cleanupTaskId=HolyStorm.Tasks:Queue("Sync.Cleanup",{priority=100,triggerSource="SYNC_STATE_EXPIRY"})else Sync:ScheduleCleanup()end
 end);return true
end
function Sync:QueueEnvelope(kind,domain,data,channel,target,priority,delay)
 local envelope={protocol=self.protocol,kind=kind,domain=domain,data=data,sentAt=now(),sender=UnitGUID("player")};self.correlationSerial=(self.correlationSerial or 0)+1;local correlationId=type(data)=="table"and data.requestId and("SYNC-"..data.requestId)or string.format("SYNC-%08X-%04X",now()%0xFFFFFFFF,self.correlationSerial%0xFFFF);local diagnostics=envelopeDiagnostics(envelope,channel,target,correlationId);return HolyStorm.Tasks:Queue("Sync.Send",{executionMode="MULTI",priority=priority or 70,delay=delay or 0,triggerSource="SYNC_"..kind,metadata={envelope=envelope,channel=channel,target=target,correlationId=correlationId,diagnostics=diagnostics}})
end
function Sync:SendNow(task)
 local m=task.metadata or{};local payload,err=HolyStorm.Serializer:Serialize(m.envelope);if not payload then log("WARN","validation","Sync envelope serialization failed",{error=err,messageKind=m.envelope and m.envelope.kind,domain=m.envelope and m.envelope.domain,correlationId=m.correlationId},m.correlationId);return false end
 local diagnostics=m.diagnostics or envelopeDiagnostics(m.envelope,m.channel,m.target,m.correlationId);local retryCount=tonumber(task.retryCount)or 0;diagnostics.bytes=#payload;diagnostics.serializedBytes=#payload;diagnostics.retry=retryCount>0;diagnostics.retryCount=retryCount;local sent,transmissionId=HolyStorm.Comms:Send(payload,m.channel,m.target,task.priority,diagnostics);diagnostics.transmissionId=transmissionId;if sent then if m.envelope and m.envelope.kind=="PRESENCE"and m.envelope.data and m.envelope.data.sessionId==self.loginSessionId then self.presencePublished=true;HolyStorm.Tasks:Queue("Sync.VersionNotice",{delay=2,priority=99,triggerSource="PRESENCE_PUBLISHED"})end;log("DEBUG",string.lower(tostring(diagnostics.messageKind or"sync")),"Sync envelope queued",diagnostics,diagnostics.correlationId)else log("WARN","retries","Sync envelope was not queued",diagnostics,diagnostics.correlationId);if retryCount<(tonumber(task.maxRetries)or 0)then HolyStorm.Tasks:Queue("Sync.Send",{executionMode="MULTI",priority=task.priority,delay=math.min(8,2^(retryCount+1)),retryCount=retryCount+1,maxRetries=task.maxRetries,triggerSource="SYNC_RETRY",metadata=m})end end;return sent
end
function Sync:Publish(domainId,objectId,reason)
 local domain=self.domains[domainId];local meta=domain and domain.getMetadata(objectId);if not meta then return false,"OBJECT_NOT_FOUND"end
 if domain.live then return HolyStorm.Tasks:Queue("Sync.LivePublish",{mergeKey=key(domainId,objectId),delay=.2,priority=domain.priority or 110,triggerSource=reason or"LIVE_UPDATE",metadata={domain=domainId,objectId=objectId}})end
 local channel=domain.getChannel and domain.getChannel(meta,"publish")or"GUILD";return HolyStorm.Tasks:Queue("Sync.Publish",{mergeKey=key(domainId,objectId),delay=1,startupPhase=startupActive() and startupPhase(domainId)or nil,priority=65,triggerSource=reason or"LOCAL_UPDATE",metadata={domain=domainId,objectId=objectId,channel=channel,reason=reason or"LOCAL_UPDATE"}})
end
function Sync:RunLivePublish(task)
 local m=task.metadata or{};local domain=self.domains[m.domain];local meta=domain and domain.getMetadata(m.objectId);local payload=domain and domain.export(m.objectId);if not meta or payload==nil then return false end;local channel=domain.getChannel and domain.getChannel(meta,"live")or"GUILD";local envelope={protocol=self.protocol,kind="LIVE",domain=m.domain,data={objectId=m.objectId,metadata=meta,payload=payload},sentAt=now(),sender=UnitGUID("player")};log("DEBUG","live","Publishing latest ephemeral state",{domain=m.domain,objectId=m.objectId,version=meta.version,channel=channel});return self:SendNow({metadata={envelope=envelope,channel=channel},priority=domain.priority or 110,retryCount=0,maxRetries=1})
end
function Sync:RunPublish(task)
 local m=task.metadata;local domain=self.domains[m.domain];local meta=domain and domain.getMetadata(m.objectId);if not meta then return false end;meta=copy(meta);meta.direct=meta.owner==UnitGUID("player")
 local channel=m.channel or(domain.getChannel and domain.getChannel(meta,"publish"))or"GUILD";local publishKey=key(m.domain,m.objectId);local signature=table.concat({tostring(meta.version),tostring(meta.revisionID or""),channel},"\031");if self.publishedVersions[publishKey]==signature then log("DEBUG","suppression","Duplicate metadata publish suppressed",{domain=m.domain,objectId=m.objectId,version=meta.version,revision=meta.revisionID,channel=channel,reason="UNCHANGED_METADATA"});return true end
 log("DEBUG","discovery","Publishing lightweight metadata",{domain=m.domain,objectId=m.objectId,version=meta.version,revision=meta.revisionID,channel=channel,reason=m.reason});local queued=self:QueueEnvelope("ANNOUNCE",m.domain,{offers={meta},reason=m.reason},channel,nil,70);if queued then self.publishedVersions[publishKey]=signature end;return queued~=nil
end
function Sync:RequestObject(domainId,objectId,options)
 local domain=self.domains[domainId];if not domain or not validId(objectId)then return false,"UNKNOWN_OBJECT"end;options=options or{};local localMeta=domain.getMetadata(objectId);local owner=options.owner or(localMeta and localMeta.owner);local target=self:GetOnlineName(owner)
 if target then local requestId=self:NewRequestId();log("DEBUG","request","Requesting payload from online owner",{domain=domainId,objectId=objectId,owner=owner,target=target,requestId=requestId});return self:QueueFetch(domainId,objectId,target,localMeta and localMeta.version or-1,options.reason or"ON_DEMAND",localMeta and localMeta.revisionID,requestId)end
 return self:Discover(domainId,objectId,options)
end
function Sync:Discover(domainId,objectId,options)
 if not self.domains[domainId]then return false,"UNKNOWN_DOMAIN"end;options=options or{};local discoveryObject=objectId or("*:"..tostring(options.scope or"ALL")..":"..tostring(options.sessionId or""));local discoveryKey=key(domainId,discoveryObject);local existing=self.activeRequests[discoveryKey];if existing and self.requests[existing]then return existing,"MERGED"end
 local requestId=self:NewRequestId();local localMeta=objectId and self.domains[domainId].getMetadata(objectId);self.requests[requestId]={id=requestId,key=discoveryKey,domain=domainId,objectId=objectId,candidates={},createdAt=now(),reason=options.reason,channel=options.channel,scope=options.scope,sessionId=options.sessionId};self.activeRequests[discoveryKey]=requestId;self:ScheduleCleanup()
 HolyStorm.Tasks:Queue("Sync.Discover",{mergeKey=discoveryKey,startupPhase=options.startupPhase or(startupActive() and startupPhase(domainId)or nil),priority=options.priority or 80,delay=options.delay or 0,triggerSource=options.reason or"DISCOVERY",metadata={requestId=requestId,domain=domainId,objectId=objectId,knownVersion=localMeta and localMeta.version or-1,knownRevisionID=localMeta and localMeta.revisionID,watermark=options.watermark,channel=options.channel or"GUILD",scope=options.scope,sessionId=options.sessionId}});return requestId,"QUEUED"
end
function Sync:RunDiscover(task)
 local m=task.metadata;log("DEBUG","discovery","Sending metadata discovery",{domain=m.domain,objectId=m.objectId,requestId=m.requestId,watermark=m.watermark,channel=m.channel});self:QueueEnvelope("DISCOVER",m.domain,{requestId=m.requestId,objectId=m.objectId,knownVersion=m.knownVersion,knownRevisionID=m.knownRevisionID,watermark=m.watermark,scope=m.scope,sessionId=m.sessionId},m.channel or"GUILD",nil,task.priority);return true
end
function Sync:MetadataForRequest(domain,request)
 local entries={};if request.objectId then local meta=domain.getMetadata(request.objectId);if meta then entries[1]=meta end else entries=domain.listMetadata(tonumber(request.watermark)or 0,request)or{}end
 local out={};for _,meta in ipairs(entries)do if type(meta)=="table"and validId(meta.objectId)and validId(meta.owner)and tonumber(meta.version)then local newer=tonumber(meta.version)>tonumber(request.knownVersion or-1);local sibling=domain.freshness=="revision-chain"and request.knownRevisionID and meta.revisionID~=request.knownRevisionID;if newer or sibling or not request.objectId then local item=copy(meta);item.direct=item.owner==UnitGUID("player");out[#out+1]=item;if#out>=self.maxOffers then break end end end end;return out
end
function Sync:OnDiscover(domainId,request,sender,channel)
 local domain=self.domains[domainId];if not domain or type(request)~="table"or type(request.requestId)~="string"then return false end;local offers=self:MetadataForRequest(domain,request);if#offers==0 then return false end
 local delay=.15+(math.random()*1.1);HolyStorm.Tasks:Queue("Sync.Offer",{mergeKey=request.requestId.."\031"..sender,delay=delay,priority=domain.priority or 85,triggerSource="DISCOVERY_RESPONSE",metadata={domain=domainId,request=request,requester=sender,responseChannel=channel}});return true
end
function Sync:RunOffer(task)
 local m=task.metadata;local domain=self.domains[m.domain];if not domain then return false end;local offers=self:MetadataForRequest(domain,m.request);local heard=self.heard[m.request.requestId]or{};local filtered={}
 for _,meta in ipairs(offers)do local decision=HolyStorm.PlayerData:CompareMetadata(heard[meta.objectId],meta);if domain.freshness=="revision-chain"or not heard[meta.objectId]or decision>0 then filtered[#filtered+1]=meta else log("DEBUG","suppression","Redundant metadata response suppressed",{domain=m.domain,objectId=meta.objectId,version=meta.version,requestId=m.request.requestId})end end
 if#filtered==0 then return true end;local supported={GUILD=true,PARTY=true,RAID=true,INSTANCE_CHAT=true};local channel=supported[m.responseChannel]and m.responseChannel or"GUILD";self:QueueEnvelope("OFFER",m.domain,{requestId=m.request.requestId,offers=filtered,requester=m.requester},channel,nil,domain.priority or 85);return true
end
function Sync:RecordOffers(domainId,data,sender,isAnnouncement)
 if type(data)~="table"or type(data.offers)~="table"then return false end;local requestId=data.requestId;local senderId=senderGuid(sender);if requestId then self.heard[requestId]=self.heard[requestId]or{};self.heardAt[requestId]=now();self:ScheduleCleanup()end;local pending=requestId and self.requests[requestId]
 for _,meta in ipairs(data.offers)do
  if type(meta)=="table"and validId(meta.objectId)and validId(meta.owner)and tonumber(meta.version)then meta=copy(meta);meta.direct=senderId~=nil and senderId==meta.owner
   if requestId then local old=self.heard[requestId][meta.objectId];if not old or HolyStorm.PlayerData:CompareMetadata(old,meta)>0 then self.heard[requestId][meta.objectId]=meta end end
   if pending and pending.domain==domainId and(not pending.objectId or pending.objectId==meta.objectId)and(not data.requester or samePlayerName(data.requester,GetUnitName("player",true)))then pending.candidates[meta.objectId]=pending.candidates[meta.objectId]or{};pending.candidates[meta.objectId][sender]={sender=sender,senderGuid=senderId,meta=meta};local characterUUID,block=splitCharacterId(meta.objectId);HolyStorm.Tasks:Queue("Sync.SelectSource",{mergeKey=requestId.."\031"..meta.objectId,delay=.75,priority=self.domains[domainId].priority or 82,triggerSource="SYNC_OFFER",metadata={requestId=requestId,domain=domainId,objectId=meta.objectId,characterUUID=characterUUID,block=block,version=meta.version,revision=meta.revisionID,selectedSource=sender,reason=pending.reason or"DISCOVERY"}})
   elseif not data.requester then self:ConsiderPassive(domainId,meta,sender)end
  end
 end;return true
end
function Sync:RunSelect(task)
 local m=task.metadata;local request=self.requests[m.requestId];if not request then return false end;local candidates=request.candidates[m.objectId]or{};local best
 for _,candidate in pairs(candidates)do if not best then best=candidate else local decision=HolyStorm.PlayerData:CompareMetadata(best.meta,candidate.meta);if decision>0 or(decision==0 and candidate.meta.direct and not best.meta.direct)then best=candidate end end end
 if best then local domain=self.domains[request.domain];local localMeta=domain.getMetadata(m.objectId);local decision=HolyStorm.PlayerData:CompareMetadata(localMeta,best.meta);local sibling=domain.freshness=="revision-chain"and localMeta and tonumber(localMeta.version)==tonumber(best.meta.version)and localMeta.revisionID~=best.meta.revisionID;local characterUUID,block=splitCharacterId(m.objectId);log("DEBUG","selection","Selecting payload source",{domain=request.domain,objectId=m.objectId,characterUUID=characterUUID,block=block,localVersion=localMeta and localMeta.version,version=best.meta.version,revision=best.meta.revisionID,requestId=m.requestId,reason=request.reason or"DISCOVERY",selectedSource=best.sender,originalOwner=best.meta.owner,relay=best.meta.direct~=true});if decision>0 or sibling then self:QueueFetch(request.domain,m.objectId,best.sender,localMeta and localMeta.version or-1,request.reason or"DISCOVERY",localMeta and localMeta.revisionID,m.requestId,best.meta)else log("DEBUG","suppression","Selected payload is no longer newer",{domain=request.domain,objectId=m.objectId,characterUUID=characterUUID,block=block,localVersion=localMeta and localMeta.version,version=best.meta.version,revision=best.meta.revisionID,requestId=m.requestId,reason="LOCAL_METADATA_CURRENT",selectedSource=best.sender})end end
 request.candidates[m.objectId]=nil;if request.objectId then self.requests[m.requestId]=nil;self.activeRequests[request.key or key(request.domain,request.objectId)]=nil;self:ScheduleCleanup()end;return best~=nil
end
function Sync:QueueFetch(domainId,objectId,target,knownVersion,reason,knownRevisionID,requestId,desiredMeta)
 local domain=self.domains[domainId];if not domain or not validId(objectId)or type(target)~="string"or target==""then return nil,"INVALID_FETCH"end;desiredMeta=type(desiredMeta)=="table"and desiredMeta or{};local peerKey=string.lower(target);local desiredVersion=desiredMeta.version;local desiredRevisionID=desiredMeta.revisionID;local dedupeKey=table.concat({peerKey,domainId,objectId,tostring(desiredVersion or knownVersion or-1),tostring(desiredRevisionID or knownRevisionID or"")},"\030");local dependencies={};local tail=self.fetchTailByPeer[peerKey];if tail then local tailTask=HolyStorm.Tasks.GetTask and HolyStorm.Tasks:GetTask(tail);if not HolyStorm.Tasks.GetTask or tailTask and(tailTask.status=="QUEUED"or tailTask.status=="WAITING"or tailTask.status=="BLOCKED"or tailTask.status=="READY"or tailTask.status=="RUNNING"or tailTask.status=="WAITING_ASYNC")then dependencies[1]=tail end end;local characterUUID,block=splitCharacterId(objectId);local taskId,state=HolyStorm.Tasks:Queue("Sync.Fetch",{mergeKey=dedupeKey,dependencies=dependencies,priority=domain.priority or 75,triggerSource=reason or"FETCH",metadata={domain=domainId,objectId=objectId,target=target,selectedSource=target,characterUUID=characterUUID,block=block,knownVersion=knownVersion,knownRevisionID=knownRevisionID,version=desiredVersion,revision=desiredRevisionID,selectedOwner=desiredMeta.owner,selectedDirect=desiredMeta.direct,reason=reason or"FETCH",requestId=requestId or self:NewRequestId(),peerKey=peerKey}});if taskId and state~="MERGED"then self.fetchTailByPeer[peerKey]=taskId end;return taskId,state
end
function Sync:RunFetch(task)local m=task.metadata;local domain=self.domains[m.domain];if not domain then return false end;local localMeta=domain.getMetadata(m.objectId);if m.version~=nil then local offered={version=m.version,revisionID=m.revision,owner=m.selectedOwner,direct=m.selectedDirect};local decision=HolyStorm.PlayerData:CompareMetadata(localMeta,offered);local sibling=domain.freshness=="revision-chain"and localMeta and tonumber(localMeta.version)==tonumber(offered.version)and localMeta.revisionID~=offered.revisionID;if decision<=0 and not sibling then log("DEBUG","suppression","Fetch skipped because local metadata is current",{domain=m.domain,objectId=m.objectId,characterUUID=m.characterUUID,block=m.block,localVersion=localMeta and localMeta.version,version=m.version,revision=m.revision,reason="LOCAL_METADATA_CURRENT",requestId=m.requestId,selectedSource=m.target});if self.fetchTailByPeer[m.peerKey]==task.uniqueId then self.fetchTailByPeer[m.peerKey]=nil end;return true end end;local knownVersion=localMeta and localMeta.version or m.knownVersion;local knownRevisionID=localMeta and localMeta.revisionID or m.knownRevisionID;log("DEBUG","request","Requesting selected payload",{direction="SEND",sender=playerName(),receiver=m.target,channel="WHISPER",domain=m.domain,objectId=m.objectId,characterUUID=m.characterUUID,block=m.block,knownVersion=knownVersion,version=m.version,revision=m.revision,reason=m.reason,requestId=m.requestId,selectedSource=m.target,originalOwner=m.selectedOwner,relay=m.selectedDirect==false});local queued=self:QueueEnvelope("FETCH",m.domain,{objectId=m.objectId,knownVersion=knownVersion,knownRevisionID=knownRevisionID,revisionID=m.revision,reason=m.reason,requestId=m.requestId},"WHISPER",m.target,75);if self.fetchTailByPeer[m.peerKey]==task.uniqueId then self.fetchTailByPeer[m.peerKey]=nil end;return queued~=nil end
function Sync:OnFetch(domainId,data,sender)
 local domain=self.domains[domainId];if not domain or type(data)~="table"or not validId(data.objectId)then return false end;local meta=domain.getMetadata(data.objectId);local sibling=domain.freshness=="revision-chain"and meta and data.knownRevisionID and meta.revisionID~=data.knownRevisionID and tonumber(meta.version)==tonumber(data.knownVersion);if not meta or((tonumber(meta.version)or 0)<=(tonumber(data.knownVersion)or-1)and not sibling)then return false end;local payload=domain.export(data.objectId);if payload==nil then return false end
 self:QueueEnvelope("PAYLOAD",domainId,{objectId=data.objectId,metadata=meta,payload=payload,reason="REQUEST_RESPONSE",requestId=data.requestId},"WHISPER",sender,domain.priority or 70);local characterUUID,block=splitCharacterId(data.objectId);log("DEBUG","payload","Payload queued for selected requester",{direction="SEND",sender=playerName(),receiver=sender,channel="WHISPER",domain=domainId,objectId=data.objectId,characterUUID=characterUUID,block=block,version=meta.version,revision=meta.revisionID,target=sender,reason="REQUEST_RESPONSE",requestId=data.requestId,originalOwner=meta.owner,relay=meta.owner~=UnitGUID("player")});return true
end
function Sync:OnPayload(domainId,data,sender)
 local domain=self.domains[domainId];if not domain or type(data)~="table"or not validId(data.objectId)or type(data.metadata)~="table"then return false end;local senderId=senderGuid(sender);local meta=copy(data.metadata);meta.direct=senderId~=nil and senderId==meta.owner;meta.receivedFrom=sender
 if domain.validate then local ok,result,reason=HolyStorm.Utils.SafeCall("sync.validate:"..domainId,domain.validate,data.payload,meta,data.objectId);if not ok or result==false then log("WARN","validation","Synchronized payload rejected",{domain=domainId,objectId=data.objectId,error=reason or result});return false end end
 if domain.authorize then local ok,result=HolyStorm.Utils.SafeCall("sync.authority:"..domainId,domain.authorize,data.payload,meta,senderId,sender,data.objectId);if not ok or result~=true then log("WARN","authority","Synchronized payload rejected by authority rule",{domain=domainId,objectId=data.objectId,owner=meta.owner,receivedFrom=sender});return false end end
 local localMeta=domain.getMetadata(data.objectId);if domain.freshness~="revision-chain"then local decision,reason=HolyStorm.PlayerData:CompareMetadata(localMeta,meta);if decision<=0 then log("DEBUG","freshness","Stale synchronized payload rejected",{domain=domainId,objectId=data.objectId,localVersion=localMeta and localMeta.version,remoteVersion=meta.version,reason=reason});return false end end
 local ok,result=HolyStorm.Utils.SafeCall("sync.import:"..domainId,domain.import,data.objectId,data.payload,meta,senderId,sender);if not ok or result==false then log("WARN","import","Synchronized payload import failed",{domain=domainId,objectId=data.objectId,error=result});return false end
 HolyStorm.PlayerData:AdvanceForeignWatermark(meta.owner,meta.updatedAt,domainId);log("DEBUG","freshness",meta.direct and"Direct owner payload accepted"or"Indirect relay payload accepted",{domain=domainId,objectId=data.objectId,owner=meta.owner,version=meta.version,receivedFrom=sender});HolyStorm.Events:Emit("HS_SYNC_DOMAIN_UPDATED",domainId,data.objectId,meta);if domain.updateEvent then HolyStorm.Events:Emit(domain.updateEvent,data.objectId,meta)end;return true
end
function Sync:ConsiderPassive(domainId,meta,sender)
 local domain=self.domains[domainId];local localMeta=domain and domain.getMetadata(meta.objectId);local decision=HolyStorm.PlayerData:CompareMetadata(localMeta,meta);local sibling=domain and domain.freshness=="revision-chain"and localMeta and tonumber(localMeta.version)==tonumber(meta.version)and localMeta.revisionID~=meta.revisionID;if decision<=0 and not sibling then return false end;local delay=3+math.random()*5;HolyStorm.Tasks:Queue("Sync.PassiveRefresh",{mergeKey=key(domainId,meta.objectId),delay=delay,priority=95,triggerSource="PASSIVE_HEALING",metadata={domain=domainId,objectId=meta.objectId,sender=sender,version=meta.version,revisionID=meta.revisionID}});log("DEBUG","passive","Passive refresh scheduled",{domain=domainId,objectId=meta.objectId,remoteVersion=meta.version,localVersion=localMeta and localMeta.version});return true
end
function Sync:RunPassive(task)local m=task.metadata;local domain=self.domains[m.domain];local localMeta=domain and domain.getMetadata(m.objectId);if localMeta and(tonumber(localMeta.version)or 0)>=(tonumber(m.version)or 0)and not(domain.freshness=="revision-chain"and localMeta.revisionID~=m.revisionID)then return true end;return self:QueueFetch(m.domain,m.objectId,m.sender,localMeta and localMeta.version or-1,"PASSIVE_HEALING",localMeta and localMeta.revisionID,nil,{version=m.version,revisionID=m.revisionID})~=nil end
function Sync:GetOnlineName(guid)if type(guid)~="string"then return nil end;local guild=HolyStorm.Data.GuildStore:GetCurrent();local member=guild and guild.roster and guild.roster[guid];return member and member.online and member.name or nil end
function Sync:GetDiagnostics()return{requests=HolyStorm.Utils.TableCount(self.requests),activeRequests=HolyStorm.Utils.TableCount(self.activeRequests),heard=HolyStorm.Utils.TableCount(self.heard),knownOnline=HolyStorm.Utils.TableCount(self.knownOnline),domains=HolyStorm.Utils.TableCount(self.domains),fetchPeers=HolyStorm.Utils.TableCount(self.fetchTailByPeer),publishedVersions=HolyStorm.Utils.TableCount(self.publishedVersions),cleanupScheduled=self.cleanupTimer~=nil or self.cleanupTaskId~=nil}end
function Sync:Cleanup()
 local current=now();local requestCutoff=current-self.requestTimeout;for requestId,request in pairs(self.requests)do if(request.createdAt or 0)<=requestCutoff then self.activeRequests[request.key or key(request.domain,request.objectId)]=nil;self.requests[requestId]=nil end end;for requestId,at in pairs(self.heardAt)do if at<=requestCutoff then self.heardAt[requestId]=nil;self.heard[requestId]=nil end end;local presenceCutoff=current-self.presenceTimeout;for guid,at in pairs(self.knownOnline)do if at<=presenceCutoff then self.knownOnline[guid]=nil end end;self:ScheduleCleanup();return true
end
function Sync:RunCatchUp()
 -- Each domain is a distinct logical scope. Discover() merges repeated catch-up requests per domain/scope.
 if not IsInGuild()then return false end;for domainId,domain in pairs(self.domains)do if domain.catchUp~=false then self:Discover(domainId,nil,{reason="LOGIN_CATCHUP",priority=98,watermark=HolyStorm.PlayerData:GetForeignWatermark(domainId)})end end;log("DEBUG","catchup","Delayed login catch-up started",{watermark=HolyStorm.PlayerData:GetForeignWatermark(),domains=HolyStorm.Utils.TableCount(self.domains)});return true
end
function Sync:GetKnownVersion(guid)local entry=type(guid)=="string"and self.knownVersions[guid];return entry and entry.version or nil end
function Sync:BeginLoginSession()
 self.loginSessionId="LOGIN-"..self:NewRequestId();self.presencePublished=false;self.peerVersionReceived=false;self.outdatedNotified=false;self.knownVersions={}
 return HolyStorm.Tasks:Queue("Sync.LoginPresence",{delay=1.5,startupPhase=4,priority=98,triggerSource="PLAYER_LOGIN",metadata={sessionId=self.loginSessionId}})
end
function Sync:RunLoginPresence(task)
 if not IsInGuild()then return false end;local sessionId=task.metadata and task.metadata.sessionId or self.loginSessionId
 self:QueueEnvelope("PRESENCE",nil,{version=HolyStorm.version,sessionId=sessionId,replyRequested=true,reason="LOGIN_PRESENCE"},"GUILD",nil,90);self:RunCatchUp();return true
end
function Sync:EvaluateOutdatedVersion()
 if self.outdatedNotified or not self.presencePublished or not self.peerVersionReceived then return false end
 for _,entry in pairs(self.knownVersions)do local comparison=HolyStorm.Utils.CompareSemanticVersions(entry.version,HolyStorm.version);if comparison==1 then self.outdatedNotified=true;if HolyStorm.Commands and HolyStorm.Commands.PrintUserMessage then HolyStorm.Commands:PrintUserMessage(L["OUTDATED_VERSION_NOTICE"])end;HolyStorm.Logger:Write("INFO","Sync","version","Newer Holy Storm version discovered",{localVersion=HolyStorm.version,remoteVersion=entry.version,sender=entry.sender,characterUUID=entry.guid,sessionId=self.loginSessionId});return true end end
 return false
end
function Sync:OnPresence(data,sender,resolved)
 if not resolved then return false end;self.knownOnline[resolved]=now();self:ScheduleCleanup()
 if type(data.version)=="string"and HolyStorm.Utils.CompareSemanticVersions(data.version,data.version)~=nil then self.knownVersions[resolved]={guid=resolved,sender=sender,version=data.version,receivedAt=now()};self.peerVersionReceived=true;HolyStorm.Events:Emit("HS_SYNC_VERSION_UPDATED",resolved,data.version,sender);HolyStorm.Tasks:Queue("Sync.VersionNotice",{delay=2,priority=99,triggerSource="PEER_VERSION_RECEIVED"})end
 if data.replyRequested==true and not data.responseTo then self:QueueEnvelope("PRESENCE",nil,{version=HolyStorm.version,responseTo=data.sessionId,reason="PRESENCE_RESPONSE"},"WHISPER",sender,90,.2+math.random()*.6)end
 return true
end
function Sync:Receive(payload,sender,channel,transport)
 local envelope=HolyStorm.Serializer:Deserialize(payload);if type(envelope)~="table"or envelope.protocol~=self.protocol or type(envelope.kind)~="string"or envelope.sender==UnitGUID("player")then return false end;transport=type(transport)=="table"and transport or{};local data=type(envelope.data)=="table"and envelope.data or{};local meta=type(data.metadata)=="table"and data.metadata or type(data.offers)=="table"and type(data.offers[1])=="table"and data.offers[1]or{};local correlationId=transport.correlationId or transport.transmissionId;local objectId=data.objectId or meta.objectId;local characterUUID,blockType;if type(objectId)=="string"then characterUUID,blockType=objectId:match("^(.-)\031([^\031]+)$")end;local destination=receiver(channel);log("DEBUG",string.lower(envelope.kind),"Sync envelope received",{direction="RECEIVE",sender=sender,receiver=destination,target=destination,from=sender,to=destination,channel=channel,domain=envelope.domain,logicalObject=blockType or objectId,blockType=blockType,block=blockType,characterUUID=characterUUID,objectId=objectId,messageKind=envelope.kind,messageClass=messageClasses[envelope.kind]or"control",version=meta.version or data.version,revision=meta.revisionID or data.revisionID,reason=data.reason,requestId=data.requestId,selectedSource=sender,transmissionId=transport.transmissionId,packetTotal=transport.packetTotal,bytes=transport.bytes,serializedBytes=transport.bytes,correlationId=correlationId,originalOwner=meta.owner,relay=meta.owner and meta.owner~=envelope.sender or false,retry=false},correlationId);local resolved=senderGuid(sender);if resolved and envelope.sender~=resolved then log("WARN","authority","Envelope sender identity mismatch",{direction="RECEIVE",from=sender,to=destination,channel=channel,sender=sender,claimed=envelope.sender,resolved=resolved,transmissionId=transport.transmissionId,correlationId=correlationId},correlationId);return false end
 if envelope.kind=="PRESENCE"then return self:OnPresence(data,sender,resolved)end
  if not self.domains[envelope.domain]then return false end
 if envelope.kind=="DISCOVER"then return self:OnDiscover(envelope.domain,envelope.data,sender,channel)elseif envelope.kind=="OFFER"or envelope.kind=="ANNOUNCE"then return self:RecordOffers(envelope.domain,envelope.data,sender,envelope.kind=="ANNOUNCE")elseif envelope.kind=="FETCH"then return self:OnFetch(envelope.domain,envelope.data,sender)elseif envelope.kind=="PAYLOAD"or envelope.kind=="LIVE"then return self:OnPayload(envelope.domain,envelope.data,sender)end;return false
end
function Sync:Initialize()
 HolyStorm.Tasks:RegisterTaskType("Sync.Send",{name=L["TASK_SYNC_SEND"],localizedNameKey="TASK_SYNC_SEND",module="Sync",priority=70,executionMode="MULTI",maxRetries=2,execute=function(task)return Sync:SendNow(task)end})
 HolyStorm.Tasks:RegisterTaskType("Sync.LivePublish",{name=L["TASK_SYNC_LIVE_PUBLISH"],localizedNameKey="TASK_SYNC_LIVE_PUBLISH",module="Sync",priority=110,executionMode="MERGE_BY_KEY",conditions={"PLAYER_READY","NOT_LOADING","NOT_ZONING","GUILD_AVAILABLE"},execute=function(task)return Sync:RunLivePublish(task)end})
 HolyStorm.Tasks:RegisterTaskType("Sync.Publish",{name=L["TASK_SYNC_PUBLISH"],localizedNameKey="TASK_SYNC_PUBLISH",module="Sync",priority=65,executionMode="MERGE_BY_KEY",conditions={"PLAYER_READY","NOT_LOADING","NOT_ZONING"},execute=function(task)return Sync:RunPublish(task)end})
 HolyStorm.Tasks:RegisterTaskType("Sync.Discover",{name=L["TASK_SYNC_DISCOVER"],localizedNameKey="TASK_SYNC_DISCOVER",module="Sync",priority=80,executionMode="MERGE_BY_KEY",conditions={"PLAYER_READY","NOT_LOADING","NOT_ZONING","GUILD_AVAILABLE"},execute=function(task)return Sync:RunDiscover(task)end})
 HolyStorm.Tasks:RegisterTaskType("Sync.Offer",{name=L["TASK_SYNC_OFFER"],localizedNameKey="TASK_SYNC_OFFER",module="Sync",priority=85,executionMode="MERGE_BY_KEY",execute=function(task)return Sync:RunOffer(task)end})
 HolyStorm.Tasks:RegisterTaskType("Sync.SelectSource",{name=L["TASK_SYNC_SELECT"],localizedNameKey="TASK_SYNC_SELECT",module="Sync",priority=82,executionMode="MERGE_BY_KEY",execute=function(task)return Sync:RunSelect(task)end})
 HolyStorm.Tasks:RegisterTaskType("Sync.Fetch",{name=L["TASK_SYNC_FETCH"],localizedNameKey="TASK_SYNC_FETCH",module="Sync",priority=75,executionMode="MERGE_BY_KEY",execute=function(task)return Sync:RunFetch(task)end})
 HolyStorm.Tasks:RegisterTaskType("Sync.PassiveRefresh",{name=L["TASK_SYNC_PASSIVE"],localizedNameKey="TASK_SYNC_PASSIVE",module="Sync",priority=95,executionMode="MERGE_BY_KEY",execute=function(task)return Sync:RunPassive(task)end})
 HolyStorm.Tasks:RegisterTaskType("Sync.Cleanup",{name="Sync cleanup",module="Sync",priority=100,executionMode="UNIQUE",execute=function()Sync.cleanupTaskId=nil;return Sync:Cleanup()end})
 HolyStorm.Tasks:RegisterTaskType("Sync.LoginPresence",{name=L["TASK_SYNC_CATCHUP"],localizedNameKey="TASK_SYNC_CATCHUP",module="Sync",priority=98,executionMode="UNIQUE",conditions={"PLAYER_LOGGED_IN","PLAYER_READY","NOT_LOADING","NOT_ZONING","GUILD_AVAILABLE"},execute=function(task)return Sync:RunLoginPresence(task)end})
 HolyStorm.Tasks:RegisterTaskType("Sync.VersionNotice",{name=L["TASK_SYNC_VERSION_NOTICE"],localizedNameKey="TASK_SYNC_VERSION_NOTICE",module="Sync",priority=99,executionMode="UNIQUE",execute=function()return Sync:EvaluateOutdatedVersion()end})
 self:RegisterDomain("character",{getMetadata=function(objectId)local guid,block=splitCharacterId(objectId);return guid and HolyStorm.PlayerData:GetMetadata(guid,block)end,listMetadata=function(since)local out={};for guid,record in pairs(HolyStorm.PlayerData:GetCharacters())do for block in pairs(record.blockMeta or{})do local meta=HolyStorm.PlayerData:GetMetadata(guid,block);if meta and(meta.updatedAt or 0)>since then out[#out+1]=meta end end end;return out end,export=function(objectId)local guid,block=splitCharacterId(objectId);local data=guid and HolyStorm.PlayerData:GetBlock(guid,block);return data and{guid=guid,block=block,data=data}end,validate=function(payload,meta,objectId)local guid,block=splitCharacterId(objectId);return type(payload)=="table"and payload.guid==guid and payload.block==block and type(payload.data)=="table"and meta.owner==guid end,authorize=function(_,meta,_,_,objectId)local guid=splitCharacterId(objectId);return meta.owner==guid end,import=function(objectId,payload,meta,senderId,sender)local guid,block=splitCharacterId(objectId);return HolyStorm.PlayerData:AcceptRemoteBlock(guid,block,payload.data,meta,senderId,sender)end,updateEvent="HS_CHARACTER_SYNC_UPDATED"})
 HolyStorm.Events:Register("HS_COMMS_MESSAGE","sync",function(_,payload,sender,channel,transport)Sync:Receive(payload,sender,channel,transport)end)
 HolyStorm.Events:Register("HS_PLAYERDATA_OWNED_UPDATED","sync-character",function(_,guid,block)Sync:Publish("character",guid.."\031"..block,"OWNED_BLOCK_UPDATED")end)
 HolyStorm.Events:Register("PLAYER_LOGIN","sync-presence",function()Sync:BeginLoginSession()end)
 HolyStorm.Tasks:RegisterTaskType("Sync.LoginCatchUp",{name=L["TASK_SYNC_CATCHUP"],localizedNameKey="TASK_SYNC_CATCHUP",module="Sync",priority=98,executionMode="UNIQUE",conditions={"PLAYER_READY","NOT_LOADING","NOT_ZONING","GUILD_AVAILABLE"},execute=function()return Sync:RunCatchUp()end})
 HolyStorm.State:Set("syncReady",HolyStorm.Comms.available==true);return true
end
function Sync:Shutdown()self:CancelCleanupTimer();if self.cleanupTaskId then HolyStorm.Tasks:Cancel(self.cleanupTaskId,"SYNC_SHUTDOWN");self.cleanupTaskId=nil end end
HolyStorm.Sync=Sync
