local addonVersion="1.2.0"
local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm")
local MapLinks={version=addonVersion,poiProviders={},minimapUpdaters={},minimapElapsed=0}

function MapLinks:RegisterPOIProvider(id,provider)if type(id)~="string"or type(provider)~="table"then return false end;self.poiProviders[id]=provider;return true end
function MapLinks:ResolvePOI(id)for providerId,provider in pairs(self.poiProviders)do if provider.get then local ok,poi=HolyStorm.Utils.SafeCall("poi.resolve:"..providerId,provider.get,id);if ok and poi then return poi,provider,providerId end end end end
function MapLinks:ListPOIs()
 local out,seen={},{};for providerId,provider in pairs(self.poiProviders)do if provider.list then local ok,items=HolyStorm.Utils.SafeCall("poi.list:"..providerId,provider.list);if ok and type(items)=="table"then for _,poi in pairs(items)do local id=poi and(poi.id or poi.poiId or poi.poiID);if type(id)=="string"and id~=""and not seen[id]then seen[id]=true;out[#out+1]={id=id,name=poi.name or id,category=poi.category,mapID=poi.mapID,creator=poi.creator or poi.creatorName,creatorGuid=poi.creatorGuid,provider=providerId}end end end end end;table.sort(out,function(a,b)return string.lower(a.name)<string.lower(b.name)end);return out
end
function MapLinks:OpenPOI(id)local poi,provider,providerId=self:ResolvePOI(id);if not poi then return false,"POI_UNAVAILABLE"end;if provider.open then local ok,result,reason=HolyStorm.Utils.SafeCall("poi.open:"..providerId,provider.open,id,poi);return ok and result or false,ok and reason or"POI_UNAVAILABLE"end;if poi.mapID and poi.x and poi.y then return self:OpenCoordinate(poi.mapID,poi.x,poi.y,poi.name)end;return false,"POI_UNAVAILABLE"end
function MapLinks:IsValidCoordinate(mapID,x,y)mapID,x,y=tonumber(mapID),tonumber(x),tonumber(y);return mapID and mapID>0 and mapID%1==0 and x and x==x and x>=0 and x<=1 and y and y==y and y>=0 and y<=1 end
function MapLinks:GetPlayerPosition()if not C_Map or not C_Map.GetBestMapForUnit or not C_Map.GetPlayerMapPosition then return nil,"MAP_UNAVAILABLE"end;local mapID=C_Map.GetBestMapForUnit("player");local position=mapID and C_Map.GetPlayerMapPosition(mapID,"player");if not position then return nil,"POSITION_UNAVAILABLE"end;local x,y=position:GetXY();if not self:IsValidCoordinate(mapID,x,y)then return nil,"POSITION_UNAVAILABLE"end;return mapID,x,y end
function MapLinks:TransformCoordinate(sourceMapID,x,y,targetMapID)
 if not self:IsValidCoordinate(sourceMapID,x,y)or not tonumber(targetMapID)then return nil,"INVALID_COORDINATE"end;sourceMapID,targetMapID=tonumber(sourceMapID),tonumber(targetMapID);if sourceMapID==targetMapID then return x,y,"DIRECT"end;if not C_Map or not C_Map.GetWorldPosFromMapPos or not C_Map.GetMapPosFromWorldPos or not CreateVector2D then return nil,"TRANSFORM_UNAVAILABLE"end
 local ok,continent,world=pcall(C_Map.GetWorldPosFromMapPos,sourceMapID,CreateVector2D(x,y));if not ok or not continent or not world then return nil,"TRANSFORM_FAILED"end;local converted,mapPosition;ok,converted,mapPosition=pcall(C_Map.GetMapPosFromWorldPos,continent,world,targetMapID);if not ok then return nil,"TRANSFORM_FAILED"end;if type(converted)=="number"then if converted~=targetMapID then return nil,"TRANSFORM_FAILED"end else mapPosition=converted end;if not mapPosition or not mapPosition.GetXY then return nil,"TRANSFORM_FAILED"end;local tx,ty=mapPosition:GetXY();if not self:IsValidCoordinate(targetMapID,tx,ty)then return nil,"TRANSFORM_FAILED"end;return tx,ty,"TRANSFORMED"
end
function MapLinks:ProjectToMinimap(sourceMapID,x,y,currentMapOnly)
 if not C_Map or not C_Map.GetBestMapForUnit or not C_Map.GetPlayerMapPosition or not C_Map.GetMapWorldSize or not C_Minimap or not C_Minimap.GetViewRadius or not Minimap then return nil,"API_UNAVAILABLE"end;local mapID=C_Map.GetBestMapForUnit("player");if currentMapOnly and tonumber(sourceMapID)~=tonumber(mapID)then return nil,"CURRENT_MAP_ONLY"end;local player=mapID and C_Map.GetPlayerMapPosition(mapID,"player");if not player then return nil,"PLAYER_POSITION"end;local tx,ty,mode=self:TransformCoordinate(sourceMapID,x,y,mapID);if not tx then return nil,ty end;local px,py=player:GetXY();local width,height=C_Map.GetMapWorldSize(mapID);local radius=C_Minimap.GetViewRadius();if not width or not height or not radius or radius<=0 then return nil,"API_UNAVAILABLE"end;local dx,north=(tx-px)*width,(py-ty)*height;if GetCVarBool and GetCVarBool("rotateMinimap")and GetPlayerFacing then local facing=GetPlayerFacing()or 0;dx,north=dx*math.cos(facing)-north*math.sin(facing),dx*math.sin(facing)+north*math.cos(facing)end;local distance=math.sqrt(dx*dx+north*north);if distance>radius then return nil,"OUT_OF_RANGE"end;local pixelRadius=math.min(Minimap:GetWidth(),Minimap:GetHeight())*.46;return dx/radius*pixelRadius,north/radius*pixelRadius,mode,mapID
end
function MapLinks:RegisterMinimapUpdater(id,callback)
 if type(id)~="string"or type(callback)~="function"then return false end;self.minimapUpdaters[id]=callback;if not self.minimapDriver and Minimap and CreateFrame then self.minimapDriver=CreateFrame("Frame",nil,Minimap);self.minimapDriver:SetScript("OnUpdate",function(_,elapsed)MapLinks.minimapElapsed=MapLinks.minimapElapsed+elapsed;if MapLinks.minimapElapsed>=.25 then MapLinks.minimapElapsed=0;for owner,update in pairs(MapLinks.minimapUpdaters)do HolyStorm.Utils.SafeCall("minimap.update:"..owner,update)end end end)end;return true
end
function MapLinks:UnregisterMinimapUpdater(id)self.minimapUpdaters[id]=nil end
function MapLinks:SetTemporaryMarker(mapID,x,y,options)
 if not self:IsValidCoordinate(mapID,x,y)then return false,"INVALID_COORDINATE"end;options=options or{};self.temporaryMarker={poiID="temporary-coordinate",mapID=tonumber(mapID),x=tonumber(x),y=tonumber(y),name=options.label,status="ACTIVE",target="PERSONAL",temporary=true,localOnly=true,createdAt=HolyStorm.Utils.Now(),expiresAt=options.timeout and(HolyStorm.Utils.Now()+math.max(1,tonumber(options.timeout)or 0))or nil};HolyStorm.Events:Emit("HS_MAP_TEMPORARY_MARKER_CHANGED",self.temporaryMarker);return true,self.temporaryMarker
end
function MapLinks:ClearTemporaryMarker()if not self.temporaryMarker then return false end;self.temporaryMarker=nil;HolyStorm.Events:Emit("HS_MAP_TEMPORARY_MARKER_CHANGED",nil);return true end
function MapLinks:OpenCoordinate(mapID,x,y,label)
 mapID,x,y=tonumber(mapID),tonumber(x),tonumber(y);if not self:IsValidCoordinate(mapID,x,y)then return false,"INVALID_COORDINATE"end
 if C_Map and C_Map.SetUserWaypoint and UiMapPoint and UiMapPoint.CreateFromCoordinates then pcall(function()local point=UiMapPoint.CreateFromCoordinates(mapID,x,y);if point then C_Map.SetUserWaypoint(point);if C_SuperTrack and C_SuperTrack.SetSuperTrackedUserWaypoint then C_SuperTrack.SetSuperTrackedUserWaypoint(true)end end end)end
 local opened=false;if OpenWorldMap then opened=pcall(OpenWorldMap,mapID)elseif WorldMapFrame and WorldMapFrame.SetMapID then opened=pcall(function()WorldMapFrame:SetMapID(mapID);WorldMapFrame:Show()end)end;if not opened then return false,"MAP_UNAVAILABLE"end
 self:SetTemporaryMarker(mapID,x,y,{label=label,timeout=300});HolyStorm.Events:Emit("HS_MAP_LINK_OPENED",self.temporaryMarker);return true
end
HolyStorm.MapLinks=MapLinks
