local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm")
local L=LibStub("AceLocale-3.0"):GetLocale("Holy_Storm_Raids")
local columns={{width=.38},{width=.10,align="RIGHT"},{width=.12,align="RIGHT"},{width=.12,align="RIGHT"},{width=.12,align="RIGHT"},{width=.16,align="RIGHT"}}
local state={rows={},snapshot=nil,summary=nil}
local function hyperlink(kind,id,label,difficulty)local C=HolyStorm.CharacterUI;local text=difficulty and C:ColorDifficulty(difficulty,label)or("|cff3fc7eb"..tostring(label).."|r");return id and("|Hhscharacter:"..kind..":"..tostring(id).."|h"..text.."|h")or text end
local function populateBest(snapshot,raidName)GameTooltip:SetText(L["BEST_TOOLTIP"]);local shown=0;for _,boss in ipairs(HolyStorm.CharacterUI:BuildRaidBestRows(snapshot))do if not raidName or not boss.raidName or boss.raidName==raidName then local short=boss.difficulty=="MYTHIC"and"M"or boss.difficulty=="HEROIC"and"H"or boss.difficulty=="NORMAL"and"N"or"LFR";GameTooltip:AddLine(string.format(L["BEST_ROW"],HolyStorm.CharacterUI:ColorDifficulty(boss.difficulty,short),boss.bossName,boss.kills));shown=shown+1 end end;if shown==0 then GameTooltip:AddLine(L["NO_DATA"],.7,.7,.7)end end
local function refresh(view,context,definition)local C=HolyStorm.CharacterUI;local ok,reason=C:CanUseTab(definition);if not ok then C:SetView(view,L["DISPLAY_NAME"],{reason=="PERMISSION"and L["PERMISSION_DENIED"]or L["MODULE_DISABLED"]});return end;local snapshot,meta=C:GetSnapshot(context.characterUUID,"raid");local status=C:GetDataStatus(context.characterUUID,"raid");if not snapshot then C:SetView(view,L["DISPLAY_NAME"],{L["NO_RAID"]},status);return end;local rows,byName,byId={},{},{};local function key(name)return type(name)=="string"and name:lower():gsub("[%s%p%c]+","")or nil end;for _,catalog in ipairs(snapshot.raids or{})do local row={name=catalog.name,instanceId=catalog.id,icon=catalog.icon,order=catalog.order or#rows+1,weekly={}};rows[#rows+1]=row;byName[key(row.name)]=row;byId[tostring(row.instanceId)]=row end;for _,lockout in ipairs(snapshot.lockouts or{})do local row=lockout.journalInstanceId and byId[tostring(lockout.journalInstanceId)]or byName[key(lockout.name)];if not row then row={name=lockout.name,instanceId=lockout.journalInstanceId,order=1000+#rows,weekly={}};rows[#rows+1]=row;byName[key(row.name)]=row end;local difficulty=C:GetDifficultyById(lockout.difficultyId);if difficulty then row.weekly[difficulty.id]=lockout end end;table.sort(rows,function(a,b)if a.order==b.order then return tostring(a.name)<tostring(b.name)end;return a.order<b.order end);state.rows,state.snapshot=rows,snapshot;local lines={{cells={L["COLUMN_RAID"],L["DIFFICULTY_LFR"],L["DIFFICULTY_NORMAL"],L["DIFFICULTY_HEROIC"],L["DIFFICULTY_MYTHIC"],L["COLUMN_BEST"]},columns=columns,style="header",maxWidth=1350}};for index,row in ipairs(rows)do local values={};for _,keyName in ipairs({"LFR","NORMAL","HEROIC","MYTHIC"})do local lockout=row.weekly[keyName];values[#values+1]=lockout and hyperlink("weekly",index..":"..keyName,string.format("%d/%d",lockout.killed or 0,lockout.total or 0),keyName)or"—"end;local best=C:GetBestProgress(snapshot,row.name);local bestText=best and hyperlink("best",index,string.format("%s %d/%d",best.difficulty,best.killed,best.total),best.difficulty)or"—";local label=(row.icon and("|T"..row.icon..":18:18|t ")or"")..row.name;local name=row.instanceId and hyperlink("journal",row.instanceId,label)or label;lines[#lines+1]={cells={name,values[1],values[2],values[3],values[4],bestText},columns=columns,maxWidth=1350}end;C:SetView(view,L["DISPLAY_NAME"],#rows>0 and lines or{L["NO_RAID"]},status,meta)end
HolyStorm:RegisterCharacterTab("raids",{id="raid",order=40,label=L["DISPLAY_NAME"],labelKey="DISPLAY_NAME",icon="Interface\\Icons\\INV_Sword_27",permission="raids-read",moduleId="raids",blocks={"raid"},events={"HS_RAIDLOCKS_UPDATED"},build=function(parent)return HolyStorm.CharacterUI:CreateTextView(parent)end,refresh=refresh})
HolyStorm:RegisterCharacterSummarySection("raids",{id="raid",order=40,render=function(context)local C=HolyStorm.CharacterUI;local snapshot=C:GetSnapshot(context.characterUUID,"raid");local best=snapshot and C:GetBestProgress(snapshot);state.summary=snapshot;return{label=L["DISPLAY_NAME"],tabId="raid",text="  "..(best and hyperlink("summarybest","all",string.format("%s %d/%d",best.difficulty,best.killed,best.total),best.difficulty)or L["NO_RAID"])}end})
HolyStorm.pendingCharacterLinkHandlers=HolyStorm.pendingCharacterLinkHandlers or{}
HolyStorm.pendingCharacterLinkHandlers.weekly={tooltip=function(id)local index,difficulty=id:match("^(%d+):(.+)$");local row=state.rows[tonumber(index)];local lockout=row and row.weekly and row.weekly[difficulty];GameTooltip:SetText(string.format(L["WEEKLY_TOOLTIP"],L["DIFFICULTY_"..tostring(difficulty)]or difficulty));if not lockout then GameTooltip:AddLine(L["NO_DATA"],.7,.7,.7);return end;for _,boss in ipairs(lockout.bosses or{})do GameTooltip:AddLine(string.format(boss.killed and L["BOSS_KILLED"]or L["BOSS_OPEN"],boss.name or L["UNKNOWN"]),boss.killed and .2 or .7,boss.killed and 1 or .7,boss.killed and .2 or .7)end end}
HolyStorm.pendingCharacterLinkHandlers.best={tooltip=function(id)local row=state.rows[tonumber(id)];populateBest(state.snapshot,row and row.name)end}
HolyStorm.pendingCharacterLinkHandlers.summarybest={tooltip=function()populateBest(state.summary)end}
HolyStorm.pendingCharacterLinkHandlers.journal=HolyStorm.pendingCharacterLinkHandlers.journal or{onClick=function(id)if not(InCombatLockdown and InCombatLockdown())and EncounterJournal_OpenJournal then EncounterJournal_OpenJournal(nil,tonumber(id))end end,tooltip=function()GameTooltip:SetText(L["COLUMN_RAID"]);GameTooltip:AddLine(L["OPEN_JOURNAL"],1,1,1,true)end}
if HolyStorm.CharacterUI then for kind,definition in pairs(HolyStorm.pendingCharacterLinkHandlers)do HolyStorm.CharacterUI:RegisterLinkHandler(kind,definition)end end
