local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm")
local L=LibStub("AceLocale-3.0"):GetLocale("Holy_Storm_Policy")
local Registry,Engine,Groups=HolyStorm.PermissionRegistry,HolyStorm.PermissionEngine,HolyStorm.GroupManager
local Filters,State=HolyStorm.FilterManager,HolyStorm.PolicyState
local Page=HolyStorm:RegisterRequiredModule("PermissionsUI")

HolyStorm:ApplyModuleMetadata(Page,{displayName=L["PERMISSIONS_TITLE"],internalName="permissionsUI",version="3.0.0",category="required",description=L["PERMISSIONS_DESC"],permissions={"permissions-manage"},dependencies={"core","ui"},enabledByDefault=true})

local tabs={"GENERAL","MEMBERS","PERMISSIONS","PERMISSION_MATRIX","RULES_FILTERS","MANAGERS","EFFECTIVE_MEMBERS","MODULE_SETTINGS","ANALYSIS","STATUS"}
local errorKeys={SYSTEM_GROUP="ERROR_SYSTEM_GROUP",SYSTEM_INVARIANT="ERROR_SYSTEM_INVARIANT",FULL_ACCESS_GROUP="ERROR_FULL_ACCESS_GROUP",GUILD_LEADER_REQUIRED="ERROR_GUILD_LEADER_REQUIRED",PERMISSION_DENIED="ERROR_PERMISSION_DENIED",STATE_NOT_VALID="ERROR_STATE_NOT_VALID",UNCHANGED="ERROR_UNCHANGED",MANAGER_CYCLE="ERROR_MANAGER_CYCLE",INVALID_GROUP="ERROR_INVALID_GROUP",INVALID_GROUP_NAME="ERROR_INVALID_GROUP_NAME",NOT_FOUND="ERROR_NOT_FOUND",TOO_MANY_MEMBERSHIPS="ERROR_TOO_MANY_MEMBERSHIPS",INVALID_MODULE="ERROR_INVALID_MODULE"}

local function keys(value)local out={};for key in pairs(value or{})do out[#out+1]=key end;table.sort(out,function(a,b)return tostring(a)<tostring(b)end);return out end
local function contains(values,wanted)for _,value in ipairs(values or{})do if value==wanted then return true end end;return false end
local function setArrayValue(values,id,enabled)local set={};for _,value in ipairs(values or{})do set[value]=true end;set[id]=enabled and true or nil;return keys(set)end
local function displayTime(value)return value and date("%Y-%m-%d %H:%M",value)or L["NONE"]end
local function categoryName(definition)local key="CATEGORY_"..tostring(definition.category or"Core"):gsub("[^%w]","_"):upper();return L[key]or definition.category or"Core"end

function Page:GetGroups()
 local out={};local search=string.lower(self.search and self.search:GetText()or"")
 for _,group in pairs(Groups:GetGroups())do local name=HolyStorm.PolicyUI:DisplayGroupName(group);if search==""or string.lower(name.." "..group.id):find(search,1,true)then out[#out+1]=group end end
 table.sort(out,function(a,b)if a.system~=b.system then return a.system end;return HolyStorm.PolicyUI:DisplayGroupName(a)<HolyStorm.PolicyUI:DisplayGroupName(b)end);return out
end
function Page:CanMutate(permission)local status=State:GetPermissionStateStatus();return status.status==State.status.VALID and Engine:HasPermission(nil,nil,permission)end
function Page:CanEditGroup()if not self.draft then return false end;if self.isNew then return self:CanMutate("groups-create")end;local actor=Engine:Actor();return Engine:CanManageGroup(actor.accountUUID,actor.characterUUID,self.draft.id)end
function Page:CanEditMembers()
 if not self.draft or self.isNew then return false end;if self.draft.id==Groups.systemIds.LEADERSHIP and not Engine:IsActualGuildLeader()then return false end
 local actor=Engine:Actor();local state=State:GetState();if state and Engine:IsManagedBy(state,actor,self.draft.id)then return true end;return self:CanMutate("groups-manage-members")
end
function Page:CanEditPermissions()return self.draft~=nil and not self.isNew and self.draft.id~=Groups.systemIds.LEADERSHIP and self:CanEditGroup()and self:CanMutate("permissions-manage")end
function Page:ErrorMessage(reason)local key=errorKeys[reason];return key and L[key]or string.format(L["INVALID"],tostring(reason))end

function Page:Select(group)
 self.selectedId=group and group.id;self.isNew=group and Groups:GetGroup(group.id)==nil or false;self.draft=group and HolyStorm.Utils.DeepCopy(group)or nil;self.baseRevision=State:GetPermissionStateStatus().revisionID
 if self.groupList then self.groupList.selected=group;self.groupList:SetSelection(group and group.id)end
 if self.deleteButton then self.deleteButton:SetEnabled(group and not self.isNew and not group.system and self:CanMutate("groups-delete")or false)end;self:RefreshDetails()
end
function Page:RefreshList()
 local summaries=Engine:GetGroupSummaries();self.groupList:SetItems(self:GetGroups(),function(group)local summary=summaries[group.id]or{};return string.format("%s%s  (%d / %d / %d / %d)",group.system and"|TInterface\\Buttons\\LockButton-Locked-Up:12|t "or"",HolyStorm.PolicyUI:DisplayGroupName(group),summary.effectiveMembers or 0,summary.explicitMembers or 0,summary.filters or 0,summary.permissions or 0)end)
 self.groupList:SetSelection(self.selectedId)
end

function Page:EnsurePermissionChecks()
 if not self.permissionTable then return end;local rows={};local query=string.lower(self.permissionSearch and self.permissionSearch:GetText()or"");local leadership=self.draft and self.draft.id==Groups.systemIds.LEADERSHIP;local editable=self:CanEditPermissions()
 for _,id in ipairs(keys(Registry:GetPermissions()))do local definition=Registry:GetPermission(id);local name=definition.label or L[definition.labelKey]or id;local description=definition.description or L[definition.descriptionKey]or id;local category=categoryName(definition);local haystack=string.lower(table.concat({id,name,description,definition.module or"",category}," "));if query==""or haystack:find(query,1,true)then rows[#rows+1]={id=id,assigned=leadership or(self.draft and self.draft.permissions[id]==true),name=name,category=category,module=definition.module or"Core",description=description,disabled=not editable or leadership}end end
 self.permissionTable:SetData(rows)
end
function Page:TogglePermission(row)
 if not row or not self.draft or not self:CanEditPermissions()then return end;self.draft.permissions[row.id]=row.assigned and nil or true;self:EnsurePermissionChecks()
end

function Page:ShowTab(id)
 self.activeTab=id;for key,frame in pairs(self.tabFrames or{})do frame:SetShown(key==id and self.draft~=nil)end;if self.tabGroup then self.tabGroup:SelectTab(id,true)end;self:RefreshDetails()
end

function Page:MembershipRows(draft)
 local rows={};for id in pairs(draft.characterMembers or{})do rows[#rows+1]={source=L["MEMBERSHIP_CHARACTER"],value=id,kind="character"}end;for id in pairs(draft.accountMembers or{})do rows[#rows+1]={source=L["MEMBERSHIP_ACCOUNT"],value=id,kind="account"}end;for id in pairs(draft.guildRanks or{})do rows[#rows+1]={source=L["MEMBERSHIP_GUILD_RANK"],value=id,kind="guild-rank"}end
 if draft.system then rows[#rows+1]={source=L["MEMBERSHIP_SYSTEM"],value=L["PROTECTED_BADGE"],protected=true}end;table.sort(rows,function(a,b)if a.source~=b.source then return a.source<b.source end;return tostring(a.value)<tostring(b.value)end);return rows
end

function Page:RefreshDetails()
 local draft=self.draft;if not draft then for _,frame in pairs(self.tabFrames or{})do frame:Hide()end;if self.empty then self.empty.frame:Show()end;return end
 self.empty.frame:Hide();local active=self.activeTab or"GENERAL";for key,frame in pairs(self.tabFrames)do frame:SetShown(key==active)end;if self.tabGroup then self.tabGroup:SelectTab(active,true)end
 if active=="GENERAL"then
  self.nameEdit:SetText(draft.nameKey and(L[draft.nameKey]or draft.name)or draft.name or"");self.descEdit:SetText(draft.description or"");local editable=not draft.system and self:CanEditGroup();self.nameEdit:SetEnabled(editable);self.descEdit:SetEnabled(editable);self.generalInfo:SetText(string.format("%s: %s\n%s: %s\n%s: %s\n%s: %s\n%s: %s",L["INTERNAL_ID"],draft.id,L["TYPE"],draft.system and L["SYSTEM_GROUP"]or L["CUSTOM_GROUP"],L["CREATOR"],draft.creator or L["NONE"],L["CREATED_AT"],displayTime(draft.createdAt),L["MODIFIED_AT"],displayTime(draft.modifiedAt)))
 elseif active=="MEMBERS"then
  self.membershipTable:SetData(self:MembershipRows(draft));local help=draft.system and L["SYSTEM_ACTION_HELP"]or L["ACCOUNT_MEMBERSHIP_HELP"];if draft.id==Groups.systemIds.LEADERSHIP then help=help.."\n"..L["LEADERSHIP_ACTION_HELP"]end;self.memberHelp:SetText(help);local canEdit=self:CanEditMembers();self.addCharacterButton:SetEnabled(canEdit);self.addAccountButton:SetEnabled(canEdit);self.addRankButton:SetEnabled(canEdit);self.removeMembershipButton:SetEnabled(canEdit)
 elseif active=="PERMISSIONS"then
  self:EnsurePermissionChecks();local leadership=draft.id==Groups.systemIds.LEADERSHIP;local unknown={};for id in pairs(draft.permissions or{})do if not Registry:GetPermission(id)then unknown[#unknown+1]=id end end;table.sort(unknown);local messages={};if leadership then messages[#messages+1]=L["FULL_ACCESS"]..": "..L["FULL_ACCESS_HELP"]end;if#unknown>0 then messages[#messages+1]=L["UNKNOWN_PERMISSIONS"]..": "..table.concat(unknown,", ")end;self.fullAccess:SetText(table.concat(messages,"\n"))
 elseif active=="PERMISSION_MATRIX"then self:RefreshMatrix()
 elseif active=="RULES_FILTERS"then self.ruleList:Refresh();self.filterList:Refresh();self.filterMode:SetValue(draft.filterOperator,L["LOGIC_"..draft.filterOperator]);if self:CanEditMembers()then UIDropDownMenu_EnableDropDown(self.filterMode)else UIDropDownMenu_DisableDropDown(self.filterMode)end
 elseif active=="MANAGERS"then self.managerList:Refresh()
 elseif active=="EFFECTIVE_MEMBERS"then
  local rows={};local query=string.lower(self.memberSearch:GetText()or"");for _,entry in ipairs(Engine:GetEffectiveMembers(draft.id))do local searchable=string.lower((entry.name or"").." "..(entry.rank or"").." "..(entry.accountUUID or""));if query==""or searchable:find(query,1,true)then local reasons={};for _,reason in ipairs(entry.reasons or{})do reasons[#reasons+1]=HolyStorm.PolicyUI:DisplayMembershipReason(reason)end;rows[#rows+1]={name=entry.name,rank=entry.rank or L["NONE"],main=entry.isMain and L["MAIN"]or L["ALT"],sources=table.concat(reasons,", ")}end end;self.effectiveTable:SetData(rows)
 elseif active=="MODULE_SETTINGS"then self.moduleList:Refresh()
 elseif active=="ANALYSIS"then self:Analyze()
 elseif active=="STATUS"then
  local status=State:GetPermissionStateStatus();local statusLabel=L["STATE_"..tostring(status.status)]or status.status or L["NONE"];local text=string.format(L["STATE_DETAILS_FORMAT"],tostring(status.guildId or L["NONE"]),statusLabel,status.version or 0,status.revisionID or L["NONE"],status.previousRevisionID or L["NONE"],tostring(status.lastSync or 0),tostring(status.changedBy and(status.changedBy.characterUUID or status.changedBy.accountUUID)or L["NONE"]),tostring(status.changedAt or L["NONE"]),status.historyLength or 0,status.rejectedLength or 0,tostring(status.missingRevisions and(status.missingRevisions.target or status.missingRevisions.after)or L["NONE"]),tostring(status.fork and(status.fork.remoteRevision or status.fork.reason)or L["NONE"]));if status.catchup then text=text.."\n"..string.format(L["CATCHUP_FORMAT"],tostring(status.catchup.requestedAfter or L["NONE"]),status.catchup.receivedCount or 0,status.catchup.validatedCount or 0,tostring(status.catchup.respondingPeer or L["NONE"]))end;self.statusText:SetText(text)
 end
end

function Page:CommitEdits()if not self.draft or self.draft.system then return end;self.draft.name=self.nameEdit:GetText();self.draft.nameKey=nil;self.draft.description=self.descEdit:GetText()end
function Page:Save()
 if not self.draft then return end;if self.baseRevision~=State:GetPermissionStateStatus().revisionID then HolyStorm.Events:Emit("HS_UI_STATUS_REQUESTED",L["STALE_EDITOR"]);return end;self:CommitEdits();local ok,result;if self.isNew then ok,result=Groups:CreateGroup({id=self.draft.id,name=self.draft.name,description=self.draft.description})else ok,result=Groups:SaveGroup(self.draft)end
 if ok then self:Select(Groups:GetGroup(self.draft.id));self:RefreshList();HolyStorm.Events:Emit("HS_UI_STATUS_REQUESTED",L["SAVED"])else HolyStorm.Events:Emit("HS_UI_STATUS_REQUESTED",self:ErrorMessage(result))end
end

function Page:RefreshMatrix()
 local rows={};local matrix=Engine:GetPermissionMatrix();local query=string.lower(self.matrixSearch:GetText()or"")
 for _,row in ipairs(matrix.rows)do local definition=row.definition;local name=definition.label or L[definition.labelKey]or row.permissionId;local description=definition.description or L[definition.descriptionKey]or"";local searchable=string.lower(table.concat({row.permissionId,name,description,definition.module or"",definition.category or""}," "));if query==""or searchable:find(query,1,true)then local defaults,direct,effective={},{},{};for _,groupId in ipairs(matrix.groupIds)do local assignment=row.assignments[groupId];local groupName=HolyStorm.PolicyUI:DisplayGroupName(matrix.groups[groupId]);if assignment.default then defaults[#defaults+1]=groupName end;if assignment.direct then direct[#direct+1]=groupName end;if assignment.effective then effective[#effective+1]=groupName end end;rows[#rows+1]={id=row.permissionId,name=name,module=definition.module or"Core",defaults=#defaults>0 and table.concat(defaults,", ")or L["NONE"],direct=#direct>0 and table.concat(direct,", ")or L["NONE"],effective=#effective>0 and table.concat(effective,", ")or L["NONE"],available=Engine:HasPermission(nil,nil,row.permissionId)and L["ALLOWED"]or L["DENIED"],description=description}end end
 self.matrixTable:SetData(rows);if not self.selectedPermissionId or not Registry:GetPermission(self.selectedPermissionId)then self.selectedPermissionId=rows[1]and rows[1].id end;self.matrixTable:SetSelection(self.selectedPermissionId);local detail=self.selectedPermissionId and Engine:GetPermissionDetail(self.selectedPermissionId);if not detail then self.matrixDetail:SetText(L["NO_SELECTION"]);return end
 local definition=detail.definition;self.matrixPermission:SetValue(detail.id,definition.label or L[definition.labelKey]or detail.id);local function names(ids)local out={};for _,id in ipairs(ids or{})do out[#out+1]=HolyStorm.PolicyUI:DisplayGroupName(detail.groups[id])end;return#out>0 and table.concat(out,", ")or L["NONE"]end;self.matrixDetail:SetText(string.format(L["PERMISSION_DETAIL_FORMAT"],detail.id,definition.label or L[definition.labelKey]or detail.id,definition.description or L[definition.descriptionKey]or detail.id,definition.module or"Core",categoryName(definition),names(detail.defaultGroupIds),names(detail.directGroupIds),names(detail.effectiveGroupIds),detail.available and L["ALLOWED"]or L["DENIED"]))
end
function Page:Analyze()
 if not self.analysisText or not self.draft then return end;local guid=self.analysisGuid:GetText();if guid==""then guid=UnitGUID("player")end;local playerId=HolyStorm.Data.PlayerStore:GetCharacterOwner(guid)or guid;local reasons=Engine:GetMembershipReasons(self.draft,playerId,guid);local lines={HolyStorm.PolicyUI:DisplayGroupName(self.draft),L["CHARACTER_ID"]..": "..tostring(guid)};for _,reason in ipairs(reasons)do lines[#lines+1]=HolyStorm.PolicyUI:DisplayMembershipReason(reason)end;if#reasons==0 then lines[#lines+1]=L["NONE"]end;lines[#lines+1]="\n"..L["PERMISSIONS"]..": "..table.concat(keys(Engine:GetEffectivePermissions(playerId,guid)),", ");self.analysisText:SetText(table.concat(lines,"\n"))
end

function Page:Render()
 if not self.page or not self.page:IsShown()then return end;self:RefreshList();local current=self.selectedId and Groups:GetGroup(self.selectedId);if self.selectedId and not current and not self.isNew then self:Select(nil)elseif current and not self.draft then self:Select(current)else self:RefreshDetails()end
 local valid=State:GetPermissionStateStatus().status==State.status.VALID;self.newButton:SetEnabled(valid and self:CanMutate("groups-create"));self.duplicateButton:SetEnabled(valid and self.draft~=nil and self:CanMutate("groups-create"));self.deleteButton:SetEnabled(valid and self.draft~=nil and not self.isNew and not self.draft.system and self:CanMutate("groups-delete"));self.saveButton:SetEnabled(valid and self.draft~=nil and(self:CanEditGroup()or self:CanEditMembers()or self:CanEditPermissions()));self.resetButton:SetEnabled(valid and self:CanMutate("permissions-reset"));self.readOnly:SetText(valid and""or L["STATE_READ_ONLY"]);if self.draft and self.baseRevision~=State:GetPermissionStateStatus().revisionID then self.readOnly:SetText(L["STALE_EDITOR"]);self.saveButton:SetEnabled(false)end
end
function Page:DeletionSummary(id)local impact=Groups:GetGroupDeletionImpact(id);if not impact then return L["NONE"]end;return string.format(L["GROUP_DELETE_IMPACT"],impact.characterMembers+impact.accountMembers+impact.guildRanks,impact.filters,impact.rules,impact.permissions,#(impact.managerReferences or{}))end

local function addField(column,label,width)
 local group=HolyStorm.UI.Components:CreateColumn(column.frame,{gap=2});group:Add(HolyStorm.UI.Components:CreateText(group.frame,{text=label,font="GameFontNormalSmall"}),{height=16});local edit=HolyStorm.PolicyUI:Edit(group.frame,width);group:Add(edit,{height=22});column:Add(group,{height=42});return edit
end
local function tabFrame(parent)local frame=CreateFrame("Frame",nil,parent);frame:SetAllPoints(parent);frame:Hide();return frame end

function Page:Build(parent)
 local C=HolyStorm.UI.Components;local page=CreateFrame("Frame",nil,parent);self.page=page;local root=C:CreateColumn(page,{frame=page,gap=8,padding={left=12,right=12,top=8,bottom=10}});root:Add(C:CreateText(page,{text=L["PERMISSIONS_TITLE"],font="GameFontHighlightLarge"}),{height=26})
 local body=C:CreateRow(page,{gap=12});root:Add(body,{weight=1,minHeight=470});local sidebar=C:CreateColumn(body.frame,{gap=6});body:Add(sidebar,{width=230,minWidth=200});self.search=HolyStorm.PolicyUI:Edit(sidebar.frame,200,function()Page:RefreshList()end);sidebar:Add(self.search,{height=24});sidebar:Add(C:CreateText(sidebar.frame,{text=L["GROUP_COUNT_COLUMNS"],font="GameFontDisableSmall"}),{height=18});self.groupList=HolyStorm.PolicyUI:CreateList(sidebar.frame,function(group)Page:Select(group)end);sidebar:Add(self.groupList,{weight=1,minHeight=300})
 local groupActions=C:CreateRow(sidebar.frame,{gap=4});self.newButton=HolyStorm.PolicyUI:Button(groupActions.frame,L["NEW"],62,function()Page:Select({id=HolyStorm.PolicyUI:NewId("group"),name=L["CUSTOM_GROUP"],description="",permissions={},characterMembers={},accountMembers={},guildRanks={},ruleIds={},filterIds={},managerGroupIds={},filterOperator="AND"})end);self.duplicateButton=HolyStorm.PolicyUI:Button(groupActions.frame,L["DUPLICATE"],90,function()if Page.draft then Page:Select({id=HolyStorm.PolicyUI:NewId("group"),name=HolyStorm.PolicyUI:DisplayGroupName(Page.draft).." "..L["COPY_SUFFIX"],description=Page.draft.description or"",permissions={},characterMembers={},accountMembers={},guildRanks={},ruleIds={},filterIds={},managerGroupIds={},filterOperator="AND"})end end);groupActions:Add(self.newButton,{weight=1,minWidth=52});groupActions:Add(self.duplicateButton,{weight=1,minWidth=72});sidebar:Add(groupActions,{height=24});self.deleteButton=HolyStorm.PolicyUI:Button(sidebar.frame,L["DELETE"],100,function()if Page.draft then StaticPopup_Show("HOLYSTORM_GROUP_DELETE",HolyStorm.PolicyUI:DisplayGroupName(Page.draft),Page:DeletionSummary(Page.draft.id),Page.draft.id)end end);sidebar:Add(self.deleteButton,{height=24})
 local detail=C:CreateColumn(body.frame,{gap=6});body:Add(detail,{weight=1,minWidth=520});self.tabGroup=C:CreateTabGroup(detail.frame,{layout="Fill",wrapTabs=true,minTabWidth=105});local tabDefs={};for _,id in ipairs(tabs)do tabDefs[#tabDefs+1]={value=id,text=L[id],icon="Interface\\Icons\\INV_Misc_Note_01"}end;self.tabGroup:SetTabs(tabDefs);self.tabGroup:SetCallback("OnGroupSelected",function(_,_,id)Page:ShowTab(id)end);detail:Add(self.tabGroup,{weight=1,minHeight=390});local host=self.tabGroup:GetContentFrame();self.tabFrames={};for _,id in ipairs(tabs)do self.tabFrames[id]=tabFrame(host)end;self.empty=C:CreateEmptyState(host,{text=L["NO_SELECTION"]});self.empty.frame:SetAllPoints(host)

 local general=C:CreateColumn(self.tabFrames.GENERAL,{frame=self.tabFrames.GENERAL,gap=6,padding=6});self.nameEdit=addField(general,L["NAME"],300);self.descEdit=addField(general,L["DESCRIPTION"],500);self.generalInfo=HolyStorm.PolicyUI:Label(general.frame,"");self.generalInfo:SetWordWrap(true);general:Add(self.generalInfo,{weight=1,minHeight=100})
 local members=C:CreateColumn(self.tabFrames.MEMBERS,{frame=self.tabFrames.MEMBERS,gap=6,padding=6});self.membershipTable=C:CreateTable(members.frame,{emptyText=L["EMPTY_MEMBERS"],columns={{id="source",title=L["SOURCES"],width=180},{id="value",title=L["VALUE"],weight=1,truncate=true}}});members:Add(self.membershipTable,{weight=1,minHeight=180});self.memberHelp=HolyStorm.PolicyUI:Label(members.frame,"");self.memberHelp:SetWordWrap(true);members:Add(self.memberHelp,{height=48});local addRow=C:CreateRow(members.frame,{gap=4});self.characterSelector=HolyStorm.PolicyUI:CreateSelector(addRow.frame,190,function()return HolyStorm.PolicyUI:CharacterItems()end);self.addCharacterButton=HolyStorm.PolicyUI:Button(addRow.frame,L["ADD_CHARACTER"],125,function()local id=Page.characterSelector:GetValue();if Page.draft and id and Page:CanEditMembers()then Page.draft.characterMembers[id]=true;Page:RefreshDetails()end end);self.accountSelector=HolyStorm.PolicyUI:CreateSelector(addRow.frame,190,function()return HolyStorm.PolicyUI:AccountItems()end);self.addAccountButton=HolyStorm.PolicyUI:Button(addRow.frame,L["ADD_ACCOUNT"],115,function()local id=Page.accountSelector:GetValue();if Page.draft and id and Page:CanEditMembers()then Page.draft.accountMembers[id]=true;Page:RefreshDetails()end end);addRow:Add(self.characterSelector,{weight=1,minWidth=150});addRow:Add(self.addCharacterButton,{width=125});addRow:Add(self.accountSelector,{weight=1,minWidth=150});addRow:Add(self.addAccountButton,{width=115});members:Add(addRow,{height=24})
 local removeRow=C:CreateRow(members.frame,{gap=4});self.removeSource=HolyStorm.PolicyUI:CreateSelector(removeRow.frame,210,function()local out={};if Page.draft then for id in pairs(Page.draft.characterMembers)do out[#out+1]={value="character\031"..id,label=L["MEMBERSHIP_CHARACTER"]..": "..id}end;for id in pairs(Page.draft.accountMembers)do out[#out+1]={value="account\031"..id,label=L["MEMBERSHIP_ACCOUNT"]..": "..id}end;for id in pairs(Page.draft.guildRanks)do out[#out+1]={value="guild-rank\031"..id,label=L["MEMBERSHIP_GUILD_RANK"]..": "..id}end end;return out end);self.removeMembershipButton=HolyStorm.PolicyUI:Button(removeRow.frame,L["REMOVE_SOURCE"],145,function()local source,id=tostring(Page.removeSource:GetValue()or""):match("^(.-)\031(.+)$");if Page.draft and source and Page:CanEditMembers()then local map=source=="character"and Page.draft.characterMembers or source=="account"and Page.draft.accountMembers or Page.draft.guildRanks;map[tonumber(id)or id]=nil;Page:RefreshDetails()end end);self.rankSelector=HolyStorm.PolicyUI:CreateSelector(removeRow.frame,170,function()local out,guild={},HolyStorm.Data.GuildStore:GetCurrent();for index,name in pairs(guild and guild.ranks or{})do out[#out+1]={value=index-1,label=name}end;return out end);self.addRankButton=HolyStorm.PolicyUI:Button(removeRow.frame,L["ADD_GUILD_RANK"],120,function()local rank=Page.rankSelector:GetValue();if Page.draft and rank~=nil and Page:CanEditMembers()then Page.draft.guildRanks[rank]=true;Page:RefreshDetails()end end);removeRow:Add(self.removeSource,{weight=1,minWidth=150});removeRow:Add(self.removeMembershipButton,{width=145});removeRow:Add(self.rankSelector,{weight=1,minWidth=130});removeRow:Add(self.addRankButton,{width=120});members:Add(removeRow,{height=24})

 local permissions=C:CreateColumn(self.tabFrames.PERMISSIONS,{frame=self.tabFrames.PERMISSIONS,gap=6,padding=6});self.permissionSearch=HolyStorm.PolicyUI:Edit(permissions.frame,240,function()Page:EnsurePermissionChecks()end);permissions:Add(self.permissionSearch,{height=24});self.permissionTable=C:CreateTable(permissions.frame,{emptyText=L["EMPTY_PERMISSIONS"],rowHeight=26,columns={{id="assigned",title="",width=34,align="CENTER",value=function(row)return row.assigned and"|cff20ff20✓|r"or"□"end},{id="name",title=L["NAME"],weight=2,minWidth=130,truncate=true},{id="category",title=L["CATEGORY"],weight=1,minWidth=90,truncate=true},{id="module",title=L["MODULE"],weight=1,minWidth=80,truncate=true}},onRowClick=function(row)Page:TogglePermission(row)end,rowTooltip=function(row)return row.description.."\n"..row.id end,isRowDisabled=function(row)return row.disabled end});permissions:Add(self.permissionTable,{weight=1,minHeight=240});self.fullAccess=HolyStorm.PolicyUI:Label(permissions.frame,"");self.fullAccess:SetWordWrap(true);permissions:Add(self.fullAccess,{height=46})
 local matrix=C:CreateColumn(self.tabFrames.PERMISSION_MATRIX,{frame=self.tabFrames.PERMISSION_MATRIX,gap=6,padding=6});local matrixTools=C:CreateRow(matrix.frame,{gap=6});self.matrixSearch=HolyStorm.PolicyUI:Edit(matrixTools.frame,220,function()Page:RefreshMatrix()end);self.matrixPermission=HolyStorm.PolicyUI:CreateSelector(matrixTools.frame,280,function()local out={};for id,definition in pairs(Registry:GetPermissions())do out[#out+1]={value=id,label=L[definition.labelKey]or id}end;table.sort(out,function(a,b)return a.label<b.label end);return out end,function(id)Page.selectedPermissionId=id;Page:RefreshMatrix()end);matrixTools:Add(self.matrixSearch,{weight=1,minWidth=160});matrixTools:Add(self.matrixPermission,{weight=1,minWidth=220});matrix:Add(matrixTools,{height=24});self.matrixTable=C:CreateTable(matrix.frame,{emptyText=L["EMPTY_PERMISSIONS"],columns={{id="name",title=L["NAME"],weight=1.5,minWidth=120,truncate=true},{id="module",title=L["MODULE"],width=100,truncate=true},{id="defaults",title=L["DEFAULT_GROUPS"],weight=1,minWidth=90,truncate=true},{id="direct",title=L["DIRECT_GROUPS"],weight=1,minWidth=90,truncate=true},{id="available",title=L["RESULT"],width=85}},onRowClick=function(row)Page.selectedPermissionId=row.id;Page:RefreshMatrix()end,rowTooltip=function(row)return row.description.."\n"..row.id end});matrix:Add(self.matrixTable,{weight=1,minHeight=200});self.matrixDetail=HolyStorm.PolicyUI:Label(matrix.frame,"");self.matrixDetail:SetWordWrap(true);self.matrixDetail:SetJustifyV("TOP");matrix:Add(self.matrixDetail,{height=90})

 local rulesFilters=C:CreateRow(self.tabFrames.RULES_FILTERS,{frame=self.tabFrames.RULES_FILTERS,gap=12,padding=6});local rulesColumn=C:CreateColumn(rulesFilters.frame,{gap=5});rulesColumn:Add(C:CreateText(rulesColumn.frame,{text=L["RULES_TITLE"],font="GameFontNormal"}),{height=22});self.ruleList=HolyStorm.PolicyUI:CreateCheckList(rulesColumn.frame,function()local out={};for id,rule in pairs(Filters:GetRules("global"))do out[#out+1]={value=id,label=rule.name,checked=Page.draft and contains(Page.draft.ruleIds,id),disabled=not Page:CanEditMembers()}end;table.sort(out,function(a,b)return a.label<b.label end);return out end,function(id,checked)if Page.draft and Page:CanEditMembers()then Page.draft.ruleIds=setArrayValue(Page.draft.ruleIds,id,checked)end end);rulesColumn:Add(self.ruleList,{weight=1});rulesFilters:Add(rulesColumn,{weight=1,minWidth=220});local filterColumn=C:CreateColumn(rulesFilters.frame,{gap=5});filterColumn:Add(C:CreateText(filterColumn.frame,{text=L["FILTERS_TITLE"],font="GameFontNormal"}),{height=22});self.filterMode=HolyStorm.PolicyUI:CreateSelector(filterColumn.frame,140,function()return{{value="AND",label=L["LOGIC_AND"]},{value="OR",label=L["LOGIC_OR"]}}end,function(value)if Page.draft and Page:CanEditMembers()then Page.draft.filterOperator=value end end);filterColumn:Add(self.filterMode,{height=24});self.filterList=HolyStorm.PolicyUI:CreateCheckList(filterColumn.frame,function()local out={};for id,filter in pairs(Filters:GetFilters("global"))do out[#out+1]={value=id,label=filter.name,checked=Page.draft and contains(Page.draft.filterIds,id),disabled=not Page:CanEditMembers()}end;table.sort(out,function(a,b)return a.label<b.label end);return out end,function(id,checked)if Page.draft and Page:CanEditMembers()then Page.draft.filterIds=setArrayValue(Page.draft.filterIds,id,checked)end end);filterColumn:Add(self.filterList,{weight=1});rulesFilters:Add(filterColumn,{weight=1,minWidth=220})
 local managers=C:CreateColumn(self.tabFrames.MANAGERS,{frame=self.tabFrames.MANAGERS,gap=6,padding=6});managers:Add(C:CreateText(managers.frame,{text=L["MANAGER_GROUPS"],font="GameFontNormal"}),{height=22});local managerHelp=C:CreateText(managers.frame,{text=L["MANAGEMENT_HELP"],wrap=true});managers:Add(managerHelp,{height=42});self.managerList=HolyStorm.PolicyUI:CreateCheckList(managers.frame,function()local out={};for _,item in ipairs(HolyStorm.PolicyUI:GroupItems(Page.draft and Page.draft.id))do item.checked=Page.draft and contains(Page.draft.managerGroupIds,item.value);item.disabled=item.disabled or Page.draft.system or not Page:CanEditGroup();out[#out+1]=item end;return out end,function(id,checked)if Page.draft and not Page.draft.system and Page:CanEditGroup()then Page.draft.managerGroupIds=setArrayValue(Page.draft.managerGroupIds,id,checked)end end);managers:Add(self.managerList,{weight=1})
 local effective=C:CreateColumn(self.tabFrames.EFFECTIVE_MEMBERS,{frame=self.tabFrames.EFFECTIVE_MEMBERS,gap=6,padding=6});self.memberSearch=HolyStorm.PolicyUI:Edit(effective.frame,240,function()Page:RefreshDetails()end);effective:Add(self.memberSearch,{height=24});self.effectiveTable=C:CreateTable(effective.frame,{emptyText=L["EMPTY_MEMBERS"],columns={{id="name",title=L["NAME"],weight=1,minWidth=110},{id="rank",title=L["GUILD_RANK"],width=120},{id="main",title=L["MAIN_TWINK"],width=80},{id="sources",title=L["SOURCES"],weight=2,minWidth=180,truncate=true}},rowTooltip=function(row)return row.sources end});effective:Add(self.effectiveTable,{weight=1})
 local modules=C:CreateColumn(self.tabFrames.MODULE_SETTINGS,{frame=self.tabFrames.MODULE_SETTINGS,gap=6,padding=6});modules:Add(C:CreateText(modules.frame,{text=L["MODULE_MODEL_HELP"],wrap=true}),{height=48});self.moduleList=HolyStorm.PolicyUI:CreateCheckList(modules.frame,function()local out={};for _,metadata in ipairs(HolyStorm:GetModuleEntries())do local id=metadata and metadata.internalName;if id and metadata.category=="optional"then out[#out+1]={value=id,label=metadata.displayName or id,checked=State:IsGuildModuleEnabled(id),disabled=not Page:CanMutate("modules-manage")}end end;return out end,function(id,checked)local ok,reason=State:SetGuildModuleEnabled(id,checked);if not ok then HolyStorm.Events:Emit("HS_UI_STATUS_REQUESTED",Page:ErrorMessage(reason))end end);modules:Add(self.moduleList,{weight=1})
 local analysis=C:CreateColumn(self.tabFrames.ANALYSIS,{frame=self.tabFrames.ANALYSIS,gap=6,padding=6});local analysisTools=C:CreateRow(analysis.frame,{gap=6});self.analysisGuid=HolyStorm.PolicyUI:Edit(analysisTools.frame,300);analysisTools:Add(self.analysisGuid,{weight=1,minWidth=180});analysisTools:Add(HolyStorm.PolicyUI:Button(analysisTools.frame,L["ANALYSIS"],90,function()Page:Analyze()end),{width=90});analysis:Add(analysisTools,{height=24});local analysisScroll;analysisScroll,self.analysisText=HolyStorm.PolicyUI:CreateTextPanel(analysis.frame);analysis:Add(analysisScroll,{weight=1})
 local statusLayout=C:CreateColumn(self.tabFrames.STATUS,{frame=self.tabFrames.STATUS,padding=6});local statusScroll;statusScroll,self.statusText=HolyStorm.PolicyUI:CreateTextPanel(statusLayout.frame);statusLayout:Add(statusScroll,{weight=1})
 self.readOnly=HolyStorm.PolicyUI:Label(detail.frame,"");self.readOnly:SetWordWrap(true);detail:Add(self.readOnly,{height=20});local footer=C:CreateRow(detail.frame,{gap=6});self.resetButton=HolyStorm.PolicyUI:Button(footer.frame,L["RESTORE_DEFAULTS"],150,function()StaticPopup_Show("HOLYSTORM_PERMISSION_RESET")end);self.saveButton=HolyStorm.PolicyUI:Button(footer.frame,L["SAVE"],100,function()Page:Save()end);local discard=HolyStorm.PolicyUI:Button(footer.frame,L["DISCARD"],100,function()Page:Select(Page.selectedId and Groups:GetGroup(Page.selectedId));HolyStorm.Events:Emit("HS_UI_STATUS_REQUESTED",L["DISCARDED"])end);footer:Add(self.resetButton,{width=150});footer:Add(C:CreateText(footer.frame,{text=""}),{weight=1});footer:Add(self.saveButton,{width=100});footer:Add(discard,{width=100});detail:Add(footer,{height=24})
 self.activeTab="GENERAL";self:Select(nil);root:Relayout();return page
end

function Page:RegisterDialogs()
 StaticPopupDialogs.HOLYSTORM_PERMISSION_RESET={text=L["CONFIRM_PERMISSION_RESET"],button1=L["YES"],button2=L["NO"],OnAccept=function()local ok,reason=State:RestoreDefaults();HolyStorm.Events:Emit("HS_UI_STATUS_REQUESTED",ok and L["RESET_COMPLETE"]or Page:ErrorMessage(reason));Page:Render()end,timeout=0,whileDead=true,hideOnEscape=true,preferredIndex=3}
 StaticPopupDialogs.HOLYSTORM_GROUP_DELETE={text=L["CONFIRM_GROUP_DELETE"],button1=L["DELETE"],button2=L["NO"],OnAccept=function(_,id)local ok,reason=Groups:DeleteGroup(id);if ok then Page:Select(nil);Page:RefreshList()else HolyStorm.Events:Emit("HS_UI_STATUS_REQUESTED",Page:ErrorMessage(reason))end end,timeout=0,whileDead=true,hideOnEscape=true,preferredIndex=3}
end
function Page:OnInitialize()
 self:RegisterDialogs();HolyStorm.Administration:RegisterSection({id="permissions",category="permissions",displayName=L["PERMISSIONS_TITLE"],displayNameKey="PERMISSIONS_TITLE",description=L["PERMISSIONS_DESC"],descriptionKey="PERMISSIONS_DESC",order=10,requiredPermission={"groups-create","groups-edit","groups-delete","groups-manage-members","permissions-manage","permissions-reset","modules-manage","policy-inspect"},owner="Core",build=function(parent)return Page:Build(parent)end,icon="Interface\\Icons\\Achievement_GuildPerk_EverybodysFriend",refresh=function()Page:Render()end,events={"HS_GROUP_UPDATED","HS_GROUP_DELETED","HS_EFFECTIVE_MEMBERSHIP_CHANGED","HS_EFFECTIVE_PERMISSIONS_CHANGED","HS_FILTER_UPDATED","HS_FILTER_DELETED","HS_RULE_UPDATED","HS_RULE_DELETED","HS_PERMISSION_REGISTERED","HS_PERMISSIONS_STATE_UPDATED","HS_PERMISSIONS_CATCHUP_STARTED","HS_PERMISSIONS_CATCHUP_COMPLETED","HS_PERMISSIONS_RECOVERY_REQUIRED","HS_PERMISSIONS_CONFLICT_DETECTED","HS_ROSTER_UPDATED","HS_CHARACTER_UPDATED"}})
end
