local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm")
local L=LibStub("AceLocale-3.0"):GetLocale("Holy_Storm_Policy")
local Page=HolyStorm:RegisterRequiredModule("PolicyInspectorUI")
local Engine,Filters,State,Registry=HolyStorm.PermissionEngine,HolyStorm.FilterManager,HolyStorm.PolicyState,HolyStorm.PermissionRegistry
local DEFAULT_SCOPE="global"
HolyStorm:ApplyModuleMetadata(Page,{displayName=L["INSPECTOR_TITLE"],internalName="policyInspectorUI",version="2.2.0",category="required",description=L["INSPECTOR_DESC"],permissions={"policy-inspect"},dependencies={"core","ui"},enabledByDefault=true})
local function displayReason(reason)return HolyStorm.PolicyUI:DisplayMembershipReason(reason)end
local function defaultPermission()local ids={};for id in pairs(Registry:GetPermissions())do ids[#ids+1]=id end;table.sort(ids);return ids[1]or""end
local function displayTime(value)value=tonumber(value);return value and value>0 and date("%Y-%m-%d %H:%M:%S",value)or"—"end
function Page:Inspect()
 local guid=self.character:GetValue()or UnitGUID("player");local accountUUID=guid and((HolyStorm.TwinkCore and HolyStorm.TwinkCore:GetAccountUUIDForCharacter(guid))or HolyStorm.Data.PlayerStore:GetCharacterOwner(guid));local permission=self.permission:GetText();local explanation=Engine:Explain(permission,accountUUID,guid,self.target:GetText());local state=State:GetPermissionStateStatus();local actor=state.changedBy and table.concat({state.changedBy.accountUUID or"-",state.changedBy.characterUUID or"-"}," / ")or"-";local missing=state.missingRevisions and tostring(state.missingRevisions.after or"-").." -> "..tostring(state.missingRevisions.target or"-")or"-";local fork=state.fork and tostring(state.fork.localRevision or"-").." <> "..tostring(state.fork.remoteRevision or"-")or"-";local lines={L["IDENTITY"],L["CHARACTER"]..": "..tostring(guid),L["ACCOUNT_MEMBERS"]..": "..tostring(accountUUID),"",string.format(L["STATE_DETAILS_FORMAT"],tostring(state.guildId or"-"),L["STATE_"..tostring(state.status)]or tostring(state.status),state.version or 0,tostring(state.revisionID or"-"),tostring(state.previousRevisionID or"-"),displayTime(state.lastSync),actor,displayTime(state.changedAt),state.historyLength or 0,state.rejectedLength or 0,missing,fork),L["RESULT"]..": "..(explanation.allowed and L["ALLOWED"]or L["DENIED"]),"",L["EFFECTIVE_MEMBERS"]}
 for id,group in pairs(explanation.groups)do local sources={};for _,reason in ipairs(group.reasons or{})do sources[#sources+1]=displayReason(reason)end;lines[#lines+1]=string.format("• %s (%s) — %s",HolyStorm.PolicyUI:DisplayGroupName(group),id,table.concat(sources,", "))end
 lines[#lines+1]="";lines[#lines+1]=L["SOURCES"];for _,grant in ipairs(explanation.grants)do lines[#lines+1]="✓ "..HolyStorm.PolicyUI:DisplayGroupName(grant) end;if#explanation.grants==0 then lines[#lines+1]="— "..L["NONE"]end
 local filterId=self.filter:GetText();if filterId~=""then local result,trace,status=Filters:ApplyFilter(filterId,{guid=guid},self.filterScope:GetText()=="local"and"local"or"global");local label=status==HolyStorm.Rules.Result.UNKNOWN and L["UNKNOWN"]or result and L["PASSED"]or L["FAILED"];lines[#lines+1]="";lines[#lines+1]=L["FILTER_REASON"].." "..filterId..": "..label;lines[#lines+1]=HolyStorm.PolicyUI:FlattenTrace(trace)end
 lines[#lines+1]="";lines[#lines+1]=L["REVISION_HISTORY"];for _,revision in ipairs(State:GetRevisionHistory())do lines[#lines+1]=string.format("v%d | %s | %s | %s | %s",revision.version or 0,tostring(revision.revisionID),tostring(revision.previousRevisionID),tostring(revision.action or(revision.change and revision.change.action)),displayTime(revision.changedAt))end
 lines[#lines+1]="";lines[#lines+1]=L["REJECTED_REVISIONS"];for _,rejected in ipairs(State:GetRejectedRevisions())do lines[#lines+1]=string.format("%s | %s | %s | %s",tostring(rejected.revisionID),tostring(rejected.sender),tostring(rejected.reason),displayTime(rejected.timestamp))end
 if state.missingRevisions or state.recovery or state.fork then lines[#lines+1]="";lines[#lines+1]=L["STATUS"]..": "..tostring(state.catchupReason or(state.recovery and state.recovery.reason)or(state.fork and state.fork.reason)or state.status)end;self.output:SetText(table.concat(lines,"\n"))
end
function Page:OnInitialize()
 HolyStorm.Administration:RegisterSection({id="policyInspector",category="system",displayName=L["INSPECTOR_TITLE"],displayNameKey="INSPECTOR_TITLE",description=L["INSPECTOR_DESC"],descriptionKey="INSPECTOR_DESC",order=10,requiredPermission="policy-inspect",owner="Core",build=function(parent)return Page:Build(parent)end,refresh=function()Page:Inspect()end,events={"HS_POLICY_UPDATED","HS_PERMISSIONS_REVISION_REJECTED","HS_PERMISSIONS_CONFLICT_DETECTED","HS_PERMISSIONS_RECOVERY_REQUIRED"},icon="Interface\\Icons\\INV_Misc_Eye_01"})
end

function Page:Build(parent)
 local C=HolyStorm.UI.Components;local p=CreateFrame("Frame",nil,parent);self.page=p;local root=C:CreateColumn(p,{frame=p,gap=8,padding={left=12,right=12,top=8,bottom=10}});root:Add(C:CreateText(p,{text=L["INSPECTOR_TITLE"],font="GameFontHighlightLarge"}),{height=26})
 local inputs=C:CreateRow(p,{gap=8});local function labeled(label,control,track)local column=C:CreateColumn(inputs.frame,{gap=2});column:Add(C:CreateText(column.frame,{text=label,font="GameFontNormalSmall"}),{height=16});column:Add(control,{height=22});inputs:Add(column,track);return control end
 self.character=labeled(L["CHARACTER"],HolyStorm.PolicyUI:CreateSelector(inputs.frame,240,function()return HolyStorm.PolicyUI:CharacterItems()end),{weight=2,minWidth=180});self.permission=labeled(L["ACTION"],HolyStorm.PolicyUI:Edit(inputs.frame,220),{weight=2,minWidth=150});self.permission:SetText(defaultPermission());self.target=labeled(L["TARGET"],HolyStorm.PolicyUI:Edit(inputs.frame,160),{weight=1.5,minWidth=110});self.filter=labeled(L["FILTER"],HolyStorm.PolicyUI:Edit(inputs.frame,160),{weight=1.5,minWidth=110});self.filterScope=labeled(L["SCOPE"],HolyStorm.PolicyUI:Edit(inputs.frame,90),{width=100});self.filterScope:SetText(DEFAULT_SCOPE);root:Add(inputs,{height=42})
 local actions=C:CreateRow(p,{gap=6});local inspect=HolyStorm.PolicyUI:Button(actions.frame,L["ANALYSIS"],100,function()Page:Inspect()end);actions:Add(inspect,{width=100});root:Add(actions,{height=24});local scroll,text=HolyStorm.PolicyUI:CreateTextPanel(p);self.output=text;root:Add(scroll,{weight=1,minHeight=260});root:Relayout();return p
end
