local addonVersion="1.3.0"
local L=LibStub("AceLocale-3.0"):NewLocale("Holy_Storm_Policy","enUS",true)
L["UNKNOWN"]="Unknown"
L["PERMISSIONS_TITLE"]="Permissions";L["PERMISSIONS_DESC"]="Manage policy groups, memberships and granular permissions."
L["RULES_TITLE"]="Rules";L["RULES_DESC"]="Create, combine and test reusable rules."
L["FILTERS_TITLE"]="Filters";L["FILTERS_DESC"]="Manage local filters, global guild filters and templates."
L["INSPECTOR_TITLE"]="Policy Inspector";L["INSPECTOR_DESC"]="Explain permissions, memberships and filter results."
L["GROUP_GUILD_LEADERSHIP"]="Guild Leadership";L["GROUP_OFFICERS"]="Officers";L["GROUP_GUILD_MEMBER"]="Guild Member";L["GROUP_DESC_GUILD_LEADERSHIP"]="Protected leadership group with full access.";L["GROUP_DESC_OFFICERS"]="Officers, including the dynamic rank-1 membership.";L["GROUP_DESC_GUILD_MEMBER"]="All current guild members.";L["SYSTEM_GROUP"]="System group";L["CUSTOM_GROUP"]="Custom group"
L["SEARCH"]="Search";L["NEW"]="New";L["DUPLICATE"]="Duplicate";L["DELETE"]="Delete";L["SAVE"]="Save";L["DISCARD"]="Discard";L["TEST"]="Test";L["RESET"]="Reset all";L["MANAGE_FILTERS"]="Manage filters";L["FILTER"]="Filter"
L["GENERAL"]="General";L["MEMBERS"]="Members";L["PERMISSIONS"]="Permissions";L["RULES_FILTERS"]="Rules & Filters";L["MANAGERS"]="Managers";L["EFFECTIVE_MEMBERS"]="Effective";L["ANALYSIS"]="Analysis";L["STATUS"]="Status"
L["LOCAL_FILTERS"]="Local filters";L["GLOBAL_FILTERS"]="Global filters";L["TEMPLATES"]="Templates";L["LOCAL_RULES"]="Local rules";L["GLOBAL_RULES"]="Global rules"
L["NAME"]="Name";L["DESCRIPTION"]="Description";L["INTERNAL_ID"]="Internal ID";L["VERSION"]="Version";L["UPDATED_BY"]="Updated by";L["UPDATED_AT"]="Updated at";L["SCOPE"]="Scope";L["USAGE"]="Usage"
L["MANUAL"]="Manual";L["GUILD_RANK"]="Guild rank";L["RULE"]="Rule";L["FILTER_REASON"]="Filter";L["SYSTEM"]="System rule";L["MEMBERSHIP_REASON"]="Membership reason"
L["FIELD"]="Field";L["OPERATOR"]="Operator";L["VALUE"]="Value";L["LOGIC"]="Logic";L["ADD_CONDITION"]="Add condition";L["ADD_GROUP"]="Add group";L["REMOVE"]="Remove";L["MATCHES"]="%d of %d characters match.";L["MATCHES_WITH_UNKNOWN"]="%d of %d characters match; %d results are unknown."
L["CHARACTER"]="Character";L["ACTION"]="Permission / action";L["MODULE"]="Module";L["TARGET"]="Target";L["RESULT"]="Result";L["ALLOWED"]="ALLOWED";L["DENIED"]="DENIED";L["CURRENT_VALUE"]="Current value";L["EXPECTED_VALUE"]="Expected value";L["PASSED"]="passed";L["FAILED"]="failed"
L["NO_SELECTION"]="Select an entry.";L["NO_PERMISSION"]="You do not have permission for this action.";L["INVALID"]="The draft is invalid: %s";L["SAVED"]="Changes saved.";L["DISCARDED"]="Draft discarded.";L["CONFIRM_DELETE"]="Delete this entry?";L["CANNOT_DELETE_SYSTEM"]="System groups cannot be deleted."
L["YES"]="Yes";L["NO"]="No";L["CREATOR"]="Creator";L["CHARACTER_MEMBERS"]="Character memberships";L["ACCOUNT_MEMBERS"]="Account memberships";L["ADD_CHARACTER"]="Add character";L["ADD_ACCOUNT"]="Add account";L["MANAGER_GROUPS"]="Manager group IDs";L["CONFIRM_PERMISSION_RESET"]="Restore permission defaults? Groups, permissions, guild-wide rules and filters, and policy/module configuration will be reset. All other Holy Storm data and personal local filters remain unchanged.";L["RESET_COMPLETE"]="Permission defaults restored.";L["REVISION_STATUS_FORMAT"]="State: %s\nVersion: %d\nRevision: %s\nPrevious: %s\nHistory: %d\nLast sync: %s";L["STATE_DETAILS_FORMAT"]="Guild: %s\nState: %s\nVersion: %d\nRevision: %s\nPrevious: %s\nLast sync: %s\nChanged by: %s\nChanged at: %s\nHistory: %d\nRejected revisions: %d\nMissing revisions: %s\nFork: %s"
L["UNKNOWN_PERMISSIONS"]="Unknown permissions"
L["PERMISSION_GROUPS_CREATE"]="Create groups";L["PERMISSION_GROUPS_EDIT"]="Edit groups";L["PERMISSION_GROUPS_DELETE"]="Delete groups";L["PERMISSION_GROUPS_MANAGE_MEMBERS"]="Manage group members";L["PERMISSION_PERMISSIONS_MANAGE"]="Assign permissions";L["PERMISSION_PERMISSIONS_RESET"]="Restore permission defaults";L["PERMISSION_FILTERS_CREATE"]="Create filters";L["PERMISSION_FILTERS_EDIT"]="Edit filters";L["PERMISSION_FILTERS_DELETE"]="Delete filters";L["PERMISSION_RULES_MANAGE"]="Manage rules";L["PERMISSION_POLICY_INSPECT"]="Inspect policies";L["PERMISSION_MODULES_MANAGE"]="Manage guild modules"
local adminDescriptions={GROUPS_CREATE="Create groups.",GROUPS_EDIT="Edit groups.",GROUPS_DELETE="Delete groups.",GROUPS_MANAGE_MEMBERS="Manage group members.",PERMISSIONS_MANAGE="Assign permissions.",PERMISSIONS_RESET="Restore permission defaults.",FILTERS_CREATE="Create filters.",FILTERS_EDIT="Edit filters.",FILTERS_DELETE="Delete filters.",RULES_MANAGE="Manage rules.",POLICY_INSPECT="Inspect policies.",MODULES_MANAGE="Manage guild modules."};for key,value in pairs(adminDescriptions)do L["PERMISSION_DESC_"..key]=value end
local coreExtras={SYNC_RECEIVE="Receive synchronized data",PLAYER_READ="Read player data",SAVEDVARIABLES_READ="Read saved variables",SAVEDVARIABLES_WRITE="Write saved variables",PROFESSIONS_READ="View professions",SETTINGS_READ="Read settings",SETTINGS_WRITE="Change settings"};for key,value in pairs(coreExtras)do L["PERMISSION_"..key]=value;L["PERMISSION_DESC_"..key]=value.."." end
L["ALL_ENABLE"]="Enable all";L["ALL_DISABLE"]="Disable all";L["DEVELOPER_KEYS"]="Show internal keys";L["PUBLISH"]="Publish globally";L["RESTORE_DEFAULTS"]="Restore defaults";L["ACTIVE_FILTERS"]="Active filters";L["NONE"]="None"
L["PERMISSION_ROLES_MANAGE"]="Manage groups";L["PERMISSION_PERMISSIONS_MANAGE"]="Manage permissions";L["PERMISSION_FILTERS_MANAGE_GLOBAL"]="Manage global filters";L["PERMISSION_RULES_MANAGE_GLOBAL"]="Manage global rules";L["PERMISSION_POLICY_INSPECT"]="Inspect policies"
L["PERMISSION_TWINKS_ASSIGN"]="Assign twinks";L["PERMISSION_DESC_TWINKS_ASSIGN"]="Administratively assign a character to an account."
L["PERMISSION_TWINKS_REMOVE"]="Remove twink assignments";L["PERMISSION_DESC_TWINKS_REMOVE"]="Remove administrative character-to-account assignments."
L["CATEGORY_ADMINISTRATION"]="Administration";L["CATEGORY_CORE"]="Core";L["CATEGORY_SYNC"]="Sync";L["CATEGORY_ROSTER"]="Roster";L["CATEGORY_CHARACTERS"]="Characters";L["CATEGORY_NEWS"]="News";L["CATEGORY_CALENDAR"]="Calendar";L["CATEGORY_RAID"]="Raid";L["CATEGORY_MYTHIC_"]="Mythic+";L["CATEGORY_DELVES"]="Delves";L["CATEGORY_EQUIPMENT"]="Equipment";L["CATEGORY_LOGS"]="Logs";L["CATEGORY_TASK_MANAGER"]="Task Manager";L["CATEGORY_POI"]="POI";L["CATEGORY_POSITIONS"]="Guild positions"
local names={CORE_SETTINGS_READ="Read core settings",CORE_SETTINGS_WRITE="Change core settings",UI_RENDER="Open the user interface",SYNC_SEND="Send synchronized data",GUILD_ROSTER_READ="View the guild roster",ROSTER_MANAGE="Manage the guild roster",NEWS_VIEW="View news",NEWS_CREATE="Create news",NEWS_EDIT="Edit news",NEWS_DELETE="Delete news",NEWS_PUBLISH="Publish news",NEWS_READ_RECEIPTS="View read receipts",GUIDE_VIEW="View guides",GUIDE_CREATE="Create guides",GUIDE_EDIT="Edit guides",GUIDE_DELETE="Delete guides",GUIDE_PUBLISH="Publish guides",CALENDAR_READ="View calendar events",CALENDAR_MANAGE="Manage calendar events",RAIDS_READ="View raid data",MYTHICPLUS_READ="View Mythic+ data",DELVES_READ="View delve data",EQUIPMENT_READ="View equipment",LOGS_VIEW="View logs",LOGS_CLEAR="Clear logs",TASKMANAGER_VIEW="View Task Manager",TASKMANAGER_CONTROL="Control Task Manager",TASKS_VIEW="View tasks",POI_VIEW="View POIs",POI_CREATE_PERSONAL="Create personal POIs",POI_CREATE_GUILD="Create guild POIs",POI_CREATE_GROUP="Create group POIs",POI_CREATE_RAID="Create raid POIs",POI_EDIT_OWN="Edit own POIs",POI_EDIT_ANY="Edit any POI",POI_DELETE_OWN="Delete own POIs",POI_DELETE_ANY="Delete any POI",POI_CREATE="Create POIs",POI_EDIT="Edit POIs",POI_DELETE="Delete POIs",POSITION_VIEW="View guild positions",POSITION_SHARE="Share guild position"};for key,value in pairs(names)do L["PERMISSION_"..key]=value;L["PERMISSION_DESC_"..key]=value.."."end
L["CATEGORY_ACHIEVEMENTS"]="Achievements";local achievementNames={ACHIEVEMENT_VIEW="View achievements",ACHIEVEMENT_CREATE="Create achievements",ACHIEVEMENT_EDIT="Edit achievements",ACHIEVEMENT_DELETE="Archive achievements",ACHIEVEMENT_PUBLISH="Publish achievements",ACHIEVEMENT_AWARD="Award achievements",ACHIEVEMENT_REVOKE="Revoke awards",ACHIEVEMENT_ADMIN="Administer achievements",ACHIEVEMENT_TEST="Test achievement awards"};for key,value in pairs(achievementNames)do L["PERMISSION_"..key]=value;L["PERMISSION_DESC_"..key]=value.."."end
local legacyDescriptions={ROLES_MANAGE="Manage groups.",PERMISSIONS_MANAGE="Manage permissions.",FILTERS_MANAGE_GLOBAL="Manage global filters.",RULES_MANAGE_GLOBAL="Manage global rules.",POLICY_INSPECT="Inspect policies."};for key,value in pairs(legacyDescriptions)do L["PERMISSION_DESC_"..key]=value end
L["APPLY"]="Apply";L["VALID_EXPRESSION"]="Valid expression";L["INVALID_EXPRESSION"]="Invalid expression: %s";L["LOGIC_AND"]="All (AND)";L["LOGIC_OR"]="Any (OR)";L["LOGIC_NOT"]="Not";L["ACCOUNT_SELECTOR_FORMAT"]="%s — %d known characters";L["GLOBAL_BADGE"]="[Guild] ";L["LOCAL_BADGE"]="[Local] ";L["COPY_SUFFIX"]="Copy";L["PROTECTED_BADGE"]="Locked — system group";L["FULL_ACCESS"]="Full access";L["FULL_ACCESS_HELP"]="Guild Leadership always has every permission.";L["SYSTEM_ACTION_HELP"]="Automatic system memberships cannot be removed.";L["LEADERSHIP_ACTION_HELP"]="Only the current Blizzard guild leader may change additional Guild Leadership members.";L["ACCOUNT_MEMBERSHIP_HELP"]="Future characters discovered for this account automatically become group members.";L["MANAGEMENT_HELP"]="Managing a group does not grant membership or inherit that group's permissions.";L["REMOVE_SOURCE"]="Remove assignment";L["FILTER_COMBINATION"]="Filter combination";L["PERMISSION_MATRIX"]="Permission matrix";L["MODULE_SETTINGS"]="Guild modules";L["TYPE"]="Type";L["EXPLICIT_MEMBERS"]="Explicit";L["FILTER_COUNT"]="Filters";L["PERMISSION_COUNT"]="Permissions";L["CLASS"]="Class";L["MAIN_TWINK"]="Main / alt";L["MAIN"]="Main";L["ALT"]="Alt";L["UNKNOWN"]="unknown / unavailable";L["USED_BY"]="Used by";L["FILTER_IN_USE"]="This filter is still referenced and cannot be deleted.";L["STATE_READ_ONLY"]="Changes are unavailable until the permission state is valid.";L["STALE_EDITOR"]="The permission state changed while this editor was open. Reload before saving.";L["STATE_VALID"]="Permissions synchronized";L["STATE_CATCHING_UP"]="Permissions are synchronizing";L["STATE_RECOVERY_REQUIRED"]="Recovery required";L["STATE_CONFLICT"]="Permission-state conflict detected";L["STATE_UNINITIALIZED"]="Permission state not initialized";L["REVISION_HISTORY"]="Revision history";L["REJECTED_REVISIONS"]="Rejected revisions";L["IDENTITY"]="Identity";L["SOURCES"]="Sources";L["CREATED_AT"]="Created at";L["MODIFIED_AT"]="Modified at"
L["CONFIRM_GROUP_DELETE"]="Delete %s? Its explicit memberships will be removed. Manager references must be removed first.";L["GROUP_IN_USE"]="This group is still referenced as a manager and cannot be deleted."
L["CATCHUP_FORMAT"]="Requested after: %s | received: %d | validated: %d | peer: %s"
L["GROUP_COUNT_COLUMNS"]="effective / explicit / filters / rights"
L["RULE_IN_USE"]="This rule is still referenced and cannot be deleted."
L["ADD_GUILD_RANK"]="Add guild rank"
L["MODULE_MODEL_HELP"]="Availability requires: enabled for this guild, an effective permission, and the user's personal setting. A personal setting cannot override a guild-wide disable."
L["CHARACTER"]="Character";L["MEMBERSHIP_ACCOUNT"]="Account assignment";L["MEMBERSHIP_CHARACTER"]="Character assignment";L["MEMBERSHIP_GUILD_RANK"]="Guild rank";L["MEMBERSHIP_SYSTEM"]="System rule";L["MEMBERSHIP_FILTER"]="Filter";L["MEMBERSHIP_RULE"]="Rule"
for key,label in pairs({["="]="equals",["!="]="not equal",[">"]="greater than",[">="]="at least",["<"]="less than",["<="]="at most",CONTAINS="contains",NOT_CONTAINS="does not contain",STARTS_WITH="starts with",ENDS_WITH="ends with",IN="in",NOT_IN="not in",BETWEEN="between",NOT_BETWEEN="not between",TRUE="is true",FALSE="is false",EXISTS="is available",NOT_EXISTS="is unavailable"})do L["OP_"..key]=label end
