local workspace = (arg[0]:gsub("tools[/\\]test_poi_map.lua$", "")) .. "LIVE/"
local root = workspace .. "Holy_Storm_POI/"
local function read(path)
    local file = assert(io.open(root .. path, "r"))
    local value = file:read("*a")
    file:close()
    return value
end

local xml = read("Map.xml")
assert(not xml:find("inherits=\"MapCanvasPinTemplate\"", 1, true), "POI must not inherit the removed global pin template")
assert(xml:find("MapCanvasPinMixin", 1, true) and xml:find("HolyStormPOIPinMixin", 1, true), "POI pin must use explicit MapCanvas mixins")
assert(not xml:find("<OnEnter", 1, true) and not xml:find("<OnLeave", 1, true), "POI pin must leave MapCanvas mouse scripts unset for its pin acquisition assertion")
assert(xml:find('<Texture parentKey="icon">',1,true) and xml:find('<Anchor point="TOPLEFT"/>',1,true) and xml:find('<Anchor point="BOTTOMRIGHT"/>',1,true),"World Map pin icon must be anchored across the sized pin frame")
assert(xml:find('<Texture parentKey="glow"',1,true) and xml:find('<Anchor point="CENTER"/>',1,true),"World Map pin glow must be centered on its sized pin frame")

local map = read("Map.lua")
assert(map:find("MapCanvasPinMixin", 1, true) and map:find("canvas:AcquirePin(\"HolyStormPOIPinTemplate\"", 1, true), "POI must acquire registered pins through MapCanvas")
assert(map:find("MAPCANVAS_NOT_READY", 1, true) and map:find("worldMapFailed", 1, true), "POI refresh must guard unavailable MapCanvas infrastructure")
assert(map:find("function HolyStormPOIPinMixin:OnMouseEnter", 1, true) and map:find("function HolyStormPOIPinMixin:OnMouseLeave", 1, true), "MapCanvas routes pin mouse interaction through mixin methods")
assert(map:find("TransformForWorldMap", 1, true) and map:find("IsMapRelated", 1, true), "World Map transforms are restricted to related map hierarchy")
assert(map:find("IsValidWorldCoordinate", 1, true) and map:find("lastRenderingFailureReason", 1, true), "World Map validates coordinates and records bounded diagnostics")
assert(not map:find("SetMapID", 1, true), "POI rendering must never mutate World Map navigation state")
assert(map:find("provider:OnMapChanged()", 1, true) and map:find("providerRegistrationCount", 1, true), "provider reacts to map changes and records registration count")
assert(map:find('UseFrameLevelType("PIN_FRAME_LEVEL_AREA_POI")',1,true),"World Map pins use the registered POI frame level range")
assert(map:find("acquirePinAttempts",1,true) and map:find("acquirePinSuccesses",1,true) and map:find("pinsRemovedByReconciliation",1,true),"World Map diagnostics count pin acquisition and reconciliation outcomes")
assert(map:find("GetMinimapSignaturePart",1,true) and map:find('return "temporary",true',1,true),"revisionless temporary markers use an explicit signature component")
assert(map:find("GetMinimapContext()", 1, true) and map:find("transformCache", 1, true), "POI minimap reuses one validated player map context and coordinate transform cache")
assert(map:find("self:UnregisterMinimapUpdater(\"poi\")", 1, true) or map:find("UnregisterMinimapUpdater(\"poi\")", 1, true), "POI removes its shared minimap updater on shutdown")
assert(map:find("RemoveDataProvider", 1, true) and map:find("UnregisterPOIProvider", 1, true), "POI releases world-map and MapLinks providers on shutdown")
assert(map:find("time-self.lastMinimapRefresh<1", 1, true), "POI minimap projection is throttled")
assert(map:find("SetMinimapUpdaterActive(\"poi\"", 1, true), "POI minimap updater is active only while visible POI markers need periodic positioning")

local toc = read("Holy_Storm_POI.toc")
local serviceFile=assert(io.open(root.."POIService.lua","r"));local service=serviceFile:read("*a");serviceFile:close()
local uiFile=assert(io.open(root.."POI.lua","r"));local poiUI=uiFile:read("*a");uiFile:close()
assert(service:find("worldMap=HolyStorm.POIMap",1,true) and poiUI:find('L["DEBUG_WORLD_MAP"]',1,true),"bounded World Map rendering diagnostics are exposed in the existing POI diagnostics view")
local coreTocFile=assert(io.open(workspace.."Holy_Storm/Holy_Storm.toc","r"));local coreToc=coreTocFile:read("*a");coreTocFile:close()
assert(not coreToc:find("Blizzard_MapCanvas", 1, true), "core TOC must not own feature MapCanvas dependencies")
assert(toc:find("## RequiredDeps: Holy_Storm, Holy_Storm_UI, Blizzard_MapCanvas", 1, true), "POI TOC declares its UI and Blizzard MapCanvas dependencies")
assert(toc:find("## X-HolyStorm-Requires: synchronization,ui,options", 1, true), "POI metadata mirrors the module dependency contract")
assert((toc:find("Map.lua", 1, true) or toc:find("Map\\.lua", 1, true)) and (toc:find("Map.xml", 1, true) or toc:find("Map\\.xml", 1, true)), "POI map files must be in the feature TOC")
print("POI MapCanvas template, refresh guard and load-order checks passed")
