local repository=(arg[0]:gsub("tools[/\\]test_character_tabs.lua$",""))
local coreRoot=repository.."LIVE/Holy_Storm/";local uiRoot=repository.."LIVE/Holy_Storm_UI/";local charactersRoot=repository.."LIVE/Holy_Storm_Characters/"
local unpack=unpack or table.unpack
local function copy(value,seen)if type(value)~="table"then return value end;seen=seen or{};if seen[value]then return seen[value]end;local out={};seen[value]=out;for key,child in pairs(value)do out[copy(key,seen)]=copy(child,seen)end;return out end
local locale=setmetatable({LEVEL="Level",SEASON="Season %s",SEASON_SUMMARY="Season %s / Rating %s",CHARACTER_COUNT="%d known characters",LAST_UPDATED="Last updated: %s",ACTIVITY="Activity %s",ACTIVITY_DETAILS="Threshold %s / Level %s",WEEKLY_TOOLTIP="Weekly %s",BOSS_KILLED="Killed %s",BOSS_OPEN="Open %s",BEST_ROW="%s | %s | %d kills",LIFETIME_UNKNOWN="%s: lifetime kills unavailable",ITEM_LEVEL="Item level",EMPTY_SLOT="Empty",EMPTY_SOCKET="Empty socket",GEM_ID="Gem %s",TELEPORT_COOLDOWN="Cooldown %s",TELEPORT_READY="Ready",TELEPORT_UNAVAILABLE="Unavailable",EQUIPMENT_DISPLAY_NAME="Equipment",MYTHICPLUS_DISPLAY_NAME="Mythic+",RAID_DISPLAY_NAME="Raids",DELVES_DISPLAY_NAME="Delves"},{__index=function(t,key)local suffix=key:match("^EQUIPMENT_(.+)$")or key:match("^MYTHICPLUS_(.+)$")or key:match("^RAID_(.+)$")or key:match("^DELVES_(.+)$");return suffix and(rawget(t,suffix)or suffix)or key end})
local records={A={guid="A",name="Alpha-Realm",realm="Realm",classFile="PALADIN",level=80,faction="Alliance",guildRank="Stored Officer",stats={spec={id=70,name="Retribution",icon=98765,index=3,role="DAMAGER"}}}}
local blocks,eventListeners,errorLogs={},{},{}
local HolyStorm={Utils={DeepCopy=copy,TableCount=function(t)local n=0;for _ in pairs(t or{})do n=n+1 end;return n end,SafeCall=function(_,fn,...)local result={pcall(fn,...)};local ok=table.remove(result,1);return ok,unpack(result)end},Data={CharacterStore={},GuildStore={},PlayerStore={}},PlayerData={},Policy={},Tasks={},Events={},Logger={},UI={}}
local aceGUI
function LibStub(name,silent)if name=="AceAddon-3.0"then return{GetAddon=function()return HolyStorm end}elseif name=="AceLocale-3.0"then return{GetLocale=function()return locale end}elseif name=="AceGUI-3.0"then return aceGUI elseif not silent then error("unknown library "..tostring(name))end end
function HolyStorm:RegisterRequiredModule()local module={};self.characterOverview=module;return module end
function HolyStorm:RegisterCapability(_,capability,handler)self.capabilities=self.capabilities or{};self.capabilities[capability]=handler;return true end
function HolyStorm:RegisterCharacterTab(_,definition)return self.CharacterUI:RegisterTab(definition)end
function HolyStorm:RegisterCharacterSummarySection(_,definition)return self.CharacterUI:RegisterSummarySection(definition)end
function HolyStorm:RegisterUIExtension(_,definition)self.uiExtension=definition;return true end
local capabilityCalls={}
function HolyStorm:CallCapability(capability,...)capabilityCalls[#capabilityCalls+1]={capability=capability,args={...}};return false,"CAPABILITY_UNAVAILABLE"end;function HolyStorm:ApplyModuleMetadata()end;function HolyStorm:IsOptionalModuleEnabled()return false end
function HolyStorm:GetModule()return{frame=self.testUIFrame,content=self.testUIContent}end
function HolyStorm.Tasks:RegisterTaskType()end;function HolyStorm.Tasks:GetTaskType()return nil end
function HolyStorm.Events:Register(event,_,callback)eventListeners[event]=callback end;function HolyStorm.Events:Emit()end;function HolyStorm.Events:UnregisterOwner()end
function HolyStorm.Logger:Write(level,source,category,message,context)errorLogs[#errorLogs+1]={level=level,source=source,category=category,message=message,context=context}end
function HolyStorm.Policy:Can()return false end;function HolyStorm.Policy:IsGuildModuleEnabled()return false end
function HolyStorm.Data.CharacterStore:Get(guid)local source=records[guid];if not source then return nil end;local record=copy(source);record.equipment=blocks.equipment;record.mythicPlus=blocks.mythicPlus;record.raidLockouts=blocks.raid;record.delves=blocks.delves;record.stats=blocks.stats or source.stats;return record end
function HolyStorm.Data.CharacterStore:CaptureCurrent()return records.A end
function HolyStorm.Data.CharacterStore:GetBlock()return nil end
function HolyStorm.Data.CharacterStore:GetBlockMetadata(_,block)return{version=block=="equipment"and 4 or 3,updatedAt=100}end
function HolyStorm.Data.GuildStore:GetCurrent()return{roster={A={name="Alpha",classFile="PALADIN",level=80}}}end
function HolyStorm.Data.PlayerStore:GetCharacterOwner()return"account-A"end;function HolyStorm.PlayerData:IsStale()return false end
HolyStorm.TwinkCore={sources={OWNER="OWNER"},GetAccountUUIDForCharacter=function()return"account-A"end,GetAccount=function()return{characters={A=true,B=true}}end,GetAccountMain=function()return"A"end,GetGuildMain=function()return"B",true end,GetVisibleCharactersForViewer=function()return{{characterUUID="A",fullName="Alpha-Realm",classFile="PALADIN",level=80,relationship={source="OWNER"}},{characterUUID="B",fullName="Beta-Realm",classFile="MAGE",level=70,relationship={source="ADMIN"}}}end}
LOCALIZED_CLASS_NAMES_MALE={PALADIN="Paladin"};RAID_CLASS_COLORS={PALADIN={r=1,g=.96,b=.41}};NORMAL_FONT_COLOR={r=1,g=1,b=1};CLASS_ICON_TCOORDS={PALADIN={0,.25,0,.25}}
for index,name in ipairs({"HEAD","NECK","SHOULDER","BACK","CHEST","WRIST","HAND","WAIST","LEGS","FEET","FINGER1","FINGER2","TRINKET1","TRINKET2","MAINHAND","OFFHAND"})do _G["INVSLOT_"..name]=index end

local function widget(kind,parent)
 local object={kind=kind,parent=parent,width=640,height=360,shown=true,enabled=true,textValue="",points={}}
 function object:SetAllPoints(target)self.allPoints=target or self.parent end;function object:SetParent(value)self.parent=value end
 function object:SetPoint(...)self.points[#self.points+1]={...}end;function object:ClearAllPoints()self.points={}end
 function object:SetSize(width,height)self.width,self.height=width,height;if self.OnSizeChanged then self.OnSizeChanged(self,width,height)end end;function object:SetWidth(width)self.width=width end;function object:GetWidth()return self.width end;function object:SetHeight(height)self.height=height end;function object:GetHeight()return self.height end
 function object:SetScrollChild(child)self.scrollChild=child end;function object:SetScript(event,handler)self[event]=handler end;function object:HookScript(event,handler)self[event]=handler end
 function object:CreateFontString()return widget("font",self)end;function object:CreateTexture()return widget("texture",self)end
 function object:SetText(text)self.textValue=text or""end;function object:GetStringHeight()return 16 end;function object:GetUnboundedStringWidth()return#self.textValue*7 end;function object:GetStringWidth()return#self.textValue*7 end
 function object:SetFontObject()end;function object:SetTextColor()end;function object:SetJustifyH()end;function object:SetJustifyV()end;function object:SetWordWrap()end;function object:SetNonSpaceWrap()end;function object:SetHyperlinksEnabled()end
 function object:SetColorTexture(...)self.color={...}end;function object:SetTexture(value)self.texture=value end;function object:SetTexCoord(...)self.texCoord={...}end;function object:SetVertexColor(...)self.vertexColor={...}end;function object:SetAlpha(value)self.alpha=value end;function object:SetNormalTexture()end;function object:SetHighlightTexture()end;function object:RegisterForClicks(...)self.clicks={...}end;function object:EnableMouse()end;function object:SetEnabled(value)self.enabled=value~=false end
 function object:SetShown(value)self.shown=value==true end;function object:IsShown()return self.shown end;function object:Show()self.shown=true end;function object:Hide()self.shown=false end
 return object
end
CreateFrame=function(_,_,parent)return widget("frame",parent)end
local function createTabGroup()
 local group={frame=widget("tabgroup-frame"),content=widget("tabgroup-content"),tabButtons={},tabs={},callbacks={}}
 function group:SetCallback(event,handler)self.callbacks[event]=handler end;function group:GetContentFrame()return self.content end
 function group:LayoutTabs()self.content:SetSize(math.max(1,self.frame.width),math.max(1,self.frame.height-36))end
 function group:SetTabs(tabs)self.tabs=tabs or{};for _,tab in ipairs(self.tabs)do local button=self.tabButtons[tab.value]or widget("tab-button");button.value=tab.value;button.icon=button.icon or widget("texture",button);button.icon:SetTexture(tab.icon);button:SetSize(100,30);button:RegisterForClicks("LeftButtonUp");self.tabButtons[tab.value]=button end;self:LayoutTabs()end
 function group:SelectTab(value,silent)self.selected=value;if not silent and self.callbacks.OnGroupSelected then self.callbacks.OnGroupSelected(self,"OnGroupSelected",value)end end
 return group
end
aceGUI={Create=function(_,kind)assert(kind=="HolyStormTabGroup");return createTabGroup()end}
HolyStorm.testUIFrame=widget("main-frame");HolyStorm.testUIContent=widget("ui-content",HolyStorm.testUIFrame)
HolyStorm.UI.frame=HolyStorm.testUIFrame;HolyStorm.UI.content=HolyStorm.testUIContent;HolyStorm.UI.registered={};HolyStorm.UI.visible="character"
function HolyStorm.UI:RegisterView(definition)self.registered[definition.id]=definition;return true end;function HolyStorm.UI:ShowView(id)self.visible=id;return true end;function HolyStorm.UI:GetVisiblePage()return self.visible end;function HolyStorm.UI:ShowPage(id)self.visible=id end
HolyStorm.Database={Get=function()return false end};C_Timer={After=function(_,callback)callback()end};date=function(format,timestamp)return format.."|"..tostring(timestamp)end;UnitGUID=function()return"A"end
GameTooltip={lines={},lineColors={}};function GameTooltip:SetOwner(owner)self.owner=owner end;function GameTooltip:SetText(value)self.text=value;self.lines={};self.lineColors={}end;function GameTooltip:AddLine(value,r,g,b)table.insert(self.lines,value);table.insert(self.lineColors,{r,g,b})end;function GameTooltip:SetHyperlink(value)self.hyperlink=value end;function GameTooltip:Show()self.shown=true end;function GameTooltip:Hide()self.shown=false end

assert(loadfile(uiRoot.."UI/Framework/Layout.lua"))();assert(loadfile(uiRoot.."UI/Framework/Components.lua"))();assert(loadfile(uiRoot.."UI/Framework/Table.lua"))();assert(loadfile(uiRoot.."UI/Framework/Components/HolyStormHeaderBar.lua"))();HolyStorm.UI.Components=HolyStorm.UIComponents
assert(loadfile(charactersRoot.."UI/CharacterUI.lua"))();assert(loadfile(charactersRoot.."UI/StoredFeatureTabs.lua"))();assert(loadfile(charactersRoot.."UI/CharacterOverview.lua"))()
local C=HolyStorm.CharacterUI;local context=C:ResolveContext("A")
local fixedIds={"summary","equipment","mythicPlus","raid","delves","stats","twinks"};local tabs=C:GetTabs();assert(#tabs==#fixedIds,"exactly seven fixed tabs are registered without producer addons");for index,id in ipairs(fixedIds)do assert(tabs[index].id==id,"fixed tab order at "..index..": "..id);assert(not tabs[index].permission and not tabs[index].moduleId and not tabs[index].availability,"fixed storage tab has no display gate: "..id)end
local function render(id,width)local definition=assert(C:GetTab(id));local parent=widget("parent");parent:SetSize(width or 900,500);local view=definition.build(parent);view.frame:SetSize(width or 900,500);view.layout:Relayout();definition.refresh(view,context,definition);return view,definition end
local function find(rows,predicate)for _,row in ipairs(rows)do if predicate(row)then return row end end end

assert(C:FormatState(0)=="0"and C:FormatState(nil):find("–",1,true)and C:FormatState(nil):find("888888",1,true),"central state formatter separates zero and gray unknown")
assert(HolyStorm.UI.Components:FormatDelta(4):find("20ff20",1,true)and HolyStorm.UI.Components:FormatDelta(-4):find("ff4040",1,true)and HolyStorm.UI.Components:FormatDelta(0)=="0","central delta colors and zero")

local slots={};slots[1]={itemId=111,link="|cffa335ee|Hitem:111::::::::80:70::1:2:999:888::::::|h[An Extremely Long Test Helm Name]|h|r",itemLevel=710,enchantId=42,enchantName="Radiant Enchant",gems={{itemId=1001,name="Ruby",icon=9001}},sockets=1,icon=123,isTier=true};slots[2]=false;slots[4]={itemId=222,link="|cff0070dd|Hitem:222::::::::80:70:::::::|h[Plain Bracers]|h|r",itemLevel=0,enchantId=0,gems={},sockets=0,icon=124,isTier=false};slots[5]={itemId=223,link="|cff0070dd|Hitem:223::::::::80:70:::::::|h[Socket Belt]|h|r",itemLevel=700,enchantId=nil,gems={{empty=true,name="Prismatic Socket"}},sockets=1,icon=125};slots[6]={itemId=224,link="|cff0070dd|Hitem:224::::::::80:70:::::::|h[Unknown Gems]|h|r",itemLevel=700,enchantId=nil,gems={},sockets=1,icon=126}
blocks.equipment={snapshotVersion=4,itemLevel=705.5,slots=slots};local equipment=render("equipment");assert(#equipment.table.rows==16,"equipment retains one row per slot")
assert(equipment.table.rows[1].state=="VALUE"and equipment.table.rows[1].tierState==true and equipment.table.rows[1].enchantState==true and equipment.table.rows[1].gems:find("9001",1,true),"equipped tier, enchant and gem state")
assert(equipment.table.rowFrames[1].cells[3].statusIcon.shown and equipment.table.rowFrames[1].cells[4].statusIcon.shown and equipment.table.rowFrames[1].cells[4].statusIcon.texture:find("UI%-CheckBox%-Check"),"tier and enchant use a Blizzard check texture")
assert(equipment.table.rows[2].state=="EMPTY"and equipment.table.rows[2].itemText==nil and equipment.table.rowFrames[2].cells[2].text.textValue=="Empty","confirmed empty slot is not unknown")
assert(equipment.table.rows[2].tierState==false and equipment.table.rows[2].enchantState==false and equipment.table.rows[2].gems==""and equipment.table.rows[2].itemLevel==""and not equipment.table.rowFrames[2].cells[3].statusIcon.shown and not equipment.table.rowFrames[2].cells[4].statusIcon.shown,"confirmed empty slot has no tier, enchant, socket or item-level status")
assert(equipment.table.rows[3].state=="UNKNOWN"and equipment.table.rowFrames[3].cells[2].text.textValue:find("–",1,true),"unknown slot uses gray dash")
assert(equipment.table.rows[4].itemLevel=="0"and equipment.table.rows[4].enchantState==false and not equipment.table.rowFrames[4].cells[4].statusIcon.shown and equipment.table.rowFrames[4].cells[4].text.textValue==""and equipment.table.rows[4].gems=="","known zero and known empty equipment fields")
assert(equipment.table.rows[4].tierState==false and not equipment.table.rowFrames[4].cells[3].statusIcon.shown and equipment.table.rowFrames[4].cells[3].text.textValue=="","known non-tier state is empty")
assert(equipment.table.rows[3].enchantState==nil and equipment.table.rowFrames[3].cells[4].text.textValue:find("–",1,true),"unknown enchant state uses the gray dash")
assert(equipment.summary.text.textValue:find("ffffd100",1,true)and equipment.summary.text.textValue:find("80dfff",1,true)and equipment.summary.text.textValue:find("705.5",1,true),"item-level header separates label and one-decimal value colors")
local tierColumn,enchantColumn=equipment.table.columns[3],equipment.table.columns[4];assert(tierColumn.tooltip(equipment.table.rows[1])=="TIER_ITEM"and tierColumn.tooltip(equipment.table.rows[4])==nil,"tier tooltip follows the exact visible boolean state");assert(enchantColumn.tooltip(equipment.table.rows[1])=="Radiant Enchant"and enchantColumn.tooltip(equipment.table.rows[4])=="NOT_ENCHANTED"and enchantColumn.tooltip(equipment.table.rows[3])==nil,"enchant tooltip cannot contradict the visible tri-state status")
assert(equipment.table.rows[5].gemDetails[1]=="Prismatic Socket"and equipment.table.rows[6].gems:find("–",1,true),"empty and unknown sockets remain distinct")
local itemCell=equipment.table.rowFrames[1].cells[2];itemCell.frame.width=105;equipment.table:FitCell(itemCell,equipment.table.columns[2]);assert(itemCell.text.textValue:find("...",1,true)and itemCell.text.textValue:find("Hitem:111::::::::80:70::1:2:999:888",1,true),"truncation preserves the complete item hyperlink payload")
itemCell.frame.OnEnter(itemCell.frame);assert(GameTooltip.hyperlink==slots[1].link,"item hover uses SetHyperlink with original payload");local clicked;HandleModifiedItemClick=function(link)clicked=link end;itemCell.frame.OnClick(itemCell.frame,"LeftButton");assert(clicked==slots[1].link,"item cell keeps native click behavior")
local equipmentRowFrame=equipment.table.rowFrames[1];blocks.equipment.itemLevel=706;C:GetTab("equipment").refresh(equipment,context,C:GetTab("equipment"));assert(equipment.table.rowFrames[1]==equipmentRowFrame,"equipment table reuses row frames")

local spellState={[902]={known=true,remaining=0},[903]={known=true,remaining=120}};GetTime=function()return 1000 end;C_Spell={IsSpellKnown=function(id)return spellState[id]and spellState[id].known end,GetSpellCooldown=function(id)local remaining=spellState[id]and spellState[id].remaining or 0;return{startTime=1000,duration=remaining}end,CastSpell=function(id)clicked="spell:"..id end};C_ChallengeMode={GetDungeonScoreRarityColor=function()return{r=.5,g=.25,b=1}end,GetAffixInfo=function()return nil end};SecondsToClock=function(value)return math.ceil(value).."s"end
blocks.mythicPlus={snapshotVersion=3,seasonId=16,overallScore=2500,scoreDataReady=true,dungeons={{name="A Dungeon",instanceId=200,texture=400,score=250,affixScores={{category="TYRANNICAL",name="Tyrannical",level=12,durationSec=1634,overTime=false},{category="FORTIFIED",name="Fortified",level=10,durationSec=1902,overTime=true}}},{name="B Dungeon",instanceId=201,texture=401,score=0,teleportSpellId=902,affixScores={}},{name="C Dungeon",instanceId=202,texture=402,score=nil,teleportSpellId=903,affixScores={}},{name="D Dungeon",instanceId=203,texture=403,score=200},{name="E Dungeon",instanceId=204,texture=404,score=100,affixScores={{name="Unknown score",level=4,durationSec=1700,overTime=false}}}}}
local mythic=render("mythicPlus");local dungeonA=find(mythic.table.rows,function(row)return row.name=="A Dungeon"end);local dungeonB=find(mythic.table.rows,function(row)return row.name=="B Dungeon"end);local dungeonC=find(mythic.table.rows,function(row)return row.name=="C Dungeon"end);local dungeonD=find(mythic.table.rows,function(row)return row.name=="D Dungeon"end);local dungeonE=find(mythic.table.rows,function(row)return row.name=="E Dungeon"end)
assert(dungeonA.tyrannical:find("20ff20",1,true)and dungeonA.tyrannical:find("27:14",1,true)and dungeonA.fortified:find("ff4040",1,true)and dungeonA.fortified:find("31:42",1,true),"stored Blizzard affix bests render level, duration and timer color");assert(dungeonB.tyrannical==""and dungeonB.rating:find("0",1,true)and dungeonC.rating:find("–",1,true)and dungeonD.tyrannical:find("–",1,true),"reliable no-run, rating zero and unavailable affix data retain distinct states")
assert(dungeonE.tyrannical:find("–",1,true)and dungeonE.fortified:find("–",1,true)and#capabilityCalls==1 and capabilityCalls[1].capability=="character.scan.mythicplus"and capabilityCalls[1].args[2]=="AFFIX_CATEGORY_REFRESH","unknown categories render gray and request exactly one targeted refresh for the owned character");C:GetTab("mythicPlus").refresh(mythic,context,C:GetTab("mythicPlus"));assert(#capabilityCalls==1,"an unusable affix snapshot cannot create a refresh loop");dungeonB=find(mythic.table.rows,function(row)return row.name=="B Dungeon"end);dungeonC=find(mythic.table.rows,function(row)return row.name=="C Dungeon"end)
assert(dungeonA.teleport.state=="UNAVAILABLE"and dungeonB.teleport.state=="READY"and dungeonC.teleport.state=="COOLDOWN","all teleport states")
local rowB;for index,row in ipairs(mythic.table.rows)do if row==dungeonB then rowB=mythic.table.rowFrames[index]end end;rowB.cells[1].teleportButton.OnClick();assert(clicked=="spell:902","ready teleport casts stored spell");local rowC;for index,row in ipairs(mythic.table.rows)do if row==dungeonC then rowC=mythic.table.rowFrames[index]end end;rowC.cells[1].teleportButton.OnEnter(rowC.cells[1].teleportButton);assert(GameTooltip.lines[1]:find("120s",1,true),"cooldown tooltip formats remaining time")
local openedJournal;EncounterJournal_OpenJournal=function(_,id)openedJournal=id end;rowB.cells[1].frame.OnClick(rowB.cells[1].frame,"LeftButton");assert(openedJournal==201,"dungeon name opens the Encounter Journal")

blocks.raid={snapshotVersion=3,catalogReady=true,currentRaid={id=200,name="Raid Two"},bestProgress={difficultyId=14,killed=2,total=3,raidInstanceId=200,raidName="Raid Two"},raids={{id=100,name="Raid One",icon=500,order=1,bosses={{id=501,name="Boss A"},{id=502,name="Boss B"}}},{id=200,name="Raid Two",icon=501,order=2,bosses={{id=601,name="Boss C"},{id=602,name="Boss D"},{id=603,name="Boss E"}}},{id=300,name="Raid Three",icon=502,order=3,bosses={{id=701,name="Boss Z"}}}},lockouts={{name="Raid One",journalInstanceId=100,difficultyId=17,killed=1,total=2,bosses={{name="Boss A",killed=true},{name="Boss B",killed=false}}},{name="Raid One",journalInstanceId=100,difficultyId=14,killed=0,total=2,bosses={{name="Boss A",killed=false},{name="Boss B",killed=false}}},{name="Raid One",journalInstanceId=100,difficultyId=16,killed=1,total=2,bosses={{name="Boss A",killed=true},{name="Boss B",killed=false}}},{name="Raid One",journalInstanceId=100,difficultyId=33,difficultyName="Timewalking",killed=1,total=2,bosses={{name="Boss A",killed=true},{name="Boss B",killed=false}}},{name="Raid Two",journalInstanceId=200,difficultyId=14,killed=2,total=3,bosses={{name="Boss C",killed=true},{name="Boss D",killed=true},{name="Boss E",killed=false}}}},lifetime={bosses={[501]={id=501,name="Boss A",raidInstanceId=100,raidName="Raid One",difficulties={MYTHIC={kills=17,source="blizzard-statistic",statisticId=12345}}},[502]={id=502,name="Boss B",raidInstanceId=100,raidName="Raid One",difficulties={NORMAL={kills=99,source="legacy-local-observation"}}}}}}
local raid=render("raid");local raidRow=find(raid.table.rows,function(row)return row.instanceId==100 end);local raidTwo=find(raid.table.rows,function(row)return row.instanceId==200 end);local raidThree=find(raid.table.rows,function(row)return row.instanceId==300 end);assert(raidRow.lfr:find("ffffd100",1,true)and raidRow.normal:find("ff33ff33",1,true)and raidRow.heroic:find("ff408cff",1,true)and raidRow.mythic:find("ffb34dff",1,true),"addon-wide raid difficulty colors");assert(raidRow.lfr:find("1/2",1,true)and raidRow.normal:find("0/2",1,true)and raidRow.heroic:find("–",1,true),"weekly lockout, real zero progress and no-lockout dash remain distinct")
assert(C:BuildRaidBestRows(blocks.raid)[1].difficulty=="MYTHIC"and C:BuildRaidBestRows(blocks.raid)[1].kills==17 and raidRow.best:find("M 1/2",1,true),"only Blizzard statistic lifetime values are used while weekly best remains available")
local bestColumn=raid.table.columns[#raid.table.columns];bestColumn.tooltip(raidRow,bestColumn,raid.table,GameTooltip);assert(#GameTooltip.lines==2 and GameTooltip.lines[1]:find("Boss A",1,true)and GameTooltip.lines[1]:find("17 kills",1,true)and GameTooltip.lines[2]:find("Boss B",1,true)and GameTooltip.lines[2]:find("unavailable",1,true),"best tooltip shows reliable Blizzard lifetime kills and marks legacy-only bosses unknown")
assert(raidRow.nameDisplay:find("TW 1/2",1,true)and#raid.table.columns==6 and not find(raid.table.columns,function(column)return column.id=="timewalking"end),"Timewalking is shown only in its raid row instead of adding a global column")
assert(raidTwo.best==""and raidThree.best=="","weekly progress and the snapshot's legacy bestProgress never populate lifetime Best")
blocks.raid.lockouts={};local expiredRaid=render("raid");local expiredRaidOne=find(expiredRaid.table.rows,function(row)return row.instanceId==100 end);assert(expiredRaidOne.best:find("M 1/2",1,true)and expiredRaidOne.lfr:find("888888",1,true),"expired weekly lockouts disappear without changing lifetime Best")
local lfrColumn=raid.table.columns[2];lfrColumn.tooltip(raidRow,lfrColumn,raid.table,GameTooltip);assert(GameTooltip.lineColors[1][1]==1 and GameTooltip.lineColors[2][2]==1,"weekly tooltip colors killed red and open green")
local heroicColumn=raid.table.columns[4];heroicColumn.tooltip(raidRow,heroicColumn,raid.table,GameTooltip);assert(#GameTooltip.lines==1 and GameTooltip.lines[1]=="NO_CURRENT_LOCKOUT","missing lockout tooltip does not fabricate open bosses")
blocks.raid={snapshotVersion=3,catalogReady=true,raids={},lockouts={{name="Firelands",journalInstanceId=300,difficultyId=33,difficultyName="Timewalking",killed=1,total=2,bosses={{name="Beth'tilac",killed=true},{name="Lord Rhyolith",killed=false}}}},lifetime={bosses={}}};local oldRaid=render("raid");local oldRow=oldRaid.table.rows[1];oldRaid.table.rowFrames[1].cells[1].frame.OnClick(oldRaid.table.rowFrames[1].cells[1].frame,"LeftButton")
assert(oldRow.nameDisplay:find("TW 1/2",1,true)and openedJournal==300,"an older Timewalking lockout renders in its row and opens its resolved Encounter Journal entry")
blocks.raid={snapshotVersion=3,catalogReady=true,raids={{id=100,name="Raid One",bosses={{name="Boss A"}}}},lockouts={},lifetime={bosses={}}};local unknownRaid=render("raid");assert(unknownRaid.table.rows[1].lfr:find("888888",1,true),"a current catalog raid without a lockout is a gray dash")

blocks.delves={seasonNumber=3,weeklyProgress=0,bountiful={status="unknown"},keyFragments={count=4},completedKeys=0,companion={level=12},activities={{index=1,progress=2,threshold=4,level=8}}};local delves=render("delves");assert(delves.table.rows[1].value=="0"and delves.table.rows[2].value:find("–",1,true)and find(delves.table.rows,function(row)return row.value=="4"end),"delve zero, unknown and structured values")

blocks.stats={primary={strength={base=100,effective=120},agility={base=20,effective=15},stamina={base=nil,effective=nil},intellect={base=10,effective=10}},armor={base=500,effective=600},secondary={criticalStrike={rating=0,percent=0},haste={rating=800,percent=15}}};local stats=render("stats");local strength=find(stats.table.rows,function(row)return row.stat=="STAT_STRENGTH"end);local agility=find(stats.table.rows,function(row)return row.stat=="STAT_AGILITY"end);local stamina=find(stats.table.rows,function(row)return row.stat=="STAT_STAMINA"end);local intellect=find(stats.table.rows,function(row)return row.stat=="STAT_INTELLECT"end);assert(strength.additional:find("+20",1,true)and agility.additional:find("-5",1,true)and intellect.additional=="0"and stamina.total:find("–",1,true),"stats positive, negative, zero and unknown Additional semantics");local critical=find(stats.table.rows,function(row)return row.stat=="STAT_CRITICALSTRIKE"end);assert(critical.total:find("0",1,true),"known secondary zero is retained")

local summary=render("summary");assert(find(summary.table.rows,function(row)return row.label=="SUMMARY_IDENTITY"and row.value=="Alpha-Realm"end)and find(summary.table.rows,function(row)return row.label=="Equipment"and row.tabId=="equipment"end),"summary combines compact identity and storage-owned feature adapters")
local twinks=render("twinks");assert(#twinks.table.rows==2 and twinks.table.rows[2].name:find("SHADOW_MAIN",1,true),"additional Twinks tab uses the central table")
for _,case in ipairs({{"equipment","equipment"},{"mythicPlus","mythicPlus"},{"raid","raid"},{"delves","delves"},{"stats","stats"}})do local block,id=case[1],case[2];local stored,storedRecordStats=blocks[block],records.A.stats;blocks[block]=nil;if block=="stats"then records.A.stats=nil end;local missing=render(id);assert(C:GetTab(id)and#missing.table.rows==0,"missing storage block keeps an empty, clickable tab: "..id);blocks[block]=stored;records.A.stats=storedRecordStats end
do local definition=C:GetTab("twinks");local view=definition.build(widget("parent"));definition.refresh(view,{characterUUID="A",accountUUID=nil},definition);assert(#view.table.rows==0 and C:GetTab("twinks"),"missing Twink storage relationship keeps the Twinks tab")end

local Page=HolyStorm.characterOverview;Page:OnInitialize();assert(HolyStorm.uiExtension and HolyStorm.uiExtension.initialize);HolyStorm.uiExtension.initialize();assert(HolyStorm.UI.registered.character and Page.header and Page.tabGroup and Page.tabHost,"Character Overview registers one declarative view with central header and TabGroup")
C:SetContext("A",false);C:SelectTab("stats");assert(Page.views.stats and Page.views.stats.table and#Page.views.stats.table.rows==9,"tab switching builds the central stats table");local statsFrame=Page.views.stats.frame;C:SelectTab("summary");assert(not statsFrame.shown and Page.views.summary.frame.shown,"tab switching reuses views and hides inactive content")
Page.page:SetSize(920,540);Page:LayoutTabs();assert(Page.tabHost.width>800 and Page.views.summary.frame.parent==Page.tabHost and Page.views.summary.table.columnWidths[2]>0,"resize relayout keeps flexible columns in the central content host")
local original=C:GetTab("summary").refresh;C:GetTab("summary").refresh=function()error("forced renderer failure")end;assert(not C:RefreshTab("summary")and errorLogs[#errorLogs].context.tabId=="summary","one failed adapter is isolated and logged");C:GetTab("summary").refresh=original;assert(C:RefreshTab("summary"),"a tab recovers after a failed refresh")

local achievements=assert(io.open(repository.."LIVE/Holy_Storm_Achievements/Achievements.lua","rb"));local achievementSource=achievements:read("*a");achievements:close();assert(achievementSource:find("CreateTableView",1,true)and not achievementSource:find("CreateTextView",1,true)and not achievementSource:find("CharacterUI:SetView",1,true),"Achievements character tab no longer activates a legacy renderer")
for _,path in ipairs({charactersRoot.."UI/StoredFeatureTabs.lua",charactersRoot.."UI/Locales/enUS.lua",charactersRoot.."UI/Locales/deDE.lua",repository.."LIVE/Holy_Storm_Achievements/Achievements.lua",repository.."LIVE/Holy_Storm_Achievements/Locales/enUS.lua",repository.."LIVE/Holy_Storm_Achievements/Locales/deDE.lua",repository.."LIVE/Holy_Storm_Raids/Locales/enUS.lua",repository.."LIVE/Holy_Storm_Raids/Locales/deDE.lua"})do local file=assert(io.open(path,"rb"));local source=file:read("*a");file:close();for _,symbol in ipairs({"✓","○","✗","◆"})do assert(not source:find(symbol,1,true),"affected character, achievement and raid views use stable textures or colored text instead of Unicode status glyphs: "..path)end end
for _,path in ipairs({charactersRoot.."UI/CharacterOverview.lua",charactersRoot.."UI/CharacterUI.lua",charactersRoot.."UI/StoredFeatureTabs.lua"})do local file=assert(io.open(path,"rb"));local source=file:read("*a");file:close();assert(not source:find("CreateTextView",1,true)and not source:find("CharacterUI:SetView",1,true),"no Character Overview file retains the legacy renderer: "..path)end
print("Declarative Character Overview, adapters, states, interactions, resize and reuse tests passed")
