local root=(arg[0]:gsub("tools[/\\]test_achievements.lua$","")).."LIVE/Holy_Storm/"
unpack=unpack or table.unpack
local clock=1000;local allowed=true;local records={};local published={};local registeredDomain;local links={};local queued={};local listeners={}
function time()return clock end;function UnitGUID(unit)if unit==nil or unit=="player"then return"Player-Local"end end;function IsInGuild()return true end
local guild={id="realm:guild",roster={}}
local HolyStorm={db={global={achievements={guilds={},schemaVersion=1},rules={global={}},filters={global={},demands={}},permissions={groups={}}},profile={filters={localFilters={}},rules={localRules={}}}},Data={GuildStore={},CharacterStore={},PlayerStore={}},Logger={},Events={},Policy={},Sync={},Tasks={},RichLinks={},Database={},TwinkCore={}}
function LibStub(name)if name=="AceAddon-3.0"then return{GetAddon=function()return HolyStorm end}elseif name=="AceLocale-3.0"then return{GetLocale=function()return setmetatable({CATEGORY_GENERAL="General",EARNED_NOTIFICATION="Earned %s",TASK_EVALUATE="Evaluate",ACHIEVEMENT="Achievement",NOT_VISIBLE="Hidden"},{__index=function(_,key)return key end})end}end end
assert(loadfile(root.."Core/Utils/Utils.lua"))();assert(loadfile(root.."Core/Serialization/Serializer.lua"))()
function HolyStorm.Logger:Write()end
function HolyStorm.Events:Emit(event,...)for _,handler in pairs(listeners[event]or{})do handler(event,...)end end
function HolyStorm.Events:Register(event,owner,handler)listeners[event]=listeners[event]or{};listeners[event][owner]=handler end
function HolyStorm.Data.GuildStore:GetCurrent()return guild end
function HolyStorm.Data.CharacterStore:Get(guid)return records[guid]end
function HolyStorm.Data.PlayerStore:GetLocalPlayerId()return"Account-Local"end
function HolyStorm.Data.PlayerStore:Get()return{}end
function HolyStorm.TwinkCore:GetLocalAccountUUID()return"Account-Local"end
function HolyStorm.TwinkCore:GetAccountUUIDForCharacter(guid)return"Account-"..guid end
function HolyStorm.Policy:Can()return allowed end
function HolyStorm.Policy:BuildContext(_,guid,target)return{accountUUID="Account-"..guid,characterUUID=guid,character=records[guid],guild=HolyStorm.Data.GuildStore:GetCurrent(),member=HolyStorm.Data.GuildStore:GetCurrent().roster[guid],target=target}end
function HolyStorm.Policy:ApplyFilter(filter,value)if filter=="eligible-only"then return records[value.guid]and records[value.guid].level==90 end;return true end
function HolyStorm.Sync:RegisterDomain(_,definition)registeredDomain=definition;return true end
function HolyStorm.Sync:Publish(_,objectId)published[#published+1]=objectId;return true end
function HolyStorm.Sync:Discover()return true end
function HolyStorm.Tasks:RegisterTaskType(id,definition)self[id]=definition end
function HolyStorm.Tasks:Queue(id,options)queued[#queued+1]={id=id,options=options};return"task"end
function HolyStorm.RichLinks:RegisterType(definition)links[definition.type]=definition;return true end
function HolyStorm.Database:RegisterArea()return true end
function HolyStorm.Database:Get()return false end
assert(loadfile(root.."Core/Permissions/RuleEngine.lua"))();HolyStorm.Rules:Initialize();assert(loadfile(root.."Persistence/AchievementStore.lua"))();assert(loadfile(root.."Modules/Achievements/AchievementService.lua"))();HolyStorm.Achievements:Initialize();HolyStorm.Rules:RegisterField("test-equipment","equipment.itemLevel",{type="number",dependencies={"equipment"},resolver=function(c)return c.character and c.character.itemLevel end});HolyStorm.Rules:RegisterField("test-character","character.level",{type="number",resolver=function(c)return c.character and c.character.level end});HolyStorm.Rules:RegisterField("test-character","character.spec",{type="string",resolver=function(c)return c.character and c.character.spec end})
local A=HolyStorm.Achievements
records["Player-Local"]={guid="Player-Local",level=90,itemLevel=705};HolyStorm.Data.GuildStore:GetCurrent().roster["Player-Local"]={name="Local"}
local complex={logic="AND",children={{field="equipment.itemLevel",operator=">=",value=700},{logic="OR",children={{field="character.level",operator=">=",value=90},{field="character.spec",operator="=",value="Restoration"}}}}};local status=HolyStorm.Rules:EvaluateDetailed(complex,HolyStorm.Policy:BuildContext(nil,"Player-Local"));assert(status=="PASS","complex AND/OR rule: "..tostring(status))
records.Missing={guid="Missing",level=90};local unknown=HolyStorm.Rules:EvaluateDetailed({logic="NOT",children={{field="equipment.itemLevel",operator=">=",value=700}}},HolyStorm.Policy:BuildContext(nil,"Missing"));assert(unknown=="UNKNOWN","NOT preserves UNKNOWN")
local ok,automatic=A:SaveDefinition({name="Item level 700",description="Reach 700",category="Progress",type="AUTOMATIC",status="ACTIVE",scope="CHARACTER",rule={field="equipment.itemLevel",operator=">=",value=700}});assert(ok and automatic.achievementID and automatic.dependencies[1]=="equipment","automatic definition")
local automaticOK,automaticEvent=A:EvaluateAutomatic(automatic.achievementID,"Player-Local");assert(automaticOK);assert(A:IsEarned(automatic.achievementID,"Player-Local"),"automatic award");local duplicate,duplicateReason=A:EvaluateAutomatic(automatic.achievementID,"Player-Local");assert(not duplicate and duplicateReason=="DUPLICATE","automatic idempotency")
local _,archiveCandidate=A:SaveDefinition({name="Archive test",category="Lifecycle",type="AUTOMATIC",status="ACTIVE",scope="CHARACTER",rule={field="character.level",operator=">=",value=90}});assert(A:SetStatus(archiveCandidate.achievementID,"ARCHIVED"));local archivedOK,archivedReason=A:EvaluateAutomatic(archiveCandidate.achievementID,"Player-Local");assert(not archivedOK and archivedReason=="NOT_ACTIVE_AUTOMATIC","archived definitions stop evaluation")
local missingStatus=A:Evaluate(automatic,"Missing");assert(missingStatus=="UNKNOWN","missing synchronized data remains unknown")
local manualCharacters={};for i=1,30 do local guid="Player-Raid-"..i;manualCharacters[i]=guid;records[guid]={guid=guid,level=i<=20 and 90 or nil};HolyStorm.Data.GuildStore:GetCurrent().roster[guid]={name="Raider"..i}end
local filtered=A:CaptureCandidates("FILTER:eligible-only");assert(#filtered==21,"central guild filter candidate source")
local _,feat=A:SaveDefinition({name="Guild First",description="Historic moment",category="Raid",type="FEAT_OF_STRENGTH",status="ACTIVE",scope="CHARACTER",rule={field="character.level",operator=">=",value=90}})
local beforeEvents=0;for _ in pairs(HolyStorm.Data.AchievementStore:GetEvents())do beforeEvents=beforeEvents+1 end;local testOK,testPreview=A:PreviewManual(feat.achievementID,"MANUAL",manualCharacters,true);assert(testOK and testPreview.counts.PASS==20 and testPreview.counts.UNKNOWN==10);local confirmedTest,testEvent=A:ConfirmManual(testPreview.previewID);assert(confirmedTest and#testEvent.awards==20);local afterTest=0;for _ in pairs(HolyStorm.Data.AchievementStore:GetEvents())do afterTest=afterTest+1 end;assert(afterTest==beforeEvents,"test mode persists nothing")
local previewOK,preview=A:PreviewManual(feat.achievementID,"MANUAL",manualCharacters,false);assert(previewOK and#preview.candidates==30);records["Player-Late"]={guid="Player-Late",level=90};manualCharacters[31]="Player-Late";local awardOK,event=A:ConfirmManual(preview.previewID);assert(awardOK and#event.candidateSnapshot==30 and#event.awards==20,"stable candidate snapshot and exact recipients");for _,award in ipairs(event.awards)do assert(award.characterUUID~="Player-Late")end
local originalRevision=event.awards[1].definitionRevision;local changed=HolyStorm.Utils.DeepCopy(feat);changed.description="Changed later";local _,updated=A:SaveDefinition(changed);assert(updated.revision>originalRevision and event.awards[1].definitionRevision==originalRevision,"historical definition revision")
local revokeOK,revoked=A:Revoke(event.awards[1].awardID,"Correction");assert(revokeOK and revoked.status=="REVOKED"and revoked.revokedBy=="Player-Local"and revoked.originalAwardInstanceID==event.awardInstanceID and not HolyStorm.Data.AchievementStore:IsEarned(feat.achievementID,revoked.recipientID),"immutable audited revoke")
local eventObjectId=HolyStorm.Data.AchievementStore:ObjectId("E",event.awardInstanceID);local currentMeta=HolyStorm.Data.AchievementStore:GetMetadata(eventObjectId);local stalePayload=HolyStorm.Data.AchievementStore:Export(eventObjectId);local imported,reason=A:Import(eventObjectId,stalePayload,currentMeta);assert(not imported and reason=="STALE_VERSION"and not HolyStorm.Data.AchievementStore:IsEarned(feat.achievementID,revoked.recipientID),"stale state cannot resurrect revoke")
local accountOK,accountDef=A:SaveDefinition({name="Account award",category="Account",type="MANUAL",status="ACTIVE",scope="ACCOUNT"});assert(accountOK);local accountPreviewOK,accountPreview=A:PreviewManual(accountDef.achievementID,"MANUAL",{"Player-Local"},false);assert(accountPreviewOK);local accountAwardOK,accountEvent=A:ConfirmManual(accountPreview.previewID);assert(accountAwardOK and accountEvent.awards[1].recipientID=="Account-Player-Local"and A:IsEarned(accountDef.achievementID,"Player-Local"),"account-scoped recipient identity")
local largeCandidates={};for i=1,65 do local guid="Player-Large-"..i;largeCandidates[i]=guid;records[guid]={guid=guid,level=90}end;local largePreviewOK,largePreview=A:PreviewManual(feat.achievementID,"MANUAL",largeCandidates,false);local largeAwardOK,largeGroup=A:ConfirmManual(largePreview.previewID);assert(largePreviewOK and largeAwardOK and#largeGroup.events==3 and#largeGroup.awards==65 and#largeGroup.candidateSnapshot==65,"large candidate snapshot is synchronized in 30-recipient batches")
local automaticObjectId=HolyStorm.Data.AchievementStore:ObjectId("E",automaticEvent.awardInstanceID);local automaticPayload=HolyStorm.Data.AchievementStore:Export(automaticObjectId);local automaticMeta=HolyStorm.Data.AchievementStore:GetMetadata(automaticObjectId);assert(A:AuthorizeSync(automaticPayload,automaticMeta,"Relay"),"owner-authored automatic event may be relayed");local forged=HolyStorm.Utils.DeepCopy(automaticPayload);forged.data.awards[2]=HolyStorm.Utils.DeepCopy(forged.data.awards[1]);assert(not A:AuthorizeSync(forged,automaticMeta,"Relay"),"automatic event cannot award another recipient")
allowed=false;local denied,deniedReason=A:PreviewManual(feat.achievementID,"MANUAL",{},false);assert(not denied and deniedReason=="PERMISSION_DENIED","service permission enforcement");allowed=true
assert(registeredDomain and links.achievement and links.achievement.onClick,"sync and central rich-link registration")
local portable={guildId="realm:guild",kind="D",id="achievement-new-client",data={achievementID="achievement-new-client",name="New provider",description="",icon=1,type="AUTOMATIC",category="Future",status="ACTIVE",scope="CHARACTER",createdBy="Player-Remote",createdAt=clock,updatedBy="Player-Remote",updatedAt=clock,revision=1,dependencies={"futureData"},rule={field="future.provider",operator="=",value="yes"}}};local portableObject=HolyStorm.Data.AchievementStore:ObjectId("D",portable.id);assert(A:ValidateSync(portable,{owner="Player-Remote",version=1,updatedAt=clock},portableObject),"unknown future provider remains portable");local portableResult=HolyStorm.Rules:EvaluateDetailed(portable.data.rule,HolyStorm.Policy:BuildContext(nil,"Player-Local"));assert(portableResult=="UNKNOWN","unknown provider never grants an award")
A:QueueEvaluation("Player-Local","equipment");assert(queued[#queued].options.mergeKey==automatic.achievementID.."\031Player-Local","dependency-indexed coalescing key")
for i=1,500 do local d=A:NormalizeDefinition({name="Scale "..i,category="Scale",type="MANUAL",status="DRAFT",scope="CHARACTER"});HolyStorm.Data.AchievementStore:Put("D",d.achievementID,d,"Player-Local")end;for i=1,1000 do local eventID="scale-event-"..i;HolyStorm.Data.AchievementStore:Put("E",eventID,{awardInstanceID=eventID,achievementID=feat.achievementID,definitionRevision=feat.revision,capturedAt=clock,awardedAt=clock,awardedBy="Player-Local",provenance={kind="IMPORT_TEST"},candidateSnapshot={},status="ACTIVE",awards={{awardID=eventID..":Player-Scale-"..i,achievementID=feat.achievementID,awardInstanceID=eventID,recipientID="Player-Scale-"..i,recipientScope="CHARACTER",characterUUID="Player-Scale-"..i,awardedAt=clock,awardedBy="Player-Local",definitionRevision=feat.revision,provenance="IMPORT_TEST",status="AWARDED"}}},"Player-Local")end;A:RebuildIndex();assert(#A:GetDefinitions(true,"Player-Local")>=504 and#HolyStorm.Data.AchievementStore:GetAwardsFor(feat.achievementID)>=1000,"500 definitions and 1000-award index scale")
print("Achievement definitions, tri-state rules, automatic/manual awards, snapshots, revoke, sync, permissions, links and scale tests passed")
