local repository=arg[0]:gsub("tools[/\\]test_guild_management.lua$","")
local core=repository.."LIVE/Holy_Storm/";local feature=repository.."LIVE/Holy_Storm_Guild/"
local clock=1000;local actorGuid="Player-Local";function time()return clock end;function UnitGUID()return actorGuid end
local function copy(value,seen)if type(value)~="table"then return value end;seen=seen or{};if seen[value]then return seen[value]end;local out={};seen[value]=out;for key,child in pairs(value)do out[copy(key,seen)]=copy(child,seen)end;return out end
local locale=setmetatable({GUILD_TASK_NOTE_EXPIRATION="Expire"},{__index=function(_,key)return key end})
local HolyStorm={Utils={DeepCopy=copy,Now=function()return clock end,Trim=function(value)return tostring(value or""):match("^%s*(.-)%s*$")end},Data={},db={global={}},Events={emitted={}},Sync={domains={},published={}},Tasks={types={},queued={}},PermissionEngine={},Accounts={}}
function LibStub(name)if name=="AceLocale-3.0"then return{GetLocale=function()return locale end}end;return{GetAddon=function()return HolyStorm end}end
function HolyStorm.Events:Emit(event,...)self.emitted[#self.emitted+1]={event,...}end
function HolyStorm.Sync:RegisterDomain(id,definition)self.domains[id]=definition;return true end
function HolyStorm.Sync:Publish(domain,id,reason)self.published[#self.published+1]={domain=domain,id=id,reason=reason};return true end
function HolyStorm.Tasks:RegisterTaskType(id,definition)self.types[id]=definition;return true end
function HolyStorm.Tasks:Queue(id,options)local token="task-"..(#self.queued+1);self.queued[#self.queued+1]={id=id,options=options};return token end
function HolyStorm.Tasks:Cancel()return true end
local accounts={["Player-Local"]="account-local",["Player-Twink"]="account-local",["Player-Officer"]="account-officer",["Player-Officer2"]="account-officer2",["Player-Member"]="account-member"}
function HolyStorm.Accounts:GetLocalAccountUUID()return accounts[actorGuid]end
function HolyStorm.Accounts:GetAccountUUIDForCharacter(guid)return accounts[guid]end
HolyStorm.Data.PlayerStore={GetLocalPlayerId=function()return accounts[actorGuid]end,GetCharacterOwner=function(_,guid)return accounts[guid]end}
HolyStorm.Data.GuildStore={GetCurrent=function()return{id="realm:guild",roster={["Player-Local"]={name="Local-Realm",online=true},["Player-Officer"]={name="Officer-Realm",online=true},["Player-Member"]={name="Member-Realm",online=true}}}end}
function HolyStorm.PermissionEngine:Can(permission,accountUUID,characterUUID)
 accountUUID=accountUUID or accounts[actorGuid];characterUUID=characterUUID or actorGuid
 if accountUUID=="account-officer"or accountUUID=="account-officer2"then return true end
 local member={ ["guild-notes-view"]=true,["guild-absences-view"]=true,["guild-absences-manage-own"]=true }
 if permission=="guild-notes-edit-own"or permission=="guild-notes-delete-own"then return accountUUID=="account-local"end
 return member[permission]==true
end
local schemas,roots={},{ }
HolyStorm.DataManager={}
function HolyStorm.DataManager:RegisterSchema(definition)schemas[definition.id]=definition;return{ok=true}end
local function valueAt(root,path)local value=root;for _,key in ipairs(path or{})do value=type(value)=="table"and value[key];if value==nil then return nil end end;return value end
function HolyStorm.DataManager:Get(id,path)return copy(valueAt(roots[id],path))end
function HolyStorm.DataManager:Commit(id,path,value)local schema=schemas[id];local root=roots[id]or schema.default();roots[id]=root;local parent=root;for index=1,#path-1 do parent[path[index]]=parent[path[index]]or{};parent=parent[path[index]]end;parent[path[#path]]=copy(value);assert(schema.validate(root));return{ok=true,changed=true,value=copy(value)}end

assert(loadfile(feature.."GuildManagementRegistry.lua"))();assert(loadfile(feature.."Persistence/GuildManagementStore.lua"))();assert(loadfile(feature.."Services/PlayerNotes.lua"))();assert(loadfile(feature.."Services/Absences.lua"))()
local GM=HolyStorm.GuildManagement;local Notes,Absences=GM.Notes,GM.Absences
assert(GM:RegisterFeature({id="notes",order=20,build=function()end}));assert(GM:RegisterFeature({id="absences",order=30,build=function()end}));assert(GM:RegisterFeature({id="future",order=40,build=function()end}));assert(#GM:GetFeatures()==3 and GM:GetFeatures()[3].id=="future","parent supports registered future children")
assert(#Notes:GetCategories()==5 and Notes:RegisterCategory("CUSTOM_TEST","GUILD_NOTE_CATEGORY_CUSTOM_TEST",99)and#Notes:GetCategories()==6,"note categories use the extensible registry")
Notes:Initialize();Absences:Initialize();assert(HolyStorm.Sync.domains.guildNotes and HolyStorm.Sync.domains.guildAbsences,"shared domains registered");assert(not HolyStorm.Sync.domains.privateNotes,"private notes have no sync domain")
local ok,private=Notes:SavePrivate({subjectCharacterUUID="Player-Twink",category="GENERAL",text=" local only "},0);assert(ok and private.localAccountUUID=="account-local"and private.text=="local only");assert(#HolyStorm.Sync.published==0,"private note content and metadata never enter sync")
assert(#Notes:List({subjectAccountUUID="account-local"})==1,"private notes are account-wide across known characters")
local privateDelete;ok,privateDelete=Notes:SavePrivate({subjectCharacterUUID="Player-Member",category="ATTENTION",text="Temporary private note"},0);assert(ok);local privatePublishes=#HolyStorm.Sync.published;ok,privateDelete=Notes:Delete(privateDelete.noteId,"PRIVATE",privateDelete.revision);assert(ok and privateDelete.status=="DELETED"and#HolyStorm.Sync.published==privatePublishes,"private edit/delete stays local and retains a local tombstone")
actorGuid="Player-Member";local deniedShared,deniedReason=Notes:SaveShared({subjectCharacterUUID="Player-Member",category="GENERAL",text="Denied",visibility="PUBLIC"},0);assert(not deniedShared and deniedReason=="PERMISSION_DENIED","shared create permission is enforced without restricting private notes")
actorGuid="Player-Officer";local shared;ok,shared=Notes:SaveShared({subjectCharacterUUID="Player-Member",category="RAID",text="Bring flasks",visibility="OFFICERS"},0);assert(ok and shared.authorCharacterUUID=="Player-Officer"and#HolyStorm.Sync.published==1 and Notes:Get(shared.noteId,"SHARED").text=="Bring flasks","shared note persists in its synchronized schema")
local domain=HolyStorm.Sync.domains.guildNotes;local meta=domain.getMetadata(shared.noteId);assert(not domain.canShare(meta,"Player-Member")and domain.canShare(meta,"Player-Officer"),"visibility is permission-backed before delivery")
local changedVisibility=copy(shared);changedVisibility.visibility="PUBLIC";local visibilityOk,visibilityReason=Notes:SaveShared(changedVisibility,shared.revision);assert(not visibilityOk and visibilityReason=="IMMUTABLE_VISIBILITY","shared visibility is immutable so former recipients cannot retain a stale readable revision")
shared.text="Author edit";ok,shared=Notes:SaveShared(shared,shared.revision);assert(ok and shared.revision==2 and shared.authorCharacterUUID=="Player-Officer","author can edit their own shared note")
actorGuid="Player-Officer2";shared.text="Elevated edit";ok,shared=Notes:SaveShared(shared,shared.revision);assert(ok and shared.authorCharacterUUID=="Player-Officer"and shared.lastEditorCharacterUUID=="Player-Officer2","elevated edit preserves authorship")
local stale=copy(shared);stale.revision=shared.revision-1;assert(not domain.import(shared.noteId,stale,{version=stale.revision}),"stale shared note rejected")
ok,shared=Notes:Delete(shared.noteId,"SHARED",shared.revision);assert(ok and shared.status=="DELETED"and shared.text=="");assert(not domain.import(shared.noteId,stale,{version=stale.revision}),"stale data cannot resurrect a deleted note")
local received={noteId="note-remote",guildId="realm:guild",scope="SHARED",subjectAccountUUID="account-member",subjectCharacterUUID="Player-Member",authorAccountUUID="account-officer",authorCharacterUUID="Player-Officer",lastEditorAccountUUID="account-officer",lastEditorCharacterUUID="Player-Officer",category="GENERAL",text="Remote",visibility="PUBLIC",createdAt=clock,modifiedAt=clock,revision=1,status="ACTIVE"};local receivedMeta={objectId=received.noteId,owner="Player-Officer",origin="Player-Officer",version=1,updatedAt=clock,guildId="realm:guild"};actorGuid="Player-Local";assert(domain.validate(received,receivedMeta,received.noteId)and domain.authorize(received,receivedMeta)and domain.import(received.noteId,received,receivedMeta),"authorized recipient synchronizes a shared note")
local relayedNote=copy(received);relayedNote.revision=2;relayedNote.modifiedAt=clock+1;relayedNote.lastEditorAccountUUID="account-officer2";relayedNote.lastEditorCharacterUUID="Player-Officer2";relayedNote.text="Relayed";local relayedNoteMeta={objectId=received.noteId,owner="Player-Officer2",origin="Player-Officer",version=2,updatedAt=clock+1,guildId="realm:guild",receivedFrom="Relay-Realm"};assert(domain.validate(relayedNote,relayedNoteMeta,received.noteId)and domain.authorize(relayedNote,relayedNoteMeta)and domain.import(received.noteId,relayedNote,relayedNoteMeta));local storedNote=Notes:Get(received.noteId,"SHARED");assert(storedNote.authorCharacterUUID=="Player-Officer"and storedNote.receivedFrom=="Relay-Realm","shared-note relay preserves original provenance separately from relay metadata")
actorGuid="Player-Local";local expiring;ok,expiring=Notes:SavePrivate({subjectCharacterUUID="Player-Local",category="GENERAL",text="Expires",expiresAt=clock+10},0);assert(ok);clock=1011;assert(#Notes:List({subjectAccountUUID="account-local"})==1 and#Notes:List({subjectAccountUUID="account-local",includeExpired=true})==2,"expired private notes leave the active view but remain history")
clock=1000;local first,second,past;ok,first=Absences:Save({startAt=900,endAt=1100,title="Current",reason=""},0);assert(ok and first.ownerAccountUUID=="account-local");ok,second=Absences:Save({startAt=1200,endAt=1300,title="Future",reason="Trip"},0);assert(ok and second.absenceId~=first.absenceId);ok,past=Absences:Save({startAt=700,endAt=800,title="Past",reason="History"},0);assert(ok);assert(#Absences:List({state="ACTIVE"})==1 and#Absences:List({state="UPCOMING"})==1 and#Absences:List({state="PAST"})==1,"multiple current, future, and historical absences classify")
actorGuid="Player-Twink";second.title="Updated from twink";ok,second=Absences:Save(second,second.revision);assert(ok and second.ownerAccountUUID=="account-local"and second.ownerCharacterUUID=="Player-Local"and second.modifiedByCharacterUUID=="Player-Twink","another character on the owner account can revise one account-oriented absence without duplication")
actorGuid="Player-Local"
local invalid,reason=Absences:Save({startAt=1400,endAt=1300},0);assert(not invalid and reason=="END_BEFORE_START","absence date validation")
local absenceDomain=HolyStorm.Sync.domains.guildAbsences;local absenceMeta=absenceDomain.getMetadata(first.absenceId);assert(absenceMeta.origin=="Player-Local"and absenceMeta.originAccountUUID=="account-local","absence origin provenance is immutable metadata")
assert(absenceDomain.authorize(first,absenceMeta),"absence owner revision is authorized");local forgedMeta=copy(absenceMeta);forgedMeta.owner="Player-Member";assert(not absenceDomain.authorize(first,forgedMeta),"non-owner without administrative permission cannot issue absence revisions")
ok,first=Absences:Save({absenceId=first.absenceId,startAt=900,endAt=1150,title="Extended"},first.revision);assert(ok and first.originCharacterUUID=="Player-Local"and first.revision==2,"owner creates monotonic revisions")
local old=copy(first);old.revision=1;assert(not absenceDomain.import(first.absenceId,old,{version=1}),"old absence cannot overwrite newer data")
actorGuid="Player-Officer";ok,first=Absences:Delete(first.absenceId,first.revision);assert(ok and first.status=="DELETED"and first.originCharacterUUID=="Player-Local"and first.modifiedByCharacterUUID=="Player-Officer","administrator tombstone preserves origin")
assert(not absenceDomain.import(first.absenceId,old,{version=1}),"old absence cannot resurrect a tombstone")
local history=Absences:List({state="PAST",includeDeleted=true});local sawCancelled=false;for _,entry in ipairs(history)do if entry.absenceId==first.absenceId and entry.state=="CANCELLED"then sawCancelled=true end end;assert(sawCancelled and#history>=2,"history retains both ended and cancelled absences")
local relayed=copy(second);relayed.revision=second.revision+1;relayed.modifiedAt=clock+5;relayed.receivedFrom=nil;assert(absenceDomain.import(second.absenceId,relayed,{version=relayed.revision,receivedFrom="Relay-Realm"}));local stored=Absences:Get(second.absenceId);assert(stored.originCharacterUUID==second.originCharacterUUID and stored.receivedFrom=="Relay-Realm","relay preserves origin provenance")
for _,localeName in ipairs({"GuildManagement_enUS.lua","GuildManagement_deDE.lua"})do local file=assert(io.open(feature.."Locales/"..localeName,"rb"));local source=file:read("*a");file:close();for _,key in ipairs({"GUILD_MANAGEMENT_TITLE","GUILD_NOTES_EMPTY","GUILD_ABSENCE_ACTIVE","GUILD_ERROR_IMMUTABLE_VISIBILITY","PERMISSION_GUILD_NOTES_VIEW","PERMISSION_GUILD_ABSENCES_MANAGE_ANY","GUILD_RULE_ABSENCE_CURRENT"})do assert(source:find(key,1,true),localeName.." missing "..key)end end
for _,localeName in ipairs({"Activity_enUS.lua","Activity_deDE.lua"})do local file=assert(io.open(feature.."Locales/"..localeName,"rb"));local source=file:read("*a");file:close();for _,key in ipairs({"GUILD_ACTIVITY","GUILD_ACTION_VIEW_ACTIVITY","PERMISSION_GUILD_ACTIVITY_VIEW","GUILD_RULE_ACTIVITY_LAST_SEEN","GUILD_ACTIVITY_TYPE_MYTHICPLUS_RUN"})do assert(source:find(key,1,true),localeName.." missing "..key)end end
local ui=assert(io.open(feature.."UI/GuildManagementUI.lua","rb"));local uiSource=ui:read("*a");ui:close();assert(uiSource:find("CreateTabGroup",1,true)and uiSource:find("CreateTable",1,true)and uiSource:find("CreateEditBox",1,true)and uiSource:find("CreateColumn",1,true)and uiSource:find("SetSelection",1,true),"Guild Management UI uses shared responsive components");assert(uiSource:find("if not self.built[id]",1,true),"child UI is lazy")
assert(uiSource:find('mode=="create"',1,true)and uiSource:find('includeDeleted=self.absenceState=="PAST"',1,true)and uiSource:find('GM:Can("guild-notes-create")',1,true),"context-create, cancellation history, and unavailable shared scope have explicit UI behavior")
local activityUI=assert(io.open(feature.."UI/ActivityUI.lua","rb"));local activityUISource=activityUI:read("*a");activityUI:close();assert(activityUISource:find("CreateColumn",1,true)and activityUISource:find("CreateRow",1,true)and activityUISource:find("CreateTable",1,true)and activityUISource:find("SetSelection",1,true)and activityUISource:find("GetOverview",1,true)and activityUISource:find("GetHistory",1,true),"Activity overview, detail, filters and empty states use shared responsive UI components");assert(activityUISource:find("activityTypeFilter",1,true)and activityUISource:find("activityProviderFilter",1,true)and activityUISource:find("activityCharacterFilter",1,true)and not activityUISource:find("SetPoint",1,true),"Activity filtering and resize rely on shared layout rather than manual positioning")
local guildUI=assert(io.open(feature.."Guild.lua","rb"));local guildUISource=guildUI:read("*a");guildUI:close();assert(guildUISource:find("for index = 1, 4",1,true)and guildUISource:find("menu.contextActions",1,true),"Guild roster reuses its CharacterActions surface for all four Guild Management actions")
local moduleFile=assert(io.open(feature.."GuildManagement.lua","rb"));local moduleSource=moduleFile:read("*a");moduleFile:close();for _,id in ipairs({"guild-notes-view","guild-notes-create","guild-notes-edit-own","guild-notes-edit-any","guild-notes-delete-own","guild-notes-delete-any","guild-notes-manage-categories","guild-absences-view","guild-absences-manage-own","guild-absences-manage-any","guild-activity-view"})do assert(moduleSource:find(id,1,true),"missing permission "..id)end;assert(moduleSource:find('permission("guild-notes-view",L["GUILD_NOTES"],{officers=true,member=true})',1,true)and moduleSource:find('permission("guild-absences-manage-any",L["GUILD_ABSENCES"],{officers=true})',1,true)and moduleSource:find('permission("guild-activity-view",L["GUILD_ACTIVITY"],{officers=true,member=true})',1,true),"permission defaults changed");assert(moduleSource:find('enabled=canViewAbsences and accountUUID~=nil',1,true)and moduleSource:find('canUsePrivateNotes=characterUUID~=nil',1,true)and moduleSource:find('GM:Open("activity",characterUUID,"view")',1,true),"context actions preserve private access and resolve Activity through the reusable provider");assert(moduleSource:find('return entry.startAt end',1,true)and moduleSource:find('return entry.endAt end',1,true)and moduleSource:find('return nil,"PERMISSION_DENIED"',1,true),"absence rule fields preserve values and UNKNOWN permission semantics");for _,field in ipairs({"activity.lastSeen","activity.daysSinceLastActivity","activity.onlineDuration7d","activity.guildChatCount7d","activity.raidParticipation30d","activity.mythicPlusParticipation30d","activity.eventAttendance30d"})do assert(moduleSource:find(field,1,true),"missing Activity Rule field "..field)end;assert(moduleSource:find('id="activity",order=30',1,true)and moduleSource:find('GM.Activity:Initialize()',1,true),"Activity is the third lazy Guild Management child");assert(not moduleSource:find("Calendar",1,true),"Guild Management remains uncoupled from Calendar")
print("Guild Management notes, absences, privacy, revision and registration tests passed")
