local repository=arg[0]:gsub("tools[/\\]test_guild_activity.lua$","")
local feature=repository.."LIVE/Holy_Storm_Guild/"
local clock=1700000000;local actorGuid="Player-Local";local loggedIn=false
date=os.date;function time()return clock end;function UnitGUID(unit)if not unit or unit=="player"then return actorGuid elseif unit=="party1"then return"Player-Member"elseif unit=="party2"then return"Player-Outsider"end end
function GetUnitName()return actorGuid=="Player-Twink"and"Twink-Realm"or"Local-Realm"end;function IsInGuild()return true end;function IsLoggedIn()return loggedIn end;function IsInRaid()return false end;local grouped=false;function IsInGroup()return grouped end;function GetNumGroupMembers()return grouped and 3 or 1 end
function GetInstanceInfo()return"Test Raid","raid",16,"Mythic",20,nil,nil,2657 end
C_ChallengeMode={GetActiveChallengeMapID=function()return 503 end,GetActiveKeystoneInfo=function()return 12 end,GetChallengeCompletionInfo=function()return{mapChallengeModeID=503,level=12,time=1820000,onTime=true,keystoneUpgradeLevels=2,practiceRun=false}end,GetMapUIInfo=function()return"Test Dungeon"end}
local function copy(value,seen)if type(value)~="table"then return value end;seen=seen or{};if seen[value]then return seen[value]end;local out={};seen[value]=out;for key,child in pairs(value)do out[copy(key,seen)]=copy(child,seen)end;return out end
local locale=setmetatable({GUILD_ACTIVITY_TASK_CAPTURE="Capture",GUILD_ACTIVITY_TASK_CHAT="Chat",GUILD_ACTIVITY_TASK_SESSION="Session"},{__index=function(_,key)return key end})
local HolyStorm={Utils={DeepCopy=copy,Now=function()return clock end,SafeCall=function(_,fn,...)local result={pcall(fn,...)};if not result[1]then return false,result[2]end;return true,table.unpack(result,2)end},Data={},Events={listeners={},emitted={}},Sync={domains={},published={}},Tasks={types={},queued={}},Logger={history={}},PermissionEngine={},Accounts={},TwinkCore={}}
function LibStub(name)if name=="AceLocale-3.0"then return{GetLocale=function()return locale end}end;return{GetAddon=function()return HolyStorm end}end
function HolyStorm.Events:Register(event,owner,callback)self.listeners[event]=self.listeners[event]or{};self.listeners[event][owner]=callback;return true end
function HolyStorm.Events:UnregisterOwner(owner)for _,listeners in pairs(self.listeners)do listeners[owner]=nil end end
function HolyStorm.Events:Emit(event,...)self.emitted[#self.emitted+1]={event,...};for _,callback in pairs(self.listeners[event]or{})do callback(event,...)end end
function HolyStorm.Sync:RegisterDomain(id,definition)self.domains[id]=definition;return true end
function HolyStorm.Sync:Publish(domain,id,reason)self.published[#self.published+1]={domain=domain,id=id,reason=reason};return true end
function HolyStorm.Tasks:RegisterTaskType(id,definition)self.types[id]=definition;return true end
function HolyStorm.Tasks:Queue(id,options)local task={id=id,metadata=copy(options and options.metadata),options=copy(options)};self.queued[#self.queued+1]=task;return"task-"..#self.queued end
local function runTasks()while#HolyStorm.Tasks.queued>0 do local task=table.remove(HolyStorm.Tasks.queued,1);local definition=assert(HolyStorm.Tasks.types[task.id],task.id);definition.execute(task)end end
function HolyStorm.Logger:Write(level,source,category,message,context)self.history[#self.history+1]={level=level,source=source,category=category,message=message,context=context}end
local accounts={['Player-Local']="account-local",['Player-Twink']="account-local",['Player-Member']="account-member",['Player-Remote']="account-remote"}
function HolyStorm.Accounts:GetLocalAccountUUID()return accounts[actorGuid]end;function HolyStorm.Accounts:GetAccountUUIDForCharacter(guid)return accounts[guid]end
function HolyStorm.TwinkCore:GetAccountMain(account)return account=="account-local"and"Player-Local"or account=="account-remote"and"Player-Remote"end
HolyStorm.Data.PlayerStore={GetLocalPlayerId=function()return accounts[actorGuid]end,GetCharacterOwner=function(_,guid)return accounts[guid]end}
HolyStorm.Data.CharacterStore={Get=function(_,guid)return{name=guid}end}
local roster={['Player-Local']={name="Local-Realm",online=true},['Player-Twink']={name="Twink-Realm",online=true},['Player-Member']={name="Member-Realm",online=true},['Player-Remote']={name="Remote-Realm",online=true}}
HolyStorm.Data.GuildStore={GetCurrent=function()return{id="realm:guild",roster=roster}end}
function HolyStorm.PermissionEngine:Can(permission)return permission=="guild-activity-view"end
local schemas,roots={},{};HolyStorm.DataManager={}
function HolyStorm.DataManager:RegisterSchema(definition)schemas[definition.id]=definition;return{ok=true}end
local function valueAt(root,path)local value=root;for _,key in ipairs(path or{})do value=type(value)=="table"and value[key];if value==nil then return nil end end;return value end
function HolyStorm.DataManager:Get(id,path)return copy(valueAt(roots[id],path))end
function HolyStorm.DataManager:Commit(id,path,value)local schema=assert(schemas[id]);local root=roots[id]or schema.default();roots[id]=root;local parent=root;for index=1,#path-1 do parent[path[index]]=parent[path[index]]or{};parent=parent[path[index]]end;parent[path[#path]]=copy(value);assert(schema.validate(root));return{ok=true,changed=true,value=copy(value)}end
function HolyStorm.DataManager:Transaction(id,path,mutator,context)local current=self:Get(id,path);local replacement=mutator(current,context or{});return self:Commit(id,path,replacement,context)end

assert(loadfile(feature.."GuildManagementRegistry.lua"))();assert(loadfile(feature.."Persistence/ActivityStore.lua"))();assert(loadfile(feature.."Services/GuildActivity.lua"))();assert(loadfile(feature.."Providers/OnlineActivity.lua"))();assert(loadfile(feature.."Providers/GuildChatActivity.lua"))();assert(loadfile(feature.."Providers/RaidActivity.lua"))();assert(loadfile(feature.."Providers/MythicPlusActivity.lua"))()
local GM,Activity=HolyStorm.GuildManagement,HolyStorm.GuildManagement.Activity
Activity:Initialize();Activity:Enable();assert(#Activity:GetProviders()==4 and not Activity:IsTypeAvailable("EVENT_ATTENDANCE"),"four capture providers load while Calendar attendance stays unavailable")
local registered,reason=Activity:RegisterProvider("raid",{types={"RAID_ENCOUNTER"}});assert(not registered and reason=="PROVIDER_EXISTS","duplicate providers are rejected")
local malformed,malformedReason=Activity:RegisterProvider("malformed",{types={"RAID_ENCOUNTER"},normalize="not-a-function"});assert(not malformed and malformedReason=="INVALID_PROVIDER_CALLBACK","malformed provider contracts are rejected")
assert(Activity:RegisterProvider("test-provider",{types={"EVENT_ATTENDANCE"}}));assert(Activity:UnregisterProvider("test-provider")and not Activity.providers['test-provider'],"providers can be unloaded without affecting history")
assert(Activity:DisableProvider("raid")and not Activity:IsTypeAvailable("RAID_ENCOUNTER"));assert(Activity:EnableProvider("raid")and Activity:IsTypeAvailable("RAID_ENCOUNTER"),"providers are lifecycle-aware")

assert(Activity:OpenSession("LOGIN"));local shard=HolyStorm.Data.GuildActivityStore:GetShard("account-local");local sessionId=shard.openSession.sessionId;clock=clock+70;assert(Activity:OpenSession("PLAYER_ENTERING_WORLD"));shard=HolyStorm.Data.GuildActivityStore:GetShard("account-local");assert(shard.openSession.sessionId==sessionId and next(shard.details)==nil and shard.openSession.lastObservedAt==clock,"zoning checkpoints one open session without fabricating a close")
clock=clock+50;local closeOk,closeReason=Activity:CloseSession("CLOSED","PLAYER_LOGOUT");if not closeOk then for _,entry in ipairs(HolyStorm.Logger.history)do print(entry.message,entry.context and entry.context.reason)end end;assert(closeOk,closeReason);shard=HolyStorm.Data.GuildActivityStore:GetShard("account-local");local onlineEvent;for _,entry in pairs(shard.details)do if entry.type=="ONLINE_SESSION"then onlineEvent=entry end end;assert(onlineEvent and onlineEvent.duration==120 and onlineEvent.status=="CLOSED"and shard.lifetime.onlineDuration==120,"normal online close records exact observed duration")
assert(Activity:OpenSession("FAST_SWITCH"));local fastFirst=HolyStorm.Data.GuildActivityStore:GetShard("account-local").openSession.sessionId;assert(Activity:CloseSession("CLOSED","FAST_SWITCH"));assert(Activity:OpenSession("FAST_SWITCH"));local fastSecond=HolyStorm.Data.GuildActivityStore:GetShard("account-local").openSession.sessionId;assert(fastFirst~=fastSecond and Activity:CloseSession("CLOSED","FAST_SWITCH"),"same-second character/session boundaries retain unique stable IDs")
clock=clock+10;assert(Activity:OpenSession("LOGIN"));clock=clock+40;assert(Activity:OpenSession("PLAYER_ENTERING_WORLD"));Activity.currentSessionId=nil;clock=clock+100;assert(Activity:OpenSession("ACTIVITY_ENABLE"));shard=HolyStorm.Data.GuildActivityStore:GetShard("account-local");local recovered;for _,entry in pairs(shard.details)do if entry.type=="ONLINE_SESSION"and entry.status=="RECOVERED"then recovered=entry end end;assert(recovered and recovered.duration==40 and recovered.metadata.uncertain==true and shard.openSession,"reload recovery ends at the last coarse checkpoint and explicitly marks uncertainty")

HolyStorm.Events:Emit("CHAT_MSG_GUILD","secret message must disappear","Local-Realm","Common","Guild",nil,nil,0,1,"Guild",nil,77,"Player-Local");HolyStorm.Events:Emit("CHAT_MSG_PARTY","not guild","Local-Realm");assert(Activity:FlushChat());shard=HolyStorm.Data.GuildActivityStore:GetShard("account-local");assert(shard.lifetime.guildChatCount==1,"only guild-chat participation is counted")
local function contains(value,needle,seen)if type(value)=="string"then return value:find(needle,1,true)~=nil elseif type(value)~="table"then return false end;seen=seen or{};if seen[value]then return false end;seen[value]=true;for key,child in pairs(value)do if contains(key,needle,seen)or contains(child,needle,seen)then return true end end;return false end
assert(not contains(roots,"secret message"),"guild-chat content is never persisted")
local chatHistory=assert(Activity:GetHistory("account-local",clock-86400,clock,{activityType="GUILD_CHAT"}));assert(#chatHistory==1 and chatHistory[1].characterUUID=="Player-Local","daily guild-chat facts retain contributing Character provenance")

clock=clock+30;HolyStorm.Events:Emit("ENCOUNTER_START",2900,"Test Boss",16,10);clock=clock+15;HolyStorm.Events:Emit("ENCOUNTER_END",2900,"Test Boss",16,10,1);actorGuid="Player-Twink";runTasks();actorGuid="Player-Local";shard=HolyStorm.Data.GuildActivityStore:GetShard("account-local");local capturedRaid;for _,entry in pairs(shard.details)do if entry.type=="RAID_ENCOUNTER"then capturedRaid=entry end end;assert(shard.lifetime.raidParticipation==1 and capturedRaid.characterUUID=="Player-Local","queued raid normalization preserves capture-time identity across a character change")
local raidPayload={encounterId=2900,encounterName="Test Boss",difficultyId=16,groupSize=10,success=true,startedAt=clock-15,occurredAt=clock,instance={instanceId=2657,name="Test Raid"},group={classification="FULL_GUILD",groupSize=1,guildMembers=1}};local duplicate,duplicateReason=Activity:CaptureNow("raid","RAID_ENCOUNTER",raidPayload);assert(not duplicate and duplicateReason=="DUPLICATE","deterministic raid identity suppresses duplicate observations per participant")
clock=clock+30;HolyStorm.Events:Emit("CHALLENGE_MODE_START");clock=clock+1820;HolyStorm.Events:Emit("CHALLENGE_MODE_COMPLETED");runTasks();shard=HolyStorm.Data.GuildActivityStore:GetShard("account-local");assert(shard.lifetime.mythicPlusParticipation==1,"completed Mythic+ participation is normalized")
local mythicEvent;for _,entry in pairs(shard.details)do if entry.type=="MYTHICPLUS_RUN"then mythicEvent=entry end end;local mythicDuplicate,mythicReason=Activity:CaptureNow("mythic-plus","MYTHICPLUS_RUN",{challengeMapId=mythicEvent.metadata.challengeMapId,keystoneLevel=mythicEvent.metadata.keystoneLevel,durationMs=mythicEvent.metadata.durationMs,timed=mythicEvent.metadata.timed,upgradeLevels=mythicEvent.metadata.upgradeLevels,practiceRun=mythicEvent.metadata.practiceRun,startedAt=mythicEvent.startedAt,occurredAt=mythicEvent.occurredAt,dungeonName=mythicEvent.metadata.dungeonName,group={classification=mythicEvent.metadata.guildClassification,groupSize=mythicEvent.metadata.groupSize,guildMembers=mythicEvent.metadata.guildMembers}});assert(not mythicDuplicate and mythicReason=="DUPLICATE","deterministic Mythic+ identity suppresses duplicate participant facts")
grouped=true;local group=Activity:SnapshotGuildGroup();assert(group.classification=="MAJORITY_GUILD"and group.groupSize==3 and group.guildMembers==2 and Activity:IsGuildRelevant(group),"central group policy classifies mixed groups factually");grouped=false
local irrelevant,irrelevantReason=Activity:CaptureNow("raid","RAID_ENCOUNTER",{encounterId=2901,encounterName="Other",difficultyId=16,success=true,startedAt=clock-5,occurredAt=clock,instance={instanceId=2657},group={classification="NOT_GUILD_RELEVANT",groupSize=5,guildMembers=0}});assert(not irrelevant and irrelevantReason=="NOT_GUILD_RELEVANT","non-guild groups are excluded by the central relevance policy")

actorGuid="Player-Twink";clock=clock+30;local twinkPayload=copy(raidPayload);twinkPayload.startedAt=clock-10;twinkPayload.occurredAt=clock;assert(Activity:CaptureNow("raid","RAID_ENCOUNTER",twinkPayload));shard=HolyStorm.Data.GuildActivityStore:GetShard("account-local");assert(shard.accountUUID=="account-local"and shard.characters['Player-Local']and shard.characters['Player-Twink']and shard.originCharacterUUID=="Player-Local","known twinks aggregate once at Account scope while preserving character provenance")
local aggregate=assert(Activity:GetAggregate("account-local",clock-86400,clock));assert(aggregate.raidParticipation==2 and aggregate.mythicPlusParticipation==1);local twinkAggregate=assert(Activity:GetAggregate("account-local",clock-86400,clock,{characterUUID="Player-Twink"}));assert(twinkAggregate.raidParticipation==1,"range queries support account and character facts")
local allTimeTwink=assert(Activity:GetAggregate("account-local",0,clock,{characterUUID="Player-Twink"}));assert(allTimeTwink.raidParticipation==1,"lifetime aggregates retain per-character provenance beyond detailed retention")
local missing,missingReason=Activity:GetAggregate("account-unknown",0,clock);assert(not missing and missingReason=="MISSING_ACTIVITY_DATA","unknown accounts remain UNKNOWN instead of factual zero")

local oldAt=clock-200*86400;local oldEvent={schemaVersion=1,type="ONLINE_SESSION",eventId=Activity:DeterministicId("online","account-local","Player-Twink",oldAt),occurrenceId="old",accountUUID="account-local",characterUUID="Player-Twink",providerId="online",source="wow-session",startedAt=oldAt,endedAt=oldAt+60,occurredAt=oldAt+60,duration=60,status="CLOSED",metadata={uncertain=false}};assert(Activity:AddEventToShard(shard,oldEvent));local lifetimeBefore=shard.lifetime.onlineDuration;shard.lastCompactedAt=0;assert(Activity:CompactShard(shard,clock));assert(not shard.details[oldEvent.eventId]and shard.lifetime.onlineDuration==lifetimeBefore,"old online detail compacts without losing lifetime facts");local weeksBefore=0;for _ in pairs(shard.weeks)do weeksBefore=weeksBefore+1 end;assert(not Activity:CompactShard(shard,clock)and weeksBefore>0,"repeated compaction is deterministic and does not double-count")
local split=Activity:NewShard("account-split","Player-Local","realm:guild");local boundary=math.floor(clock/86400)*86400;Activity:AddOnlineDuration(split,"Player-Local",boundary-30,boundary+30);local splitDays=0;for _,bucket in pairs(split.days)do splitDays=splitDays+1;assert(bucket.onlineDuration==30)end;assert(splitDays==2 and split.lifetime.onlineDuration==60,"online duration splits across UTC day boundaries without DST-sensitive local dates")
local large=Activity:NewShard("account-large","Player-Local","realm:guild");for index=1,2605 do local at=clock-index;assert(Activity:AddEventToShard(large,{schemaVersion=1,type="RAID_ENCOUNTER",eventId="large-"..index,occurrenceId="occurrence-"..index,accountUUID="account-large",characterUUID="Player-Local",providerId="raid",source="synthetic-test",occurredAt=at,metadata={encounterId=1,success=true}}))end;large.lastCompactedAt=0;assert(Activity:CompactShard(large,clock));local largeDetails=0;for _ in pairs(large.details)do largeDetails=largeDetails+1 end;assert(largeDetails==Activity.detailLimit and large.lifetime.raidParticipation==2605,"large histories cap detail while preserving long-term aggregate facts")

local invalid=copy(oldEvent);invalid.eventId="bad";invalid.duration=40*86400;local valid,validationReason=Activity:ValidateEvent(invalid);assert(not valid and validationReason=="INVALID_ONLINE_SESSION","malformed provider data is rejected")
local oversized=copy(oldEvent);oversized.eventId="oversized";oversized.metadata={value=string.rep("x",201)};local metadataValid,metadataReason=Activity:ValidateEvent(oversized);assert(not metadataValid and metadataReason=="METADATA_STRING","oversized provider metadata is rejected")
local domain=assert(HolyStorm.Sync.domains.guildActivity);local localMeta=domain.getMetadata("account-local");assert(localMeta.origin=="Player-Local"and localMeta.owner=="Player-Twink"and localMeta.version==shard.revision,"owner revisions preserve immutable origin provenance")
local remote=Activity:NewShard("account-remote","Player-Remote","realm:guild");remote.revision=1;remote.updatedAt=clock;remote.lastWriterCharacterUUID="Player-Remote";remote.ownerCharacterUUID="Player-Remote";local remoteMeta={objectId="account-remote",accountUUID="account-remote",owner="Player-Remote",origin="Player-Remote",version=1,updatedAt=clock,guildId="realm:guild",receivedFrom="Relay-Realm"};assert(domain.validate(remote,remoteMeta,"account-remote")and domain.authorize(remote,remoteMeta)and domain.import("account-remote",remote,remoteMeta));assert(HolyStorm.Data.GuildActivityStore:GetShard("account-remote").receivedFrom=="Relay-Realm");assert(not domain.import("account-remote",remote,remoteMeta),"stale synchronized shards are rejected")

assert(#HolyStorm.Sync.published<#HolyStorm.Events.emitted+20,"capture uses compact owner-shard synchronization rather than broadcasting every chat message")
local moduleMetadata;function HolyStorm:RegisterModule(metadata)moduleMetadata=metadata;return true end
assert(loadfile(feature.."GuildManagement.lua"))();local fields={};for _,field in ipairs(moduleMetadata.ruleFields or{})do fields[field.id]=field end;for _,id in ipairs({"activity.lastSeen","activity.daysSinceLastActivity","activity.onlineDuration7d","activity.guildChatCount7d","activity.raidParticipation30d","activity.mythicPlusParticipation30d","activity.eventAttendance30d"})do assert(fields[id],"missing module-owned Rule field "..id)end
local knownZero,zeroReason=fields['activity.raidParticipation30d'].resolver({accountUUID="account-remote"});assert(knownZero==0 and zeroReason==nil,"an available provider and known shard yield factual zero")
Activity:DisableProvider("raid");local unknown,unknownReason=fields['activity.raidParticipation30d'].resolver({accountUUID="account-remote"});assert(unknown==nil and unknownReason=="PROVIDER_UNAVAILABLE","an unavailable provider yields UNKNOWN");Activity:EnableProvider("raid")
local attendance,attendanceReason=fields['activity.eventAttendance30d'].resolver({accountUUID="account-remote"});assert(attendance==nil and attendanceReason=="PROVIDER_UNAVAILABLE","deferred Calendar attendance remains UNKNOWN")
local formerCan=HolyStorm.PermissionEngine.Can;function HolyStorm.PermissionEngine:Can()return false end;local denied,deniedReason=fields['activity.lastSeen'].resolver({accountUUID="account-local"});assert(denied==nil and deniedReason=="PERMISSION_DENIED","Rule fields enforce Activity view permission");HolyStorm.PermissionEngine.Can=formerCan
local serviceSource=assert(io.open(feature.."Services/GuildActivity.lua","rb"));local source=serviceSource:read("*a");serviceSource:close();assert(not source:lower():find("activity points",1,true)and not source:find("PromoteGuildMember",1,true)and not source:find("HS_Player_DB",1,true),"Activity remains factual and uses central persistence")
print("Guild Activity provider, identity, session, privacy, aggregation, compaction and sync tests passed")
