local root=(arg[0]:gsub("tools[/\\]test_positions.lua$","")).."LIVE/Holy_Storm/"
local featureRoot=(arg[0]:gsub("tools[/\\]test_positions.lua$","")).."LIVE/Holy_Storm_Positions/"
local function copy(value,seen)if type(value)~="table"then return value end;seen=seen or{};if seen[value]then return seen[value]end;local out={};seen[value]=out;for key,child in pairs(value)do out[copy(key,seen)]=copy(child,seen)end;return out end
local wall,mono=1000,100;local localGuid="Player-Local";local pos={map=84,x=.2,y=.3};local speed=0;local enabled=true;local permission=true;local guild={id="realm:guild",roster={[localGuid]={guid=localGuid,name="Local-Realm",online=true},["Player-Remote"]={guid="Player-Remote",name="Remote-Realm",online=true}}}
local locale=setmetatable({},{__index=function(_,key)return key end});local HolyStorm={db={profile={positions={}}},Utils={},Data={GuildStore={},PlayerStore={}},Policy={},Tasks={types={},queued={},pending={}},Sync={domains={},published={},discovered={}},Events={handlers={},emitted={}},Logger={rows={}},MapLinks={},POI={}}
function LibStub(name)if name=="AceAddon-3.0"then return{GetAddon=function()return HolyStorm end}elseif name=="AceLocale-3.0"then return{GetLocale=function()return locale end}end end
function HolyStorm.Utils.DeepCopy(v)return copy(v)end;function HolyStorm.Utils.ApplyDefaults(target,defaults)target=type(target)=="table"and target or{};for k,v in pairs(defaults)do if target[k]==nil then target[k]=copy(v)end end;return target end;function HolyStorm.Utils.Now()return wall end;function HolyStorm.Utils.TableCount(t)local n=0;for _ in pairs(t or{})do n=n+1 end;return n end
function HolyStorm.Data.GuildStore:GetCurrent()return guild end;function HolyStorm.Data.PlayerStore:GetCharacterOwner(guid)return"account-"..guid end
function HolyStorm.Policy:IsGuildModuleEnabled()return enabled end;function HolyStorm.Policy:Can()return permission end
function HolyStorm.Tasks:RegisterTaskType(id,d)self.types[id]=d end;function HolyStorm.Tasks:Queue(id,o)local key=id..":"..tostring(o and o.mergeKey or"");local status=self.pending[key]and"MERGED"or"QUEUED";self.pending[key]=true;self.queued[#self.queued+1]={id=id,options=o,status=status};return"task",status end;function HolyStorm.Tasks:ScheduleRecurring(id,interval,fn,o)self.recurring={id=id,interval=interval,fn=fn,options=o}end
function HolyStorm.Sync:RegisterDomain(id,d)self.domains[id]=d end;function HolyStorm.Sync:Publish(domain,id,reason)self.published[#self.published+1]={domain=domain,id=id,reason=reason};return true end;function HolyStorm.Sync:Discover(domain,since,o)self.discovered[#self.discovered+1]={domain=domain,since=since,options=o};return true end
function HolyStorm.Events:Register(event,owner,fn)self.handlers[event..":"..owner]=fn end;function HolyStorm.Events:Emit(event,...)self.emitted[#self.emitted+1]={event=event,args={...}}end
function HolyStorm.Logger:Write(level,module,category,message,context)self.rows[#self.rows+1]={level=level,module=module,category=category,message=message,context=context}end
function HolyStorm.MapLinks:GetPlayerPosition()return pos.map,pos.x,pos.y end;function HolyStorm.MapLinks:IsValidCoordinate(map,x,y)return tonumber(map)and map>0 and tonumber(x)and x>=0 and x<=1 and tonumber(y)and y>=0 and y<=1 end
function HolyStorm.POI:IsMapValid(map)return tonumber(map)and map>0 end
function UnitGUID()return localGuid end;function IsInGuild()return guild~=nil end;function GetTime()return mono end;function GetUnitSpeed()return speed end

assert(loadfile(featureRoot.."GuildPositions.lua"))();local P=HolyStorm.GuildPositions;P:Initialize();local domain=HolyStorm.Sync.domains["guild-position"]
assert(P:GetSettings().share==false and not P:CanShare(),"position sharing must default to privacy opt-out");assert(not P:SampleMovement("PRIVACY_OFF",true)and#HolyStorm.Sync.published==0,"privacy off captured or published a position")
P:SetSetting("share",true);P.captureForce,P.captureReason=true,"TEST_INITIAL";assert(P:RunCapture());assert(P.pendingSnapshot and P.pendingSnapshot.characterUUID==localGuid);local keys=0;for _ in pairs(P.pendingSnapshot)do keys=keys+1 end;assert(keys==7 and P.pendingSnapshot.name==nil and P.pendingSnapshot.class==nil,"position payload is not compact");assert(P:RunPublish()and HolyStorm.Sync.published[#HolyStorm.Sync.published].domain=="guild-position","privacy-on initial state was not published")
P.movement.active=false;local queued=#HolyStorm.Tasks.queued;mono=mono+600;assert(not P:SampleMovement("STATIONARY",false)and#HolyStorm.Tasks.queued==queued,"stationary player generated a network update")
P.movement.active=true;speed=2;pos.x=.21;mono=mono+8;assert(P:SampleMovement("SLOW",false)and P.movement.bucket=="slow"and P.movement.nextEligible==mono+8,"slow movement policy is incorrect");pos.x=.22;mono=mono+1;assert(not P:SampleMovement("TOO_SOON",false),"minimum slow interval was ignored");speed=14;mono=mono+7;assert(P:SampleMovement("FAST",false)and P.movement.bucket=="fast"and P.movement.nextEligible==mono+3,"fast movement policy is incorrect");assert(P.metrics.coalesced>=1,"pending position updates were not coalesced")
local remote={characterUUID="Player-Remote",guildId=guild.id,mapID=84,x=.4,y=.5,timestamp=wall,sequence=1};local meta={owner="Player-Remote",version=1,updatedAt=wall};assert(domain.validate(remote,meta,remote.characterUUID),"valid online guild position rejected");assert(domain.authorize(remote,meta,"Player-Remote",nil,remote.characterUUID),"direct owner authority rejected");assert(domain.import(remote.characterUUID,remote,meta,"Player-Remote","Remote-Realm")and P:Get(remote.characterUUID),"remote position not imported/renderable")
local bloated=copy(remote);bloated.name="leak";assert(not domain.validate(bloated,meta,bloated.characterUUID),"non-compact character details were accepted");local invalid=copy(remote);invalid.x=2;assert(not domain.validate(invalid,meta,invalid.characterUUID),"invalid coordinates were accepted")
guild.roster["Player-Remote"].online=false;P:ReconcileRoster();assert(not P.remote["Player-Remote"],"offline roster member marker was not removed immediately");guild.roster["Player-Remote"].online=true;domain.import(remote.characterUUID,remote,meta,"Player-Remote","Remote-Realm");wall=wall+91;P:ReconcileRoster();assert(not P.remote["Player-Remote"]and P.metrics.droppedStale>0,"stale remote position was not removed")
wall=wall+1;remote.timestamp=wall;remote.sequence=2;domain.import(remote.characterUUID,remote,{owner="Player-Remote",version=2,updatedAt=wall},"Player-Remote","Remote-Realm");guild={id="realm:other",roster={[localGuid]={online=true}}};P:ReconcileRoster();assert(next(P.remote)==nil and P.currentGuildId=="realm:other","guild switch leaked old positions")
P:SetSetting("worldMapEnabled",false);P:SetSetting("minimapEnabled",true);P:SetSetting("worldMapSize",40);P:SetSetting("minimapSize",15);P:SetSetting("currentMapOnly",true);assert(not P:GetSettings().worldMapEnabled and P:GetSettings().minimapEnabled and P:GetSettings().worldMapSize==40 and P:GetSettings().minimapSize==15 and P:GetSettings().currentMapOnly,"display settings are not independent")
enabled=false;assert(not P:CanShare()and not P:CanDisplay(),"guild module disable did not stop sharing/display");P:SetSetting("share",false);local published=#HolyStorm.Sync.published;P:RunPublish();assert(#HolyStorm.Sync.published==published,"opt-out allowed a queued position send")
print("Guild-position privacy, movement, coalescing, validation, roster and stale tests passed")
