local repository=(arg[0]:gsub("tools[/\\]test_character_tabs.lua$",""))
local coreRoot=repository.."LIVE/Holy_Storm/";local uiRoot=repository.."LIVE/Holy_Storm_UI/";local charactersRoot=repository.."LIVE/Holy_Storm_Characters/"
local unpack=unpack or table.unpack
local function copy(value,seen)if type(value)~="table"then return value end;seen=seen or{};if seen[value]then return seen[value]end;local out={};seen[value]=out;for key,child in pairs(value)do out[copy(key,seen)]=copy(child,seen)end;return out end
local locale=setmetatable({LEVEL="Level",SEASON="Season %s",SEASON_SUMMARY="Season %s / Rating %s",CHARACTER_COUNT="%d known characters",LAST_UPDATED="Last updated: %s",ACTIVITY="Activity %s",ACTIVITY_DETAILS="Threshold %s / Level %s",WEEKLY_TOOLTIP="Weekly %s",BOSS_KILLED="Killed %s",BOSS_OPEN="Open %s",BEST_ROW="%s | %s | %d kills",ITEM_LEVEL="Item level",EMPTY_SLOT="Empty",EMPTY_SOCKET="Empty socket",GEM_ID="Gem %s",TELEPORT_COOLDOWN="Cooldown %s",TELEPORT_READY="Ready",TELEPORT_UNAVAILABLE="Unavailable"},{__index=function(_,key)return key end})
local records={A={guid="A",name="Alpha-Realm",realm="Realm",classFile="PALADIN",level=80,faction="Alliance",guildRank="Stored Officer",stats={spec={id=70,name="Retribution",icon=98765,index=3,role="DAMAGER"}}}}
local blocks,eventListeners,errorLogs={},{},{}
local HolyStorm={Utils={DeepCopy=copy,TableCount=function(t)local n=0;for _ in pairs(t or{})do n=n+1 end;return n end,SafeCall=function(_,fn,...)local result={pcall(fn,...)};local ok=table.remove(result,1);return ok,unpack(result)end},Data={CharacterStore={},GuildStore={},PlayerStore={}},PlayerData={},Policy={},Tasks={},Events={},Logger={},UI={}}
local aceGUI
function LibStub(name,silent)if name=="AceAddon-3.0"then return{GetAddon=function()return HolyStorm end}elseif name=="AceLocale-3.0"then return{GetLocale=function()return locale end}elseif name=="AceGUI-3.0"then return aceGUI elseif not silent then error("unknown library "..tostring(name))end end
function HolyStorm:RegisterRequiredModule()local module={};self.characterOverview=module;return module end
function HolyStorm:RegisterCapability(_,capability,handler)self.capabilities=self.capabilities or{};self.capabilities[capability]=handler;return true end
function HolyStorm:RegisterCharacterTab(_,definition)return self.CharacterUI:RegisterTab(definition)end
function HolyStorm:RegisterCharacterSummarySection(_,definition)return self.CharacterUI:RegisterSummarySection(definition)end
function HolyStorm:RegisterUIExtension(_,definition)self.uiExtension=definition;return true end
function HolyStorm:CallCapability()return true end;function HolyStorm:ApplyModuleMetadata()end;function HolyStorm:IsOptionalModuleEnabled()return true end
function HolyStorm:GetModule()return{frame=self.testUIFrame,content=self.testUIContent}end
function HolyStorm.Tasks:RegisterTaskType()end;function HolyStorm.Tasks:GetTaskType()return nil end
function HolyStorm.Events:Register(event,_,callback)eventListeners[event]=callback end;function HolyStorm.Events:Emit()end;function HolyStorm.Events:UnregisterOwner()end
function HolyStorm.Logger:Write(level,source,category,message,context)errorLogs[#errorLogs+1]={level=level,source=source,category=category,message=message,context=context}end
function HolyStorm.Policy:Can()return true end;function HolyStorm.Policy:IsGuildModuleEnabled()return true end
function HolyStorm.Data.CharacterStore:Get(guid)return records[guid]end
function HolyStorm.Data.CharacterStore:CaptureCurrent()return records.A end
function HolyStorm.Data.CharacterStore:GetBlock(_,block)local data=blocks[block];if block=="equipment"then return data and{equipment=data,itemLevel=data.itemLevel},{version=4,updatedAt=100}end;return data,{version=3,updatedAt=100}end
function HolyStorm.Data.GuildStore:GetCurrent()return{roster={A={name="Alpha",classFile="PALADIN",level=80}}}end
function HolyStorm.Data.PlayerStore:GetCharacterOwner()return"account-A"end;function HolyStorm.PlayerData:IsStale()return false end
HolyStorm.TwinkCore={sources={OWNER="OWNER"},GetAccountUUIDForCharacter=function()return"account-A"end,GetAccount=function()return{characters={A=true,B=true}}end,GetAccountMain=function()return"A"end,GetGuildMain=function()return"B",true end,GetVisibleCharactersForViewer=function()return{{characterUUID="A",fullName="Alpha-Realm",classFile="PALADIN",level=80,relationship={source="OWNER"}},{characterUUID="B",fullName="Beta-Realm",classFile="MAGE",level=70,relationship={source="ADMIN"}}}end}
LOCALIZED_CLASS_NAMES_MALE={PALADIN="Paladin"};RAID_CLASS_COLORS={PALADIN={r=1,g=.96,b=.41}};NORMAL_FONT_COLOR={r=1,g=1,b=1};CLASS_ICON_TCOORDS={PALADIN={0,.25,0,.25}}
for index,name in ipairs({"HEAD","NECK","SHOULDER","BACK","CHEST","WRIST","HAND","WAIST","LEGS","FEET","FINGER1","FINGER2","TRINKET1","TRINKET2","MAINHAND","OFFHAND"})do _G["INVSLOT_"..name]=index end

local function widget(kind,parent)
 local object={kind=kind,parent=parent,width=640,height=360,shown=true,enabled=true,textValue="",points={}}
 function object:SetAllPoints(target)self.allPoints=target or self.parent end;function object:SetParent(value)self.parent=value end
 function object:SetPoint(...)self.points[#self.points+1]={...}end;function object:ClearAllPoints()self.points={}end
 function object:SetSize(width,height)self.width,self.height=width,height;if self.OnSizeChanged then self.OnSizeChanged(self,width,height)end end;function object:SetWidth(width)self.width=width end;function object:GetWidth()return self.width end;function object:SetHeight(height)self.height=height end;function object:GetHeight()return self.height end
 function object:SetScrollChild(child)self.scrollChild=child end;function object:SetScript(event,handler)self[event]=handler end;function object:HookScript(event,handler)self[event]=handler end
 function object:CreateFontString()return widget("font",self)end;function object:CreateTexture()return widget("texture",self)end
 function object:SetText(text)self.textValue=text or""end;function object:GetStringHeight()return 16 end;function object:GetUnboundedStringWidth()return#self.textValue*7 end;function object:GetStringWidth()return#self.textValue*7 end
 function object:SetFontObject()end;function object:SetTextColor()end;function object:SetJustifyH()end;function object:SetJustifyV()end;function object:SetWordWrap()end;function object:SetNonSpaceWrap()end;function object:SetHyperlinksEnabled()end
 function object:SetColorTexture(...)self.color={...}end;function object:SetTexture(value)self.texture=value end;function object:SetTexCoord(...)self.texCoord={...}end;function object:SetAlpha(value)self.alpha=value end;function object:SetNormalTexture()end;function object:SetHighlightTexture()end;function object:RegisterForClicks(...)self.clicks={...}end;function object:EnableMouse()end;function object:SetEnabled(value)self.enabled=value~=false end
 function object:SetShown(value)self.shown=value==true end;function object:IsShown()return self.shown end;function object:Show()self.shown=true end;function object:Hide()self.shown=false end
 return object
end
CreateFrame=function(_,_,parent)return widget("frame",parent)end
local function createTabGroup()
 local group={frame=widget("tabgroup-frame"),content=widget("tabgroup-content"),tabButtons={},tabs={},callbacks={}}
 function group:SetCallback(event,handler)self.callbacks[event]=handler end;function group:GetContentFrame()return self.content end
 function group:LayoutTabs()self.content:SetSize(math.max(1,self.frame.width),math.max(1,self.frame.height-36))end
 function group:SetTabs(tabs)self.tabs=tabs or{};for _,tab in ipairs(self.tabs)do local button=self.tabButtons[tab.value]or widget("tab-button");button.value=tab.value;button.icon=button.icon or widget("texture",button);button.icon:SetTexture(tab.icon);button:SetSize(100,30);button:RegisterForClicks("LeftButtonUp");self.tabButtons[tab.value]=button end;self:LayoutTabs()end
 function group:SelectTab(value,silent)self.selected=value;if not silent and self.callbacks.OnGroupSelected then self.callbacks.OnGroupSelected(self,"OnGroupSelected",value)end end
 return group
end
aceGUI={Create=function(_,kind)assert(kind=="HolyStormTabGroup");return createTabGroup()end}
HolyStorm.testUIFrame=widget("main-frame");HolyStorm.testUIContent=widget("ui-content",HolyStorm.testUIFrame)
HolyStorm.UI.frame=HolyStorm.testUIFrame;HolyStorm.UI.content=HolyStorm.testUIContent;HolyStorm.UI.registered={};HolyStorm.UI.visible="character"
function HolyStorm.UI:RegisterView(definition)self.registered[definition.id]=definition;return true end;function HolyStorm.UI:ShowView(id)self.visible=id;return true end;function HolyStorm.UI:GetVisiblePage()return self.visible end;function HolyStorm.UI:ShowPage(id)self.visible=id end
HolyStorm.Database={Get=function()return false end};C_Timer={After=function(_,callback)callback()end};date=function(format,timestamp)return format.."|"..tostring(timestamp)end;UnitGUID=function()return"A"end
GameTooltip={lines={}};function GameTooltip:SetOwner(owner)self.owner=owner end;function GameTooltip:SetText(value)self.text=value;self.lines={}end;function GameTooltip:AddLine(value)table.insert(self.lines,value)end;function GameTooltip:SetHyperlink(value)self.hyperlink=value end;function GameTooltip:Show()self.shown=true end;function GameTooltip:Hide()self.shown=false end

assert(loadfile(uiRoot.."UI/Framework/Layout.lua"))();assert(loadfile(uiRoot.."UI/Framework/Components.lua"))();assert(loadfile(uiRoot.."UI/Framework/Table.lua"))();assert(loadfile(uiRoot.."UI/Framework/Components/HolyStormHeaderBar.lua"))();HolyStorm.UI.Components=HolyStorm.UIComponents
assert(loadfile(charactersRoot.."UI/CharacterUI.lua"))();assert(loadfile(repository.."LIVE/Holy_Storm_Equipment/UI/CharacterTab.lua"))();assert(loadfile(repository.."LIVE/Holy_Storm_MythicPlus/UI/CharacterTab.lua"))();assert(loadfile(repository.."LIVE/Holy_Storm_Raids/UI/CharacterTab.lua"))();assert(loadfile(repository.."LIVE/Holy_Storm_Delves/UI/CharacterTab.lua"))();assert(loadfile(charactersRoot.."UI/CharacterOverview.lua"))()
local C=HolyStorm.CharacterUI;local context=C:ResolveContext("A")
local function render(id,width)local definition=assert(C:GetTab(id));local parent=widget("parent");parent:SetSize(width or 900,500);local view=definition.build(parent);view.frame:SetSize(width or 900,500);view.layout:Relayout();definition.refresh(view,context,definition);return view,definition end
local function find(rows,predicate)for _,row in ipairs(rows)do if predicate(row)then return row end end end

assert(C:FormatState(0)=="0"and C:FormatState(nil):find("–",1,true)and C:FormatState(nil):find("888888",1,true),"central state formatter separates zero and gray unknown")
assert(HolyStorm.UI.Components:FormatDelta(4):find("20ff20",1,true)and HolyStorm.UI.Components:FormatDelta(-4):find("ff4040",1,true)and HolyStorm.UI.Components:FormatDelta(0)=="0","central delta colors and zero")

local slots={};slots[1]={itemId=111,link="|cffa335ee|Hitem:111::::::::80:70::1:2:999:888::::::|h[An Extremely Long Test Helm Name]|h|r",itemLevel=710,enchantId=42,enchantName="Radiant Enchant",gems={{itemId=1001,name="Ruby",icon=9001}},sockets=1,icon=123,isTier=true};slots[2]=false;slots[4]={itemId=222,link="|cff0070dd|Hitem:222::::::::80:70:::::::|h[Plain Bracers]|h|r",itemLevel=0,enchantId=0,gems={},sockets=0,icon=124,isTier=false};slots[5]={itemId=223,link="|cff0070dd|Hitem:223::::::::80:70:::::::|h[Socket Belt]|h|r",itemLevel=700,enchantId=nil,gems={{empty=true,name="Prismatic Socket"}},sockets=1,icon=125};slots[6]={itemId=224,link="|cff0070dd|Hitem:224::::::::80:70:::::::|h[Unknown Gems]|h|r",itemLevel=700,enchantId=nil,gems={},sockets=1,icon=126}
blocks.equipment={snapshotVersion=4,itemLevel=705.5,slots=slots};local equipment=render("equipment");assert(#equipment.table.rows==16,"equipment retains one row per slot")
assert(equipment.table.rows[1].state=="VALUE"and equipment.table.rows[1].tier=="✓"and equipment.table.rows[1].enchant=="✓"and equipment.table.rows[1].gems:find("9001",1,true),"equipped tier, enchant and gem state")
assert(equipment.table.rows[2].state=="EMPTY"and equipment.table.rows[2].itemText==nil and equipment.table.rowFrames[2].cells[2].text.textValue=="Empty","confirmed empty slot is not unknown")
assert(equipment.table.rows[3].state=="UNKNOWN"and equipment.table.rowFrames[3].cells[2].text.textValue:find("–",1,true),"unknown slot uses gray dash")
assert(equipment.table.rows[4].itemLevel=="0"and equipment.table.rows[4].enchant=="○"and equipment.table.rows[4].gems=="","known zero and known empty equipment fields")
assert(equipment.table.rows[5].gemDetails[1]=="Prismatic Socket"and equipment.table.rows[6].gems:find("–",1,true),"empty and unknown sockets remain distinct")
local itemCell=equipment.table.rowFrames[1].cells[2];itemCell.frame.width=105;equipment.table:FitCell(itemCell,equipment.table.columns[2]);assert(itemCell.text.textValue:find("...",1,true)and itemCell.text.textValue:find("Hitem:111::::::::80:70::1:2:999:888",1,true),"truncation preserves the complete item hyperlink payload")
itemCell.frame.OnEnter(itemCell.frame);assert(GameTooltip.hyperlink==slots[1].link,"item hover uses SetHyperlink with original payload");local clicked;HandleModifiedItemClick=function(link)clicked=link end;itemCell.frame.OnClick(itemCell.frame,"LeftButton");assert(clicked==slots[1].link,"item cell keeps native click behavior")
local equipmentRowFrame=equipment.table.rowFrames[1];blocks.equipment.itemLevel=706;C:GetTab("equipment").refresh(equipment,context,C:GetTab("equipment"));assert(equipment.table.rowFrames[1]==equipmentRowFrame,"equipment table reuses row frames")

local spellState={[902]={known=true,remaining=0},[903]={known=true,remaining=120}};GetTime=function()return 1000 end;C_Spell={IsSpellKnown=function(id)return spellState[id]and spellState[id].known end,GetSpellCooldown=function(id)local remaining=spellState[id]and spellState[id].remaining or 0;return{startTime=1000,duration=remaining}end,CastSpell=function(id)clicked="spell:"..id end};C_ChallengeMode={GetDungeonScoreRarityColor=function()return{r=.5,g=.25,b=1}end};SecondsToClock=function(value)return math.ceil(value).."s"end
blocks.mythicPlus={snapshotVersion=3,seasonId=16,overallScore=2500,scoreDataReady=true,dungeons={{name="A Dungeon",instanceId=200,texture=400,score=250,affixScores={{affixID=9,level=12,overTime=false},{affixIDs={10},level=10,overTime=true}}},{name="B Dungeon",instanceId=201,texture=401,score=0,teleportSpellId=902,affixScores={}},{name="C Dungeon",instanceId=202,texture=402,score=nil,teleportSpellId=903,affixScores={}}}}
local mythic=render("mythicPlus");local dungeonA=find(mythic.table.rows,function(row)return row.name=="A Dungeon"end);local dungeonB=find(mythic.table.rows,function(row)return row.name=="B Dungeon"end);local dungeonC=find(mythic.table.rows,function(row)return row.name=="C Dungeon"end)
assert(dungeonA.tyrannical:find("20ff20",1,true)and dungeonA.fortified:find("ff4040",1,true),"in-time and over-time affix bests have correct colors");assert(dungeonB.tyrannical==""and dungeonB.rating:find("0",1,true)and dungeonC.rating:find("–",1,true),"empty best, rating zero and unknown rating")
assert(dungeonA.teleport.state=="UNAVAILABLE"and dungeonB.teleport.state=="READY"and dungeonC.teleport.state=="COOLDOWN","all teleport states")
local rowB;for index,row in ipairs(mythic.table.rows)do if row==dungeonB then rowB=mythic.table.rowFrames[index]end end;rowB.cells[1].teleportButton.OnClick();assert(clicked=="spell:902","ready teleport casts stored spell");local rowC;for index,row in ipairs(mythic.table.rows)do if row==dungeonC then rowC=mythic.table.rowFrames[index]end end;rowC.cells[1].teleportButton.OnEnter(rowC.cells[1].teleportButton);assert(GameTooltip.lines[1]:find("120s",1,true),"cooldown tooltip formats remaining time")
local openedJournal;EncounterJournal_OpenJournal=function(_,id)openedJournal=id end;rowB.cells[1].frame.OnClick(rowB.cells[1].frame,"LeftButton");assert(openedJournal==201,"dungeon name opens the Encounter Journal")

blocks.raid={snapshotVersion=3,catalogReady=true,raids={{id=100,name="Raid One",icon=500,order=1,bosses={{id=501,name="Boss A"},{id=502,name="Boss B"}}}},lockouts={{name="Raid One",journalInstanceId=100,difficultyId=17,killed=1,total=2,bosses={{name="Boss A",killed=true},{name="Boss B",killed=false}}},{name="Raid One",journalInstanceId=100,difficultyId=16,killed=1,total=2,bosses={{name="Boss A",killed=true},{name="Boss B",killed=false}}}},lifetime={bosses={[501]={id=501,name="Boss A",raidName="Raid One",difficulties={LFR={kills=5},NORMAL={kills=2},HEROIC={kills=7},MYTHIC={kills=1}}},[502]={id=502,name="Boss B",raidName="Raid One",difficulties={LFR={kills=5},NORMAL={kills=2}}}}}}
local raid=render("raid");local raidRow=raid.table.rows[1];assert(raidRow.lfr:find("ffffd100",1,true)and raidRow.normal:find("ff33ff33",1,true)and raidRow.heroic:find("ff408cff",1,true)and raidRow.mythic:find("ffb34dff",1,true),"addon-wide raid difficulty colors");assert(raidRow.lfr:find("1/2",1,true)and raidRow.normal:find("0/2",1,true),"weekly lockout and confirmed zero progress")
assert(C:BuildRaidBestRows(blocks.raid)[1].difficulty=="MYTHIC"and raidRow.best:find("M 1/2",1,true),"best progress keeps only the highest difficulty per boss")
local bestColumn=raid.table.columns[#raid.table.columns];bestColumn.tooltip(raidRow,bestColumn,raid.table,GameTooltip);assert(#GameTooltip.lines==2 and GameTooltip.lines[1]:find("Boss A",1,true)and GameTooltip.lines[1]:find("1 kills",1,true),"best tooltip contains one highest-difficulty row per boss with lifetime kills")
blocks.raid={snapshotVersion=3,catalogReady=false,raids={{id=100,name="Raid One",bosses={{name="Boss A"}}}},lockouts={},lifetime={bosses={}}};local unknownRaid=render("raid");assert(unknownRaid.table.rows[1].lfr:find("888888",1,true),"unreliable weekly raid state is gray unknown")

blocks.delves={seasonNumber=3,weeklyProgress=0,bountiful={status="unknown"},keyFragments={count=4},completedKeys=0,companion={level=12},activities={{index=1,progress=2,threshold=4,level=8}}};local delves=render("delves");assert(delves.table.rows[1].value=="0"and delves.table.rows[2].value:find("–",1,true)and find(delves.table.rows,function(row)return row.value=="4"end),"delve zero, unknown and structured values")

blocks.stats={primary={strength={base=100,effective=120},agility={base=20,effective=15},stamina={base=nil,effective=nil},intellect={base=10,effective=10}},armor={base=500,effective=600},secondary={criticalStrike={rating=0,percent=0},haste={rating=800,percent=15}}};local stats=render("stats");local strength=find(stats.table.rows,function(row)return row.stat=="STAT_STRENGTH"end);local agility=find(stats.table.rows,function(row)return row.stat=="STAT_AGILITY"end);local stamina=find(stats.table.rows,function(row)return row.stat=="STAT_STAMINA"end);local intellect=find(stats.table.rows,function(row)return row.stat=="STAT_INTELLECT"end);assert(strength.additional:find("+20",1,true)and agility.additional:find("-5",1,true)and intellect.additional=="0"and stamina.total:find("–",1,true),"stats positive, negative, zero and unknown Additional semantics");local critical=find(stats.table.rows,function(row)return row.stat=="STAT_CRITICALSTRIKE"end);assert(critical.total:find("0",1,true),"known secondary zero is retained")

local summary=render("summary");assert(find(summary.table.rows,function(row)return row.label=="SUMMARY_IDENTITY"and row.value=="Alpha-Realm"end)and find(summary.table.rows,function(row)return row.label=="DISPLAY_NAME"and row.tabId=="equipment"end),"summary combines compact identity and registered feature adapters")
local twinks=render("twinks");assert(#twinks.table.rows==2 and twinks.table.rows[2].name:find("SHADOW_MAIN",1,true),"additional Twinks tab uses the central table")
blocks.mythicPlus=nil;local missing=render("mythicPlus");assert(#missing.table.rows==0 and missing.table.empty.textValue=="NO_MYTHICPLUS","missing optional snapshot is a localized empty state")

local Page=HolyStorm.characterOverview;Page:OnInitialize();assert(HolyStorm.uiExtension and HolyStorm.uiExtension.initialize);HolyStorm.uiExtension.initialize();assert(HolyStorm.UI.registered.character and Page.header and Page.tabGroup and Page.tabHost,"Character Overview registers one declarative view with central header and TabGroup")
C:SetContext("A",false);C:SelectTab("stats");assert(Page.views.stats and Page.views.stats.table and#Page.views.stats.table.rows==9,"tab switching builds the central stats table");local statsFrame=Page.views.stats.frame;C:SelectTab("summary");assert(not statsFrame.shown and Page.views.summary.frame.shown,"tab switching reuses views and hides inactive content")
Page.page:SetSize(920,540);Page:LayoutTabs();assert(Page.tabHost.width>800 and Page.views.summary.frame.parent==Page.tabHost and Page.views.summary.table.columnWidths[2]>0,"resize relayout keeps flexible columns in the central content host")
local original=C:GetTab("summary").refresh;C:GetTab("summary").refresh=function()error("forced renderer failure")end;assert(not C:RefreshTab("summary")and errorLogs[#errorLogs].context.tabId=="summary","one failed adapter is isolated and logged");C:GetTab("summary").refresh=original;assert(C:RefreshTab("summary"),"a tab recovers after a failed refresh")

local achievements=assert(io.open(repository.."LIVE/Holy_Storm_Achievements/Achievements.lua","rb"));local achievementSource=achievements:read("*a");achievements:close();assert(achievementSource:find("CreateTableView",1,true)and not achievementSource:find("CreateTextView",1,true)and not achievementSource:find("CharacterUI:SetView",1,true),"Achievements character tab no longer activates a legacy renderer")
for _,path in ipairs({charactersRoot.."UI/CharacterOverview.lua",charactersRoot.."UI/CharacterUI.lua",repository.."LIVE/Holy_Storm_Equipment/UI/CharacterTab.lua",repository.."LIVE/Holy_Storm_MythicPlus/UI/CharacterTab.lua",repository.."LIVE/Holy_Storm_Raids/UI/CharacterTab.lua",repository.."LIVE/Holy_Storm_Delves/UI/CharacterTab.lua"})do local file=assert(io.open(path,"rb"));local source=file:read("*a");file:close();assert(not source:find("CreateTextView",1,true)and not source:find("CharacterUI:SetView",1,true),"no migrated file retains the legacy renderer: "..path)end
print("Declarative Character Overview, adapters, states, interactions, resize and reuse tests passed")
