local root=(arg[0]:gsub("tools[/\\]test_poi.lua$","")).."LIVE/Holy_Storm/"
local function copy(value,seen)if type(value)~="table"then return value end;seen=seen or{};if seen[value]then return seen[value]end;local out={};seen[value]=out;for key,child in pairs(value)do out[copy(key,seen)]=copy(child,seen)end;return out end
local clock=1000;local currentGuid="Player-A";local currentGuild={id="realm:guild"};local moduleEnabled=true;local permissions={};local groupMode=nil
local locale=setmetatable({TASK_POI_EXPIRE="Expire POIs",TASK_POI_MAP_REFRESH="Refresh POIs",POI_LINK_LABEL="POI: %s"},{__index=function(_,key)return key end})
local HolyStorm={db={global={installId="poi-test",poi={personal={},guilds={},sessions={},schemaVersion=1}},profile={poi={}}},Data={GuildStore={},PlayerStore={},POIStore=nil},Utils={},Policy={},Tasks={registered={},queued={}},Sync={domains={},published={},requested={},discovered={}},Events={handlers={},emitted={}},TwinkCore={},Logger={rows={}},Rules={fields={}},RichLinks={},capabilities={}}
function LibStub(name)if name=="AceAddon-3.0"then return{GetAddon=function()return HolyStorm end}elseif name=="AceLocale-3.0"then return{GetLocale=function()return locale end}end end
function HolyStorm.Utils.DeepCopy(value)return copy(value)end;function HolyStorm.Utils.Now()return clock end;function HolyStorm.Utils.Trim(value)return tostring(value):match("^%s*(.-)%s*$")end;function HolyStorm.Utils.TableCount(value)local n=0;for _ in pairs(value or{})do n=n+1 end;return n end;function HolyStorm.Utils.ApplyDefaults(target,defaults)target=type(target)=="table"and target or{};for key,value in pairs(defaults)do if target[key]==nil then target[key]=copy(value)end end;return target end;function HolyStorm.Utils.SafeCall(_,fn,...)local results={pcall(fn,...)};local ok=table.remove(results,1);return ok,(table.unpack or unpack)(results)end
function HolyStorm.Data.GuildStore:GetCurrent()return currentGuild end;function HolyStorm.Data.PlayerStore:GetCharacterOwner(guid)return"account-"..tostring(guid)end;function HolyStorm.TwinkCore:GetAccountUUIDForCharacter(guid)return"account-"..tostring(guid)end
function HolyStorm.Policy:IsGuildModuleEnabled()return moduleEnabled end;function HolyStorm.Policy:Can(id)return permissions[id]~=false end
function HolyStorm.Tasks:RegisterTaskType(id,definition)self.registered[id]=definition end;function HolyStorm.Tasks:Queue(id,options)self.queued[#self.queued+1]={id=id,options=options};return true end;function HolyStorm.Tasks:Enqueue(_,fn)fn();return true end
function HolyStorm.Sync:RegisterDomain(id,definition)self.domains[id]=definition end;function HolyStorm.Sync:Publish(domain,id,reason)self.published[#self.published+1]={domain=domain,id=id,reason=reason};return true end;function HolyStorm.Sync:RequestObject(domain,id,options)self.requested[#self.requested+1]={domain=domain,id=id,options=options};return true end;function HolyStorm.Sync:Discover(domain,since,options)self.discovered[#self.discovered+1]={domain=domain,since=since,options=options};return true end
function HolyStorm.Events:Register(event,owner,handler)self.handlers[event..":"..owner]=handler end;function HolyStorm.Events:Emit(event,...)self.emitted[#self.emitted+1]={event=event,args={...}}end
function HolyStorm.Logger:Write(level,module,category,message,context)self.rows[#self.rows+1]={level=level,module=module,category=category,message=message,context=context}end
function HolyStorm.Rules:RegisterField(id,definition)self.fields[id]=definition;return true end
function HolyStorm.RichLinks:InsertChatLink(kind,id,label)self.last={kind=kind,id=id,label=label};return true end
function HolyStorm:RegisterCapability(id,fn)self.capabilities[id]=fn end;function HolyStorm:CallCapability(id,...)self.called={id=id,args={...}};return true end
function UnitGUID(unit)if unit=="party1"or unit=="raid1"then return"Leader-B"end;return currentGuid end;function GetUnitName()return"Alpha-Realm"end;function UnitExists(unit)return unit=="party1"or unit=="raid1"end;function UnitIsGroupLeader(unit)return unit=="party1"or unit=="raid1"end
function IsInRaid()return groupMode=="RAID"end;function IsInGroup()return groupMode=="GROUP"or groupMode=="RAID"end;function GetNumGroupMembers()return groupMode=="RAID"and 1 or 0 end;function GetNumSubgroupMembers()return groupMode=="GROUP"and 1 or 0 end;function GetInstanceInfo()return nil,nil,nil,nil,nil,nil,nil,777,"Normal",0,20 end
C_Map={GetMapInfo=function(id)return tonumber(id)and tonumber(id)>0 and{id=id}or nil end,GetBestMapForUnit=function()return 84 end,GetPlayerMapPosition=function()return{GetXY=function()return.5,.6 end}end};UiMapPoint={CreateFromCoordinates=function(map,x,y)return{mapID=map,x=x,y=y}end};function OpenWorldMap(map)HolyStorm.openedMap=map end

assert(loadfile(root.."Data/POIStore.lua"))();assert(loadfile(root.."Core/MapLinks.lua"))();assert(loadfile(root.."Core/POI.lua"))();HolyStorm.POI:Initialize();local POI=HolyStorm.POI;local domain=HolyStorm.Sync.domains.poi
local function draft(target,name)return{target=target or"PERSONAL",mapID=84,x=.25,y=.75,name=name or"Test POI",description="Rich [[coordinate:84,0.2,0.3|route]]",category="note",customCategory="",icon="marker",color={r=.2,g=.4,b=.6,a=1},status="ACTIVE"}end

local ok,personal=POI:Save(draft("PERSONAL","Personal"),0);assert(ok and personal.revision==1 and#HolyStorm.Sync.published==0,"personal POI persists without synchronization");local stable=personal.poiID;personal.name="Renamed";ok,personal=POI:Save(personal,1);assert(ok and personal.poiID==stable and personal.revision==2,"stable ID survives edits");assert(not POI:Save(personal,1),"stale editor revision is rejected")
permissions["poi-create-guild"]=false;assert(not POI:Save(draft("GUILD","Denied"),0),"core enforces create permission");permissions["poi-create-guild"]=nil;local guild;ok,guild=POI:Save(draft("GUILD","Guild"),0);assert(ok and guild.guildId=="realm:guild"and HolyStorm.Sync.published[#HolyStorm.Sync.published].id==guild.poiID,"guild POI is isolated and published")
currentGuid="Player-B";permissions["poi-edit-any"]=false;assert(not POI:Save(guild,guild.revision),"editing another creator requires edit-any authority");permissions["poi-edit-any"]=nil;currentGuid="Player-A"
POI:SetHidden(guild.poiID,true);assert(not POI:CanView(guild)and POI:CanView(guild,true),"local hiding is separate from shared data");local newer=copy(guild);newer.revision=2;newer.updatedAt=clock+1;newer.name="Remote update";assert(domain.import(guild.poiID,newer,{owner=newer.modifiedBy},nil,"Remote"));assert(POI:GetSettings().hidden[guild.poiID]and POI:Get(guild.poiID).name=="Remote update","sync update preserves local hide state");assert(not domain.import(guild.poiID,guild,{owner=guild.modifiedBy},nil,"Remote"),"older sync revision cannot overwrite")
assert(domain.getChannel({target="GUILD"})=="GUILD"and domain.getChannel({target="GROUP"})=="PARTY"and domain.getChannel({target="RAID"})=="RAID","sync channels follow target scope")
groupMode="GROUP";POI:HandleGroupContext();local group;ok,group=POI:Save(draft("GROUP","Group"),0);assert(ok and group.sessionId:match("^group%-"),"group POI receives a session ID");local groupSession=group.sessionId;groupMode=nil;POI:HandleGroupContext();assert(not POI:Get(group.poiID)and HolyStorm.db.global.poi.sessions[groupSession]==nil,"leaving a group clears ephemeral POIs")
groupMode="RAID";POI:HandleGroupContext();local raid;ok,raid=POI:Save(draft("RAID","Raid"),0);assert(ok and raid.sessionId and HolyStorm.Sync.discovered[#HolyStorm.Sync.discovered].options.channel=="RAID","raid session triggers scoped resync");groupMode=nil;POI:HandleGroupContext();assert(not POI:Get(raid.poiID),"leaving a raid clears ephemeral POIs")
local expiring;ok,expiring=POI:Save(draft("PERSONAL","Short"),0);expiring.expiresAt=clock+5;HolyStorm.Data.POIStore:Put(expiring);POI:ScheduleExpiration();assert(HolyStorm.Tasks.queued[#HolyStorm.Tasks.queued].options.delay==5,"earliest expiration is scheduled exactly");clock=clock+6;POI:CleanupExpired();assert(not POI:Get(expiring.poiID),"expired personal POI is removed")
local invalid=draft("GUILD","Invalid");invalid.poiID="remote-invalid";invalid.guildId="realm:guild";invalid.creatorGuid="Remote";invalid.modifiedBy="Remote";invalid.creatorName="Remote";invalid.createdAt=clock;invalid.updatedAt=clock;invalid.revision=1;invalid.x=2;assert(not domain.validate(invalid,{owner="Remote"},invalid.poiID),"invalid remote coordinates are rejected");invalid.x=.2;invalid.icon="unknown";assert(domain.validate(invalid,{owner="Remote"},invalid.poiID)and invalid.icon=="marker","unknown remote icons use the safe default");invalid.category="future-category";invalid.customCategory="";assert(domain.validate(invalid,{owner="Remote"},invalid.poiID)and invalid.category=="custom"and invalid.customCategory=="future-category","unknown categories remain readable as custom metadata")
POI:SetCategoryVisible("note",false);assert(not POI:CanView(personal),"category filter applies locally");POI:SetCategoryVisible("note",true);POI:SetSetting("worldMapSize",34);POI:SetSetting("minimapSize",16);assert(POI:GetSettings().worldMapSize==34 and POI:GetSettings().minimapSize==16,"world-map and minimap sizes are independent")
local priorPublished=#HolyStorm.Sync.published;assert(POI:SetTemporaryMarker(84,.1,.2,{timeout=10}));assert(HolyStorm.MapLinks.temporaryMarker.localOnly and#HolyStorm.Sync.published==priorPublished,"temporary coordinate marker stays local");POI:ClearTemporaryMarker()
assert(HolyStorm.Rules.fields["poi.target"]and HolyStorm.Rules.fields["poi.mapID"],"POI fields are available to the central rule engine");local listed=HolyStorm.MapLinks:ListPOIs();local found=false;for _,item in ipairs(listed)do if item.id==personal.poiID then found=true end end;assert(found,"map-link provider exposes canonical poiID")
local dx,dy,mode=HolyStorm.MapLinks:TransformCoordinate(84,.25,.75,84);assert(dx==.25 and dy==.75 and mode=="DIRECT","same-map coordinates remain exact");assert(not HolyStorm.MapLinks:TransformCoordinate(84,.25,.75,85),"cross-map positions are omitted when official transformation APIs are unavailable")
function CreateVector2D(x,y)return{x=x,y=y,GetXY=function(self)return self.x,self.y end}end;C_Map.GetWorldPosFromMapPos=function(source,point)assert(source==84);return 1,CreateVector2D(point.x*100,point.y*100)end;C_Map.GetMapPosFromWorldPos=function(continent,world,target)assert(continent==1 and target==85);return 85,CreateVector2D(world.x/200,world.y/200)end;dx,dy,mode=HolyStorm.MapLinks:TransformCoordinate(84,.25,.75,85);assert(dx==.125 and dy==.375 and mode=="TRANSFORMED","child-to-parent coordinates use the shared official world-position conversion")
local missing=POI:Open("missing-id");assert(not missing and HolyStorm.Sync.requested[#HolyStorm.Sync.requested].id=="missing-id","missing POI links request their object on demand")
local tombstone;ok,tombstone=POI:Delete(guild.poiID,POI:Get(guild.poiID).revision);assert(ok and tombstone.status=="DELETED"and tombstone.revision==3,"global delete creates a newer tombstone");assert(not domain.import(guild.poiID,newer,{owner=newer.modifiedBy},nil,"OldClient"),"an older active client cannot resurrect a tombstone");POI:GetSettings().maxSynced=0;local overflow=copy(invalid);overflow.poiID="remote-overflow";overflow.category="note";overflow.customCategory="";assert(not domain.import(overflow.poiID,overflow,{owner="Remote"},nil,"Remote"),"received POI limit rejects overflow without crashing")
currentGuild={id="realm:other"};assert(POI:Get(guild.poiID)==nil,"guild data is isolated by guild identity")
local poiModuleFile=assert(io.open(root.."Modules/POI/POI.lua","r"));local poiModuleSource=poiModuleFile:read("*a");poiModuleFile:close();assert(poiModuleSource:find('InputScrollFrameTemplate',1,true)and not poiModuleSource:find('description:GetStringHeight()',1,true),"POI editor uses Blizzard's scrolling EditBox contract")
print("POI persistence, permissions, sync, sessions, expiration, filtering and map-link tests passed")
