local root=(arg[0]:gsub("tools[/\\]test_mythicplus.lua$","")).."LIVE/Holy_Storm/"
local featureRoot=(arg[0]:gsub("tools[/\\]test_mythicplus.lua$","")).."LIVE/Holy_Storm_MythicPlus/"
local Module={};local registeredEvents={};local capabilities={};local requested={affixes=0,maps=0,rewards=0};local workflows={created=0,merged=0,active=false,queueCalls=0};local commits,emitted,blockEvents=0,{},{}
local logs={}
local HolyStorm={Utils={Now=function()return 100 end},Data={CharacterStore={}},Snapshots={},Events={},Logger={},PlayerData={}}
function HolyStorm.Logger:Write(level,source,category,message,context)logs[#logs+1]={level=level,source=source,category=category,message=message,context=context}end
HolyStorm.CharacterScans={providers={},requests={}}
function HolyStorm.CharacterScans:RegisterProvider(_,definition)self.providers[definition.block]=definition;return true end
function HolyStorm.CharacterScans:Request(block,reason,sync)self.requests[#self.requests+1]={block=block,reason=reason,sync=sync};return true,"QUEUED"end
function HolyStorm.PlayerData:RegisterBlock(block,definition)blockEvents[block]=definition.event;return true end
function HolyStorm.PlayerData:WriteOwnedBlock(_,block,snapshot)commits=commits+1;emitted[#emitted+1]={event=blockEvents[block],block=block,snapshot=snapshot};return true end
local registeredMetadata
function HolyStorm:RegisterModule(metadata,callback)registeredMetadata=metadata;callback(Module)end
function HolyStorm:ApplyModuleMetadata()end
function HolyStorm:RegisterCapability(_,name,handler)capabilities[name]=handler end
function HolyStorm.Data.CharacterStore:GetBlock()end
function HolyStorm.Data.CharacterStore:SetMythicPlus()return true end
function HolyStorm.Snapshots:Queue(_,scanner,validator,commit,options)workflows.queueCalls=workflows.queueCalls+1;workflows.scanner,workflows.validator,workflows.commit=scanner,validator,commit;workflows.lastDelay=options.delay;if workflows.active then workflows.merged=workflows.merged+1;return true,"MERGED"end;workflows.active=true;workflows.created=workflows.created+1;return true,"wf-"..workflows.created end
function HolyStorm.Snapshots:Cancel()end
function HolyStorm.Events:Register(event,_,callback)registeredEvents[event]=callback end
function HolyStorm.Events:UnregisterOwner()end
function LibStub(name)if name=="AceAddon-3.0"then return{GetAddon=function()return HolyStorm end}elseif name=="AceLocale-3.0"then return{GetLocale=function()return setmetatable({TYRANNICAL="Tyrannical",FORTIFIED="Fortified"},{__index=function(_,key)return key end})end}end end
function UnitGUID()return"A"end
local blizzardAffixNames={[9]="Tyrannical",[10]="Fortified"}
C_ChallengeMode={GetOverallDungeonScore=function()return 1128 end,GetMapTable=function()return{1,2}end,GetMapUIInfo=function(id)return"Dungeon "..id,100+id,1800,200+id,300+id,400+id end,GetAffixInfo=function(id)return blizzardAffixNames[id]or("Affix "..id),"Description",500+id end}
C_MythicPlus={GetCurrentSeason=function()return 18 end,GetCurrentUIDisplaySeason=function()return 2 end,RequestCurrentAffixes=function()requested.affixes=requested.affixes+1;if registeredEvents.MYTHIC_PLUS_CURRENT_AFFIX_UPDATE then registeredEvents.MYTHIC_PLUS_CURRENT_AFFIX_UPDATE("MYTHIC_PLUS_CURRENT_AFFIX_UPDATE")end end,RequestMapInfo=function()requested.maps=requested.maps+1;if registeredEvents.CHALLENGE_MODE_MAPS_UPDATE then registeredEvents.CHALLENGE_MODE_MAPS_UPDATE("CHALLENGE_MODE_MAPS_UPDATE")end end,RequestRewards=function()requested.rewards=requested.rewards+1;if registeredEvents.MYTHIC_PLUS_NEW_WEEKLY_RECORD then registeredEvents.MYTHIC_PLUS_NEW_WEEKLY_RECORD("MYTHIC_PLUS_NEW_WEEKLY_RECORD")end end,GetCurrentAffixes=function()return{{id=9}}end,GetOwnedKeystoneLevel=function()return 4 end,GetOwnedKeystoneChallengeMapID=function()return 1 end,GetOwnedKeystoneMapID=function()return 401 end,GetSeasonBestForMap=function()end,GetSeasonBestAffixScoreInfoForMap=function()end}
assert(loadfile(featureRoot.."MythicPlus.lua"))()
assert(registeredMetadata and registeredMetadata.id=="mythicPlus" and registeredMetadata.name=="MythicPlus" and registeredMetadata.displayName=="DISPLAY_NAME" and registeredMetadata.description=="DESCRIPTION" and registeredMetadata.version=="2.2.0" and registeredMetadata.moduleType=="feature" and registeredMetadata.category=="feature","MythicPlus exposes the central module contract")
assert(registeredMetadata.capabilities[1]=="character.scan.mythicplus" and registeredMetadata.data.block=="mythicPlus" and registeredMetadata.data.snapshotType=="mythicplus" and registeredMetadata.data.schemaVersion==3 and registeredMetadata.sync.domains[1]=="character","MythicPlus contract describes capabilities, snapshot data and sync integration")
Module:OnInitialize();Module:OnEnable();assert(type(registeredEvents.MYTHIC_PLUS_CURRENT_AFFIX_UPDATE)=="function"and type(registeredEvents.CHALLENGE_MODE_MAPS_UPDATE)=="function"and not registeredEvents.PLAYER_ENTERING_WORLD,"specific asynchronous events remain registered without PLAYER_ENTERING_WORLD")
assert(Module:NeedsBootstrapRefresh({dungeons={{affixScores={{name="Unknown"}}}}})==true and Module:NeedsBootstrapRefresh({dungeons={{affixScores={{category="TYRANNICAL"}}}}})==false,"provider freshness distinguishes unresolved from usable affix snapshots")
registeredEvents.MYTHIC_PLUS_CURRENT_AFFIX_UPDATE("MYTHIC_PLUS_CURRENT_AFFIX_UPDATE");assert(#HolyStorm.CharacterScans.requests==1 and workflows.created==0,"an affix update enters the central character-scan queue")
local provider=assert(HolyStorm.CharacterScans.providers.mythicPlus);provider.request(true,"MYTHIC_PLUS_CURRENT_AFFIX_UPDATE");assert(workflows.created==1,"the serialized provider starts one snapshot workflow")
local pending=workflows.scanner();local valid,reason=Module:Validate(pending);assert(not valid and reason=="dungeon scores pending","overall rating without loaded map scores is retried instead of committed");assert(requested.affixes==0 and requested.maps==0 and requested.rewards==0 and workflows.created==1,"API update events scan available data without re-requesting the same API and creating a loop")
local validationOk,malformedValid,malformedReason=pcall(Module.Validate,Module,{seasonId=18,dungeons="broken"});assert(validationOk and not malformedValid and malformedReason=="dungeon pool unavailable","malformed scan data is rejected without raising a Lua error")
registeredEvents.CHALLENGE_MODE_MAPS_UPDATE("CHALLENGE_MODE_MAPS_UPDATE");registeredEvents.CHALLENGE_MODE_COMPLETED("CHALLENGE_MODE_COMPLETED");registeredEvents.MYTHIC_PLUS_NEW_WEEKLY_RECORD("MYTHIC_PLUS_NEW_WEEKLY_RECORD");assert(#HolyStorm.CharacterScans.requests==4 and workflows.created==1,"bursty Mythic+ events are handed to the central merge point without request recursion")
C_MythicPlus.GetSeasonBestForMap=function(id)if id==1 then return{level=6,dungeonScore=145,durationSec=1200}end;return nil,{level=5,dungeonScore=90,durationSec=1900}end
C_MythicPlus.GetSeasonBestAffixScoreInfoForMap=function(id)if id==1 then return{{name="Tyrannical",score=145,level=6,durationSec=1200,overTime=false},{name="Fortified",score=130,level=5,durationSec=1500,overTime=true}},155 end end
local snapshot=Module:Collect();assert(Module:Validate(snapshot));assert(snapshot.snapshotVersion==3 and snapshot.scoreDataReady,"loaded per-dungeon scores produce a complete v3 snapshot");assert(snapshot.dungeons[1].bestRun.level==6 and snapshot.dungeons[1].bestRun.score==145 and not snapshot.dungeons[1].bestRun.overTime,"in-time best run is normalized");assert(snapshot.dungeons[1].score==155,"the API's second overall-score return value is retained");assert(snapshot.dungeons[1].affixScores[1].name=="Tyrannical"and snapshot.dungeons[1].affixScores[1].affixId==nil and snapshot.dungeons[1].affixScores[1].category=="TYRANNICAL"and snapshot.dungeons[1].affixScores[2].name=="Fortified"and snapshot.dungeons[1].affixScores[2].category=="FORTIFIED","the current name/score/level/durationSec/overTime affix structure is preserved and categorized without invented IDs");assert(snapshot.dungeons[2].bestRun.level==5 and snapshot.dungeons[2].bestRun.overTime and snapshot.dungeons[2].score==90,"the API's second overtime return value is retained and normalized")
assert(logs[1].message=="MPLUS_AFFIX"and logs[1].context.challengeMapId==1 and logs[1].context.dungeon=="Dungeon 1"and logs[1].context.index==1 and logs[1].context.name=="Tyrannical"and logs[1].context.score==145 and logs[1].context.level==6 and logs[1].context.durationSec==1200 and logs[1].context.overTime==false and logs[1].context.category=="TYRANNICAL","runtime affix diagnostics preserve the complete structured Blizzard entry")
blizzardAffixNames={[9]="Tyrannisch",[10]="Verstärkt"};C_MythicPlus.GetSeasonBestAffixScoreInfoForMap=function(id)if id==1 then return{{name="Tyrannisch",score=145,level=6,durationSec=1200,overTime=false},{name="Verstärkt Wertung",score=130,level=5,durationSec=1500,overTime=true}},155 end end;snapshot=Module:Collect();assert(snapshot.dungeons[1].affixScores[1].category=="TYRANNICAL"and snapshot.dungeons[1].affixScores[2].category=="FORTIFIED"and snapshot.dungeons[1].affixScores[2].name=="Verstärkt Wertung","localized Blizzard names and harmless Blizzard suffix text are categorized while the original name is retained")
C_MythicPlus.GetSeasonBestAffixScoreInfoForMap=function(id)if id==1 then return{{name="Unbekannte Wertung",score=100,level=4,durationSec=1700,overTime=false}},100 end end;snapshot=Module:Collect();assert(snapshot.dungeons[1].affixScores[1].category==nil and snapshot.dungeons[1].affixScores[1].name=="Unbekannte Wertung","an unknown Blizzard name is never guessed")
assert(requested.affixes==0 and requested.maps==0 and requested.rewards==0,"repeated Collect calls never issue asynchronous requests")
workflows.active=false;provider.request(true,"INITIAL_MISSING_BLOCK");assert(requested.affixes==1 and requested.maps==1 and requested.rewards==1,"the central initial provider requests asynchronous Mythic+ data once")
local createdAfterInitial=workflows.created;local requestsAfterInitial=requested.affixes+requested.maps+requested.rewards;workflows.scanner();assert(workflows.created==createdAfterInitial and requested.affixes+requested.maps+requested.rewards==requestsAfterInitial,"the resulting snapshot cannot recursively request data or create another workflow")
Module.initialDataRequested=false;workflows.active=false;provider.request(true,"INITIAL_STALE_BLOCK");assert(requested.affixes==2 and requested.maps==2 and requested.rewards==2 and workflows.created==createdAfterInitial+1,"a stale initial snapshot requests Blizzard data and starts a fresh workflow")
local requestsAfterStale=requested.affixes+requested.maps+requested.rewards;workflows.scanner();assert(requested.affixes+requested.maps+requested.rewards==requestsAfterStale,"a stale snapshot workflow does not recursively request Blizzard data")
Module.initialDataRequested=false;workflows.active=false;provider.request(true,"INITIAL_INCOMPLETE_BLOCK");assert(requested.affixes==3 and requested.maps==3 and requested.rewards==3,"an incomplete fresh snapshot actively requests Blizzard data")
local committedSnapshot=Module:Collect();assert(workflows.commit(committedSnapshot)and commits==1 and emitted[1].event=="HS_MYTHICPLUS_UPDATED"and emitted[1].block=="mythicPlus","the producer workflow commits through PlayerData and emits the Mythic+ update contract")
capabilities["character.scan.mythicplus"](Module,true);assert(#HolyStorm.CharacterScans.requests==14,"an explicit capability refresh is serialized instead of starting parallel work")
print("Mythic+ request separation, workflow coalescing and best-run parsing tests passed")
