-- Offline contracts for the guild-scoped permission revision engine (A-V).
local root=(arg[0]:gsub("tools[/\\]test_policy.lua$","")).."LIVE/Holy_Storm/"
local clock,currentGuid=100000,"Maristi"
unpack=unpack or table.unpack
function time()return clock end;function GetTime()return clock end;function UnitGUID()return currentGuid end;function IsInGuild()return true end;function GetGuildInfo()local m=_G.roster and _G.roster[currentGuid];return"Guild",m and m.rank,m and m.rankIndex,"Realm"end;function GetMaxLevelForPlayerExpansion()return 80 end
local locale=setmetatable({}, {__index=function(_,key)return key end})
local HolyStorm={db={global={localPlayerId="acct-maristi",localAccountUUID="acct-maristi",data={players={},characters={},characterOwners={},guilds={}},permissions={groups={},roles={}},permissionStates={},rules={global={}},filters={global={},templates={},demands={quests={},achievements={}}},policy={tombstones={groups={},rules={},filters={}}},news={entries={keep=true}}},profile={rules={localRules={}},filters={localFilters={},activeByContext={}}}}}
function HolyStorm:GetAddon()return self end;function LibStub(name)if name=="AceLocale-3.0"then return{GetLocale=function()return locale end}end;return HolyStorm end
HolyStorm.Database={initialized=true,rootReads=0};function HolyStorm.Database:IsInitialized()return self.initialized==true and type(HolyStorm.db)=="table"end;function HolyStorm.Database:GetRoot(scope)self.rootReads=self.rootReads+1;if not self:IsInitialized()then return nil end;if scope=="character"or scope=="char"then return HolyStorm.db.char end;return HolyStorm.db[scope or"profile"]end
assert(loadfile(root.."Core/Utils/Utils.lua"))();assert(loadfile(root.."Core/Serialization/Serializer.lua"))()
HolyStorm.Logger={Write=function()end};HolyStorm.Events={listeners={}}
function HolyStorm.Events:Register(e,o,fn)self.listeners[e]=self.listeners[e]or{};self.listeners[e][o]=fn end;function HolyStorm.Events:Emit(e,...)for _,fn in pairs(self.listeners[e]or{})do fn(e,...)end end
HolyStorm.State={values={guildRosterReady=true}};function HolyStorm.State:Is(key)return self.values[key]==true end
HolyStorm.Tasks={types={},queued={}};function HolyStorm.Tasks:RegisterTaskType(id,d)self.types[id]=d;return true end;function HolyStorm.Tasks:GetTaskType(id)return self.types[id]end;function HolyStorm.Tasks:Queue(id,o)self.queued[#self.queued+1]={id=id,options=o};return id end
HolyStorm.Sync={domains={},published={}};function HolyStorm.Sync:RegisterDomain(id,d)d.id=id;self.domains[id]=d;return true end;function HolyStorm.Sync:GetDomain(id)return self.domains[id]end;function HolyStorm.Sync:Publish(...)self.published[#self.published+1]={...};return true end;function HolyStorm.Sync:Discover(...)self.discovered={...};return"request"end
local characters={Maristi={guid="Maristi",level=80,classFile="PALADIN",itemLevel=710,demands={quests={[12345]=true}}},Anna={guid="Anna",level=80,classFile="PRIEST",itemLevel=700,demands={quests={}}},Daniel={guid="Daniel",level=80,classFile="WARRIOR",itemLevel=705,demands={quests={}}},Klaus={guid="Klaus",level=70,classFile="MAGE",itemLevel=250,demands={quests={}}}}
local fullCharacterReads,projectionReads,rosterSummaryReads=0,0,0
local accounts={Maristi="acct-maristi",Anna="acct-anna",Daniel="acct-raid",Klaus="acct-klaus"}
_G.roster={Maristi={guid="Maristi",name="Maristi-Realm",rank="Guild Master",rankIndex=0},Anna={guid="Anna",name="Anna-Realm",rank="Member",rankIndex=3},Daniel={guid="Daniel",name="Daniel-Realm",rank="Officer",rankIndex=1},Klaus={guid="Klaus",name="Klaus-Realm",rank="Member",rankIndex=4}}
local guild={id="realm:guild",roster=_G.roster,ranks={[1]="Guild Master",[2]="Officer"}}
HolyStorm.Data={PlayerStore={},CharacterStore={},GuildStore={}}
function HolyStorm.Data.PlayerStore:GetLocalPlayerId()return"acct-maristi"end;function HolyStorm.Data.PlayerStore:Get(id)return{id=id,characters={}}end;function HolyStorm.Data.PlayerStore:GetCharacterOwner(guid)return accounts[guid]end
function HolyStorm.Data.CharacterStore:Get(guid)fullCharacterReads=fullCharacterReads+1;return characters[guid]end;function HolyStorm.Data.CharacterStore:GetProjection(guid,blocks)projectionReads=projectionReads+1;local result={guid=guid};for _,block in ipairs(blocks or{})do if block=="identity"then for key,value in pairs(characters[guid]or{})do result[key]=value end elseif block=="demands"then result.demands=characters[guid]and characters[guid].demands end end;return result end;function HolyStorm.Data.CharacterStore:Upsert(guid,changes)characters[guid]=characters[guid]or{guid=guid};for k,v in pairs(changes)do characters[guid][k]=v end;return true end
function HolyStorm.Data.GuildStore:GetCurrent()return guild end;function HolyStorm.Data.GuildStore:GetCurrentRosterSummary()rosterSummaryReads=rosterSummaryReads+1;local result={id=guild.id,roster={}};for guid,member in pairs(guild.roster)do result.roster[guid]={rankIndex=member.rankIndex,classFile=member.classFile,level=member.level}end;return result end;function HolyStorm.Data.GuildStore:GetGuildId()return guild.id end;function HolyStorm.Data.GuildStore:ResolveSenderGuid(sender)return sender end
HolyStorm.TwinkCore={GetLocalAccountUUID=function()return"acct-maristi"end,GetAccountUUIDForCharacter=function(_,guid)return accounts[guid]end,GetAccount=function(_,id)return id and{accountUUID=id}end,GetCharactersForAccount=function(_,id)local out={};for guid,account in pairs(accounts)do if account==id then out[guid]={characterUUID=guid}end end;return out end,GetAccountMain=function(_,id)for guid,account in pairs(accounts)do if account==id then return guid end end end}
assert(loadfile(root.."Core/Permissions/RuleEngine.lua"))();assert(loadfile(root.."Core/Permissions/PermissionRegistry.lua"))();assert(loadfile(root.."Core/Permissions/GroupManager.lua"))();assert(loadfile(root.."Core/Permissions/FilterManager.lua"))();assert(loadfile(root.."Core/Permissions/PolicyState.lua"))()
local persistedDatabase=HolyStorm.db;HolyStorm.db=nil;HolyStorm.Database.initialized=false
local earlyOk,earlyResult=pcall(function()return HolyStorm.PermissionRegistry:RegisterPermission({id="calendar-read",module="LifecycleTest",category="Calendar",defaults={member=true}})end);assert(earlyOk and earlyResult,"permission metadata must be safe before persistence initialization");assert(HolyStorm.PermissionComponents.State:GetStates()==nil,"policy state must not synthesize storage before persistence")
HolyStorm.db=persistedDatabase;HolyStorm.Database.initialized=true
assert(loadfile(root.."Core/Permissions/PermissionEngine.lua"))();assert(loadfile(root.."Core/Permissions/PermissionSync.lua"))();assert(loadfile(root.."Core/Permissions/Policy.lua"))();assert(loadfile(root.."Core/Permissions/Permissions.lua"))();HolyStorm.Rules:RegisterField("test-character","character.level",{type="number",resolver=function(context)return context.character and context.character.level end});HolyStorm.Rules:RegisterField("test-character","character.class",{type="string",resolver=function(context)return context.character and context.character.classFile end});HolyStorm.Rules:RegisterField("test-character","character.maxLevel",{type="boolean",resolver=function(context)return context.character and context.character.level==80 end});HolyStorm.Rules:RegisterField("test-guild","player.online",{type="boolean",resolver=function(context)return context.member and context.member.online end});HolyStorm.Rules:RegisterField("test-demands","quest.completed",{type="boolean",resolver=function(context)return context.character and context.character.demands and context.character.demands.quests[tonumber(context.argument)]end});HolyStorm.Rules:Initialize();for _,field in ipairs({"equipment.itemLevel","mythicplus.rating","raid.progress","delves.status"})do HolyStorm.Rules:RegisterField("test-features",field,{type="number",resolver=function(context)return context.character and context.character.itemLevel end})end;HolyStorm.Permissions:Initialize();assert(HolyStorm.Policy:Initialize())
for _,id in ipairs({"news-view","news-create","news-edit","calendar-manage","raids-read","equipment-read"}) do HolyStorm.Permissions:RegisterPermission({id=id,module="TestFixture",category="Test"}) end
local P,R=HolyStorm.Policy,HolyStorm.Rules;local ids=HolyStorm.Permissions.systemIds;local state=P:GetState();assert(state and state.status==P.status.VALID and state.version==1);assert(HolyStorm.Database.rootReads>0,"PolicyState must use the Database facade");assert(HolyStorm.Sync:GetDomain("permissions").freshness=="revision-chain")
local queuedBeforeBaseline=#HolyStorm.Tasks.queued;HolyStorm.State.values.guildRosterReady=false;P:Invalidate("CORE_UI_BASELINE");assert(#HolyStorm.Tasks.queued==queuedBeforeBaseline,"policy queued roster work without a ready roster");HolyStorm.State.values.guildRosterReady=true;P:Invalidate("ROSTER_READY");local rosterTask=HolyStorm.Tasks.queued[#HolyStorm.Tasks.queued];assert(rosterTask.id=="Policy.RecalculateEffectiveMemberships"and rosterTask.options.dependencies==nil,"policy recalculation must use roster readiness instead of a feature task dependency")
state.modules.lifecyclePreserved=true;local stateReference=state;assert(P:BootstrapState());assert(P:GetState()==stateReference and P:GetState().modules.lifecyclePreserved==true,"PolicyState bootstrap must preserve persisted state")
local policyStateSource=assert(io.open(root.."Core/Permissions/PolicyState.lua","r"));local policyStateText=policyStateSource:read("*a");policyStateSource:close();assert(not policyStateText:find("HolyStorm.db",1,true),"PolicyState must not bypass the Database facade")
local bootstrapSource=assert(io.open(root.."Core/Bootstrap/Bootstrap.lua","r"));local bootstrapText=bootstrapSource:read("*a");bootstrapSource:close();local databaseInit=assert(bootstrapText:find("self.Database:Initialize()",1,true));local policyInit=assert(bootstrapText:find("self.Policy:Initialize()",1,true));assert(databaseInit<policyInit,"normal bootstrap must initialize persistence before policy state")

-- A: guild membership is dynamic and disappears with Blizzard roster state.
assert(P:GetEffectiveGroups("acct-klaus","Klaus")[ids.MEMBER]);guild.roster.Klaus=nil;P:Invalidate("TEST");assert(not P:GetEffectiveGroups("acct-klaus","Klaus")[ids.MEMBER]);guild.roster.Klaus=_G.roster.Klaus
-- B: rank-1 membership is dynamic; an independent character source remains.
assert(P:GetEffectiveGroups("acct-raid","Daniel")[ids.OFFICERS]);guild.roster.Daniel.rankIndex=3;P:Invalidate("TEST");assert(not P:GetEffectiveGroups("acct-raid","Daniel")[ids.OFFICERS]);assert(P:AddCharacterMembership(ids.OFFICERS,"Daniel"));assert(P:GetEffectiveGroups("acct-raid","Daniel")[ids.OFFICERS]);guild.roster.Daniel.rankIndex=1
-- C: actual Blizzard leadership transfers dynamically.
assert(P:GetEffectiveGroups("acct-maristi","Maristi")[ids.LEADERSHIP]);guild.roster.Maristi.rankIndex=2;guild.roster.Daniel.rankIndex=0;P:Invalidate("LEADER_CHANGE");assert(P:GetEffectiveGroups("acct-raid","Daniel")[ids.LEADERSHIP]);assert(not P:GetEffectiveGroups("acct-maristi","Maristi")[ids.LEADERSHIP]);guild.roster.Maristi.rankIndex=0;guild.roster.Daniel.rankIndex=1
-- D: only actual leader can alter additional leadership members.
assert(P:AddCharacterMembership(ids.LEADERSHIP,"Anna"));local leadership=P:GetGroup(ids.LEADERSHIP);leadership.characterMembers.Daniel=true;leadership.guildRanks[4]=true;local normalized=P:NormalizeGroup(leadership,P:GetGroup(ids.LEADERSHIP));assert(not P:CommitChange({action="GROUP_UPSERT",group=normalized},{accountUUID="acct-anna",characterUUID="Anna"}))
-- E: positive grants from multiple groups are additive.
local okE,errE=P:CreateGroup({id="news-team",name="News",permissions={["news-create"]=true}});assert(okE,tostring(errE))
local memberE,memberErr=P:AddCharacterMembership("news-team","Klaus");assert(memberE,tostring(memberErr))
okE,errE=P:CreateGroup({id="event-team",name="Events",permissions={["calendar-manage"]=true}});assert(okE,tostring(errE))
memberE,memberErr=P:AddCharacterMembership("event-team","Klaus");assert(memberE,tostring(memberErr))
local effective=P:GetEffectivePermissions("acct-klaus","Klaus");assert(effective["news-create"]and effective["calendar-manage"],"additive permissions")
-- F: account membership automatically covers newly discovered twinks.
assert(P:CreateGroup({id="raid-lead",name="Raid Lead",permissions={["raids-read"]=true}}));assert(P:AddAccountMembership("raid-lead","acct-raid"));assert(P:GetEffectiveGroups("acct-raid","Daniel")["raid-lead"]);accounts.Marithiel="acct-raid";characters.Marithiel={guid="Marithiel",level=80,itemLevel=700};guild.roster.Marithiel={guid="Marithiel",rankIndex=4};P:Invalidate("HS_TWINKS_UPDATED");assert(P:GetEffectiveGroups("acct-raid","Marithiel")["raid-lead"])
-- G: reusable AND filter membership reacts to changed character data.
local filter={id="raid-ready-filter",name="Raid ready",root={logic="AND",children={{field="equipment.itemLevel",operator=">=",value=300},{field="quest.completed",operator="true",value=12345}}}}
local okG,errG=P:CreateFilter(filter);assert(okG,tostring(errG))
okG,errG=P:CreateGroup({id="raid-ready",name="Raid Ready",permissions={["equipment-read"]=true}});assert(okG,tostring(errG))
okG,errG=P:AttachFilter("raid-ready","raid-ready-filter");assert(okG,tostring(errG))
assert(not P:GetEffectiveGroups("acct-anna","Anna")["raid-ready"],"filter should initially fail")
characters.Anna.demands.quests[12345]=true;P:Invalidate("HS_CHARACTER_UPDATED");assert(P:GetEffectiveGroups("acct-anna","Anna")["raid-ready"],"filter should update")
assert(P:SaveRule({id="max-level-rule",name="Max level",root={field="character.level",operator=">=",value=80}},"global"));local ruleGroup=P:GetGroup("raid-ready");ruleGroup.ruleIds={"max-level-rule"};assert(P:SaveGroup(ruleGroup));assert(P:GetEffectiveGroups("acct-raid","Daniel")["raid-ready"],"reusable rule membership should apply")
-- H: manager-group membership grants management authority, not permissions.
assert(P:SetGroupManagers("raid-ready",{"raid-lead"}));assert(P:CanManageGroup("acct-raid","Daniel","raid-ready"));assert(not P:CanManageGroup("acct-klaus","Klaus","raid-ready"))
assert(P:RemoveManagerGroup("raid-ready","raid-lead"));assert(not P:CanManageGroup("acct-raid","Daniel","raid-ready"));assert(P:AddManagerGroup("raid-ready","raid-lead"))

-- H2: membership sources remain independent and removing one source preserves the others.
assert(P:AddCharacterMembership("raid-ready","Anna"));local reasonsH2=P:GetMembershipReasons(P:GetGroup("raid-ready"),"acct-anna","Anna");local sourcesH2={};for _,reason in ipairs(reasonsH2)do sourcesH2[reason.source]=true end;assert(sourcesH2.MANUAL and sourcesH2.FILTER,"manual and filter sources must be visible together")
assert(P:RemoveMembership("raid-ready","character","Anna"));assert(P:IsMemberOfGroup("raid-ready","acct-anna","Anna"),"removing a manual source removed a valid filter membership")

-- H3: permission assignments are mutable, while the matrix is registry-driven and exposes defaults/protection.
local permissionsH3=P:GetGroup("raid-ready").permissions;permissionsH3["news-edit"]=true;assert(P:SetGroupPermissions("raid-ready",permissionsH3));assert(P:GetGroup("raid-ready").permissions["news-edit"])
permissionsH3=P:GetGroup("raid-ready").permissions;permissionsH3["news-edit"]=nil;assert(P:SetGroupPermissions("raid-ready",permissionsH3));assert(not P:GetGroup("raid-ready").permissions["news-edit"])
local unknownH3=P:GetGroup("raid-ready");unknownH3.permissions["removed-module-permission"]=true;assert(P:SaveGroup(unknownH3));local matrixH3=P:GetPermissionMatrix();local seenH3={};for _,row in ipairs(matrixH3.rows)do seenH3[row.permissionId]=row end;assert(seenH3["news-edit"]and not seenH3["removed-module-permission"],"matrix must contain only actively registered permissions");assert(seenH3["news-edit"].assignments[ids.LEADERSHIP].protected and seenH3["news-edit"].assignments[ids.LEADERSHIP].effective,"leadership matrix cell must be protected full access");local detailH3=P:GetPermissionDetail("news-edit","acct-maristi","Maristi");assert(detailH3 and detailH3.registered and detailH3.available and detailH3.definition.module=="TestFixture")

-- H4: deleting a custom manager group removes every manager reference in the same revision.
assert(P:CreateGroup({id="temporary-managers",name="Temporary Managers",permissions={}}));assert(P:CreateGroup({id="temporary-target",name="Temporary Target",permissions={}}));assert(P:SetGroupManagers("temporary-target",{"temporary-managers"}));local impactH4=P:GetGroupDeletionImpact("temporary-managers");assert(impactH4 and #impactH4.managerReferences==1);assert(P:DeleteGroup("temporary-managers"));assert(#P:GetGroup("temporary-target").managerGroupIds==0,"manager reference survived group deletion")

-- H5: creation cannot smuggle privileged assignments, and leadership permissions are immutable in Core.
assert(P:CreateGroup({id="group-creators",name="Group Creators",permissions={["groups-create"]=true}}));assert(P:AddCharacterMembership("group-creators","Klaus"));local simpleH5=P:NormalizeGroup({id="klaus-simple",name="Klaus Simple",permissions={},characterMembers={},accountMembers={},guildRanks={},filterIds={},ruleIds={},managerGroupIds={}});assert(P:CommitChange({action="GROUP_UPSERT",group=simpleH5},{accountUUID="acct-klaus",characterUUID="Klaus"}),"groups-create should create an empty custom group");local privilegedH5=P:NormalizeGroup({id="klaus-privileged",name="Klaus Privileged",permissions={["permissions-reset"]=true},characterMembers={},accountMembers={},guildRanks={},filterIds={},ruleIds={},managerGroupIds={}});assert(not P:CommitChange({action="GROUP_UPSERT",group=privilegedH5},{accountUUID="acct-klaus",characterUUID="Klaus"}),"groups-create must not assign arbitrary permissions")
local leadershipPermissionsH5=P:GetGroup(ids.LEADERSHIP).permissions;leadershipPermissionsH5["news-edit"]=true;local protectedH5,protectedReasonH5=P:SetGroupPermissions(ids.LEADERSHIP,leadershipPermissionsH5);assert(not protectedH5 and protectedReasonH5=="FULL_ACCESS_GROUP")
local systemH5=P:GetGroup(ids.OFFICERS);systemH5.managerGroupIds={};local systemOkH5,systemReasonH5=P:SaveGroup(systemH5);assert(not systemOkH5 and systemReasonH5=="SYSTEM_INVARIANT","system-group manager invariants must be protected")
-- I: system groups remain undeletable despite full access.
assert(not P:DeleteGroup(ids.MEMBER))
-- J: a sequential revision with the exact predecessor is accepted.
local baseVersion,baseRevision=state.version,state.revisionID;local group=P:NormalizeGroup({id="remote-sequential",name="Sequential",permissions={},characterMembers={},accountMembers={},guildRanks={},filterIds={},ruleIds={},managerGroupIds={} });local revJ={version=baseVersion+1,revisionID="remote-j",previousRevisionID=baseRevision,changedBy={accountUUID="acct-maristi",characterUUID="Maristi"},changedAt=clock+1,change={action="GROUP_UPSERT",group=group}};assert(P:ApplyRevision(state,revJ));assert(state.revisionID=="remote-j")
-- K: a chain gap is not accepted and starts catch-up/recovery.
local gap={guildId=guild.id,current={version=state.version+2,revisionID="gap-current",previousRevisionID="missing",changedBy={accountUUID="acct-anna",characterUUID="Anna"},changedAt=clock+2},history={{version=state.version+2,revisionID="gap-current",previousRevisionID="missing",changedBy={accountUUID="acct-anna",characterUUID="Anna"},changedAt=clock+2,change={action="GROUP_DELETE",groupId="remote-sequential"}}},snapshot=P:Snapshot(state)};local gapOk,gapErr=P:ImportPermissionState(guild.id,gap,nil,"Anna");assert(not gapOk,tostring(gapErr));assert(state.status==P.status.RECOVERY_REQUIRED and HolyStorm.Tasks.queued[#HolyStorm.Tasks.queued].id=="Policy.PermissionCatchup",tostring(state.status))
state.status=P.status.VALID;state.missingRevisions={}
-- L: authorization is evaluated after each direct predecessor, not against stale base.
local stale=copy and copy(state)or HolyStorm.Utils.DeepCopy(state);local leaderGroup=HolyStorm.Utils.DeepCopy(stale.groups[ids.LEADERSHIP]);leaderGroup.characterMembers.Daniel=true;local r1={version=stale.version+1,revisionID="chain-l1",previousRevisionID=stale.revisionID,changedBy={accountUUID="acct-maristi",characterUUID="Maristi"},changedAt=clock+3,change={action="GROUP_UPSERT",group=leaderGroup}};assert(P:ApplyRevision(stale,r1));local created=P:NormalizeGroup({id="daniel-created",name="Daniel",permissions={},characterMembers={},accountMembers={},guildRanks={},filterIds={},ruleIds={},managerGroupIds={}});local r2={version=stale.version+1,revisionID="chain-l2",previousRevisionID=stale.revisionID,changedBy={accountUUID="acct-raid",characterUUID="Daniel"},changedAt=clock+4,change={action="GROUP_UPSERT",group=created}};assert(P:ApplyRevision(stale,r2))
-- M: sibling revisions for the same predecessor are a fork.
local sibling={version=state.version,revisionID="fork-m",previousRevisionID=state.previousRevisionID,changedBy={accountUUID="acct-maristi",characterUUID="Maristi"},changedAt=clock+5,change={action="GROUP_DELETE",groupId="remote-sequential"}};assert(not P:ApplyRevision(state,sibling));assert(state.status==P.status.CONFLICT);state.status=P.status.VALID;state.fork=nil
-- N: reset is a chained revision, clears group customization, and preserves reusable and unrelated data.
HolyStorm.db.profile.filters.localFilters.personal={id="personal",name="Personal"};HolyStorm.db.profile.rules.localRules.personal={id="personal",name="Personal"};HolyStorm.db.global.data.characters.keep={mythicPlus={overallScore=2500}};assert(P:SetGuildModuleEnabled("feature",false))
local beforeReset,previousResetRevision=state.version,state.revisionID;assert(P:RestoreDefaults());assert(state.version==beforeReset+1 and state.previousRevisionID==previousResetRevision and state.revisionID~=previousResetRevision);assert(not P:GetGroup("news-team")and P:GetFilter("raid-ready-filter")and P:GetRule("max-level-rule")and state.modules.feature==false);assert(P:GetFilters("local").personal and P:GetRules("local").personal and HolyStorm.db.global.news.entries.keep and HolyStorm.db.global.data.characters.keep.mythicPlus.overallScore==2500);local resetRevision=state.history[#state.history];assert(resetRevision.change.action=="RESET" and resetRevision.changedBy.characterUUID=="Maristi" and resetRevision.changedAt==clock);local resetStatus=P:GetPermissionStateStatus();assert(resetStatus.changedBy.characterUUID=="Maristi" and resetStatus.changedAt==clock and resetStatus.rejectedLength>=1)
-- O: an ordinary guild member cannot reset and no revision is created.
local beforeDenied=state.version;assert(not P:CommitChange({action="RESET"},{accountUUID="acct-klaus",characterUUID="Klaus"}));assert(state.version==beforeDenied)
-- P: partially migrated groups remain safe while startup/sync normalization catches up.
local partial=state.groups[ids.MEMBER];partial.characterMembers=nil;partial.accountMembers=nil;partial.guildRanks=nil;partial.filterIds=nil;partial.ruleIds=nil;partial.permissions=nil
P:Invalidate("PARTIAL_LEGACY_GROUP");assert(P:Recalculate());assert(P:GetEffectiveGroups("acct-anna","Anna")[ids.MEMBER]);assert(next(P:GetEffectivePermissions("acct-anna","Anna"))==nil);P:UpgradeState(state)

-- Q: exactly three protected system groups survive reset; system membership is not mutable.
assert(HolyStorm.Utils.TableCount(P:GetGroups())==3,"reset must restore exactly three system groups")
assert(not P:DeleteGroup(ids.LEADERSHIP) and not P:DeleteGroup(ids.OFFICERS) and not P:DeleteGroup(ids.MEMBER))
local removedSystem,removedSystemReason=P:RemoveMembership(ids.MEMBER,"system","GUILD_MEMBER");assert(not removedSystem and removedSystemReason=="SYSTEM_MEMBERSHIP")

-- R: character and guild-rank memberships remain distinct dynamic sources.
assert(P:CreateGroup({id="character-only",name="Character Only",permissions={}}));assert(P:AddCharacterMembership("character-only","Anna"));assert(P:IsMemberOfGroup("character-only","acct-anna","Anna"));assert(not P:IsMemberOfGroup("character-only","acct-klaus","Klaus"))
guild.roster.Klaus={guid="Klaus",name="Klaus-Realm",rank="Member",rankIndex=4};assert(P:CreateGroup({id="rank-four",name="Rank Four",permissions={}}));assert(P:AddGuildRankMembership("rank-four",4));assert(P:IsMemberOfGroup("rank-four","acct-klaus","Klaus"));guild.roster.Klaus.rankIndex=3;P:Invalidate("RANK_CHANGED");assert(not P:IsMemberOfGroup("rank-four","acct-klaus","Klaus"));guild.roster.Klaus.rankIndex=4;P:Invalidate("RANK_RESTORED")

-- S: leadership receives newly registered permissions; manager groups only grant management authority.
assert(HolyStorm.Permissions:RegisterPermission({id="future-permission",module="Test",category="Test"}));assert(P:HasPermission("acct-maristi","Maristi","future-permission"));assert(P:AddCharacterMembership(ids.LEADERSHIP,"Anna"));assert(P:HasPermission("acct-anna","Anna","future-permission"))
assert(P:CreateGroup({id="managed-target",name="Managed Target",permissions={["future-permission"]=true}}));assert(P:CreateGroup({id="target-managers",name="Target Managers",permissions={}}));assert(P:AddCharacterMembership("target-managers","Daniel"));assert(P:SetGroupManagers("managed-target",{"target-managers"}));assert(P:CanManageGroup("acct-raid","Daniel","managed-target"));assert(not P:HasPermission("acct-raid","Daniel","future-permission"))

-- T: filters reuse the rule engine for AND/OR and preserve UNKNOWN.
assert(P:CreateFilter({id="filter-level",name="Level",root={field="character.level",operator=">=",value=80}}));assert(P:CreateFilter({id="filter-mage",name="Mage",root={field="character.class",operator="=",value="MAGE"}}));assert(P:CreateGroup({id="filter-combine",name="Filter Combine",permissions={}}));local combine=P:GetGroup("filter-combine");combine.filterIds={"filter-level","filter-mage"};combine.filterOperator="OR";assert(P:SaveGroup(combine));assert(P:IsMemberOfGroup("filter-combine","acct-anna","Anna"));combine=P:GetGroup("filter-combine");combine.filterOperator="AND";assert(P:SaveGroup(combine));assert(not P:IsMemberOfGroup("filter-combine","acct-anna","Anna"));local unknownStatus=R:EvaluateDetailed({field="equipment.itemLevel",operator=">=",value=1},{});assert(unknownStatus==R.Result.UNKNOWN)
local optionalFilter={id="filter-optional-module",name="Optional module",root={field="external.featureScore",operator=">=",value=10}};assert(P:SaveFilter(optionalFilter,"global"));local retained=P:GetFilter(optionalFilter.id,"global");assert(retained and retained.root.field=="external.featureScore");local _,_,optionalStatus=P:ApplyFilter(retained,{guid="Anna"});assert(optionalStatus==R.Result.UNKNOWN)

-- U: legacy role calls delegate to the single group state and old IDs normalize.
assert(HolyStorm.Permissions:CreateRole("legacy-role","Legacy",{["news-view"]=true}));assert(HolyStorm.Permissions:AssignRole("acct-klaus","legacy-role",true));assert(P:IsMemberOfGroup("legacy-role","acct-klaus","Klaus"));assert(HolyStorm.Permissions:NormalizePermissionId("permissions.manage")=="permissions-manage")
assert(HolyStorm.PermissionRegistry:GetPermission("future-permission").module=="Test");assert(HolyStorm.GroupManager:GetGroup("legacy-role"));assert(HolyStorm.PermissionEngine:IsMemberOfGroup("legacy-role","acct-klaus","Klaus"));assert(HolyStorm.FilterManager:GetFilter("filter-level"));assert(HolyStorm.PolicyState:GetState().revisionID==P:GetState().revisionID)
assert(HolyStorm.PermissionManager==HolyStorm.Permissions and HolyStorm:HasPermission("future-permission","acct-maristi","Maristi"));assert(HolyStorm.Permissions:GetRoles()["legacy-role"]);assert(HolyStorm.Permissions:UpdateRole("legacy-role","Legacy updated",{["news-edit"]=true}));assert(HolyStorm.Permissions:GetRoles()["legacy-role"].permissions["news-edit"]);assert(HolyStorm.Permissions:DeleteRole("legacy-role"))

-- Generic condition contracts are retained and IDs are hyphenated.
assert(R:Evaluate({field="character.level",operator=">=",value=80},P:BuildContext("acct-maristi","Maristi")));for id in pairs(HolyStorm.Permissions:GetPermissionDefinitions())do assert(id:match("^[a-z][a-z0-9%-]*$"),id)end
local nested={logic="AND",children={{field="character.level",operator=">=",value=80},{logic="NOT",children={{field="character.class",operator="=",value="MAGE"}}}}};assert(R:Evaluate(nested,P:BuildContext("acct-maristi","Maristi")));assert(not R:Validate({field="character.level",operator="contains",value="8"}))
-- V: defaults initialize a newly known permission once and never overwrite a manual removal.
assert(HolyStorm.PermissionRegistry:RegisterPermission({id="default-once",module="Test",category="Test",defaults={member=true}}));local defaultsMember=P:GetGroup(ids.MEMBER);assert(defaultsMember.permissions["default-once"]==true,"new permission default was not initialized");defaultsMember.permissions["default-once"]=nil;assert(P:SaveGroup(defaultsMember));assert(HolyStorm.PermissionRegistry:RegisterPermission({id="default-once",module="Test",category="Test",defaults={member=true}}));P:UpgradeState(state);assert(P:GetGroup(ids.MEMBER).permissions["default-once"]==nil,"module re-registration or upgrade overwrote an administrator change")
local otherGuild=P:CreateState("realm:other");assert(next(otherGuild.filters)==nil and next(otherGuild.rules)==nil and HolyStorm.Utils.TableCount(otherGuild.groups)==3,"guild state leaked across guilds")
assert(P:Recalculate(),"effective membership recalculation failed")
fullCharacterReads,projectionReads,rosterSummaryReads=0,0,0
assert(P:Recalculate(),"projected membership recalculation failed")
assert(fullCharacterReads==0,"policy recalculation must not read full character records")
assert(projectionReads==HolyStorm.Utils.TableCount(guild.roster),"policy recalculation must project each guild character once")
assert(rosterSummaryReads==1,"policy recalculation must read one compact guild summary")

-- W: complete filter CRUD preserves metadata and duplication creates a fresh identity/audit record.
assert(P:SaveFilter({id="admin-crud",name="Admin CRUD",description="Initial",category="Tests",root={field="character.level",operator=">=",value=70}},"global"))
local crud=P:GetFilter("admin-crud","global");assert(crud.creator=="Maristi"and crud.createdAt==clock and crud.modifiedBy=="Maristi"and crud.version==1 and crud.scope=="global")
clock=clock+1;crud.description="Changed";assert(P:SaveFilter(crud,"global"));crud=P:GetFilter("admin-crud","global");assert(crud.description=="Changed"and crud.version==2 and crud.modifiedAt==clock)
clock=clock+1;local duplicated,duplicate=P:DuplicateFilter("admin-crud","global",{name="Admin CRUD Copy"});assert(duplicated,tostring(duplicate));assert(duplicate.id~="admin-crud"and duplicate.name=="Admin CRUD Copy"and duplicate.version==1 and duplicate.createdAt==clock)

-- X: central reference providers protect deletion; providers can be added and removed without hardcoding consumers.
assert(P:RegisterReferenceProvider("test-owner","test-consumer",function(kind,id)return kind=="filters"and id==duplicate.id and{{kind="module",id="consumer",name="Test consumer"}}or{}end))
local refs=P:GetReferences("filters",duplicate.id,"global");assert(#refs==1 and refs[1].provider=="test-consumer"and refs[1].owner=="test-owner")
local blocked,blockedReason,blockedRefs=P:DeleteFilter(duplicate.id,"global");assert(not blocked and blockedReason=="FILTER_IN_USE"and#blockedRefs==1)
assert(P:UnregisterReferenceOwner("test-owner")==1);assert(P:DeleteFilter(duplicate.id,"global"))
assert(P:CreateGroup({id="filter-reference",name="Filter Reference",permissions={}}));assert(P:AttachFilter("filter-reference","admin-crud"));local groupRefs=P:GetReferences("filters","admin-crud","global");assert(#groupRefs==1 and groupRefs[1].kind=="group"and groupRefs[1].id=="filter-reference");assert(not P:DeleteFilter("admin-crud","global"));assert(P:DetachFilter("filter-reference","admin-crud"));assert(P:DeleteFilter("admin-crud","global"))
assert(P:SaveFilter({id="local-active",name="Local active",root={field="character.level",operator=">=",value=1}},"local"));assert(P:SetActiveFilters("test-context",{{id="local-active",scope="local"}}));local contextRefs=P:GetReferences("filters","local-active","local");assert(#contextRefs==1 and contextRefs[1].kind=="context");assert(not P:DeleteFilter("local-active","local"));assert(P:SetActiveFilters("test-context",{}));assert(P:DeleteFilter("local-active","local"))

-- Y: rule-tree validation covers single conditions, nested AND/OR/NOT and type-specific operators/values.
assert(R:RegisterField("test-types","test.enum",{type="enum",values={"A","B"},resolver=function(context)return context.enum end}))
assert(R:RegisterField("test-types","test.boolean",{type="boolean",resolver=function(context)return context.boolean end}))
assert(R:RegisterField("test-types","test.string",{type="string",resolver=function(context)return context.string end}))
local typedTree={logic="AND",children={{field="character.level",operator=">=",value=70},{logic="OR",children={{field="test.string",operator="contains",value="storm"},{field="test.enum",operator="in",value={"A","B"}}}},{field="test.boolean",operator="true"}}}
assert(R:Validate(typedTree));local typedStatus,typedTrace=R:EvaluateDetailed(typedTree,{character={level=80},string="Holy Storm",enum="A",boolean=true});assert(typedStatus==R.Result.PASS and#typedTrace==6)
assert(not R:Validate({logic="AND",children={}}));assert(not R:Validate({field="character.level",operator="contains",value="80"}));assert(not R:Validate({field="character.level",operator=">=",value="not-a-number"}));assert(not R:Validate({field="test.boolean",operator="=",value="true"}));assert(R:Validate({field="test.enum",operator="not_in",value={"B"}}));assert(not R:Validate({field="test.enum",operator="=",value="C"}))
local numberOperators=R:GetAllowedOperators("character.level");local hasGreater=false;for _,operator in ipairs(numberOperators)do if operator==">"then hasGreater=true end end;assert(hasGreater and R:GetOperator(">").types[1]=="number"and R:GetOperators().contains)

-- Z: unavailable optional fields remain portable, evaluate UNKNOWN, and recover after owner re-registration.
assert(R:RegisterField("optional-owner","optional.score",{type="number",resolver=function(context)return context.optionalScore end}))
local optionalTree={field="optional.score",operator=">=",value=10};assert(R:EvaluateDetailed(optionalTree,{optionalScore=12})==R.Result.PASS);assert(R:UnregisterOwner("optional-owner")==1);assert(R:Validate(optionalTree));local missingStatus,missingTrace=R:EvaluateDetailed(optionalTree,{optionalScore=12});assert(missingStatus==R.Result.UNKNOWN and missingTrace[1].reason:match("UNKNOWN_FIELD"));assert(R:RegisterField("optional-owner","optional.score",{type="number",resolver=function(context)return context.optionalScore end}));assert(R:EvaluateDetailed(optionalTree,{optionalScore=12})==R.Result.PASS)

-- AA: preview returns a structured trace with actual/expected/provider/reason and never changes revisions or objects.
local previewSaved,previewSaveReason=P:SaveFilter({id="preview-filter",name="Preview",root={logic="OR",children={{field="character.level",operator=">=",value=80},{field="missing.preview",operator="exists"}}}},"global")
assert(previewSaved,tostring(previewSaveReason))
local previewRevision=P:GetPermissionStateStatus().revisionID
local previewBefore=HolyStorm.Serializer:Serialize(P:GetFilter("preview-filter","global"))
local previewOk,preview=P:Preview("filters","preview-filter",{guid="Anna"},"global")
assert(previewOk,tostring(preview))
assert(preview.status==R.Result.PASS,tostring(preview.status))
assert(preview.trace[1].actual==80 and preview.trace[1].expected==80 and preview.trace[1].provider=="test-character")
assert(preview.trace[2].reason:match("UNKNOWN_FIELD"))
assert(P:GetPermissionStateStatus().revisionID==previewRevision and HolyStorm.Serializer:Serialize(P:GetFilter("preview-filter","global"))==previewBefore)

-- AB: reusable rules are independent persisted objects, and mutation permissions are enforced in Core.
assert(P:SaveRule({id="standalone-rule",name="Standalone",root={field="test.boolean",operator="true"}},"global"));assert(P:GetRule("standalone-rule","global")and P:GetFilter("standalone-rule","global")==nil)
local filterCandidate=HolyStorm.Utils.DeepCopy(P:GetFilter("preview-filter","global"));filterCandidate.name="Denied edit";local actor={accountUUID="acct-klaus",characterUUID="Klaus"};assert(not P:AuthorizeChange(state,{action="FILTER_UPSERT",filter=filterCandidate},actor));assert(not P:AuthorizeChange(state,{action="FILTER_DELETE",filterId="preview-filter"},actor));local newCandidate={id="denied-create",name="Denied",root={field="test.boolean",operator="true"}};assert(not P:AuthorizeChange(state,{action="FILTER_UPSERT",filter=newCandidate},actor))
currentGuid="Klaus";local localDenied,localDeniedReason=P:SaveFilter({id="denied-local",name="Denied local",root={field="test.boolean",operator="true"}},"local");assert(not localDenied and localDeniedReason=="PERMISSION_DENIED");currentGuid="Maristi"

-- AC: invalid names/descriptions and unsafe rule references are rejected before persistence.
assert(not P:SaveFilter({id="bad-name",name="   ",root={field="test.boolean",operator="true"}},"global"));assert(not P:SaveFilter({id="bad-description",name="Bad",description=string.rep("x",1025),root={field="test.boolean",operator="true"}},"global"));assert(P:CreateGroup({id="rule-reference",name="Rule Reference",permissions={}}));local ruleReference=P:GetGroup("rule-reference");ruleReference.ruleIds={"standalone-rule"};assert(P:SaveGroup(ruleReference));assert(not P:DeleteRule("standalone-rule","global"));ruleReference=P:GetGroup("rule-reference");ruleReference.ruleIds={};assert(P:SaveGroup(ruleReference));assert(P:DeleteRule("standalone-rule","global"))

print("Permission engine scenarios A-AC passed")
