local root=(arg[0]:gsub("tools[/\\]test_content.lua$","")).."LIVE/Holy_Storm/"
local function copy(value,seen)if type(value)~="table"then return value end;seen=seen or{};if seen[value]then return seen[value]end;local out={};seen[value]=out;for key,child in pairs(value)do out[copy(key,seen)]=copy(child,seen)end;return out end
local clock=1000;local currentGuid="A";local contentEnabled=true;local currentGuild={id="realm:guild",roster={A={rankIndex=1},B={rankIndex=2}}};local permissions={}
local locale=setmetatable({RICH_ITEM_FALLBACK="Item %s",RICH_POI_UNAVAILABLE="POI unavailable",RICH_CONTENT_UNAVAILABLE="Content unavailable",TASK_CONTENT_INDEX="Rebuild content index"},{__index=function(_,key)return key end})
local HolyStorm={db={global={installId="install-test",content={guilds={},legacyNews={old={id="old-news",title="Legacy",content="Preserved",status="published",targetRanks={},version=4,authorGuid="A"}},legacyReads={["old-news"]={A={version=4}}}}}},Data={GuildStore={},CharacterStore={},PlayerStore={}},Utils={},Policy={},Tasks={},Sync={domains={},published={},requested={}},Events={handlers={}},TwinkCore={},Logger={Write=function()end}}
function LibStub(name)if name=="AceAddon-3.0"then return{GetAddon=function()return HolyStorm end}elseif name=="AceLocale-3.0"then return{GetLocale=function()return locale end}end end
function HolyStorm.Utils.DeepCopy(value)return copy(value)end;function HolyStorm.Utils.Now()clock=clock+1;return clock end;function HolyStorm.Utils.Trim(value)return tostring(value):match("^%s*(.-)%s*$")end;function HolyStorm.Utils.TableCount(value)local n=0;for _ in pairs(value or{})do n=n+1 end;return n end;function HolyStorm.Utils.ApplyDefaults(target,defaults)target=type(target)=="table"and target or{};for key,value in pairs(defaults)do if target[key]==nil then target[key]=copy(value)end end;return target end;function HolyStorm.Utils.SafeCall(_,fn,...)local result={pcall(fn,...)};local ok=table.remove(result,1);return ok,(table.unpack or unpack)(result)end
function HolyStorm.Data.GuildStore:GetCurrent()return currentGuild end;function HolyStorm.Data.CharacterStore:Get(guid)return{name="Character-"..guid,class="Paladin"}end;function HolyStorm.Data.PlayerStore:GetCharacterOwner(guid)return"account-"..guid end
function HolyStorm.TwinkCore:GetAccountUUIDForCharacter(guid)return"account-"..guid end
function HolyStorm.Policy:IsGuildModuleEnabled()return contentEnabled end;function HolyStorm.Policy:Can(id,_,guid)return permissions[id]~=false and(guid==nil or permissions[id..":"..guid]~=false)end;function HolyStorm.Policy:GetGroup(id)return{id=id}end;function HolyStorm.Policy:GetMembershipReasons(_,_,guid)return guid=="A"and{{type="TEST"}}or{}end;function HolyStorm.Policy:ApplyFilter(id)return id=="visible-filter"end
function HolyStorm.Tasks:RegisterTaskType(id,definition)self[id]=definition end;function HolyStorm.Tasks:Queue()return true end
function HolyStorm.Sync:RegisterDomain(id,definition)self.domains[id]=definition end;function HolyStorm.Sync:Publish(domain,id)self.published[#self.published+1]={domain=domain,id=id};return true end;function HolyStorm.Sync:RequestObject(domain,id)self.requested[#self.requested+1]={domain=domain,id=id};return true end
function HolyStorm.Events:Register(event,owner,handler)self.handlers[event..owner]=handler end;function HolyStorm.Events:Emit()end
function HolyStorm:CallCapability(_,target)self.openedCharacter=target end
function UnitGUID()return currentGuid end;function GetUnitName()return"Alpha-Realm"end
C_Map={SetUserWaypoint=function(point)HolyStorm.waypoint=point end};C_SuperTrack={SetSuperTrackedUserWaypoint=function()end};UiMapPoint={CreateFromCoordinates=function(map,x,y)return{mapID=map,x=x,y=y}end};function OpenWorldMap(map)HolyStorm.openedMap=map end

assert(loadfile(root.."Data/ContentStore.lua"))();assert(loadfile(root.."Core/MapLinks.lua"))();assert(loadfile(root.."Core/RichContent.lua"))();assert(loadfile(root.."Core/Content.lua"))()
HolyStorm.RichContent:Initialize();HolyStorm.Content:Initialize();local Content=HolyStorm.Content
local migrated,count=HolyStorm.Data.ContentStore:MigrateLegacy();assert(migrated and count==1 and Content:Get("old-news").body=="Preserved"and HolyStorm.Data.ContentStore:GetRead("old-news","A").revision==4,"legacy news and personal read state migrate once");assert(not HolyStorm.Data.ContentStore:MigrateLegacy(),"legacy migration is idempotent")

local ok,guide=Content:SaveDraft({type="GUIDE",category="MOUNT",title="Mount X",body="# Route\n- Go to [[coordinate:2248,0.524,0.631|52.4, 63.1]]\n- Use |cffa335ee|Hitem:111::::::::80:70::1:2:999:888::::::|h[Test]|h|r",priority="IMPORTANT",visibility={scope="GUILD"}},0)
assert(ok and guide.id:match("^content%-")and guide.status=="DRAFT"and guide.revision==1,"stable draft creation")
local stableId=guide.id;guide.title="Renamed Mount Guide";ok,guide=Content:SaveDraft(guide,1);assert(ok and guide.id==stableId and guide.revision==2,"rename retains ID")
local stale=copy(guide);ok=Content:SaveDraft(stale,1);assert(not ok,"stale editor revision rejected")
ok,guide=Content:Publish(guide,2);assert(ok and guide.status=="PUBLISHED"and guide.publishedBy=="A","publishing is separate and audited")
permissions["guide-edit"]=false;local denied=Content:SaveDraft(guide,guide.revision);assert(not denied,"direct core edit enforces permission");permissions["guide-edit"]=nil
local resolved=Content:ResolveGuide("Renamed Mount Guide");assert(resolved and resolved.id==guide.id,"guide resolves by exact title")
local _,secondGuide=Content:SaveDraft({type="GUIDE",category="MOUNT",title="Renamed Route Companion",body="Alternative",visibility={scope="GUILD"}},0);local ambiguous,matches,reason=Content:ResolveGuide("renamed");assert(not ambiguous and reason=="AMBIGUOUS"and#matches==2,"ambiguous guide names return a deterministic choice list")
local blocks,diagnostics=HolyStorm.RichContent:Parse(guide.body);local rendered="";for _,block in ipairs(blocks)do rendered=rendered..block.text end;assert(rendered:find("Hitem:111::::::::80:70::1:2:999:888",1,true),"complete item hyperlink preserved");assert(rendered:find("holystorm:coordinate",1,true)and#diagnostics.links==1,"coordinate token rendered through registry")
local unknownBlocks,unknownDiagnostics=HolyStorm.RichContent:Parse("See [[future:abc|Future link]]");assert(unknownBlocks[1].text:find("Future link",1,true)and#unknownDiagnostics.unresolved==1,"unknown link type has readable fallback")
assert(HolyStorm.RichContent:RegisterType({type="achievement",render=function(target)return"Achievement "..target end}),"future modules can register link types");assert(HolyStorm.RichContent:MakeToken("achievement","42","Done"),"registered token creation")
assert(HolyStorm.MapLinks:OpenCoordinate(2248,.524,.631)and HolyStorm.openedMap==2248 and HolyStorm.waypoint.x==.524 and HolyStorm.MapLinks.temporaryMarker.localOnly,"coordinate opens exact map and local marker")
HolyStorm.MapLinks:RegisterPOIProvider("test",{list=function()return{{id="poi-one",name="POI One",mapID=2248,creator="A"}}end,get=function(id)return id=="poi-one"and{id=id,name="POI One",mapID=2248,x=.2,y=.3}end});local pois=HolyStorm.MapLinks:ListPOIs();assert(#pois==1 and pois[1].id=="poi-one"and HolyStorm.MapLinks:OpenPOI("poi-one"),"POI providers expose and open stable POI IDs");assert(not HolyStorm.MapLinks:OpenPOI("poi-deleted"),"deleted POIs fail gracefully")
HolyStorm.RichContent:HandleHyperlink("holystorm:character:A");assert(HolyStorm.openedCharacter=="A","character links use the central character capability")
local missing=Content:Open("content-missing");assert(not missing and HolyStorm.Sync.requested[#HolyStorm.Sync.requested].id=="content-missing","missing chat target requests content on demand")

local targeted=copy(guide);targeted.id=nil;targeted.title="Targeted";targeted.slug=nil;targeted.visibility={scope="CHARACTERS",characterIds={A=true}};targeted.revision=nil;ok,targeted=Content:SaveDraft(targeted,0);assert(ok);currentGuid="B";assert(not Content:GetVisibleById(targeted.id),"direct lookup enforces visibility");currentGuid="A"
local metadata=Content:GetIndex()[guide.id];assert(metadata and metadata.bodyLoaded and metadata.type=="GUIDE"and metadata.title==guide.title,"metadata index avoids body scans")
local detail=Content:GetDiagnostics(guide.id);assert(detail.payloadMode=="FULL"and detail.payloadSize==#guide.body and detail.syncStatus=="LOCAL"and#detail.links==1,"developer diagnostics expose payload and parsed-link state")
for i=1,1000 do HolyStorm.Data.ContentStore:Put({id="perf-"..i,guildId=Content:GetGuildId(),type="GUIDE",category="GENERAL",title=i==777 and"Indexed Needle"or("Guide "..i),slug="guide-"..i,body=string.rep("x",1000),author="Load Test",authorGuid="A",modifiedBy="A",modifiedAt=i,status="PUBLISHED",priority="NORMAL",visibility={scope="GUILD"},tags={},revision=1})end;local parse=HolyStorm.RichContent.Parse;HolyStorm.RichContent.Parse=function()error("list parsed a body")end;local searchResults=Content:List({type="GUIDE",search="indexed needle"});HolyStorm.RichContent.Parse=parse;assert(#searchResults==1 and searchResults[1].id=="perf-777","1000-guide list/search does not parse content bodies")
contentEnabled=false;assert(not Content:SaveDraft({type="NEWS",title="Disabled",body="x",visibility={scope="GUILD"}},0),"guild-wide module disable blocks creation");contentEnabled=true
ok,guide=Content:Delete(guide.id,guide.revision);assert(ok and guide.status=="DELETED"and not Content:GetVisibleById(guide.id),"delete creates hidden tombstone")
currentGuild={id="other:guild",roster={A={rankIndex=1}}};assert(Content:Get(guide.id)==nil,"content is isolated by guild identity")
local newsFile=assert(io.open(root.."Modules/News/News.lua","r"));local newsSource=newsFile:read("*a");newsFile:close();assert(newsSource:find('InputScrollFrameTemplate',1,true)and not newsSource:find('body:GetStringHeight()',1,true),"News editor must use Blizzard's scrolling EditBox contract")
print("Content model, revisions, visibility, rich links, map links and guild isolation tests passed")
