-- Offline contract tests for the Holy Storm scheduler. Run with: lua tools/test_task_workflow.lua
local root=(arg[0]:gsub("tools[/\\]test_task_workflow.lua$","")).."LIVE/Holy_Storm/"
local monotonic,epoch=0,100000
function GetTime()return monotonic end
function time()return epoch+math.floor(monotonic)end
function InCombatLockdown()return false end
local timers={}
C_Timer={NewTimer=function(delay,callback)local t={cancelled=false,due=monotonic+delay,callback=callback};function t:Cancel()self.cancelled=true end;timers[#timers+1]=t;return t end,NewTicker=function(_,callback)local t={callback=callback};function t:Cancel()self.cancelled=true end;return t end}
local HolyStorm={db={profile={taskManager={}}}}
function HolyStorm:GetAddon()return self end
function HolyStorm:GetLocale()return setmetatable({TASK_GENERIC="Task: %s"},{__index=function(_,key)return key end})end
HolyStorm.Utils={}
function HolyStorm.Utils.DeepCopy(value,seen)if type(value)~="table"then return value end;seen=seen or{};if seen[value]then return seen[value]end;local out={};seen[value]=out;for k,v in pairs(value)do out[HolyStorm.Utils.DeepCopy(k,seen)]=HolyStorm.Utils.DeepCopy(v,seen)end;return out end
function HolyStorm.Utils.Now()return time()end
function HolyStorm.Utils.SafeCall(_,fn,...)local args={...};return xpcall(function()return fn(table.unpack(args))end,function(e)return e end)end
HolyStorm.Events={listeners={}}
function HolyStorm.Events:Register(event,owner,callback)self.listeners[event]=self.listeners[event]or{};self.listeners[event][owner]=callback end
function HolyStorm.Events:Emit(event,...)for _,callback in pairs(self.listeners[event]or{})do callback(event,...)end end
HolyStorm.Logger={history={}}
function HolyStorm.Logger:Write(level,source,category,message,context,correlationId)self.history[#self.history+1]={level=level,source=source,category=category,message=message,context=context,correlationId=correlationId}end
HolyStorm.State={values={playerLoggedIn=true,playerReady=true,guildAvailable=true,guildRosterReady=false}}
function HolyStorm.State:Is(key)return self.values[key]==true end
function HolyStorm.State:Get(key)return self.values[key]end
function LibStub()return HolyStorm end
assert(loadfile(root.."Core/Tasks/TaskManager.lua"))()
assert(loadfile(root.."Core/Workflows/WorkflowManager.lua"))()
assert(loadfile(root.."Core/Serialization/Serializer.lua"))()
HolyStorm.Events.listeners.PLAYER_LOGIN={}
HolyStorm.PlayerData={FingerprintSnapshot=function(_,value)
 local ignored={version=true,updatedAt=true,committedAt=true,receivedAt=true,originCreatedAt=true,receivedFrom=true,transport=true,transportMetadata=true,syncMetadata=true,schemaVersion=true,snapshotVersion=true}
 local function comparable(item,isRoot)if type(item)~="table"then return item end;local out={};for key,child in pairs(item)do if not(isRoot and ignored[key])then out[key]=comparable(child,false)end end;return out end
 return HolyStorm.Serializer:Serialize(comparable(value,true))
end}
assert(loadfile(root.."Persistence/SnapshotManager.lua"))()
HolyStorm.Tasks:Initialize();HolyStorm.Workflows:Initialize()
local function processAll(limit)for _=1,limit or 100 do if#HolyStorm.Tasks.queue==0 and not HolyStorm.Tasks.runningTaskId then return end;HolyStorm.Tasks.timer,HolyStorm.Tasks.timerDue=nil,nil;HolyStorm.Tasks:Process();local earliest;for _,task in ipairs(HolyStorm.Tasks.queue)do if task.blockReason=="DEBOUNCE"then earliest=earliest and math.min(earliest,task.notBefore)or task.notBefore end end;if earliest and earliest>monotonic then monotonic=earliest end end;local pending={};for _,task in ipairs(HolyStorm.Tasks.queue)do local dep=task.dependencies and task.dependencies[1];pending[#pending+1]=task.registryId..":"..tostring(task.blockReason).." dep="..tostring(dep).." depStatus="..tostring(dep and HolyStorm.Tasks.tasks[dep]and HolyStorm.Tasks.tasks[dep].status)end;error("scheduler did not drain: "..table.concat(pending,","))end

assert(HolyStorm.Tasks:RegisterTaskType("Test.Unique",{execute=function()return true end,executionMode="UNIQUE"}))
local a=HolyStorm.Tasks:Queue("Test.Unique",{triggerSource="A"});local b,state=HolyStorm.Tasks:Queue("Test.Unique",{triggerSource="B"});assert(a==b and state=="MERGED"and HolyStorm.Tasks.tasks[a].triggerCount==2);processAll()
assert(HolyStorm.Tasks:RegisterTaskType("Test.Multi",{execute=function()return true end,executionMode="MULTI"}));local m1=HolyStorm.Tasks:Queue("Test.Multi");local m2=HolyStorm.Tasks:Queue("Test.Multi");assert(m1~=m2);processAll()
assert(HolyStorm.Tasks:RegisterTaskType("Test.Diagnostics",{module="Comms",execute=function()return true end,executionMode="MULTI"}));local diagnosticTask=HolyStorm.Tasks:Queue("Test.Diagnostics",{metadata={packet={payload="must-not-be-logged",diagnostics={direction="SEND",transmissionId="tx-task",correlationId="corr-task",packetPart=2,packetTotal=4,bytes=220,channel="GUILD",domain="character",objectId="Player-Test",messageKind="PAYLOAD",version=7}},privateValue="must-not-be-logged"}});local diagnosticLog;for _,entry in ipairs(HolyStorm.Logger.history)do if entry.message=="Task requested: Test.Diagnostics"then diagnosticLog=entry end end;assert(diagnosticTask and diagnosticLog and diagnosticLog.context.direction=="SEND"and diagnosticLog.context.transmissionId=="tx-task"and diagnosticLog.context.packetPart==2 and diagnosticLog.context.packetTotal==4,"compact task diagnostics are propagated");assert(diagnosticLog.context.payload==nil and diagnosticLog.context.packet==nil and diagnosticLog.context.privateValue==nil,"task diagnostics leaked task metadata");processAll()
assert(HolyStorm.Tasks.tasks[diagnosticTask].metadata.packet==nil and HolyStorm.Tasks.tasks[diagnosticTask].metadata.transmissionId=="tx-task"and HolyStorm.Tasks.tasks[diagnosticTask].callback==nil,"completed task history must release packet payloads while retaining compact diagnostics")
assert(HolyStorm.Tasks:RegisterTaskType("Test.Key",{execute=function()return true end,executionMode="MERGE_BY_KEY"}));local k1=HolyStorm.Tasks:Queue("Test.Key",{mergeKey=15});local k2=HolyStorm.Tasks:Queue("Test.Key",{mergeKey=15});local k3=HolyStorm.Tasks:Queue("Test.Key",{mergeKey=22});assert(k1==k2 and k1~=k3);processAll()
local order={};HolyStorm.Tasks:RegisterTaskType("Test.Low",{priority=75,execute=function()order[#order+1]="low"end});HolyStorm.Tasks:RegisterTaskType("Test.High",{priority=10,execute=function()order[#order+1]="high"end});HolyStorm.Tasks:Queue("Test.Low");HolyStorm.Tasks:Queue("Test.High");processAll();assert(order[1]=="high"and order[2]=="low")
HolyStorm.State.values.playerReady=false;HolyStorm.Tasks:RegisterTaskType("Test.Blocked",{conditions={"PLAYER_READY"},priority=0,execute=function()error("must remain blocked")end});HolyStorm.Tasks:RegisterTaskType("Test.Runnable",{priority=50,execute=function()order[#order+1]="runnable"end});local blocked=HolyStorm.Tasks:Queue("Test.Blocked");HolyStorm.Tasks:Queue("Test.Runnable");HolyStorm.Tasks.timer=nil;HolyStorm.Tasks:Process();assert(HolyStorm.Tasks.tasks[blocked].status=="BLOCKED"and order[#order]=="runnable");HolyStorm.Tasks:Cancel(blocked);HolyStorm.State.values.playerReady=true
HolyStorm.Tasks:RegisterTaskType("Test.GuildRosterCondition",{conditions={"GUILD_ROSTER_READY"},execute=function()return true end});local rosterTaskId=HolyStorm.Tasks:Queue("Test.GuildRosterCondition");local rosterTask=HolyStorm.Tasks.tasks[rosterTaskId];local rosterReady,rosterReason=HolyStorm.Tasks:CheckConditions(rosterTask);assert(not rosterReady and rosterReason=="GUILD_ROSTER_READY","a known false guild-roster state waits by its value, not as an unknown condition");HolyStorm.State.values.guildRosterReady=true;rosterReady,rosterReason=HolyStorm.Tasks:CheckConditions(rosterTask);assert(rosterReady and not rosterReason,"GUILD_ROSTER_READY becomes runnable when GuildStore marks its state ready")
local dep=HolyStorm.Tasks:Queue("Test.Unique");local dependent=HolyStorm.Tasks:Queue("Test.Multi",{dependencies={dep}});processAll();assert(HolyStorm.Tasks.tasks[dependent].status=="COMPLETED")
HolyStorm.Tasks:RegisterTaskType("Test.Error",{execute=function()error("isolated")end});local failure=HolyStorm.Tasks:Queue("Test.Error");HolyStorm.Tasks:Queue("Test.Unique");processAll();assert(HolyStorm.Tasks.tasks[failure].status=="FAILED")
assert(HolyStorm.Tasks:GetTaskType("Test.Error").maxRetries==3,"default retry limit must be three")
HolyStorm.Tasks:RegisterTaskType("Test.Async",{execute=function()return HolyStorm.Tasks.ASYNC end});local async=HolyStorm.Tasks:Queue("Test.Async");HolyStorm.Tasks.timer=nil;HolyStorm.Tasks:Process();assert(HolyStorm.Tasks.tasks[async].status=="WAITING_ASYNC");assert(HolyStorm.Tasks:Complete(async,true,{ready=true}))
HolyStorm.Tasks:RegisterTaskType("Test.TimeoutAsync",{timeoutSeconds=2,execute=function()return HolyStorm.Tasks.ASYNC end});local delayedAsync=HolyStorm.Tasks:Queue("Test.TimeoutAsync",{delay=5});HolyStorm.Tasks.timer=nil;HolyStorm.Tasks:Process();assert(HolyStorm.Tasks.tasks[delayedAsync].status=="WAITING"and HolyStorm.Tasks.tasks[delayedAsync].timeoutTimer==nil,"queue wait does not consume task execution timeout");monotonic=HolyStorm.Tasks.tasks[delayedAsync].notBefore;HolyStorm.Tasks.timer=nil;HolyStorm.Tasks:Process();local asyncTimeout=HolyStorm.Tasks.tasks[delayedAsync].timeoutTimer;assert(HolyStorm.Tasks.tasks[delayedAsync].status=="WAITING_ASYNC"and asyncTimeout and asyncTimeout.due==monotonic+2,"async timeout starts when task execution begins");monotonic=asyncTimeout.due;asyncTimeout.callback();assert(HolyStorm.Tasks.tasks[delayedAsync].status=="FAILED"and HolyStorm.Tasks.tasks[delayedAsync].lastError=="TASK_TIMEOUT"and HolyStorm.Tasks.runningTaskId==nil,"an uncompleted async task times out cleanly")
HolyStorm.Tasks:Pause();local paused=HolyStorm.Tasks:Queue("Test.Multi");HolyStorm.Tasks:Process();assert(HolyStorm.Tasks.tasks[paused].status=="QUEUED");HolyStorm.Tasks:Resume();processAll()
local requested=false;HolyStorm.Tasks:RegisterTaskType("WF.One",{executionMode="MULTI",execute=function(task)if not requested then requested=true;HolyStorm.Workflows:Request("TEST_WORKFLOW",{triggerSource="DURING_RUN"})end;return 1 end});HolyStorm.Tasks:RegisterTaskType("WF.Two",{executionMode="MULTI",execute=function()return 2 end});assert(HolyStorm.Workflows:Register("TEST_WORKFLOW",{allowParallel=false,steps={{id="one",taskType="WF.One"},{id="two",taskType="WF.Two"}}}));local wf=HolyStorm.Workflows:Request("TEST_WORKFLOW",{triggerSource="TEST"});processAll();assert(HolyStorm.Workflows.workflows[wf].status=="COMPLETED"and#HolyStorm.Workflows.history==2)
local retries=0;HolyStorm.Tasks:RegisterTaskType("WF.Retry",{executionMode="MULTI",execute=function()retries=retries+1;if retries==1 then return{workflowAction="RETRY",gotoStep=1,delay=.1,maxRetries=2}end;return true end});HolyStorm.Workflows:Register("RETRY_WORKFLOW",{steps={{id="retry",taskType="WF.Retry"}}});local retryWorkflow=HolyStorm.Workflows:Request("RETRY_WORKFLOW");processAll();assert(retries==2 and HolyStorm.Workflows.workflows[retryWorkflow].status=="COMPLETED")
local skipped=false;HolyStorm.Tasks:RegisterTaskType("WF.Fail",{executionMode="MULTI",execute=function()error("expected")end});HolyStorm.Tasks:RegisterTaskType("WF.After",{executionMode="MULTI",execute=function()skipped=true end});HolyStorm.Workflows:Register("SKIP_WORKFLOW",{steps={{id="fail",taskType="WF.Fail",failurePolicy="SKIP"},{id="after",taskType="WF.After"}}});local skipWorkflow=HolyStorm.Workflows:Request("SKIP_WORKFLOW");processAll();assert(skipped and HolyStorm.Workflows.workflows[skipWorkflow].status=="COMPLETED")
local lastKnownGood={seasonId=18,overallScore=2500,dungeons={{name="Stable"}}};local invalidScans,commits=0,0;local queued,invalidWorkflow=HolyStorm.Snapshots:Queue("mythicplus-lkg",function()invalidScans=invalidScans+1;return{seasonId=18,dungeons=nil}end,function(snapshot)return type(snapshot.dungeons)=="table","dungeon pool unavailable"end,function(snapshot)commits=commits+1;lastKnownGood=snapshot;return true end,{delay=0,retryDelay=.1,maxRetries=2});assert(queued);processAll();assert(HolyStorm.Workflows.workflows[invalidWorkflow].status=="FAILED"and invalidScans==3 and commits==0 and lastKnownGood.overallScore==2500,"retry exhaustion never commits an invalid snapshot over last-known-good data")
local sawWorkflowError=false;for _,entry in ipairs(HolyStorm.Logger.history)do if entry.level=="ERROR"and entry.context and entry.context.workflowId==invalidWorkflow then sawWorkflowError=true end end;assert(sawWorkflowError,"retry exhaustion is logged as a failed workflow")
local fresh={seasonId=18,overallScore=2600,dungeons={{name="Fresh"}}};local freshQueued,freshWorkflow=HolyStorm.Snapshots:Queue("mythicplus-lkg",function()return fresh end,function()return true end,function(snapshot)commits=commits+1;lastKnownGood=snapshot;return true end,{delay=0});assert(freshQueued);processAll();assert(HolyStorm.Workflows.workflows[freshWorkflow].status=="COMPLETED"and commits==1 and lastKnownGood.overallScore==2600,"a later valid snapshot commits normally after retry exhaustion")
local retryScanCount,retryCommitCount=0,0;local retrySuccess,retrySuccessWorkflow=HolyStorm.Snapshots:Queue("fresh-retry",function()retryScanCount=retryScanCount+1;return retryScanCount==1 and{invalid=true}or{valid=true,value=3}end,function(snapshot)return snapshot.valid==true,"TRANSIENT_INVALID"end,function(snapshot)assert(snapshot.value==3);retryCommitCount=retryCommitCount+1;return true end,{delay=0,maxRetries=2});assert(retrySuccess);processAll();assert(HolyStorm.Workflows.workflows[retrySuccessWorkflow].status=="COMPLETED"and retryScanCount==2 and retryCommitCount==1,"a retry performs a new scan and commits only its valid result")
local readinessScans,readinessCommits,readinessDiagnostics=0,0,{};local readinessQueued,readinessWorkflow=HolyStorm.Snapshots:Queue("readiness-retry",function()readinessScans=readinessScans+1;return nil,"DUNGEON_POOL_NOT_READY",{retryable=true,season=18,rating=2500,maps=0}end,function(snapshot,reason,diagnostics,retryCount,maxRetries)assert(snapshot==nil and reason=="DUNGEON_POOL_NOT_READY"and diagnostics.season==18 and retryCount<=maxRetries);return false,reason,diagnostics.retryable end,function()readinessCommits=readinessCommits+1;return true end,{delay=0,maxRetries=2,retryDelay=.1,onValidationFailure=function(reason,disposition,retryCount,maxRetries,diagnostics)readinessDiagnostics[#readinessDiagnostics+1]={reason=reason,disposition=disposition,retryCount=retryCount,maxRetries=maxRetries,maps=diagnostics.maps}end});assert(readinessQueued);processAll();assert(HolyStorm.Workflows.workflows[readinessWorkflow].status=="FAILED"and readinessScans==3 and readinessCommits==0,"readiness retries are bounded and carry collection reasons without committing unknown data");assert(readinessDiagnostics[1].disposition=="RETRY"and readinessDiagnostics[1].reason=="DUNGEON_POOL_NOT_READY"and readinessDiagnostics[3].disposition=="FAIL"and readinessDiagnostics[3].retryCount==2,"validation diagnostics identify retry status and final exhaustion")
local permanentScans,permanentDiagnostics=0,{};local permanentQueued,permanentWorkflow=HolyStorm.Snapshots:Queue("permanent-invalid",function()permanentScans=permanentScans+1;return nil,"INVALID_BEST_RUN_COMPLETION_DATE",{retryable=false,mapId=4}end,function(snapshot,reason,diagnostics)return false,reason,diagnostics.retryable end,function()error("invalid scan must not commit")end,{delay=0,maxRetries=3,onValidationFailure=function(reason,disposition,_,_,diagnostics)permanentDiagnostics[#permanentDiagnostics+1]={reason=reason,disposition=disposition,mapId=diagnostics.mapId}end});assert(permanentQueued);processAll();assert(HolyStorm.Workflows.workflows[permanentWorkflow].status=="FAILED"and permanentScans==1 and permanentDiagnostics[1].reason=="INVALID_BEST_RUN_COMPLETION_DATE"and permanentDiagnostics[1].disposition=="FAIL"and permanentDiagnostics[1].mapId==4,"permanent malformed API data fails immediately with its stable reason ID")
local unchangedWorkflowQueued,unchangedWorkflow=HolyStorm.Snapshots:Queue("unchanged-result",function()return{value=3}end,function()return true end,function()return false,"UNCHANGED"end,{delay=0});assert(unchangedWorkflowQueued);processAll();assert(HolyStorm.Workflows.workflows[unchangedWorkflow].status=="COMPLETED","UNCHANGED ends a successful workflow")
local failedCommitQueued,failedCommitWorkflow=HolyStorm.Snapshots:Queue("failed-commit",function()return{value=4}end,function()return true end,function()return false,"STORE_FAILED"end,{delay=0});assert(failedCommitQueued);processAll();assert(HolyStorm.Workflows.workflows[failedCommitWorkflow].status=="FAILED","a failed persistence commit cannot be reported as a successful workflow")
local chunkCalls,chunkValidations,chunkCommits,chunkRunIds=0,0,0,{};local chunkedSnapshot={seasonId=18,dungeons={{name="Chunked"}}};local chunkQueued,chunkWorkflow=HolyStorm.Snapshots:Queue("chunked",function()chunkCalls=chunkCalls+1;chunkRunIds[#chunkRunIds+1]=HolyStorm.Tasks.tasks[HolyStorm.Tasks.runningTaskId].workflowId;if chunkCalls<4 then return{workflowAction="GOTO",gotoStep=1,delay=0}end;return chunkedSnapshot end,function(snapshot)chunkValidations=chunkValidations+1;return snapshot==chunkedSnapshot end,function(snapshot)chunkCommits=chunkCommits+1;assert(snapshot==chunkedSnapshot);return true end,{delay=0});assert(chunkQueued);processAll();assert(chunkCalls==4 and chunkValidations==1 and chunkCommits==1 and HolyStorm.Workflows.workflows[chunkWorkflow].status=="COMPLETED","snapshot scans can yield through central Tasks and validate/commit only after completion");for _,runId in ipairs(chunkRunIds)do assert(runId==chunkWorkflow,"scan chunks retain one workflow ID")end
local completedWorkflow=HolyStorm.Workflows.workflows[freshWorkflow];assert(completedWorkflow.context==nil and completedWorkflow.definition==nil and completedWorkflow.restartOptions==nil,"completed workflow history must release snapshot context and restart options")
for _,task in pairs(HolyStorm.Tasks.tasks)do if task.workflowId==freshWorkflow and task.registryId:match("%.Scan$")then assert(type(task.result)=="table"and task.result.snapshot==nil,"completed task history must release scanned snapshots")end end
local fingerprintA=HolyStorm.Snapshots:Fingerprint({version=1,updatedAt=10,snapshotVersion=2,nested={value=true}});local fingerprintB=HolyStorm.Snapshots:Fingerprint({version=9,updatedAt=99,snapshotVersion=8,nested={value=true}});assert(fingerprintA==fingerprintB,"fingerprinting must omit volatile top-level fields without copying the full snapshot")
local agedOrder={};HolyStorm.Tasks:RegisterTaskType("Test.AgedLowPriority",{priority=30,executionMode="MULTI",execute=function()agedOrder[#agedOrder+1]="aged"end});HolyStorm.Tasks:RegisterTaskType("Test.NewHighPriority",{priority=25,executionMode="MULTI",execute=function()agedOrder[#agedOrder+1]="new"end});local agedTask=HolyStorm.Tasks:Queue("Test.AgedLowPriority");monotonic=monotonic+330;local newTask=HolyStorm.Tasks:Queue("Test.NewHighPriority");local agedQueue=HolyStorm.Tasks:GetQueue();assert(agedQueue[1].uniqueId==agedTask and agedQueue[2].uniqueId==newTask,"priority aging still promotes long-waiting work");processAll();assert(agedOrder[1]=="aged","aged tasks retain their effective priority when selected")
local sortCalls=0;local originalSort=table.sort;table.sort=function(...)sortCalls=sortCalls+1;return originalSort(...)end
local bulkBlocked,bulkReady,badRuns,readyRuns={},nil,0,0;HolyStorm.Tasks:RegisterTaskType("Test.BulkBlocked",{priority=1,executionMode="MULTI",conditions={function()return false end},execute=function()badRuns=badRuns+1 end});HolyStorm.Tasks:RegisterTaskType("Test.BulkReady",{priority=90,execute=function()readyRuns=readyRuns+1 end});HolyStorm.Tasks:RegisterTaskType("Test.BulkHigh",{priority=0,execute=function()order[#order+1]="inserted-high"end})
for _=1,130 do bulkBlocked[#bulkBlocked+1]=HolyStorm.Tasks:Queue("Test.BulkBlocked")end;bulkReady=HolyStorm.Tasks:Queue("Test.BulkReady");local inserted=HolyStorm.Tasks:Queue("Test.BulkHigh");assert(sortCalls==0,"queue insertion must defer full ordering until the scheduler turn");table.sort=originalSort
HolyStorm.Tasks:Process();assert(order[#order]=="inserted-high"and readyRuns==0,"a newly queued high-priority task preempts an incomplete lower-priority scan");assert(HolyStorm.Tasks.lastProcessMetrics.queueChecks<=64,"one scheduler turn inspects no more than its queue-check budget")
for _=1,5 do if readyRuns>0 then break end;HolyStorm.Tasks.timer,HolyStorm.Tasks.timerDue=nil,nil;HolyStorm.Tasks:Process();assert(HolyStorm.Tasks.lastProcessMetrics.queueChecks<=64,"continued selection remains bounded per scheduler turn")end;assert(readyRuns==1 and badRuns==0,"bounded queue scans continue until the next runnable task without starvation")
for _,id in ipairs(bulkBlocked)do HolyStorm.Tasks:Cancel(id,"TEST_CLEANUP")end
local wakeRuns=0;HolyStorm.Tasks:RegisterTaskType("Test.WakeCoalesce",{execute=function()wakeRuns=wakeRuns+1 end});HolyStorm.Tasks:Queue("Test.WakeCoalesce");for _=1,100 do HolyStorm.Events:Emit("HS_STATE_CHANGED","playerReady",true,false)end;HolyStorm.Tasks:Process();local wakeSummaries=0;local summary;for _,entry in ipairs(HolyStorm.Logger.history)do if entry.message=="Scheduler wakes coalesced"then wakeSummaries=wakeSummaries+1;summary=entry.context end end;assert(wakeRuns==1 and wakeSummaries==1 and summary.triggerCount==100 and summary.triggerSources["HS_STATE_CHANGED:playerReady"]==100,"repeated identical state changes coalesce into one scheduler turn")
local childRan,parentRan=false,false;HolyStorm.Tasks:RegisterTaskType("Test.ReentrantChild",{execute=function()childRan=true end});HolyStorm.Tasks:RegisterTaskType("Test.ReentrantParent",{execute=function()parentRan=true;HolyStorm.Events:Emit("HS_STATE_CHANGED","playerReady",true,false);HolyStorm.Tasks:Queue("Test.ReentrantChild");HolyStorm.Tasks:Process()end});HolyStorm.Tasks:Queue("Test.ReentrantParent");HolyStorm.Tasks:Process();assert(parentRan and not childRan and#HolyStorm.Tasks.queue==1,"events and task requests during callback cannot reenter the scheduler");processAll();assert(childRan,"the queued task advances on a later scheduler turn")
assert(HolyStorm.Tasks:GetDiagnostics().history==#HolyStorm.Tasks.history and HolyStorm.Workflows:GetDiagnostics().history==#HolyStorm.Workflows.history,"bounded scheduler diagnostics expose current history sizes")
local delayedMetrics=HolyStorm.Tasks:GetPerformance()["Test.TimeoutAsync"];assert(delayedMetrics and delayedMetrics.averageQueueWait>=5 and delayedMetrics.averageDuration<delayedMetrics.averageQueueWait,"queue wait is reported separately from callback execution and async wait")
local taskMetrics=HolyStorm.Tasks:GetRuntimeMetrics();assert(taskMetrics.tasks.requested>0 and taskMetrics.tasks.started>0 and taskMetrics.tasks.completed>0 and taskMetrics.tasks.failed>0 and taskMetrics.tasks.cancelled>0 and taskMetrics.tasks.retried>0,"task lifecycle counters include requests, starts, outcomes, cancellations and retries")
assert(taskMetrics.scheduler.runs>0 and taskMetrics.scheduler.queueScans>0 and taskMetrics.scheduler.queueChecks>0 and taskMetrics.scheduler.tasksSelected>0 and taskMetrics.scheduler.coalescedWakes>0 and taskMetrics.scheduler.idleTransitions>0,"scheduler counters cover actual runs, scans, selection, coalescing and idle transitions")
assert(HolyStorm.Workflows:Register("TEST_CANCEL",{module="CancelTest",steps={{id="pending",taskType="Test.Multi"}}}));local cancelledWorkflow=HolyStorm.Workflows:Request("TEST_CANCEL",{triggerSource="MAINTENANCE_CANCEL_TEST"});assert(cancelledWorkflow and HolyStorm.Workflows:Cancel(cancelledWorkflow,"METRIC_TEST"),"workflow cancellation is recorded from the central lifecycle")
local workflowMetrics=HolyStorm.Workflows:GetRuntimeMetrics();assert(workflowMetrics.requested>0 and workflowMetrics.started>0 and workflowMetrics.completed>0 and workflowMetrics.failed>0 and workflowMetrics.cancelled>0 and next(workflowMetrics.byModule)and workflowMetrics.byTrigger["MAINTENANCE:MAINTENANCE_CANCEL_TEST"].cancelled==1,"workflow lifecycle counters retain module and trigger attribution")
local manualId=HolyStorm.Tasks:Queue("Test.Multi",{triggerSource="MANUAL_COMMAND"});assert(manualId and HolyStorm.Tasks:Cancel(manualId,"METRIC_TEST"));local blizzardId=HolyStorm.Tasks:Queue("Test.Multi",{triggerSource="PLAYER_LOGIN"});assert(blizzardId and HolyStorm.Tasks:Cancel(blizzardId,"METRIC_TEST"))
taskMetrics=HolyStorm.Tasks:GetRuntimeMetrics();assert(taskMetrics.tasks.byTrigger["USER:MANUAL_COMMAND"].requested==1 and taskMetrics.tasks.byTrigger["BLIZZARD_EVENT:PLAYER_LOGIN"].requested==1,"task triggers retain category and trigger-name attribution")
local taskHistoryCount,workflowHistoryCount,logHistoryCount,timerCount=#HolyStorm.Tasks.history,#HolyStorm.Workflows.history,#HolyStorm.Logger.history,#timers;assert(HolyStorm.Tasks:ResetRuntimeMetrics());assert(HolyStorm.Tasks:GetRuntimeMetrics().tasks.requested==0 and HolyStorm.Tasks:GetRuntimeMetrics().scheduler.runs==0 and next(HolyStorm.Tasks.performance)==nil and#timers==timerCount,"runtime metric reset clears task and scheduler aggregates without creating scheduler work");assert(#HolyStorm.Tasks.history==taskHistoryCount and#HolyStorm.Workflows.history==workflowHistoryCount and#HolyStorm.Logger.history==logHistoryCount,"runtime metric reset preserves task/workflow history and logs")
HolyStorm.Tasks:BeginStartup("OBSERVABILITY_TEST");local startupTask=HolyStorm.Tasks:Queue("Test.Unique",{triggerSource="MAINTENANCE_STARTUP_TEST"});processAll();local startupMetrics=HolyStorm.Tasks:GetStartupMetrics();assert(startupTask and startupMetrics.active and startupMetrics.tasksRequested==1 and startupMetrics.tasksStarted==1 and startupMetrics.tasksCompleted==1 and startupMetrics.schedulerRuns==1,"startup window measures task lifecycle and scheduler runs without a separate timer");local startupStartedAt=startupMetrics.startedAt;assert(HolyStorm.Tasks:ResetRuntimeMetrics()and HolyStorm.Tasks.startup.active and HolyStorm.Tasks.startup.startedAt==startupStartedAt and HolyStorm.Tasks:GetStartupMetrics().tasksRequested==0,"runtime reset clears startup counters but preserves its lightweight measurement window")
print("Task/workflow tests passed")

-- Same-task continuations retain callback/context and have one lifecycle. A
-- scheduler backlog or repeated Process call in one frame must never burst.
local slices,contextRef=0,{}
HolyStorm.Tasks:RegisterTaskType("Test.Continuation",{executionMode="MULTI",execute=function(task)
 slices=slices+1;assert(task.uniqueId==contextRef.id)
 if slices<4 then return HolyStorm.Tasks:Yield(task)end
 return "done"
end})
contextRef.id=HolyStorm.Tasks:Queue("Test.Continuation")
HolyStorm.Tasks:Process();assert(slices==1)
for _=1,10 do HolyStorm.Tasks:Process()end;assert(slices==1,"same frame cannot dispatch a second slice")
monotonic=monotonic+100;HolyStorm.Tasks:Process();assert(slices==2)
for _=1,10 do HolyStorm.Tasks:Process()end;assert(slices==2,"late continuations cannot catch up")
processAll()
local continuationPerf=HolyStorm.Tasks:GetPerformance()["Test.Continuation"]
assert(slices==4 and continuationPerf.requested==1 and continuationPerf.started==1 and continuationPerf.completed==1)

local signalCalls=0
HolyStorm.Tasks:RegisterTaskType("Test.Signal",{execute=function(task)signalCalls=signalCalls+1;if signalCalls==1 then return HolyStorm.Tasks:WaitForResume(task,.5)end;return true end})
local signalId=HolyStorm.Tasks:Queue("Test.Signal");processAll()
assert(HolyStorm.Tasks.suspendedCount==1 and not HolyStorm.Tasks:IsIdle()and not HolyStorm.Tasks.runningTaskId)
local unrelated=HolyStorm.Tasks:Queue("Test.Multi");processAll();assert(HolyStorm.Tasks.tasks[unrelated].status=="COMPLETED","a suspended task releases the scheduler")
HolyStorm.Tasks:Pause();assert(HolyStorm.Tasks:ResumeTask(signalId));assert(not HolyStorm.Tasks:ResumeTask(signalId),"duplicate signal does not duplicate the queue entry")
assert(HolyStorm.Tasks.suspendedCount==0);HolyStorm.Tasks:Process();assert(signalCalls==1)
HolyStorm.Tasks:Resume();processAll();assert(signalCalls==2 and HolyStorm.Tasks.tasks[signalId].status=="COMPLETED")
local timeoutId=HolyStorm.Tasks:Queue("Test.Signal",{executionMode="MULTI",execute=function(task)return HolyStorm.Tasks:WaitForResume(task,.5)end});processAll()
local timeoutTask=HolyStorm.Tasks.tasks[timeoutId];assert(timeoutTask.timeoutTimer)
timeoutTask.timeoutTimer.callback();assert(timeoutTask.status=="FAILED"and timeoutTask.lastError=="TASK_TIMEOUT"and HolyStorm.Tasks.suspendedCount==0)
local cancelId=HolyStorm.Tasks:Queue("Test.Signal",{executionMode="MULTI",execute=function(task)return HolyStorm.Tasks:WaitForResume(task,.5)end});processAll();HolyStorm.Tasks:CancelAll();assert(HolyStorm.Tasks.tasks[cancelId].status=="CANCELLED"and HolyStorm.Tasks.suspendedCount==0)

-- A yielded first step has already started; later workflow requests coalesce
-- one follow-up instead of mutating its debounce or replacing its context.
local workflowSlices=0
HolyStorm.Tasks:RegisterTaskType("Test.YieldStep",{execute=function(task)workflowSlices=workflowSlices+1;if workflowSlices==1 then return HolyStorm.Tasks:Yield(task)end;return true end})
HolyStorm.Workflows:Register("YIELD_WORKFLOW",{steps={{id="yield",taskType="Test.YieldStep"}}})
local yieldWorkflow=HolyStorm.Workflows:Request("YIELD_WORKFLOW");HolyStorm.Tasks:Process()
local _,requestState=HolyStorm.Workflows:Request("YIELD_WORKFLOW")
assert(requestState=="RESTART_PENDING"and HolyStorm.Workflows.workflows[yieldWorkflow].pendingRestart)
processAll();assert(workflowSlices==3)
print("Task continuation, frame guard, async resume/timeout/cancel and workflow coalescing tests passed")

local workflowSignalCalls=0
HolyStorm.Tasks:RegisterTaskType("Test.WorkflowSignal",{execute=function(task)workflowSignalCalls=workflowSignalCalls+1;if workflowSignalCalls==1 then return HolyStorm.Tasks:WaitForResume(task,2)end;return true end})
HolyStorm.Workflows:Register("SIGNAL_WORKFLOW",{steps={{id="signal",taskType="Test.WorkflowSignal"}}})
local signalWorkflow=HolyStorm.Workflows:Request("SIGNAL_WORKFLOW");processAll()
local signalW=HolyStorm.Workflows.workflows[signalWorkflow];assert(signalW.status=="WAITING_ASYNC")
HolyStorm.Tasks:Pause();assert(signalW.status=="PAUSED")
assert(HolyStorm.Tasks:ResumeTask(signalW.currentTaskId)and signalW.status=="PAUSED","a readiness signal must not unpause a workflow")
HolyStorm.Tasks:Resume();processAll();assert(signalW.status=="COMPLETED"and workflowSignalCalls==2)
print("A resumed async workflow preserves queue pause state")
