local root=(arg[0]:gsub("tools[/\\]test_mythicplus.lua$","")).."LIVE/Holy_Storm/"
local Module={};local registeredEvents={};local capabilities={};local requested={affixes=0,maps=0,rewards=0};local workflows={created=0,merged=0,active=false,queueCalls=0}
local HolyStorm={Utils={Now=function()return 100 end},Data={CharacterStore={}},Snapshots={},Events={}}
local registeredMetadata
function HolyStorm:RegisterModule(metadata,callback)registeredMetadata=metadata;callback(Module)end
function HolyStorm:ApplyModuleMetadata()end
function HolyStorm:RegisterCapability(_,name,handler)capabilities[name]=handler end
function HolyStorm.Data.CharacterStore:GetBlock()end
function HolyStorm.Data.CharacterStore:SetMythicPlus()return true end
function HolyStorm.Snapshots:Queue(_,scanner,validator,commit,options)workflows.queueCalls=workflows.queueCalls+1;workflows.scanner,workflows.validator,workflows.commit=scanner,validator,commit;workflows.lastDelay=options.delay;if workflows.active then workflows.merged=workflows.merged+1;return true,"MERGED"end;workflows.active=true;workflows.created=workflows.created+1;return true,"wf-"..workflows.created end
function HolyStorm.Snapshots:Cancel()end
function HolyStorm.Events:Register(event,_,callback)registeredEvents[event]=callback end
function HolyStorm.Events:UnregisterOwner()end
function LibStub(name)if name=="AceAddon-3.0"then return{GetAddon=function()return HolyStorm end}elseif name=="AceLocale-3.0"then return{GetLocale=function()return setmetatable({},{__index=function(_,key)return key end})end}end end
function UnitGUID()return"A"end
C_ChallengeMode={GetOverallDungeonScore=function()return 1128 end,GetMapTable=function()return{1,2}end,GetMapUIInfo=function(id)return"Dungeon "..id,100+id,1800,200+id,300+id,400+id end,GetAffixInfo=function(id)return"Affix "..id,"Description",500+id end}
C_MythicPlus={GetCurrentSeason=function()return 18 end,GetCurrentUIDisplaySeason=function()return 2 end,RequestCurrentAffixes=function()requested.affixes=requested.affixes+1;if registeredEvents.MYTHIC_PLUS_CURRENT_AFFIX_UPDATE then registeredEvents.MYTHIC_PLUS_CURRENT_AFFIX_UPDATE("MYTHIC_PLUS_CURRENT_AFFIX_UPDATE")end end,RequestMapInfo=function()requested.maps=requested.maps+1;if registeredEvents.CHALLENGE_MODE_MAPS_UPDATE then registeredEvents.CHALLENGE_MODE_MAPS_UPDATE("CHALLENGE_MODE_MAPS_UPDATE")end end,RequestRewards=function()requested.rewards=requested.rewards+1;if registeredEvents.MYTHIC_PLUS_NEW_WEEKLY_RECORD then registeredEvents.MYTHIC_PLUS_NEW_WEEKLY_RECORD("MYTHIC_PLUS_NEW_WEEKLY_RECORD")end end,GetCurrentAffixes=function()return{{id=9}}end,GetOwnedKeystoneLevel=function()return 4 end,GetOwnedKeystoneChallengeMapID=function()return 1 end,GetOwnedKeystoneMapID=function()return 401 end,GetSeasonBestForMap=function()end,GetSeasonBestAffixScoreInfoForMap=function()end}
assert(loadfile(root.."Modules/MythicPlus/MythicPlus.lua"))()
assert(registeredMetadata and registeredMetadata.id=="mythicPlus" and registeredMetadata.name=="MythicPlus" and registeredMetadata.displayName=="DISPLAY_NAME" and registeredMetadata.description=="DESCRIPTION" and registeredMetadata.version=="2.1.2" and registeredMetadata.moduleType=="feature" and registeredMetadata.category=="optional","MythicPlus exposes the central module contract")
assert(registeredMetadata.capabilities[1]=="character.scan.mythicplus" and registeredMetadata.data.block=="mythicPlus" and registeredMetadata.data.snapshotType=="mythicplus" and registeredMetadata.data.schemaVersion==3 and registeredMetadata.sync.domains[1]=="character","MythicPlus contract describes capabilities, snapshot data and sync integration")
Module:OnInitialize();Module:OnEnable();assert(type(registeredEvents.MYTHIC_PLUS_CURRENT_AFFIX_UPDATE)=="function"and type(registeredEvents.CHALLENGE_MODE_MAPS_UPDATE)=="function","all asynchronous completion events remain registered")
registeredEvents.MYTHIC_PLUS_CURRENT_AFFIX_UPDATE("MYTHIC_PLUS_CURRENT_AFFIX_UPDATE");assert(workflows.created==1,"an affix update starts one snapshot workflow")
local pending=workflows.scanner();local valid,reason=Module:Validate(pending);assert(not valid and reason=="dungeon scores pending","overall rating without loaded map scores is retried instead of committed");assert(requested.affixes==0 and requested.maps==0 and requested.rewards==0 and workflows.created==1,"Collect only reads data and cannot self-trigger another workflow")
local validationOk,malformedValid,malformedReason=pcall(Module.Validate,Module,{seasonId=18,dungeons="broken"});assert(validationOk and not malformedValid and malformedReason=="dungeon pool unavailable","malformed scan data is rejected without raising a Lua error")
registeredEvents.CHALLENGE_MODE_MAPS_UPDATE("CHALLENGE_MODE_MAPS_UPDATE");registeredEvents.CHALLENGE_MODE_COMPLETED("CHALLENGE_MODE_COMPLETED");assert(workflows.created==1 and workflows.merged==2 and workflows.lastDelay==0.5,"completion and map updates merge with the short refresh delay");registeredEvents.MYTHIC_PLUS_NEW_WEEKLY_RECORD("MYTHIC_PLUS_NEW_WEEKLY_RECORD");assert(workflows.created==1 and workflows.merged==3,"bursty Mythic+ events merge into the active snapshot workflow")
C_MythicPlus.GetSeasonBestForMap=function(id)if id==1 then return{level=6,dungeonScore=145,durationSec=1200}end;return nil,{level=5,dungeonScore=90,durationSec=1900}end
C_MythicPlus.GetSeasonBestAffixScoreInfoForMap=function(id)if id==1 then return{{name="Seasonal",score=145,level=6,durationSec=1200,overTime=false}},155 end end
local snapshot=Module:Collect();assert(Module:Validate(snapshot));assert(snapshot.snapshotVersion==3 and snapshot.scoreDataReady,"loaded per-dungeon scores produce a complete v3 snapshot");assert(snapshot.dungeons[1].bestRun.level==6 and snapshot.dungeons[1].bestRun.score==145 and not snapshot.dungeons[1].bestRun.overTime,"in-time best run is normalized");assert(snapshot.dungeons[1].score==155,"the API's second overall-score return value is retained");assert(snapshot.dungeons[2].bestRun.level==5 and snapshot.dungeons[2].bestRun.overTime and snapshot.dungeons[2].score==90,"the API's second overtime return value is retained and normalized")
assert(requested.affixes==0 and requested.maps==0 and requested.rewards==0,"repeated Collect calls never issue asynchronous requests")
local mergesBeforeInitial=workflows.merged;workflows.active=false;registeredEvents.PLAYER_ENTERING_WORLD("PLAYER_ENTERING_WORLD");assert(requested.affixes==1 and requested.maps==1 and requested.rewards==1,"initial world entry requests asynchronous Mythic+ data once");assert(workflows.created==2 and workflows.merged==mergesBeforeInitial+3,"request completion events and world entry merge into one snapshot")
local createdAfterInitial=workflows.created;local requestsAfterInitial=requested.affixes+requested.maps+requested.rewards;workflows.scanner();assert(workflows.created==createdAfterInitial and requested.affixes+requested.maps+requested.rewards==requestsAfterInitial,"the resulting snapshot cannot recursively request data or create another workflow")
workflows.active=false;registeredEvents.PLAYER_ENTERING_WORLD("PLAYER_ENTERING_WORLD");assert(workflows.created==createdAfterInitial+1 and requested.affixes+requested.maps+requested.rewards==requestsAfterInitial,"later world entries refresh the snapshot without repeating initial API requests")
capabilities["character.scan.mythicplus"](Module,true);assert(requested.affixes==2 and requested.maps==2 and requested.rewards==2,"an explicit refresh may request fresh Blizzard data");assert(workflows.created==createdAfterInitial+1,"explicit request completion events merge instead of creating parallel workflows")
print("Mythic+ request separation, workflow coalescing and best-run parsing tests passed")
