local addonVersion="1.0.0"
local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm")
local L=LibStub("AceLocale-3.0"):GetLocale("Holy_Storm")
local Content={version=addonVersion,types={NEWS=true,GUIDE=true,ANNOUNCEMENT=true},statuses={DRAFT=true,PUBLISHED=true,ARCHIVED=true,DELETED=true},priorities={NORMAL=true,IMPORTANT=true,URGENT=true},openHandlers={},sequence=0,maxEntries=1500,maxTitle=160,maxBody=60000}

local function copy(value)return HolyStorm.Utils.DeepCopy(value)end
local function now()return HolyStorm.Utils.Now()end
local function validId(value)return type(value)=="string"and#value>0 and#value<=160 and value:match("^[%w%-_]+$")~=nil end
local function setContains(values,key)return type(values)=="table"and values[key]==true end
local function slug(value)return string.lower(tostring(value or"")):gsub("[^%w%s%-]",""):gsub("[%s_]+","-"):gsub("%-+","-"):gsub("^%-",""):gsub("%-$","")end
local function permission(entry,action)return string.lower(entry.type=="ANNOUNCEMENT"and"NEWS"or entry.type).."-"..action end

function Content:IsEnabled()return not HolyStorm.Policy or(HolyStorm.Policy:IsGuildModuleEnabled("content")and HolyStorm.Policy:IsGuildModuleEnabled("news"))end
function Content:GetGuildId()return HolyStorm.Data.ContentStore:GetGuildId()end
function Content:Get(id)return HolyStorm.Data.ContentStore:Get(id)end
function Content:GetIndex()return HolyStorm.Data.ContentStore:GetIndex()end
function Content:NewId()
 self.sequence=self.sequence+1;local install=HolyStorm.db.global.installId or"local";return string.format("content-%08x-%04x-%04x-%s",now()%0xffffffff,self.sequence%0xffff,math.random(0,0xffff),install:gsub("[^%w]",""):sub(-12))
end
function Content:Normalize(entry,current)
 local result=copy(entry);result.id=result.id or self:NewId();result.guildId=result.guildId or self:GetGuildId();result.type=string.upper(tostring(result.type or(current and current.type)or"NEWS"));result.category=string.upper(tostring(result.category or(current and current.category)or"GENERAL"));result.title=HolyStorm.Utils.Trim(result.title or"");result.slug=slug(result.slug~=""and result.slug or result.title);result.body=tostring(result.body or result.content or"");result.content=nil;result.status=string.upper(tostring(result.status or(current and current.status)or"DRAFT"));result.priority=string.upper(tostring(result.priority or(current and current.priority)or"NORMAL"));result.visibility=type(result.visibility)=="table"and result.visibility or{scope="GUILD"};result.visibility.scope=string.upper(tostring(result.visibility.scope or"GUILD"));result.tags=type(result.tags)=="table"and result.tags or{};result.metadata=type(result.metadata)=="table"and result.metadata or{};return result
end
function Content:Validate(entry)
 if type(entry)~="table"or not validId(entry.id)or type(entry.guildId)~="string"or#entry.guildId==0 or#entry.guildId>160 or not self.types[entry.type]or not self.statuses[entry.status]or not self.priorities[entry.priority]then return false,"INVALID_CONTENT"end
 if type(entry.title)~="string"or#entry.title==0 or#entry.title>self.maxTitle or type(entry.body)~="string"or#entry.body>self.maxBody then return false,"INVALID_TEXT"end
 if type(entry.category)~="string"or#entry.category==0 or#entry.category>64 or type(entry.tags)~="table"or HolyStorm.Utils.TableCount(entry.tags)>20 then return false,"INVALID_METADATA"end;for _,tag in ipairs(entry.tags)do if type(tag)~="string"or#tag>32 then return false,"INVALID_TAG"end end
 if type(entry.visibility)~="table"or not({GUILD=true,GROUPS=true,CHARACTERS=true,ACCOUNTS=true,FILTERS=true,RANKS=true})[entry.visibility.scope]then return false,"INVALID_VISIBILITY"end;for _,field in ipairs({"groupIds","characterIds","accountIds","filterIds","rankIds"})do local values=entry.visibility[field];if values~=nil then if type(values)~="table"or HolyStorm.Utils.TableCount(values)>100 then return false,"INVALID_VISIBILITY"end;for id,enabled in pairs(values)do if enabled~=true or(type(id)~="string"and type(id)~="number")or#tostring(id)>160 then return false,"INVALID_VISIBILITY"end end end end
 return true
end
function Content:IsTargeted(entry,accountUUID,characterUUID)
 local visibility=entry.visibility or{scope="GUILD"};local scope=visibility.scope or"GUILD";if scope=="GUILD"then return true end
 if scope=="CHARACTERS"then return setContains(visibility.characterIds,characterUUID)end;if scope=="ACCOUNTS"then return setContains(visibility.accountIds,accountUUID)end
 if scope=="GROUPS"then for groupId in pairs(visibility.groupIds or{})do local group=HolyStorm.Policy:GetGroup(groupId);if group and#HolyStorm.Policy:GetMembershipReasons(group,accountUUID,characterUUID)>0 then return true end end;return false end
 if scope=="RANKS"then local guild=HolyStorm.Data.GuildStore:GetCurrent();local member=guild and guild.roster and guild.roster[characterUUID];return member and visibility.rankIds and visibility.rankIds[member.rankIndex]==true or false end
 if scope=="FILTERS"then local target={guid=characterUUID,accountUUID=accountUUID,content=entry};for filterId in pairs(visibility.filterIds or{})do if HolyStorm.Policy:ApplyFilter(filterId,target,"global")then return true end end;return false end
 return false
end
function Content:CanView(entry,accountUUID,characterUUID)
 if not entry or entry.status=="DELETED"or not self:IsEnabled()then return false,"UNAVAILABLE"end;characterUUID=characterUUID or UnitGUID("player");accountUUID=accountUUID or(HolyStorm.TwinkCore and HolyStorm.TwinkCore:GetAccountUUIDForCharacter(characterUUID))
 local own=entry.authorGuid==characterUUID;local canEdit=(HolyStorm.PermissionEngine or HolyStorm.Policy):Can(permission(entry,"edit"),accountUUID,characterUUID,entry);if entry.status~="PUBLISHED"and not own and not canEdit then return false,"DRAFT"end
 if not (HolyStorm.PermissionEngine or HolyStorm.Policy):Can(permission(entry,"view"),accountUUID,characterUUID,entry)and not own and not canEdit then return false,"PERMISSION"end
 return self:IsTargeted(entry,accountUUID,characterUUID),"VISIBILITY"
end
function Content:GetVisibleById(id)local entry=self:Get(id);local visible,reason=self:CanView(entry);return visible and entry or nil,reason end
function Content:List(options)
 options=options or{};local out={};local query=string.lower(HolyStorm.Utils.Trim(options.search or""));for _,entry in pairs(HolyStorm.Data.ContentStore:GetEntries())do local visible=self:CanView(entry);local typeMatch=not options.type or entry.type==options.type;local statusMatch=not options.status or entry.status==options.status;local haystack=string.lower(table.concat({entry.title or"",entry.category or"",entry.author or"",table.concat(entry.tags or{}," ")}," "));if visible and typeMatch and statusMatch and(query==""or haystack:find(query,1,true))then out[#out+1]=entry end end
 table.sort(out,function(a,b)if options.type=="GUIDE"then if a.category~=b.category then return a.category<b.category end;if a.title~=b.title then return a.title<b.title end end;if a.priority~=b.priority then local p={NORMAL=1,IMPORTANT=2,URGENT=3};return p[a.priority]>p[b.priority]end;return(a.modifiedAt or 0)>(b.modifiedAt or 0)end);return out
end
function Content:Save(entry,expectedRevision)
 if not self:IsEnabled()then return false,"MODULE_DISABLED"end;local current=entry.id and self:Get(entry.id);if current and tonumber(expectedRevision)~=tonumber(current.revision)then return false,"CONFLICT",current.revision end;if not current and expectedRevision~=nil and tonumber(expectedRevision)~=0 then return false,"CONFLICT",0 end
 local candidate=self:Normalize(entry,current);if candidate.guildId~=self:GetGuildId()then return false,"WRONG_GUILD"end;local action=current and"edit"or"create";local deleting=current and candidate.status=="DELETED"and (HolyStorm.PermissionEngine or HolyStorm.Policy):Can(permission(current,"delete"),nil,nil,candidate);if not deleting and not (HolyStorm.PermissionEngine or HolyStorm.Policy):Can(permission(current or candidate,action),nil,nil,candidate)then return false,"PERMISSION_DENIED"end
 if current and candidate.type~=current.type and not (HolyStorm.PermissionEngine or HolyStorm.Policy):Can(permission(candidate,"create"),nil,nil,candidate)then return false,"PERMISSION_DENIED"end;if candidate.status=="PUBLISHED"and(current==nil or current.status~="PUBLISHED")and not (HolyStorm.PermissionEngine or HolyStorm.Policy):Can(permission(candidate,"publish"),nil,nil,candidate)then return false,"PERMISSION_DENIED"end
 if not current and HolyStorm.Utils.TableCount(HolyStorm.Data.ContentStore:GetEntries())>=self.maxEntries then return false,"CONTENT_LIMIT"end
 local actorGuid=UnitGUID("player");local actorAccount=HolyStorm.TwinkCore and HolyStorm.TwinkCore:GetAccountUUIDForCharacter(actorGuid);candidate.authorGuid=current and current.authorGuid or candidate.authorGuid or actorGuid;candidate.authorAccountUUID=current and current.authorAccountUUID or candidate.authorAccountUUID or actorAccount;candidate.author=current and current.author or candidate.author or GetUnitName("player",true);candidate.createdAt=current and current.createdAt or candidate.createdAt or now();candidate.createdBy=current and current.createdBy or candidate.createdBy or actorGuid;candidate.modifiedAt=now();candidate.modifiedBy=actorGuid;candidate.revision=(current and current.revision or 0)+1
 if candidate.status=="PUBLISHED"and(not current or current.status~="PUBLISHED")then candidate.publishedAt=now();candidate.publishedBy=actorGuid elseif current then candidate.publishedAt=candidate.publishedAt or current.publishedAt;candidate.publishedBy=candidate.publishedBy or current.publishedBy end
 local valid,err=self:Validate(candidate);if not valid then return false,err end;if current then HolyStorm.Data.ContentStore:AddHistory(current,candidate.guildId)end;HolyStorm.Data.ContentStore:Put(candidate);HolyStorm.RichContent:Invalidate();HolyStorm.Sync:Publish("content",candidate.id,"CONTENT_UPDATED");HolyStorm.Events:Emit(current and"HS_CONTENT_UPDATED"or"HS_CONTENT_CREATED",candidate.id,candidate.type);if candidate.status=="PUBLISHED"and(not current or current.status~="PUBLISHED")then HolyStorm.Events:Emit("HS_CONTENT_PUBLISHED",candidate.id,candidate.type)elseif candidate.status=="ARCHIVED"and current and current.status~="ARCHIVED"then HolyStorm.Events:Emit("HS_CONTENT_ARCHIVED",candidate.id,candidate.type)elseif candidate.status=="DELETED"and current and current.status~="DELETED"then HolyStorm.Events:Emit("HS_CONTENT_DELETED",candidate.id,candidate.type)end;HolyStorm.Events:Emit(candidate.type=="GUIDE"and"HS_GUIDE_UPDATED"or"HS_NEWS_UPDATED",candidate.id);return true,candidate
end
function Content:SaveDraft(entry,expectedRevision)entry=copy(entry);entry.status="DRAFT";return self:Save(entry,expectedRevision)end
function Content:Publish(entry,expectedRevision)entry=copy(entry);entry.status="PUBLISHED";return self:Save(entry,expectedRevision)end
function Content:Archive(id,expectedRevision)local entry=self:Get(id);if not entry then return false,"NOT_FOUND"end;entry=copy(entry);entry.status="ARCHIVED";return self:Save(entry,expectedRevision)end
function Content:Delete(id,expectedRevision)local entry=self:Get(id);if not entry then return false,"NOT_FOUND"end;if not (HolyStorm.PermissionEngine or HolyStorm.Policy):Can(permission(entry,"delete"),nil,nil,entry)then return false,"PERMISSION_DENIED"end;if tonumber(expectedRevision)~=tonumber(entry.revision)then return false,"CONFLICT",entry.revision end;entry=copy(entry);entry.status="DELETED";entry.deletedAt=now();entry.deletedBy=UnitGUID("player");return self:Save(entry,expectedRevision)
end
function Content:IsUnread(entry)local guid=UnitGUID("player");if not entry or entry.type=="GUIDE"or entry.status~="PUBLISHED"or not self:CanView(entry)then return false end;local read=HolyStorm.Data.ContentStore:GetRead(entry.id,guid);return not read or tonumber(read.revision)<tonumber(entry.revision)end
function Content:MarkRead(id)local entry=self:GetVisibleById(id);if not entry then return false end;HolyStorm.Data.ContentStore:SetRead(id,UnitGUID("player"),entry.revision);HolyStorm.Events:Emit("HS_CONTENT_READ",id);HolyStorm.Events:Emit("HS_NEWS_READ",id);return true end
function Content:GetUnreadCount()local count=0;for _,entry in ipairs(self:List())do if self:IsUnread(entry)then count=count+1 end end;return count end
function Content:ResolveGuide(query)
 query=HolyStorm.Utils.Trim(query or"");local direct=self:GetVisibleById(query);if direct and direct.type=="GUIDE"then return direct,{}end;local normalized=slug(query);local exact,partial={},{};for _,entry in ipairs(self:List({type="GUIDE"}))do if entry.slug==normalized or string.lower(entry.title)==string.lower(query)then exact[#exact+1]=entry elseif normalized~=""and(entry.slug:find(normalized,1,true)or string.lower(entry.title):find(string.lower(query),1,true))then partial[#partial+1]=entry end end;if#exact==1 then return exact[1],exact elseif#exact>1 then return nil,exact,"AMBIGUOUS"elseif#partial==1 then return partial[1],partial elseif#partial>1 then return nil,partial,"AMBIGUOUS"end;return nil,{},"NOT_FOUND"
end
function Content:RegisterOpenHandler(id,handler)if type(id)~="string"or type(handler)~="function"then return false end;self.openHandlers[id]=handler;return true end
function Content:Open(id)
 local entry,reason=self:GetVisibleById(id);if not entry then local index=self:GetIndex()[id];if validId(id)and(not index or index.bodyLoaded==false)then HolyStorm.Sync:RequestObject("content",id,{reason="CONTENT_OPEN"});HolyStorm.Events:Emit("HS_CONTENT_LOADING",id);return false,"LOADING"end;HolyStorm.Events:Emit("HS_CONTENT_OPEN_FAILED",id,reason or"NOT_FOUND");return false,reason or"NOT_FOUND"end
 local handler=self.openHandlers[entry.type]or self.openHandlers["*"];if not handler then return false,"NO_VIEW"end;handler(entry);if entry.type~="GUIDE"then self:MarkRead(id)end;return true
end
function Content:GetDiagnostics(id)local entry=self:Get(id);if not entry then return nil end;local _,diagnostics=HolyStorm.RichContent:Parse(entry.body);local index=self:GetIndex()[id]or{};local pending=false;for _,request in pairs(HolyStorm.Sync.requests or{})do if request.domain=="content"and request.objectId==id then pending=true break end end;return{id=id,type=entry.type,revision=entry.revision,source=index.source,bodyLoaded=index.bodyLoaded,modifiedAt=entry.modifiedAt,lastSync=index.syncedAt,visibility=select(1,self:CanView(entry)),syncStatus=pending and"PENDING"or index.source=="sync"and"SYNCED"or"LOCAL",payloadMode=index.bodyLoaded and"FULL"or"METADATA_ONLY",payloadSize=entry.body and#entry.body or 0,pendingFetch=pending,links=diagnostics.links,parserErrors=diagnostics.errors,unresolved=diagnostics.unresolved}
end
function Content:RebuildIndex()for _,entry in pairs(HolyStorm.Data.ContentStore:GetEntries())do HolyStorm.Data.ContentStore:Put(entry)end;return true end
function Content:Initialize()
 HolyStorm.Data.ContentStore:Initialize();HolyStorm.Tasks:RegisterTaskType("Content.RebuildIndex",{name=L["TASK_CONTENT_INDEX"],localizedNameKey="TASK_CONTENT_INDEX",module="Content",priority=60,executionMode="UNIQUE",execute=function()return Content:RebuildIndex()end});HolyStorm.Tasks:RegisterTaskType("Content.Migrate",{name=L["TASK_CONTENT_MIGRATE"],localizedNameKey="TASK_CONTENT_MIGRATE",module="Content",priority=15,executionMode="UNIQUE",execute=function(task)local _,count=HolyStorm.Data.ContentStore:MigrateLegacy(task.metadata and task.metadata.guildId);return true,count end})
 HolyStorm.Sync:RegisterDomain("content",{getMetadata=function(id)if not Content:IsEnabled()then return nil end;local index=Content:GetIndex()[id];return index and{objectId=id,owner=index.modifiedBy or index.authorGuid or(Content:Get(id)and(Content:Get(id).modifiedBy or Content:Get(id).authorGuid)),version=tonumber(index.revision)or 0,updatedAt=tonumber(index.modifiedAt)or 0,source="content"}end,listMetadata=function(since)local out={};if not Content:IsEnabled()then return out end;for id,index in pairs(Content:GetIndex())do if(index.modifiedAt or 0)>since then out[#out+1]={objectId=id,owner=index.modifiedBy or index.authorGuid or(Content:Get(id)and(Content:Get(id).modifiedBy or Content:Get(id).authorGuid)),version=tonumber(index.revision)or 0,updatedAt=tonumber(index.modifiedAt)or 0,source="content"}end end;return out end,export=function(id)return Content:IsEnabled()and copy(Content:Get(id))or nil end,validate=function(entry,meta,id)local valid=Content:Validate(entry);return Content:IsEnabled()and valid and entry.id==id and entry.guildId==Content:GetGuildId()and(meta.owner==entry.modifiedBy or meta.owner==entry.authorGuid)end,authorize=function(entry,meta)if not Content:IsEnabled()then return false end;local account=HolyStorm.Data.PlayerStore:GetCharacterOwner(meta.owner)or meta.owner;local current=Content:Get(entry.id);local action=current and(entry.status=="DELETED"and"delete"or"edit")or"create";if entry.status=="PUBLISHED"and not (HolyStorm.PermissionEngine or HolyStorm.Policy):Can(permission(entry,"publish"),account,meta.owner,entry)then return false end;return (HolyStorm.PermissionEngine or HolyStorm.Policy):Can(permission(entry,action),account,meta.owner,entry)end,import=function(id,entry)if not Content:IsEnabled()then return false end;local current=Content:Get(id);if current and tonumber(current.revision)>=tonumber(entry.revision)then return false end;if not Content:CanView(entry)then return false end;if current then HolyStorm.Data.ContentStore:AddHistory(current,entry.guildId)end;entry.source="sync";entry.syncedAt=now();HolyStorm.Data.ContentStore:Put(entry);HolyStorm.RichContent:Invalidate();HolyStorm.Events:Emit("HS_CONTENT_UPDATED",id,entry.type);HolyStorm.Events:Emit(entry.type=="GUIDE"and"HS_GUIDE_UPDATED"or"HS_NEWS_UPDATED",id);return true end,updateEvent="HS_CONTENT_SYNC_UPDATED"})
 HolyStorm.Events:Register("HS_GUILD_UPDATED","content-store",function(_,guildId)HolyStorm.Tasks:Queue("Content.Migrate",{startupPhase=4,triggerSource="GUILD_UPDATED",metadata={guildId=guildId}});HolyStorm.Tasks:Queue("Content.RebuildIndex",{startupPhase=4,triggerSource="GUILD_UPDATED"})end)
end
HolyStorm.Content=Content
