local addonVersion="2.0.1"
local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm")
local L=LibStub("AceLocale-3.0"):GetLocale("Holy_Storm_News")
local metadata={id="News",name="News",internalName="content",displayName=L["TITLE"],description=L["DESCRIPTION"],version=addonVersion,moduleType="feature",category="required",permissions={{id="news-view",category="News",defaults={officers=true,member=true}},{id="news-create",category="News",defaults={officers=true}},{id="news-edit",category="News",defaults={officers=true}},{id="news-delete",category="News",defaults={officers=true}},{id="news-publish",category="News",defaults={officers=true}},{id="news-read-receipts",category="News",defaults={officers=true}},{id="guide-view",category="News",defaults={officers=true,member=true}},{id="guide-create",category="News",defaults={officers=true}},{id="guide-edit",category="News",defaults={officers=true}},{id="guide-delete",category="News",defaults={officers=true}},{id="guide-publish",category="News",defaults={officers=true}}},dependencies={"core","ui","synchronization"},ui={page="news",navigation=true},data={store="ContentStore"},sync={domains={"content"}},enabledByDefault=true}
HolyStorm:RegisterModule(metadata,function(News)

local types={"ALL","NEWS","GUIDE","ANNOUNCEMENT"}
local priorities={"NORMAL","IMPORTANT","URGENT"}
local visibilities={"GUILD","GROUPS","CHARACTERS","ACCOUNTS","FILTERS"}
local linkTypes={"item","player","character","poi","coordinate","guide","news"}
local function label(prefix,value)local key=prefix..tostring(value);return L[key]or tostring(value)end
local function cycle(list,current)local found=1;for index,value in ipairs(list)do if value==current then found=index break end end;return list[found%#list+1]end
local function csvSet(text)local out={};for value in tostring(text or""):gmatch("[^,%s]+")do out[value]=true end;return out end
local function setCsv(values)local out={};for value,enabled in pairs(values or{})do if enabled then out[#out+1]=value end end;table.sort(out);return table.concat(out,",")end
local function permission(entry,action)local kind=entry and entry.type=="GUIDE"and"guide"or"news";return kind.."-"..action end
local function button(parent,text,width,onClick)local value=CreateFrame("Button",nil,parent,"UIPanelButtonTemplate");value:SetSize(width or 100,24);value:SetText(text);value:SetScript("OnClick",onClick);return value end

function News:GetStore()return HolyStorm.Data.ContentStore:GetGuild(nil,true)end
function News:GetVisible()local out={};for _,entry in ipairs(HolyStorm.Content:List({type=self.activeType~="ALL"and self.activeType or nil,search=self.searchText}))do if not self.filterBar or self.filterBar:Matches({guid=entry.authorGuid,content=entry,news=entry})then out[#out+1]=entry end end;return out end
function News:GetUnreadCount()return HolyStorm.Content:GetUnreadCount()end
function News:IsUnread(entry)return HolyStorm.Content:IsUnread(entry)end
function News:Save(entry,expectedRevision)return HolyStorm.Content:Save(entry,expectedRevision)end
function News:Delete(id,revision)return HolyStorm.Content:Delete(id,revision)end
function News:MarkRead(id)return HolyStorm.Content:MarkRead(id)end
function News:IsRelevant(entry,guid)local account=HolyStorm.TwinkCore and HolyStorm.TwinkCore:GetAccountUUIDForCharacter(guid);return HolyStorm.Content:CanView(entry,account,guid)end
function News:Validate(entry)return HolyStorm.Content:Validate(HolyStorm.Content:Normalize(entry,entry.id and HolyStorm.Content:Get(entry.id)))end
function News:SetMode(mode)for id,frame in pairs(self.modes)do frame:SetShown(id==mode)end;self.mode=mode end
function News:ShowMessage(key)local text=L[key]or key;self.message:SetText(text);self.message:Show();if C_Timer then C_Timer.After(4,function()if self.message:GetText()==text then self.message:Hide()end end)end end
function News:RefreshListIfVisible()if self.page and self.page:IsShown()and self.mode=="list"then self:RenderList();return true end;return false end

function News:RenderList()
 if not self.page:IsShown()then return end;self:SetMode("list");for _,row in ipairs(self.rows)do row:Hide()end
 if not HolyStorm.Content:IsEnabled()then self.empty:SetText(L["MODULE_DISABLED"]);self.empty:Show();return end
 local visible=self:GetVisible();self.empty:SetText(self.searchText and self.searchText~=""and L["EMPTY_SEARCH"]or(self.activeType=="GUIDE"and L["EMPTY_GUIDES"]or L["EMPTY_NEWS"]));self.empty:SetShown(#visible==0)
 for index,entry in ipairs(visible)do local row=self.rows[index];if not row then row=CreateFrame("Button",nil,self.listContent,"BackdropTemplate");row:SetHeight(54);row:RegisterForClicks("LeftButtonUp");row:EnableMouse(true);row:SetBackdrop({bgFile="Interface\\Buttons\\WHITE8x8"});row.icon=row:CreateTexture(nil,"ARTWORK");row.icon:SetSize(32,32);row.icon:SetPoint("LEFT",10,0);row.title=row:CreateFontString(nil,"OVERLAY","GameFontNormal");row.title:SetPoint("TOPLEFT",52,-8);row.title:SetWidth(350);row.title:SetJustifyH("LEFT");row.meta=row:CreateFontString(nil,"OVERLAY","GameFontHighlightSmall");row.meta:SetPoint("BOTTOMLEFT",52,8);row.meta:SetWidth(500);row.meta:SetJustifyH("LEFT");row.priority=row:CreateFontString(nil,"OVERLAY","GameFontHighlightSmall");row.priority:SetPoint("RIGHT",-12,0);row.priority:SetJustifyH("RIGHT");row:SetScript("OnEnter",function(r)r:SetBackdropColor(1,.82,0,.10)end);row:SetScript("OnLeave",function(r)r:SetBackdropColor(1,1,1,r.baseAlpha or.025)end);self.rows[index]=row end
  local contentId=entry.id;row.baseAlpha=index%2==0 and.04 or.025;row:SetBackdropColor(1,1,1,row.baseAlpha);row:ClearAllPoints();row:SetPoint("TOPLEFT",0,-((index-1)*56));row:SetPoint("RIGHT",0,0);row.icon:SetTexture(entry.icon or(entry.type=="GUIDE"and"Interface\\Icons\\INV_Misc_Book_09"or"Interface\\Icons\\INV_Misc_Note_05"));row.title:SetText((self:IsUnread(entry)and"|cffffd100•|r "or"")..entry.title);row.meta:SetText(string.format(L["LIST_META"],label("TYPE_",entry.type),label("CATEGORY_",entry.category),entry.author or L["UNKNOWN"],date("%d.%m.%Y",entry.modifiedAt or entry.createdAt)));row.priority:SetText(label("PRIORITY_",entry.priority).."  ·  "..label("STATUS_",entry.status));row:SetScript("OnClick",function()HolyStorm.Content:Open(contentId)end);row:Show()
 end;self.listContent:SetHeight(math.max(1,#visible*56));self.create:SetEnabled(HolyStorm.Content:IsEnabled()and(HolyStorm.Policy:Can("news-create")or HolyStorm.Policy:Can("guide-create")));self.diagnosticsButton:SetShown(HolyStorm.Database:Get("debug","profile")==true)
end
function News:RenderDiagnostics()
 self:SetMode("diagnostics");local ids={};for id in pairs(HolyStorm.Content:GetIndex())do ids[#ids+1]=id end;table.sort(ids);local lines={L["DEBUG_HEADER"]};for _,id in ipairs(ids)do local d=HolyStorm.Content:GetDiagnostics(id);if d then lines[#lines+1]=string.format(L["DEBUG_ENTRY"],d.id,d.type,d.revision or 0,d.source or"-",d.syncStatus,d.payloadMode,d.payloadSize,tostring(d.visibility),#d.links,#d.unresolved,#d.parserErrors);for _,linkInfo in ipairs(d.links)do lines[#lines+1]=string.format(L["DEBUG_LINK"],linkInfo.type,linkInfo.target,tostring(linkInfo.resolved))end end end;self.diagnosticsText:SetText(table.concat(lines,"\n"));self.diagnosticsContent:SetHeight(math.max(self.diagnosticsScroll:GetHeight(),self.diagnosticsText:GetStringHeight()+12))
end
function News:Open(entry)
 if type(entry)=="string"then return HolyStorm.Content:Open(entry)end;self.current=entry;self:SetMode("detail");self.detailTitle:SetText(entry.title);self.detailMeta:SetText(string.format(L["DETAIL_META"],label("TYPE_",entry.type),label("CATEGORY_",entry.category),entry.author or L["UNKNOWN"],date("%d.%m.%Y %H:%M",entry.modifiedAt or entry.createdAt),label("PRIORITY_",entry.priority),label("STATUS_",entry.status)));self.diagnostics=HolyStorm.RichContent:Render(self.detailRenderer,entry.body,{contentId=entry.id});self.edit:SetEnabled(HolyStorm.Policy:Can(permission(entry,"edit")));self.publish:SetEnabled(entry.status~="PUBLISHED"and HolyStorm.Policy:Can(permission(entry,"publish")));self.archive:SetEnabled(entry.status~="ARCHIVED"and HolyStorm.Policy:Can(permission(entry,"edit")));self.delete:SetEnabled(HolyStorm.Policy:Can(permission(entry,"delete")));HolyStorm.Content:MarkRead(entry.id);if HolyStorm.Database:Get("debug","profile")then local diagnostics=HolyStorm.Content:GetDiagnostics(entry.id);self.debug:SetText(string.format(L["DEBUG_FORMAT"],entry.id,entry.revision or 0,diagnostics and diagnostics.source or"-",diagnostics and tostring(diagnostics.bodyLoaded)or"false",diagnostics and#diagnostics.links or 0,diagnostics and#diagnostics.unresolved or 0,diagnostics and#diagnostics.parserErrors or 0));self.debug:Show()else self.debug:Hide()end
end
function News:BeginEditor(entry)
 self.editing=entry and HolyStorm.Utils.DeepCopy(entry)or{type=self.activeType~="ALL"and self.activeType or"NEWS",category="GENERAL",priority="NORMAL",status="DRAFT",visibility={scope="GUILD"},tags={}};if self.editing.type=="ANNOUNCEMENT"then self.editing.type="NEWS"end;self.baseRevision=entry and entry.revision or 0;self.titleInput:SetText(self.editing.title or"");self.categoryInput:SetText(self.editing.category or"GENERAL");self.tagsInput:SetText(table.concat(self.editing.tags or{},","));self.bodyInput:SetText(self.editing.body or"");self.editorType=self.editing.type;self.editorPriority=self.editing.priority;self.editorVisibility=self.editing.visibility and self.editing.visibility.scope or"GUILD";local values=self.editing.visibility and(self.editing.visibility.groupIds or self.editing.visibility.characterIds or self.editing.visibility.accountIds or self.editing.visibility.filterIds);self.targetsInput:SetText(setCsv(values));self:RefreshEditorButtons();self:SetMode("editor");self.titleInput:SetFocus()
end
function News:RefreshEditorButtons()self.typeButton:SetText(label("TYPE_",self.editorType));self.priorityButton:SetText(label("PRIORITY_",self.editorPriority));self.visibilityButton:SetText(label("VISIBILITY_",self.editorVisibility));self.targetsInput:SetEnabled(self.editorVisibility~="GUILD")end
function News:CollectEditor()
 local visibility={scope=self.editorVisibility};local targets=csvSet(self.targetsInput:GetText());if self.editorVisibility=="GROUPS"then visibility.groupIds=targets elseif self.editorVisibility=="CHARACTERS"then visibility.characterIds=targets elseif self.editorVisibility=="ACCOUNTS"then visibility.accountIds=targets elseif self.editorVisibility=="FILTERS"then visibility.filterIds=targets end
 local tags={};for tag in self.tagsInput:GetText():gmatch("[^,%s]+")do tags[#tags+1]=tag end;local draft=HolyStorm.Utils.DeepCopy(self.editing);draft.title=self.titleInput:GetText();draft.type=self.editorType;draft.category=self.categoryInput:GetText();draft.priority=self.editorPriority;draft.visibility=visibility;draft.tags=tags;draft.body=self.bodyInput:GetText();return draft
end
function News:SaveEditor(publish)
 local draft=self:CollectEditor();local ok,result,current=publish and HolyStorm.Content:Publish(draft,self.baseRevision)or HolyStorm.Content:SaveDraft(draft,self.baseRevision);if not ok then self:ShowMessage(result=="CONFLICT"and"ERROR_CONFLICT"or result=="PERMISSION_DENIED"and"ERROR_PERMISSION"or"ERROR_SAVE");if result=="CONFLICT"then self.baseRevision=current end;return end;self.editing=result;self.baseRevision=result.revision;self:ShowMessage(publish and"PUBLISHED"or"DRAFT_SAVED");self:Open(result)
end
function News:Preview()local draft=self:CollectEditor();self.previewTitle:SetText(draft.title~=""and draft.title or L["UNTITLED"]);HolyStorm.RichContent:Render(self.previewRenderer,draft.body,{preview=true});self:SetMode("preview")end
function News:Share(entry)local inserted,link=HolyStorm.RichContent:InsertChatLink(entry.type=="GUIDE"and"guide"or"news",entry.id,string.format(entry.type=="GUIDE"and L["GUIDE_LINK"]or L["NEWS_LINK"],entry.title));if not inserted then self.shareBox:SetText(link);self.shareBox:HighlightText();self.shareBox:Show();self.shareBox:SetFocus()end end
function News:GetInsertItems()
 local out={};if self.insertType=="player"or self.insertType=="character"then return HolyStorm.PolicyUI:CharacterItems()end
 if self.insertType=="guide"or self.insertType=="news"then for _,entry in ipairs(HolyStorm.Content:List())do local match=self.insertType=="guide"and entry.type=="GUIDE"or self.insertType=="news"and entry.type~="GUIDE";if match then out[#out+1]={value=entry.id,label=entry.title.."  ·  "..label("CATEGORY_",entry.category),entry=entry}end end;table.sort(out,function(a,b)return a.label<b.label end);return out end
 if self.insertType=="poi"then for _,poi in ipairs(HolyStorm.MapLinks:ListPOIs())do local details={poi.category,poi.mapID and string.format(L["POI_MAP"],poi.mapID),poi.creator};local suffix={};for _,value in ipairs(details)do if value then suffix[#suffix+1]=tostring(value)end end;out[#out+1]={value=poi.id,label=poi.name..(#suffix>0 and("  ·  "..table.concat(suffix," · "))or""),poi=poi}end end;return out
end
function News:OpenInsert(linkType)self.insertType=linkType;self.insertTitle:SetText(string.format(L["INSERT_TITLE"],label("LINK_",string.upper(linkType))));self.insertTarget:SetText(nil);self.insertLabel:SetText(nil);self.insertHint:SetText(L["INSERT_HINT_"..string.upper(linkType)]or L["INSERT_HINT"]);local selectable=linkType=="player"or linkType=="character"or linkType=="poi"or linkType=="guide"or linkType=="news";self.insertSelector:SetShown(selectable);self.insertSelector:SetValue(nil,L["SELECT_TARGET"]);self.insertDialog:Show();if not selectable then self.insertTarget:SetFocus()end end
function News:ApplyInsert()
 local target=self.insertTarget:GetText();local token;if self.insertType=="item"and target:find("|Hitem:",1,true)then token=target else token=HolyStorm.RichContent:MakeToken(self.insertType,target,self.insertLabel:GetText()~=""and self.insertLabel:GetText()or nil)end;if not token then self:ShowMessage("ERROR_LINK")return end;self.bodyInput:Insert(token);self.insertDialog:Hide();self.bodyInput:SetFocus()
end

function News:BuildList(page)
 local frame=CreateFrame("Frame",nil,page);frame:SetAllPoints();local search=CreateFrame("EditBox",nil,frame,"SearchBoxTemplate");search:SetSize(250,24);search:SetPoint("TOPLEFT",18,-18);search:SetScript("OnTextChanged",function(box,user)if user then News.searchText=box:GetText();News:RenderList()end end);self.search=search
 local typeButton=button(frame,L["FILTER_ALL"],120,function(b)News.activeType=cycle(types,News.activeType or"ALL");b:SetText(label("FILTER_",News.activeType));News:RenderList()end);typeButton:SetPoint("LEFT",search,"RIGHT",10,0);self.typeFilter=typeButton
 local create=button(frame,L["CREATE"],130,function()News:BeginEditor()end);create:SetPoint("TOPRIGHT",-18,-18);local diagnostics=button(frame,L["DIAGNOSTICS"],110,function()News:RenderDiagnostics()end);diagnostics:SetPoint("RIGHT",create,"LEFT",-8,0);diagnostics:Hide();self.create,self.diagnosticsButton=create,diagnostics
 self.filterBar=HolyStorm.PolicyUI:CreateFilterBar(frame,"content",function()News:RenderList()end);self.filterBar:SetPoint("TOPLEFT",18,-50);self.filterBar:SetPoint("TOPRIGHT",-18,-50)
 local scroll=CreateFrame("ScrollFrame",nil,frame,"UIPanelScrollFrameTemplate");scroll:SetPoint("TOPLEFT",18,-100);scroll:SetPoint("BOTTOMRIGHT",-34,18);local content=CreateFrame("Frame",nil,scroll);content:SetSize(1,1);scroll:SetScrollChild(content);scroll:SetScript("OnSizeChanged",function(s)content:SetWidth(math.max(1,s:GetWidth()))end);local empty=content:CreateFontString(nil,"OVERLAY","GameFontHighlight");empty:SetPoint("TOPLEFT",8,-8);self.listContent,self.empty,self.rows=content,empty,{};return frame
end
function News:BuildDetail(page)
 local frame=CreateFrame("Frame",nil,page);frame:SetAllPoints();local back=button(frame,L["BACK"],90,function()News:RenderList()end);back:SetPoint("TOPLEFT",18,-16);local title=frame:CreateFontString(nil,"OVERLAY","GameFontHighlightLarge");title:SetPoint("TOPLEFT",frame,"TOPLEFT",18,-56);title:SetPoint("TOPRIGHT",frame,"TOPRIGHT",-20,-56);title:SetJustifyH("LEFT");local meta=frame:CreateFontString(nil,"OVERLAY","GameFontHighlightSmall");meta:SetPoint("TOPLEFT",title,"BOTTOMLEFT",0,-8);meta:SetPoint("RIGHT",frame,"RIGHT",-20,0);meta:SetTextColor(.7,.7,.7);local actions=CreateFrame("Frame",nil,frame);actions:SetSize(520,24);actions:SetPoint("TOPRIGHT",-18,-16);local edit=button(actions,L["EDIT"],80,function()News:BeginEditor(News.current)end);edit:SetPoint("LEFT");local publish=button(actions,L["PUBLISH"],90,function()local ok,result=HolyStorm.Content:Publish(News.current,News.current.revision);if ok then News:Open(result)else News:ShowMessage(result=="CONFLICT"and"ERROR_CONFLICT"or"ERROR_SAVE")end end);publish:SetPoint("LEFT",edit,"RIGHT",6,0);local archive=button(actions,L["ARCHIVE"],90,function()local ok,result=HolyStorm.Content:Archive(News.current.id,News.current.revision);if ok then News:RenderList()else News:ShowMessage("ERROR_SAVE")end end);archive:SetPoint("LEFT",publish,"RIGHT",6,0);local delete=button(actions,L["DELETE"],80,function()local ok=HolyStorm.Content:Delete(News.current.id,News.current.revision);if ok then News:RenderList()else News:ShowMessage("ERROR_SAVE")end end);delete:SetPoint("LEFT",archive,"RIGHT",6,0);local share=button(actions,L["SHARE"],90,function()News:Share(News.current)end);share:SetPoint("LEFT",delete,"RIGHT",6,0)
 local host=CreateFrame("Frame",nil,frame);host:SetPoint("TOPLEFT",18,-100);host:SetPoint("BOTTOMRIGHT",-18,58);local renderer=HolyStorm.RichContent:CreateRenderer(host);local debug=frame:CreateFontString(nil,"OVERLAY","GameFontHighlightSmall");debug:SetPoint("BOTTOMLEFT",18,34);debug:SetTextColor(.55,.55,.55);local shareBox=CreateFrame("EditBox",nil,frame,"InputBoxTemplate");shareBox:SetSize(620,24);shareBox:SetPoint("BOTTOMLEFT",18,6);shareBox:SetAutoFocus(false);shareBox:Hide();self.detailTitle,self.detailMeta,self.detailRenderer,self.debug,self.shareBox,self.edit,self.publish,self.archive,self.delete=title,meta,renderer,debug,shareBox,edit,publish,archive,delete;return frame
end
function News:BuildEditor(page)
 local frame=CreateFrame("Frame",nil,page);frame:SetAllPoints();local back=button(frame,L["CANCEL"],90,function()if News.current then News:Open(News.current)else News:RenderList()end end);back:SetPoint("TOPLEFT",18,-16)
 local titleLabel=frame:CreateFontString(nil,"OVERLAY","GameFontNormal");titleLabel:SetPoint("TOPLEFT",18,-56);titleLabel:SetText(L["TITLE_FIELD"]);local title=CreateFrame("EditBox",nil,frame,"InputBoxTemplate");title:SetPoint("TOPLEFT",titleLabel,"BOTTOMLEFT",0,-6);title:SetPoint("RIGHT",-18,0);title:SetHeight(26);title:SetMaxLetters(HolyStorm.Content.maxTitle);title:SetAutoFocus(false)
 local typeLabel=frame:CreateFontString(nil,"OVERLAY","GameFontNormalSmall");typeLabel:SetPoint("TOPLEFT",18,-112);typeLabel:SetText(L["TYPE_FIELD"]);local categoryLabel=frame:CreateFontString(nil,"OVERLAY","GameFontNormalSmall");categoryLabel:SetPoint("TOPLEFT",148,-112);categoryLabel:SetText(L["CATEGORY_FIELD"]);local priorityLabel=frame:CreateFontString(nil,"OVERLAY","GameFontNormalSmall");priorityLabel:SetPoint("TOPLEFT",338,-112);priorityLabel:SetText(L["PRIORITY_FIELD"]);local visibilityLabel=frame:CreateFontString(nil,"OVERLAY","GameFontNormalSmall");visibilityLabel:SetPoint("TOPLEFT",468,-112);visibilityLabel:SetText(L["VISIBILITY_FIELD"])
 local typeButton=button(frame,"",120,function()News.editorType=cycle({"NEWS","GUIDE"},News.editorType);News:RefreshEditorButtons()end);typeButton:SetPoint("TOPLEFT",18,-130);local category=CreateFrame("EditBox",nil,frame,"InputBoxTemplate");category:SetSize(180,24);category:SetPoint("LEFT",typeButton,"RIGHT",10,0);category:SetAutoFocus(false);category:SetMaxLetters(64);local priority=button(frame,"",120,function()News.editorPriority=cycle(priorities,News.editorPriority);News:RefreshEditorButtons()end);priority:SetPoint("LEFT",category,"RIGHT",10,0);local visibility=button(frame,"",145,function()News.editorVisibility=cycle(visibilities,News.editorVisibility);News:RefreshEditorButtons()end);visibility:SetPoint("LEFT",priority,"RIGHT",10,0)
 local targetsLabel=frame:CreateFontString(nil,"OVERLAY","GameFontNormalSmall");targetsLabel:SetPoint("TOPLEFT",18,-166);targetsLabel:SetText(L["TARGETS_FIELD"]);local targets=CreateFrame("EditBox",nil,frame,"InputBoxTemplate");targets:SetPoint("TOPLEFT",100,-160);targets:SetPoint("RIGHT",-18,0);targets:SetHeight(24);targets:SetAutoFocus(false)
 local tagsLabel=frame:CreateFontString(nil,"OVERLAY","GameFontNormalSmall");tagsLabel:SetPoint("TOPLEFT",18,-196);tagsLabel:SetText(L["TAGS_FIELD"]);local tags=CreateFrame("EditBox",nil,frame,"InputBoxTemplate");tags:SetPoint("TOPLEFT",170,-190);tags:SetPoint("RIGHT",-18,0);tags:SetHeight(24);tags:SetAutoFocus(false)
 local contentLabel=frame:CreateFontString(nil,"OVERLAY","GameFontNormalSmall");contentLabel:SetPoint("TOPLEFT",18,-226);contentLabel:SetText(L["CONTENT_FIELD"]);local tools=CreateFrame("Frame",nil,frame);tools:SetSize(620,24);tools:SetPoint("TOPLEFT",100,-220);for index,linkType in ipairs(linkTypes)do local selected=linkType;local insert=button(tools,label("LINK_",string.upper(linkType)),74,function()News:OpenInsert(selected)end);insert:SetPoint("LEFT",(index-1)*77,0)end
 local bodyScroll=CreateFrame("ScrollFrame",nil,frame,"InputScrollFrameTemplate");bodyScroll:SetPoint("TOPLEFT",18,-252);bodyScroll:SetPoint("BOTTOMRIGHT",-34,58);bodyScroll.hideCharCount=true;bodyScroll.maxLetters=HolyStorm.Content.maxBody;if InputScrollFrame_OnLoad then InputScrollFrame_OnLoad(bodyScroll)end;local body=bodyScroll.EditBox;body:SetMultiLine(true);body:SetFontObject("ChatFontNormal");body:SetAutoFocus(false);body:SetMaxLetters(HolyStorm.Content.maxBody);body:SetScript("OnReceiveDrag",function(b)local kind,itemId=GetCursorInfo();if kind=="item"then local _,link=GetItemInfo(itemId);if link then b:Insert(link);ClearCursor()end end end)
 local draft=button(frame,L["SAVE_DRAFT"],120,function()News:SaveEditor(false)end);draft:SetPoint("BOTTOMLEFT",18,18);local publish=button(frame,L["PUBLISH"],100,function()News:SaveEditor(true)end);publish:SetPoint("LEFT",draft,"RIGHT",8,0);local preview=button(frame,L["PREVIEW"],100,function()News:Preview()end);preview:SetPoint("LEFT",publish,"RIGHT",8,0);self.titleInput,self.typeButton,self.categoryInput,self.priorityButton,self.visibilityButton,self.targetsInput,self.tagsInput,self.bodyInput=title,typeButton,category,priority,visibility,targets,tags,body;return frame
end
function News:BuildPreview(page)local frame=CreateFrame("Frame",nil,page);frame:SetAllPoints();local back=button(frame,L["BACK_TO_EDITOR"],140,function()News:SetMode("editor")end);back:SetPoint("TOPLEFT",18,-16);local title=frame:CreateFontString(nil,"OVERLAY","GameFontHighlightLarge");title:SetPoint("TOPLEFT",18,-56);local host=CreateFrame("Frame",nil,frame);host:SetPoint("TOPLEFT",18,-92);host:SetPoint("BOTTOMRIGHT",-18,18);self.previewTitle=title;self.previewRenderer=HolyStorm.RichContent:CreateRenderer(host);return frame end
function News:BuildDiagnostics(page)local frame=CreateFrame("Frame",nil,page);frame:SetAllPoints();local back=button(frame,L["BACK"],90,function()News:RenderList()end);back:SetPoint("TOPLEFT",18,-16);local title=frame:CreateFontString(nil,"OVERLAY","GameFontHighlightLarge");title:SetPoint("LEFT",back,"RIGHT",14,0);title:SetText(L["DIAGNOSTICS"]);local scroll=CreateFrame("ScrollFrame",nil,frame,"UIPanelScrollFrameTemplate");scroll:SetPoint("TOPLEFT",18,-56);scroll:SetPoint("BOTTOMRIGHT",-28,18);local content=CreateFrame("Frame",nil,scroll);content:SetSize(1,1);scroll:SetScrollChild(content);local output=content:CreateFontString(nil,"OVERLAY","GameFontHighlightSmall");output:SetPoint("TOPLEFT",4,-4);output:SetJustifyH("LEFT");output:SetJustifyV("TOP");scroll:SetScript("OnSizeChanged",function(s)content:SetWidth(math.max(1,s:GetWidth()));output:SetWidth(math.max(1,s:GetWidth()-8))end);self.diagnosticsScroll,self.diagnosticsContent,self.diagnosticsText=scroll,content,output;return frame end
function News:BuildInsertDialog(page)local frame=CreateFrame("Frame",nil,page,"BackdropTemplate");frame:SetSize(560,280);frame:SetPoint("CENTER");frame:SetFrameStrata("DIALOG");frame:SetBackdrop({bgFile="Interface\\DialogFrame\\UI-DialogBox-Background",edgeFile="Interface\\DialogFrame\\UI-DialogBox-Border",edgeSize=24,insets={left=8,right=8,top=8,bottom=8}});local title=frame:CreateFontString(nil,"OVERLAY","GameFontHighlightLarge");title:SetPoint("TOP",0,-24);local hint=frame:CreateFontString(nil,"OVERLAY","GameFontHighlightSmall");hint:SetPoint("TOPLEFT",24,-58);hint:SetPoint("RIGHT",-24,0);hint:SetJustifyH("LEFT");local selector=HolyStorm.PolicyUI:CreateSelector(frame,455,function()return News:GetInsertItems()end,function(value,item)News.insertTarget:SetText(value);if News.insertLabel:GetText()==""then News.insertLabel:SetText(item.label or item.name or value)end end);selector:SetPoint("TOPLEFT",8,-92);local target=CreateFrame("EditBox",nil,frame,"InputBoxTemplate");target:SetPoint("TOPLEFT",24,-142);target:SetPoint("RIGHT",-24,0);target:SetHeight(26);target:SetMaxLetters(1024);local labelInput=CreateFrame("EditBox",nil,frame,"InputBoxTemplate");labelInput:SetPoint("TOPLEFT",24,-182);labelInput:SetPoint("RIGHT",-24,0);labelInput:SetHeight(26);labelInput:SetMaxLetters(180);local insert=button(frame,L["INSERT"],100,function()News:ApplyInsert()end);insert:SetPoint("BOTTOMRIGHT",-24,22);local cancel=button(frame,L["CANCEL"],100,function()frame:Hide()end);cancel:SetPoint("RIGHT",insert,"LEFT",-8,0);frame:Hide();self.insertDialog,self.insertTitle,self.insertHint,self.insertSelector,self.insertTarget,self.insertLabel=frame,title,hint,selector,target,labelInput end
function News:OnInitialize()
 local UI=HolyStorm:GetModule("UI",true);local page=CreateFrame("Frame",nil,UI.content);self.page=page;self.activeType="ALL";self.modes={list=self:BuildList(page),detail=self:BuildDetail(page),editor=self:BuildEditor(page),preview=self:BuildPreview(page),diagnostics=self:BuildDiagnostics(page)};self:BuildInsertDialog(page);local message=page:CreateFontString(nil,"OVERLAY","GameFontNormal");message:SetPoint("BOTTOM",0,8);message:Hide();self.message=message
 HolyStorm.Rules:RegisterField("content.author",{type="string",get=function(context)return context.target and context.target.content and context.target.content.author end});HolyStorm.Rules:RegisterField("content.type",{type="string",get=function(context)return context.target and context.target.content and context.target.content.type end});HolyStorm.Rules:RegisterField("content.category",{type="string",get=function(context)return context.target and context.target.content and context.target.content.category end});HolyStorm.Rules:RegisterField("content.priority",{type="string",get=function(context)return context.target and context.target.content and context.target.content.priority end});HolyStorm.Rules:RegisterField("content.status",{type="string",get=function(context)return context.target and context.target.content and context.target.content.status end});HolyStorm.Rules:RegisterField("content.read",{type="boolean",get=function(context)return context.target and context.target.content and not HolyStorm.Content:IsUnread(context.target.content)end})
 HolyStorm.Content:RegisterOpenHandler("*",function(entry)HolyStorm.UI:ShowPage("news");News:Open(entry)end);HolyStorm.UI:RegisterPage("news",page,L["TITLE"],function()News:RenderList()end);HolyStorm.UI:AddNavigation("news",2,"Interface\\Icons\\INV_Misc_Note_05",L["TITLE"],L["DESCRIPTION"],function()HolyStorm.UI:ShowPage("news")end)
 if HolyStorm.UI.RegisterDashboardProvider then HolyStorm.UI:RegisterDashboardProvider("content",function()local entries={};if not HolyStorm.Content:IsEnabled()then return entries,L["MODULE_DISABLED"]end;for _,entry in ipairs(HolyStorm.Content:List())do if entry.status=="PUBLISHED"and entry.type~="GUIDE"and#entries<5 then local contentId=entry.id;entries[#entries+1]={title=entry.title,summary=string.format(L["DASHBOARD_META"],entry.author or L["UNKNOWN"],date("%d.%m.%Y",entry.modifiedAt)),icon=entry.icon,onClick=function()HolyStorm.Content:Open(contentId)end}end end;return entries end)end
end
function News:OnEnable()local guildId=HolyStorm.Content:GetGuildId();if guildId then HolyStorm.Tasks:Queue("Content.Migrate",{triggerSource="CONTENT_ENABLE",metadata={guildId=guildId}})end;if HolyStorm.Content:IsEnabled()then HolyStorm.Sync:Discover("content",nil,{reason="CONTENT_ENABLE",priority=92})end;for _,event in ipairs({"HS_CONTENT_CREATED","HS_CONTENT_UPDATED","HS_CONTENT_PUBLISHED","HS_CONTENT_ARCHIVED","HS_CONTENT_DELETED","HS_CONTENT_READ","HS_CONTENT_SYNC_UPDATED","HS_FILTER_UPDATED","HS_PERMISSIONS_STATE_UPDATED"})do HolyStorm.Events:Register(event,"content-ui",function()News:RefreshListIfVisible();if HolyStorm.UI.driver then HolyStorm.UI.driver:RefreshDashboardProviders()end end)end;HolyStorm.Events:Register("HS_CONTENT_LOADING","content-ui-loading",function()HolyStorm.UI:ShowPage("news");News:ShowMessage("LOADING")end);HolyStorm.Events:Register("HS_CONTENT_OPEN_FAILED","content-ui-failed",function(_,_,reason)HolyStorm.UI:ShowPage("news");News:ShowMessage((reason=="PERMISSION"or reason=="VISIBILITY")and"ERROR_PERMISSION"or"ERROR_NOT_FOUND")end)end
function News:OnDisable()HolyStorm.Events:UnregisterOwner("content-ui");HolyStorm.Events:UnregisterOwner("content-ui-loading");HolyStorm.Events:UnregisterOwner("content-ui-failed")end
end)
