local addonVersion="3.0.0"
local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm")
local Rules={version=addonVersion,fields={},operators={},maxDepth=8,maxChildren=32,maxListValues=100,Result={PASS="PASS",FAIL="FAIL",UNKNOWN="UNKNOWN"}}
local function lower(v)return string.lower(tostring(v or""))end
local function equals(a,b)if type(a)=="number"or type(b)=="number"then return tonumber(a)~=nil and tonumber(a)==tonumber(b)end;return a==b end
local function inList(a,b)if type(b)~="table"then return false end;for _,v in pairs(b)do if equals(a,v)then return true end end;return false end
Rules.operators["="]=equals;Rules.operators["!="]=function(a,b)return not equals(a,b)end
Rules.operators[">"]=function(a,b)return tonumber(a)and tonumber(b)and tonumber(a)>tonumber(b)or false end;Rules.operators[">="]=function(a,b)return tonumber(a)and tonumber(b)and tonumber(a)>=tonumber(b)or false end
Rules.operators["<"]=function(a,b)return tonumber(a)and tonumber(b)and tonumber(a)<tonumber(b)or false end;Rules.operators["<="]=function(a,b)return tonumber(a)and tonumber(b)and tonumber(a)<=tonumber(b)or false end
Rules.operators.between=function(a,b)local lo,hi=type(b)=="table"and tonumber(b[1]),type(b)=="table"and tonumber(b[2]);return tonumber(a)and lo and hi and tonumber(a)>=lo and tonumber(a)<=hi or false end
Rules.operators.not_between=function(a,b)return not Rules.operators.between(a,b)end;Rules.operators.contains=function(a,b)return lower(a):find(lower(b),1,true)~=nil end;Rules.operators.not_contains=function(a,b)return not Rules.operators.contains(a,b)end
Rules.operators.starts_with=function(a,b)return lower(a):sub(1,#lower(b))==lower(b)end;Rules.operators.ends_with=function(a,b)local x,y=lower(a),lower(b);return y==""or x:sub(-#y)==y end
Rules.operators["in"]=inList;Rules.operators.not_in=function(a,b)return not inList(a,b)end;Rules.operators["true"]=function(a)return a==true end;Rules.operators["false"]=function(a)return a==false end;Rules.operators.exists=function(a)return a~=nil end;Rules.operators.not_exists=function(a)return a==nil end
Rules.operators.range=Rules.operators.between;Rules.operators.in_list=Rules.operators["in"];Rules.operators.not_in_list=Rules.operators.not_in;Rules.operators.is_true=Rules.operators["true"];Rules.operators.is_false=Rules.operators["false"]

function Rules:RegisterField(id,definition)if type(id)~="string"or not id:match("^[%w%._]+$")or type(definition)~="table"or type(definition.get)~="function"then return false,"INVALID_FIELD"end;self.fields[id]=definition;if HolyStorm.Events then HolyStorm.Events:Emit("HS_RULE_PROVIDER_REGISTERED",id)end;return true end
function Rules:GetFields()return HolyStorm.Utils.DeepCopy(self.fields)end
function Rules:GetFieldValue(id,context,node)local field=self.fields[id];if not field then return nil,"UNKNOWN_FIELD:"..tostring(id)end;local c={accountUUID=context.accountUUID or context.playerId,characterUUID=context.characterUUID or context.guid,character=context.character,player=context.player,guild=context.guild,member=context.member,target=context.target,argument=node and(node.argument or node.value)};local ok,value,reason=HolyStorm.Utils.SafeCall("rule.field:"..id,field.get,c,node);if ok then if value==nil then return nil,reason or"MISSING_DATA:"..id end;return value,nil end;return nil,tostring(value)end
function Rules:GetDependencies(node)local found={};local function walk(current)if type(current)~="table"then return end;if current.field then local provider=self.fields[current.field];for _,dependency in ipairs(provider and provider.dependencies or{})do found[dependency]=true end end;for _,child in ipairs(current.children or{})do walk(child)end end;walk(node);local result={};for dependency in pairs(found)do result[#result+1]=dependency end;table.sort(result);return result end
function Rules:Validate(node,depth,count)
 depth=depth or 0;count=count or{value=0};if type(node)~="table"then return false,"RULE_NOT_TABLE"end;count.value=count.value+1;if count.value>256 then return false,"RULE_TOO_LARGE"end;if depth>self.maxDepth then return false,"RULE_TOO_DEEP"end
 if node.logic then local logic=string.upper(tostring(node.logic));if logic~="AND"and logic~="OR"and logic~="NOT"then return false,"INVALID_LOGIC"end;if type(node.children)~="table"or#node.children==0 or#node.children>self.maxChildren or(logic=="NOT"and#node.children~=1)then return false,"INVALID_CHILDREN"end;for _,child in ipairs(node.children)do local ok,err=self:Validate(child,depth+1,count);if not ok then return false,err end end;return true end
 if type(node.field)~="string"or not self.fields[node.field]then return false,"UNKNOWN_FIELD:"..tostring(node.field)end;local op=node.operator or"=";if not self.operators[op]then return false,"UNKNOWN_OPERATOR:"..tostring(op)end;local kind=self.fields[node.field].type;local allowed=kind=="boolean"and{["="]=1,["!="]=1,["true"]=1,["false"]=1,exists=1,not_exists=1}or kind=="number"and{["="]=1,["!="]=1,[">"]=1,[">="]=1,["<"]=1,["<="]=1,between=1,not_between=1,exists=1,not_exists=1}or kind=="string"and{["="]=1,["!="]=1,contains=1,not_contains=1,starts_with=1,ends_with=1,["in"]=1,not_in=1,exists=1,not_exists=1};if allowed and not allowed[op]then return false,"INVALID_OPERATOR_FOR_TYPE:"..op end;if op~="true"and op~="false"and op~="exists"and op~="not_exists"and node.value==nil then return false,"MISSING_VALUE"end;if(op=="between"or op=="not_between"or op=="in"or op=="not_in")and(type(node.value)~="table"or#node.value>self.maxListValues)then return false,"INVALID_VALUE"end;return true
end
function Rules:ValidatePortable(node,depth,count)
 depth=depth or 0;count=count or{value=0};if type(node)~="table"then return false,"RULE_NOT_TABLE"end;count.value=count.value+1;if count.value>256 then return false,"RULE_TOO_LARGE"end;if depth>self.maxDepth then return false,"RULE_TOO_DEEP"end;if node.logic then local logic=string.upper(tostring(node.logic));if logic~="AND"and logic~="OR"and logic~="NOT"then return false,"INVALID_LOGIC"end;if type(node.children)~="table"or#node.children==0 or#node.children>self.maxChildren or(logic=="NOT"and#node.children~=1)then return false,"INVALID_CHILDREN"end;for _,child in ipairs(node.children)do local ok,reason=self:ValidatePortable(child,depth+1,count);if not ok then return false,reason end end;return true end;if type(node.field)~="string"or not node.field:match("^[%w%._]+$")then return false,"INVALID_FIELD"end;local operator=node.operator or"=";if not self.operators[operator]then return false,"UNKNOWN_OPERATOR:"..tostring(operator)end;if operator~="true"and operator~="false"and operator~="exists"and operator~="not_exists"and node.value==nil then return false,"MISSING_VALUE"end;if(operator=="between"or operator=="not_between"or operator=="in"or operator=="not_in")and(type(node.value)~="table"or#node.value>self.maxListValues)then return false,"INVALID_VALUE"end;return true
end
-- DE: Der Evaluator verarbeitet nur deklarative, validierte Knoten. EN: The
-- evaluator processes declarative validated nodes only; dynamic code is forbidden.
function Rules:EvaluateDetailed(node,context,trace)
 trace=trace or{};local PASS,FAIL,UNKNOWN=self.Result.PASS,self.Result.FAIL,self.Result.UNKNOWN;local valid,validationError=self:Validate(node);if not valid then trace[#trace+1]={kind="error",error=validationError,status=UNKNOWN,result=false};HolyStorm.Logger:Write("WARN","Rules","validation","Invalid rule",{error=validationError});return UNKNOWN,trace end
 local function evaluate(current)
  if current.logic then local logic=string.upper(current.logic);local status
   if logic=="NOT"then local child=evaluate(current.children[1]);status=child==PASS and FAIL or child==FAIL and PASS or UNKNOWN
   elseif logic=="OR"then status=FAIL;for _,nodeChild in ipairs(current.children)do local child=evaluate(nodeChild);if child==PASS then status=PASS elseif child==UNKNOWN and status~=PASS then status=UNKNOWN end end
   else status=PASS;for _,nodeChild in ipairs(current.children)do local child=evaluate(nodeChild);if child==FAIL then status=FAIL elseif child==UNKNOWN and status~=FAIL then status=UNKNOWN end end end
   trace[#trace+1]={kind="group",logic=logic,status=status,result=status==PASS};return status
  end
  local actual,err=self:GetFieldValue(current.field,context,current);local status;if err then status=UNKNOWN else status=self.operators[current.operator or"="](actual,current.value)and PASS or FAIL end;trace[#trace+1]={kind="condition",field=current.field,operator=current.operator or"=",expected=current.value,actual=actual,status=status,result=status==PASS,error=err};return status
 end
 local ok,status=HolyStorm.Utils.SafeCall("rule.evaluate",evaluate,node);if not ok then HolyStorm.Logger:Write("ERROR","Rules","evaluation","Unexpected rule evaluation error",{error=tostring(status)});trace[#trace+1]={kind="error",error=tostring(status),status=UNKNOWN,result=false};return UNKNOWN,trace end;HolyStorm.Logger:Write("DEBUG","Rules","evaluation","Rule evaluated",{result=status});return status,trace
end
function Rules:Evaluate(node,context,trace)local status,details=self:EvaluateDetailed(node,context,trace);return status==self.Result.PASS,details,status end
local function walk(node,demands)if type(node)~="table"then return end;local argument=tonumber(node.argument or node.value);if(node.field=="quest.completed"or node.field=="questCompleted")and argument then demands.quests[argument]=true elseif(node.field=="achievement.completed"or node.field=="achievementCompleted")and argument then demands.achievements[argument]=true end;for _,child in ipairs(node.children or{})do walk(child,demands)end end
function Rules:RebuildDemands()local d={quests={},achievements={}};local global=HolyStorm.db.global;for _,rule in pairs(global.rules and global.rules.global or{})do if rule.enabled~=false then walk(rule.root or rule.rules,d)end end;for _,filter in pairs(global.filters and global.filters.global or{})do if filter.enabled~=false then walk(filter.root or filter.rules,d)end end;for _,group in pairs(global.permissions and global.permissions.groups or{})do for _,rule in pairs(group.rules or{})do if type(rule)=="table"then walk(rule,d)end end end;global.filters.demands=d;HolyStorm.Events:Emit("HS_RULE_DEMANDS_CHANGED",HolyStorm.Utils.DeepCopy(d));return d end
function Rules:CaptureDemands(guid)guid=guid or UnitGUID("player");if not guid then return false end;local d=HolyStorm.db.global.filters.demands or{};local result={quests={},achievements={},updatedAt=HolyStorm.Utils.Now()};for id in pairs(d.quests or{})do if C_QuestLog and C_QuestLog.IsQuestFlaggedCompleted then result.quests[id]=C_QuestLog.IsQuestFlaggedCompleted(id)==true end end;for id in pairs(d.achievements or{})do if GetAchievementInfo then local _,_,_,completed=GetAchievementInfo(id);result.achievements[id]=completed==true end end;return HolyStorm.Data.CharacterStore:Upsert(guid,{demands=result},"blizzard")end
function Rules:Initialize()
 local function character(key)return function(x)return x.character and x.character[key]end end
 local fields={
  ["character.level"]={get=character("level"),type="number"},["character.class"]={get=character("classFile"),type="string"},["character.spec"]={get=function(x)return x.character and x.character.stats and x.character.stats.spec and(x.character.stats.spec.id or x.character.stats.spec.name)end,type="string"},["character.role"]={get=function(x)return x.character and x.character.stats and x.character.stats.spec and x.character.stats.spec.role end,type="string"},["guild.rank"]={get=function(x)return(x.member and x.member.rank)or(x.character and x.character.guildRank)end,type="string"},["guild.rankIndex"]={get=function(x)return(x.member and x.member.rankIndex)or(x.character and x.character.guildRankIndex)end,type="number"},["equipment.itemLevel"]={get=character("itemLevel"),type="number"},["player.online"]={get=function(x)return x.member and x.member.online or false end,type="boolean"},["player.afk"]={get=function(x)return x.member and(x.member.status=="AFK"or x.member.status==1)or false end,type="boolean"},["player.dnd"]={get=function(x)return x.member and(x.member.status=="DND"or x.member.status==2)or false end,type="boolean"},["holystorm.version"]={get=function(x)return x.character and x.character.addon and x.character.addon.version end,type="string"},["character.maxLevel"]={get=function(x)local max=GetMaxLevelForPlayerExpansion and GetMaxLevelForPlayerExpansion()or GetMaxPlayerLevel and GetMaxPlayerLevel()or 80;return(x.character and x.character.level or 0)==max end,type="boolean"},["character.mainTwinkStatus"]={get=function(x)local guid=x.character and x.character.guid;local account=guid and HolyStorm.TwinkCore and HolyStorm.TwinkCore:GetAccountUUIDForCharacter(guid);local main=account and HolyStorm.TwinkCore:GetAccountMain(account);return guid and(main==guid and"MAIN"or"TWINK")or nil end,type="string"},["profile.preferredRole"]={get=function(x)return x.character and x.character.profile and x.character.profile.preferredRole end,type="string"},["profile.raidInterest"]={get=function(x)return x.character and x.character.profile and x.character.profile.raidInterest end,type="string"},["mythicplus.rating"]={get=function(x)return x.character and x.character.mythicPlus and x.character.mythicPlus.overallScore end,type="number"},["raid.progress"]={get=function(x)return x.character and x.character.raidLockouts and x.character.raidLockouts.bestProgress and x.character.raidLockouts.bestProgress.killed end,type="number"},["delves.status"]={get=function(x)return x.character and x.character.delves and x.character.delves.weeklyProgress end},["quest.completed"]={get=function(x)return x.character and x.character.demands and x.character.demands.quests and x.character.demands.quests[tonumber(x.argument)]end,type="boolean",onDemand="quest"},["achievement.completed"]={get=function(x)return x.character and x.character.demands and x.character.demands.achievements and x.character.demands.achievements[tonumber(x.argument)]end,type="boolean",onDemand="achievement"},
 }
 local dependencies={identity={"character.level","character.class","character.maxLevel"},stats={"character.spec","character.role"},roster={"guild.rank","guild.rankIndex","player.online","player.afk","player.dnd"},equipment={"equipment.itemLevel"},addon={"holystorm.version"},twinks={"character.mainTwinkStatus"},profile={"profile.preferredRole","profile.raidInterest"},mythicPlus={"mythicplus.rating"},raid={"raid.progress"},delves={"delves.status"},demands={"quest.completed","achievement.completed"}};for dependency,ids in pairs(dependencies)do for _,id in ipairs(ids)do if fields[id]then fields[id].dependencies={dependency}end end end
 fields["character.maxLevel"].get=function(x)if not(x.character and x.character.level)then return nil,"MISSING_LEVEL"end;local max=GetMaxLevelForPlayerExpansion and GetMaxLevelForPlayerExpansion()or GetMaxPlayerLevel and GetMaxPlayerLevel()or 80;return x.character.level==max end
 fields["player.online"].get=function(x)return x.member and x.member.online end;fields["player.afk"].get=function(x)if not x.member then return nil,"MISSING_ROSTER"end;return x.member.status=="AFK"or x.member.status==1 end;fields["player.dnd"].get=function(x)if not x.member then return nil,"MISSING_ROSTER"end;return x.member.status=="DND"or x.member.status==2 end
 for id,definition in pairs(fields)do self:RegisterField(id,definition)end;local aliases={level="character.level",class="character.class",spec="character.spec",role="character.role",guildRank="guild.rank",itemLevel="equipment.itemLevel",online="player.online",addonVersion="holystorm.version",maxLevel="character.maxLevel",preferredRole="profile.preferredRole",mythicScore="mythicplus.rating",raidProgress="raid.progress",delveStatus="delves.status",questCompleted="quest.completed",achievementCompleted="achievement.completed"};for alias,id in pairs(aliases)do self.fields[alias]=self.fields[id]end;self:RebuildDemands()
end
HolyStorm.Rules,HolyStorm.RuleEngine=Rules,Rules
Rules.RegisterConditionProvider=Rules.RegisterField
