local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm")
local L=LibStub("AceLocale-3.0"):GetLocale("Holy_Storm_GuildRoster")
local GM=HolyStorm.GuildManagement
local UI=GM.UI
local C

local activityTypes={false,"ONLINE_SESSION","GUILD_CHAT","RAID_ENCOUNTER","MYTHICPLUS_RUN","EVENT_ATTENDANCE"}
local function characterName(guid)local character=guid and HolyStorm.Data.CharacterStore:Get(guid);local guild=HolyStorm.Data.GuildStore:GetCurrent();local member=guild and guild.roster and guild.roster[guid];return(member and member.name)or(character and(character.fullName or character.name))or guid or L["GUILD_UNKNOWN"]end
local function formatTime(value)return value and value>0 and date("%Y-%m-%d %H:%M",value)or L["GUILD_NEVER"]end
local function duration(value)value=math.max(0,tonumber(value)or 0);local hours=math.floor(value/3600);local minutes=math.floor((value%3600)/60);return string.format(L["GUILD_ACTIVITY_DURATION"],hours,minutes)end
local function cycle(values,current)local index=1;for i,value in ipairs(values)do if value==current then index=i;break end end;return values[index%#values+1]end
local function labelType(value)return value and(L["GUILD_ACTIVITY_TYPE_"..value]or value)or L["GUILD_ALL"]end
local function labelProvider(value)return value and(L["GUILD_ACTIVITY_PROVIDER_"..value:upper():gsub("%-","_")]or value)or L["GUILD_ACTIVITY_ALL_PROVIDERS"]end
local function groupDescription(metadata)local classification=metadata.guildClassification;if not classification then return""end;return string.format(L["GUILD_ACTIVITY_GROUP_FORMAT"],L["GUILD_ACTIVITY_GROUP_"..classification]or classification,metadata.guildMembers or 0,metadata.groupSize or 0)end
local function historyDescription(row)
 local metadata=row.metadata or{};if row.type=="ONLINE_SESSION"then return duration(row.duration)..(row.status=="RECOVERED"and" ("..L["GUILD_ACTIVITY_RECOVERED"]..")"or"")elseif row.type=="GUILD_CHAT"then return string.format(L["GUILD_ACTIVITY_CHAT_MESSAGES"],metadata.count or 0)elseif row.type=="RAID_ENCOUNTER"then return string.format(L["GUILD_ACTIVITY_RAID_DETAIL"],metadata.instanceName or"",metadata.encounterName or"",metadata.success and L["GUILD_ACTIVITY_SUCCESS"]or L["GUILD_ACTIVITY_FAILED"],groupDescription(metadata))elseif row.type=="MYTHICPLUS_RUN"then local timed=metadata.timed==true and L["GUILD_ACTIVITY_TIMED"]or metadata.timed==false and L["GUILD_ACTIVITY_NOT_TIMED"]or L["GUILD_UNKNOWN"];return string.format(L["GUILD_ACTIVITY_MYTHICPLUS_DETAIL"],metadata.dungeonName or"",tostring(metadata.keystoneLevel or"?"),timed,groupDescription(metadata))elseif row.type=="EVENT_ATTENDANCE"then return tostring(metadata.attendanceState or"")end;return""
end
local function filterValues()
 local providers={false};for _,provider in ipairs(GM.Activity:GetProviders())do providers[#providers+1]=provider.id end
 local characters={false};local account=UI.activitySelectedAccount;local shard=account and HolyStorm.Data.GuildActivityStore:GetShard(account);for guid in pairs(shard and shard.characters or{})do characters[#characters+1]=guid end;table.sort(characters,function(a,b)if a==false then return true elseif b==false then return false end;return characterName(a)<characterName(b)end);return providers,characters
end

function UI:BuildActivity(parent)
 C=HolyStorm.UIComponents;local frame=CreateFrame("Frame",nil,parent);local root=C:CreateColumn(frame,{frame=frame,gap=8,padding=8});local toolbar=C:CreateRow(frame,{gap=6})
 for _,days in ipairs({7,30,90})do local selectedDays=days;toolbar:Add(C:CreateButton(toolbar.frame,{text=string.format(L["GUILD_ACTIVITY_DAYS"],days),width=72,onClick=function()UI.activityDays=selectedDays;UI:RefreshActivity()end}),{width=72})end
 self.activityTypeButton=C:CreateButton(toolbar.frame,{text=L["GUILD_ALL"],width=160,onClick=function()UI.activityTypeFilter=cycle(activityTypes,UI.activityTypeFilter);UI:RefreshActivity()end});toolbar:Add(self.activityTypeButton,{width=160})
 self.activityProviderButton=C:CreateButton(toolbar.frame,{text=L["GUILD_ACTIVITY_ALL_PROVIDERS"],width=150,onClick=function()local providers=filterValues();UI.activityProviderFilter=cycle(providers,UI.activityProviderFilter);UI:RefreshActivity()end});toolbar:Add(self.activityProviderButton,{width=150})
 self.activityCharacterButton=C:CreateButton(toolbar.frame,{text=L["GUILD_ACTIVITY_ALL_CHARACTERS"],width=180,onClick=function()local _,characters=filterValues();UI.activityCharacterFilter=cycle(characters,UI.activityCharacterFilter);UI:RefreshActivity()end});toolbar:Add(self.activityCharacterButton,{weight=1,minWidth=150});root:Add(toolbar,{height=28})
 local overview;overview=C:CreateTable(frame,{emptyText=L["GUILD_ACTIVITY_EMPTY"],columns={{id="characterUUID",weight=1.4,minWidth=120,title=L["GUILD_ACTIVITY_ACCOUNT"],value=function(row)return characterName(row.characterUUID)end},{id="lastActivity",width=130,title=L["GUILD_ACTIVITY_LAST_ACTIVITY"],value=function(row)return formatTime(row.lastActivity)end},{id="lastSeen",width=130,title=L["GUILD_ACTIVITY_LAST_SEEN"],value=function(row)return formatTime(row.lastSeen)end},{id="onlineDuration",width=85,title=L["GUILD_ACTIVITY_ONLINE"],value=function(row)return duration(row.onlineDuration)end},{id="guildChatCount",width=70,title=L["GUILD_ACTIVITY_CHAT"],align="RIGHT"},{id="raidParticipation",width=65,title=L["GUILD_ACTIVITY_RAIDS"],align="RIGHT"},{id="mythicPlusParticipation",width=65,title=L["GUILD_ACTIVITY_MYTHICPLUS"],align="RIGHT"},{id="absence",width=90,title=L["GUILD_ABSENCES"]}},onRowClick=function(row)if UI.activitySelectedAccount~=row.accountUUID then UI.activityCharacterFilter=nil end;UI.activitySelectedAccount=row.accountUUID;overview:SetSelection(row.accountUUID);UI:RefreshActivity()end,isRowSelected=function(row)return UI.activitySelectedAccount==row.accountUUID end,rowTooltip=function(row)return row.approximate and L["GUILD_ACTIVITY_APPROXIMATE"]or nil end});root:Add(overview,{weight=1,minHeight=165});self.activityOverview=overview
 self.activityDetailLabel=C:CreateText(frame,{text=L["GUILD_ACTIVITY_SELECT_ACCOUNT"],font="GameFontNormal",wrap=true});root:Add(self.activityDetailLabel,{height=38})
 local history=C:CreateTable(frame,{emptyText=L["GUILD_ACTIVITY_HISTORY_EMPTY"],columns={{id="occurredAt",width=135,title=L["GUILD_ACTIVITY_TIME"],value=function(row)return formatTime(row.occurredAt or row.endedAt or row.startedAt)end},{id="type",width=135,title=L["GUILD_ACTIVITY_TYPE"],value=function(row)return labelType(row.type)end},{id="characterUUID",weight=1,minWidth=110,title=L["GUILD_ACTIVITY_CHARACTER"],value=function(row)return characterName(row.characterUUID)end},{id="providerId",width=105,title=L["GUILD_ACTIVITY_PROVIDER"],value=function(row)return labelProvider(row.providerId)end},{id="description",weight=2,minWidth=160,title=L["GUILD_ACTIVITY_DETAILS"],truncate=true,value=historyDescription}},rowTooltip=historyDescription});root:Add(history,{weight=1,minHeight=145});self.activityHistory=history;self.activityDays=self.activityDays or 30;self:RefreshActivity();return frame
end

function UI:RefreshActivity()
 if not self.activityOverview then return end;local rows=GM.Activity:GetOverview(self.activityDays or 30);for _,row in ipairs(rows)do local active,upcoming=GM.Absences:GetForAccount(row.accountUUID);row.absence=active and L["GUILD_ABSENCE_ACTIVE"]or upcoming and L["GUILD_ABSENCE_UPCOMING"]or"" end
 self.activityOverview:SetData(rows);if self.activityAccountFilter then if self.activitySelectedAccount~=self.activityAccountFilter then self.activityCharacterFilter=nil end;self.activitySelectedAccount=self.activityAccountFilter;self.activityAccountFilter=nil end;if self.activitySelectedAccount then self.activityOverview:SetSelection(self.activitySelectedAccount)end
 self.activityTypeButton:SetText(labelType(self.activityTypeFilter));self.activityProviderButton:SetText(labelProvider(self.activityProviderFilter));self.activityCharacterButton:SetText(self.activityCharacterFilter and characterName(self.activityCharacterFilter)or L["GUILD_ACTIVITY_ALL_CHARACTERS"]);self:RefreshActivityDetail()
end

function UI:RefreshActivityDetail()
 if not self.activityHistory then return end;local accountUUID=self.activitySelectedAccount;if not accountUUID then self.activityDetailLabel:SetText(L["GUILD_ACTIVITY_SELECT_ACCOUNT"]);self.activityHistory:SetData({});return end;local stamp=HolyStorm.Utils.Now();local aggregate,reason=GM.Activity:GetAggregate(accountUUID,stamp-(self.activityDays or 30)*86400,stamp,{characterUUID=self.activityCharacterFilter});if not aggregate then self.activityDetailLabel:SetText(L["GUILD_ACTIVITY_UNAVAILABLE"]..": "..tostring(reason));self.activityHistory:SetData({});return end
 local summary=HolyStorm.Data.GuildActivityStore:GetSummary(accountUUID);local count=0;for _ in pairs(summary and summary.characters or{})do count=count+1 end;self.activityDetailLabel:SetText(string.format(L["GUILD_ACTIVITY_DETAIL_SUMMARY"],characterName(summary and summary.referenceCharacterUUID),count,duration(aggregate.onlineDuration),aggregate.guildChatCount,aggregate.raidParticipation,aggregate.mythicPlusParticipation)..(aggregate.approximate and" · "..L["GUILD_ACTIVITY_APPROXIMATE"]or""))
 local history=GM.Activity:GetHistory(accountUUID,stamp-(self.activityDays or 30)*86400,stamp,{activityType=self.activityTypeFilter,providerId=self.activityProviderFilter,characterUUID=self.activityCharacterFilter,limit=200});self.activityHistory:SetData(history or{})
end
