local HolyStorm=LibStub("AceAddon-3.0"):GetAddon("Holy_Storm")
local L=LibStub("AceLocale-3.0"):GetLocale("Holy_Storm_GuildRoster")
local GM=HolyStorm.GuildManagement
local UI={version="1.0.0",built={},selected="notes",absenceState="ACTIVE"}
local C
local function now()return HolyStorm.Utils.Now()end
local function formatDate(value)return value and date("%Y-%m-%d",value)or"-"end
local function parseDate(value)value=tostring(value or"");local y,m,d=value:match("^(%d%d%d%d)%-(%d%d)%-(%d%d)$");if not y then return nil end;local stamp=time({year=tonumber(y),month=tonumber(m),day=tonumber(d),hour=12});return stamp and date("%Y-%m-%d",stamp)==value and stamp or nil end
local function characterName(guid)local character=guid and HolyStorm.Data.CharacterStore:Get(guid);local guild=HolyStorm.Data.GuildStore:GetCurrent();local member=guild and guild.roster and guild.roster[guid];return(member and member.name)or(character and(character.fullName or character.name))or guid or"-"end
local function characters()return HolyStorm.PolicyUI and HolyStorm.PolicyUI:CharacterItems()or{}end
local function button(parent,text,width,callback)return C:CreateButton(parent,{text=text,width=width,onClick=callback})end
local function input(parent,width)return C:CreateEditBox(parent,{width=width,height=24})end
local function label(parent,text,x,y)local value=C:CreateText(parent,{text=text,font="GameFontNormalSmall"});value.frame:SetPoint("TOPLEFT",x,y);return value end
local function cycle(values,current)local index=1;for i,value in ipairs(values)do if value==current then index=i;break end end;return values[index%#values+1]end
local function confirm(text,callback)
 if not StaticPopupDialogs or not StaticPopup_Show then return false end;StaticPopupDialogs.HOLYSTORM_GUILD_MANAGEMENT_CONFIRM={text="%s",button1=L["GUILD_CONFIRM"],button2=L["GUILD_CANCEL"],OnAccept=function(_,data)if data then data()end end,timeout=0,whileDead=true,hideOnEscape=true};StaticPopup_Show("HOLYSTORM_GUILD_MANAGEMENT_CONFIRM",text,nil,callback);return true
end
function UI:SelectFeature(id)
 local feature=GM:GetFeature(id);if not feature then return false end;self.selected=id
 for featureId,frame in pairs(self.built)do frame:SetShown(featureId==id)end
 if not self.built[id]then local built=feature.build(self.content,self);local frame=type(built)=="table"and built.frame or built;if not frame then return false end;frame:SetAllPoints(self.content);self.built[id]=frame end
 for featureId,frame in pairs(self.built)do frame:SetShown(featureId==id)end;if feature.refresh then feature.refresh()end;if self.tabs and self.tabs.selected~=id then self.tabs:SelectTab(id,true)end;return true
end
function UI:Build(parent)
 local frame=CreateFrame("Frame",nil,parent);local tabs=C:CreateTabGroup(frame,{wrapTabs=true,minTabWidth=150});if not tabs then return frame end;tabs.frame:SetAllPoints();local definitions={};for _,feature in ipairs(GM:GetFeatures())do definitions[#definitions+1]={value=feature.id,text=feature.title,icon=feature.icon}end;tabs:SetTabs(definitions);tabs:SetCallback("OnGroupSelected",function(_,_,id)UI:SelectFeature(id)end);self.frame,self.tabs,self.content=frame,tabs,tabs:GetContentFrame();return frame
end
function UI:Refresh()if not self.built[self.selected]then self:SelectFeature(self.selected)else local feature=GM:GetFeature(self.selected);if feature and feature.refresh then feature.refresh()end end end
function UI:Initialize()
 C=HolyStorm.UIComponents;HolyStorm.UI:RegisterView({id="guildManagement",owner="GuildManagement",moduleId="GuildManagement",order=4,title=L["GUILD_MANAGEMENT_TITLE"],description=L["GUILD_MANAGEMENT_DESCRIPTION"],navigation={order=4,icon="Interface\\Icons\\Achievement_GuildPerk_EverybodysFriend",title=L["GUILD_MANAGEMENT_TITLE"],description=L["GUILD_MANAGEMENT_DESCRIPTION"]},events={"HS_GUILD_NOTE_CREATED","HS_GUILD_NOTE_UPDATED","HS_GUILD_NOTE_DELETED","HS_GUILD_NOTE_SYNCED","HS_GUILD_NOTE_EXPIRATION","HS_GUILD_ABSENCE_CREATED","HS_GUILD_ABSENCE_UPDATED","HS_GUILD_ABSENCE_DELETED","HS_GUILD_ABSENCE_SYNCED","HS_ROSTER_UPDATED","HS_PERMISSIONS_STATE_UPDATED"},build=function(parent)return UI:Build(parent)end,refresh=function()return UI:Refresh()end})
 HolyStorm.Events:Register("HS_GUILD_MANAGEMENT_OPEN_REQUESTED","guild-management-ui",function(_,featureId,characterUUID,mode)UI.pendingCharacter=characterUUID;UI.pendingMode=mode;if featureId=="absences"then UI.absenceOwnerFilter=GM:GetAccountUUID(characterUUID)end;UI:SelectFeature(featureId or"notes");if featureId=="notes"and mode=="create"then UI:EditNote()end end)
end

function UI:NoteVisibilityLabel(value)return L["GUILD_NOTE_VISIBILITY_"..tostring(value)]or value end
function UI:NoteCategoryLabel(value)return L["GUILD_NOTE_CATEGORY_"..tostring(value)]or value end
function UI:BuildNotes(parent)
 local frame=CreateFrame("Frame",nil,parent);local layout=C:CreateColumn(frame,{gap=8,padding=8});layout.frame:SetAllPoints();local toolbar=C:CreateRow(frame,{gap=6});local subject;subject=HolyStorm.PolicyUI:CreateSelector(toolbar.frame,175,characters,function(value,item)UI.noteSubject=value;subject:SetValue(value,item.label);UI:RefreshNotes()end);subject:SetValue(self.pendingCharacter or UnitGUID("player"),characterName(self.pendingCharacter or UnitGUID("player")));self.noteSubject=subject:GetValue()
 local search=input(toolbar.frame,180);search.edit:SetScript("OnTextChanged",function(box,user)if user then UI.noteSearch=box:GetText();UI:RefreshNotes()end end)
 local create=button(toolbar.frame,L["GUILD_CREATE"],90,function()UI:EditNote()end);local editButton=button(toolbar.frame,L["GUILD_EDIT"],80,function()UI:EditNote(UI.noteSelected)end);local deleteButton=button(toolbar.frame,L["GUILD_DELETE"],80,function()local entry=UI.noteSelected;if entry then confirm(L["GUILD_CONFIRM_DELETE_NOTE"],function()GM.Notes:Delete(entry.noteId,entry.scope,entry.revision);UI.noteSelected=nil;UI:RefreshNotes()end)end end)
 toolbar:Add(subject,{width=210});toolbar:Add(search,{weight=1,min=130});toolbar:Add(create,{width=90});toolbar:Add(editButton,{width=80});toolbar:Add(deleteButton,{width=80});layout:Add(toolbar,{height=32});self.noteSubjectSelector=subject
 local tableView;tableView=C:CreateTable(frame,{emptyText=L["GUILD_NOTES_EMPTY"],columns={{id="scope",width=80,title=L["GUILD_COLUMN_SCOPE"],value=function(row)return L["GUILD_NOTE_SCOPE_"..row.scope]end},{id="subject",weight=1,minWidth=120,title=L["GUILD_COLUMN_PLAYER"],truncate=true,value=function(row)return characterName(row.subjectCharacterUUID)end},{id="category",width=115,title=L["GUILD_COLUMN_CATEGORY"],value=function(row)return UI:NoteCategoryLabel(row.category)end},{id="text",weight=2,minWidth=150,title=L["GUILD_COLUMN_NOTE"],truncate=true},{id="author",weight=1,minWidth=110,title=L["GUILD_COLUMN_AUTHOR"],value=function(row)return characterName(row.authorCharacterUUID)end},{id="modifiedAt",width=100,title=L["GUILD_COLUMN_MODIFIED"],value=function(row)return formatDate(row.modifiedAt)end},{id="expiresAt",width=100,title=L["GUILD_COLUMN_EXPIRES"],value=function(row)return row.expiresAt and formatDate(row.expiresAt)or L["GUILD_NEVER"]end}},onRowClick=function(row)UI.noteSelected=row;tableView:SetSelection(row.noteId);UI:RefreshNoteActions()end,isRowSelected=function(row)return UI.noteSelected and UI.noteSelected.noteId==row.noteId end,rowTooltip=function(row)return string.format(L["GUILD_NOTE_TOOLTIP"],UI:NoteVisibilityLabel(row.visibility),formatDate(row.createdAt),formatDate(row.modifiedAt))end});layout:Add(tableView,{weight=1,min=160});self.notesTable,self.noteCreate,self.noteEdit,self.noteDelete=tableView,create.button,editButton.button,deleteButton.button;self.pendingCharacter=nil;self:RefreshNotes();return frame
end
function UI:RefreshNoteActions()
 if not self.noteCreate then return end;local who=GM:Actor();self.noteCreate:SetEnabled(true);local entry=self.noteSelected;self.noteEdit:SetEnabled(entry~=nil and GM.Notes:CanMutate(entry,"edit",who.accountUUID,who.characterUUID));self.noteDelete:SetEnabled(entry~=nil and GM.Notes:CanMutate(entry,"delete",who.accountUUID,who.characterUUID))
end
function UI:RefreshNotes()
 if not self.notesTable then return end;if self.pendingCharacter then self.noteSubject=self.pendingCharacter;if self.noteSubjectSelector then self.noteSubjectSelector:SetValue(self.noteSubject,characterName(self.noteSubject))end;self.pendingCharacter=nil end;local accountUUID=GM:GetAccountUUID(self.noteSubject);local rows=GM.Notes:List({subjectAccountUUID=accountUUID,subjectCharacterUUID=accountUUID and nil or self.noteSubject,includeExpired=false});local searchText=string.lower(self.noteSearch or"");if searchText~=""then local filtered={};for _,entry in ipairs(rows)do if string.lower(entry.text or""):find(searchText,1,true)or string.lower(characterName(entry.subjectCharacterUUID)):find(searchText,1,true)then filtered[#filtered+1]=entry end end;rows=filtered end;self.notesTable:SetData(rows);self:RefreshNoteActions()
end
function UI:EditNote(entry)
 if not self.noteDialog then self:BuildNoteDialog()end;self.editingNote=entry;self.noteScope=entry and entry.scope or"PRIVATE";self.noteCategory=entry and entry.category or"GENERAL";self.noteVisibility=entry and entry.visibility or"PUBLIC";self.noteDialogSubject:SetValue(entry and entry.subjectCharacterUUID or self.noteSubject,characterName(entry and entry.subjectCharacterUUID or self.noteSubject));self.noteDialogText:SetText(entry and entry.text or"");self.noteDialogExpiration:SetText(entry and entry.expiresAt and formatDate(entry.expiresAt)or"");self.noteDialogScope:SetEnabled(entry==nil and GM:Can("guild-notes-create"));self.noteDialogVisibility:SetEnabled(entry==nil);self:RefreshNoteDialog();self.noteDialog:Show()
end
function UI:BuildNoteDialog()
 local dialog=CreateFrame("Frame",nil,self.frame,"BackdropTemplate");dialog:SetSize(620,310);dialog:SetPoint("CENTER");dialog:SetFrameStrata("DIALOG");dialog:SetBackdrop({bgFile="Interface\\DialogFrame\\UI-DialogBox-Background",edgeFile="Interface\\DialogFrame\\UI-DialogBox-Border",edgeSize=24,insets={left=8,right=8,top=8,bottom=8}});local title=C:CreateText(dialog,{text=L["GUILD_NOTE_EDITOR"],font="GameFontHighlightLarge"});title.frame:SetPoint("TOPLEFT",24,-24)
 local subject;subject=HolyStorm.PolicyUI:CreateSelector(dialog,210,characters,function(value,item)subject:SetValue(value,item.label)end);subject:SetPoint("TOPLEFT",8,-62);local scope=button(dialog,"",120,function()UI.noteScope=cycle({"PRIVATE","SHARED"},UI.noteScope);UI:RefreshNoteDialog()end);scope.frame:SetPoint("TOPLEFT",250,-66);local category=button(dialog,"",130,function()UI.noteCategory=cycle({"GENERAL","RAID","ORGANIZATION","RECRUITMENT","ATTENTION"},UI.noteCategory);UI:RefreshNoteDialog()end);category.frame:SetPoint("LEFT",scope.frame,"RIGHT",6,0);local visibility=button(dialog,"",130,function()UI.noteVisibility=cycle({"PUBLIC","RAID_LEADERSHIP","OFFICERS","LEADERSHIP"},UI.noteVisibility);UI:RefreshNoteDialog()end);visibility.frame:SetPoint("LEFT",category.frame,"RIGHT",6,0)
 local textBox=input(dialog,560);textBox.frame:SetPoint("TOPLEFT",30,-118);textBox.edit:SetMaxLetters(GM.Notes.maxText);local expiration=input(dialog,180);expiration.frame:SetPoint("TOPLEFT",30,-165);local hint=C:CreateText(dialog,{text=L["GUILD_DATE_HINT"],font="GameFontDisableSmall"});hint.frame:SetPoint("LEFT",expiration.frame,"RIGHT",10,0);local save=button(dialog,L["GUILD_SAVE"],100,function()UI:SaveNoteDialog()end);save.frame:SetPoint("BOTTOMRIGHT",-28,24);local cancel=button(dialog,L["GUILD_CANCEL"],100,function()dialog:Hide()end);cancel.frame:SetPoint("RIGHT",save.frame,"LEFT",-8,0);dialog:Hide();self.noteDialog,self.noteDialogSubject,self.noteDialogText,self.noteDialogExpiration,self.noteDialogScope,self.noteDialogCategory,self.noteDialogVisibility=dialog,subject,textBox.edit,expiration.edit,scope.button,category.button,visibility.button
 label(dialog,L["GUILD_FIELD_PLAYER"],30,-50);label(dialog,L["GUILD_FIELD_TEXT"],30,-105);label(dialog,L["GUILD_FIELD_EXPIRATION"],30,-152)
end
function UI:RefreshNoteDialog()self.noteDialogScope:SetText(L["GUILD_NOTE_SCOPE_"..self.noteScope]);self.noteDialogCategory:SetText(self:NoteCategoryLabel(self.noteCategory));self.noteDialogVisibility:SetText(self:NoteVisibilityLabel(self.noteVisibility));self.noteDialogVisibility:SetShown(self.noteScope=="SHARED")end
function UI:SaveNoteDialog()
 local entry=self.editingNote;local subjectGuid=self.noteDialogSubject:GetValue();local expirationText=self.noteDialogExpiration:GetText();local expiresAt=expirationText~=""and parseDate(expirationText)or nil;if expirationText~=""and not expiresAt then HolyStorm.Events:Emit("HS_UI_STATUS_REQUESTED",L["GUILD_ERROR_INVALID_EXPIRATION"]);return end;local draft={noteId=entry and entry.noteId,subjectCharacterUUID=subjectGuid,subjectAccountUUID=GM:GetAccountUUID(subjectGuid),category=self.noteCategory,text=self.noteDialogText:GetText(),visibility=self.noteVisibility,expiresAt=expiresAt,clearExpiration=expirationText==""};local ok,result;if self.noteScope=="PRIVATE"then ok,result=GM.Notes:SavePrivate(draft,entry and entry.revision or 0)else ok,result=GM.Notes:SaveShared(draft,entry and entry.revision or 0)end;if ok then self.noteDialog:Hide();self.noteSelected=result;self:RefreshNotes()else HolyStorm.Events:Emit("HS_UI_STATUS_REQUESTED",L["GUILD_ERROR_"..tostring(result)]or tostring(result))end
end

function UI:BuildAbsences(parent)
 local frame=CreateFrame("Frame",nil,parent);local layout=C:CreateColumn(frame,{gap=8,padding=8});layout.frame:SetAllPoints();local toolbar=C:CreateRow(frame,{gap=6});toolbar:Add(button(toolbar.frame,L["GUILD_ALL"],70,function()UI.absenceOwnerFilter=nil;UI:RefreshAbsences()end),{width=70});for _,state in ipairs({"ACTIVE","UPCOMING","PAST"})do local chosen=state;toolbar:Add(button(toolbar.frame,L["GUILD_ABSENCE_"..state],100,function()UI.absenceState=chosen;UI:RefreshAbsences()end),{width=100})end;local create=button(toolbar.frame,L["GUILD_CREATE"],90,function()UI:EditAbsence()end);local editButton=button(toolbar.frame,L["GUILD_EDIT"],80,function()UI:EditAbsence(UI.absenceSelected)end);local deleteButton=button(toolbar.frame,L["GUILD_CANCEL_ABSENCE"],120,function()local entry=UI.absenceSelected;if entry then confirm(L["GUILD_CONFIRM_DELETE_ABSENCE"],function()GM.Absences:Delete(entry.absenceId,entry.revision);UI.absenceSelected=nil;UI:RefreshAbsences()end)end end);toolbar:Add(create,{width=90});toolbar:Add(editButton,{width=80});toolbar:Add(deleteButton,{width=120});layout:Add(toolbar,{height=32})
 local tableView;tableView=C:CreateTable(frame,{emptyText=L["GUILD_ABSENCES_EMPTY"],columns={{id="player",weight=1,minWidth=130,title=L["GUILD_COLUMN_PLAYER"],value=function(row)return characterName(row.ownerCharacterUUID)end},{id="startAt",width=105,title=L["GUILD_COLUMN_START"],value=function(row)return formatDate(row.startAt)end},{id="endAt",width=105,title=L["GUILD_COLUMN_END"],value=function(row)return formatDate(row.endAt)end},{id="state",width=100,title=L["GUILD_COLUMN_STATUS"],value=function(row)return L["GUILD_ABSENCE_"..row.state]end},{id="duration",width=100,title=L["GUILD_COLUMN_DURATION"],value=function(row)return string.format(L["GUILD_DAYS"],math.max(1,math.floor((row.endAt-row.startAt)/86400)+1))end},{id="title",weight=2,minWidth=160,title=L["GUILD_COLUMN_REASON"],truncate=true,value=function(row)return row.title~=""and row.title or row.reason end}},onRowClick=function(row)UI.absenceSelected=row;tableView:SetSelection(row.absenceId);UI:RefreshAbsenceActions()end,isRowSelected=function(row)return UI.absenceSelected and UI.absenceSelected.absenceId==row.absenceId end,rowTooltip=function(row)return row.reason end});layout:Add(tableView,{weight=1,min=160});self.absencesTable,self.absenceCreate,self.absenceEdit,self.absenceDelete=tableView,create.button,editButton.button,deleteButton.button;self:RefreshAbsences();return frame
end
function UI:RefreshAbsenceActions()if not self.absenceCreate then return end;local who=GM:Actor();local draft={ownerAccountUUID=who.accountUUID};self.absenceCreate:SetEnabled(GM.Absences:CanMutate(draft,who.accountUUID,who.characterUUID));local entry=self.absenceSelected;local allowed=entry and GM.Absences:CanMutate(entry,who.accountUUID,who.characterUUID);self.absenceEdit:SetEnabled(allowed==true);self.absenceDelete:SetEnabled(allowed==true)end
function UI:RefreshAbsences()if not self.absencesTable then return end;self.absencesTable:SetData(GM.Absences:List({state=self.absenceState,ownerAccountUUID=self.absenceOwnerFilter,includeDeleted=self.absenceState=="PAST"}));self:RefreshAbsenceActions()end
function UI:EditAbsence(entry)
 if not self.absenceDialog then self:BuildAbsenceDialog()end;self.editingAbsence=entry;local who=GM:Actor();local canManageAny=GM:Can("guild-absences-manage-any",who.accountUUID,who.characterUUID);local requested=self.pendingCharacter;local requestedAccount=GM:GetAccountUUID(requested);local guid=entry and entry.ownerCharacterUUID or requested and(requestedAccount==who.accountUUID or canManageAny)and requested or who.characterUUID;self.absenceDialogOwner:SetValue(guid,characterName(guid));if entry or not canManageAny then UIDropDownMenu_DisableDropDown(self.absenceDialogOwner)else UIDropDownMenu_EnableDropDown(self.absenceDialogOwner)end;self.absenceStart:SetText(entry and formatDate(entry.startAt)or formatDate(now()));self.absenceEnd:SetText(entry and formatDate(entry.endAt)or formatDate(now()+86400));self.absenceTitle:SetText(entry and entry.title or"");self.absenceReason:SetText(entry and entry.reason or"");self.absenceDialog:Show()
end
function UI:BuildAbsenceDialog()
 local dialog=CreateFrame("Frame",nil,self.frame,"BackdropTemplate");dialog:SetSize(620,330);dialog:SetPoint("CENTER");dialog:SetFrameStrata("DIALOG");dialog:SetBackdrop({bgFile="Interface\\DialogFrame\\UI-DialogBox-Background",edgeFile="Interface\\DialogFrame\\UI-DialogBox-Border",edgeSize=24,insets={left=8,right=8,top=8,bottom=8}});local title=C:CreateText(dialog,{text=L["GUILD_ABSENCE_EDITOR"],font="GameFontHighlightLarge"});title.frame:SetPoint("TOPLEFT",24,-24);local owner;owner=HolyStorm.PolicyUI:CreateSelector(dialog,220,characters,function(value,item)owner:SetValue(value,item.label)end);owner:SetPoint("TOPLEFT",8,-60);local start=input(dialog,180);start.frame:SetPoint("TOPLEFT",30,-108);local finish=input(dialog,180);finish.frame:SetPoint("LEFT",start.frame,"RIGHT",30,0);local titleInput=input(dialog,540);titleInput.frame:SetPoint("TOPLEFT",30,-155);titleInput.edit:SetMaxLetters(GM.Absences.maxTitle);local reason=input(dialog,540);reason.frame:SetPoint("TOPLEFT",30,-202);reason.edit:SetMaxLetters(GM.Absences.maxReason);local save=button(dialog,L["GUILD_SAVE"],100,function()UI:SaveAbsenceDialog()end);save.frame:SetPoint("BOTTOMRIGHT",-28,24);local cancel=button(dialog,L["GUILD_CANCEL"],100,function()dialog:Hide()end);cancel.frame:SetPoint("RIGHT",save.frame,"LEFT",-8,0);dialog:Hide();self.absenceDialog,self.absenceDialogOwner,self.absenceStart,self.absenceEnd,self.absenceTitle,self.absenceReason=dialog,owner,start.edit,finish.edit,titleInput.edit,reason.edit
 label(dialog,L["GUILD_FIELD_PLAYER"],30,-50);label(dialog,L["GUILD_FIELD_START"],30,-95);label(dialog,L["GUILD_FIELD_END"],240,-95);label(dialog,L["GUILD_FIELD_TITLE"],30,-142);label(dialog,L["GUILD_FIELD_REASON"],30,-189)
end
function UI:SaveAbsenceDialog()
 local entry=self.editingAbsence;local guid=self.absenceDialogOwner:GetValue();local ok,result=GM.Absences:Save({absenceId=entry and entry.absenceId,ownerCharacterUUID=guid,ownerAccountUUID=GM:GetAccountUUID(guid),startAt=parseDate(self.absenceStart:GetText()),endAt=parseDate(self.absenceEnd:GetText()),title=self.absenceTitle:GetText(),reason=self.absenceReason:GetText()},entry and entry.revision or 0);if ok then self.absenceDialog:Hide();self.absenceSelected=result;self:RefreshAbsences()else HolyStorm.Events:Emit("HS_UI_STATUS_REQUESTED",L["GUILD_ERROR_"..tostring(result)]or tostring(result))end
end
GM.UI=UI
